### ISSUE TITLE
[BUG] Server Crash When Loading New Chunks

### ISSUE THREAD

**Issue by Xuwznln** [PluginBugs/Issues-ItemsAdder#1049]
**Describe the bug**
Server crashes when I tried to enter the new world, which has ia ores configured and was refreshed recently.

**To Reproduce**
1. Spawn a world that have custom ores configured.
2. Remove the world and regen chunks.
3. Enter the refreshed world and the server crashes.

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.4
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.1

**Additional context**
error log:
```
[19:51:21] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at dev.lone.itemsadder.n.z.a(SourceFile:117) ~[?:?]
	at dev.lone.itemsadder.Core.k.d.a(SourceFile:139) ~[?:?]
	at dev.lone.itemsadder.Core.k.d.populate(SourceFile:101) ~[?:?]
	at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:891) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:672) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[TTCW.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[TTCW.jar:git-Paper-782]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by LoneDev6** [comment]
is it the latest paper version?

**Comment by Xuwznln** [comment]
build 782, I removed the cache file(.nbt) in itemsadder, regeneration of new chunks is fine now.

**Comment by Xuwznln** [comment]
I wrongly configured an ore which I didn't found before. Simply re-checking the configs will help. Make sure the min_height is less than max_height.

**Comment by LoneDev6** [comment]
Thanks, I will show an error and avoid loading populators with min_height > max_height
