### ISSUE TITLE
[BUG] Error in console

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#1053]
**Describe the bug**
Errore in console

**To Reproduce**
Appare in chat quando avvio il server

[16:50:56 WARN]: [ItemsAdder] Plugin ItemsAdder v2.4.5 generated an exception while executing task 3325
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.n.e.ao()" because the return value of "java.util.HashMap.get(Object)" is null
        at dev.lone.itemsadder.a.g(SourceFile:99) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-100]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-100]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Info (please complete the following information):**
 - Server version: Paper 1.17.1
 - Client version: 1.17

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Solitamente questi errori capitano quando un oggetto non è stato caricato correttamente.
Leggi più in alto nei log.
O comunque allegalo qui nel report, con soltanto quell'errore non posso aiutarti

**Comment by RickyLaChow** [comment]
Purtroppo non ho trovato nessun errore, probabilmente devo aggiornare la cartella

**Comment by LoneDev6** [comment]
Manda tutto il log al massimo, controllo
