### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cristagolem** [PluginBugs/Issues-ItemsAdder#1114]
The plugin won't load
**To Reproduce**
1. Download ItemsAdder 2.4.9
2. Upload it on server in the plugins folder
3. Stop the server
4. Start the server

**Expected behavior**
Plugin loads

**Info**
 - Server version: Paper 1.16.5 (Latest)
 - Client version: Fabric 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.9
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.7
 - ProtocolLib version: 4.6.0

**Additional context**
I have no errors in my console, I am running this server as a single paper server on a VPS with 8GB of RAM, I have these plugins installed:  `AdvancedGUI*, FastAsyncWorldEdit (WorldEdit), ItemsAdder, LibsDisguises, LightAPI, LiteBans, LoneLibs, PlaceholderAPI, ProtocolLib.`

This is my latest.log:
```
[14:17:21] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:17:22] [main/INFO]: Reloading ResourceManager: Default, bukkit
[14:17:23] [Worker-Main-2/INFO]: Loaded 7 recipes
[14:17:25] [Server thread/INFO]: Starting minecraft server version 1.16.5
[14:17:25] [Server thread/INFO]: Loading properties
[14:17:25] [Server thread/INFO]: This server is running Paper version git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:17:25] [Server thread/INFO]: Debug logging is disabled
[14:17:25] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:17:25] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:17:25] [Server thread/INFO]: Default game type: SURVIVAL
[14:17:25] [Server thread/INFO]: Generating keypair
[14:17:26] [Server thread/INFO]: Starting Minecraft server on *:25569
[14:17:26] [Server thread/INFO]: Using epoll channel type
[14:17:27] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[14:17:34] [Server thread/WARN]: Legacy plugin AdvancedGUI v2.0.5 does not specify an api-version.
[14:17:34] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.17-160;188e4b6
[14:17:36] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@296030de]
[14:17:36] [Server thread/INFO]: [LoneLibs] Loading LoneLibs v1.0.7
[14:17:36] [Server thread/INFO]: [LightAPI] Loading LightAPI v3.5.2
[14:17:36] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.10
[14:17:36] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.0
[14:17:38] [Server thread/INFO]: [AdvancedGUI] Loading AdvancedGUI v2.0.5
[14:17:38] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v10.0.26-SNAPSHOT
[14:17:38] [Server thread/INFO]: [LiteBans] Loading LiteBans v2.7.5
[14:17:38] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v2.4.9
[14:17:38] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:17:38] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.17-160;188e4b6
[14:17:39] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[14:17:39] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[14:17:39] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.FAWE_Spigot_v1_16_R3 as the Bukkit adapter
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] ************************************************************
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * MINECRAFT WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] *
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * Please update the version of Java you use to run this server
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * to at least Java 16. Minecraft 1.17 requires a minimum Java version of 16.
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] *
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] * Current Java version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
[14:17:40] [Server thread/INFO]: [com.fastasyncworldedit.serverlib.util.JavaVersionCheck] ************************************************************
[14:17:40] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.7
[14:17:40] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.0
[14:17:40] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[14:17:40] [Server thread/INFO]: Preparing level "world3"
[14:17:40] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:17:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:17:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:17:41] [Server thread/INFO]: Time elapsed: 1086 ms
[14:17:41] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[14:17:42] [Server thread/INFO]: Preparing spawn area: 0%
[14:17:42] [Server thread/INFO]: Time elapsed: 250 ms
[14:17:42] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[14:17:42] [Server thread/INFO]: Time elapsed: 454 ms
[14:17:42] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.5.2
[14:17:42] [Server thread/INFO]: [LightAPI] Loading CraftBukkit implementation for Paper server v1_16_R3.
[14:17:42] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.10
[14:17:43] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[14:17:43] [Server thread/INFO]: [AdvancedGUI] Enabling AdvancedGUI v2.0.5*
[14:17:44] [Server thread/INFO]: Enabling AG...
[14:17:44] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: advancedgui
[14:17:44] [Server thread/INFO]: Loading layout 'DarioGreggio1'...
[14:17:44] [Server thread/INFO]: Loading default fonts...
[14:17:44] [Server thread/INFO]: Done loading default font
[14:17:46] [Server thread/INFO]: - Resources done
[14:17:47] [Server thread/INFO]: - Components done
[14:17:47] [Server thread/INFO]: Loading layout 'CristianoBarone'...
[14:17:48] [Server thread/INFO]: - Resources done
[14:17:48] [Server thread/INFO]: - Components done
[14:17:48] [Server thread/INFO]: Loading layout 'Registrazione'...
[14:17:48] [Server thread/INFO]: - Resources done
[14:17:48] [Server thread/INFO]: - Components done
[14:17:48] [Server thread/INFO]: Loading layout 'PerfezioneWeb'...
[14:17:50] [Server thread/INFO]: - Resources done
[14:17:50] [Server thread/INFO]: - Components done
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #1 (World not found! : world2)
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #2 (World not found! : world2)
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #3 (World not found! : world2)
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #4 (World not found! : world2)
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #5 (World not found! : world2)
[14:17:50] [Server thread/WARN]: Error while loading location of GUI instance #6 (World not found! : world2)
[14:17:50] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.26-SNAPSHOT
[14:17:50] [Server thread/INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[14:17:50] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_16_R3
[14:17:50] [Server thread/INFO]: [LibsDisguises] Jenkins Build: #989
[14:17:50] [Server thread/INFO]: [LibsDisguises] Build Date: 11/08/2021 00:40
[14:17:50] [Server thread/WARN]: [LibsDisguises] If you own the plugin, place the premium jar downloaded from https://www.spigotmc.org/resources/libs-disguises.32453/ in plugins/LibsDisguises/
[14:17:50] [Server thread/INFO]: [LibsDisguises] You are running the free version, commands limited to non-players and operators. (Console, Command Blocks, Admins)
[14:17:53] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[14:17:53] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
[14:17:53] [Server thread/INFO]: [LibsDisguises] Config is up to date!
[14:17:53] [Server thread/INFO]: [LiteBans] Enabling LiteBans v2.7.5
[14:17:54] [Server thread/INFO]: [LiteBans] Loading SQL driver: h2 1.4.197 (org.h2.Driver)
[14:17:54] [Server thread/INFO]: [LiteBans] Connecting to database...
[14:17:54] [Server thread/INFO]: [LiteBans] litebans-pool - Starting...
[14:17:54] [Server thread/INFO]: [LiteBans] litebans-pool - Start completed.
[14:17:54] [Server thread/INFO]: [LiteBans] Connected to [jdbc:h2:///pp/plugins/LiteBans/litebans] (446.2 ms).
[14:17:54] [Server thread/INFO]: [LiteBans] Database connection fully initialized (455.2 ms).
[14:17:54] [Server thread/INFO]: [LiteBans] v2.7.5 enabled. Startup took 672 ms.
[14:17:54] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.4.9
[14:17:54] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.4.9 (Is it up to date?)
java.lang.NoSuchFieldError: MC1_17_R1
	at dev.lone.itemsadder.k.a.a(SourceFile:43) ~[?:?]
	at dev.lone.itemsadder.Main.aQ(SourceFile:463) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[14:17:54] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.4.9
[14:17:55] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[14:17:55] [Server thread/INFO]: No expansions were registered!
[14:17:55] [Server thread/INFO]: Running delayed init tasks
[14:17:55] [Server thread/INFO]: Done (30.170s)! For help, type "help"
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 16. When Paper for Minecraft 1.17 is
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 16 will
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 11.0.11
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java16
[14:17:55] [Server thread/WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[14:17:55] [Server thread/INFO]: Timings Reset
[14:17:57] [Server thread/INFO]: -------< LightAPI-fork 3.5.2 >-------
[14:17:57] [Server thread/INFO]: You are running the latest version!
[14:18:04] [Server thread/INFO]: Stopping the server
[14:18:04] [Server thread/INFO]: Stopping server
[14:18:04] [Server thread/INFO]: [LiteBans] Disabling LiteBans v2.7.5
[14:18:04] [Server thread/INFO]: [LiteBans] litebans-pool - Shutdown initiated...
[14:18:04] [Server thread/INFO]: [LiteBans] litebans-pool - Shutdown completed.
[14:18:05] [Server thread/INFO]: [LiteBans] v2.7.5 disabled.
[14:18:05] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v10.0.26-SNAPSHOT
[14:18:05] [Server thread/INFO]: [AdvancedGUI] Disabling AdvancedGUI v2.0.5
[14:18:05] [Server thread/INFO]: Disabling AG...
[14:18:05] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.6.0
[14:18:05] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.10
[14:18:05] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.5.2
[14:18:05] [Server thread/INFO]: [LoneLibs] Disabling LoneLibs v1.0.7
[14:18:05] [Server thread/INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v1.17-160;188e4b6
[14:18:05] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[14:18:05] [Server thread/INFO]: Saving players
[14:18:05] [Server thread/INFO]: Saving worlds
[14:18:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world3]'/minecraft:overworld
[14:18:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (world3): All chunks are saved
[14:18:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world3_nether]'/minecraft:the_nether
[14:18:07] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:18:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world3_the_end]'/minecraft:the_end
[14:18:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:18:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (world3): All chunks are saved
[14:18:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:18:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:18:08] [Server thread/INFO]: Flushing Chunk IO
[14:18:08] [Server thread/INFO]: Closing Thread Pool
[14:18:08] [Server thread/INFO]: Closing Server
```

**Comment by LoneDev6** [comment]
You have to update LoneLibs
