### ISSUE TITLE
[BUG] ChattyMessageEvent may only be triggered asynchronously.

### ISSUE THREAD

**Issue by iBuseWinner** [PluginBugs/Issues-ItemsAdder#1127]
**Describe the bug**
ChattyMessageEvent may only be triggered asynchronously.

**To Reproduce**
1. /e <random emoji>
2. Send
3. See console for errors

**Expected behavior**
Message send without errors in console

**Screenshots**
```
[09:11:36 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.2
java.lang.IllegalStateException: ChattyMessageEvent may only be triggered asynchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:610) ~[patched_1.17.1.jar:git-Purpur-1320]
        at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:197) ~[Chatty (3).jar:?]
        at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[Chatty (3).jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1320]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1320]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116) ~[patched_1.17.1.jar:git-Purpur-1320]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2226) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.chat(CraftPlayer.java:647) ~[patched_1.17.1.jar:git-Purpur-1320]
        at dev.lone.itemsadder.e.m.onCommand(SourceFile:45) ~[ItemsAdder (6).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1320]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1320]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2309) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2120) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1320]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1320]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.11
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Chatty version 2.19.4

**Comment by LoneDev6** [comment]
I can't fix this, you have to ask the author of Chatty to implement a fix.

Tell them I just call `player.chat(str);` function in the `at dev.lone.itemsadder.e.m.onCommand(SourceFile:45) ~[ItemsAdder (6).jar:?]` line.


Have a nice day
