### ISSUE TITLE
[BUG]  NullPointerException

### ISSUE THREAD

**Issue by wishingrocket20** [PluginBugs/Issues-ItemsAdder#1141]
**Info**
 - Server version: (example: paper 1.17.1)
 - Client version: (example: fabric 1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version:  2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0
 
items adder keep spaming this in the console

 [ItemsAdder] Task #5479 for ItemsAdder v2.4.12 generated an exception
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Core.c.a.a.g()" because "this.a" is null
	at dev.lone.itemsadder.Core.d.a.g.l(SourceFile:42) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.d.b.a.p(SourceFile:84) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.d.b.a.s(SourceFile:109) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.d.b.b.g(SourceFile:277) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.d.b.b.A(SourceFile:159) ~[ItemsAdder.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-186]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-186]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-186]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-186]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-186]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-186]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-186]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by SirCraftypants** [comment]
You need to add a title to your report.  example `NullPointerException`

**Comment by wishingrocket20** [comment]
oh sorry i didnt notice im new to github

**Comment by LoneDev6** [comment]
Why did you close the issue? @wishingrocket20

**Comment by wishingrocket20** [comment]
figered out what it was it was a huds error that got hidden by the spam in log and console
