### ISSUE TITLE
[BUG] Cannot invoke "dev.lone.itemsadder.Core.f.a.b.b.b.c.a(org.bukkit.Location, boolean)"

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1143]
**Describe the bug**
[17:03:55 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.4.12
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Core.f.a.b.b.b.c.a(org.bukkit.Location, boolean)" because the return value of "dev.lone.itemsadder.Core.f.a.b.b.b.c.a()" is null
        at dev.lone.itemsadder.Core.f.a.b.b.b.b(SourceFile:389) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-196]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:220) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1655) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:831) [?:?]
>

**To Reproduce**
Break the wire block

**Screenshots**
https://cdn.discordapp.com/attachments/533413171403292712/881102442777964545/unknown.png

**Info (please complete the following information):**
 - Server version: 1.17.1 paper
 - Client version: vanilla 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: NA
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
This happens because the placed block was removed/renamed in your configuration files.
If you read on the top of this error you surely can notice another warning, for example:
`[ItemsAdder] LoneDev mined unknown block worlddeco:fallen_leaves -157, 64, 69`
