### ISSUE TITLE
[BUG] Server crashes when performing iareload after creating a terra world with world populators

### ISSUE THREAD

**Issue by lucian929** [PluginBugs/Issues-ItemsAdder#1152]
**Describe the bug**
When you create a terra world with Multiverse (I used the command `mv create testworld NORMAL -g Terra:DEFAULT`, and then do /iareload the server will crash.

**To Reproduce**
1. Install Multiverse-core
2. Type this command: `mv create testworld NORMAL -g Terra:DEFAULT` **Sidenote**: I'm pretty sure this only works if the world has a worlds_populator key for it.
3. Type /iareload BEFORE going to the world
4. Server crashes

**Expected behavior**
No crash

**Screenshots**
paste.gg/p/anonymous/3dc3c57a2241499fb512dc7423f77fc9

**Info (please complete the following information):**
 - Server version: git-Airplane-"ec7d3d0"
 - Client version: Fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: N/A
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1-SNAPSHOT-b531

**Additional context**
Nothing else to see here

**Comment by LoneDev6** [comment]
> This crash report has been saved to: /home/container/./crash-reports/crash-2021-09-01_04.29.54-server.txt

Please provide the crash log, this is the server log

**Comment by LoneDev6** [comment]
I don't think I can fix this on my own, seems to be a Terra bug which somehow gets triggered when ItemsAdder is loaded, I have no idea why.
Send them this Github issue link so that we can discuss about it.

`java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`

``` 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.world.BukkitTree.plant(BukkitTree.java:48) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.tree.TreeLayer.place(TreeLayer.java:27) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.TreePopulator.populate(TreePopulator.java:46) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.lambda$checkNeighbors$0(PopulationManager.java:69) 
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.checkNeighbors(PopulationManager.java:67) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.populate(PopulationManager.java:88)
```


``` 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.world.block.BukkitBlock.getType(BukkitBlock.java:57) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.flora.TerraFlora.test(TerraFlora.java:136) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.flora.TerraFlora.getFaces(TerraFlora.java:128) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.flora.TerraFlora.plant(TerraFlora.java:103) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.flora.FloraLayer.lambda$place$0(FloraLayer.java:24) 
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.items.flora.FloraLayer.place(FloraLayer.java:24) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.world.population.FloraPopulator.populate(FloraPopulator.java:59) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.lambda$checkNeighbors$0(PopulationManager.java:69) 
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.checkNeighbors(PopulationManager.java:67) 
at Terra-bukkit-5.4.1-BETA+efd1665c-shaded.jar//com.dfsek.terra.bukkit.population.PopulationManager.populate(PopulationManager.java:88)
```

**Comment by LoneDev6** [comment]
Did Terra devs find the issue cause?

**Comment by LoneDev6** [comment]
This MAY be fixed by the next itemsadder update since I fixed this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/613 , but I'm not sure if it's related, it's just an idea.

**Comment by lucian929** [comment]
I'll try to check it out soon - one of the Terra Devs said it may be caused by the TerraItemsAdderAddon

**Comment by LoneDev6** [comment]
Any news? Can I do anything?

**Comment by lucian929** [comment]
I haven't gotten the chance because I've been working on a custom system instead, closing.
