### ISSUE TITLE
[BUG] Errors and lags

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1167]
**Describe the bug**
Errors and lags

**To Reproduce**
print iareload when player interacts (block state = isBreaking or so) with a block
it causes some lags and errors

> iareload
[22:29:01 INFO]: [ItemsAdder] Reloading...
[22:29:02 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.4.12
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.containsKey(Object)" because "dev.lone.itemsadder.Core.b.a().a.P" is null
        at dev.lone.itemsadder.Core.h.a.h(SourceFile:89) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-232]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:356) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:316) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1734) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1467) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:29:02 INFO]: [ItemsAdder] [Init] Loading YML files...
[22:29:04 INFO]: [ItemsAdder] [Init] Loading items_packs...
[22:29:04 INFO]: [ItemsAdder] Loaded 1772 items
[22:29:04 INFO]: [ItemsAdder] Used 189/188 REAL block IDs.
[22:29:04 INFO]: [ItemsAdder] Used 706/750 REAL_NOTE block IDs.
[22:29:04 INFO]: [ItemsAdder] Used 18/63 REAL_TRANSPARENT block IDs.
[22:29:04 INFO]: [ItemsAdder] Used 10/127 REAL_WIRE block IDs.
[22:29:04 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs.
[22:29:04 INFO]: [ItemsAdder] Used 693/6608 available max font_images.
[22:29:04 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.4.12
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.containsKey(Object)" because "dev.lone.itemsadder.Core.b.a().a.P" is null
        at dev.lone.itemsadder.Core.h.a.h(SourceFile:89) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-232]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:151) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.EntityPlayer.tick(EntityPlayer.java:630) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1114) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.World.a(World.java:986) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:775) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:29:04 WARN]: [ProtocolLib] [PacketFilterManager] [ItemsAdder] Unsupported server packet in current Minecraft version: TITLE[PLAY, SERVER, 249, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTitle, net.minecraft.network.protocol.game.ClientboundTitlePacket] (unregistered)]

**Info (please complete the following information):**
 - Server version: 1.17.1 papermc
 - Client version: 1.17.1 optifine

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
- ItemsAdder version: 2.4.12
- LightAPI Fork version: 3.5.2
- LoneLibs version: 1.0.14
- ProtocolLib version: 4.7.0

**Additional context**

**Comment by LoneDev6** [comment]
Update to latest version before reporting bugs, thanks.
I may already have fixed this issue.
