### ISSUE TITLE
[BUG] [.....ERROR]: [ItemsAdder] World populator since 2.4.13

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1168]
**Describe the bug**
Hello, after updating to 2.4.13 I have error messages in the server console;
Example :
>.... [20:11:25 ERROR]: [ItemsAdder] World populator ruby_ore failed to load. No world matched. Maybe wrong names or they don't exist. File: /data/items_packs/itemsadder/blocks.yml
At first it was talking about the Blockus addon, I removed it restart the server redo /iazip but again it's not talking about Blockus but just ItemsAdder.

- I went to check the "blocks.yml" file but in "worlds_populators:" all the worlds I added have their place, I can't remove them :

---------------------
worlds_populators:
  ruby_ore:
    block: itemsadder:ruby_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 85.0
    max_height: 65
    min_height: 25
    amount: 6
    iterations: 1
  spinel_ore:
    block: itemsadder:spinel_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 80.0
    max_height: 55
    min_height: 20
    amount: 6
    iterations: 1
  turquoise_ore:
    block: itemsadder:turquoise_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 60.0
    max_height: 35
    min_height: 10
    amount: 5
    iterations: 1
  aqua_aura_ore:
    block: itemsadder:aqua_aura_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 90.0
    max_height: 75
    min_height: 30
    amount: 6
    iterations: 1
  amethyst_ore:
    block: itemsadder:amethyst_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 50.0
    max_height: 25
    min_height: 5
    amount: 5
    iterations: 1
  bronze_ore:
    block: itemsadder:bronze_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 70.0
    max_height: 45
    min_height: 15
    amount: 5
    iterations: 1
  mysterious_ore:
    block: itemsadder:mysterious_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - OBSIDIAN
    chance: 60.0
    max_height: 16
    min_height: 1
    amount: 4
    iterations: 1
  end_ore:
    block: itemsadder:end_ore
    worlds:
    - 1_the_end
    replaceable_blocks:
    - END_STONE
    chance: 100.0
    max_height: 60
    min_height: 10
    amount: 5
    iterations: 1
  iron_dirt_ore:
    block: itemsadder:iron_dirt_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 80.0
    max_height: 250
    min_height: 5
    amount: 6
    iterations: 1
  gold_dirt_ore:
    block: itemsadder:gold_dirt_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 80.0
    max_height: 250
    min_height: 5
    amount: 6
    iterations: 1
  coal_dirt_ore:
    block: itemsadder:coal_dirt_ore
    worlds:
    - world
    - world2
    - minage
    - nouveau
    - nouveau2
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 80.0
    max_height: 250
    min_height: 5
    amount: 6
    iterations: 1
  blaze_powder_ore:
    block: itemsadder:blaze_powder_ore
    worlds:
    - 1_nether
    replaceable_blocks:
    - NETHERRACK
    - NETHER_QUARTZ_ORE
    - NETHER_GOLD_ORE
    chance: 80.0
    max_height: 250
    min_height: 5
    amount: 6
    iterations: 1
  nether_alchemy_ore:
    block: itemsadder:nether_alchemy_ore
    worlds:
    - 1_nether
    replaceable_blocks:
    - NETHERRACK
    chance: 50.0
    max_height: 250
    min_height: 5
    amount: 2
    iterations: 1
---------------------

I also have since this version 2.4.13 WARM in relation to LightAPI 3.5.2, I did not have its WARM before this version 2.4.13 :

---------------------
>.... [20:16:20 WARN]: java.lang.ClassCastException: class ca.spottedleaf.starlight.light.StarLightInterface$2 cannot be cast to class net.minecraft.world.level.lighting.LightEngineBlock (ca.spottedleaf.starlight.light.StarLightInterface$2 and net.minecraft.world.level.lighting.LightEngineBlock are in unnamed module of loader 'app')
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1$2.run(CraftBukkit_v1_17_R1.java:166)
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.executeSync(CraftBukkit_v1_17_R1.java:242)
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.recalculateLighting(CraftBukkit_v1_17_R1.java:159)
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.createLight(CraftBukkit_v1_17_R1.java:97)
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.LightAPI$1.run(LightAPI.java:320)
>.... [20:16:20 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.request.RequestSteamMachine.run(RequestSteamMachine.java:120)
>.... [20:16:20 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>.... [20:16:20 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
>.... [20:16:20 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
>.... [20:16:20 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [20:16:20 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [20:16:20 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [20:16:46 WARN]: Can't keep up! Is the server overloaded? Running 5016ms or 100 ticks behind
>.... [20:17:03 WARN]: java.lang.ClassCastException: class ca.spottedleaf.starlight.light.StarLightInterface$2 cannot be cast to class net.minecraft.world.level.lighting.LightEngineBlock (ca.spottedleaf.starlight.light.StarLightInterface$2 and net.minecraft.world.level.lighting.LightEngineBlock are in unnamed module of loader 'app')
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1$2.run(CraftBukkit_v1_17_R1.java:166)
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.executeSync(CraftBukkit_v1_17_R1.java:242)
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.recalculateLighting(CraftBukkit_v1_17_R1.java:159)
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.createLight(CraftBukkit_v1_17_R1.java:97)
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.LightAPI$1.run(LightAPI.java:320)
>.... [20:17:03 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.request.RequestSteamMachine.run(RequestSteamMachine.java:120)
>.... [20:17:03 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>.... [20:17:03 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
>.... [20:17:03 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
>.... [20:17:03 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [20:17:03 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [20:17:03 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [20:17:05 WARN]: java.lang.ClassCastException: class ca.spottedleaf.starlight.light.StarLightInterface$2 cannot be cast to class net.minecraft.world.level.lighting.LightEngineBlock (ca.spottedleaf.starlight.light.StarLightInterface$2 and net.minecraft.world.level.lighting.LightEngineBlock are in unnamed module of loader 'app')
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1$2.run(CraftBukkit_v1_17_R1.java:166)
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.executeSync(CraftBukkit_v1_17_R1.java:242)
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.recalculateLighting(CraftBukkit_v1_17_R1.java:159)
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.createLight(CraftBukkit_v1_17_R1.java:97)
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.LightAPI$1.run(LightAPI.java:320)
>.... [20:17:05 WARN]: at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.request.RequestSteamMachine.run(RequestSteamMachine.java:120)
>.... [20:17:05 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>.... [20:17:05 WARN]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
>.... [20:17:05 WARN]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
>.... [20:17:05 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>.... [20:17:05 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>.... [20:17:05 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
---------------------

**Screenshots**

Just after the update to 2.4.13 I had the addon "blockus" as I saw the errors about it I removed it:
![blockus2021-09-08_200611](https://user-images.githubusercontent.com/80985545/132566693-2851cd57-0c03-44b5-bbb0-4d2a2ad1d5e9.jpg)

After deleting Blockus I have the same errors but no longer talking about blockus but just itemsAdder:
![sans blockus2021-09-08_201032](https://user-images.githubusercontent.com/80985545/132566704-69281ed6-efa9-47a4-a8bf-06776400ff71.jpg)

Info (please complete the following information):
Minecraft PaperSpigot 1.17.1 #255

Special Info
Please do not write "latest"! Tell us the specific plugin version you are using.

    ItemsAdder version: 2.4.13
    LightAPI Fork version: 3.5.2
    LoneLibs version: 1.0.14
    ProtocolLib version: ProtocolLib #531 (27 juil. 2021 06:52:08)

**Comment by vdl19** [comment]
Here is my blocks.yml file I just renamed it blocks.yml.txt :

[blocks.yml.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7131219/blocks.yml.txt)

**Comment by ghtg** [comment]
same problem

**Comment by vdl19** [comment]
And I also have this new error that seems to come back intermittently:

>.... [21:19:28 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected ']' at position 445: ...xt\":\"[ "<--[HERE]

![image](https://user-images.githubusercontent.com/80985545/132573335-181f4dfd-7d3b-4a14-b5d1-b9b89431a69c.png)


![image](https://user-images.githubusercontent.com/80985545/132573256-93e26e58-2c6f-49a1-bb55-b23df7b416c7.png)

**Comment by matyasvane** [comment]
Some problem with this, clean install have some problem.

**Comment by LoneDev6** [comment]
Please everyone avoid pasting very long texts in the issue reports...
Attach files directly (drag and drop) or use [pastebin ](pastebin.com/)
Update your messages, thanks.


Also, I need your worlds names to answer this error report.
The message states that no world in the list is in the server when the populator tried to load.

**Comment by LoneDev6** [comment]
> And I also have this new error that seems to come back intermittently:
> 
> > .... [21:19:28 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers] null
> > com.mojang.brigadier.exceptions.CommandSyntaxException: Expected ']' at position 445: ...xt":"[ "<--[HERE]


Please open another issue report, it is a different problem, thanks.
It seems to be a problem of LibsDisguises, I'll investigate once you've opened the new issue report.

Have a nice day

**Comment by LoneDev6** [comment]
Anyway this will be fixed in the next update, seems the missing world error is triggered in some cases even if a world is correctly found
