### ISSUE TITLE
[BUG] Could not pass event PlayerTeleportEvent to ItemsAdder v2.4.13

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1169]
**Describe the bug**
Error in console and player get stuck in ground
error: https://pastebin.com/byn20J32

**To Reproduce**
player just joined the server and stuck

**Expected behavior**
spawn player on last position

**Info (please complete the following information):**
server: papermc 1.17.1
client: optifine 1.17.1

**Special Info**
ItemsAdder version: 2.4.13
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Please update to the latest version and send me an updated log of this error, thanks

**Comment by inrhor** [comment]
> Please update to the latest version and send me an updated log of this error, thanks

2.4.15 error:
[code]
[14:55:22 ERROR]: Could not pass event PlayerTeleportEvent to ItemsAdder v2.4.15
java.lang.NullPointerException: null
        at dev.lone.itemsadder.i.c.h(SourceFile:581) ~[?:?]
        at dev.lone.itemsadder.i.c.x(SourceFile:335) ~[?:?]
        at dev.lone.itemsadder.i.c.c(SourceFile:771) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1644) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1623) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1613) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:343) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:317) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1597) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
[/code]

**Comment by TinZz7** [comment]
> Please update to the latest version and send me an updated log of this error, thanks

[17:31:40 ERROR]: Could not pass event PlayerTeleportEvent to ItemsAdder v2.4.15
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
        at dev.lone.itemsadder.i.c.h(SourceFile:581) ~[ItemsAdder (18).jar:?]
        at dev.lone.itemsadder.i.c.x(SourceFile:335) ~[ItemsAdder (18).jar:?]
        at dev.lone.itemsadder.i.c.c(SourceFile:771) ~[ItemsAdder (18).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1600) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1571) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1567) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:341) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:307) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:555) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1643) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
