### ISSUE TITLE
Error in console when I use /iareload

### ISSUE THREAD

**Issue by ipermatti83** [PluginBugs/Issues-ItemsAdder#1180]
Every time I use /iareload on my server this happen in console.
[15:02:18 INFO]: ipermatti83 issued server command: /iareload
[15:02:18 INFO]: [ItemsAdder] Reloading...
[15:02:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iareload' in plugin ItemsAdder v2.4.15
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1335]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1335]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2309) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2120) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2101) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1532) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1335]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1335]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.ServerSocket.close()" because "dev.lone.itemsadder.l.b.b.a" is null
        at dev.lone.itemsadder.l.b.b.aA(SourceFile:71) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.l.c.f.aA(SourceFile:34) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.l.b.aA(SourceFile:137) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.e.u.a(SourceFile:80) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.e.u.onCommand(SourceFile:64) ~[ItemsAdder.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1335]
        ... 21 more

INFO
 - Server version: purpur 1.17.1
 - Client version: Minecraft Premium 1.17.1

 - ItemsAdder version: 2.4.15
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0
 - ScracthIt version: 1.1.9

**Comment by LoneDev6** [comment]
I'll fix this but probably there is also another error before this one.
Thanks
