### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CivicXFB** [PluginBugs/Issues-ItemsAdder#1203]
**Describe the bug**
Can't compress zip to create packets so things don't work properly

**To Reproduce**
1. Go to '/iazip Waiting for the iazip to be packed. But iazip doesn't work!'
2. Click on 'Then, the packaged file is only 7kb in size'
3. Scroll down to 'Secondly, the original material pack does not work properly. 2.4.15 version can use the packing function properly.'

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: example: 2.4.16
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Additional context**

[11:29:40] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] [Pack] Compressing resource_pack ... 
[11:29:40] [Craft Scheduler Thread - 1/WARN]: [ItemsAdder] Plugin ItemsAdder v2.4.16 generated an exception while executing task 2077
java.lang.ExceptionInInitializerError: null
	at dev.lone.itemsadder.l.j.a(SourceFile:166) ~[?:?]
	at dev.lone.itemsadder.l.j.av(SourceFile:104) ~[?:?]
	at dev.lone.itemsadder.l.a.a(SourceFile:164) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-788]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-788]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.util.zip.ZipEntry.size accessible: module java.base does not "opens java.util.zip" to unnamed module @5531476d
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
	at com.comphenix.protocol.reflect.FieldUtils.getField(FieldUtils.java:111) ~[?:?]
	at dev.lone.itemsadder.l.k.<clinit>(SourceFile:12) ~[?:?]
	... 9 more

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1199
