### ISSUE TITLE
[BUG] PlayerInteractAtEntityEvent since 2.4.17

### ISSUE THREAD

**Issue by L3v3lup** [PluginBugs/Issues-ItemsAdder#1218]
**Describe the bug**
Clicking on the ItemsAdder-own coffee machine causes this console error.
*! I've deleted the whole plugin folder - but error stays.

**Screenshots**
![image](https://user-images.githubusercontent.com/40206438/134502337-3ced7a26-115f-4247-8923-38b05bce2afc.png)

**Info**
 - Server version: git-Purpur-1393 (MC: 1.17.1)
 - Client version: 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.17
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Error should be very easy reproducible.

**Comment by LoneDev6** [comment]
Please post this as text not screenshot, thanks

**Comment by L3v3lup** [comment]
```
[13:53:30 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ItemsAdder v2.4.17
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.WeakHashMap.get(Object)" is null
        at dev.lone.itemsadder.Core.f.a.b.k.g(SourceFile:99) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b(SourceFile:159) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1393]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2504) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2561) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2496) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by EchocallingEarth** [comment]
LoneDev 
If it helps I tested several (not 100% of blocks etc) And noticed the error floods console when placing on ItemFrames
