### ISSUE TITLE
[Bug]: Error when I put something against one of the faces of an Barrier

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1224]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When I put something (blocks, mats, ..) against one of the faces of an invisible block (Barrier) I get the following error every time: 
>.... [11:58:12 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.4.17

In fact I just saw that if I right click on a "Barrier" it triggers the error.
I have this bug only on my Paper 1.17.1 server not on my official Paper 1.16.5 server.

On my test server in Paper 1.17.1 I have IA 2.4.17 = BUG with the Barriers
On my official server in 1.16.5 I have IA 2.4.16b = OK no bug with the Barrier

### Steps to reproduce the issue

Right click on Barriers

### Server version

This server is running Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)

### ItemsAdder Version

ItemsAdder version 2.4.17

### ProtocolLib Version

ProtocolLib version 4.7.1-SNAPSHOT-b531

### LoneLibs Version

LoneLibs version 1.0.14

### LightAPI Version (optional)

LightAPI version 3.5.2

### LibsDisguises Version (optional)

LibsDisguises version 10.0.26-SNAPSHOT

/ld update :
>.... [12:21:47 INFO]: You are already on the latest version of LibsDisguises!

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7229556/latest.log)

### Error (optional)

```shell
[12:13:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.4.17
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.WeakHashMap.get(Object)" is null
	at dev.lone.itemsadder.Core.f.a.b.k.g(SourceFile:99) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.f.a.b.b.a(SourceFile:186) ~[ItemsAdder.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-278]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1810) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1528) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-278]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Configurations

[config.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7229560/config.zip)

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/80985545/134768233-a43a8c79-24ff-4a08-9579-4c854f6821dc.png)

**Comment by vdl19** [comment]
To bring more information, I just put version 2.4.16b on my Paper 1.17.1 server and I don't have the error anymore, so it is indeed version 2.4.17 that brings this error.

>....=>.... [12:37:38 INFO]: ItemsAdder version 2.4.16b
