### ISSUE TITLE
[Bug]: Server Crash with java.lang.RuntimeException: Failed to read BlockState at: world: res_world location

### ISSUE THREAD

**Issue by Xwdit** [PluginBugs/Issues-ItemsAdder#1236]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Xwdit#2696

### What happened?

Looks like custom blocks/custom trees crash my server when a player entered the world that enabled them.

I have a world that generating with Stratos  Generator , Dangerous Cave and Oh The Dungeon You will go. After I enabled custom tree/custom ore generation in this world, my server start to crash.

### Steps to reproduce the issue

1. Enable custom ores generate in a world
2. Go to this world or wait sometimes
3. Server Crash/No response

### Server version

[11:02:11] [Server thread/INFO]: This server is running Airplane version git-Airplane-92 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5ed110b on HEAD)

### ItemsAdder Version

ItemsAdder Version 2.4.17

### ProtocolLib Version

ProtocolLib 4.7.1-SNAPSHOT-b533

### LoneLibs Version

LoneLibs 1.0.14

### Error (optional)

```shell
java.lang.RuntimeException: Failed to read BlockState at: world: res_world location: (240, 27, -369)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:47)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftCreatureSpawner.<init>(CraftCreatureSpawner.java:15)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getState0(CraftBlock.java:366)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getState(CraftBlock.java:325)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getState(CraftBlock.java:319)
	at Stratos1.14.3.jar//com.civious.worldgenerator.f.c.c.a(DungeonPopulator.java:98)
	at Stratos1.14.3.jar//com.civious.worldgenerator.f.c.c.populate(DungeonPopulator.java:77)
	at app//net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:1004)
	at app//net.minecraft.server.level.ChunkHolder.lambda$updateFutures$22(ChunkHolder.java:873)
	at app//net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:182)
	at app//net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1251)
	at app//net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
	at app//net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:680)
	at app//net.minecraft.world.level.Level.getChunk(Level.java:646)
	at app//net.minecraft.world.level.Level.getBlockState(Level.java:985)
	at app//net.minecraft.world.level.Level.updateNeighbourForOutputSignal(Level.java:1464)
	at app//net.minecraft.world.level.block.entity.BlockEntity.setChanged(BlockEntity.java:158)
	at app//net.minecraft.world.level.block.entity.BlockEntity.setChanged(BlockEntity.java:150)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.update(CraftBlockEntityState.java:148)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.update(CraftBlockState.java:193)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.update(CraftBlockState.java:188)
	at Stratos1.14.3.jar//com.civious.worldgenerator.f.c.c.a(DungeonPopulator.java:109)
	at Stratos1.14.3.jar//com.civious.worldgenerator.f.c.c.populate(DungeonPopulator.java:77)
	at app//net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:1004)
	at app//net.minecraft.server.level.ChunkHolder.lambda$updateFutures$22(ChunkHolder.java:873)
	at app//net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:182)
	at app//net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1251)
	at app//net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:839)
	at app//net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406)
	at app//net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389)
	at app//net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
	at app//net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278)
	at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=240, y=27, z=-369},type=SPAWNER,data=Block{minecraft:spawner},fluid=net.minecraft.world.level.material.FluidTypeEmpty@2b2954e1}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:28)
	... 34 more
```

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
It seems to be a `Stratos` plugin bug.

I don't see `ItemsAdder` in the log
