### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractAtEntityEvent to ItemsAdder v2.4.17

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#1237]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[18:22:35 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ItemsAdder v2.4.17
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.WeakHashMap.get(Object)" is null
        at dev.lone.itemsadder.Core.f.a.b.k.g(SourceFile:99) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b(SourceFile:159) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1344]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1344]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1344]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2474) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2531) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2466) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1344]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1344]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Steps to reproduce the issue

Try to ride vehicle that isn't yours

### Server version

[18:30:37 INFO]: This server is running Purpur version git-Purpur-1344 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9d932a on ver/1.17.1)
[18:30:37 INFO]: You are 51 version(s) behind
[18:30:37 INFO]: Previous version: git-Purpur-1382 (MC: 1.17.1)

### ItemsAdder Version

[18:26:22 INFO]: ItemsAdder version 2.4.17
[18:26:22 INFO]: Customize Minecraft without client mods!
[18:26:22 INFO]: Website: devs.beer
[18:26:22 INFO]: Authors: LoneDev and LoneDev

### ProtocolLib Version

[18:26:48 INFO]: ProtocolLib version 4.7.0
[18:26:48 INFO]: Provides read/write access to the Minecraft protocol.
[18:26:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[18:27:10 INFO]: LoneLibs version 1.0.14
[18:27:10 INFO]: Collection of libs used by my plugins
[18:27:10 INFO]: Authors: LoneDev and others

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by Go4SKILL** [comment]
Please, it's like 3rd time I see this issue.
"I already searched on this Github page to check if the same issue was already reported.", did you even read it?

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1234

**Comment by ghtg** [comment]
+, fix pls

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1218
