### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by FoonZA** [PluginBugs/Issues-ItemsAdder#1244]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

FEAR#9095

### What happened?

This null happen to me on 1/10/2021 not sure what is going on everything in the server looking so fine. but it keep appear when ever player touch the armour stand. I use model engine to put 3D stuff in my server as well not sure if it because of my model or something else.

### Steps to reproduce the issue

1.Delete Itemadder
2.install new one

### ItemsAdder Version

Itemadder version 2.4.18

### ProtocolLib Version

ProtocolLib v4.7.0

### LoneLibs Version

LoneLibs 1.0.14

### Error (optional)

```shell
[06:17:01 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ItemsAdder v2.4.17
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.WeakHashMap.get(Object)" is null
        at dev.lone.itemsadder.Core.f.a.b.k.g(SourceFile:99) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b(SourceFile:159) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-280]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2422) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2477) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2414) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-280]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-280]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Screenshots/Videos

![244411410_1283023845482720_6430292440806058392_n](https://user-images.githubusercontent.com/91829461/135752044-07c207aa-6361-453c-995c-6f242c5e22f1.png)
s)

**Comment by 100petr** [comment]
Can you try version 2.4.18?
> fixes:
>- fixed "Could not pass event PlayerInteractAtEntityEvent" https://github.com/PluginBugs/Issues-ItemsAdder/issues/1218

**Comment by FoonZA** [comment]
> Can you try version 2.4.18?
> 
> > fixes:
> > 
> > * fixed "Could not pass event PlayerInteractAtEntityEvent" [[BUG] PlayerInteractAtEntityEvent since 2.4.17 #1218](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1218)

you mean Itemadder ye ? if yes, yes I using 2.4.18

**Comment by 100petr** [comment]
the error says .17
