### ISSUE TITLE
Unable to broke furnitures

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [PluginBugs/Issues-ItemsAdder#1252]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Temporex#7795

### What happened?

I read the wikia where they notified this error but I have all the recent versions and it is still happening I can't reomper furniture but I have the protocllib lonelibs and itemsadder in latest versions and on top of that I don't have AST or LootChest

### Steps to reproduce the issue

1. Placing furniture
2. Try to break it

### Server version

This server is running Airplane version git-Airplane-87 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 002f470 on HEAD)

### ItemsAdder Version

version itemsadder
[09:29:38 INFO]: ItemsAdder version 2.4.18
[09:29:38 INFO]: Customize Minecraft without client mods!
[09:29:38 INFO]: Website: devs.beer
[09:29:38 INFO]: Authors: LoneDev and LoneDev

### ProtocolLib Version

version protocollib
[09:30:00 INFO]: ProtocolLib version 4.7.0
[09:30:00 INFO]: Provides read/write access to the Minecraft protocol.
[09:30:00 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

version lonelibs
[09:30:16 INFO]: LoneLibs version 1.0.14
[09:30:16 INFO]: Collection of libs used by my plugins
[09:30:16 INFO]: Authors: LoneDev and others

### FULL server log

[Uploading latest (1).log…]()

### Error (optional)

```shell
[03:17:17 ERROR]: Could not pass event PlayerItemDamageEvent to ItemsAdder v2.4.18
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Core.e.n.E()" because "<local4>" is null
        at dev.lone.itemsadder.Core.e.n.a(SourceFile:324) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.Core.e.n.a(SourceFile:296) ~[ItemsAdder.jar:?]
        at dev.lone.itemsadder.Core.e.a(SourceFile:37) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Airplane-87]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.world.item.ItemStack.hurt(ItemStack.java:546) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.world.item.ItemStack.damage(ItemStack.java:584) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.world.item.ItemTool.a(ItemTool.java:51) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.world.item.ItemStack.a(ItemStack.java:637) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:458) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:356) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:316) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1734) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Screenshots/Videos

https://user-images.githubusercontent.com/54515502/136177895-8070c9ab-087a-408e-ac2c-6a0280f5e99f.mp4

**Comment by LoneDev6** [comment]
I doubt the error is related to the issue.
The error tells that somehow a custom item is not found anymore in your configuration files, maybe try to check the log file (I can't read it as you didn't let it finish uploading)

Let me know
