### ISSUE TITLE
INCOMPATIBILITY WITH DELUXEANNOUNCE

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [PluginBugs/Issues-ItemsAdder#1271]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Gers#7795

### What happened?

As soon as a command is sent from the deluxe plugin announce the itemsadder starts spamming errors in the console

### Steps to reproduce the issue

set the plugin donation command
1. acs donate <nick> <package>

### Server version

This server is running Airplane version git-Airplane-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 317e61b on HEAD)

### ItemsAdder Version

[14:46:28 INFO]: ItemsAdder version 2.4.18
[14:46:28 INFO]: Customize Minecraft without client mods!
[14:46:28 INFO]: Website: devs.beer
[14:46:28 INFO]: Authors: LoneDev and LoneDev
for a or b reason that version is out but I already updated to the new 2.4.19.b

### ProtocolLib Version

[14:52:40 INFO]: ProtocolLib version 4.7.1-SNAPSHOT-b533
[14:52:40 INFO]: Provides read/write access to the Minecraft protocol.
[14:52:40 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:52:53 INFO]: LoneLibs version 1.0.15
[14:52:53 INFO]: Collection of libs used by my plugins
[14:52:53 INFO]: Authors: LoneDev and others

### FULL server log

[message (1).txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7403186/message.1.txt)

### Error (optional)

```shell
[14:45:44 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
        at dev.lone.itemsadder.j.d.onPacketSending(SourceFile:158) ~[ItemsAdder (2).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1992) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1978) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:230) ~[patched_1.17.1.jar:git-Airplane-95]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:246) ~[patched_1.17.1.jar:git-Airplane-95]
        at ruben_artz.bukkit.player.SendAvatar.lambda$sendDonationEveryAvatar$2(Unknown Source) ~[Deluxe Announce.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-95]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Airplane-95]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Airplane-95]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
Waiting for the new full log
