### ISSUE TITLE
Itemsadder 2.4.21b doesn't start

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1294]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Agaloth#4927

### What happened?

The plugin doesn't work on 2.4.21b

### Steps to reproduce the issue

Just install 2.4.21b and run it.

### Server version

git-Purpur-1397 (MC: 1.17.1)

### ItemsAdder Version

Itemsadder 2.4.21b

### ProtocolLib Version

ProtocolLib version 4.7.1-SNAPSHOT-b531

### LoneLibs Version

LoneLibs 1.0.15

### Error (optional)

```shell
[07:38:34] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[07:38:34] [Server thread/WARN]: java.lang.ClassCastException: class lonelibs.net.kyori.adventure.text.TextComponentImpl cannot be cast to class net.minecraft.nbt.NBTBase (lonelibs.net.kyori.adventure.text.TextComponentImpl is in unnamed module of loader 'LoneLibs 1.0.15.jar' @2a290bae; net.minecraft.nbt.NBTBase is in unnamed module of loader 'app')
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.k.q.a.a.t.a(SourceFile:96)
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.k.q.a.a.t.a(SourceFile:6)
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.k.q.f.a(SourceFile:96)
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.o.m.a(SourceFile:449)
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.Core.b.b(SourceFile:1221)
[07:38:34] [Server thread/WARN]: 	at ItemsAdder 2.4.21b.jar//dev.lone.itemsadder.Core.b.a(SourceFile:520)
[07:38:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:103)
[07:38:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:38:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1225)
[07:38:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[07:38:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by ArtifactyNight** [comment]
Same issues too
but i have error spamming 😂 

https://www.toptal.com/developers/hastebin/lefewayixu.apache

**Comment by LoneDev6** [comment]
Thanks this is known and will be fixed in some minutes :D
