### ISSUE TITLE
Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1296]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

pitilon#6950

### What happened?

Console error while starting server. The second error spams almost constantly

### Steps to reproduce the issue

Start server

### Server version

This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

### ItemsAdder Version

ItemsAdder v2.4.21c

### ProtocolLib Version

v4.7.1-SNAPSHOT-b530

### LoneLibs Version

1.0.15

### LibsDisguises Version (optional)

 v10.0.26-SNAPSHOT

### Error (optional)

```shell
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Loaded 2250 items
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 148/188 REAL block IDs.
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 54/750 REAL_NOTE block IDs.
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 22/63 REAL_TRANSPARENT block IDs.
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 9/127 REAL_WIRE block IDs.
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 5/14 FIRE block IDs.
[07:24:43] [Craft Scheduler Thread - 65 - ItemsAdder/INFO]: [ItemsAdder] Used 1245/6608 available max font_images.
[07:24:43] [Server thread/ERROR]: Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v2.4.21c
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null
     at dev.lone.itemsadder.o.m.d(SourceFile:498) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.n.b(SourceFile:232) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:265) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.d.a(SourceFile:82) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:433) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:395) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.a.ag(SourceFile:449) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.b.h.a(SourceFile:167) ~[ItemsAdder.jar:?]
     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1423]
     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
     at dev.lone.itemsadder.o.i.a(SourceFile:38) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.b.b(SourceFile:1761) ~[ItemsAdder.jar:?]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1588) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
     at java.lang.Thread.run(Thread.java:831) ~[?:?]

[09:08:14] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to ItemsAdder v2.4.21c
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null
     at dev.lone.itemsadder.o.m.d(SourceFile:498) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.n.b(SourceFile:232) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:265) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:393) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.d.a(SourceFile:71) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.b.h.a(SourceFile:85) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.a.b.a(SourceFile:149) ~[ItemsAdder.jar:?]
     at dev.lone.itemsadder.Core.f.a.c.a.b.a(SourceFile:125) ~[ItemsAdder.jar:?]
     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1423]
     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:738) ~[patched_1.17.1.jar:git-Purpur-1423]
     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:643) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1483) ~[app:?]
     at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1395) ~[app:?]
     at net.minecraft.world.level.ServerLevelAccessor.lambda$addAllEntities$0(ServerLevelAccessor.java:16) ~[app:?]
     at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
     at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
     at net.minecraft.world.level.ServerLevelAccessor.addAllEntities(ServerLevelAccessor.java:16) ~[app:?]
     at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:310) ~[app:?]
     at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:227) ~[app:?]
     at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:185) ~[app:?]
     at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1045) ~[app:?]
     at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
     at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
     at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by LoneDev6** [comment]
Will be fixed, thanks
