### ISSUE TITLE
Possible abusing of selfhost port

### ISSUE THREAD

**Issue by DanikVitek** [PluginBugs/Issues-ItemsAdder#1307]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Danik Vitek#9110

### What happened?

It seems to be just a minor bug. It's not critical, just spamming in console

### Steps to reproduce the issue

It just happens sometimes

### Server version

This server is running Paper version git-Paper-280 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e3cea1)

### ItemsAdder Version

ItemsAdder version 2.4.21c

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.15

### FULL server log

[2021-11-07-1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7504743/2021-11-07-1.log)

### Error (optional)

```shell
[23:23:15 WARN]: Exception in thread "Thread-659" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
[23:23:15 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:197)
[23:23:15 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:234)
[23:23:15 WARN]:        at ItemsAdder (3).jar//dev.lone.itemsadder.l.b.a.run(SourceFile:41)
[23:23:17 WARN]: Exception in thread "Thread-658" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
[23:23:17 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:197)
[23:23:17 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:234)
[23:23:17 WARN]:        at ItemsAdder (3).jar//dev.lone.itemsadder.l.b.a.run(SourceFile:41)
[23:23:19 WARN]: Exception in thread "Thread-660" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
[23:23:19 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:197)
[23:23:19 WARN]:        at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:234)
[23:23:19 WARN]:        at ItemsAdder (3).jar//dev.lone.itemsadder.l.b.a.run(SourceFile:41)
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  self-host: {}
  external-host: {}
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 20
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: false
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 178.208.254.231
      pack-port: 5555
    external-host:
      enabled: false
      url: https://www.dropbox.com/s/0hxgazt84ucpky1/pack.zip?dl=0
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```

**Comment by LoneDev6** [comment]
This is not the full log.
Anyway seems the selfhost somehow failed to initialize

**Comment by LoneDev6** [comment]
Or you have someone spamming your server with requests on this port.

**Comment by DanikVitek** [comment]
> This is not the full log. Anyway seems the selfhost somehow failed to initialize

Yeah, sorry. My logs are constantly archiving, so I was not able to easily contact all of them. I tried to get the most full one.
