### ISSUE TITLE
[Mobs] CreaturesPlus : ERROR no longer spawn (with 2.4.21b and 2.4.21c)

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1312]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hello, I updated to version 2.4.21c and I no longer have CreaturePlus mobs, in the console instead I have Error every time one of the 2 mobs should Spawn.

### Steps to reproduce the issue

- You just have to have the Addon creaturesplus installed and roam around a world at night to normally spawn them and errors occur in the console each time one of the 2 mobs should appear.
- Another solution to get the error, use mob eggs:
. Drunk
. Glow Squid
. Brush Stooge

### Server version

This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)

### ItemsAdder Version

ItemsAdder version 2.4.21c

### ProtocolLib Version

ProtocolLib version 4.7.1-SNAPSHOT-b533

### LoneLibs Version

LoneLibs version 1.0.15

### LightAPI Version (optional)

I no longer have LightAPI in 1.17.1 it had to be removed I had read

### LibsDisguises Version (optional)

Lib's Disguises v10.0.26-SNAPSHOT, build #1013, built Thu Nov 11 10:09:00 CET 2021 and size 1156kb

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7533533/latest.log)

### Error (optional)

```shell
>.... [10:56:07 ERROR]: Could not pass event CreatureSpawnEvent to ItemsAdder v2.4.21c
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null
at dev.lone.itemsadder.o.m.d(SourceFile:498) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.b(SourceFile:232) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:265) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:393) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.d.b(SourceFile:63) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.b.h.a(SourceFile:52) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.b.a(SourceFile:151) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.b.a(SourceFile:125) ~[ItemsAdder.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-381]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:729) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:634) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1399) ~[app:?]
at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1311) ~[app:?]
at net.minecraft.world.level.ServerLevelAccessor.lambda$addAllEntities$0(ServerLevelAccessor.java:16) ~[app:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at net.minecraft.world.level.ServerLevelAccessor.addAllEntities(ServerLevelAccessor.java:16) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:310) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:227) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:185) ~[app:?]
at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1044) ~[app:?]
at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:731) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
>.... [10:56:18 ERROR]: Could not pass event CreatureSpawnEvent to ItemsAdder v2.4.21c
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null
at dev.lone.itemsadder.o.m.d(SourceFile:498) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.b(SourceFile:232) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:265) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.n.a(SourceFile:393) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.d.b(SourceFile:63) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.b.h.a(SourceFile:52) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.b.a(SourceFile:151) ~[ItemsAdder.jar:?]
at dev.lone.itemsadder.Core.f.a.c.a.b.a(SourceFile:125) ~[ItemsAdder.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-381]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:729) ~[patched_1.17.1.jar:git-Paper-381]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:634) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1399) ~[app:?]
at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1311) ~[app:?]
at net.minecraft.world.level.ServerLevelAccessor.lambda$addAllEntities$0(ServerLevelAccessor.java:16) ~[app:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at net.minecraft.world.level.ServerLevelAccessor.addAllEntities(ServerLevelAccessor.java:16) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:310) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:227) ~[app:?]
at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:185) ~[app:?]
at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1044) ~[app:?]
at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:731) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-381]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 146.59.138.51
      pack-port: 30070
    external-host:
      enabled: false
      url: ''
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: fr
  dictionaries-lang: fr
  extract-default-items: true
  extract-default-resources: true
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
      - DARK_FOREST
      - JUNGLE
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```

**Comment by vdl19** [comment]
I just installed version 2.4.21b and there the mobs of "creature plus" do not spawn but the eggs of "creature plus" no longer work at all to spawn they eat each other. So no more errors in the console but no more mobs or eggs that work from Creature anymore! This is why I had not seen that the problem existed from this version 2.4.21b I had not been to see if the 3 mobs that I use with spawner

**Comment by vdl19** [comment]
I just reverted to version 2.4.20 and creature plus mobs are now working again without error. I did not put back the modifications that had to be made when we go to 2.4.21b and c I hope this is not a problem because otherwise it will take a bit long to recover the files from before.

**Comment by 100petr** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1296
