### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by NewJeb** [PluginBugs/Issues-ItemsAdder#1319]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

newjebv#2777

### What happened?

There are 3 errors:
1) The one on the video, by the way, is similar to the anvils when using ingots
https://www.youtube.com/watch?v=nWFU0VLyUV0
2) IA does not work with CMI I attach error
3) Another video with changing textures
https://www.youtube.com/watch?v=iLr1tyG7shg

### Steps to reproduce the issue

https://www.youtube.com/watch?v=nWFU0VLyUV0

### Server version

Previous version: git-Paper-377 (MC: 1.17.1)

### ItemsAdder Version

2.4.21c

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.15

### FULL server log

[latest_14.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7557252/latest_14.log)

### Error (optional)

```shell
[17:01:02] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.4.19
[17:01:02] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 2.4.19
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.15
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Airplane git-Airplane-98 (MC: 1.17.1)
                                               
[17:01:02] [Server thread/INFO]: [ItemsAdder] LightAPI is not compatible with Spigot forks. Disabling LightAPI... Read more here: http://a.devs.beer/starlight-git-issue
[17:01:02] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.5.2
[17:01:02] [Server thread/INFO]: [ItemsAdder] LibsDisguises not installed, please install it to make custom mobs working: ci.md-5.net/job/LibsDisguises/
[17:01:02] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.4.19 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.lone.itemsadder.Core.b
    at dev.lone.itemsadder.Main.onEnable(SourceFile:381) ~[ItemsAdder (18).jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-98]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-98]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-98]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-98]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-98]
    at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Airplane-98]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patched_1.17.1.jar:git-Airplane-98]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Airplane-98]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-98]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
[17:01:02] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.4.19
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.dropbox.com/s/85tmvrfb0a1l6m9/GTRP%2009.10.2021%20%C2%A9.zip?dl=1
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: false
      extreme: false
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 200
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: green_tavern
recipes:
  crafting_table:
    orichalcum_ingot:
      permission: greentavern.itemsadder.all.use
      enabled: true
      pattern:
      - AAA
      - AAA
      - AAA
      ingredients:
        A: green_tavern:orichalcum_nugget
      result:
        item: green_tavern:orichalcum_ingot
        amount: 1
  cooking:
    orcish_steel_ingot:
      permission: itemsadder.ingot.smithing
      ingredient:
        item: green_tavern:raw_orcish_iron
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: green_tavern:orcish_steel_ingot
        amount: 1
    titanite_ingot:
      permission: itemsadder.ingot.smithing
      ingredient:
        item: green_tavern:raw_titanite
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: green_tavern:titanite_ingot
        amount: 1
    wolfram_ingot:
      permission: itemsadder.ingot.smithing
      ingredient:
        item: green_tavern:raw_wolfram
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: green_tavern:wolfram_ingot
        amount: 1
    mythril_ingot:
      permission: itemsadder.ingot.smithing
      ingredient:
        item: green_tavern:raw_mythril
      machines:
      - FURNACE
      - BLAST_FURNACE
      exp: 1
      cook_time: 200
      result:
        item: green_tavern:mythril_ingot
        amount: 1
loots:
  blocks:
    orcish_iron_ore:
      type: green_tavern:orcish_iron_ore
      items:
        raw_orcish_iron:
          item: green_tavern:raw_orcish_iron
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 0
          max_amount: 3
          chance: 100
    titanite_ore:
      type: green_tavern:titanite_ore
      items:
        raw_titanite:
          item: green_tavern:raw_titanite
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    wolfram_ore:
      type: green_tavern:wolfram_ore
      items:
        raw_wolfram:
          item: green_tavern:raw_wolfram
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    orichalcum_ore:
      type: green_tavern:orichalcum_ore
      items:
        raw_wolfram:
          item: green_tavern:orichalcum_nugget
          min_amount: 2
          max_amount: 5
          chance: 100
      exp:
        exp_1:
          min_amount: 10
          max_amount: 18
          chance: 100
    mythril_ore:
      type: green_tavern:mythril_ore
      items:
        raw_mythril:
          item: green_tavern:raw_mythril
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    magic_crystals_ore:
      type: green_tavern:magic_crystals_ore
      items:
        magic_crystal:
          item: green_tavern:magic_crystal
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    deepslate_orcish_iron_ore:
      type: green_tavern:deepslate_orcish_iron_ore
      items:
        raw_orcish_iron:
          item: green_tavern:raw_orcish_iron
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 0
          max_amount: 3
          chance: 100
    deepslate_titanite_ore:
      type: green_tavern:deepslate_titanite_ore
      items:
        raw_titanite:
          item: green_tavern:raw_titanite
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    deepslate_wolfram_ore:
      type: green_tavern:deepslate_wolfram_ore
      items:
        raw_wolfram:
          item: green_tavern:raw_wolfram
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    deepslate_mythril_ore:
      type: green_tavern:deepslate_mythril_ore
      items:
        raw_mythril:
          item: green_tavern:raw_mythril
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
    deepslate_magic_crystals_ore:
      type: green_tavern:deepslate_magic_crystals_ore
      items:
        magic_crystal:
          item: green_tavern:magic_crystal
          min_amount: 1
          max_amount: 1
          chance: 100
      exp:
        exp_1:
          min_amount: 1
          max_amount: 3
          chance: 100
items:
  raw_orcish_iron:
    display_name: Рудное орочье железо
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/raw_orcish_iron.png
  raw_titanite:
    display_name: Рудный титанит
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/raw_titanite.png
  raw_wolfram:
    display_name: Рудный вольфрам
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/raw_wolfram.png
  raw_mythril:
    display_name: Рудный мифрил
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/raw_mythril.png
  orcish_steel_ingot:
    display_name: Слиток орочьей стали
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/orcish_steel_ingot.png
  titanite_ingot:
    display_name: Титанитовый слиток
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/titanite_ingot.png
  wolfram_ingot:
    display_name: Вольфрамовый слиток
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/wolfram_ingot.png
  mythril_ingot:
    display_name: Мифриловый слиток
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/mythril_ingot.png
  magic_crystal:
    display_name: Магический кристалл
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/magic_crystal.png
  orichalcum_ingot:
    display_name: Орихалковый слиток
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/orichalcum_ingot.png
  orichalcum_nugget:
    display_name: Орихалковый самородок
    permission: custom_ores_use
    resource:
      material: NETHERITE_SCRAP
      generate: true
      textures:
      - item/orichalcum_nugget.png
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=nWFU0VLyUV0
https://www.youtube.com/watch?v=iLr1tyG7shg

**Comment by LoneDev6** [comment]
> : Error occurred while enabling ItemsAdder v2.4.19 (Is it up to date?)

update the plugin

**Comment by NewJeb** [comment]
> > : Error occurred while enabling ItemsAdder v2.4.19 (Is it up to date?)
> 
> update the plugin

Well, I realized that with CMI there may be a problem due to the version, but other problems are that!
