### ISSUE TITLE
Emotes dont work correctly

### ISSUE THREAD

**Issue by MrHarebug** [PluginBugs/Issues-ItemsAdder#1355]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

MrHarebug#7486

### What happened?

I added some custom emotes. When Im trying use it in format :emote name: in chat dont work but if I use /e and TAB emote then emote show (Also in /e book GUI emote show correct)

### Steps to reproduce the issue

1. /emoji - show emoji on first page
2. When I try use some custom added emoji in chat in format :emoji: dont work
3. Other emoji like Minecraft and Twitter work correct

### Server version

This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 2.4.23

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.15

### LightAPI Version (optional)

LightAPI version 3.5.2

### FULL server log

[04:24:47] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:24:47] [main/INFO]: Reloading ResourceManager: Default, bukkit
[04:24:48] [Worker-Main-5/INFO]: Loaded 7 recipes
[04:24:49] [Server thread/INFO]: Starting minecraft server version 1.16.5
[04:24:49] [Server thread/INFO]: Loading properties
[04:24:49] [Server thread/INFO]: This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[04:24:49] [Server thread/INFO]: Debug logging is disabled
[04:24:49] [Server thread/INFO]: Using 4 threads for Netty based IO
[04:24:49] [Server thread/INFO]: Server Ping Player Sample Count: 12
[04:24:49] [Server thread/INFO]: Default game type: SURVIVAL
[04:24:49] [Server thread/INFO]: Generating keypair
[04:24:49] [Server thread/INFO]: Starting Minecraft server on *:
[04:24:49] [Server thread/INFO]: Using default channel type
[04:24:50] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.89
[04:24:50] [Server thread/INFO]: [LoneLibs] Loading LoneLibs v1.0.15
[04:24:50] [Server thread/INFO]: [LightAPI] Loading LightAPI v3.5.2
[04:24:51] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.10
[04:24:51] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0
[04:24:51] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v2.4.23
[04:24:51] [Server thread/INFO]: [ScreenEffects] Loading ScreenEffects v1.0.7
[04:24:51] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:24:51] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.89
[04:24:52] [Server thread/INFO]:         __    
[04:24:52] [Server thread/INFO]:   |    |__)   LuckPerms v5.3.89
[04:24:52] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[04:24:52] [Server thread/INFO]: 
[04:24:52] [Server thread/INFO]: [LuckPerms] Loading configuration...
[04:24:52] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[04:24:53] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[04:24:53] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[04:24:53] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1349ms)
[04:24:53] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.15
[04:24:53] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0
[04:24:53] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[04:24:53] [Server thread/INFO]: Preparing level "world"
[04:24:53] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[04:24:54] [Server thread/INFO]: Preparing spawn area: 0%
[04:24:54] [Server thread/INFO]: Time elapsed: 451 ms
[04:24:54] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[04:24:54] [Server thread/INFO]: Preparing spawn area: 0%
[04:24:54] [Server thread/INFO]: Time elapsed: 263 ms
[04:24:54] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[04:24:54] [Server thread/INFO]: Time elapsed: 152 ms
[04:24:54] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.5.2
[04:24:54] [Server thread/INFO]: [LightAPI] Loading CraftBukkit implementation for Paper server v1_16_R3.
[04:24:54] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.10
[04:24:54] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[04:24:54] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.4.23
[04:24:55] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 2.4.23
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.15
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-790 (MC: 1.16.5)
                                               
[04:24:55] [Server thread/INFO]: [ItemsAdder] LibsDisguises not installed, please install it to make custom mobs working: ci.md-5.net/job/LibsDisguises/
[04:24:55] [Server thread/WARN]: [ItemsAdder] (Liquids disabled. If you want to use liquids enable them in config.yml please)
[04:24:55] [Server thread/INFO]: [ScreenEffects] Enabling ScreenEffects v1.0.7
[04:24:55] [Server thread/INFO]: [ScreenEffects]     Extracting default effects from .jar
[04:24:55] [Server thread/INFO]: [ScreenEffects]       DONE extracting default effects from .jar
[04:24:55] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[04:24:55] [Server thread/INFO]: Running delayed init tasks
[04:24:55] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [Pack] Checking for online default resourcepack updates...
[04:24:55] [Server thread/INFO]: No expansions were registered!
[04:24:55] [Server thread/INFO]: Done (6.706s)! For help, type "help"
[04:24:55] [Server thread/INFO]: Timings Reset
[04:24:55] [Craft Scheduler Thread - 0/INFO]: [ItemsAdder] 
[04:24:55] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [Pack] No need to download default resourcepack. Cached file is up to date
[04:24:55] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] You can ignore this message: Can't connect to SpigotMC.org, probably internet connection is blocked.
[04:24:55] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] ( Server returned HTTP response code: 503 for URL: https://www.spigotmc.org/members/246338/ ) - 246338
[04:24:56] [Server thread/INFO]: [ItemsAdder] [Init] Loading YML files...
[04:24:59] [Server thread/INFO]: [ItemsAdder] [Init] Loading items_packs...
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Loaded 483 items
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 0/188 REAL block IDs. 
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 28/750 REAL_NOTE block IDs. 
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs. 
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs. 
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs. 
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] Used 625/6608 available max font_images. 
[04:25:00] [User Authenticator #1/INFO]: UUID of player MrHarebug is e333fdb3-6461-4fae-8b33-09122cdebc89
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [Init] Loaded 40 categories
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [Init] Loaded 483 items and stuff in 4339ms
[04:25:00] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [Pack] Checking resourcepack url... 
[04:25:00] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img
[04:25:00] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat
[04:25:00] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[04:25:02] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (external-host). Url: deleted
[04:25:04] [Server thread/INFO]: MrHarebug joined the game
[04:25:04] [Server thread/INFO]: MrHarebug[/] logged in with entity id 128 at ([world]-182.74576216332542, 65.0, 5.213694229565236)
[04:25:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8144ms or 162 ticks behind
[04:25:06] [Server thread/INFO]: -------< LightAPI-fork 3.5.2 >-------
[04:25:06] [Server thread/INFO]: You are running the latest version!

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: deleted
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: "emoji"
font_images:
  3Head:
    permission: chat
    show_in_gui: true
    path: "font/emoji/3head.png"
    scale_ratio: 9
    y_position: 8
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot_477](https://user-images.githubusercontent.com/69869677/146119316-4399fc9b-883e-439b-b315-06b93899995b.png)
![Screenshot_468](https://user-images.githubusercontent.com/69869677/146119324-51e6ada5-5de7-4d6e-affd-20fd9d577242.png)
![Screenshot_463](https://user-images.githubusercontent.com/69869677/146119338-455a28ea-d4a5-4d1a-979b-91f268d0c6b0.png)
![Screenshot_480](https://user-images.githubusercontent.com/69869677/146119396-8e1fbcbf-3aed-4a67-ba21-7b1c2fa1d388.png)

**Comment by LoneDev6** [comment]
do you have any plugin which interferes with the chat?
the placeholders should work fine..

**Comment by MrHarebug** [comment]
Hello.
Server updated to **Paper version git-Paper-76 (MC: 1.18.1)** and also every plugin to latest version. I dont have any plugin to chat. Screenshot with all plugin is in top.

**Comment by LoneDev6** [comment]
Update also ProtocolLib

**Comment by MrHarebug** [comment]
ProtocolLib version 4.8.0-SNAPSHOT-b538
- still dont work

**Comment by MrHarebug** [comment]
So? What now?

**Comment by MrHarebug** [comment]
Edit: after update to 1.18 some another think stops working...
ScreenEffect Addon: Error:
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.ScreenEffects.a.c.a(org.bukkit.entity.Player, float)" because "dev.lone.ScreenEffects.a.a.a().a" is null

- Emotes dont work only in chat... in books and signs Twitter and Minecraft emotes work correctly... Custom emotes what I add dont work in sign, chat, book.. but work if I use /e and TAB emote.
Also <rw text> and <r text> dont work in chat.. work only on sign.

What is interesting:
- <rw text> <r text> Twitter and Minecraft emotes work in command like /say ... Custom emotes what show in /emoji book dont work.

**Comment by LoneDev6** [comment]
> So? What now?

Emojis work fine for me. You have to disable all plugins and check which one is interfering.
It's a common practice in server configuration. Disable all plugins (keep only ItemsAdder dependencies + ItemsAdder) until you find the one which is causing the incompatibility issue.

![immagine](https://user-images.githubusercontent.com/27242001/147233169-cc629105-066c-4962-af1e-6401f6d3cb7d.png)
`This server is running Paper version git-Paper-85 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: df8d28a)`

`ItemsAdder version 2.5.1-beta4`


> Edit: after update to 1.18 some another think stops working...

Do not use the same Github issue page to report different issues. 
Anyway you must always provide the full error not a part of it.

**Comment by MrHarebug** [comment]
Still dont work but look at this:
![Screenshot_507](https://user-images.githubusercontent.com/69869677/147288664-3e6b4b72-86ab-4f02-95b7-7285ff153eee.png)
First message is with OP and second with no OP... in second message is message without dots (:) but no emote.
Plugin list:
- ItemsAdder : 2.5.0-beta
- LightAPI : bukkit-5.1.0
- LoneLibs : 1.0.16b
- PlaceholderAPI : 2.10.10
- ProtocolLib : 4.8.0-SNAPSHOT-b538
- ScreenEffect : 1.0.7
Server version: This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Today latest version)

ScreenEffect error:
MrHarebug issued server command: /screeneffect fullscreen AQUA 10 10 10 nofreeze MrHarebug Welcome to my server!
[00:20:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'screeneffect' in plugin ScreenEffects v1.0.7
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.ScreenEffects.a.c.a(org.bukkit.entity.Player, float)" because "dev.lone.ScreenEffects.a.a.a().a" is null
at dev.lone.ScreenEffects.a.a.a(SourceFile:63) ~[ScreenEffects.jar:?]
at dev.lone.ScreenEffects.a.a(SourceFile:165) ~[ScreenEffects.jar:?]
at dev.lone.ScreenEffects.a.onCommand(SourceFile:153) ~[ScreenEffects.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
... 21 more
I can open new ticket if you want about ScreenEffect.
Thanks

**Comment by LoneDev6** [comment]
Are you sure you added the correct permissions?
https://itemsadder.devs.beer/plugin-usage/permissions/example-permissions

Permission to replace emoji text :smile: etc in chat
`ia.user.image.chat`

Permissions to use emojis
`ia.user.image.use.smile`
`ia.user.image.use.<emoji name here>`

**Comment by LoneDev6** [comment]
> I can open new ticket if you want about ScreenEffect.

yes

**Comment by MrHarebug** [comment]
I have OP and ia.* and ia.user.image.use.* and nothing.

**Comment by LoneDev6** [comment]
Which chat plugin are you using?

**Comment by MrHarebug** [comment]
I dont use any chat plugin.
Plugin list:

    ItemsAdder : 2.5.0-beta
    LightAPI : bukkit-5.1.0
    LoneLibs : 1.0.16b
    PlaceholderAPI : 2.10.10
    ProtocolLib : 4.8.0-SNAPSHOT-b538
    ScreenEffect : 1.0.7
    Server version: This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Today latest version)

^^ This list is 14 day ago

**Comment by emielderckx** [comment]
I think I have the same problem it works with `/say` but in normal chat it doesn't work

(I have itemsadder, lightapi, lonelibs, protocollib and luckperms installed atm)

**Comment by LoneDev6** [comment]
The problem is that I tested with no plugin and it works fine.
I tested with EssentialsX and ChatControl red and it works fine.

There is something in your server which is interfering with the chat.

**Comment by MrHarebug** [comment]
I have only your plugin on the server.. nothing more and still doesnt work,

**Comment by Klein-76** [comment]
I have the same problem that Emoji is not displayed in chat

**Comment by LoneDev6** [comment]
Read here and let me know, thanks

https://github.com/PluginBugs/Issues-ItemsAdder/issues/1518
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1506

**Comment by TheArmagan** [comment]
same bug here

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1518#issuecomment-1059284175
> Solution found by changing chat plugin to **Venturechat**


https://github.com/PluginBugs/Issues-ItemsAdder/issues/1506#issuecomment-1056039473
> try this plugin https://github.com/FlickerProjects/TrChat/releases/tag/latest
