### ISSUE TITLE
Can't mark file as compressed

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1383]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

the plugin stop zip any new items and i have to restart the server - Error https://paste.md-5.net/pelefecanu.md
i also saw this Permission denied so i also used this | 
![image](https://user-images.githubusercontent.com/68678154/147633495-cc564377-2d28-4828-979a-2d67de42e1fd.png)
but we are using  | ->  java 17
![image](https://user-images.githubusercontent.com/68678154/147633554-2140ce42-9a3c-44ab-9347-fb48d6761971.png)

### Steps to reproduce the issue

1 - iazip

### Server version

![image](https://user-images.githubusercontent.com/68678154/147633668-f400cba6-4db3-4500-9a6d-2c1e7d405300.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/68678154/147633688-6d905bf8-82d8-4568-b5cf-cc79978b0b30.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/68678154/147633697-d95cb9d4-7148-41c6-ac55-c4c0509c3a49.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/68678154/147633708-62d7297b-034c-4910-b848-37dd850925d4.png)

**Comment by SNokerYT** [comment]
```
[23:19:57 WARN]: [ItemsAdder] Plugin ItemsAdder v2.5.1-beta4 generated an exception while executing task 32371
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.main.bo.getNamespace()" because "this.c" is null
at dev.lone.itemsadder.main.gc.aw(SourceFile:169) ~[ItemsAdder (57).jar:?]
at dev.lone.itemsadder.main.gm.a(SourceFile:365) ~[ItemsAdder (57).jar:?]
at dev.lone.itemsadder.main.az.a(SourceFile:2180) ~[ItemsAdder (57).jar:?]
at dev.lone.itemsadder.main.at.a(SourceFile:91) ~[ItemsAdder (57).jar:?]
at dev.lone.itemsadder.main.az.a(SourceFile:2003) ~[ItemsAdder (57).jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-117]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-117]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-117]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
For some reason an item failed to load and it's NULL, so the plugin breaks at some point.
I need your full log.

**Comment by LoneDev6** [comment]
The `--illegal-access-permit` option has nothing to do with the error you posted

**Comment by SNokerYT** [comment]
for now, you can close this ticket, it was happening when I add new armor, so when I test it again I will reply to this ticket
because i don't have the full log right now

**Comment by LoneDev6** [comment]
I can read: `Permission denied`
It seems your uploaded files have a different owner than the user who runs the server jar.

For example you uploaded the files with `admin` account  and run the jar with `root`

**Comment by LoneDev6** [comment]
I'd avoid using this tool.

You can't be sure the server doesn't break between updates.
It's a must to check the Spigot/Paper changelog each time you update the server before opening it to the public.
