### ISSUE TITLE
/Iazip command error

### ISSUE THREAD

**Issue by Klein-76** [PluginBugs/Issues-ItemsAdder#1384]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

klein#6189

### What happened?

After using the / iazip command, the second time you use the / iazip command, an error occurs and the files in the rescource are deleted

### Steps to reproduce the issue

1. Start the server
2. Use the / iazip command
3. Use the / iazip command again

### Server version

Purpur version git-Purpur-1428 (MC: 1.17.1)

### ItemsAdder Version

ItemsAdder version 2.5.1-beta4

### ProtocolLib Version

 ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.16b

### Error (optional)

```shell
[01:16:56 INFO]: [ItemsAdder] Error calculating font_image 'magiccraft:mana_bar_3' dimensions
[01:16:56 WARN]: javax.imageio.IIOException: Can't create an ImageOutputStream!
[01:16:56 WARN]:        at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1553)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aF.a(SourceFile:356)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aF.<init>(SourceFile:169)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aG.p(SourceFile:106)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.az.b(SourceFile:596)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.az.a(SourceFile:530)
[01:16:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:103)
[01:16:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1591)
[01:16:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:528)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1300)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[01:16:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:16:56 WARN]: java.io.FileNotFoundException: D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\4.png (拒绝访问。)
[01:16:56 WARN]:        at java.base/java.io.RandomAccessFile.open0(Native Method)
[01:16:56 WARN]:        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
[01:16:56 WARN]:        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
[01:16:56 WARN]:        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
[01:16:56 WARN]:        at java.desktop/javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)[01:16:56 WARN]:        at java.desktop/com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
[01:16:56 WARN]:        at java.desktop/javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:421)
[01:16:56 WARN]:        at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1551)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aF.a(SourceFile:356)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aF.<init>(SourceFile:169)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aG.p(SourceFile:106)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.az.b(SourceFile:596)
[01:16:56 WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.az.a(SourceFile:530)
[01:16:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:103)
[01:16:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1591)
[01:16:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:528)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1300)
[01:16:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[01:16:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\example\textures\font\tags\cutie.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\example\textures\font\tags\cutie.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\coffee_machine_left.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\coffee_machine_left.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\coffee_machine_right.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\coffee_machine_right.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\customization_table_left.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\customization_table_left.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\customization_table_right.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\customization_table_right.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_converter_left.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_converter_left.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_converter_right.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_converter_right.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_extractor_left.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_extractor_left.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_extractor_right.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\energy_extractor_right.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\vending_machine_left.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\vending_machine_left.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\vending_machine_right.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\itemsadder\textures\gui\vending_machine_right.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\0.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\0.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\1.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\1.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\2.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\2.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\3.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\3.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\4.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\4.png
[01:16:57 ERROR]: [ItemsAdder] Error stripping metadata of file 'D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\5.png': D:\test\plugins\ItemsAdder\data\resource_pack\assets\magiccraft\textures\font\hud\mana_bar\5.png
```

### ItemsAdder config.yml

```shell
default
```

### Problematic items yml configuration file (optional)

```shell
default
```

### Screenshots/Videos (you can drag and drop files or paste links)

![QQ图片20211231012304](https://user-images.githubusercontent.com/76739381/147774293-6d75c04d-dd99-49a0-a3ac-9adf1fa6d8d8.png)
![QQ图片20211231012402](https://user-images.githubusercontent.com/76739381/147774358-7cc5bf5c-8715-4134-8e28-4524d7635139.png)

**Comment by LoneDev6** [comment]
For some reason your java installation cannot find a suitable implementation to handle PNG files, this is strange.
