### ISSUE TITLE
CustomCrafting compatibility

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#1397]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

**Any custom item or armor, for example, copper armor and copper tools, I created them, they have IRON_PICKAXE material initially, if I combine them in a workbench, I will get RESULT = IRON_PICKAXE, although I connected copper tools together, the same with armor. And if, for example, I take a custom ore (RUBY) under the material: PAPER, then I can add skin to rubies and get = A BOOK!!! FIX IT!**

### Steps to reproduce the issue

**Any custom item or armor, for example, copper armor and copper tools, I created them, they have IRON_PICKAXE material initially, if I combine them in a workbench, I will get RESULT = IRON_PICKAXE, although I connected copper tools together, the same with armor. And if, for example, I take a custom ore (RUBY) under the material: PAPER, then I can add skin to rubies and get = A BOOK!!! FIX IT!**

### Server version

This server is running Paper version git-Paper-136 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9a47cf1)
You are running the latest version
Previous version: git-Paper-134 (MC: 1.18.1)

### ItemsAdder Version

ItemsAdder version 2.5.2

### ProtocolLib Version

ProtocoLib version 4.8.0-b539

### LoneLibs Version

LoneLibs version 1.0.16b

### FULL server log

No error log

**Comment by LoneDev6** [comment]
Please test this without any other plugin installed on your server.
Also provide a video.
Thanks

**Comment by MrJorman** [comment]
```[02:16:16 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v2.5.2
java.lang.NoClassDefFoundError: me/wolfyscript/customcrafting/recipes/types/CustomRecipe
        at dev.lone.itemsadder.main.fj.a(SourceFile:265) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-136]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1339) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[?:?]
        at net.minecraft.world.inventory.InventoryMenu.slotsChanged(InventoryMenu.java:141) ~[?:?]
        at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:141) ~[?:?]
        at net.minecraft.world.inventory.Slot.set(Slot.java:61) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.world.inventory.InventoryMenu.quickMoveStack(InventoryMenu.java:206) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:528) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:371) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-136]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.wolfyscript.customcrafting.recipes.types.CustomRecipe
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 30 more
        ```

**Comment by LoneDev6** [comment]
I didn't know you was trying to create a CustomCrafting recipe.
Please be more specific when you create issue reports.


I'll try to add compatibility in the next days. Thanks.
Seems CustomCrafting updated their API code again.
