### ISSUE TITLE
ScreenEffects stop working after update to 1.18.1

### ISSUE THREAD

**Issue by SentixDev** [PluginBugs/Issues-ItemsAdder#1403]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Sentix#1337

### What happened?

I upgraded my server to 1.18.1 and saw that ScreenEffects isnt working anymore and throws a nullpointer:

Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.ScreenEffects.a.c.a(org.bukkit.entity.Player, float)" because "dev.lone.ScreenEffects.a.a.a().a" is null
        at dev.lone.ScreenEffects.a.a.a(SourceFile:63) ~[ScreenEffects.jar:?]
        at dev.lone.ScreenEffects.a.a(SourceFile:165) ~[ScreenEffects.jar:?]
        at dev.lone.ScreenEffects.a.onCommand(SourceFile:153) ~[ScreenEffects.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more

### Steps to reproduce the issue

1. Setup a server with 1.18.1-Purpur-1497
2. Install ItemsAdder 2.5.2
3. Install ScreenEffects
4. Use the screeneffects commands

### Server version

This server is running Purpur version git-Purpur-1497 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9c51f21 on HEAD)

### ItemsAdder Version

ItemsAdder version 2.5.2

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b540

### LoneLibs Version

LoneLibs version 1.0.16b

### FULL server log

No error shown, beside the nullpointer on use

### Error (optional)

```shell
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.ScreenEffects.a.c.a(org.bukkit.entity.Player, float)" because "dev.lone.ScreenEffects.a.a.a().a" is null
        at dev.lone.ScreenEffects.a.a.a(SourceFile:63) ~[ScreenEffects.jar:?]
        at dev.lone.ScreenEffects.a.a(SourceFile:165) ~[ScreenEffects.jar:?]
        at dev.lone.ScreenEffects.a.onCommand(SourceFile:153) ~[ScreenEffects.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    disable-overwrite-leather-armor-layers-textures: false
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: -
      pack-port: -
    external-host:
      enabled: false
      url:
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
```

**Comment by LoneDev6** [comment]
Download the new ScreenEffects version
