### ISSUE TITLE
Itemsadder not enabling or working properly

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1432]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I get this error, I assume I configured something incorrectly but it doesn't show which file.

[14:35:30 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[14:35:30 WARN]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 5 column 4 path $.item.color
[14:35:30 WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:60)
[14:35:30 WARN]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:85)
[14:35:30 WARN]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:60)
[14:35:30 WARN]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[14:35:30 WARN]: 	at com.google.gson.JsonParser.parse(JsonParser.java:98)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.eF.<init>(SourceFile:34)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.eE.a(SourceFile:146)
[14:35:30 WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.eE.a(SourceFile:146)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.az.b(SourceFile:2134)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.az.b(SourceFile:613)
[14:35:30 WARN]: 	at ItemsAdder_2.5.4-beta2.jar//dev.lone.itemsadder.main.az.a(SourceFile:530)
[14:35:30 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:103)
[14:35:30 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:35:30 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574)
[14:35:30 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[14:35:30 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1497)
[14:35:30 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
[14:35:30 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[14:35:30 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:35:30 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 5 column 4 path $.item.color
[14:35:30 WARN]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
[14:35:30 WARN]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
[14:35:30 WARN]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
[14:35:30 WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:725)
[14:35:30 WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701)
[14:35:30 WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:48)
[14:35:30 WARN]: 	... 19 more

### Steps to reproduce the issue

I don't know what is causing it yet

### Server version

purpur build 1508

### ItemsAdder Version

2.5.4-beta2

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
Seems one of your recently added .json files is malformed, this causes ItemsAdder to fail to load it.
You can enable more logs in config.yml of the plugin to know which item has failed to load.
