### ISSUE TITLE
Task #1103 Failed

### ISSUE THREAD

**Issue by ConaII** [PluginBugs/Issues-ItemsAdder#1488]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

ConaII#1154

### What happened?

N/A

### Steps to reproduce the issue

N/A

### Server version

Pufferfish git-Pufferfish-8 (MC: 1.17.1)
(Pufferfish-purpur)

### ItemsAdder Version

ItemsAdder_2.5.5

### ProtocolLib Version

ProtocolLib-4.7.0 build 540

### LoneLibs Version

LoneLibs-1.0.16b

### LightAPI Version (optional)

LightAPI-Bukkit-5.1.0

### LibsDisguises Version (optional)

LibsDisguises build 1047

version: 10.0.27-SNAPSHOT 
build-date: 02/02/2022 07:16
build-number: 1053 

### Error (optional)

```shell
[21:49:11] [Server thread/WARN]: [ItemsAdder] Task #1103 for ItemsAdder v2.5.5 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at dev.lone.itemsadder.main.aV.n(SourceFile:63) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.bd.q(SourceFile:88) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.bd.u(SourceFile:114) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.be.f(SourceFile:293) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.be.C(SourceFile:168) ~[ItemsAdder_2.5.5.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1584) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:506) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1500) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:323) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Will be fixed in 3.0.1
