### ISSUE TITLE
Unhandled exception occured in onPacketSending

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#1509]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Anto'#1234

### What happened?

Randomly happen, itemsadder throw an error.

### Steps to reproduce the issue

Don't know.

### Server version

This server is running Pufferfish version git-Pufferfish-47 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a786526 on HEAD)
You are on the latest version!
Previous version: git-Purpur-1565 (MC: 1.18.1)

### ItemsAdder Version

ItemsAdder 2.5.5

### ProtocolLib Version

ProtocolLib 4.8.0-SNAPSHOT-b545

### LoneLibs Version

Lonelibs version 1.0.16b

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build snapshot)

### FULL server log

[15:20:01 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
        at dev.lone.itemsadder.main.hl.onPacketSending(SourceFile:123) ~[ItemsAdder_2.5.5.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2023) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2009) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:241) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:257) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at com.bgsoftware.superiorskyblock.lang.Message$1.send(Message.java:710) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at com.bgsoftware.superiorskyblock.lang.Message.lambda$send$0(Message.java:807) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.runIfOnline(SSuperiorPlayer.java:236) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at com.bgsoftware.superiorskyblock.lang.Message.send(Message.java:807) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$sendMessage$41(SIsland.java:1576) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.sendMessage(SIsland.java:1576) ~[SuperiorSkyblock2-1.8.4.jar:?]
        at fr.centurygroup.earthcore.generator.tasks.UpdateGeneratorTask.lambda$run$0(UpdateGeneratorTask.java:33) ~[EarthCore-2.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.centurygroup.earthcore.generator.tasks.UpdateGeneratorTask.run(UpdateGeneratorTask.java:24) ~[EarthCore-2.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:20:01 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutChat@72ecf967[
    a=TextComponent{text='', siblings=[TextComponent{text='G', siblings=[], style=Style{ color=#46B2F6, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='é', siblings=[], style=Style{ color=#44AFF3, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='n', siblings=[], style=Style{ color=#41ADF1, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='é', siblings=[], style=Style{ color=#3FAAEE, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='r', siblings=[], style=Style{ color=#3DA7EB, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='a', siblings=[], style=Style{ color=#3BA4E8, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='t', siblings=[], style=Style{ color=#39A1E5, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='e', siblings=[], style=Style{ color=#369FE3, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='u', siblings=[], style=Style{ color=#349CE0, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='r ', siblings=[], style=Style{ color=#3299DD, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='◆ ', siblings=[], style=Style{ color=gray, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='Votre générateur vient de générer une nouvelle ressource.', siblings=[], style=Style{ color=white, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

**Comment by LoneDev6** [comment]
will be fixed in 3.0
