### ISSUE TITLE
Water crash

### ISSUE THREAD

**Issue by LozoTrioxide** [PluginBugs/Issues-ItemsAdder#1510]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Lozo#0001

### What happened?

When using https://www.spigotmc.org/resources/liquids-colored-liquids-itemsadder-addon.84386/, placing, picking up and placing a block on top of the source of the custom water causes an error. 

Also if you let the water flow a chunk update error occurs and either the player gets disconnected or the server crashes

The colour of the block also doesnt work outright, So the errors on the wiki are not the same as this issue

### Steps to reproduce the issue

(1.18)
Install ItemsAdder
Install the liquid plugin
Try placing the liquid, putting a block on the source, or picking up the liquid

### ItemsAdder Version

[18:24:33 INFO]: ItemsAdder version 2.5.5
[18:24:33 INFO]: Customized Minecraft without client mods!
[18:24:33 INFO]: Website: devs.beer
[18:24:33 INFO]: Author: LoneDev

### ProtocolLib Version

[18:24:48 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[18:24:48 INFO]: Provides read/write access to the Minecraft protocol.
[18:24:48 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[18:24:58 INFO]: LoneLibs version 1.0.16b
[18:24:58 INFO]: Collection of libs used by my plugins
[18:24:58 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

[18:25:07 INFO]: LightAPI version bukkit-5.1.0 (build SNAPSHOT)
[18:25:07 INFO]: Bukkit library for edit light levels
[18:25:07 INFO]: Website: https://github.com/BeYkeRYkt/LightAPI
[18:25:07 INFO]: Authors: BeYkeRYkt and other contributors in GitHub

### LibsDisguises Version (optional)

[18:25:19 INFO]: LibsDisguises version 10.0.27
[18:25:19 INFO]: A disguise plugin with various disguises.
[18:25:19 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8155355/latest.log)

### Error (optional)

```shell
Placing block on top of source error:

[18:10:30 ERROR]: Could not pass event BlockPlaceEvent to ItemsAdder v2.5.5
org.apache.commons.lang.NotImplementedException: Not implemented!
        at dev.lone.itemsadder.NMS.DimensionsWrapper.impl.v1_18_R1.a(SourceFile:105) ~[ItemsAdder_2.5.5.jar:?]
        at dev.lone.itemsadder.main.cp.a(SourceFile:371) ~[ItemsAdder_2.5.5.jar:?]
        at dev.lone.itemsadder.main.cp.j(SourceFile:69) ~[ItemsAdder_2.5.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-197]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:373) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:601) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Filling bucket error:
[18:01:37 ERROR]: Could not pass event PlayerBucketFillEvent to ItemsAdder v2.5.5
org.apache.commons.lang.NotImplementedException: Not implemented!
        at dev.lone.itemsadder.NMS.DimensionsWrapper.impl.v1_18_R1.a(SourceFile:105) ~[ItemsAdder_2.5.5.jar:?]
        at dev.lone.itemsadder.main.cp.a(SourceFile:371) ~[ItemsAdder_2.5.5.jar:?]
        at dev.lone.itemsadder.main.cp.a(SourceFile:105) ~[ItemsAdder_2.5.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-197]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:486) ~[paper-1.18.1.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:462) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.world.item.BucketItem.use(BucketItem.java:75) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:475) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:492) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1913) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Chunk Error:
[00:09:18 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseItem@590d424 for LozoTrioxide[/82.22.231.3:55485]
net.minecraft.ReportedException: Getting biome
        at net.minecraft.world.level.chunk.ChunkAccess.getNoiseBiome(ChunkAccess.java:451) ~[?:?]
        at net.minecraft.world.level.LevelReader.getNoiseBiome(LevelReader.java:57) ~[?:?]
        at net.minecraft.world.level.biome.BiomeManager.getBiome(BiomeManager.java:78) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.world.level.LevelReader.getBiome(LevelReader.java:36) ~[?:?]
        at net.minecraft.advancements.critereon.LocationPredicate.matches(LocationPredicate.java:89) ~[?:?]
        at net.minecraft.advancements.critereon.ItemUsedOnBlockTrigger$TriggerInstance.matches(ItemUsedOnBlockTrigger.java:48) ~[?:?]
        at net.minecraft.advancements.critereon.ItemUsedOnBlockTrigger.lambda$trigger$0(ItemUsedOnBlockTrigger.java:30) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:62) ~[?:?]
        at net.minecraft.advancements.critereon.ItemUsedOnBlockTrigger.lambda$trigger$0(ItemUsedOnBlockTrigger.java:30) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:608) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 3.
        at net.minecraft.world.level.chunk.LinearPalette.valueFor(LinearPalette.java:75) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer.get(PalettedContainer.java:191) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer.get(PalettedContainer.java:186) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunkSection.getNoiseBiome(LevelChunkSection.java:195) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkAccess.getNoiseBiome(ChunkAccess.java:443) ~[?:?]
        ... 26 more
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: true
    self-host:
      enabled: false
      server-ip: 45.86.168.163
      pack-port: 40124
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: true
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
      - MUSHROOM
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: true
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

**Comment by LoneDev6** [comment]
What is your server version?
Update to 1.18.1 if it's 1.18.

**Comment by LozoTrioxide** [comment]
I'm on 1.18.1

**Comment by LoneDev6** [comment]
Dupicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/1464
