### ISSUE TITLE
BlockBreakEvent Error

### ISSUE THREAD

**Issue by EchocallingEarth** [PluginBugs/Issues-ItemsAdder#1517]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When I break a IA block it spams the console with the following error

[Server thread/ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.0.1-beta2
java.lang.NoSuchMethodError: 'net.minecraft.world.level.material.FluidType net.minecraft.server.level.WorldServer.b_(net.minecraft.core.BlockPosition)'
	at dev.lone.itemsadder.NMS.BlockUtil.impl.v1_18_R1.D(SourceFile:252) ~[ItemsAdder_3.0.1-beta3.jar:?]
	at dev.lone.itemsadder.main.cE.b(SourceFile:657) ~[ItemsAdder_3.0.1-beta3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1565]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:238) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1838) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1398) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

This only occurs with ItemsAdder blocks/addon blocksan

### Steps to reproduce the issue

Simply use the latest Beta release.the 

### Server version

git-Purpur-1565 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ea44ea1 on HEAD)

### ItemsAdder Version

3.0.1-beta2

### ProtocolLib Version

ProtocolLib v4.8.0-SNAPSHOT-b539

### LoneLibs Version

v1.0.17

### LightAPI Version (optional)

vbukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

v10.0.27-SNAPSHOT

### FULL server log

https://pastebin.com/Lsfjr9a8

### Error (optional)

```shell
[12:28:47] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.0.1-beta2
java.lang.NoSuchMethodError: 'net.minecraft.world.level.material.FluidType net.minecraft.server.level.WorldServer.b_(net.minecraft.core.BlockPosition)'
	at dev.lone.itemsadder.NMS.BlockUtil.impl.v1_18_R1.D(SourceFile:252) ~[ItemsAdder_3.0.1-beta3.jar:?]
	at dev.lone.itemsadder.main.cE.b(SourceFile:657) ~[ItemsAdder_3.0.1-beta3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1565]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:238) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1838) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1398) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 65.101.47.170
      pack-port: 8192
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 1
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BADLANDS
      - BADLANDS_PLATEAU
      - BAMBOO_JUNGLE
      - BAMBOO_JUNGLE_HILLS
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - BIRCH_FOREST_HILLS
      - COLD_OCEAN
      - DARK_FOREST
      - DARK_FOREST_HILLS
      - DEEP_COLD_OCEAN
      - DEEP_FROZEN_OCEAN
      - DEEP_LUKEWARM_OCEAN
      - DEEP_OCEAN
      - DEEP_WARM_OCEAN
      - DESERT
      - DESERT_HILLS
      - DESERT_LAKES
      - END_BARRENS
      - END_HIGHLANDS
      - END_MIDLANDS
      - ERODED_BADLANDS
      - FLOWER_FOREST
      - FOREST
      - FROZEN_OCEAN
      - FROZEN_RIVER
      - GIANT_SPRUCE_TAIGA
      - GIANT_SPRUCE_TAIGA_HILLS
      - GIANT_TREE_TAIGA
      - GIANT_TREE_TAIGA_HILLS
      - GRAVELLY_MOUNTAINS
      - ICE_SPIKES
      - JUNGLE
      - JUNGLE_EDGE
      - JUNGLE_HILLS
      - LUKEWARM_OCEAN
      - MODIFIED_BADLANDS_PLATEAU
      - MODIFIED_GRAVELLY_MOUNTAINS
      - MODIFIED_JUNGLE
      - MODIFIED_JUNGLE_EDGE
      - MODIFIED_WOODED_BADLANDS_PLATEAU
      - MOUNTAIN_EDGE
      - MOUNTAINS
      - MUSHROOM_FIELD_SHORE
      - MUSHROOM_FIELDS
      - OCEAN
      - PLAINS
      - RIVER
      - SAVANNA
      - SAVANNA_PLATEAU
      - SHATTERED_SAVANNA
      - SHATTERED_SAVANNA_PLATEAU
      - SMALL_END_ISLANDS
      - SNOWY_BEACH
      - SNOWY_MOUNTAINS
      - SNOWY_TAIGA
      - SNOWY_TAIGA_HILLS
      - SNOWY_TAIGA_MOUNTAINS
      - SNOWY_TUNDRA
      - STONE_SHORE
      - SUNFLOWER_PLAINS
      - SWAMP
      - SWAMP_HILLS
      - TAIGA
      - TAIGA_HILLS
      - TAIGA_MOUNTAINS
      - TALL_BIRCH_FOREST
      - TALL_BIRCH_HILLS
      - THE_VOID
      - WARM_OCEAN
      - WOODED_BADLANDS_PLATEAU
      - WOODED_HILLS
      - WOODED_MOUNTAINS
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 999
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Other files, you can drag and drop them here to upload. (optional)

If it helps here is a complete list of Plugins (85): 
AdvancedChests, AdvancedClaimGuardian, AdvancedEnchantments, AntiCurse, AureliumSkills, Bank, BetterConcrete, BetterPortals, BigDoors, BloodNight, Bookshelf, ChestSort, ChickenShedder, Chunky, Citizens, CitizensGUI, CleanroomGenerator, ClearFog, CMI, CMILib, ColorBundles, ConsoleSpamFix, Core, CraftBook, CustomCrafting, Denizen, DisplayShops, dtlTradersPlus, EpicBackpacks, FastAsyncWorldEdit (WorldEdit), FoodMasters, GadgetsMenu, GoatHorn, HaroTorch-V2, HeadDatabase, HolographicDisplays, HorseOverhaul, IABlockUpdater, ImageOnMap, InteractionVisualizer, InteractiveBoard, InteractiveBooks, Item-Chest-Sorter, ItemsAdder, Jobs, Leaves, LibsDisguises, LightAPI, LoneLibs, Lootin, LuckPerms, LWC, LWCTrust, MobColors, ModelEngine, MTVehicles, Multiverse-Core, MyPet, MythicCrucible, MythicMobs, NBTAPI, NetheriteShield, Nova, ntdLuckyBlock, PerWorldInventory, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib, PyroFishingPro, PyroLib, Sentinel, SimpleStack, SnowierSnow, spark, Spartan, SpectatorMode, SurvivalInvisiframes, TransportPipes, UltimateCatcher, UltimateTimber, VanillaTweaks, Vault, Wailat, WolfyUtilities, WorldGuard

**Comment by EchocallingEarth** [comment]
Forgot to include Discord info above:
EchocallingEarth#0001

**Comment by LoneDev6** [comment]
3.0.2 should have fixed this issue
