### ISSUE TITLE
auto_generated folder deletes itself and won't regen, if you have it open during the /iazip

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#1532]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

purejosh#2047

### What happened?

If you have the auto_generated folder open while running /iazip, it deletes itself and won't regen, causing the plugin to hang and requiring a server restart. 

### Steps to reproduce the issue

1. open auto_generated
2. run /iazip
3. cry

### Server version

This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
You are 41 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-76 (MC: 1.18.1)

### ItemsAdder Version

[22:39:54 INFO]: ItemsAdder version 2.5.5

### ProtocolLib Version

[22:39:41 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

[22:40:16 INFO]: LoneLibs version 1.0.16b

### FULL server log

[22:07:51 INFO]: purejosh issued server command: /iazip
[22:07:51 INFO]: [ItemsAdder] [Host] Started self-host webserver on port: 32105
[22:07:51 INFO]: [ItemsAdder] png file for font_image 'itemsadder:energy_extractor_left' not found. File not found: C:\Users\purejosh\Desktop\MCSS\servers\devserver\plugins\ItemsAdder/data/resource_pack/assets/itemsadder/textures/gui/energy_extractor_left.png
[22:07:51 INFO]: [ItemsAdder] png file for font_image 'itemsadder:energy_extractor_right' not found. File not found: C:\Users\purejosh\Desktop\MCSS\servers\devserver\plugins\ItemsAdder/data/resource_pack/assets/itemsadder/textures/gui/energy_extractor_right.png
[22:07:51 INFO]: [ItemsAdder] png file for font_image 'itemsadder:energy_converter_left' not found. File not found: C:\Users\purejosh\Desktop\MCSS\servers\devserver\plugins\ItemsAdder/data/resource_pack/assets/itemsadder/textures/gui/energy_converter_left.png
[22:07:51 INFO]: [ItemsAdder] png file for font_image 'itemsadder:energy_converter_right' not found. File not found: C:\Users\purejosh\Desktop\MCSS\servers\devserver\plugins\ItemsAdder/data/resource_pack/assets/itemsadder/textures/gui/energy_converter_right.png
[22:07:51 INFO]: [ItemsAdder] Ingredient not found OAK_PLANK in recipe diamond_shield file: \data\items_packs\pureweapons\shields.yml
[22:07:51 INFO]: [ItemsAdder] Result item pureweapons:gauntlet_gauntlet not found in crafting recipe recipes.crafting_table.gauntlet_gauntlet, file \data\items_packs\pureweapons\weapons.yml
[22:07:51 INFO]: [ItemsAdder] Can't find item named 'hamburger' to complete registration in file '\data\items_packs\itemsadder\furnitures.yml'
[22:07:51 INFO]: [ItemsAdder] Can't find item named 'hotdog' to complete registration in file '\data\items_packs\itemsadder\furnitures.yml'
[22:07:51 INFO]: [ItemsAdder] Loaded 1441 items
[22:07:51 INFO]: [ItemsAdder] Used 92/188 REAL block IDs. 
[22:07:51 INFO]: [ItemsAdder] Used 175/750 REAL_NOTE block IDs. 
[22:07:51 INFO]: [ItemsAdder] Used 19/63 REAL_TRANSPARENT block IDs. 
[22:07:51 INFO]: [ItemsAdder] Used 11/127 REAL_WIRE block IDs. 
[22:07:51 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs. 
[22:07:51 INFO]: [ItemsAdder] Used 570/6608 available max font_images. 
[22:07:51 INFO]: [ItemsAdder] Can't find item named 'itemsadder:bloody_mary' to complete registration in file '\data\items_packs\itemsadder\drinks.yml'
[22:07:51 INFO]: [ItemsAdder] [Init] Loaded 21 categories
[22:07:51 INFO]: [ItemsAdder] [Init] Loaded 1441 items and stuff in 337ms
[22:07:51 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[22:07:51 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[22:07:51 WARN]: [ItemsAdder] Plugin ItemsAdder v2.5.5 generated an exception while executing task 857
java.lang.IllegalArgumentException: File system element for parameter 'directory' does not exist: 'C:\Users\purejosh\Desktop\MCSS\servers\devserver\plugins\ItemsAdder\data\resource_pack\assets\pureweapons\models\auto_generated'
	at org.apache.commons.io.FileUtils.requireExists(FileUtils.java:2701) ~[commons-io-2.11.0.jar:2.11.0]
	at org.apache.commons.io.FileUtils.requireDirectoryExists(FileUtils.java:2650) ~[commons-io-2.11.0.jar:2.11.0]
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2091) ~[commons-io-2.11.0.jar:2.11.0]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:319) ~[commons-io-2.11.0.jar:2.11.0]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192) ~[commons-io-2.11.0.jar:2.11.0]
	at dev.lone.itemsadder.main.gK.a(SourceFile:349) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.az.a(SourceFile:2196) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.at.a(SourceFile:91) ~[ItemsAdder_2.5.5.jar:?]
	at dev.lone.itemsadder.main.az.a(SourceFile:2019) ~[ItemsAdder_2.5.5.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-175]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-175]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[MCSS] Your server will restart any moment now.

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 192.34.113.4
      pack-port: 32105
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: OPTIFINE
    disable-overwrite-leather-armor-layers-textures: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: true
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: true
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 70
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

**Comment by LoneDev6** [comment]
Will be fixed in the next version, thanks

**Comment by purejosh** [comment]
Thank you.
