### ISSUE TITLE
Itemsadder crashing when zipping

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#1570]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When running /iazip Itemsadder stopped responding

### Steps to reproduce the issue

1. /iazip

### Server version

This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 3.0.4

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### Error (optional)

```shell
[22:51:47 WARN]: [ItemsAdder] Plugin ItemsAdder v3.0.3-beta4 generated an exception while executing task 38182
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.toString()" because "this.a" is null
        at dev.lone.itemsadder.main.hl.d(SourceFile:76) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.hq.a(SourceFile:122) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.hq.<init>(SourceFile:86) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.ht.e(SourceFile:379) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.aA.a(SourceFile:2304) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.au.a(SourceFile:91) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at dev.lone.itemsadder.main.aA.a(SourceFile:2103) ~[ItemsAdder_3.0.3-beta4.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Do you remember the last file you added?
ItemsAdder failed to load a `.json` file, probably a model.

**Comment by MinecollYT** [comment]
I think it was an item with the automatic generation to true

**Comment by LoneDev6** [comment]
Automatic generation cannot break, it's surely a manually added json

**Comment by MinecollYT** [comment]
Nop. 100 % sure

**Comment by MinecollYT** [comment]
I think it was paper

**Comment by LoneDev6** [comment]
Please make sure to identify the correct material which causes this issue, you can enable logging in config.yml to know which item failed to load

**Comment by MinecollYT** [comment]
This issue hasn't happened since that. I can comment here again when this issue happens again
