### ISSUE TITLE
MMOItems integration no longer works

### ISSUE THREAD

**Issue by Zangerine** [PluginBugs/Issues-ItemsAdder#1575]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The MMOItems integration no longer works. You can link it up exactly like the wiki says but with the latest version of MMOItems and ItemsAdder it no longer links the items (MMOItems stats not on IA item).

### Steps to reproduce the issue

Try and use MMOItems integration with ItemsAdder.

### Server version

Current: git-Purpur-1587 (MC: 1.18.2)*
Previous: git-Purpur-1579 (MC: 1.18.2)
* You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

[20:38:36 INFO]: ItemsAdder version 3.0.4
[20:38:36 INFO]: Customized Minecraft without client mods!
[20:38:36 INFO]: Website: devs.beer
[20:38:36 INFO]: Author: LoneDev

### ProtocolLib Version

[20:38:57 INFO]: ProtocolLib version 4.8.0
[20:38:57 INFO]: Provides read/write access to the Minecraft protocol.
[20:38:57 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:39:11 INFO]: LoneLibs version 1.0.18
[20:39:11 INFO]: Collection of libs used by my plugins
[20:39:11 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
onyx_chestplate:
    display_name: "Onyx Chestplate"
    permission: onyx_chestplate
    mmoitem:
      type: ARMOR
      id: ONYX_CHESTPLATE
    resource:
      generate: true
      textures:
      - item/armor/onyx/onyx_chestplate
    specific_properties:
      armor:
        slot: chest
        custom_armor: onyx
```

**Comment by LoneDev6** [comment]
I wanted to test but I can't even load MMOItems and MythicLibs.
I guess they are currently broken. We have to wait the author to fix.
The armor should load just fine in normal conditions.

```
[16:05:20 ERROR]: Error occurred while enabling MythicLib v1.3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class io.lumine.mythic.lib.version.VersionMaterial
        at io.lumine.mythic.lib.api.crafting.uimanager.UIFilterManager.registerUIFilter(UIFilterManager.java:107) ~[MythicLib-1.3.jar:?]
        at io.lumine.mythic.lib.api.crafting.uifilters.VanillaUIFilter.register(VanillaUIFilter.java:185) ~[MythicLib-1.3.jar:?]
        at io.lumine.mythic.lib.api.crafting.recipes.MythicCraftingManager.<init>(MythicCraftingManager.java:56) ~[MythicLib-1.3.jar:?]
        at io.lumine.mythic.lib.MythicLib.enable(MythicLib.java:148) ~[MythicLib-1.3.jar:?]
        at io.lumine.mythic.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java:72) ~[MythicLib-1.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:05:20 INFO]: [MythicLib] Disabling MythicLib v1.3
[16:05:20 INFO]: [MMOItems] Enabling MMOItems v6.7.2
[16:05:20 ERROR]: Error occurred while enabling MMOItems v6.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: io/lumine/mythic/lib/version/SpigotPlugin
        at net.Indyuce.mmoitems.MMOItems.enable(MMOItems.java:160) ~[MMOItems-6.7.2.jar:?]
        at io.lumine.mythic.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java:73) ~[MythicMobs-5.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.lib.version.SpigotPlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
```

**Comment by Zangerine** [comment]
Both versions work perfectly fine for me so I have no idea why you're unable to load them up.

https://prnt.sc/SnbPdI5tUKT5

**Comment by LoneDev6** [comment]
I was using Mythicmobs 5.0.1, it seems to be the issue, MMOItems seems not to support this version.

Anyway I tested and your items loads just fine for me
![immagine](https://user-images.githubusercontent.com/27242001/160865318-924318d1-12b6-427a-b7c7-d667420c8e8f.png)


https://user-images.githubusercontent.com/27242001/160865449-e36d3121-27cd-403b-ae3c-b5e8b23bc54e.mp4

**Comment by Zangerine** [comment]
I cannot get it to work so I'll dump as much info as I can here. Maybe I'm doing something wrong?

Here is my **armor.yml** entry for the item. I have a corresponding MMOItem in the **ARMOR** category called **gilded_chestplate**.
`  gilded_chestplate:
    display_name: "Netherite Chestplate (G)"
    permission: gilded_netherite
    mmoitem:
      type: ARMOR
      id: gilded_chestplate
    resource:
      generate: true
      textures:
      - item/armor/gilded_netherite/chestplate
    durability:
      max_custom_durability: 1200
    specific_properties:
      armor:
        slot: chest
        custom_armor: gilded_netherite`

Here is the exert from the armor.yml in MMOItems
`GILDED_CHESTPLATE:
  base:
    material: LEATHER_CHESTPLATE
    custom-model-data: 10005.0
    name: '&8&lNetherite Chestplate &6&l(G)'
    armor: 12.0
    knockback-resistance: 0.25
    armor-toughness: 4.0
    unstackable: true
    max-durability: 1200.0
    hide-dye: true`

Paper Version: 
`Current: git-Purpur-1587 (MC: 1.18.2)*
Previous: git-Purpur-1579 (MC: 1.18.2)`

ItemsAdder Version/Info:
`[18:20:17 INFO]: -----------=[ ServerUtils PluginInfo ]=-----------
[18:20:17 INFO]:  Name: ItemsAdder
[18:20:17 INFO]:  Full Name: ItemsAdder v3.0.4b
[18:20:17 INFO]:  Version: 3.0.4b
[18:20:17 INFO]:  Website: devs.beer
[18:20:17 INFO]:  Authors: LoneDev
[18:20:17 INFO]:  Description: Customized Minecraft without client mods!
[18:20:17 INFO]:  Main: dev.lone.itemsadder.Main
[18:20:17 INFO]:  Prefix: ItemsAdder
[18:20:17 INFO]:  Load Order: POSTWORLD
[18:20:17 INFO]:  Depend: LoneLibs and ProtocolLib
[18:20:17 INFO]:  Soft Depend: ViaVersion, LibsDisguises, WorldGuard, GriefPrevention, Towny, Essentials, LightAPI, Realistic_World, EpicWorldGenerator, EpicNetherGenerator, Skript, MythicMobs, PlaceholderAPI, CMI, PermissionsEx, LuckPerms, Vault, MMOItems, GlowAPI, Slimefun, Orebfuscator, ExecutableItems, AdvancedEnchantments, Mimic and Citizens
[18:20:17 INFO]:  API Version: 1.14
[18:20:17 INFO]: -------------------------------------------------`

MMOItems Info:
`[18:20:52 INFO]: -----------=[ ServerUtils PluginInfo ]=-----------
[18:20:52 INFO]:  Name: MMOItems
[18:20:52 INFO]:  Full Name: MMOItems v6.7.2
[18:20:52 INFO]:  Version: 6.7.2
[18:20:52 INFO]:  Authors: Indyuce
[18:20:52 INFO]:  Description: A great item solution for your RPG server!!
[18:20:52 INFO]:  Main: net.Indyuce.mmoitems.MMOItems
[18:20:52 INFO]:  Load Order: POSTWORLD
[18:20:52 INFO]:  Depend: MythicLib
[18:20:52 INFO]:  Soft Depend: WorldGuard, Residence, BossShopPro, SkillAPI, SkillsPro, MMOCore, MythicMobs, MMOInventory, PlaceholderAPI, Vault, Denizen and ViaVersion
[18:20:52 INFO]:  API Version: 1.13
[18:20:52 INFO]: -------------------------------------------------`

MythicLib Version:
`[18:21:07 INFO]: -----------=[ ServerUtils PluginInfo ]=-----------
[18:21:07 INFO]:  Name: MythicLib
[18:21:07 INFO]:  Full Name: MythicLib v1.3.1
[18:21:07 INFO]:  Version: 1.3.1
[18:21:07 INFO]:  Authors: Lumine Studios
[18:21:07 INFO]:  Description: Kind of like mythiclib, but without the generic disorders
[18:21:07 INFO]:  Main: io.lumine.mythic.lib.MythicLib
[18:21:07 INFO]:  Load Order: POSTWORLD
[18:21:07 INFO]:  Load Before: MMOCore and MMOItems
[18:21:08 INFO]:  Soft Depend: WorldGuard, Residence, Factions, MythicMobs and ViaVersion
[18:21:08 INFO]:  API Version: 1.13
[18:21:08 INFO]: -------------------------------------------------`

MythicMobs Version:
`[18:21:28 INFO]: -----------=[ ServerUtils PluginInfo ]=-----------
[18:21:28 INFO]:  Name: MythicMobs
[18:21:28 INFO]:  Full Name: MythicMobs v5.0.3-SNAPSHOT-c60e1b69
[18:21:28 INFO]:  Version: 5.0.3-SNAPSHOT-c60e1b69
[18:21:28 INFO]:  Authors: Lumine
[18:21:28 INFO]:  Description: The total solution for all things mob-related.
[18:21:28 INFO]:  Main: io.lumine.mythic.bukkit.MythicBukkit
[18:21:28 INFO]:  Load Order: POSTWORLD
[18:21:28 INFO]:  Load Before: Quests and Nations
[18:21:28 INFO]:  Soft Depend: Multiverse-Core, Heroes, PhatLoots, Vault, MagicSpells, MiniaturePets, BarAPI, LanguageAPI, LibsDisguises, WorldGuard, Holograms, HolographicDisplays, PlaceholderAPI, CMI, ModelEngine and ViaVersion
[18:21:28 INFO]:  API Version: 1.13
[18:21:28 INFO]: -------------------------------------------------`

MMOItems Menu:
![image](https://user-images.githubusercontent.com/7933032/160904635-ad5daf79-9689-41a3-9ab3-a2234b780e8c.png)

ItemsAdder item:
![image](https://user-images.githubusercontent.com/7933032/160904725-984d88fc-0f7c-4ebf-acc7-123f5197be77.png)

I hope this can be of some help regarding this issue

**Comment by LoneDev6** [comment]
I see you used lowercase name, surely that's why, set it to `GILDED_CHESTPLATE`
I'm surprised you didn't notice any warning in the logs about an unknown item
```yml
   gilded_chestplate:
     display_name: "Netherite Chestplate (G)"
     permission: gilded_netherite
     mmoitem:
       type: ARMOR
       id: GILDED_CHESTPLATE
     resource:
       generate: true
       textures:
       - item/armor/gilded_netherite/chestplate
     durability:
       max_custom_durability: 1200
     specific_properties:
       armor:
         slot: chest
         custom_armor: gilded_netherite
```

**Comment by Zangerine** [comment]
> I see you used lowercase name, surely that's why, set it to `GILDED_CHESTPLATE` I'm surprised you didn't notice any warning in the logs about an unknown item
> 
> ```yaml
>    gilded_chestplate:
>      display_name: "Netherite Chestplate (G)"
>      permission: gilded_netherite
>      mmoitem:
>        type: ARMOR
>        id: GILDED_CHESTPLATE
>      resource:
>        generate: true
>        textures:
>        - item/armor/gilded_netherite/chestplate
>      durability:
>        max_custom_durability: 1200
>      specific_properties:
>        armor:
>          slot: chest
>          custom_armor: gilded_netherite
> ```

Sorry I should have mentioned that as soon as I had posted my reply I had already attempted to implement it by changing the case. It made absolutely no difference.

**Comment by LoneDev6** [comment]
I really have no clue, I tested it with your exact configuration and the item loads fine
