### ISSUE TITLE
Itemsadder plugin is disabled (maybe problem with mythicmobs

### ISSUE THREAD

**Issue by Freddy1CZ1** [PluginBugs/Issues-ItemsAdder#1591]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

FreddyCZ#3144

### What happened?

Itemsadder dont work, its disabled idk why i checked everything where could be problem but i think its about Mythicmobs.

I using Purpur 1.17.1

java version - 17

Log when server starts:

Plugin version - ItemsAdder v3.0.3-beta4

[20:36:08] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.0.3-beta4
[20:36:08] [Server thread/INFO]: 
[20:36:08] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[20:36:08] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_17_R1' loaded!
[20:36:08] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[20:36:08] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.0.3-beta4
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.18
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1428 (MC: 1.17.1)
                                               
[20:36:08] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.0.3-beta4 (Is it up to date?)
java.lang.IllegalAccessException: no such method: dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.MythicMobsHook.inst()MythicMobsHook/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(Unknown Source) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(Unknown Source) ~[?:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[server.jar:git-Purpur-1428]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/mythic/api/skills/ISkillMechanic
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.skills.ISkillMechanic
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[server.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 16 more
[20:36:08] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.0.3-beta4
[20:36:08] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v3.0.3-beta4 (Is it up to date?)
java.lang.IllegalAccessException: no such method: dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.MythicMobsHook.inst()MythicMobsHook/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(Unknown Source) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(Unknown Source) ~[?:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.onDisable(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[server.jar:git-Purpur-1428]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/mythic/api/skills/ISkillMechanic
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.skills.ISkillMechanic
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[server.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]

Log when i write /ia :

21:04:20[ERROR] null
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v3.0.3-beta4 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[server.jar:git-Purpur-1428]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[server.jar:git-Purpur-1428]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[server.jar:git-Purpur-1428]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server.jar:git-Purpur-1428]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[server.jar:git-Purpur-1428]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[server.jar:git-Purpur-1428]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[server.jar:git-Purpur-1428]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[server.jar:git-Purpur-1428]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[server.jar:git-Purpur-1428]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[server.jar:git-Purpur-1428]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[server.jar:git-Purpur-1428]
at java.lang.Thread.run(Unknown Source) ~[?:?]

### Steps to reproduce the issue

Plugin dont work 
1.type to chat /ia
2.Error

### Server version

This server is running Purpur version git-Purpur-1428 (mc:1.17.1) (implementing API version 1.17.1-R0.1-SNAPSHOT) (git:9beb23b on ver/1.17.1)

### ItemsAdder Version

 ItemsAdder v3.0.3-beta4

### ProtocolLib Version

Protocollib version is 4.8.0

### LoneLibs Version

LoneLibs 1.0.18

### LightAPI Version (optional)

LightAPI version is 5.1.0

### LibsDisguises Version (optional)

LibsDisguises Version is 10.0.28

### FULL server log

[2022-04-02-2.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8403241/2022-04-02-2.log)

### Error (optional)

```shell
[14:36:40] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.0.3-beta4
[14:36:40] [Server thread/INFO]: 
[14:36:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[14:36:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_17_R1' loaded!
[14:36:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[14:36:40] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.0.3-beta4
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.18
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1428 (MC: 1.17.1)
                                               
[14:36:41] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.0.3-beta4 (Is it up to date?)
java.lang.IllegalAccessException: no such method: dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.MythicMobsHook.inst()MythicMobsHook/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(Unknown Source) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(Unknown Source) ~[?:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[server.jar:git-Purpur-1428]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/mythic/api/skills/ISkillMechanic
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.skills.ISkillMechanic
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[server.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 16 more
[14:36:41] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.0.3-beta4
[14:36:41] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v3.0.3-beta4 (Is it up to date?)
java.lang.IllegalAccessException: no such method: dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.MythicMobsHook.inst()MythicMobsHook/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(Unknown Source) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findStatic(Unknown Source) ~[?:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.ZHk(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at dev.lone.itemsadder.Main.onDisable(SourceFile) ~[ItemsAdder-3.0.3B4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[server.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[server.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[server.jar:git-Purpur-1428]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/mythic/api/skills/ISkillMechanic
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.skills.ISkillMechanic
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[server.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[server.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
      url: ''
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: true
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: true
    log-not-extract-default-resources-already-exist: true
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-04-02_21 21 52](https://user-images.githubusercontent.com/77932673/161398085-3754f581-7e7c-463d-99b0-3f904a2c8bcf.png)
![2022-04-02_21 22 06](https://user-images.githubusercontent.com/77932673/161398087-438771a4-6cfa-43b4-9da4-aab5105e82a7.png)

**Comment by LoneDev6** [comment]
ItemsAdder is compatible with the latest Mythicmobs plugin, please try also to update ItemsAdder to 3.1.0.
I will post this version in some hours.

Thanks
