### ISSUE TITLE
[Server thread/ERROR] Could not pass event BlockPhysicsEvent to ItemsAdder v3.1.1

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1629]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [ ] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The error occurs in the server console of my 1.18.2 test about 2 to 3 hours after starting it without any players having connected to it. It doesn't seem to happen on my 1.18.1 test server which has the same plugins.

-------------------

[06:35:41] [Craft Scheduler Thread - 106 - LibsDisguises/INFO]: [LibsDisguises] Now looking for update on Jenkins..
[09:25:42] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.1.1
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.main.dD.o(org.bukkit.block.Block)" because "<local6>" is null
	at dev.lone.itemsadder.main.cU.a(SourceFile:220) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.d(SourceFile:339) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.b(SourceFile:501) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.c(SourceFile:577) ~[ItemsAdder_3.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:763) ~[?:?]
	at com.destroystokyo.paper.util.RedstoneWireTurbo.breadthFirstWalk(RedstoneWireTurbo.java:649) ~[paper-1.18.2.jar:git-Paper-283]
	at com.destroystokyo.paper.util.RedstoneWireTurbo.updateSurroundingRedstone(RedstoneWireTurbo.java:792) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.level.block.RedStoneWireBlock.updateSurroundingRedstone(RedStoneWireBlock.java:271) ~[?:?]
	at net.minecraft.world.level.block.RedStoneWireBlock.neighborChanged(RedStoneWireBlock.java:529) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.neighborChanged(BlockBehaviour.java:953) ~[?:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:770) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.updateNeighborsInFront(DiodeBlock.java:192) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.onPlace(DiodeBlock.java:177) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onPlace(BlockBehaviour.java:987) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:597) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:537) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:499) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.tick(DiodeBlock.java:54) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:995) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1081) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:615) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce the issue

There is nothing to do, I have this error on the 1.18.2 test server which arrives in the server console after 2 or 3 hours without anyone having gone to the server.

### Server version

>.... [18:07:23 INFO]: This server is running Paper version git-Paper-286 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d4a712d)

### ItemsAdder Version

>....=>.... [18:08:19 INFO]: ItemsAdder version 3.1.1
>.... [18:08:19 INFO]: Customized Minecraft without client mods!
>.... [18:08:19 INFO]: Website: devs.beer
>.... [18:08:19 INFO]: Author: LoneDev

### ProtocolLib Version

>....=>.... [18:08:56 INFO]: ProtocolLib version 4.8.0
>.... [18:08:56 INFO]: Provides read/write access to the Minecraft protocol.
>.... [18:08:56 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

>....=>.... [18:09:18 INFO]: LoneLibs version 1.0.18
>.... [18:09:18 INFO]: Collection of libs used by my plugins
>.... [18:09:18 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

>....=>.... [18:09:37 INFO]: LightAPI version bukkit-5.2.0 (build SNAPSHOT)
>.... [18:09:37 INFO]: Bukkit library for edit light levels
>.... [18:09:37 INFO]: Website: https://github.com/BeYkeRYkt/LightAPI
>.... [18:09:37 INFO]: Authors: BeYkeRYkt and other contributors in GitHub

### LibsDisguises Version (optional)

>....=>.... [18:10:51 INFO]: LibsDisguises version 10.0.28-SNAPSHOT
>.... [18:10:51 INFO]: A disguise plugin with various disguises.
>.... [18:10:51 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

[2022-04-13-3.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8482995/2022-04-13-3.log)

### Error (optional)

```shell
[09:25:42] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.1.1
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.main.dD.o(org.bukkit.block.Block)" because "<local6>" is null
	at dev.lone.itemsadder.main.cU.a(SourceFile:220) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.d(SourceFile:339) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.b(SourceFile:501) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.cU.c(SourceFile:577) ~[ItemsAdder_3.1.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:763) ~[?:?]
	at com.destroystokyo.paper.util.RedstoneWireTurbo.breadthFirstWalk(RedstoneWireTurbo.java:649) ~[paper-1.18.2.jar:git-Paper-283]
	at com.destroystokyo.paper.util.RedstoneWireTurbo.updateSurroundingRedstone(RedstoneWireTurbo.java:792) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.level.block.RedStoneWireBlock.updateSurroundingRedstone(RedStoneWireBlock.java:271) ~[?:?]
	at net.minecraft.world.level.block.RedStoneWireBlock.neighborChanged(RedStoneWireBlock.java:529) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.neighborChanged(BlockBehaviour.java:953) ~[?:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:770) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.updateNeighborsInFront(DiodeBlock.java:192) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.onPlace(DiodeBlock.java:177) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onPlace(BlockBehaviour.java:987) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:597) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:537) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:499) ~[?:?]
	at net.minecraft.world.level.block.DiodeBlock.tick(DiodeBlock.java:54) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:995) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1081) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:615) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 146.59.138.51
      pack-port: 30070
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: fr
  dictionaries-lang: fr
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: true
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
      - TERRAFORMGENERATOR:MUDDY_BOG
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

**Comment by vdl19** [comment]
Hello, strange I did not have the problem today, the only thing I seem to have done is to switch to Paper version 1.18.2 #287 so maybe it was version #286 the problem, I will continue to see if it comes back.

**Comment by LoneDev6** [comment]
Probably a region file was deleted while the server was running
