### ISSUE TITLE
Corruption of all texture after iazip

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#1630]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Sometimes randomly, when i want to add a new texture or model on ItemsAdder

### Steps to reproduce the issue

1. Add a model
2. /iazip
3. and i have an error on console

### Server version

Current: git-Purpur-1565 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.1.1

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.18

### FULL server log

[19:07:08] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:07:08] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit, ia_ialiquids
[19:07:08] [Worker-Main-2/INFO]: Loaded 7 recipes
[19:07:09] [Server thread/INFO]: Starting minecraft server version 1.18.1
[19:07:10] [Server thread/INFO]: Loading properties
[19:07:10] [Server thread/INFO]: This server is running Purpur version git-Purpur-1565 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ea44ea1 on HEAD)
[19:07:10] [Server thread/INFO]: Server Ping Player Sample Count: 12
[19:07:10] [Server thread/INFO]: Using 6 threads for Netty based IO
[19:07:10] [Server thread/WARN]: [Pufferfish] To improve performance, timings have been disabled by default
[19:07:10] [Server thread/WARN]: [Pufferfish] You can still use timings by using /timings on, but they will not start on server startup unless you set timings.really-enabled to true in paper.yml
[19:07:10] [Server thread/WARN]: [Pufferfish] If you would like to disable this message, either set timings.really-enabled to true or timings.enabled to false.
[19:07:10] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[19:07:10] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[19:07:10] [Server thread/INFO]: Default game type: SURVIVAL
[19:07:10] [Server thread/INFO]: Generating keypair
[19:07:10] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25578
[19:07:10] [Server thread/INFO]: Using epoll channel type
[19:07:10] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[19:07:10] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[19:07:10] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[19:07:14] [Server thread/WARN]: Legacy plugin ArmorStandTools v2.4.3 does not specify an api-version.
[19:07:14] [Server thread/WARN]: Legacy plugin EarthPlayers v1.0.0 does not specify an api-version.
[19:07:14] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.4
[19:07:14] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1
[19:07:14] [Server thread/INFO]: [ArmorStandTools] Loading ArmorStandTools v2.4.3
[19:07:14] [Server thread/INFO]: [EarthPlayers] Loading EarthPlayers v1.0.0
[19:07:14] [Server thread/INFO]: [EarthLib] Loading EarthLib v1.0.0
[19:07:14] [Server thread/INFO]: [EarthCeremony] Loading EarthCeremony v1.0.0
[19:07:14] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[19:07:14] [Server thread/INFO]: [LoneLibs] Loading LoneLibs v1.0.18
[19:07:14] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0
[19:07:14] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.18.1) has not yet been tested! Proceed with caution.
[19:07:15] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v3.1.1
[19:07:15] [Server thread/INFO]: [EarthHub] Loading EarthHub v1.0.0
[19:07:15] [Server thread/INFO]: [InteractiveBoard] Loading InteractiveBoard v15.5
[19:07:15] [Server thread/INFO]: [DecentHolograms] Loading DecentHolograms v2.3.1
[19:07:15] [Server thread/INFO]: [LPX] Loading LPX v3.0.3
[19:07:15] [Server thread/INFO]: [TAB-Bridge] Loading TAB-Bridge v2.0.1
[19:07:15] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.4
[19:07:15] [Server thread/INFO]:         __    
[19:07:15] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.4
[19:07:15] [Server thread/INFO]:   |___ |      Running on Bukkit - Purpur
[19:07:15] [Server thread/INFO]: 
[19:07:15] [Server thread/INFO]: [LuckPerms] Loading configuration...
[19:07:15] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[19:07:15] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[19:07:15] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[19:07:16] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[19:07:16] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[19:07:16] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[19:07:16] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1424ms)
[19:07:16] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[19:07:16] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:07:16] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[19:07:16] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[19:07:16] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.18
[19:07:16] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0
[19:07:16] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[19:07:16] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:07:16] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[19:07:16] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord or Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[19:07:16] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[19:07:16] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[19:07:16] [Server thread/INFO]: Preparing level "world"
[19:07:17] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:07:17] [Server thread/INFO]: Time elapsed: 221 ms
[19:07:17] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[19:07:17] [Server thread/INFO]: Time elapsed: 74 ms
[19:07:17] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.1
[19:07:17] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[19:07:17] [Server thread/INFO]: [ArmorStandTools] Enabling ArmorStandTools v2.4.3*
[19:07:17] [Server thread/WARN]: [ArmorStandTools] Support for v1_18_R1 not found, trying v1_12_R1. Please check for possible updates to the plugin.
[19:07:17] [Server thread/INFO]: [ArmorStandTools] PlotSquared plugin not found. Continuing without PlotSquared support.
[19:07:17] [Server thread/INFO]: [ArmorStandTools] WorldGuard plugin not found. Continuing without WorldGuard support.
[19:07:17] [Server thread/INFO]: [EarthPlayers] Enabling EarthPlayers v1.0.0*
[19:07:17] [Server thread/WARN]: [EarthPlayers] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.11.1 which is not a depend or softdepend of this plugin.
[19:07:17] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: wrapper [1.0.0]
[19:07:17] [Server thread/INFO]: [space.debian.earthwrapper.spigot.SpigotWrapper] [38;5;244m#~ [38;5;012mInstancing listeners.[0m
[19:07:17] [Server thread/INFO]: [space.debian.earthwrapper.spigot.SpigotWrapper] [38;5;244m#~ ------------------------------------------------ ~#[0m
[19:07:17] [Server thread/INFO]: [space.debian.earthwrapper.spigot.SpigotWrapper] [38;5;244m#~ [38;5;012mInstancing commands.[0m
[19:07:17] [Server thread/INFO]: [EarthLib] Enabling EarthLib v1.0.0
[19:07:17] [Server thread/WARN]: [EarthLib] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[19:07:17] [Server thread/INFO]: 
[19:07:17] [Server thread/INFO]: EarthLib - [ON]
[19:07:17] [Server thread/INFO]: 
[19:07:17] [Server thread/INFO]: [EarthCeremony] Enabling EarthCeremony v1.0.0
[19:07:17] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.1.1
[19:07:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R1! Trying to find NMS support
[19:07:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_18_R1' loaded!
[19:07:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[19:07:18] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.1.1
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.18
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1565 (MC: 1.18.1)
                                               
[19:07:18] [Server thread/INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: 
[19:07:18] [Server thread/INFO]: [ItemsAdder] 1.17.1 and newer https://a.devs.beer/lightapi-new
[19:07:18] [Server thread/INFO]: [ItemsAdder] LibsDisguises not installed, please install it to make (legacy) custom mobs working: ci.md-5.net/job/LibsDisguises/
[19:07:19] [Server thread/INFO]: [EarthHub] Enabling EarthHub v1.0.0
[19:07:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: earthhub [1.0]
[19:07:19] [Server thread/INFO]: 
[19:07:19] [Server thread/INFO]: EarthHub - ON
[19:07:19] [Server thread/INFO]: 
[19:07:19] [Server thread/INFO]: [InteractiveBoard] Enabling InteractiveBoard v15.5
[19:07:19] [Server thread/INFO]: [DecentHolograms] Enabling DecentHolograms v2.3.1
[19:07:19] [Server thread/INFO]: [DecentHolograms] Using ProtocolLib for packet listening.
[19:07:19] [Server thread/INFO]: [LPX] Enabling LPX v3.0.3
[19:07:19] [Server thread/INFO]: [LPX] License successfully verified!
[19:07:19] [Server thread/INFO]: [TAB-Bridge] Enabling TAB-Bridge v2.0.1
[19:07:19] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[19:07:19] [Server thread/INFO]: Running delayed init tasks
[19:07:19] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [License] Product licensed to: Mineof13 (193957)
[19:07:20] [Craft Scheduler Thread - 5 - Vault/INFO]: [Vault] Checking for Updates ... 
[19:07:20] [Craft Scheduler Thread - 5 - Vault/INFO]: [Vault] No new version available
[19:07:21] [Server thread/INFO]: [DecentHolograms] Loading holograms... 
[19:07:21] [Server thread/INFO]: [DecentHolograms] Loaded 2 holograms!
[19:07:21] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.7.0]
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bungee [1.0.1]
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.2]
[19:07:21] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.4.4 which is not a depend or softdepend of this plugin.
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms [5.1-R2]
[19:07:21] [Server thread/INFO]: 4 placeholder hook(s) registered! 1 placeholder hook(s) have an update available.
[19:07:21] [Server thread/INFO]: Done (11.104s)! For help, type "help"
[19:07:21] [Server thread/INFO]: Timings Reset
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Loaded 92 items
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 30/750 REAL_NOTE block IDs
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] Used 1269/6608 available max font_images
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 1 categories
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 92 items and stuff in 1494ms
[19:07:21] [Craft Scheduler Thread - 5 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Checking resourcepack url... 
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[19:07:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[19:07:21] [Craft Scheduler Thread - 6 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (external-host), LastEdit: 2022-04-13_18-56. Url: MYPACK.zip
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Loaded 92 items
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 30/750 REAL_NOTE block IDs
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] Used 1269/6608 available max font_images
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 1 categories
[19:07:24] [Craft Scheduler Thread - 7 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 92 items and stuff in 613ms
[19:07:25] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[19:07:25] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[19:07:25] [Craft Scheduler Thread - 7 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.1.1 generated an exception while executing task 1207
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "<local5>" is null
	at dev.lone.itemsadder.main.hj.a(SourceFile:122) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.hl.c(SourceFile:404) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.hl.ce(SourceFile:194) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.hl.cd(SourceFile:128) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.hy.cm(SourceFile:413) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.aB.a(SourceFile:2322) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.av.a(SourceFile:91) ~[ItemsAdder_3.1.1.jar:?]
	at dev.lone.itemsadder.main.aB.a(SourceFile:2110) ~[ItemsAdder_3.1.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1565]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:11:11] [Server thread/INFO]: Checking version, please wait...
[19:11:11] [Thread-32/INFO]: Current: git-Purpur-1565 (MC: 1.18.1)*
[19:11:11] [Thread-32/INFO]: Previous: git-Paper-790 (MC: 1.16.5)
[19:11:11] [Thread-32/INFO]: * You are 1 version(s) behind
[19:11:11] [Thread-32/INFO]: Download the new version at: https://purpurmc.org/downloads
[19:11:28] [Server thread/INFO]: ItemsAdder version 3.1.1
[19:11:28] [Server thread/INFO]: Customized Minecraft without client mods!
[19:11:28] [Server thread/INFO]: Website: devs.beer
[19:11:28] [Server thread/INFO]: Author: LoneDev
[19:11:38] [Server thread/INFO]: ProtocolLib version 4.7.0
[19:11:38] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[19:11:38] [Server thread/INFO]: Authors: dmulloy2 and comphenix
[19:11:44] [Server thread/INFO]: LoneLibs version 1.0.18
[19:11:44] [Server thread/INFO]: Collection of libs used by my plugins
[19:11:44] [Server thread/INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[19:07:25 WARN]: [ItemsAdder] Plugin ItemsAdder v3.1.1 generated an exception while executing task 1207
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "<local5>" is null
        at dev.lone.itemsadder.main.hj.a(SourceFile:122) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.hl.c(SourceFile:404) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.hl.ce(SourceFile:194) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.hl.cd(SourceFile:128) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.hy.cm(SourceFile:413) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.aB.a(SourceFile:2322) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.av.a(SourceFile:91) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.aB.a(SourceFile:2110) ~[ItemsAdder_3.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  self-host: {}
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: MYPACKURL
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: fr
  dictionaries-lang: fr
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 100
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: true
    log-not-extract-default-resources-already-exist: true
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

**Comment by LoneDev6** [comment]
Please share some of your texture files, thanks

**Comment by LoneDev6** [comment]
It's hard to help you without any log or any file.
This is a very strange issue and never happened on other servers

**Comment by SwartZCoding** [comment]
> It's hard to help you without any log or any file. This is a very strange issue and never happened on other servers

I can't do anything more, now i don't have the issue since 1 week. But 1 week before, i have this 2 times in 2 days different just after an iazip command
