### ISSUE TITLE
ClassCastException on custom plugins

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#1631]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When i used CustomBlock API on my plugin, i have an issue when i place my block.

### Steps to reproduce the issue

1. Create a custom block on ItemsAdder config
2. Use API to place this block on a BlockPlaceEvent
3. Check the error

### Server version

Current: git-Purpur-1565 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.1.1

API version for my plugin : 3.1.0b

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28

### Error (optional)

```shell
[22:22:31 ERROR]: Could not pass event in to EarthCore v2.0
java.lang.ClassCastException: class dev.lone.itemsadder.main.cc cannot be cast to class dev.lone.itemsadder.main.ca (dev.lone.itemsadder.main.cc and dev.lone.itemsadder.main.ca are in unnamed module of loader 'ItemsAdder_3.1.1.jar' @3e618a45)
        at dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:44) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:55) ~[ItemsAdder_3.1.1.jar:?]
        at fr.centurygroup.earthcore.generator.GeneratorManager.addGenerator(GeneratorManager.java:141) ~[EarthCore-2.0.jar:?]
        at fr.centurygroup.earthcore.generator.GeneratorListener.onPlace(GeneratorListener.java:46) ~[EarthCore-2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor686.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1565]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at dev.lone.itemsadder.main.iB.b(SourceFile:406) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.cD.a(SourceFile:137) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.fb.a(SourceFile:135) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.main.fb.r(SourceFile:226) ~[ItemsAdder_3.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1565]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:544) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1913) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1398) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1565]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

My code about this error on a BlockPlaceEvent : 

`        CustomBlock customBlock = CustomBlock.getInstance("earthsky:generator");

        if (customBlock != null) {
            customBlock.place(event.getBlock().getLocation());

// And other actions here.
}`

Error is located on a "CustomBlock customBlock = CustomBlock.getInstance("earthsky:generator");"

**Comment by LoneDev6** [comment]
Provide your `earthsky:generator` config, I suspect it's not a block.
