### ISSUE TITLE
CustomCrop "byAlreadyPlaced NullPointerException

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1638]
### What happened?

When getting data of vanilla crops using "byAlreadyPlaced", it would not return null but NullPointerException.

### Steps to reproduce the issue

1

### Server version

[19:16:08 INFO]: Checking version, please wait...
[19:16:10 INFO]: Current: git-Purpur-1604 (MC: 1.18.2)*
Previous: git-Paper-273 (MC: 1.18.2)
* You are 6 version(s) behind

### ItemsAdder Version

> about ItemsAdder
[19:16:26 INFO]: ItemsAdder version 3.1.1
[19:16:26 INFO]: Customized Minecraft without client mods!
[19:16:26 INFO]: Website: devs.beer
[19:16:26 INFO]: Author: LoneDev

### ProtocolLib Version

> about ProtocolLib
[19:16:33 INFO]: ProtocolLib version 4.8.0-b547
[19:16:33 INFO]: Provides read/write access to the Minecraft protocol.
[19:16:33 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> about LoneLibs
[19:16:40 INFO]: LoneLibs version 1.0.18
[19:16:40 INFO]: Collection of libs used by my plugins
[19:16:40 INFO]: Authors: LoneDev and others

### FULL server log
```
[19:07:12 ERROR]: Could not pass event BlockBreakEvent to Pouvoir v1.2.11
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:97) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:76) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at dev.lone.itemsadder.NMS.nbt.nms.impl.CraftItemStack_v1_18_R2.a(SourceFile:34) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.NMS.nbt.nms.impl.CraftItemStack_v1_18_R2.f(SourceFile:18) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.NMS.nbt.NItem.<init>(SourceFile:19) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:34) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:27) ~[ItemsAdder_3.1.1.jar:?]
        at dev.lone.itemsadder.api.CustomCrop.byAlreadyPlaced(SourceFile:52) ~[ItemsAdder_3.1.1.jar:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$318$14399A$\^eval\_.onBlockBreak_NEE(<eval>:321) ~[?:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$317$1239A$\^eval\_.onEnable_NEE#L:25(<eval>:26) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648) ~[Pouvoir-1.2.11.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[Pouvoir-1.2.11.jar:?]
        at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520) ~[Pouvoir-1.2.11.jar:?]
        at org.openjdk.nashorn.javaadapters.java_util_function_Consumer.accept(Unknown Source) ~[?:?]
        at com.skillw.pouvoir.api.script.ScriptTool$addListener$1.invoke(ScriptTool.kt:144) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.api.script.ScriptTool$addListener$1.invoke(ScriptTool.kt:143) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.api.script.ScriptTool.addListener$lambda-0(ScriptTool.kt:143) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.api.listener.ScriptListener$Companion$build$1.invoke(ScriptListener.kt:28) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.api.listener.ScriptListener$Companion$build$1.invoke(ScriptListener.kt:27) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Pouvoir-1.2.11.jar:?]
        at com.skillw.pouvoir.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[Pouvoir-1.2.11.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1604]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1604]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming update 3.2.2
