### ISSUE TITLE
Emoji not displaying in chat.

### ISSUE THREAD

**Issue by ElMoha943** [PluginBugs/Issues-ItemsAdder#1661]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Valen#7358

### What happened?

My emojis are working correctly in every place (scoreboards, tab, names, msg) but the chat. I tried vanilla chat, essentialschat and venturechat, none worked. The plugin was working fine until i isntalled mccosmetics plugin, but even after uninstalling it the problem persists.
![imagen](https://user-images.githubusercontent.com/25410859/164990724-e42f823f-fc27-485c-99f6-46f49b8690de.png)
also, placeholders work, as you can see the tag and crown that are form %img_name% work perfect, but the :name: doesnt

### Steps to reproduce the issue

type in chat :emoji_name: or do it with /e.

### Server version

git-Purpur-1612 (MC: 1.18.2)*

### ItemsAdder Version

3.1.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b553

### LoneLibs Version

1.0.18

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8550288/latest.log)

### Error (optional)

```shell
Found 2 erros but i dont know if they are related to the issue, i removed both combatlox and mythicmobs and the problem persists

24.04 15:00:05 [Server] ERROR Unhandled exception occurred in onPacketSending(PacketEvent) for CombatLogX
24.04 15:00:05 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer
24.04 15:00:05 [Server] INFO at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketSending(ForceFieldAdapter.java:80) ~[CombatLogX.jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:508) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.access$000(NettyChannelInjector.java:40) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:450) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib(1).jar:?]
24.04 15:00:05 [Server] INFO at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2122) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2108) ~[?:?]
24.04 15:00:05 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:901) ~[purpur-1.18.2.jar:git-Purpur-1612]
24.04 15:00:05 [Server] INFO at dev.lone.itemsadder.main.hD.ag(SourceFile:124) ~[ItemsAdder_3.1.2.jar:?]
24.04 15:00:05 [Server] INFO at dev.lone.itemsadder.main.hA.a(SourceFile:177) ~[ItemsAdder_3.1.2.jar:?]
24.04 15:00:05 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor604.execute(Unknown Source) ~[?:?]
24.04 15:00:05 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 15:00:05 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1612]
24.04 15:00:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 15:00:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:665) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 15:00:05 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2051) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:6) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
24.04 15:00:05 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1612]
24.04 15:00:05 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
24.04 15:00:10 [Multicraft] Skipped 117 lines due to rate limit (30/s)
24.04 14:48:08 [Server] ERROR [SCHEDULER] Exception thrown whilst executing task
24.04 14:48:08 [Server] WARN java.lang.NullPointerException: Cannot read field "a" because "<parameter1>" is null
24.04 14:48:08 [Server] WARN at ItemsAdder_3.1.1.jar//dev.lone.itemsadder.main.aJ.<init>(SourceFile:98)
24.04 14:48:08 [Server] WARN at ItemsAdder_3.1.1.jar//dev.lone.itemsadder.main.aH.a(SourceFile:373)
24.04 14:48:08 [Server] WARN at ItemsAdder_3.1.1.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.mechanics.CustomEntityMechanic.castAtEntity(SourceFile:64)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeTargetedEntitySkill$7(SkillMechanic.java:513)
24.04 14:48:08 [Server] WARN at java.base/java.lang.Iterable.forEach(Iterable.java:75)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.core.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:509)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeSkills$3(SkillMechanic.java:466)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
24.04 14:48:08 [Server] WARN at MythicMobs-5.0.1.jar//io.lumine.mythic.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
24.04 14:48:08 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
24.04 14:48:08 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
24.04 14:48:08 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1558)
24.04 14:48:08 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
24.04 14:48:08 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
24.04 14:48:08 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
24.04 14:48:08 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
24.04 14:48:08 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
```

### ItemsAdder config.yml

```shell
metrics: false
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 45.235.98.31
      pack-port: 37133
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: es
  dictionaries-lang: es
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_BOOTS: false
      DIAMOND_CHESTPLATE: false
      DIAMOND_HELMET: false
      DIAMOND_LEGGINGS: false
      NETHERITE_BOOTS: true
      NETHERITE_CHESTPLATE: true
      NETHERITE_HELMET: true
      NETHERITE_LEGGINGS: true
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: "iconos"
font_images:
# Base
  annoyed:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/annoyed.png"
    scale_ratio: 9
    y_position: 8
  blush:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/blush.png"
    scale_ratio: 9
    y_position: 8
  chefs-kiss:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/chefs-kiss.png"
    scale_ratio: 9
    y_position: 8
  confusion:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/confusion.png"
    scale_ratio: 9
    y_position: 8
  cringe:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/cringe.png"
    scale_ratio: 9
    y_position: 8
  happy-sarcasm:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/happy-sarcasm.png"
    scale_ratio: 9
    y_position: 8
  lip-bite:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/lip-bite.png"
    scale_ratio: 9
    y_position: 8
  nya:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/nya.png"
    scale_ratio: 9
    y_position: 8
  oh-god:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/oh-god.png"
    scale_ratio: 9
    y_position: 8
  pleading:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/pleading.png"
    scale_ratio: 9
    y_position: 8
  sad-yeehaw:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/sad-yeehaw.png"
    scale_ratio: 9
    y_position: 8
  scared-smile:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/scared-smile.png"
    scale_ratio: 9
    y_position: 8
  sparkle:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/sparkle.png"
    scale_ratio: 9
    y_position: 8
  stare-grab:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/stare-grab.png"
    scale_ratio: 9
    y_position: 8
  strong-blush:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/strong-blush.png"
    scale_ratio: 9
    y_position: 8
  taunting:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/taunting.png"
    scale_ratio: 9
    y_position: 8
  thinking:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/thinking.png"
    scale_ratio: 9
    y_position: 8
  tired:
    permission: base
    show_in_gui: true
    path: "font/emoji/base/tired.png"
    scale_ratio: 9
    y_position: 8
# Kitty
  kittyawe:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittyawe.png"
    scale_ratio: 9
    y_position: 8
  kittycry:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittycry.png"
    scale_ratio: 9
    y_position: 8
  kittycurious:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittycurious.png"
    scale_ratio: 9
    y_position: 8
  kittycute:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittycute.png"
    scale_ratio: 9
    y_position: 8
  kittydrool:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittydrool.png"
    scale_ratio: 9
    y_position: 8
  kittyflushed:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittyflushed.png"
    scale_ratio: 9
    y_position: 8
  kittygasm:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittygasm.png"
    scale_ratio: 9
    y_position: 8
  kittygrab:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittygrab.png"
    scale_ratio: 9
    y_position: 8
  kittyplead:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittyplead.png"
    scale_ratio: 9
    y_position: 8
  kittyscared:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittyscared.png"
    scale_ratio: 9
    y_position: 8
  kittysecret:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittysecret.png"
    scale_ratio: 9
    y_position: 8
  kittyshy:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittyshy.png"
    scale_ratio: 9
    y_position: 8
  kittysly:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittysly.png"
    scale_ratio: 9
    y_position: 8
  kittysmug:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittysmug.png"
    scale_ratio: 9
    y_position: 8
  kittysquish:
    permission: kitty
    show_in_gui: true
    path: "font/emoji/kitty/kittysquish.png"
    scale_ratio: 9
    y_position: 8
# Others
  wumpus:
    permission: wumpus
    show_in_gui: true
    path: "font/emoji/others/wumpus.png"
    scale_ratio: 9
    y_position: 8
```

**Comment by ElMoha943** [comment]
> This is a mojang bug I think. I cant remember which, but I remember that its not fixable on the plugin side
> 
> Lone dev has already addressed this in a few posts

They where working fine before so there is probably a fix, lets wait until @LoneDev6 answers

**Comment by LoneDev6** [comment]
You have to trace back what you changed before it stopped working.
This problem is usually happening if you don't have a chat plugin installed, people fixed it by installing EssentialsX-Chat or VentureChat

**Comment by ElMoha943** [comment]
as said above, proble started happening after installing mccosmetics but persissted after removing it. I tried vanilla chat, essentialsx and venturechat and none work

**Comment by LoneDev6** [comment]
Are you 100% sure it was caused by McCosmetics installation? It might be just a coincidence

**Comment by ElMoha943** [comment]
> Are you 100% sure it was caused by McCosmetics installation? It might be just a coincidence

Turned out to be venturechat apparently, idk why it was working fine before installing the other plugin, but now it doesnt, but it worked fine with essentialsx. Maybe last update of venturechat borke it. I will ask the dev about it
