### ISSUE TITLE
failed to get CustomBlock's Loot

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1710]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[19:54:39 ERROR]: Could not pass event CustomBlockBreakEvent to CustomCrops v1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getBiome()" because "<parameter1>" is null
        at dev.lone.itemsadder.api.CustomBlock.getLoot(SourceFile:268) ~[ItemsAdder_3.1.4b.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getLoot(SourceFile:248) ~[ItemsAdder_3.1.4b.jar:?]
        at net.momirealms.customcrops.listener.BreakCustomBlock.breakCustomBlock(BreakCustomBlock.java:23) ~[CustomCrops.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1613]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at dev.lone.itemsadder.main.cK.d(SourceFile:243) ~[ItemsAdder_3.1.4b.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

    CustomBlock.getInstance(event.getNamespacedID()).getLoot(false).forEach(itemStack -> {
        location.getWorld().dropItem(location.clone().add(0.5,0.2,0.5), itemStack);
    });

**Comment by LoneDev6** [comment]
You're using the API in the wrong way.
You can only get loot of placed blocks. This block is not currently placed in the world, that's why you this error.

This should work.
```java
CustomBlock.getByAlreadyPlaced(location.getBlock()).getLoot(false).forEach(itemStack -> {
    location.getWorld().dropItem(location.clone().add(0.5,0.2,0.5), itemStack);
});
```
