### ISSUE TITLE
Getting CustomStack returns null

### ISSUE THREAD

**Issue by iRedTea** [PluginBugs/Issues-ItemsAdder#1723]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Red Tea#4666

### What happened?

CustomStack c = CustomStack.getInstance("itemsadder:red_lightsaber");
System.out.println(c.getId());
Why this retur null? If i remove "itemsadder:", this also return null.

### Steps to reproduce the issue

1. Write CustomStack c = CustomStack.getInstance("itemsadder:red_lightsaber");
2. Write System.out.println(c.getId());
3. Start plugin
4. I get NullPointerException

### Server version

 git-Airplane-"d9154a1" (MC: 1.17.1) 

### ItemsAdder Version

 ItemsAdder version 3.1.4b

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### Error (optional)

```shell
[09:18:20 INFO]: [NetherIIBlockAndNoDrop] Enabling NetherIIBlockAndNoDrop v0.0.1.0
[09:18:20 ERROR]: Error occurred while enabling NetherIIBlockAndNoDrop v0.0.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.api.CustomStack.getId()" because "c" is null
        at ru.netherstudio.netheriiblockandnodrop.utils.Config.initNoDropList(Config.java:23) ~[NetherIIBlockAndNoDrop.jar:?]
        at ru.netherstudio.netheriiblockandnodrop.NoDropCore.<init>(NoDropCore.java:17) ~[NetherIIBlockAndNoDrop.jar:?]
        at ru.netherstudio.netheriiblockandnodrop.NetherIIBlockAndNoDrop.onEnable(NetherIIBlockAndNoDrop.java:18) ~[NetherIIBlockAndNoDrop.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:328) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Airplane-"d9154a1"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
Default swords.yml
```

### Screenshots/Videos (you can drag and drop files or paste links)
![idea64_UTBAlXoKVy](https://user-images.githubusercontent.com/104762784/170195119-aee964a7-cacd-4436-a37c-602dad584aa9.png)
![cmd_GVVjOZeklH](https://user-images.githubusercontent.com/104762784/170195135-d1f99cc4-d80c-467a-9536-b594e6ea2508.png)

**Comment by LoneDev6** [comment]
getInstance returns null if the item was not found
