### ISSUE TITLE
Custom trees time out the server

### ISSUE THREAD

**Issue by sketrick** [PluginBugs/Issues-ItemsAdder#1780]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SkretNI#4709

### What happened?

Custom trees time out the whole server if spawned next to each other.
Only fix is removing itemsadder plugin and removing the custom trees.

### Steps to reproduce the issue

 Plant trees next to each other and try placing a torch on a custom tree log.

### Server version

[15:27:17 INFO]: This server is running Paper version git-Paper-28 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b0eb4e0)
You are running the latest version
Previous version: git-Paper-27 (MC: 1.19)

### ItemsAdder Version

[15:30:36 INFO]: ItemsAdder version 3.2.0b-beta4
[15:30:36 INFO]: Customized Minecraft without client mods!
[15:30:36 INFO]: Website: devs.beer
[15:30:36 INFO]: Author: LoneDev

### ProtocolLib Version

[15:30:47 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b569
[15:30:47 INFO]: Provides read/write access to the Minecraft protocol.
[15:30:47 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:31:00 INFO]: LoneLibs version 1.0.19
[15:31:00 INFO]: Collection of libs used by my plugins
[15:31:00 INFO]: Authors: LoneDev and others

### FULL server log

[04:23:26] [Server thread/INFO]:   Loaded (2) kits into memory. Took 2ms
[04:23:26] [Server thread/INFO]:   Loaded (7) ranks into memory. Took 5ms
[04:23:26] [Server thread/INFO]:   Loaded (8) playtime rewards into memory. Took 8ms
[04:23:26] [Server thread/INFO]:   Loaded (9) player data into memory. Took 0ms
[04:23:26] [Server thread/INFO]:   Loaded (61) playtime records into memory. Took 8ms
[04:23:26] [Server thread/INFO]:   Loaded (6) playtime reward records into memory. Took 0ms
[04:23:26] [Server thread/INFO]:   Loaded (25) custom alias into memory. Took 8ms
[04:23:26] [Server thread/INFO]:   Registered events. Took 104ms
[04:23:26] [Server thread/INFO]:   Loaded (0) event action commands into memory. Took 0ms
[04:23:26] [Server thread/INFO]:   Updated (EN) language file. Took 96ms
[04:23:26] [Server thread/INFO]:   Loaded (248) worth values into memory. Took 56ms
[04:23:26] [Server thread/INFO]:   Loaded (7) warps into memory. Took 24ms
[04:23:26] [Server thread/INFO]:   Vault permissions was found - Enabling capabilities.
[04:23:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cmi [9.2.0.3]
[04:23:26] [Server thread/INFO]:   PlaceholderAPI hooked.
[04:23:26] [Server thread/INFO]:   PlaceholderAPI was found - Enabling capabilities.
[04:23:26] [Server thread/INFO]:   McMMO was found - Enabling capabilities.
[04:23:26] [Server thread/INFO]:   Starting world timer.
[04:23:26] [Server thread/INFO]:   Initializing world manager.
[04:23:26] [Server thread/INFO]:   Loaded (5) schedules into memory. Took 8ms
[04:23:26] [Server thread/INFO]:   Loaded GeoIP
[04:23:26] [Server thread/INFO]:   Loaded (116) skin cache entries into memory. Took 8ms
[04:23:26] [Server thread/INFO]:   Loaded (0) ArmorStand templates into memory. Took 0ms
[04:23:26] [Server thread/INFO]:   Version 9.2.0.3 has been enabled
[04:23:26] [Server thread/INFO]: ???????????????????????????????????????????????????????
[04:23:26] [Server thread/INFO]: [AuthMe] Hooked successfully into CMI
[04:23:26] [Server thread/INFO]: [Vault][Economy] CMI Economy hooked.
[04:23:26] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.2.0b-beta4
[04:23:26] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[04:23:26] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R1' loaded!
[04:23:26] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[04:23:26] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.2.0b-beta4
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.19
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-28 (MC: 1.19)
                                               
[04:23:26] [Server thread/INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: https://a.devs.beer/lightapi-new
[04:23:26] [Server thread/WARN]: [ItemsAdder] [0;33mUsing the legacy pack.[0m

### Error (optional)

```shell
it and delete your pastes!
 3.38 KB
      
[14:26:58 ERROR]: Could not pass event PlayerArmSwingEvent to ItemsAdder v3.2.0b-beta4
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 2, Size: 2)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:371) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:347) ~[ProtocolLib.jar:?]
        at dev.lone.itemsadder.NMS.PlayerUtil.PlayerUtil.a(SourceFile:324) ~[ItemsAdder_3.2.0b-beta4.jar:?]
        at dev.lone.itemsadder.main.cI.s(SourceFile:332) ~[ItemsAdder_3.2.0b-beta4.jar:?]
        at dev.lone.itemsadder.main.cI.ab(SourceFile:168) ~[ItemsAdder_3.2.0b-beta4.jar:?]
        at dev.lone.itemsadder.main.cL.b(SourceFile:300) ~[ItemsAdder_3.2.0b-beta4.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-28]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2534) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-28]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-28]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: true
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: false
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: true
    log-single-loaded-overwrite: true
    log-single-skip: true
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
```

**Comment by sketrick** [comment]
> > Textures not applying for blocks based on spawners video:
> 
> can't reproduce
> 
>  OUTPUT.mp4 
> ```yaml
> items:
>   modern_quartz:
>     enabled: true
>     display_name: display-name-modern_quartz
>     permission: iasurvival.decorative.modern_quartz
>     resource:
>       material: PAPER
>       generate: true
>       textures:
>         - block/decorative/modern_quartz
>     specific_properties:
>       block:
>         placed_model:
>           type: TILE
>           break_particles_material: QUARTZ_BLOCK
>         break_tools_whitelist:
>           - PICKAXE
>           - pickaxe
> ```
> 
> > Trees bugging out video:
> 
> Will be fixed

Might be CMI or UpgradableSpawners breaking it.

**Comment by LoneDev6** [comment]
Might be, but I doubt since I don't know how CMI can catch the custom block placement.

**Comment by sketrick** [comment]
I tested with just running the server on latest spigot build and no other plugins but itemsadder and protocolLib and it still doesn't apply textures for this addon: https://www.spigotmc.org/resources/blocks-blockus-reimagined-itemsadder-addon.83918/
Is there something incompatible in the writing of the addon?

**Comment by LoneDev6** [comment]
It doesn't work because the addon author decided to keep using the old way of creating blocks.
He uses `material: <BLOCK>` instead of a non-placeable item, like `PAPER`, this causes problems with TILE type custom block.

I also don't really like the fact that this pack is using TILE block type to create an extremely high amount of custom blocks which are not rare blocks but BUILDING blocks. They are likely to cause some little lag on servers if players abuse them to create huge structures.


Anyway, I will post an ItemsAdder update to fix this, but I'd have preferred to avoid doing that. You usually should use the new way of creating blocks.
