### ISSUE TITLE
itemsadder block injector bug

### ISSUE THREAD

**Issue by Shidapu** [PluginBugs/Issues-ItemsAdder#1795]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Shidapu#9455

### What happened?

Plugin doesn't load.

### Steps to reproduce the issue

Install server and addon.
Would be nice if you could implement a fix for this as they have for https://www.spigotmc.org/resources/iaxpresencefootsteps.102192/ , had to do with load order not working correctly, and the plugin loaded before ItemsAdder.

### Server version

Current: git-Purpur-1670 (MC: 1.19)

### ItemsAdder Version

ItemsAdder version 3.2.0c-beta6

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b569

### LoneLibs Version

LoneLibs version 1.0.19

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### FULL server log

No need.

### Error (optional)

```shell
[23:42:44 ERROR]: Could not load 'plugins\itemsadder-blocks-injector_0.0.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:410) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:318) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[purpur-1.19.jar:git-Purpur-1670]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1670]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1670]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:467) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
... 7 more
Caused by: java.lang.RuntimeException: ItemsAdder not installed
at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.v1_19_R1.loadFromCache(v1_19_R1.java:86) ~[itemsadder-blocks-injector_0.0.5.jar:?]
at dev.lone.blocksinjector.Main.<clinit>(Main.java:20) ~[itemsadder-blocks-injector_0.0.5.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:467) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
... 7 more
```

### ItemsAdder config.yml

```shell
Default config.
```

**Comment by LoneDev6** [comment]
This is not a load order problem.
itemsadder-blocks-injector must load before ItemsAdder.

`ItemsAdder not installed` means you don't have this folder: `plugins/ItemsAdder/storage/` which contains custom blocks IDs.

https://github.com/ItemsAdder/ItemsAdderBlocksInjector/blob/77d182079d5a1afeb853bbba30d8087ce9102834/nms_v1_19_R1/src/main/java/dev/lone/blocksinjector/custom_blocks/nms/blocksmanager/v1_19_R1.java#L73

**Comment by Shidapu** [comment]
> This is not a load order problem. itemsadder-blocks-injector must load before ItemsAdder.
> 
> `ItemsAdder not installed` means you don't have this folder: `plugins/ItemsAdder/storage/` which contains custom blocks IDs.
> 
> https://github.com/ItemsAdder/ItemsAdderBlocksInjector/blob/77d182079d5a1afeb853bbba30d8087ce9102834/nms_v1_19_R1/src/main/java/dev/lone/blocksinjector/custom_blocks/nms/blocksmanager/v1_19_R1.java#L73

I do have that folder.
https://gcloud.gmz.cx/s/CKxi6YCrSi5bGbe/preview

**Comment by LoneDev6** [comment]
Try to remove spaces from your server main folder.
Somehow the plugin cannot find that folder, for some reason

**Comment by Shidapu** [comment]
> Try to remove spaces from your server main folder. Somehow the plugin cannot find that folder, for some reason

Yes that seem to have fixed my issue all together. Thanks! Such a small mistake.

**Comment by LoneDev6** [comment]
Amazing!
Perfect
