### ISSUE TITLE
NoSuckFieldError : SYSTEM_CHAT on 1.19

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#1803]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Anto'#1234

### What happened?

On start of the server, i got this error : 

`[12:17:55 WARN]: [ItemsAdder] Plugin ItemsAdder v3.2.0c-beta6 generated an exception while executing task 354
java.lang.NoSuchFieldError: SYSTEM_CHAT
        at dev.lone.itemsadder.main.jF.b(SourceFile:152) ~[ItemsAdder_3.2.0c-beta6.jar:?]
        at dev.lone.itemsadder.main.jF.<init>(SourceFile:53) ~[ItemsAdder_3.2.0c-beta6.jar:?]
        at dev.lone.itemsadder.main.aB.a(SourceFile:2125) ~[ItemsAdder_3.2.0c-beta6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1670]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1670]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Steps to reproduce the issue

1. Start 1.19 server with purpur.
2. Put ItemsAdder version 3.2.0c-beta6 on your plugin folder
3. Add all dependencies for ItemsAdder.

### Server version

Current: git-Purpur-1670 (MC: 1.19)*

### ItemsAdder Version

ItemsAdder version 3.2.0c-beta6

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b545

### LoneLibs Version

LoneLibs version 1.0.19

**Comment by LoneDev6** [comment]
Update protocollib https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
