### ISSUE TITLE
Updating to 1.19 | ItemsAdder not working ⚠🛑

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1804]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

I'm using the last version of everything 
and updated the server to 1.19 | but the itemsadder not working at all

### Steps to reproduce the issue

update to 1.19

### Server version

[16:26:05 INFO]: This server is running Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)
You are running the latest version
Previous version: git-Paper-339 (MC: 1.18.2

### ItemsAdder Version

ItemsAdder version 3.2.0c-beta6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b569

### LoneLibs Version

LoneLibs version 1.0.19

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28

### Error (optional)

```shell
[16:28:22 INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: https://a.devs.beer/lightapi-new
[16:28:22 ERROR]: Error occurred while enabling ItemsAdder v3.2.0c-beta6 (Is it up to date?)
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/utilities/LibsPremium
at dev.lone.itemsadder.Main.onEnable(SourceFile:400) ~[ItemsAdder_3.2.0c-beta6.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-36]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-36]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-36]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.utilities.LibsPremium
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 12 more
[16:28:22 INFO]: [ItemsAdder] Disabling ItemsAdder v3.2.0c-beta6
```

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1774
