### ISSUE TITLE
<rw> shaders doesn't work

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1827]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Agaloth#4927

### What happened?

Since I've updated my server to 1.19, the emojis and chat effects doesn't work (inconsistently)

### Steps to reproduce the issue

1. Use any chat effect in-game like: <rw> <r> <j> etc...
2. Check results

### Server version

[12:14:03 INFO]: Checking version, please wait...
[12:14:03 INFO]: This server is running Paper version git-Paper-51 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a05e69b)

### ItemsAdder Version

[12:14:21 INFO]: ItemsAdder version 3.2.1b
[12:14:21 INFO]: Customized Minecraft without client mods!
[12:14:21 INFO]: Website: devs.beer
[12:14:21 INFO]: Author: LoneDe

### ProtocolLib Version

[12:14:35 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b573
[12:14:35 INFO]: Provides read/write access to the Minecraft protocol.
[12:14:35 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:14:43 INFO]: LoneLibs version 1.0.19
[12:14:43 INFO]: Collection of libs used by my plugins
[12:14:43 INFO]: Authors: LoneDev and others

### LibsDisguises Version (optional)

[12:14:56 INFO]: LibsDisguises version 10.0.28-SNAPSHOT
[12:14:56 INFO]: A disguise plugin with various disguises.
[12:14:56 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

https://mclo.gs/tfu4tEc

### Error (optional)

```shell
After normal launch (appeared some days ago) (no plugins unloaded via ServerUtils):
[04:04:45 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BOOLEAN but was STRING at path $.bold
        at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:95) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs 1.0.19.jar:?]
        at dev.lone.itemsadder.NMS.Comp.a(SourceFile:77) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jT.f(SourceFile:115) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jN.onPacketSending(SourceFile:187) ~[ItemsAdder_3.2.1b.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib #573.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java) ~[?:?]
        at net.minecraft.network.Connection.a(Connection.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$2(NettyChannelInjector.java:519) ~[ProtocolLib #573.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run() ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java) ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java) ~[pufferfishplus-1.19.jar:git-PufferfishPlus-1]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BOOLEAN but was STRING at path $.bold
        at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.JsonTreeReader.nextBoolean(JsonTreeReader.java:191) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:114) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        ... 40 more
[04:04:45 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@4be9f941[
    content=[{"text":"","color":"white"},{"text":"","color":"blue"},{"text":"(Discord) ","color":"blue","bold":"true"},{"text":" ","color":"white"},{"text":"| ","color":"dark_gray"},{"text":"Agaloth ","color":"gray"},{"text":"» ","color":"dark_gray"},{"text":"gym at 2am is so good","color":"white"},{"text":""}]
    b=1

After unloading DiscordSRV with Serverutils:

[10:27:51 INFO]:  | Agaloth ☽ » <rw test>
[10:27:51 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
com.google.gson.JsonParseException: invalid click action:  
        at lonelibs.net.kyori.adventure.text.serializer.gson.IndexedSerializer.read(IndexedSerializer.java:58) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:124) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:95) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs 1.0.19.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[LoneLibs 1.0.19.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs 1.0.19.jar:?]
        at dev.lone.itemsadder.NMS.Comp.a(SourceFile:77) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jT.f(SourceFile:115) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jN.onPacketSending(SourceFile:187) ~[ItemsAdder_3.2.1b.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib #573.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2067) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2053) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[ProtocolLib #573.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$2(NettyChannelInjector.java:519) ~[ProtocolLib #573.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-51]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-51]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:27:51 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@7e86a038[
    content=["",{"text":"","extra":[{"text":"","color":"white"},{"text":"","color":"white","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"white","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":" ","color":"white"},{"text":"| ","color":"dark_gray"},{"text":"","color":"gray"},{"text":"","color":"gray","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#00ddfb","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"A","color":"#00ddfb","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#18eef7","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"g","color":"#18eef7","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#2ffff3","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"a","color":"#2ffff3","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#58ffee","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"l","color":"#58ffee","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#81ffe8","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"o","color":"#81ffe8","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#acffed","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"t","color":"#acffed","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#d7fff1","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"h","color":"#d7fff1","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#d7fff1"},{"text":" ","color":"#d7fff1","bold":"true"},{"text":"","color":"#d7fff1","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"#d7fff1","bold":"true","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"☽ ","color":"yellow","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"yellow"},{"text":"","color":"yellow","clickEvent":{"action":"","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}},{"text":"","color":"yellow"},{"text":"»","color":"dark_gray"}]},{"text":"","color":"white"},{"text":" <rw test>","color":"white"},{"text":""}]
    b=1
  ]
```

### ItemsAdder config.yml

```shell
metrics: false
resource-pack:
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  title:
    enabled: false
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: xxx
      pack-port: xxx
    external-host:
      enabled: false
      url: xxx
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    fix_transparent_noteblocks__disable-for-more-performance: false
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: false
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: false
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
  notify-other-plugins-interfering: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: false
    lock-player: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    replace-only-packets: true
    add-hover-suggestion: false
  command:
    enabled: false
    commandblocks: false
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: false
  book:
    enabled: true
  anvil:
    enabled: false
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 12000
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 12000
  replace-in-customitems-name-and-lore: true
liquids:
  enabled: false
huds:
  enabled: false
config_files:
  update-automatically: false
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
update-checker: false
entities:
  max-furniture-vehicles-per-chunk: 200
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: true
        ingredients: true
  fix-packet-too-large-kick: false
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

Custom announcement plugin: ![image](https://user-images.githubusercontent.com/33335971/177548417-93f0b7ba-b6b5-45b0-9edf-93d51885e6da.png)

Essentials broadcast: 
![image](https://user-images.githubusercontent.com/33335971/177548483-0f5c4229-35d9-4f36-8712-265582b5074a.png)

VentureChat (the chat plugin we use): 
![image](https://user-images.githubusercontent.com/33335971/177548532-5a37a032-fb39-4c09-8f9e-ef7dba36c369.png)

**Comment by LoneDev6** [comment]
Probably related to that: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1830
