### ISSUE TITLE
Emoji give Itemsadder error and do not show up when trying to send with VentureChat installed

### ISSUE THREAD

**Issue by Kenified** [PluginBugs/Issues-ItemsAdder#1830]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Keks#9948

### What happened?

Trying to send IA emoji doesn't work with VentureChat, IA produces an error and the emoji text `:smile:` for example is not converted to emoji

### Steps to reproduce the issue

- use /emoji command to send an emoji
- emoji will not show up in chat
- error will generate

- send an emoji using name ie `:smile:`
- emoji will not show up in chat
- error will generate

### Server version

Current: git-Purpur-1684 (MC: 1.19)*

### ItemsAdder Version

ItemsAdder version 3.2.1b

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b570

### LoneLibs Version

LoneLibs version 1.0.19

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9062056/latest.log)

### Error (optional)

```shell
[08:57:57 ERROR]: [ItemsAdder] Unhandled exception number 128 occurred in onPacketSending(PacketEvent) for ItemsAdder
com.google.gson.JsonParseException: invalid click action:  
        at lonelibs.net.kyori.adventure.text.serializer.gson.IndexedSerializer.read(IndexedSerializer.java:58) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:124) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:95) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
        at dev.lone.itemsadder.NMS.Comp.a(SourceFile:77) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jT.f(SourceFile:115) ~[ItemsAdder_3.2.1b.jar:?]
        at dev.lone.itemsadder.main.jN.onPacketSending(SourceFile:187) ~[ItemsAdder_3.2.1b.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib b570.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:181) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:154) ~[ProtocolLib b570.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149) ~[ProtocolLib b570.jar:?]
        at mineverse.Aust1n46.chat.utilities.Format.sendPacketPlayOutChat(Format.java:462) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at mineverse.Aust1n46.chat.MineverseChat.onPluginMessageReceived(MineverseChat.java:438) ~[VentureChat-3.4.1_1.19_patch.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3524) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.19.jar:git-Purpur-1684]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1684]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.com
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: false
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: true
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: false
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      BONE_MEAL: true
      BREAD: true
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/93137126/177735922-34b83693-8fe1-452a-8686-18d72a59365f.png)
![image](https://user-images.githubusercontent.com/93137126/177735966-504bdcb6-ee8c-4675-b5b4-4045f544787d.png)

**Comment by LoneDev6** [comment]
Venture chat support will be fixed in the next update
