### ISSUE TITLE
CustomBlockInteractEvent (getCustomBlockItem)

### ISSUE THREAD

**Issue by cupa488** [PluginBugs/Issues-ItemsAdder#1851]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

yopu#1506

### What happened?

PROBLEM: When you get the ItemStack from getCustomBlockItem its right, but if you want to serialized and get again the ItemStack you will get "Failed to deserialize object".

SOLUTION:
ItemStack aux = event.getCustomBlockItem(); // doing this, you can NOT serialize the item
ItemStack item = new ItemStack(aux); //doing this, you can serialize the item.

### Steps to reproduce the issue

1. Create CustomBlockInteractEvent
2. getCustomBlockItem
3. Encode that item
4. Decode that item

### Server version

1.18.2

### ItemsAdder Version

API version: 3.0.0
ItemsAdder version: 3.2.0c-beta6

### ProtocolLib Version

ProtocolLib version: 4.8.0

### LoneLibs Version

LoneLibs version: 1.0.20

### Error (optional)

```shell
[WARNING] java.io.IOException: Failed to deserialize object

[WARNING] at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59)

[WARNING] at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51)

[WARNING] at java.base/java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1793)

[WARNING] at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)

[WARNING] at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)

[WARNING] at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)

[WARNING] at me.okramt.alexandrite.utils.Encoding.decode(Encoding.java:40)

[WARNING] at me.okramt.alexandrite.events.IAInteractBlock.check(IAInteractBlock.java:51)

[WARNING] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[WARNING] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[WARNING] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[WARNING] at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[WARNING] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)

[WARNING] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)

[WARNING] at dev.lone.itemsadder.main.eZ.p(SourceFile:74)

[WARNING] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[WARNING] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[WARNING] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[WARNING] at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[WARNING] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)

[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)

[WARNING] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)

[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)

[WARNING] at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505)

[WARNING] at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:496)

[WARNING] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1547)

[WARNING] at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)

[WARNING] at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)

[WARNING] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)

[WARNING] at net.minecraft.server.TickTask.run(SourceFile:18)

[WARNING] at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)

[WARNING] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)

[WARNING] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190)

[WARNING] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)

[WARNING] at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131)

[WARNING] at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169)

[WARNING] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162)

[WARNING] at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)

[WARNING] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146)

[WARNING] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051)

[WARNING] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)

[WARNING] at java.base/java.lang.Thread.run(Thread.java:833)

[WARNING] Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(java.util.Map)" is null

[WARNING] at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49)

[WARNING] ... 42 more
```

**Comment by LoneDev6** [comment]
Will be fixed, thanks
