### ISSUE TITLE
[22:37:42 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.2.2-beta5 java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null  The main thread of the server is stuck, and all players are disconnected

### ISSUE THREAD

**Issue by XinyuGuGu** [PluginBugs/Issues-ItemsAdder#1854]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[22:37:42 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.2.2-beta5
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null

The main thread of the server is stuck, and all players are disconnected

### Steps to reproduce the issue

Because there are too many related entities in this place, the loading time accumulates when converting from json format to mc object

### Server version

![20220717093317](https://user-images.githubusercontent.com/96636368/179380243-344973fb-ad8b-48c9-8075-f235c4128dcf.png)

### ItemsAdder Version

ItemsAdder v3.2.2-beta5

### ProtocolLib Version

tihs
![20220717093351](https://user-images.githubusercontent.com/96636368/179380256-6cc51bd2-ea19-4b18-98ee-2f552d4c302d.png)

### LoneLibs Version

tihs
![Uploading 20220717093406.png…]()

### FULL server log

[新建文本文档.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/9126888/default.txt)

### Error (optional)

```shell
[22:37:33 INFO]: え 你给予了 L_Libran 1.50 G
[22:37:33 INFO]: え ReasonYoung 被给予了 2 灵晶
[22:37:33 INFO]: ②Alleys➦ Alleys的小店开业了，有各种食物，矿石,升级材料等，均是平民价，在出生点左边
[22:37:34 INFO]: ④wildcat➦ 铁块倒也不算啥
[22:37:35 INFO]: ④j1angnan➦ 你要么
[22:37:36 INFO]: ②Aceroiaorion➦ 没带锄头
[22:37:37 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.2.2-beta5
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
        at dev.lone.itemsadder.main.co.a(SourceFile:96) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.cv.a(SourceFile:62) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.dn.i(SourceFile:81) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:299) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1843) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:37 INFO]: ④j1angnan➦ 我要走了
[22:37:38 INFO]: え 你给予了 ReasonYoung 15.00 G
[22:37:39 INFO]: ①Hunter➦ 抱歉，正好缺铁
[22:37:41 INFO]: ④wildcat➦ 不缺几个铁
[22:37:41 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.2.2-beta5
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
        at dev.lone.itemsadder.main.co.a(SourceFile:96) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.cv.a(SourceFile:62) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.dn.i(SourceFile:81) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:299) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1843) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:41 INFO]: ④j1angnan➦ 你去拿
[22:37:41 INFO]: UUID of player Yttikie is cea76370-6bed-3bcd-96d2-ecae1609c09b
[22:37:42 INFO]: ②Aceroiaorion➦ 别走
[22:37:42 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.2.2-beta5
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
        at dev.lone.itemsadder.main.co.a(SourceFile:96) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.cv.a(SourceFile:62) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at dev.lone.itemsadder.main.dn.i(SourceFile:81) ~[[I][物品模型]ItemsAdder_3.2.2-beta5 (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:299) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1843) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:37:44 INFO]: ④j1angnan➦ 我等你
[22:37:44 INFO]: ①Ca_ca➦ 10690000000000000000 3631
[22:37:45 INFO]: ②Aceroiaorion➦ 我去拿锄头
[22:37:47 INFO]: ⑧23121➦ ..
[22:37:49 INFO]: ⑧23121➦ ...
[22:37:50 INFO]: ②Aceroiaorion➦ 我去拿锄头
[22:37:53 INFO]: ⑤dyss➦ 1
[22:37:59 INFO]: ①Ca_ca➦ 10690000000000000000 3631
[22:38:00 INFO]: ⑧23121➦ 卡了
[22:38:00 INFO]: ④j1angnan➦ 卡了？
[22:38:00 INFO]: UUID of player Anuosi is 10dc2718-df52-3c39-b34c-3fa5273e6cc2
[22:38:23 INFO]: UUID of player ziyewuge is feebd95d-4103-3edb-af21-1483e6d29695
[22:38:24 INFO]: UUID of player sFry is d292d0d2-8929-35aa-b956-d028f4cf7921
[22:38:25 INFO]: UUID of player Yttikie is cea76370-6bed-3bcd-96d2-ecae1609c09b
[22:38:28 INFO]: UUID of player Enchanter_s is b70fb40b-423c-31e5-8024-04e4a09e1a70
[22:38:32 INFO]: UUID of player Yuzi3_2 is b46101bd-2c55-3576-b1d4-8f3c14c06de9
[22:38:33 INFO]: UUID of player Comoke is 371986e6-0e49-3672-b34c-42328b0f106e
[22:38:35 INFO]: UUID of player Ca_ca is b0aff412-6c33-30c7-b60e-d18de6ef6aa1
[22:38:35 INFO]: UUID of player Hunter is 989d7207-ade9-3acf-af05-7350fc90dd7e
[22:38:35 INFO]: UUID of player Helexal is 4c1c32a1-6c21-39a4-9747-168e782388b6
[22:38:37 INFO]: UUID of player DefeatInviteEn is 6e052bc3-c76f-39a6-8d11-09271ebd9a30
[22:38:39 INFO]: UUID of player XYMSS520 is 849d8c72-f0b7-33c9-86eb-00371b486241
[22:38:40 INFO]: UUID of player Summer886 is b95714b6-b940-35aa-9e83-5d7801453536
[22:38:40 INFO]: UUID of player xueyueyaodao is ffcd58ec-a210-3d98-86ab-572c5348a288
[22:38:41 INFO]: UUID of player r0413 is ee417a7e-91a4-3477-b0b8-6db5b1d8ebe5
[22:38:43 INFO]: UUID of player Trigger2334 is 6761da27-2b9d-3e75-bf9c-33bf43952494
[22:38:44 INFO]: UUID of player wildcat is c7fac498-7e09-3efa-b2a4-a87422d77d4a
[22:38:45 INFO]: UUID of player Seven_Nine79 is d1a04b4f-928f-3e26-9d85-b2ce971861e5
[22:38:47 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[22:38:48 INFO]: UUID of player laoguobhuiwan is 3c3c6c81-0850-3625-b5e2-3b7967e13ce4
[22:38:51 INFO]: UUID of player jimhacker is b40534f1-34a4-31fa-baed-1659e97b85c6
[22:38:51 INFO]: UUID of player sour_budou is 835a7489-1776-3437-890b-cccfff943a70
[22:38:54 INFO]: UUID of player VorticalGlobe34 is ba044cbc-5261-3d0b-86f7-72d815f2164a
[22:38:56 INFO]: rtgsg lost connection: Disconnected
[22:38:56 INFO]: xueyueyaodao lost connection: Disconnected
[22:38:56 INFO]: ReasonYoung lost connection: Disconnected
[22:38:56 INFO]: dyss lost connection: Disconnected
[22:38:56 INFO]: mikasa lost connection: Disconnected
[22:38:56 INFO]: Trigger2334 lost connection: Disconnected
[22:38:56 INFO]: PUUUUUU123 lost connection: Disconnected
[22:38:56 INFO]: DefeatInviteEn lost connection: Disconnected
[22:38:56 INFO]: Seven_Nine79 lost connection: Disconnected
[22:38:56 INFO]: dan_moya lost connection: Disconnected
[22:38:56 INFO]: Px_Heaven lost connection: Disconnected
[22:38:57 INFO]: Sherlock_OvO lost connection: Disconnected
[22:38:57 INFO]: fxz lost connection: Disconnected
[22:38:57 INFO]: jimhacker lost connection: Disconnected
[22:38:57 INFO]: Timoweide lost connection: Disconnected
[22:38:57 INFO]: Comoke lost connection: Disconnected
[22:38:57 INFO]: laoguobhuiwan lost connection: Disconnected
[22:38:57 INFO]: MiKaQiu lost connection: Disconnected
[22:38:57 INFO]: HellHunter lost connection: Disconnected
[22:38:57 INFO]: QHHHHHHA lost connection: Disconnected
[22:38:57 INFO]: MCxiao_ju lost connection: Disconnected
[22:38:57 INFO]: L_Libran lost connection: Disconnected
[22:38:57 INFO]: Lenients lost connection: Disconnected
[22:38:57 INFO]: Enchanted_Doll lost connection: Disconnected
[22:38:57 INFO]: Yuzi3_2 lost connection: Disconnected
[22:38:57 INFO]: wildcat lost connection: Disconnected
[22:38:57 INFO]: VorticalGlobe34 lost connection: Disconnected
[22:38:57 INFO]: _wuliao lost connection: Disconnected
[22:38:57 INFO]: jinciwu lost connection: Disconnected
[22:38:57 INFO]: LUDENG6666 lost connection: Disconnected
[22:38:57 INFO]: XYMSS520 lost connection: Disconnected
[22:38:57 INFO]: wang_boluo lost connection: Disconnected
[22:38:57 INFO]: Enchanter_s lost connection: Disconnected
[22:38:57 INFO]: Caca lost connection: Disconnected
[22:38:58 INFO]: SpecialCheni lost connection: Disconnected
[22:38:58 INFO]: Ca_ca lost connection: Disconnected
[22:38:58 INFO]: k_on lost connection: Disconnected
[22:38:58 INFO]: jackk36 lost connection: Disconnected
[22:38:58 INFO]: Yue_yan lost connection: Disconnected
[22:38:58 INFO]: j1angnan lost connection: Disconnected
[22:38:58 INFO]: ziyewuge lost connection: Disconnected
[22:38:58 INFO]: TaiHanShi lost connection: Disconnected
[22:38:58 INFO]: appp lost connection: Disconnected
[22:38:58 INFO]: HaiBLa lost connection: Disconnected
[22:38:58 INFO]: r0413 lost connection: Disconnected
[22:38:58 INFO]: Hunter lost connection: Disconnected
[22:38:58 INFO]: Williams lost connection: Disconnected
[22:38:58 INFO]: Aceroiaorion lost connection: Disconnected
[22:38:58 INFO]: Helexal lost connection: Disconnected
[22:38:58 INFO]: 23121 lost connection: Disconnected
[22:38:58 INFO]: Alleys lost connection: Disconnected
[22:38:58 INFO]: sour_budou lost connection: Disconnected
[22:38:58 INFO]: sFry lost connection: Disconnected
[22:38:58 INFO]: SakuraYukino lost connection: Disconnected
[22:38:58 INFO]: Summer886 lost connection: Disconnected
[22:38:58 INFO]: com.mojang.authlib.GameProfile@5c64a50e[id=cea76370-6bed-3bcd-96d2-ecae1609c09b,name=Yttikie,properties={textures=[com.mojang.authlib.properties.Property@21ddf26]},legacy=false] (/115.195.129.232:11296) lost connection: Disconnected
[22:38:58 INFO]: com.mojang.authlib.GameProfile@40830236[id=10dc2718-df52-3c39-b34c-3fa5273e6cc2,name=Anuosi,properties={textures=[com.mojang.authlib.properties.Property@2df6a0ab]},legacy=false] (/180.162.8.94:11408) lost connection: Timed out
[22:38:58 INFO]: com.mojang.authlib.GameProfile@6306f6fd[id=feebd95d-4103-3edb-af21-1483e6d29695,name=ziyewuge,properties={textures=[com.mojang.authlib.properties.Property@530b7655]},legacy=false] (/220.160.65.190:11734) lost connection: Timed out
[22:38:58 INFO]: com.mojang.authlib.GameProfile@c33cca5[id=d292d0d2-8929-35aa-b956-d028f4cf7921,name=sFry,properties={textures=[com.mojang.authlib.properties.Property@5c09c679]},legacy=false] (/14.122.168.240:11758) lost connection: Disconnected
[22:38:58 INFO]: com.mojang.authlib.GameProfile@758654f8[id=cea76370-6bed-3bcd-96d2-ecae1609c09b,name=Yttikie,properties={textures=[com.mojang.authlib.properties.Property@fe4cddd]},legacy=false] (/115.195.129.232:11781) lost connection: Disconnected
[22:38:58 INFO]: com.mojang.authlib.GameProfile@2dcc6acc[id=b70fb40b-423c-31e5-8024-04e4a09e1a70,name=Enchanter_s,properties={textures=[com.mojang.authlib.properties.Property@3825a6b3]},legacy=false] (/117.50.156.146:11871) lost connection: Disconnected
[22:38:58 INFO]: UUID of player qixia is c39bb689-260c-3432-97bc-5fb8bb206cab
[22:38:59 INFO]: Yuzi3_2[/119.39.207.190:11982] logged in with entity id 13482718 at ([world]-50414.097609339966, 140.65212924546623, 13558.50191534498)
[22:38:59 INFO]: Comoke[/101.224.25.20:12019] logged in with entity id 13482719 at ([world]-46363.22055405603, 63.0, 39736.52436790685)
[22:38:59 INFO]: Ca_ca[/192.168.1.101:12142] logged in with entity id 13482720 at ([world]10690.406021049126, 88.0, -3631.67593199
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: dx1.anue.cc
      pack-port: 50008
    external-host:
      enabled: false
      url: http://r82py4zwz.hd-bkt.clouddn.com/g004.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: false
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    disable-overwrite-leather-armor-layers-textures: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: zh_cn
  dictionaries-lang: zh_cn
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
```

### Other files, you can drag and drop them here to upload. (optional)

no

### Screenshots/Videos (you can drag and drop files or paste links)

no

**Comment by LoneDev6** [comment]
Provide a full server log.Provide a full server log.
