### ISSUE TITLE
Errors with MyPet

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#1864]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Nailm#9364

### What happened?

Whenever I switch a pet or release a pet, the same errors occured.

### Steps to reproduce the issue

1. Install Itemsadder & Mypet
2. Get a pet using /petshop
3. Release the pet using /petrelease
4. Errors occured

### Server version

Current: git-Purpur-1724 (MC: 1.19)*

### ItemsAdder Version

ItemsAdder version 3.2.3
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b570
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:17:38 INFO]: LoneLibs version 1.0.20
[15:17:38 INFO]: Collection of libs used by my plugins
[15:17:38 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

[15:17:49 INFO]: LightAPI version bukkit-5.3.0 (build SNAPSHOT)
[15:17:49 INFO]: Bukkit library for edit light levels
[15:17:49 INFO]: Website: https://github.com/BeYkeRYkt/LightAPI
[15:17:49 INFO]: Authors: BeYkeRYkt and other contributors in GitHub

### LibsDisguises Version (optional)

[15:20:19 INFO]: LibsDisguises version 10.0.29-SNAPSHOT
[15:20:19 INFO]: A disguise plugin with various disguises.
[15:20:19 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9165559/latest.log)

### Error (optional)

```shell
[15:09:01] [Server thread/INFO]: Nailm issued server command: /petadmin switch Kanroji_Nanami
[15:09:01] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:206) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:161) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
	at dev.lone.itemsadder.NMS.aE.aE.a(SourceFile:77) ~[ItemsAdder_3.2.3.jar:?]
	at dev.lone.itemsadder.main.jS.f(SourceFile:115) ~[ItemsAdder_3.2.3.jar:?]
	at dev.lone.itemsadder.main.jM.onPacketSending(SourceFile:203) ~[ItemsAdder_3.2.3.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2812) ~[purpur-1.19.jar:git-Purpur-1724]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2794) ~[purpur-1.19.jar:git-Purpur-1724]
	at de.Keyle.MyPet.compat.v1_19_R1.PlatformHelper.sendMessageRaw(PlatformHelper.java:277) ~[MyPet-3.12-SNAPSHOT-B1696.jar:?]
	at de.Keyle.MyPet.commands.admin.CommandOptionSwitch$1.callback(CommandOptionSwitch.java:107) ~[MyPet-3.12-SNAPSHOT-B1696.jar:?]
	at de.Keyle.MyPet.commands.admin.CommandOptionSwitch$1.callback(CommandOptionSwitch.java:87) ~[MyPet-3.12-SNAPSHOT-B1696.jar:?]
	at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37) ~[MyPet-3.12-SNAPSHOT-B1696.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1724]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1724]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1724]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1724]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1724]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1724]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1724]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:09:01] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@5a5d33fd[
    content={"extra":[{"text":""},{"color":"aqua","clickEvent":{"action":"run_command","value":"/petadmin switch a74f9503-399d-4106-b926-efca3258040d 94dece76-cfd6-4940-975f-4933b070a0f3"},"hoverEvent":{"action":"show_item","value":[{"text":"{id:\"minecraft:stone\",tag:{display:{Name:\"{\\\"text\\\":\\\"僵尸疣猪兽\\\"}\",Lore:[\"{\\\"text\\\":\\\"饥饿值: 75\\\"}\",\"{\\\"text\\\":\\\"HP: 11.00\\\"}\",\"{\\\"text\\\":\\\"经验值: 0.00\\\"}\",\"{\\\"text\\\":\\\"等级: 1\\\"}\",\"{\\\"text\\\":\\\"类型: Zoglin\\\"}\",\"{\\\"text\\\":\\\"技能树: 拾荒者\\\"}\"]}}, Count:1}"}]},"text":"僵尸疣猪兽"}],"text":""}
    b=1
  ]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://mimaru.oss-cn-zhangjiakou.aliyuncs.com/assets/default.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 20
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: zh_cn
  dictionaries-lang: zh_cn
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: false
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: true
    log-not-extract-default-resources-already-exist: true
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: true
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
chat-preview: false
```

**Comment by LoneDev6** [comment]
I'll check this as soon as possible, thanks for the report

**Comment by LoneDev6** [comment]
Make sure to update LoneLibs if you didn't.
Anyway seems to be related to the fact the MyPets is sending a malformed JSON message.
Refer to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1856

**Comment by LoneDev6** [comment]
Read more here, it will be fixed: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1884
