### ISSUE TITLE
Citizens API changes

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1877]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Andre_601#0601

### What happened?

There seems to have been breaking changes for the plugin Citizens, as using `2.0.30 BUILD #6.2` from its Spigot page alongside latest ItemsAdder version available results in a `NoSuchMethodException` being thrown by ItemsAdder (See error section for stacktrace).

I cannot think of a fix for this right now, but have contacted the devs in the hope to find a solution to share.

### Steps to reproduce the issue

1. Download Citizens `2.0.30 BUILD #6.2` from Spigot ([Link of Update](https://www.spigotmc.org/resources/citizens.13811/update?update=466297)).
2. Download latest ItemsAdder from Spigot.
3. Install both on the server.
4. Start the server.

### Server version

This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)

### ItemsAdder Version

[01:03:33 INFO]: ItemsAdder version 3.2.3
[01:03:33 INFO]: Customized Minecraft without client mods!
[01:03:33 INFO]: Website: devs.beer
[01:03:33 INFO]: Author: LoneDev

### ProtocolLib Version

[01:03:58 INFO]: ProtocolLib version 4.8.0
[01:03:58 INFO]: Provides read/write access to the Minecraft protocol.
[01:03:58 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:04:14 INFO]: LoneLibs version 1.0.19
[01:04:14 INFO]: Collection of libs used by my plugins
[01:04:14 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9193794/latest.log)

### Error (optional)

```shell
[00:50:12 ERROR]: Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v3.2.3
java.lang.NoSuchMethodError: 'void net.citizensnpcs.Citizens.storeNPCs(net.citizensnpcs.api.command.CommandContext)'
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.reload(SourceFile:53) ~[ItemsAdder_3.2.3.jar:?]
        at dev.lone.itemsadder.main.bg.a(SourceFile:367) ~[ItemsAdder_3.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at dev.lone.itemsadder.main.if.a(SourceFile:41) ~[ItemsAdder_3.2.3.jar:?]
        at dev.lone.itemsadder.main.aB.b(SourceFile:2152) ~[ItemsAdder_3.2.3.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Andre601** [comment]
Received an update from the devs.
The API indeed changed and now only accepts a boolean: https://github.com/CitizensDev/Citizens2/commit/9cf7779ff41dae0ebe3fd492fe9ff7e6ac2b1043#diff-4ccfa6faae0768c4cfe55dbf8e056d0a2e3d256bf500eef570e1dfb8da41855eR514

**Comment by LoneDev6** [comment]
Thanks
