### ISSUE TITLE
ItemsAdder don't work 1.18.2

### ISSUE THREAD

**Issue by Krypto7494** [PluginBugs/Issues-ItemsAdder#1880]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

ItemsAdder don't work

[Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.2.3c (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'dev.lone.itemsadder.main.iu dev.lone.itemsadder.main.iu.a()' must be InterfaceMethodref constant
	at dev.lone.itemsadder.Main.onEnable(SourceFile:370) ~[ItemsAdder_3.2.3c_cracked.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce the issue

idk

### Server version

Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### ItemsAdder Version

ItemsAdder version 3.2.3

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

 LoneLibs version 1.0.20

### FULL server log

[Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.2.3c (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'dev.lone.itemsadder.main.iu dev.lone.itemsadder.main.iu.a()' must be InterfaceMethodref constant
	at dev.lone.itemsadder.Main.onEnable(SourceFile:370) ~[ItemsAdder_3.2.3c_cracked.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Krypto7494** [comment]
@LoneDev6 pls help

**Comment by LoneDev6** [comment]
You omitted all the useful information to fix the issue.

Anyway make sure you have the latest LightAPI installed, I don't even know the version since you didn't write it.

**Comment by Krypto7494** [comment]
i install the latest version of lightapi
LightAPI 5.3.0

**Comment by Krypto7494** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
Please stop pinging me each 30 minutes.
I'm working for a fix for you.

I'll keep you updated.

**Comment by Krypto7494** [comment]
so how can i download it?

**Comment by LoneDev6** [comment]
I'm working on it.
