### ISSUE TITLE
Incompatible with QuickShop error

### ISSUE THREAD

**Issue by DreamMiu** [PluginBugs/Issues-ItemsAdder#1884]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

DreamMiu#7046

### What happened?

If multiple players click on the QuickShop box, the CMD will get stuck, resulting in a lot of errors.

### Steps to reproduce the issue

1. Create a QuickShop store
2. Click to buy

### Server version

1:10:24 INFO]: --------------------------------------------------
1:10:24 INFO]: CMI Plugin Version: 9.2.3.0 SqLite
1:10:24 INFO]: CMILib: 1.2.3.1
1:10:24 INFO]: Server: Pufferfish 1.19.1-R0.1-SNAPSHOT
1:10:24 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
1:10:24 INFO]: Modules -> 54 enabled 2 disabled: votifier, jail
1:10:24 INFO]: --------------------------------------------------

### ItemsAdder Version

ItemsAdder_3.2.3d

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b586

### LoneLibs Version

LoneLibs-1.0.20

### LightAPI Version (optional)

LightAPI-Bukkit-5.3.0

### LibsDisguises Version (optional)

null

### FULL server log

There was an error creating your Issue: body is too long (maximum is 65536 characters).

### Error (optional)

```shell
[01:24:09] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:206) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:161) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
	at dev.lone.itemsadder.NMS.aE.aE.a(SourceFile:77) ~[ItemsAdder_3.2.3d.jar:?]
	at dev.lone.itemsadder.main.kd.f(SourceFile:113) ~[ItemsAdder_3.2.3d.jar:?]
	at dev.lone.itemsadder.main.jX.onPacketSending(SourceFile:203) ~[ItemsAdder_3.2.3d.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2142) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2128) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2860) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2848) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2828) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at org.maxgamer.quickshop.chat.platform.minedown.BungeeQuickChat.send(BungeeQuickChat.java:66) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1248) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:199) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:92) ~[QuickShop-5.1.0.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor796.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.1-R0.1-SNAPSHOT.jar:git-Pufferfish-28]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1877) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.1.jar:git-Pufferfish-28]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:24:09] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@76556f02[
    content={"extra":[{"color":"dark_purple","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:paper\",tag:{CMILimitedUseCurrent:1,CMILimitedUseMax:1,NBTCommands:[\"R378kW/wGo2gID8tr0MUKZU3d1DpziAFmNYCyRTcHFBFDVDB8Gz6ZtobJH8pxH/P\"],RandomId:497991933,display:{Lore:[\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"light_purple\",\"text\":\"通用货币 \"},{\"bold\":true,\"italic\":false,\"color\":\"gold\",\"text\":\"? \"},{\"bold\":true,\"italic\":false,\"color\":\"yellow\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"text\":\"[签到获得]\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"dark_green\",\"text\":\"Tps\"},{\"bold\":false,\"italic\":false,\"color\":\"blue\",\"text\":\".\"},{\"italic\":false,\"color\":\"dark_green\",\"text\":\"鼠标左右键均可直接使用！\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"剩余使用: \"},{\"italic\":false,\"color\":\"gold\",\"text\":\"1 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"次\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"百元\"},{\"bold\":true,\"italic\":false,\"color\":\"blue\",\"text\":\"·\"},{\"bold\":true,\"italic\":false,\"color\":\"dark_green\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027}}}"}]},"text":"| "},{"color":"green","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:paper\",tag:{CMILimitedUseCurrent:1,CMILimitedUseMax:1,NBTCommands:[\"R378kW/wGo2gID8tr0MUKZU3d1DpziAFmNYCyRTcHFBFDVDB8Gz6ZtobJH8pxH/P\"],RandomId:497991933,display:{Lore:[\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"light_purple\",\"text\":\"通用货币 \"},{\"bold\":true,\"italic\":false,\"color\":\"gold\",\"text\":\"? \"},{\"bold\":true,\"italic\":false,\"color\":\"yellow\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"text\":\"[签到获得]\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"dark_green\",\"text\":\"Tps\"},{\"bold\":false,\"italic\":false,\"color\":\"blue\",\"text\":\".\"},{\"italic\":false,\"color\":\"dark_green\",\"text\":\"鼠标左右键均可直接使用！\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"剩余使用: \"},{\"italic\":false,\"color\":\"gold\",\"text\":\"1 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"次\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"百元\"},{\"bold\":true,\"italic\":false,\"color\":\"blue\",\"text\":\"·\"},{\"bold\":true,\"italic\":false,\"color\":\"dark_green\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027}}}"}]},"text":"物品："},{"bold":true,"color":"gold","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:paper\",tag:{CMILimitedUseCurrent:1,CMILimitedUseMax:1,NBTCommands:[\"R378kW/wGo2gID8tr0MUKZU3d1DpziAFmNYCyRTcHFBFDVDB8Gz6ZtobJH8pxH/P\"],RandomId:497991933,display:{Lore:[\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"light_purple\",\"text\":\"通用货币 \"},{\"bold\":true,\"italic\":false,\"color\":\"gold\",\"text\":\"? \"},{\"bold\":true,\"italic\":false,\"color\":\"yellow\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"text\":\"[签到获得]\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"dark_green\",\"text\":\"Tps\"},{\"bold\":false,\"italic\":false,\"color\":\"blue\",\"text\":\".\"},{\"italic\":false,\"color\":\"dark_green\",\"text\":\"鼠标左右键均可直接使用！\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"剩余使用: \"},{\"italic\":false,\"color\":\"gold\",\"text\":\"1 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"次\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"百元\"},{\"bold\":true,\"italic\":false,\"color\":\"blue\",\"text\":\"·\"},{\"bold\":true,\"italic\":false,\"color\":\"dark_green\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027}}}"}]},"text":"百元"},{"bold":true,"color":"blue","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:paper\",tag:{CMILimitedUseCurrent:1,CMILimitedUseMax:1,NBTCommands:[\"R378kW/wGo2gID8tr0MUKZU3d1DpziAFmNYCyRTcHFBFDVDB8Gz6ZtobJH8pxH/P\"],RandomId:497991933,display:{Lore:[\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"light_purple\",\"text\":\"通用货币 \"},{\"bold\":true,\"italic\":false,\"color\":\"gold\",\"text\":\"? \"},{\"bold\":true,\"italic\":false,\"color\":\"yellow\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"text\":\"[签到获得]\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"dark_green\",\"text\":\"Tps\"},{\"bold\":false,\"italic\":false,\"color\":\"blue\",\"text\":\".\"},{\"italic\":false,\"color\":\"dark_green\",\"text\":\"鼠标左右键均可直接使用！\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"剩余使用: \"},{\"italic\":false,\"color\":\"gold\",\"text\":\"1 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"次\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"百元\"},{\"bold\":true,\"italic\":false,\"color\":\"blue\",\"text\":\"·\"},{\"bold\":true,\"italic\":false,\"color\":\"dark_green\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027}}}"}]},"text":"·"},{"bold":true,"color":"dark_green","hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:paper\",tag:{CMILimitedUseCurrent:1,CMILimitedUseMax:1,NBTCommands:[\"R378kW/wGo2gID8tr0MUKZU3d1DpziAFmNYCyRTcHFBFDVDB8Gz6ZtobJH8pxH/P\"],RandomId:497991933,display:{Lore:[\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"light_purple\",\"text\":\"通用货币 \"},{\"bold\":true,\"italic\":false,\"color\":\"gold\",\"text\":\"? \"},{\"bold\":true,\"italic\":false,\"color\":\"yellow\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"text\":\"[签到获得]\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"dark_green\",\"text\":\"Tps\"},{\"bold\":false,\"italic\":false,\"color\":\"blue\",\"text\":\".\"},{\"italic\":false,\"color\":\"dark_green\",\"text\":\"鼠标左右键均可直接使用！\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"yellow\",\"text\":\"剩余使用: \"},{\"italic\":false,\"color\":\"gold\",\"text\":\"1 \"},{\"italic\":false,\"color\":\"yellow\",\"text\":\"次\"}],\"text\":\"\"}\u0027],Name:\u0027{\"extra\":[{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"百元\"},{\"bold\":true,\"italic\":false,\"color\":\"blue\",\"text\":\"·\"},{\"bold\":true,\"italic\":false,\"color\":\"dark_green\",\"text\":\"鱼币\"}],\"text\":\"\"}\u0027}}}"}]},"text":"鱼币  "},{"bold":true,"color":"dark_green","text":""},{"text":" "},{"color":"aqua","clickEvent":{"action":"run_command","value":"/qs silentpreview a26bb03c-81e4-45b4-9f42-8ad47790e4e4"},"text":"[物品预览]"}],"text":""}
    b=false
  ]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: i9-02.mcstory.cc
      pack-port: 20308
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/30835281/182208236-72707c71-1c05-4a45-9dc9-5d1a17e7cddc.png)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1856

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/183075974-26d6f30a-f27d-4880-b9e6-d3a539431fca.png)
