### ISSUE TITLE
LIbsDisguises EntityDamageEvent Error

### ISSUE THREAD

**Issue by fnrcum** [PluginBugs/Issues-ItemsAdder#1897]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Xafnir#1337

### What happened?

Basically EntityDamageEvent cannot be passed to IA so the console gets flooded with errors nearly every second

### Steps to reproduce the issue

Just start the server

### Server version

paper-1.19.2-118

### ItemsAdder Version

3.2.3d

### ProtocolLib Version

5.0.0-SNAPSHOT-b588

### LoneLibs Version

LoneLibs version 1.0.20

### LibsDisguises Version (optional)

LibsDisguises version 10.0.30

### Error (optional)

```shell
[09:59:05 ERROR]: Could not pass event EntityDamageEvent to ItemsAdder v3.2.3d
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
        at dev.lone.itemsadder.main.de.a(SourceFile:227) ~[ItemsAdder_3.2.3d.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-118]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[paper-1.19.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1152) ~[paper-1.19.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1126) ~[paper-1.19.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:963) ~[paper-1.19.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1186) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:318) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:403) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:239) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1156) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-118]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-118]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
        ... 30 more
```

**Comment by LoneDev6** [comment]
Make sure to update LibsDisguises.
https://www.spigotmc.org/resources/libs-disguises-free.81/

Another customer reported a similar issue which was solved by updating.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1898
