### ISSUE TITLE
Itemsadder plugin cannot be loaded normally on Purpur-1.19.2-1757

### ISSUE THREAD

**Issue by jiuwu02** [PluginBugs/Issues-ItemsAdder#1901]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

氿雾#3380

### What happened?

Itemsadder plugin cannot be loaded normally on Purpur-1.19.2-1757

### Steps to reproduce the issue

Report the error log when starting the server

### Server version

PurpurMC-1.19.2-1757

### ItemsAdder Version

ItemsAdder 3.2.3d

### ProtocolLib Version

ProtocolLib #588

### LoneLibs Version

LoneLibs 1.0.20

### LightAPI Version (optional)

LightAPI 5.3.0

### LibsDisguises Version (optional)

none

### Error (optional)

```shell
[INFO]: [ItemsAdder] Enabling ItemsAdder v3.2.3d
[ERROR]: Error occurred while enabling ItemsAdder v3.2.3d (Is it up to date?)
java.lang.NoSuchFieldError: MC1_19_R1
        at dev.lone.itemsadder.Main.onEnable(SourceFile:242) ~[ItemsAdder_3.2.3d[物品添加].jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1141) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[INFO]: [ItemsAdder] Disabling ItemsAdder v3.2.3d
```

### ItemsAdder config.yml

```shell
Not generated
```

### Other files, you can drag and drop them here to upload. (optional)

All plug in server (45): 
AdvancedEnchantments-8.13.7,
AnCDK, 
Authy-3.0.1, 
Backpacks-2.2.0,
Citizens, 
CMI-9.2.3.4, 
CMILib-1.2.3.3,
CrazyAuctionsPlus-1.3.0.0, 
DeluxeMenus-1.13.5-Release,
EasyGuiShop-2.3.5,
FastAsyncWorldEdit-2.4.4-SNAPSHOT-262(WorldEdit), 
floodgate, 
GCore, G
eyser-Spigot,
GPS, 
Iris-2.2.7, 
ItemsAdder-3.2.3d,
LagAssist-2.29.1, 
LightAPI-5.3.0,
LiteSignIn-1.6.3.3, 
LoneLibs-1.0.20, 
LuckPerms-5.4.40, 
Matrix-6.8.19, 
MMOCore-1.9.4, 
MMOItems-6.7.4, 
ModelEngine_Beta-B3.0.0, 
Multiverse-Core-4.3.1, 
MythicLib-1.3.3, 
MythicMobs-5.1.0, 
NBTAPI-2.10.0, 
PlaceholderAPI-2.11.2, 
ProtocolLib #588, 
QuestCreator, 
RealBiomeConditon-1.0.4, 
Scoreboard-revision*, 
SelectionVisualizer-3.2.0.0, 
ServerBackup, 
ServerBooster-1.1.3, 
SkinsRestorer, 
spark, 
Vault, 
ViaBackwards-4.4.1, 
ViaVersion-4.4.1, 
WorldGuard-7.0.7-dist, 
XConomy-2.19.2,

**Comment by LoneDev6** [comment]
Update LoneLibs
