### ISSUE TITLE
Custom blocks (from blockus addon) not spawning after update

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1906]
### Discord tag (optional)

ghtg#3326

### What happened?

Custom blocks from blockus addon (https://www.spigotmc.org/resources/blocks-blockus-reimagined-itemsadder-addon.83918/) not spawning after update

### Steps to reproduce the issue

1. start the server with ia, lonelibs and protocollib
2. join the server as op
3. see the _custom blocks placed before update is working_
4. place a new block (not furniture)
5. see the block of wooden planks or glowstone and the error in console

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 3.2.3f

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b569

### LoneLibs Version

LoneLibs version 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9336519/latest.log)

```
[13:50:18] [Server thread/WARN]: [ItemsAdder] Task #478 for ItemsAdder v3.2.3f generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.TileEntityMobSpawner.save(net.minecraft.nbt.NBTTagCompound)" because "<local5>" is null
	at dev.lone.itemsadder.NMS.aB.impl.v1_17_R1.a(SourceFile:51) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.g(SourceFile:461) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.b(SourceFile:439) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.bZ.a(SourceFile:234) ~[ItemsAdder_3.2.3f.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:50:19] [Server thread/WARN]: [ItemsAdder] Task #479 for ItemsAdder v3.2.3f generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.TileEntityMobSpawner.save(net.minecraft.nbt.NBTTagCompound)" because "<local5>" is null
	at dev.lone.itemsadder.NMS.aB.impl.v1_17_R1.a(SourceFile:51) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.g(SourceFile:461) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.b(SourceFile:439) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.bZ.a(SourceFile:234) ~[ItemsAdder_3.2.3f.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:50:23] [Server thread/INFO]: ghtg issued server command: /ia
[13:50:33] [Server thread/INFO]: ghtg issued server command: /ia
[13:50:37] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.2.3f
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.TileEntityMobSpawner.save(net.minecraft.nbt.NBTTagCompound)" because "<local5>" is null
	at dev.lone.itemsadder.NMS.aB.impl.v1_17_R1.a(SourceFile:51) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.g(SourceFile:461) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.b(SourceFile:448) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.a(SourceFile:249) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.d(SourceFile:374) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.b(SourceFile:543) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.c(SourceFile:612) ~[ItemsAdder_3.2.3f.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1428]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:959) ~[app:?]
	at net.minecraft.world.level.Level.updateNeighborsAt(Level.java:915) ~[app:?]
	at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2272) ~[app:?]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:819) ~[app:?]
	at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:417) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:603) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1887) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:50:37] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.2.3f
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.TileEntityMobSpawner.save(net.minecraft.nbt.NBTTagCompound)" because "<local5>" is null
	at dev.lone.itemsadder.NMS.aB.impl.v1_17_R1.a(SourceFile:51) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.g(SourceFile:461) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cj.b(SourceFile:448) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.a(SourceFile:249) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.d(SourceFile:374) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.b(SourceFile:543) ~[ItemsAdder_3.2.3f.jar:?]
	at dev.lone.itemsadder.main.cS.c(SourceFile:612) ~[ItemsAdder_3.2.3f.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1428]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:959) ~[app:?]
	at net.minecraft.world.level.Level.updateNeighborsAt(Level.java:916) ~[app:?]
	at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2272) ~[app:?]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:819) ~[app:?]
	at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:417) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:603) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1887) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ItemsAdder config.yml

```shell
metrics: true
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 100
  title:
    enabled: false
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    fix_transparent_noteblocks__disable-for-more-performance: false
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: goneward.ddns.net
      pack-port: 25566
    external-host:
      enabled: false
      url: https://www.dropbox.com/s/fj41p7v7qw7k3w1/pack.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  notify-other-plugins-interfering: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: false
    lock-player: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
      - FOREST
      - BIRCH_FOREST
      - RIVER
      - FOREST_HILLS
      - BIRCH_HILLS
      - DARK_FOREST
      - FLOWER_FOREST
      - TALL_BIRCH_FOREST
      - DARK_FOREST_HILLS
      - JUNGLE
      - JUNGLE_EDGE
      - JUNGLE_HILLS
      - MODIFIED_JUNGLE
      - MODIFIED_JUNGLE_EDGE
      - SAVANNA
      - ICE_SPIKES
      - SWAMP
      - SWAMP_HILLS
      - SNOWY_TUNDRA
      - SNOWY_TAIGA
      - SNOWY_TAIGA_MOUNTAINS
      - TAIGA
      - TAIGA_MOUNTAINS
      - GIANT_TREE_TAIGA
      - GIANT_SPRUCE_TAIGA
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
liquids:
  enabled: true
huds:
  enabled: true
config_files:
  update-automatically: true
  lang: ru
  dictionaries-lang: en
  extract-default-resources: true
  extract-default-configs: true
  legacy_pack: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
update-checker: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
entities:
  max-furniture-vehicles-per-chunk: 100
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
```

### Problematic items yml configuration file (optional)

```shell
items:
  bamboo_planks:
    display_name: Бамбуковые доски
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/bamboo_planks.png
      - block/bamboo_planks.png
      - block/bamboo_planks.png
      - block/bamboo_planks.png
      - block/bamboo_planks.png
      - block/bamboo_planks.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  charred_planks:
    display_name: Обугленные доски
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/charred_planks.png
      - block/charred_planks.png
      - block/charred_planks.png
      - block/charred_planks.png
      - block/charred_planks.png
      - block/charred_planks.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  white_oak_planks:
    display_name: доски из белого дуба
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/white_oak_planks.png
      - block/white_oak_planks.png
      - block/white_oak_planks.png
      - block/white_oak_planks.png
      - block/white_oak_planks.png
      - block/white_oak_planks.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  acacia_barrel:
    display_name: Бочка из акации
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/acacia_barrel_bottom.png
      - block/acacia_barrel_side.png
      - block/acacia_barrel_side.png
      - block/acacia_barrel_side.png
      - block/acacia_barrel_top.png
      - block/acacia_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  bamboo_barrel:
    display_name: Бамбуковая бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/bamboo_barrel_bottom.png
      - block/bamboo_barrel_side.png
      - block/bamboo_barrel_side.png
      - block/bamboo_barrel_side.png
      - block/bamboo_barrel_top.png
      - block/bamboo_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  birch_barrel:
    display_name: Березовая бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/birch_barrel_bottom.png
      - block/birch_barrel_side.png
      - block/birch_barrel_side.png
      - block/birch_barrel_side.png
      - block/birch_barrel_top.png
      - block/birch_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  charred_barrel:
    display_name: Обугленная бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/charred_barrel_bottom.png
      - block/charred_barrel_side.png
      - block/charred_barrel_side.png
      - block/charred_barrel_side.png
      - block/charred_barrel_top.png
      - block/charred_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  crimson_barrel:
    display_name: Багровая бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/crimson_barrel_bottom.png
      - block/crimson_barrel_side.png
      - block/crimson_barrel_side.png
      - block/crimson_barrel_side.png
      - block/crimson_barrel_top.png
      - block/crimson_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  dark_oak_barrel:
    display_name: Бочка из темного дуба
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/dark_oak_barrel_bottom.png
      - block/dark_oak_barrel_side.png
      - block/dark_oak_barrel_side.png
      - block/dark_oak_barrel_side.png
      - block/dark_oak_barrel_top.png
      - block/dark_oak_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  jungle_barrel:
    display_name: Бочка из тропической древесины
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/jungle_barrel_bottom.png
      - block/jungle_barrel_side.png
      - block/jungle_barrel_side.png
      - block/jungle_barrel_side.png
      - block/jungle_barrel_top.png
      - block/jungle_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  oak_barrel:
    display_name: Дубовая бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/oak_barrel_bottom.png
      - block/oak_barrel_side.png
      - block/oak_barrel_side.png
      - block/oak_barrel_side.png
      - block/oak_barrel_top.png
      - block/oak_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  warped_barrel:
    display_name: Искажённая бочка
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/warped_barrel_bottom.png
      - block/warped_barrel_side.png
      - block/warped_barrel_side.png
      - block/warped_barrel_side.png
      - block/warped_barrel_top.png
      - block/warped_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
  white_oak_barrel:
    display_name: Бочка из Белого Дуба
    permission: blockus
    resource:
      material: OAK_PLANKS
      generate: true
      textures:
      - block/white_oak_barrel_bottom.png
      - block/white_oak_barrel_side.png
      - block/white_oak_barrel_side.png
      - block/white_oak_barrel_side.png
      - block/white_oak_barrel_top.png
      - block/white_oak_barrel_side.png
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/21358664/184615698-8af981c2-e400-48dc-bb89-d0ccb74b00c4.png)

and these blocks spawned before update. the texture is working, but animation is gone (it was gradient rainbow shifting)
![image](https://user-images.githubusercontent.com/21358664/184616484-7307b6a0-4c14-4c8d-b004-aef2dd4a3d7e.png)

**Comment by LoneDev6** [comment]
I'll try to reproduce the issue in the next hours and publish a fix.
Anyway you should really consider updating your server, 1.17 is very old.

**Comment by ghtg** [comment]
> I'll try to reproduce the issue in the next hours and publish a fix. Anyway you should really consider updating your server, 1.17 is very old.

Thank you. Yes i will update my server soon.
