### ISSUE TITLE
Nova compatibility

### ISSUE THREAD

**Issue by ZDaPlaY** [PluginBugs/Issues-ItemsAdder#1918]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

ZDaPlaY#6666

### What happened?

when nova is in the list of plugins itemsadder does not start

### Steps to reproduce the issue

`[14:09:38] [Async Nova Worker - 1/ERROR]: [Nova] An exception occurred running a task
java.lang.ExceptionInInitializerError: null
    at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:36) ~[ItemsAdder_3.2.3f.jar:?]
    at xyz.xenondevs.nova.integration.customitems.plugin.ItemsAdder.<clinit>(ItemsAdder.kt:37) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager$PLUGINS$2.invoke(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager$PLUGINS$2.invoke(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager.getPLUGINS$Nova(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager.init$Nova(CustomItemServiceManager.kt:22) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializable.initialize$performInitialization(Initializable.kt:22) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializable.initialize(Initializable.kt:37) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializer$init$2$1$1.invoke(Initializer.kt:99) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializer$init$2$1$1.invoke(Initializer.kt:89) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda-0(SchedulerUtils.kt:92) ~[Nova-0.10.5.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null
    at dev.lone.itemsadder.main.aB.<clinit>(SourceFile:111) ~[ItemsAdder_3.2.3f.jar:?]
    ... 18 more`
when nova is in the list of plugins itemsadder does not start

### Server version

Purpur 1.19.2 1762

### ItemsAdder Version

Itemsadder version 3.2.3f

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b598

### LoneLibs Version

LoneLibs v1.0.21

### Error (optional)

```shell
`[14:09:38] [Async Nova Worker - 1/ERROR]: [Nova] An exception occurred running a task
java.lang.ExceptionInInitializerError: null
    at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:36) ~[ItemsAdder_3.2.3f.jar:?]
    at xyz.xenondevs.nova.integration.customitems.plugin.ItemsAdder.<clinit>(ItemsAdder.kt:37) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager$PLUGINS$2.invoke(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager$PLUGINS$2.invoke(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager.getPLUGINS$Nova(CustomItemServiceManager.kt:16) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.integration.customitems.CustomItemServiceManager.init$Nova(CustomItemServiceManager.kt:22) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializable.initialize$performInitialization(Initializable.kt:22) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializable.initialize(Initializable.kt:37) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializer$init$2$1$1.invoke(Initializer.kt:99) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.initialize.Initializer$init$2$1$1.invoke(Initializer.kt:89) ~[Nova-0.10.5.jar:?]
    at xyz.xenondevs.nova.util.AsyncExecutor.run$lambda-0(SchedulerUtils.kt:92) ~[Nova-0.10.5.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null
    at dev.lone.itemsadder.main.aB.<clinit>(SourceFile:111) ~[ItemsAdder_3.2.3f.jar:?]
    ... 18 more`
when nova is in the list of plugins itemsadder does not start
```

**Comment by LoneDev6** [comment]
send full log

**Comment by ZDaPlaY** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9417524/latest.log)

**Comment by LoneDev6** [comment]
This happens because somehow Nova is calling the ItemsAdder API even before ItemsAdder loaded, this causes this error.
I'll try to code a bypass for this but I'd rather avoid having to do this kind of black magic.
