### ISSUE TITLE
Could not pass event ChunkLoadEvent to ItemsAdder v3.2.3i

### ISSUE THREAD

**Issue by PoPoGH** [PluginBugs/Issues-ItemsAdder#1949]
### Discord tag (optional)

PoPo#3827

### What happened?

a bug that I connect to the server in the console.

### Steps to reproduce the issue

1. Start the server
2. Connect to the server
3. the error appears

### Server version

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemAdder version 3.2.3i

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9470703/latest.log)

### Error (optional)

```
[16:25:52] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to ItemsAdder v3.2.3i
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:594) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.level.PlayerChunk.lambda$16(PlayerChunk.java:484) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:620) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:160) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.World.getChunkAt(World.java:280) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.IWorldReader.getChunkAt(SourceFile:140) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.World.getChunkAt(World.java:274) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.World.getChunkAtWorldCoords(World.java:269) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.World.getFluid(World.java:606) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.Entity.l(Entity.java:1334) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.Entity.entityBaseTick(Entity.java:564) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.EntityLiving.entityBaseTick(EntityLiving.java:391) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.Entity.tick(Entity.java:531) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2768) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.entity.player.EntityHuman.tick(EntityHuman.java:262) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.level.EntityPlayer.playerTick(EntityPlayer.java:615) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:298) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:250) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkSection.getYPosition()" because "<local11>" is null
	at dev.lone.itemsadder.NMS.bA.impl.v1_17_R1.b(SourceFile:173) ~[?:?]
	at dev.lone.itemsadder.main.cR.b(SourceFile:557) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
	... 30 more
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.dropbox.com/s/7hnwo7vuqb9wkxf/pack.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: fr
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LoneDev6** [comment]
Seems to be a 1.17.1 issue, I'll check it as soon as I can.

**Comment by PoPoGH** [comment]
thank you for your quick reply.

**Comment by amarcais53** [comment]
any new regarding this ? im getting everydays a log file of almost 1GB

**Comment by PoPoGH** [comment]
@amarcais53 j'ai changer de version et j'ai plus de problème la dernière version est full bug

**Comment by amarcais53** [comment]
ok merci

**Comment by PoPoGH** [comment]
prends ItemsAdder_3.2.3 avec ces version de LoneLibs & ProtocolLib sinon ça va pas fonctionner correctement
[plugins.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/9491442/plugins.zip)

**Comment by LoneDev6** [comment]
Hello, sorry I'm currently on vacation so I cannot look into the issue, I'll be able to work on an update in 2 days.
I hope you can be patient, in the meantime you can try to use a previous version of the plugin.

**Comment by amarcais53** [comment]
yeah that's what we was talking about in french we did downgraded version to fix the issue
