### ISSUE TITLE
plugin does not load on 1.19.2

### ISSUE THREAD

**Issue by mitchngwen** [PluginBugs/Issues-ItemsAdder#1971]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[22:16:17 INFO]: ================ [ExecutableItems] ================
[22:16:17 INFO]: [ItemsAdder] Enabling ItemsAdder v3.2.3m
[22:16:18 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.2.3m
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.21
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-142 (MC: 1.19.2)
                                               
[22:16:18 ERROR]: Error occurred while enabling ItemsAdder v3.2.3m (Is it up to date?)
java.lang.NoClassDefFoundError: net/sourcewriters/spigot/rwg/legacy/api/compatibility/AddonInitializationException
        at dev.lone.itemsadder.Main.onEnable(SourceFile:376) ~[ItemsAdder_3.2.3m.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.sourcewriters.spigot.rwg.legacy.api.compatibility.AddonInitializationException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

### Steps to reproduce the issue

1

### ItemsAdder Version

1

### ProtocolLib Version

1

### LoneLibs Version

1

**Comment by mitchngwen** [comment]
More Information: 
Error while loading ChatControlRed dependencies!
ReflectionException Could not find class: dev.lone.itemsadder.api.FontImages.FontImageWrapper
	 at ChatControl-Red-10.13.8 (1).jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.lookupClass(ReflectionUtil.java:643)
	 at ChatControl-Red-10.13.8 (1).jar//org.mineacademy.chatcontrol.lib.model.ItemsAdderHook.<init>(HookManager.java:3613)
	 at ChatControl-Red-10.13.8 (1).jar//org.mineacademy.chatcontrol.lib.model.HookManager.loadDependencies(HookManager.java:218)
	 at ChatControl-Red-10.13.8 (1).jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:298)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
----------------------------------------------------------------------------------------------

**Comment by mitchngwen** [comment]
can't you guys just get along?! lol

**Comment by LoneDev6** [comment]
> can't you guys just get along?! lol

This message was sent at 6AM, we might have a different timezone. "lol"


> java.lang.NoClassDefFoundError: net/sourcewriters/spigot/rwg/legacy/api/compatibility/AddonInitializationException

Seems RWG changed something in their code, can you ask them?

> Error while loading ChatControlRed dependencies!
ReflectionException Could not find class: dev.lone.itemsadder.api.FontImages.FontImageWrapper

It probably failed to load ChatControlRed because of the previous RWG error.


Anyway would be nice to have a complete server log instead of partial errors.

**Comment by mitchngwen** [comment]
So I was going to get you a log so I re enabled itemsadder so I could get you a fresh log  but it's working now. Letting chatcontrolred load without items adder and then re enabling itemsadder was the solution. I am not sure if I gave you a log now if it would help any, if you still want it let me know. Thank you for getting back to me on my weird problem.
