### ISSUE TITLE
CustomStack#getOriginal() causes an exception on EcoItems 

### ISSUE THREAD

**Issue by luizsusin** [PluginBugs/Issues-ItemsAdder#1983]
### Terms
- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [ ] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)
CrafTIT Server#5457

### What happened?
When using ItemsAdder Namespaces on EcoItems, the plugin integrates with the IA's API.
While loading the plugin, a NPE is thrown.

### Steps to reproduce the issue
1. Create an EcoItem with ItemsAdder namespace;
2. Restart the server.

### Server version
git-Purpur-1778 (MC: 1.19.2)

### ItemsAdder Version
ItemsAdder version 3.2.3n

### ProtocolLib Version
ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version
LoneLibs version 1.0.21

### LightAPI Version
LightAPI version bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version
LibsDisguises version 10.0.31

### Error (optional)

```shell
[00:53:52 ERROR]: Error occurred while enabling EcoItems v3.113.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.main.aB.c(String)" because the return value of "dev.lone.itemsadder.main.aB.a()" is null
        at dev.lone.itemsadder.api.CustomStack.getOriginal(SourceFile:60) ~[ItemsAdder-3.2.3.jar:?]
        at dev.lone.itemsadder.api.CustomStack.getInstance(SourceFile:98) ~[ItemsAdder-3.2.3.jar:?]
        at com.willfp.eco.internal.spigot.integrations.customitems.CustomItemsItemsAdder$ItemsAdderProvider.provideForKey(CustomItemsItemsAdder.kt:26) ~[Eco-6.41.1.jar:?]
        at com.willfp.eco.core.items.Items.doParse(Items.java:233) ~[Eco-6.41.1.jar:?]
        at com.willfp.eco.core.items.ItemsLookupHandler.parse(ItemsLookupHandler.java:31) ~[Eco-6.41.1.jar:?]
        at com.willfp.eco.core.items.ItemsLookupHandler.parse(ItemsLookupHandler.java:14) ~[Eco-6.41.1.jar:?]
        at com.willfp.eco.core.lookup.LookupHandler.parseKey(LookupHandler.java:36) ~[Eco-6.41.1.jar:?]
        at com.willfp.eco.core.items.Items.lookup(Items.java:193) ~[Eco-6.41.1.jar:?]
        at com.willfp.ecoitems.items.EcoItem.<init>(EcoItem.kt:35) ~[EcoItems-3.113.1.jar:?]
        at com.willfp.ecoitems.items.EcoItems.update(EcoItems.kt:55) ~[EcoItems-3.113.1.jar:?]
        at com.willfp.ecoitems.EcoItemsPlugin.handleEnableAdditional(EcoItemsPlugin.kt:33) ~[EcoItems-3.113.1.jar:?]
        at com.willfp.ecoitems.libreforge.LibReforgePlugin.handleEnable(LibReforge.kt:211) ~[EcoItems-3.113.1.jar:?]
        at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:414) ~[Eco-6.41.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Seems EcoItems is loaded before ItemAdder is initialized.
Ask them to make it a softdepend.

**Comment by 0ft3n** [comment]
> Seems EcoItems is loaded before ItemAdder is initialized. Ask them to make it a softdepend.

EcoItems has eco as depend, while eco has ItemsAdder as softdepend

**Comment by LoneDev6** [comment]
For some reason EcoItems/eco is loaded before ItemsAdder.
Anyway EcoItems must listen to the ItemsAdder load event instead of instantly getting items.
https://itemsadder.devs.beer/developers/java-api#important-notes
