### ISSUE TITLE
spam in logs

### ISSUE THREAD

**Issue by Kokolochnik** [PluginBugs/Issues-ItemsAdder#2026]
### What happened?

when the server starts everything is fine, when the admin (me) comes in everything is fine.
but if any other player enters with a different nickname, there is a war in the console. I checked it myself using another minecraft account. this also happens on all cores, pufferfish and paper are the same. also, when another player enters, customentity animations stop playing.

### Steps to reproduce the issue

put the configs and everything in the items pack, put the texture pack and go under a different nickname on the server. ready!

### Server version

pufferfish 1.19.2

### ItemsAdder Version

[13:21:57 INFO]: ItemsAdder version 3.2.3-r9
[13:21:57 INFO]: Customized Minecraft without client mods!
[13:21:57 INFO]: Website: devs.beer
[13:21:57 INFO]: Author: LoneDev

### ProtocolLib Version

[13:21:30 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b600
[13:21:30 INFO]: Provides read/write access to the Minecraft protocol.
[13:21:30 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:18:46 INFO]: LoneLibs version 1.0.21
[12:18:46 INFO]: Collection of libs used by my plugins
[12:18:46 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

[12:19:12 INFO]: LightAPI version bukkit-5.3.0 (build SNAPSHOT)
[12:19:12 INFO]: Bukkit library for edit light levels
[12:19:12 INFO]: Website: https://github.com/BeYkeRYkt/LightAPI
[12:19:12 INFO]: Authors: BeYkeRYkt and other contributors in GitHub

### LibsDisguises Version (optional)

[12:19:40 INFO]: LibsDisguises version 10.0.31
[12:19:40 INFO]: A disguise plugin with various disguises.
[12:19:40 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

[latest (2).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9744687/latest.2.log)

### Error (optional)

```shell
[12:12:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:12:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:12:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:12:39 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[12:12:39 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[12:12:39 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[12:12:39 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[12:12:39 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[12:12:39 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[12:12:39 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aT.a(SourceFile:26)
[12:12:39 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.ba.a(SourceFile:25)
[12:12:39 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.ba.a(SourceFile:81)
[12:12:39 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aZ.Z(SourceFile:132)
[12:12:39 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aH.B(SourceFile:780)
[12:12:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:12:39 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[12:12:39 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[12:12:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:12:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:12:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 65.108.21.254
      pack-port: 25611
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Other files, you can drag and drop them here to upload. (optional)

[Downloads.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/9745132/Downloads.zip)

**Comment by Kokolochnik** [comment]
[14:26:43 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[14:26:43 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[14:26:43 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[14:26:43 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[14:26:43 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[14:26:43 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[14:26:43 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aT.a(SourceFile:26)
[14:26:43 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.ba.a(SourceFile:25)
[14:26:43 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.ba.a(SourceFile:81)
[14:26:43 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aZ.Z(SourceFile:132)
[14:26:43 WARN]:        at ItemsAdder_3.2.3-r9.jar//dev.lone.itemsadder.main.aH.B(SourceFile:780)
[14:26:43 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[14:26:43 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[14:26:43 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

**Comment by Kokolochnik** [comment]
and why any player can kill npc

**Comment by LoneDev6** [comment]
You seem to have a broken ItemsAdder entity.
It might be caused by a misconfiguration, please can you attach your broken `.iaentitymodel` project here?
Please open a thread on Discord and mark it as private if you don't want to share the model here.

**Comment by Kokolochnik** [comment]
you're right - a bug in the models. but there is another problem now. texture pack does not want to be created

**Comment by Kokolochnik** [comment]
![image](https://user-images.githubusercontent.com/114332828/195145989-d417f066-a706-4fde-9619-c66d99e97181.png)
![image](https://user-images.githubusercontent.com/114332828/195146050-7aba0c30-6dfc-43cb-90ad-957804fe7a27.png)

**Comment by LoneDev6** [comment]
You have a problem in your pack, a JSON file is malformed.
When you make a change you should take note of what you change, I have no idea what you edited in the pack.
