### ISSUE TITLE
ChatChat plugin compatibility

### ISSUE THREAD

**Issue by ColorsASD** [PluginBugs/Issues-ItemsAdder#2064]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Eriik#0580

### What happened?

After I stop the server I get the following error:

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Server thread"

### Steps to reproduce the issue

Shut down the server as ItemsAdder and ChatChat are present.

### Server version

{"currentVersion":"git-Purpur-1428 (MC: 1.17.1)"}

### ItemsAdder Version

3.2.4-beta1

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.21

### FULL server log

[06:01:18] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.2.4-beta1
[06:01:18] [Server thread/INFO]: [ItemsAdder] Saving custom entities...
[06:01:18] [Server thread/INFO]: [ItemsAdder] Saved 0 custom entities successfully!

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Server thread"

### Error (optional)

```shell
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Server thread"
```

### Java Version

Eclipse Temurin JDK with Hotspot 17.0.3+7 (x64)

**Comment by ColorsASD** [comment]
https://github.com/HelpChat/ChatChat/issues/172

**Comment by LoneDev6** [comment]
Post a valid log.

**Comment by TnTVlogs** [comment]
Not the owner of the issue, but he did not answer and I have the same problem

`
[17:48:21] [Server thread/INFO]: [ChatChat] Enabling ChatChat v1.0-SNAPSHOT-47
[17:48:22] [Server thread/ERROR]: Error occurred while enabling ChatChat v1.0-SNAPSHOT-47 (Is it up to date?)
java.lang.ClassCastException: class at.helpch.chatchat.format.SimpleFormat cannot be cast to class at.helpch.chatchat.api.format.PriorityFormat (at.helpch.chatchat.format.SimpleFormat and at.helpch.chatchat.api.format.PriorityFormat are in unnamed module of loader 'ChatChat-1.0-SNAPSHOT-47.jar' @571aabae)
	at at.helpch.chatchat.config.ConfigManager.reload(ConfigManager.java:51) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
	at at.helpch.chatchat.ChatChatPlugin.onEnable(ChatChatPlugin.java:96) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:48:22] [Server thread/INFO]: [ChatChat] Disabling ChatChat v1.0-SNAPSHOT-47
[17:48:22] [Server thread/ERROR]: Error occurred while disabling ChatChat v1.0-SNAPSHOT-47 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.isCancelled()" because "this.dataSaveTask" is null
	at at.helpch.chatchat.ChatChatPlugin.onDisable(ChatChatPlugin.java:138) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:377) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by LoneDev6** [comment]
> Not the owner of the issue, but he did not answer and I have the same problem
> 
> ```
> [17:48:21] [Server thread/INFO]: [ChatChat] Enabling ChatChat v1.0-SNAPSHOT-47
> [17:48:22] [Server thread/ERROR]: Error occurred while enabling ChatChat v1.0-SNAPSHOT-47 (Is it up to date?)
> java.lang.ClassCastException: class at.helpch.chatchat.format.SimpleFormat cannot be cast to class at.helpch.chatchat.api.format.PriorityFormat (at.helpch.chatchat.format.SimpleFormat and at.helpch.chatchat.api.format.PriorityFormat are in unnamed module of loader 'ChatChat-1.0-SNAPSHOT-47.jar' @571aabae)
> 	at at.helpch.chatchat.config.ConfigManager.reload(ConfigManager.java:51) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
> 	at at.helpch.chatchat.ChatChatPlugin.onEnable(ChatChatPlugin.java:96) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [17:48:22] [Server thread/INFO]: [ChatChat] Disabling ChatChat v1.0-SNAPSHOT-47
> [17:48:22] [Server thread/ERROR]: Error occurred while disabling ChatChat v1.0-SNAPSHOT-47 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.isCancelled()" because "this.dataSaveTask" is null
> 	at at.helpch.chatchat.ChatChatPlugin.onDisable(ChatChatPlugin.java:138) ~[ChatChat-1.0-SNAPSHOT-47.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:377) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

I don't see how this has to do with ItemsAdder (check the error, no trace of ItemsAdder there).

**Comment by LoneDev6** [comment]
Open a valid issue report in order to continue discussing about this problem.
