### ISSUE TITLE
Problems with entities

### ISSUE THREAD

**Issue by Batatoones** [PluginBugs/Issues-ItemsAdder#2070]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Batatones#2768

### What happened?

I tried to make an entity that would just move its head to be an npc in my world. However the npc is giving the following error that will be in the print just below. If anyone has any idea what this error could be and how to resolve it, I would be grateful. Note: I followed every step by step of the wiki.
![image](https://user-images.githubusercontent.com/117117621/199094045-71f80fae-b31d-40b4-9ec7-124a9aa8ef8e.png)

### Steps to reproduce the issue

1. /iaentity summon ''name of the entity''

### Server version

![image](https://user-images.githubusercontent.com/117117621/199094387-421dc6dd-ebe6-4072-98ce-4ab55675ef83.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/117117621/199094522-8646ef0b-bde6-42ab-96e3-818d7a2e5ece.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/117117621/199094614-0a858bcc-3ef5-49ec-ab23-056dd1764e97.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/117117621/199094719-78322277-296f-43e5-92b5-ad7b7b1091e9.png)

### Error (optional)

```shell
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:37:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:37:56 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[16:37:56 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[16:37:56 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aT.a(SourceFile:26)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:25)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:81)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aZ.X(SourceFile:132)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aG.y(SourceFile:783)
[16:37:56 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:37:56 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:37:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:37:56 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[16:37:56 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[16:37:56 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aT.a(SourceFile:26)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:25)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:81)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aZ.X(SourceFile:132)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aG.y(SourceFile:783)
[16:37:56 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:37:56 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:37:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:37:56 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[16:37:56 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[16:37:56 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[16:37:56 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aT.a(SourceFile:26)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:25)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.ba.a(SourceFile:81)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aZ.X(SourceFile:132)
[16:37:56 WARN]:        at ItemsAdder_3.2.5_beta5.jar//dev.lone.itemsadder.main.aG.y(SourceFile:783)
[16:37:56 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:37:56 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:37:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:37:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:37:56 INFO]: Villager EntityVillager['Villager'/2957, uuid='c6a657ce-c809-47f1-ad64-38cc1765a9d1', l='ServerLevel[world]', x=397.40, y=68.00, z=-54.46, cpos=[24, -4], tl=254, v=true] died, message: 'Villager was slain by Batatones_ using [PVP Sword (Right-Click)]'
```

### ItemsAdder config.yml

```shell
info:
  namespace: custom
entities:
  npc_1:
    display_name: "Travelling Man"
    type: VILLAGER
    model_folder: entity/npc_1
    silent: true
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/117117621/199095446-14f3774a-05c7-4894-ac87-517aaf623389.png)

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, probably your animation has 0 frames

**Comment by LoneDev6** [comment]
The next update might mitigate this issue, but it's hard for me to reproduce without your model files.

Anyway also make sure you have correctly exported the model files, read here to know what failed to load and why:
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
