### ISSUE TITLE
Denizens plugin Error ItemsAdder

### ISSUE THREAD

**Issue by DonKolia** [PluginBugs/Issues-ItemsAdder#2081]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Discord#5845

### What happened?

I have changed the version of ItemsAdder and now it crashes in the console.

### Steps to reproduce the issue

I have changed the version of ItemsAdder and now it crashes in the console.

### Server version

This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)

### ItemsAdder Version

ItemsAdder version 3.2.5-r3

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.19

### FULL server log

Comment is too long (maximum is 65536 characters)
Put in the title: **FULL server log FILE URL**

https://cdn.discordapp.com/attachments/971533655719686154/1039358508740640788/latest.log

### Error (optional)

```shell
[02:52:20] [Server thread/INFO]: [ItemsAdder] [0m[38;5;51m
[38;5;51m  ___  ___        __        __   __   ___  __  [38;5;2m    ItemsAdder[38;5;246m 3.2.5-r3
[38;5;51m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [38;5;2m    LoneLibs[38;5;246m 1.0.19
[38;5;51m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [38;5;8m    Paper git-Paper-379 (MC: 1.18.2)
[38;5;51m                                               [0m
[02:52:20] [Server thread/WARN]: [ItemsAdder] Loaded class com.denizenscript.denizen.objects.ItemTag from Denizen v1.2.5-SNAPSHOT (build 1775-REL) which is not a depend or softdepend of this plugin.
[02:52:20] [Server thread/ERROR]: [ItemsAdder] [0m[38;5;9mError while hooking into Denizen[0m
[02:52:20] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because "mainType" is null
[02:52:20] [Server thread/WARN]: 	at Denizen-1.2.5-b1775-REL.jar//com.denizenscript.denizencore.utilities.codegen.TagNamer.nameTagInterface(TagNamer.java:22)
[02:52:20] [Server thread/WARN]: 	at Denizen-1.2.5-b1775-REL.jar//com.denizenscript.denizencore.tags.ObjectTagProcessor.registerTagInternal(ObjectTagProcessor.java:381)
[02:52:20] [Server thread/WARN]: 	at Denizen-1.2.5-b1775-REL.jar//com.denizenscript.denizencore.tags.ObjectTagProcessor.registerTag(ObjectTagProcessor.java:377)
[02:52:20] [Server thread/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.Core.OtherPlugins.Denizen.DenizenHook.hook(SourceFile:22)
[02:52:20] [Server thread/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:425)
[02:52:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:52:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:52:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[02:52:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[02:52:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[02:52:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[02:52:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[02:52:20] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[02:52:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[02:52:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:52:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[02:52:20] [Server thread/INFO]: [ItemsAdder] [0mRegistered Citizens NPC Trait: customentity[0m
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

Denizen version: Denizen-1.2.5-b1775-REL

**Comment by DonKolia** [comment]
Is ItemsAdder error or Denizen error?

**Comment by LoneDev6** [comment]
> Is ItemsAdder error or Denizen error?

I have to identify it before saying anything.
Anyway try to update to `Denizen-1.2.5-b1779-REL`, you are using an old Denizen version.
https://ci.citizensnpcs.co/job/Denizen/

**Comment by LoneDev6** [comment]
I cannot reproduce this issue with Denizen-1.2.6-b1783-REL.
https://ci.citizensnpcs.co/job/Denizen/
