### ISSUE TITLE
Denizen Support

### ISSUE THREAD

**Issue by nomadjimbob** [PluginBugs/Issues-ItemsAdder#2104]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

nomadjimbob#4507

### Describe the solution you'd like

I have added huge ItemsAdder support through Depenzien which I am currently testing and almost ready to submit to mcmonkey for a PR.

This might save you adding support directly within the plugin, or I am happy to not do the PR and help move this directly into IA (or happy for you to take my code).

https://github.com/STEMMechanics/Depenizen

### Is your feature request related to a problem?

Denizen support

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Very nice, exactly how does this works?

I already added basic support in some recent update https://itemsadder.devs.beer/developers/denizen-api

**Comment by nomadjimbob** [comment]
I saw that so thanks. I did start this a while back as I needed the bridge for my server as I use Denizen quite extensively.

I'm going to cover everything below, so apologies if you are already aware!

Depenizen is the plugin that adds bridging between Denizen and 3rd party plugins, supported and hosted by mcmonkey and feeds into their documentation site https://meta.denizenscript.com

This repo lists the currently supported plugins through the Depenzien bridge https://github.com/DenizenScript/Depenizen-Lib/tree/83fb6580fd81ce06633d6e27b20c7d9339b9bd5c

I have a updates to the current code I still need to push which updates the documentation and naming consistency.

I have added the following (from memory, I'm away from my dev machine):

## Commands
Drop a block/item at a location
`- iadrop <namespace:name> <locationtag>`

Set block at a location
`- iaplace <namespace:name> <locationtag>`

Spawn entity at a location
`- iaspawn <namespace:name> <locationtag>`

Play totem animation
`- iatotemanimation <namespace:name> <playertag>`

## Events
Called when ItemsAdder has loaded. `<context.reload>` is a boolean if this was a reload.
`on itemsadder loaded:`

## Objects
`<itemsadder_item[namespace:name]>` - ItemsAdder item
`<itemsadder_entity[namespace:name]>` - ItemsAdder entity

## Properties
`<ElementTag.itemsadder.parse>` - Parses element with itemsadder placeholders
`<EntityTag.is_iaentity>` - Boolean if entity is itemsadder_entity
`<EntityTag.iaentity>` - Returns the itemsadder_entity tag
`<ItemTag.is_itemsadder>` - Boolean if itemsadder_item item
`<ItemTag.itemsadder>` - Returns itemsadder_item tag
`<LocationTag.is_itemsadder>` - Boolean if itemsadder_item item
`<LocationTag.itemsadder>` - Returns itemsadder_item tag

`<itemsadder_item.namespace>` - Namespace string
`<itemsadder_item.name>` - Name string (without namespace)
`<itemsadder_entity.namespace>` - Namespace string
`<itemsadder_entity.name>` - Name string (without namespace)


Because I haven't submitted this to the Depenzien plugin yet, and if you want to keep the implementation to be within the ItemsAdder codebase instead, I am happy to refactor the files over the next week, bring the naming into line with what you have already, add the files to this issue for you to review and potentially add into your codebase?

**Comment by LoneDev6** [comment]
> add the files to this issue for you to review and potentially add into your codebase?


I think making a separate plugin would do the trick too, isn't it possible?

Thanks for all your efforts!

**Comment by nomadjimbob** [comment]
It seems that most other plugins just add the Denizen bridge by contributing to the [Depenizen plugin](https://github.com/DenizenScript/Depenizen/blob/master/Docs/BukkitPlugins.md) using their own APIs.

That is the approach I've taken on my own server to get what I needed  done and works well.

The benefits of that approach is that any changes to the Denizen codebase are added automagically, and allows contributors to add/edit the IA bridge over time, hopefully taking, abit small, load off you.

It will take me a week or 2 to finalise and submit a PR to the Depenizen repo.

This can be closed and I'll ping you once it's all done, pushed and published. The IA/Denizen docs will be automatically generated over at [meta.denizenscript.com](https://meta.denizenscript.com) from comments inside the Depenizen codebase

**Comment by LoneDev6** [comment]
Amazing thanks for your efforts! Let me know.

**Comment by szarkans** [comment]
I beg for Denizen support

**Comment by bukkake747** [comment]
i NEED Denizen support 🙏🙏🙏 please😭

**Comment by PSYCHEER** [comment]
Currently
```
[17:44:01] [Server thread/INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[17:44:01] [Server thread/ERROR]: [ItemsAdder] Error while hooking into Denizen
[17:44:01] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/denizenscript/denizen/objects/ItemTag
[17:44:01] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Core.OtherPlugins.Denizen.DenizenHook.hook(SourceFile:22)
[17:44:01] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:355)
[17:44:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[17:44:01] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[17:44:01] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[17:44:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[17:44:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[17:44:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[17:44:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[17:44:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[17:44:01] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[17:44:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[17:44:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[17:44:01] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[17:44:01] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizen.objects.ItemTag
[17:44:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[17:44:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[17:44:01] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:44:01] [Server thread/WARN]: 	... 14 more
```
While enabling the ItemsAdder, idk if I should do a new issue or it's in state of "todo" as wasn't reported but maybe are devs aware of this...
