### ISSUE TITLE
Better Malformed Json error

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#2111]
### Discord tag (optional)

Raccoon#4485

### What happened?

Due to the new data format it is currently NOT possible to change the vanilla textures.
Furthermore, it is no longer possible to add textures through e.g. mythicmobs or the model engine.

Also the icon of the pack can not be edited.

### Steps to reproduce the issue

1. updated to the 3.3.0
2. transferred all textures to the new format
3. /iaz
4. itemsadder works (except for some bugs, see other issues)
5. added Minecraft textures
5.1 added in:
plugins\ItemsAdder\data\resource_pack\assets\minecraft
5.2 added in:
plugins\ItemsAdder\data\resourcepack\assets\minecraft
5.3 inserted In:
pluginsItemsAdder\contents\minecraft\resourcepack\assets\minecraft

Result: No error display and no working textures.
Or with method 5.1 and 5.3
an error (see below)

### ItemsAdder Version

3.3.0-beta-r4

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### LoneLibs Version

1.0.21

### Error (optional)

```shell
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
    at com.google.gson.JsonParser.parseReader(JsonParser.java:66) ~[gson-2.8.9.jar:?]
    at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[gson-2.8.9.jar:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:98) ~[gson-2.8.9.jar:?]
    at dev.lone.itemsadder.main.hZ.ct(SourceFile:671) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
    at dev.lone.itemsadder.main.P.a(SourceFile:2616) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
    at dev.lone.itemsadder.main.hx.a(SourceFile:85) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
    at dev.lone.itemsadder.main.P.a(SourceFile:2414) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-246]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-246]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.9.jar:?]
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
    at com.google.gson.JsonParser.parseReader(JsonParser.java:61) ~[gson-2.8.9.jar:?]
    ... 12 more
```

**Comment by LoneDev6** [comment]
Anyway seems one of the JSON files inside your `minecraft/item` folder is malformed.
The next update will throw a more specific error with the file name for you to easily identify it.
