### ISSUE TITLE
Problem with latest format changes

### ISSUE THREAD

**Issue by BendersRepublic** [PluginBugs/Issues-ItemsAdder#2113]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

PapaWulf#0001

### What happened?

i moved my assets to contents and deleted the old data folder, but i still get https://hastebin.com/fadobanume.properties

### Steps to reproduce the issue

Moved my previous files from data to contents

### Server version

Paper-263

### ItemsAdder Version

3.3.0-beta-r4

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[01:16:08 ERROR]: [ItemsAdder] [STDERR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[01:16:08 WARN]: Nag author(s): '[LoneDev]' of 'ItemsAdder' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[01:16:08 ERROR]: [ItemsAdder] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[01:16:08 ERROR]: [ItemsAdder] [STDERR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[01:16:08 WARN]: [ItemsAdder] Plugin ItemsAdder v3.3.0-beta-r4 generated an exception while executing task 26128
java.lang.ExceptionInInitializerError: null
        at dev.lone.shaded.itemsadder.com.jayway.jsonpath.internal.JsonContext.b(SourceFile:217) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.shaded.itemsadder.com.jayway.jsonpath.internal.JsonContext.a(SourceFile:77) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.itemsadder.main.hZ.a(SourceFile:877) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.itemsadder.main.hZ.ct(SourceFile:841) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.itemsadder.main.P.a(SourceFile:2616) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.itemsadder.main.hx.a(SourceFile:85) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at dev.lone.itemsadder.main.P.a(SourceFile:2414) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-271]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:355) ~[?:?]
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:115) ~[?:?]
        at dev.lone.shaded.itemsadder.com.jayway.jsonpath.spi.cache.CacheProvider.<clinit>(SourceFile:12) ~[ItemsAdder_3.3.0-beta-r4.jar:?]
        ... 13 more
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 129.213.126.113
      pack-port: 25575
    external-host:
      enabled: false
      url: https://www.dropbox.com/s/e5vn5ri7uht8vtv/BendersRepublic%20RP.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - vanilla
    - _iainternal
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  force-sync-loading: false
blocks:
  light-api: false
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: false
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: true
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: false
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 200
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: false
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
ignore-server-compatibility-check: false
```

**Comment by BendersRepublic** [comment]
did a binary search, it's my /assets/minecraft/font/ contents

https://gyazo.com/1479bf2b83e12b6bf5c2fb1d114318d8
https://hastebin.com/apemeziwat.json < default.json

**Comment by LoneDev6** [comment]
> did a binary search, it's my /assets/minecraft/font/ contents

Can I see the FULL path (relative to the server root folder) of the default.json file? Where is this file? 
Thanks.

**Comment by LoneDev6** [comment]
Found the issue btw, seems strange that the beta testing team didn't notice that...
