### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2117]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[14:36:05 ERROR]: [ItemsAdder] SocketException while handling self-host
[14:36:05 WARN]: java.net.SocketException: Socket closed
[14:36:05 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:675)
[14:36:05 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:748)
[14:36:05 WARN]: 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:690)
[14:36:05 WARN]: 	at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:655)
[14:36:05 WARN]: 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:631)
[14:36:05 WARN]: 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:588)
[14:36:05 WARN]: 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:546)
[14:36:05 WARN]: 	at ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.iD.c(SourceFile:65)
[14:36:05 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[14:36:05 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[14:36:05 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:36:05 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:36:05 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[14:36:05 INFO]: [ItemsAdder] [Host] Started self-host webserver on port: 8163
[14:36:05 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[14:36:05 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_head Another item is already using model_id 15 [flamos_set:flamos_head]
[14:36:06 ERROR]: [ItemsAdder] Error loading MMOItems integration for item flamos_set:flamos_head. Please check if the MMOItem of type 'ARMOR' and id 'FLAMOS_HEAD' exists in MMOItems plugin. File: /contents/_iainternal/configs/flamos_set/flamos_head.yml
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_1 Another item is already using model_id 1080401 [skills_kitetsu:demon_fairy_dance_s2_1]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_2 Another item is already using model_id 1080402 [skills_kitetsu:demon_fairy_dance_s2_2]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_3 Another item is already using model_id 1080403 [skills_kitetsu:demon_fairy_dance_s2_3]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_4 Another item is already using model_id 1080404 [skills_kitetsu:demon_fairy_dance_s2_4]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_5 Another item is already using model_id 1080405 [skills_kitetsu:demon_fairy_dance_s2_5]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s2_6 Another item is already using model_id 1080406 [skills_kitetsu:demon_fairy_dance_s2_6]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_1 Another item is already using model_id 1080801 [skills_kitetsu:double_vertical_slash_red_1]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_2 Another item is already using model_id 1080802 [skills_kitetsu:double_vertical_slash_red_2]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_3 Another item is already using model_id 1080803 [skills_kitetsu:double_vertical_slash_red_3]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_4 Another item is already using model_id 1080804 [skills_kitetsu:double_vertical_slash_red_4]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_5 Another item is already using model_id 1080805 [skills_kitetsu:double_vertical_slash_red_5]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_6 Another item is already using model_id 1080806 [skills_kitetsu:double_vertical_slash_red_6]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_7 Another item is already using model_id 1080807 [skills_kitetsu:double_vertical_slash_red_7]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_red_8 Another item is already using model_id 1080808 [skills_kitetsu:double_vertical_slash_red_8]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_1 Another item is already using model_id 1081301 [skills_kitetsu:redbuff_1]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_2 Another item is already using model_id 1081302 [skills_kitetsu:redbuff_2]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_3 Another item is already using model_id 1081303 [skills_kitetsu:redbuff_3]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_4 Another item is already using model_id 1081304 [skills_kitetsu:redbuff_4]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_5 Another item is already using model_id 1081305 [skills_kitetsu:redbuff_5]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_6 Another item is already using model_id 1081306 [skills_kitetsu:redbuff_6]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_7 Another item is already using model_id 1081307 [skills_kitetsu:redbuff_7]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_8 Another item is already using model_id 1081308 [skills_kitetsu:redbuff_8]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_9 Another item is already using model_id 1081309 [skills_kitetsu:redbuff_9]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_10 Another item is already using model_id 1081310 [skills_kitetsu:redbuff_10]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_11 Another item is already using model_id 1081311 [skills_kitetsu:redbuff_11]
[14:36:06 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:redbuff_12 Another item is already using model_id 1081312 [skills_kitetsu:redbuff_12]
[14:36:06 ERROR]: [ItemsAdder] Error loading MMOItems integration for item fuben:fb_gem_27. Please check if the MMOItem of type 'MATERIAL' and id 'TIN_INGOT' exists in MMOItems plugin. File: /contents/_iainternal/configs/fuben/fuben_gem.yml
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_1 Another item is already using model_id 1081901 [skills_kitetsu:vertical_slash_red_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_2 Another item is already using model_id 1081902 [skills_kitetsu:vertical_slash_red_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_3 Another item is already using model_id 1081903 [skills_kitetsu:vertical_slash_red_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_4 Another item is already using model_id 1081904 [skills_kitetsu:vertical_slash_red_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_5 Another item is already using model_id 1081905 [skills_kitetsu:vertical_slash_red_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_6 Another item is already using model_id 1081906 [skills_kitetsu:vertical_slash_red_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_7 Another item is already using model_id 1081907 [skills_kitetsu:vertical_slash_red_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_8 Another item is already using model_id 1081908 [skills_kitetsu:vertical_slash_red_8]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_9 Another item is already using model_id 1081909 [skills_kitetsu:vertical_slash_red_9]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:vertical_slash_red_10 Another item is already using model_id 1081910 [skills_kitetsu:vertical_slash_red_10]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_1 Another item is already using model_id 1081201 [skills_kitetsu:horz_slash_red_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_2 Another item is already using model_id 1081202 [skills_kitetsu:horz_slash_red_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_3 Another item is already using model_id 1081203 [skills_kitetsu:horz_slash_red_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_4 Another item is already using model_id 1081204 [skills_kitetsu:horz_slash_red_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_5 Another item is already using model_id 1081205 [skills_kitetsu:horz_slash_red_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_6 Another item is already using model_id 1081206 [skills_kitetsu:horz_slash_red_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_7 Another item is already using model_id 1081207 [skills_kitetsu:horz_slash_red_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_8 Another item is already using model_id 1081208 [skills_kitetsu:horz_slash_red_8]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_9 Another item is already using model_id 1081209 [skills_kitetsu:horz_slash_red_9]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_red_10 Another item is already using model_id 1081210 [skills_kitetsu:horz_slash_red_10]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_1 Another item is already using model_id 1080701 [skills_kitetsu:double_vertical_slash_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_2 Another item is already using model_id 1080702 [skills_kitetsu:double_vertical_slash_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_3 Another item is already using model_id 1080703 [skills_kitetsu:double_vertical_slash_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_4 Another item is already using model_id 1080704 [skills_kitetsu:double_vertical_slash_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_5 Another item is already using model_id 1080705 [skills_kitetsu:double_vertical_slash_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_6 Another item is already using model_id 1080706 [skills_kitetsu:double_vertical_slash_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_7 Another item is already using model_id 1080707 [skills_kitetsu:double_vertical_slash_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:double_vertical_slash_8 Another item is already using model_id 1080708 [skills_kitetsu:double_vertical_slash_8]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_chestplate Another item is already using model_id 5 [flamos_set:flamos_chestplate]
[14:36:07 ERROR]: [ItemsAdder] Error loading MMOItems integration for item flamos_set:flamos_chestplate. Please check if the MMOItem of type 'ARMOR' and id 'FLAMOS_CHESTPLATE' exists in MMOItems plugin. File: /contents/_iainternal/configs/flamos_set/flamos_armor.yml
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_leggings Another item is already using model_id 5 [flamos_set:flamos_leggings]
[14:36:07 ERROR]: [ItemsAdder] Error loading MMOItems integration for item flamos_set:flamos_leggings. Please check if the MMOItem of type 'ARMOR' and id 'FLAMOS_LEGGINGS' exists in MMOItems plugin. File: /contents/_iainternal/configs/flamos_set/flamos_armor.yml
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_boots Another item is already using model_id 5 [flamos_set:flamos_boots]
[14:36:07 ERROR]: [ItemsAdder] Error loading MMOItems integration for item flamos_set:flamos_boots. Please check if the MMOItem of type 'ARMOR' and id 'FLAMOS_BOOTS' exists in MMOItems plugin. File: /contents/_iainternal/configs/flamos_set/flamos_armor.yml
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:sword_1 Another item is already using model_id 1081701 [skills_kitetsu:sword_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:sword_2 Another item is already using model_id 1081702 [skills_kitetsu:sword_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:sword_3 Another item is already using model_id 1081703 [skills_kitetsu:sword_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:sword_4 Another item is already using model_id 1081704 [skills_kitetsu:sword_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:sword_5 Another item is already using model_id 1081705 [skills_kitetsu:sword_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_1 Another item is already using model_id 1080301 [skills_kitetsu:demon_fairy_dance_s1_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_2 Another item is already using model_id 1080302 [skills_kitetsu:demon_fairy_dance_s1_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_3 Another item is already using model_id 1080303 [skills_kitetsu:demon_fairy_dance_s1_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_4 Another item is already using model_id 1080304 [skills_kitetsu:demon_fairy_dance_s1_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_5 Another item is already using model_id 1080305 [skills_kitetsu:demon_fairy_dance_s1_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_s1_6 Another item is already using model_id 1080306 [skills_kitetsu:demon_fairy_dance_s1_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:emma Another item is already using model_id 1080101 [skills_kitetsu:emma]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:goldenkatana Another item is already using model_id 1080102 [skills_kitetsu:goldenkatana]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:katanadragonblue Another item is already using model_id 1080103 [skills_kitetsu:katanadragonblue]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:katanaghost Another item is already using model_id 1080104 [skills_kitetsu:katanaghost]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:katanasamurai Another item is already using model_id 1080105 [skills_kitetsu:katanasamurai]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:katanatiger Another item is already using model_id 1080106 [skills_kitetsu:katanatiger]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:orinakatana Another item is already using model_id 1080107 [skills_kitetsu:orinakatana]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:violetkatana Another item is already using model_id 1080108 [skills_kitetsu:violetkatana]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_1 Another item is already using model_id 1081001 [skills_kitetsu:horz_slash_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_2 Another item is already using model_id 1081002 [skills_kitetsu:horz_slash_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_3 Another item is already using model_id 1081003 [skills_kitetsu:horz_slash_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_4 Another item is already using model_id 1081004 [skills_kitetsu:horz_slash_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_5 Another item is already using model_id 1081005 [skills_kitetsu:horz_slash_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_6 Another item is already using model_id 1081006 [skills_kitetsu:horz_slash_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_7 Another item is already using model_id 1081007 [skills_kitetsu:horz_slash_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_8 Another item is already using model_id 1081008 [skills_kitetsu:horz_slash_8]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_9 Another item is already using model_id 1081009 [skills_kitetsu:horz_slash_9]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:horz_slash_10 Another item is already using model_id 1081010 [skills_kitetsu:horz_slash_10]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item customfishing:nature_fishing_cane Another item is already using model_id 2 [customfishing:nature_fishing_cane]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item customfishing:silver_fishing_rod Another item is already using model_id 3 [customfishing:silver_fishing_rod]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item customfishing:golden_fishing_rod Another item is already using model_id 4 [customfishing:golden_fishing_rod]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item customfishing:star_fishing_rod Another item is already using model_id 5 [customfishing:star_fishing_rod]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_1 Another item is already using model_id 1080201 [skills_kitetsu:demon_fairy_dance_ef_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_2 Another item is already using model_id 1080202 [skills_kitetsu:demon_fairy_dance_ef_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_3 Another item is already using model_id 1080203 [skills_kitetsu:demon_fairy_dance_ef_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_4 Another item is already using model_id 1080204 [skills_kitetsu:demon_fairy_dance_ef_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_5 Another item is already using model_id 1080205 [skills_kitetsu:demon_fairy_dance_ef_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item skills_kitetsu:demon_fairy_dance_ef_6 Another item is already using model_id 1080206 [skills_kitetsu:demon_fairy_dance_ef_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_1 Another item is already using model_id 1 [flamos_set:flamos_blaze_leap_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_2 Another item is already using model_id 2 [flamos_set:flamos_blaze_leap_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_3 Another item is already using model_id 3 [flamos_set:flamos_blaze_leap_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_4 Another item is already using model_id 4 [flamos_set:flamos_blaze_leap_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_5 Another item is already using model_id 5 [flamos_set:flamos_blaze_leap_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_6 Another item is already using model_id 6 [flamos_set:flamos_blaze_leap_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_blaze_leap_7 Another item is already using model_id 7 [flamos_set:flamos_blaze_leap_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_1 Another item is already using model_id 8 [flamos_set:flamos_flame_slash_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_2 Another item is already using model_id 9 [flamos_set:flamos_flame_slash_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_3 Another item is already using model_id 10 [flamos_set:flamos_flame_slash_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_4 Another item is already using model_id 11 [flamos_set:flamos_flame_slash_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_5 Another item is already using model_id 12 [flamos_set:flamos_flame_slash_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_6 Another item is already using model_id 13 [flamos_set:flamos_flame_slash_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_flame_slash_7 Another item is already using model_id 14 [flamos_set:flamos_flame_slash_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_1 Another item is already using model_id 16 [flamos_set:flamos_hellfire_slash_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_2 Another item is already using model_id 17 [flamos_set:flamos_hellfire_slash_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_3 Another item is already using model_id 18 [flamos_set:flamos_hellfire_slash_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_4 Another item is already using model_id 19 [flamos_set:flamos_hellfire_slash_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_5 Another item is already using model_id 20 [flamos_set:flamos_hellfire_slash_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_6 Another item is already using model_id 21 [flamos_set:flamos_hellfire_slash_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_hellfire_slash_7 Another item is already using model_id 22 [flamos_set:flamos_hellfire_slash_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno Another item is already using model_id 23 [flamos_set:flamos_inferno]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_1 Another item is already using model_id 24 [flamos_set:flamos_inferno_wheel_1]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_2 Another item is already using model_id 25 [flamos_set:flamos_inferno_wheel_2]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_3 Another item is already using model_id 26 [flamos_set:flamos_inferno_wheel_3]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_4 Another item is already using model_id 27 [flamos_set:flamos_inferno_wheel_4]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_5 Another item is already using model_id 28 [flamos_set:flamos_inferno_wheel_5]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_6 Another item is already using model_id 29 [flamos_set:flamos_inferno_wheel_6]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_7 Another item is already using model_id 30 [flamos_set:flamos_inferno_wheel_7]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_8 Another item is already using model_id 31 [flamos_set:flamos_inferno_wheel_8]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_9 Another item is already using model_id 32 [flamos_set:flamos_inferno_wheel_9]
[14:36:07 ERROR]: [ItemsAdder] Cannot set model_id for item flamos_set:flamos_inferno_wheel_10 Another item is already using model_id 33 [flamos_set:flamos_inferno_wheel_10]
[14:36:07 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[14:36:07 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "<local5>" is null
[14:36:07 WARN]: 	at ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.P.a(SourceFile:2949)
[14:36:07 WARN]: 	at ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.P.b(SourceFile:1252)
[14:36:07 WARN]: 	at ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.P.a(SourceFile:592)
[14:36:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[14:36:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:36:07 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500)
[14:36:07 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[14:36:07 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[14:36:07 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[14:36:07 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[14:36:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)

### Steps to reproduce the issue

new jar in plugins.

### ItemsAdder Version

3.3.0-rRRRRRRRRRRRRRR4

### ProtocolLib Version

2.4.17

### LoneLibs Version

2.4.17

**Comment by LoneDev6** [comment]
Update to the new version 3.3.0-beta-r5
