### ISSUE TITLE
Error loading the plugin, something is not configured right or an exception occured.

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#2120]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

[23:06:02 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[23:06:02 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.hU.z(SourceFile:489)
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.b(SourceFile:790)
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.a(SourceFile:592)
[23:06:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[23:06:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:06:02 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1154)
[23:06:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[23:06:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce the issue

xx

### ItemsAdder Version

latestt

### ProtocolLib Version

latestt

### LoneLibs Version

latestt

### FULL server log

x

### Error (optional)

```shell
[23:06:02 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[23:06:02 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.hU.z(SourceFile:489)
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.b(SourceFile:790)
[23:06:02 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.a(SourceFile:592)
[23:06:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[23:06:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:06:02 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1154)
[23:06:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[23:06:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ItemsAdder config.yml

```shell
metrics: false
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: true
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: https://www.dropbox.com/s/ab6grqfbet2o6s6/pack.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: true
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    - psd
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - vanilla
    - _iainternal
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: cz
  dictionaries-lang: cz
  extract-default-resources: false
  force-sync-loading: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
  cancel-break-wrong-tool:
    enabled: false
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: true
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
ignore-server-compatibility-check: false
```

**Comment by ArubikU** [comment]
*WOW SAME ISSUE*
[02:13:26 ERROR]: [AnimaCraft] Error loading the plugin, something is not configured right or an exception occured. More detail:
[02:13:26 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
[02:13:26 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.hU.z(SourceFile:489)
[02:13:26 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.b(SourceFile:790)
[02:13:26 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.P.a(SourceFile:592)
[02:13:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[02:13:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[02:13:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500)
[02:13:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[02:13:26 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[02:13:26 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[02:13:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[02:13:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ArubikU** [comment]
![image](https://user-images.githubusercontent.com/102335860/203451810-8c06381b-69d9-4afc-90a9-7e6606f1f9f1.png)
the <parameter1> dont appear XD

**Comment by LoneDev6** [comment]
Fixed in upcoming update

**Comment by EloyCubo** [comment]
I have the same error v3.5.0c-r6

**Comment by LoneDev6** [comment]
> I have the same error v3.5.0c-r6

This is an issue report form 2022, please avoid commenting on very old issue reports which were already solved.
