### ISSUE TITLE
Craft Async Scheduler Management Thread

### ISSUE THREAD

**Issue by JuliGame** [PluginBugs/Issues-ItemsAdder#2133]
### Discord tag (optional)

JuliGame#8036

### What happened?

_Im not using latest because it breakes my recipes. Im using r4, but this bug is not fixed in the changelogs._

**The problem**
Suddendly the console starts spamming:
```
[Craft Async Scheduler Management Thread/ERROR]: Craft Async Scheduler Management Thread
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:802) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1013) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Before that this happened:
```
 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-285 (MC: 1.19.2) ---
 The server has not responded for 10 seconds! Creating thread dump
 ------------------------------
 Server thread dump (Look for plugins here before reporting to Paper!):
 [ChunkTaskScheduler] Chunk wait task info below: 
 [ChunkTaskScheduler] Chunk wait: [( 605,310) in 'world']
 [ChunkTaskScheduler] Chunk holder: NewChunkHolder{world=world, chunkX=605, chunkZ=310, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=null,status=null}, currentGenStatus=null, requestedGenStatus=minecraft:full, generationTask=ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkLoadTask, for world: world, chunk: (605,310), hashcode: 445854454, priority: COMPLETING, status: minecraft:empty, scheduled: true}, generationTaskStatus=minecraft:empty, priority=BLOCKING, priorityLocked=false, neighbourRequestedPriority=IDLE, effective_priority=BLOCKING, oldTicketLevel=33, currentTicketLevel=33, totalNeighboursUsingThisChunk=1, fullNeighbourChunksLoadedBitset=25137, chunkStatusRaw=0, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}
 ------------------------------
 Current Thread: Server thread
 	PID: 28 | Suspended: false | Native: false | State: RUNNABLE
 	Stack:
 		net.minecraft.world.level.chunk.PalettedContainer.get(PalettedContainer.java:208)
 		net.minecraft.world.level.chunk.LevelChunk.getBlockStateFinal(LevelChunk.java:461)
 		net.minecraft.world.level.chunk.LevelChunk.getBlockState(LevelChunk.java:447)
 		net.minecraft.world.level.Level.getBlockState(Level.java:782)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.getType(CraftBlock.java:227)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.b(SourceFile:394)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.c(SourceFile:509)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c09400.invokeSpecial(LambdaForm$DMH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802c89800.invoke(LambdaForm$MH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802041000.invoke_MT(LambdaForm$MH)
 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
 		net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:651)
 		net.minecraft.world.level.Level.setBlock(Level.java:604)
 		net.minecraft.world.level.Level.setBlock(Level.java:513)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:210)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:195)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:191)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:185)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:257)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:210)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:584)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c09400.invokeSpecial(LambdaForm$DMH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802be9800.invoke(LambdaForm$MH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802041000.invoke_MT(LambdaForm$MH)
 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
 		net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:916)
 		net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:868)
 		io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919)
 		net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:582)
 		net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1000)
 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
 		net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:450)
 		net.minecraft.world.level.Level.getChunk(Level.java:502)
 		net.minecraft.world.level.Level.getBlockState(Level.java:780)
 		net.minecraft.world.level.LevelReader.getDirectSignal(LevelReader.java:122)
 		net.minecraft.world.level.Level.getDirectSignalTo(Level.java:1112)
 		net.minecraft.world.level.Level.getSignal(Level.java:1137)
 		net.minecraft.world.level.Level.hasNeighborSignal(Level.java:1141)
 		net.minecraft.world.level.block.NoteBlock.neighborChanged(NoteBlock.java:50)
 		net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.neighborChanged(BlockBehaviour.java:975)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:137)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:45)
 		net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1723)
 		net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2344)
 		net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:637)
 		net.minecraft.world.level.Level.setBlock(Level.java:604)
 		net.minecraft.world.level.Level.setBlock(Level.java:513)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:210)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:195)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:191)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:185)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:257)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:210)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:584)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c09400.invokeSpecial(LambdaForm$DMH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802be9800.invoke(LambdaForm$MH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802041000.invoke_MT(LambdaForm$MH)
 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
 		net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:916)
 		net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:868)
 		io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919)
 		net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:582)
 		net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1000)
 		net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578)
 		net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2715)
 		net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2738)
 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319)
 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311)
 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389)
 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
 		net.minecraft.server.MinecraftServer$$Lambda$4362/0x00000008014da740.run(Unknown Source)
 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
 ------------------------------
 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
 ------------------------------
 
 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-285 (MC: 1.19.2) ---
 The server has not responded for 15 seconds! Creating thread dump
 ------------------------------
 Server thread dump (Look for plugins here before reporting to Paper!):
 ------------------------------
 Current Thread: Server thread
 	PID: 28 | Suspended: false | Native: false | State: RUNNABLE
 	Stack:
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.iX.a(SourceFile:724)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.iX.b(SourceFile:705)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cT.m(SourceFile:592)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cT.c(SourceFile:89)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c09400.invokeSpecial(LambdaForm$DMH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802c89000.invoke(LambdaForm$MH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802041000.invoke_MT(LambdaForm$MH)
 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
 		org.bukkit.event.Event.callEvent(Event.java:45)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:132)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63)
 		net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:45)
 		net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1723)
 		net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2344)
 		net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:637)
 		net.minecraft.world.level.Level.setBlock(Level.java:604)
 		net.minecraft.world.level.Level.setBlock(Level.java:513)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:210)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:195)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:191)
 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.setBlockData(CraftBlock.java:185)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:257)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:210)
 		ItemsAdder_3.3.0-beta-r4.jar//dev.lone.itemsadder.main.cQ.a(SourceFile:584)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$DMH/0x0000000800c09400.invokeSpecial(LambdaForm$DMH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802be9800.invoke(LambdaForm$MH)
 		java.base@17.0.2/java.lang.invoke.LambdaForm$MH/0x0000000802041000.invoke_MT(LambdaForm$MH)
 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
 		net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:916)
 		net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:868)
 		io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034)
 		io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919)
 		net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:582)
 		net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1000)
 		net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578)
 		net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2715)
 		net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2738)
 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319)
 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311)
 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389)
 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
 		net.minecraft.server.MinecraftServer$$Lambda$4362/0x00000008014da740.run(Unknown Source)
 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
 ------------------------------
 --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
 ------------------------------
```

Well after reading "unable to create native thread". I made a plugin to see the current threads, before this there were 170 threads and after this there were 476 threads, and a lot are from IA.
**Threads Info:** 
[ThreadLog_1669335043.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10087761/ThreadLog_1669335043.txt)

### Steps to reproduce the issue

1. Unknown

### Server version

git-Paper-285

### ItemsAdder Version

ItemsAdder_3.3.0-beta-r4

### ProtocolLib Version

1.19 Latest build. Compilacion: 602

### LoneLibs Version

Lonelib 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10087769/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - vanilla
    - _iainternal
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
ignore-server-compatibility-check: false
```

**Comment by LoneDev6** [comment]
This is quite strange, I'll add you on a private Discord ticket in order to identify the cause.

**Comment by LoneDev6** [comment]
Added! Please make sure to download the new beta and let me know :D 
https://discord.com/channels/533407895010803753/1047198933924982824/1047202281268969522
