### ISSUE TITLE
Start error with Denizen Version 1.2.5-b1780-REL

### ISSUE THREAD

**Issue by TasnSchimmerlos** [PluginBugs/Issues-ItemsAdder#2139]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Tasn#7326

### What happened?
```
starting with ItemnAdder v3.3.0-beta-r8 and Denizen 1.2.5-b1780-REL throws the following error on the console:
[15:28:46 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.3.0-beta-r8
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.21
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-278 (MC: 1.19.2)
                                               
[15:28:46 INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: https://a.devs.beer/lightapi-new
[15:28:46 WARN]: [ItemsAdder] Loaded class com.denizenscript.denizen.objects.ItemTag from Denizen v1.2.5-SNAPSHOT (build 1780-REL) which is not a depend or softdepend of this plugin.
[15:28:46 ERROR]: [ItemsAdder] Error while hooking into Denizen
[15:28:46 WARN]: java.lang.NoSuchMethodError: com/denizenscript/denizencore/tags/ObjectTagProcessor.registerMechanism(Ljava/lang/String;ZLjava/lang/Class;Lcom/denizenscript/denizencore/objects/Mechanism$ObjectInputMechRunnerInterface;)V (loaded from file:/home/container/plugins/Denizen-1.2.5-b1780-REL.jar by PluginClassLoader{plugin=Denizen v1.2.5-SNAPSHOT (build 1780-REL), pluginEnabled=true, url=plugins/Denizen-1.2.5-b1780-REL.jar}) called from class dev.lone.itemsadder.Core.OtherPlugins.Denizen.DenizenHook (loaded from file:/home/container/plugins/ItemsAdder_3.3.0-beta-r8.jar by PluginClassLoader{plugin=ItemsAdder v3.3.0-beta-r8, pluginEnabled=true, url=plugins/ItemsAdder_3.3.0-beta-r8.jar}).
[15:28:46 WARN]:        at ItemsAdder_3.3.0-beta-r8.jar//dev.lone.itemsadder.Core.OtherPlugins.Denizen.DenizenHook.hook(SourceFile:55)
[15:28:46 WARN]:        at ItemsAdder_3.3.0-beta-r8.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:422)
[15:28:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:28:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:28:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[15:28:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[15:28:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[15:28:46 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[15:28:46 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[15:28:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[15:28:46 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[15:28:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[15:28:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:857)
[15:28:46 INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
```
### Steps to reproduce the issue

see "What happened"

### Server version

This server is running Paper version git-Paper-278 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b95d4b2)

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r8

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b605

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Will be fixed, please also update to Denizen-1.2.6-b1783-REL https://ci.citizensnpcs.co/job/Denizen/
