### ISSUE TITLE
Smithing recipes not working on Spigot, only on Paper

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2149]
```
[13:31:33] [Server thread/ERROR]: Could not pass event PrepareSmithingEvent to ItemsAdder v3.3.0-beta-r8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPrepareSmithingEvent(CraftEventFactory.java:1497) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.ContainerSmithing.l(ContainerSmithing.java:76) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:80) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.ContainerAnvilAbstract$1.e(ContainerAnvilAbstract.java:25) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.InventorySubcontainer.a(InventorySubcontainer.java:203) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.Slot.d(SourceFile:61) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.Container.a(Container.java:822) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:124) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.Container.b(Container.java:532) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.world.inventory.Container.a(Container.java:375) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2884) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.inventory.SmithingInventory.getInputEquipment()'
	at dev.lone.itemsadder.main.fG.a(SourceFile:174) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor755.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 30 more
```

**Comment by dinobossytnew** [comment]
yes bug and 

`[22:22:30 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v3.3.0-beta-r9
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 5
        at dev.lone.itemsadder.main.fv.a(SourceFile:214) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at dev.lone.itemsadder.main.fv.a(SourceFile:185) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:185) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:247) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:214) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at dev.lone.itemsadder.main.fx.a(SourceFile:298) ~[ItemsAdder_3.3.0-beta-r9.jar:?]
        at java.lang.invoke.LambdaForm$DMH/0x00000000710e0900.invokeSpecial(LambdaForm$DMH) ~[?:?]
        at java.lang.invoke.LambdaForm$MH/0x000000005e3e41f0.invoke(LambdaForm$MH) ~[?:?]
        at java.lang.invoke.LambdaForm$MH/0x00000000701d2100.invoke_MT(LambdaForm$MH) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1368) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[?:?]
        at net.minecraft.world.inventory.InventoryMenu.slotsChanged(InventoryMenu.java:141) ~[?:?]
        at net.minecraft.world.inventory.CraftingContainer.removeItem(CraftingContainer.java:132) ~[?:?]
        at net.minecraft.world.inventory.ResultSlot.onTake(ResultSlot.java:67) ~[?:?]
        at net.minecraft.world.inventory.InventoryMenu.quickMoveStack(InventoryMenu.java:215) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:540) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2869) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$9927/0x0000000072ef8350.run(Unknown Source) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer$$Lambda$4056/0x000000008a2ebb28.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by LoneDev6** [comment]
@dinobossytnew  It has nothing to do with Smithing, please avoid commenting on random issues pages
