### ISSUE TITLE
When use iaemote,the console spam " java.lang.NullPointerException"

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#2159]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

neverlag#6619

### What happened?

When players use /iaemote,the console will spam" java.lang.NullPointerException".
Not always happen,my server run some time and before all is fine.

You can see the lastest.log and the error

### Steps to reproduce the issue

1. use /iaemote bow
2. the console start spam

Not sure you can reprouduce this one,just see the log and error

### Server version

purpur-1854(1.19.2)

### ItemsAdder Version

3.3.0-beta-r9

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10133165/latest.log)

### Error (optional)

```shell
[21:12:25] [pool-46-thread-1/WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.ChannelHandlerContext.channel()" because "<parameter1>" is null
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.kh.a(SourceFile:61)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.kh.a(SourceFile:44)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.nms.aR.impl.v1_19_R1_2.a(SourceFile:33)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.nms.aR.impl.v1_19_R1_2.c(SourceFile:14)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.nms.aR.bC.c(SourceFile:36)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.nms.aD.impl.v1_19_R1_2.a(SourceFile:547)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.nms.aD.impl.v1_19_R1_2.a(SourceFile:448)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aL.an(SourceFile:561)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aL.a(SourceFile:273)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aK.a(SourceFile:86)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aK.a(SourceFile:81)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aJ.ac(SourceFile:132)
[21:12:25] [pool-46-thread-1/WARN]: 	at ItemsAdder_3.3.0-beta-r9.jar//dev.lone.itemsadder.main.aq.E(SourceFile:780)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:12:25] [pool-46-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
I think you have another plugin which is messing up with packets channels.
For some reason it's deleting my channel at some point, this is causing the plugin to fail sending packets.

I can try adding a temporary fix but I cannot guarantee it will work correctly.
