### ISSUE TITLE
Issue with multiple armor textures

### ISSUE THREAD

**Issue by jere62smi** [PluginBugs/Issues-ItemsAdder#2176]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

jere62smi#2156

### What happened?

Hello,

I allow myself to send you contact via github because I have not found a way to find how to make a ticket on the Discord but only ItemsAdder-communities but I have no answer.

So here it is, I try to add several armors but when I add a second, or more I encounter an error with my texturepack, it works. The problem is that the texture worn by the player does not work and applies the colors given in color: "#fffff0".

In my configuration, only the armor named "kraken_set" and all its related items work
As you can see, the one if works correctly, whether it's in the inventory as worn by a player.

Here is an armor where I have the problem, on the screen, I have my 2 textures in the correct inventory, on the other hand if I have worn it, I have the color of the leather armor entered in the config file.

I tried to find on the wiki or others how to add several armors in configuration, I must surely have made a mistake, if you could help me and explain me 🙂

I posted screens below of a texture that works correctly (inventory + player) and another that does not work (inventory + player).

I remain available on Discord in pm if you ever need more information or directly come to my test server to show you the problem encountered.

### Steps to reproduce the issue

If I add an extra argument other than my_armor, I get the error and the texture problem.

  my_armor:
    color: "#d60000"
    layer_1: kraken_set
    layer_2: kraken_set_2
    use_color: false
  my_armor2:
    color: "#ffffff"
    layer_1: king_chestplate
    use_color: false
  my_armor3:
    color: "#fffff0"
    layer_1: noel_set
    use_color: false

### Server version

git-Purpur-1857 (MC 1.19.2)

### ItemsAdder Version

ItemsAdder 3.2.5-r3

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs 1.0.21

### Error (optional)

```shell
[20:02:40] [Server thread/INFO]: jere62smi issued server command: /iazip
[20:02:40] [Server thread/INFO]: [ItemsAdder] [0m[38;5;51m[Pack] Extracting utility resource_pack assets from .jar[0m
[20:02:40] [Server thread/INFO]: [ItemsAdder] [0m[38;5;10m[Pack] DONE extracting utility resource_pack assets from .jar[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mLoaded [38;5;51m229[38;5;11m items[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m0[38;5;11m/[38;5;51m188[38;5;11m REAL block IDs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m29[38;5;11m/[38;5;51m750[38;5;11m REAL_NOTE block IDs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m0[38;5;11m/[38;5;51m63[38;5;11m REAL_TRANSPARENT block IDs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m0[38;5;11m/[38;5;51m127[38;5;11m REAL_WIRE block IDs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m0[38;5;11m/[38;5;51m14[38;5;11m FIRE block IDs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;11mUsed [38;5;51m699[38;5;11m/[38;5;51m6608[38;5;11m font_images[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[Init] Loaded [38;5;51m5[38;5;11m categories[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[Init] Loaded [38;5;51m229[38;5;10m items and stuff in [38;5;51m225ms[0m
[20:02:40] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[20:02:40] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[20:02:40] [Server thread/INFO]: [EvenMoreFish] Detected that itemsadder has finished loading all items...
[20:02:40] [Server thread/INFO]: [EvenMoreFish] Reloading EMF.
[20:02:40] [Server thread/INFO]: [ItemsAdder] [0mReloading ItemsAdder Custom Entities Citizens NPCs[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at java.desktop/sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:298)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at java.desktop/java.awt.image.BufferedImage.setRGB(BufferedImage.java:1017)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.ha.a(SourceFile:481)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.ha.a(SourceFile:382)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.ha.cr(SourceFile:244)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.hn.cD(SourceFile:418)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.aA.a(SourceFile:2607)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.au.a(SourceFile:91)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at ItemsAdder_3.2.5-r3.jar//dev.lone.itemsadder.main.aA.a(SourceFile:2407)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:02:40] [Server thread/INFO]: [Mythic] Reloading plugin...
[20:02:40] [Server thread/INFO]: [MythicMobs] Mythic beginning reload procedure...[0m
[20:02:40] [Server thread/INFO]: [MythicMobs] Loading Packs...[0m
[20:02:40] [Server thread/INFO]: [MythicMobs] Loading Items...[0m
[20:02:40] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[OK] Your zip file will be protected from unzip (as set in config.yml)[0m
[20:02:40] [Server thread/INFO]: [MythicMobs] Loading Item Groups...[0m
[20:02:40] [Server thread/INFO]: [MythicMobs] Loading Skills...[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] Loading Drop Tables...[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] Loading Random Spawns...[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] Loading Spawn Blocks...[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 148 mobs.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 0 vanilla mob overrides.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 0 mob stacks.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 388 skills.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 0 random spawns.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 120 mythic items.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 0 drop tables.[0m
[20:02:41] [Server thread/INFO]: [MythicMobs] [32m✓[37m Loaded 213 mob spawners.[0m
[20:02:41] [Server thread/INFO]: [Mythic] Mythic has finished reloading!
[20:02:41] [Server thread/INFO]: [MythicMobs] Mythic has finished reloading![0m
[20:02:41] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;51m[Pack] Compressing resource_pack ... [0m
[20:02:41] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[Pack] Resource pack successfully compressed. Uploading...[0m
[20:02:41] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;51m[Pack] Uploading resourcepack...[0m
[20:02:43] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[Pack] Finished uploading resourcepack: http://resourcepack.host/dl/D4evETDAdZTTrgpZNQy1XivrlJMGicWL/pack.zip[0m
[20:02:53] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10m[Pack] Resourcepack URL is valid (auto-external-host), LastEdit: 2022-12-11_20-02. Url: http://resourcepack.host/dl/D4evETDAdZTTrgpZNQy1XivrlJMGicWL/pack.zip[0m
[20:02:53] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;51mApplying pack to every player... [0m
[20:02:53] [Craft Scheduler Thread - 42 - ItemsAdder/INFO]: [ItemsAdder] [0m[38;5;10mApplied pack to [38;5;11m1[38;5;10m players[0m
```

### ItemsAdder config.yml

```shell
metrics: false
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: https://drive.google.com/uc?export=view&id=1SlGvV4SZzsB43rGAtGZsgcpxI0s33fWQ
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - vanilla
    - _iainternal
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  force-sync-loading: false
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: true
    log-single-loaded-overwrite: true
    log-single-skip: true
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
chat-preview: false
ignore-server-compatibility-check: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: rpg
armors_rendering:
  my_armor:
    color: "#d60000"
    layer_1: kraken_set
    layer_2: kraken_set_2
    use_color: false
  my_armor2:
    color: "#ffffff"
    layer_1: king_chestplate
    use_color: false
  my_armor3:
    color: "#fffff0"
    layer_1: noel_set
    use_color: false
items:
  king_sword:
    display_name: Epée du Vieux Roi
    resource:
      material: golden_sword
      model_id: 10300
      generate: true
      textures: 
      - king_sword.png
  faux:
    display_name: Faux de la Faucheuse
    resource:
      material: iron_hoe
      model_id: 10302
      generate: true
      textures: 
      - faux.png
  bone_dague:
    display_name: Os du Gardien
    resource:
      material: iron_sword
      model_id: 10303
      generate: true
      textures: 
      - bone_dague.png
  guardian_shield:
    display_name: Carapace du Gardien
    resource:
      material: SHIELD
      model_id: 10304
      generate: true
      textures: 
      - guardian_shield.png
  pirate_sword:
    display_name: Epée du Pirate
    resource:
      material: diamond_sword
      model_id: 10301
      generate: false
      model_path: pirate_sword
  ogre_mace:
    display_name: Masse de l'Ogre
    resource:
      material: diamond_sword
      model_id: 10305
      generate: false
      model_path: ogre_mace
  baguette:
    display_name: Baguette de GuerreCendre
    resource:
      material: stick
      model_id: 10306
      generate: false
      model_path: baguette
#casque kraken
  kraken_hat:
    display_name: Casque du Kraken
    resource:
      model_id: 10307
      generate: true
      textures:
      - kraken_hat
    mmoitem:
      type: ARMOR
      id: CASQUE_KRAKEN
    specific_properties:
      armor:
        slot: head
        custom_armor: my_armor
#plastron kraken
  kraken_chestplate_item:
    display_name: Plastron du Kraken
    resource:
      model_id: 10308
      generate: true
      textures:
      - kraken_chestplate_item
    mmoitem:
      type: ARMOR
      id: PLASTRON_KRAKEN
    specific_properties:
      armor:
        slot: chest
        custom_armor: my_armor
#jambière kraken
  kraken_pants:
    display_name: Jambière du Kraken
    resource:
      model_id: 10309
      generate: true
      textures:
      - kraken_pants
    mmoitem:
      type: ARMOR
      id: JAMBIERE_KRAKEN
    specific_properties:
      armor:
        slot: legs
        custom_armor: my_armor
#bottes kraken
  kraken_boots:
    display_name: Bottes du Kraken
    resource:
      model_id: 10310
      generate: true
      textures:
      - kraken_boots
    mmoitem:
      type: ARMOR
      id: BOTTES_KRAKEN
    specific_properties:
      armor:
        slot: feet
        custom_armor: my_armor
  # plastron vieux roi
  king_chestplate:
    display_name: Plastron du Vieux Roi
    resource:
      model_id: 10311
      generate: true
      textures:
      - king_chestplate_item
    mmoitem:
      type: ARMOR
      id: VIEUX_ROI
    specific_properties:
      armor:
        slot: chest
        custom_armor: my_armor2
#bottes noel
  noel_boots:
    display_name: Bottes de Noel
    resource:
      model_id: 10312
      generate: true
      textures:
      - noel_boots
    specific_properties:
      armor:
        slot: feet
        custom_armor: my_armor3
#jambière noel
  noel_pants:
    display_name: Jambière de Noel
    resource:
      model_id: 10313
      generate: true
      textures:
      - noel_pants
    specific_properties:
      armor:
        slot: legs
        custom_armor: my_armor3
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image1](https://user-images.githubusercontent.com/31114661/206925948-3bcb45d9-2ebd-45e6-851b-11804aa7fb7d.png)
![image2](https://user-images.githubusercontent.com/31114661/206925949-f6678692-8c9f-4389-aa7e-ae4b1b0f6d69.png)

**Comment by jere62smi** [comment]
Hello,
First of all, I would like to thank you for taking the time to answer and help me.
Is it possible that you send me a Discord message or other networks to send you my configuration files and avoid sharing them for everyone.
The configuration to test is located in:
data/items_packs/rpg/rpg.yml
Textures in pgn format can be found in data/resource_pack/assets/rpg
Looking forward to your return.

**Comment by LoneDev6** [comment]
No worries, i wish i had more time to answer everyone.
Open a private ticket on my Discord server even if it's not a payment issue and kindly attach this issue report link so staff knows what's about.

Thanks

**Comment by LoneDev6** [comment]
Some of your armors are missing layer_2.
Use a blank 64x32 image or actually create the layer_2 image for these armors.

I copied the first layer_2 to each other armor in order to test this out and it works fine.
```yml
armors_rendering:
  my_armor:
    color: "#d60000"
    layer_1: kraken_set
    layer_2: kraken_set_2
    use_color: false
  my_armor2:
    color: "#ffffff"
    layer_1: king_chestplate
    layer_2: kraken_set_2
    use_color: false
  my_armor3:
    color: "#fffff0"
    layer_1: noel_set
    layer_2: kraken_set_2
    use_color: false
```
![image](https://user-images.githubusercontent.com/27242001/207659870-8eeb93a2-8b9b-4f8b-8f03-70e4f672f0ed.png)
