### ISSUE TITLE
Thirst Bar Bug

### ISSUE THREAD

**Issue by rageyh** [PluginBugs/Issues-ItemsAdder#2183]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

! zRageyh_ ®#2284

### What happened?

I can't create thirst bar

![image](https://user-images.githubusercontent.com/48997749/208146959-57e9c99b-1504-4110-8576-060c250933ed.png)
![image](https://user-images.githubusercontent.com/48997749/208146977-37c034bd-3cd9-48a6-a951-5c584691bb9e.png)
![image](https://user-images.githubusercontent.com/48997749/208146988-df1169f0-2c7b-4b5a-aff2-4b22bb217f92.png)
![image](https://user-images.githubusercontent.com/48997749/208146998-0f9360c3-099e-4de8-9208-9f02a0de3457.png)

### Steps to reproduce the issue

1. Create namespace
2. Create yml files
3. iazip

### Server version

This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.2.3e-2

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.20

### FULL server log

[2022-12-16-4.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10247554/2022-12-16-4.log)

### Error (optional)

```shell
[16:38:35] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mFailed to load positive font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[m
[16:38:35] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mFailed to load half font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[m
[16:38:35] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mFailed to load negative font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[m
[16:38:36] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mInvalid character in namespace 'Equilibratrice' of file: item/Equilibratrice[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mLoaded [0;36;1m577[0;33;1m items[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m188[0;33;1m REAL block IDs[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m28[0;33;1m/[0;36;1m750[0;33;1m REAL_NOTE block IDs[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m63[0;33;1m REAL_TRANSPARENT block IDs[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m127[0;33;1m REAL_WIRE block IDs[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m14[0;33;1m FIRE block IDs[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m291[0;33;1m/[0;36;1m6608[0;33;1m font_images[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded [0;36;1m3[0;33;1m categories[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded successfully in [0;36;1m2393ms[m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url... [m
[16:38:37] [Craft Scheduler Thread - 24 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Pack] Resourcepack URL (self-host): http://127.0.0.1:8163/generated.zip[m
[16:38:38] [Server thread/WARN]: [ItemsAdder] Task #2073 for ItemsAdder v3.3.0 generated an exception
java.lang.NullPointerException: Cannot invoke "ia.m.aJ.getWidth()" because "this.a" is null
	at ia.m.aN.t(SourceFile:188) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.bf.x(SourceFile:106) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.bf.r(SourceFile:92) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.bf.aE(SourceFile:113) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.bg.m(SourceFile:294) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.bg.aK(SourceFile:168) ~[ItemsAdder_3.3.0.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by rageyh** [comment]
Boh lone vedi tu, ho provato con la maggior parte delle versioni se riesci a passarmi un preset già fatto per la sete mi faresti un favore, grazie :)

**Comment by LoneDev6** [comment]
Stai usando una vecchia versione del plugin, aggiorna e non mischiare configurazioni.
Qui ci sono un sacco di esempi ed è presente anche la barra della sete: https://github.com/ItemsAdder/DefaultPack
