### ISSUE TITLE
EntityDamage

### ISSUE THREAD

**Issue by Tylwen** [PluginBugs/Issues-ItemsAdder#2195]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Tylwen#4130

### What happened?

lag server

### Steps to reproduce the issue

I dont know

### Server version

Paper 307 1.19.2

### ItemsAdder Version

3.3.0

### ProtocolLib Version

b608

### LoneLibs Version

1.0.21

### LightAPI Version (optional)

5.3.0

### LibsDisguises Version (optional)

b1144

### Error (optional)

```shell
[14:19:33 ERROR]: Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v3.3.0
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/utilities/DisguiseUtilities
        at ia.m.cI.<init>(SourceFile:85) ~[ItemsAdder_3.3.0.jar:?]
        at ia.m.bQ.a(SourceFile:164) ~[ItemsAdder_3.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at ia.m.jZ.a(SourceFile:64) ~[ItemsAdder_3.3.0.jar:?]
        at ia.m.I.c(SourceFile:2420) ~[ItemsAdder_3.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.utilities.DisguiseUtilities
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
```

**Comment by LoneDev6** [comment]
Check if you are using the latest LibsDisguises.
Free: https://ci.md-5.net/job/LibsDisguises/
Paid: https://www.spigotmc.org/resources/libs-disguises-premium.32453/

Note: LibsDisguises is needed only if you use the old mobs of ItemsAdder, you don't need it if you don't use them.
