### ISSUE TITLE
ItemsAdder randomly triggers Could not pass event NotePlayEvent to ItemsAdder v3.3.0 on an empty testserver.

### ISSUE THREAD

**Issue by ofunny** [PluginBugs/Issues-ItemsAdder#2198]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

ofunny#1337

### What happened?

On my development server I randomly get "Could not pass event NotePlayEvent to ItemsAdder v3.3.0" even if nobody is on the server. 

The only thing related to NotePlayEvents might be a Redstone music installation some Builders made or the custom music disks via ItemsAdder what are fully functional. So I can only guess about the possible cause.

### Steps to reproduce the issue

Not really sure what's triggering it, look above to see my assumptions. 

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.3.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.21

### LightAPI Version (optional)

Not installed, not compatible with 1.19.2

### FULL server log

On request only

### Error (optional)

```shell
[07:40:05 ERROR]: Could not pass event NotePlayEvent to ItemsAdder v3.3.0
java.lang.NullPointerException: Cannot invoke "ia.m.cN.m(org.bukkit.block.Block)" because the return value of "ia.m.I.a(org.bukkit.block.Block)" is null
        at ia.m.I.isCustomBlock(SourceFile:3433) ~[ItemsAdder.jar:?]
        at ia.m.cA.a(SourceFile:99) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callNotePlayEvent(CraftEventFactory.java:1442) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.world.level.block.NoteBlock.triggerEvent(NoteBlock.java:102) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969) ~[?:?]
        at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1811) ~[?:?]
        at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1797) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:690) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, but I'll try to find a solution.

**Comment by ofunny** [comment]
I will try to trigger it this weekend so maybe I can figure out the cause, if yes, I'll let you know. Thanks so far.

**Comment by LoneDev6** [comment]
Any news?

**Comment by ofunny** [comment]
Hmm this happens on my development server where no custom block generation is activated and hardly new chunks will be generated since people work a lot in the same area, but also a lot with Fawe (https://www.spigotmc.org/resources/fastasyncworldedit.13932/), I could not find any corrupted region folders within the world directories and there are multiple worlds loading via Mutliverse – I try to check all logs again as far as I still have a copy (dev server is restarted more often).
