### ISSUE TITLE
LifeCore

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2203]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

DinoBoss#6985

### What happened?

I don't know how the error occurred, I only know that it happens when data is saved automatically the lifecore.

### Steps to reproduce the issue

I repeat I wouldn't know, I only know that LifeCore starts to do automatic saves and the AI error came up.

### Server version

[17:55:41 INFO]: Checking version, please wait...
[17:55:41 INFO]: Current: git-Purpur-1876 (MC: 1.19.3)*
* You are running the latest version

### ItemsAdder Version

[17:56:04 INFO]: Use /plugins to get a list of plugins.
[17:56:06 INFO]: ItemsAdder version 3.3.0b
[17:56:06 INFO]: Customized Minecraft without client mods!
[17:56:06 INFO]: Website: devs.beer
[17:56:06 INFO]: Author: LoneDev

### ProtocolLib Version

[17:56:23 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[17:56:23 INFO]: Provides read/write access to the Minecraft protocol.
[17:56:23 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:56:37 INFO]: LoneLibs version 1.0.22
[17:56:37 INFO]: Collection of libs used by my plugins
[17:56:37 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

null

### LibsDisguises Version (optional)

null

### FULL server log

https://mclo.gs/INWKaRQ

### Error (optional)

```shell
[17:48:47 ERROR]: [ItemsAdder] Unexpected I/O error while handling webserver request: 
[17:48:47 WARN]: java.net.SocketException: Connection reset
[17:48:47 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[17:48:47 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[17:48:47 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[17:48:47 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[17:48:47 WARN]:        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[17:48:47 WARN]:        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[17:48:47 WARN]:        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[17:48:47 WARN]:        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[17:48:47 WARN]:        at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
[17:48:47 WARN]:        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[17:48:47 WARN]:        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[17:48:47 WARN]:        at ItemsAdder_3.3.0b.jar//ia.m.iD.run(SourceFile:40)
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Captura de pantalla (242)](https://user-images.githubusercontent.com/58078116/209244964-c57a4d73-80ba-418b-9978-0694744d8b84.png)

**Comment by dinobossytnew** [comment]
[error](https://mclo.gs/0xcMphA)

It comes out when I compress and it is not that the file does not exist in the folder but it is not compressed by the plugin.

**Comment by dinobossytnew** [comment]
![Captura de pantalla (244)](https://user-images.githubusercontent.com/58078116/209254860-206305a6-418d-4b2d-92b3-9cab0c3c79b2.png)

**Comment by LoneDev6** [comment]
> [17:48:47 ERROR]: [ItemsAdder] Unexpected I/O error while handling webserver request: 
[17:48:47 WARN]: java.net.SocketException: Connection reset

This is because somehow pack connection failed.
Maybe the pack port is closed or your host is somehow blocking connection in some cases.

And please next time avoid reporting multiple issues in the same Github page.
