### ISSUE TITLE
Mystic Mobs 5.2.1 Not Compatible

### ISSUE THREAD

**Issue by editon96** [PluginBugs/Issues-ItemsAdder#2215]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

editon#9622

### What happened?

The Iteam Adder Version 3.3.0b-r2 dont hook into Mystic Mobs Version 5.2.1

```
Massage: [14:26:08] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.3.0b-r2
[14:26:08] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m
[0;36;1m  ___  ___        __        __   __   ___  __  [0;32;22m    ItemsAdder[0;37;22m 3.3.0b-r2
[0;36;1m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [0;32;22m    LoneLibs[0;37;22m 1.0.22
[0;36;1m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [0;30;1m    Purpur git-Purpur-1876 (MC: 1.19.3)
[Server thread/ERROR]: [ItemsAdder] [m[0;31;1mFailed to hook into MythicMobs. Please update to Mythicmobs 5.0.1 or greather.[m
```

I want that you now that so here we are. 
I test my Plugins I use too see what are 1.19.3 Compatible and what not.

### Steps to reproduce the issue

1. Go to Mystic Mobs Website and Download the newest Mysticmobs Version 5.2.1
2. Go to Iteam Adder and load the newest Version 3.3.0b-r2
3. Go to Minecraft Pupur Server Software and download the newest 1.19.3 Build
4. Start the Server under 1.19.3 Purpur put the Plugins in the Folder with the depadence MysticLib and LoneLib the newest Versions
5. Volla finshed

### Server version

Purpur git-Purpur-1876 (MC: 1.19.3)

### ItemsAdder Version

Iteam Adder 3.3.0b-r2

### ProtocolLib Version

Protocol Lib Devbuild Build #608

### LoneLibs Version

1.0.22 Lonelibs

### Screenshots/Videos (you can drag and drop files or paste links)

https://mclo.gs/jKBKnOF

**Comment by LoneDev6** [comment]
They probably updated something, I'll do some tests

**Comment by LoneDev6** [comment]
Your Mythicmobs copy has some issues. Contact their support.
It has nothing to do with ItemsAdder.
ItemsAdder just reports you that it failed to hook into MythicMobs. The reason is because the plugin MythicMobs is not loaded correctly.
![image](https://user-images.githubusercontent.com/27242001/211029507-79f7a3ba-6ed7-4e94-98e6-a7c4f192f99f.png)

```
[14:25:58] [Server thread/ERROR]: Error occurred while enabling MythicMobs v5.2.1-SNAPSHOT-5399bfba (Is it up to date?)
--
1750 | java.lang.RuntimeException: Unknown exception loading version handler. Volatile code has been disabled.
1751 | at io.lumine.mythic.bukkit.MythicBukkit.getVolatileCodeHandler(MythicBukkit.java:313) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1752 | at io.lumine.mythic.bukkit.MythicBukkit.enable(MythicBukkit.java:148) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1753 | at io.lumine.mythic.bukkit.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java:84) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1754 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
1755 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
1756 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
1757 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1876]
1758 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1876]
1759 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1876]
1760 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1876]
1761 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1876]
1762 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1876]
1763 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
1764 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
1765 | Caused by: java.lang.reflect.InvocationTargetException
1766 | at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?]
1767 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
1768 | at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
1769 | at io.lumine.mythic.bukkit.MythicBukkit.getVolatileCodeHandler(MythicBukkit.java:306) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1770 | ... 13 more
1771 | Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/inventory/CraftItemStack
1772 | at io.lumine.mythic.core.volatilecode.v1_19_R1_2.VolatileItemHandlerImpl.<init>(VolatileItemHandlerImpl.java:33) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1773 | at io.lumine.mythic.core.volatilecode.VolatileCodeEnabled_v1_19_R1_2.<init>(VolatileCodeEnabled_v1_19_R1_2.java:42) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1774 | at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
1775 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
1776 | at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
1777 | at io.lumine.mythic.bukkit.MythicBukkit.getVolatileCodeHandler(MythicBukkit.java:306) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1778 | ... 13 more
1779 | Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack
1780 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
1781 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
1782 | at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
1783 | at io.lumine.mythic.core.volatilecode.v1_19_R1_2.VolatileItemHandlerImpl.<init>(VolatileItemHandlerImpl.java:33) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1784 | at io.lumine.mythic.core.volatilecode.VolatileCodeEnabled_v1_19_R1_2.<init>(VolatileCodeEnabled_v1_19_R1_2.java:42) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1785 | at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
1786 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
1787 | at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
1788 | at io.lumine.mythic.bukkit.MythicBukkit.getVolatileCodeHandler(MythicBukkit.java:306) ~[MythicMobs-5.2.1-SNAPSHOT.jar:?]
1789 | ... 13 more
```
