### ISSUE TITLE
Can't get items in iagui in latest version.

### ISSUE THREAD

**Issue by CactusMikaz** [PluginBugs/Issues-ItemsAdder#2221]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Marcus#4607

### What happened?

like the title said.
![image](https://user-images.githubusercontent.com/64403069/209817525-2d01beb4-e53b-4043-91a0-2b594b3a41c4.png)

Normally it should open a gui which I can click a button on mid-bottom to get the item. 

### Steps to reproduce the issue

1. use `ia` command to open IA's catagories UI.
2. click on any catagory.
3. click on any item.

### Server version

spigot 1.17.1

### ItemsAdder Version

ItemsAdder 3.3.0b-r2

### ProtocolLib Version

ProtocoLib 4.8.0

### LoneLibs Version

Lonelib 1.0.22

### LibsDisguises Version (optional)

LightAPI 5.2.0

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10314398/latest.log)

### Error (optional)

```shell
[21:18:26] [Server thread/INFO]: Cactus_Mikaz issued server command: /ia
[21:18:28] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.22
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2427) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "this.h" is null
        at ia.m.hI.a(SourceFile:109) ~[?:?]
        at ia.m.hH.a(SourceFile:208) ~[?:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[?:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        ... 18 more
```

**Comment by LoneDev6** [comment]
I'll try to reproduce the issue, please share your custom GUI configuration `.yml` file.
