### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by yusunai** [PluginBugs/Issues-ItemsAdder#2242]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Whenever a player joins and is in any gamemode except spectator, the console gets spammed

### Steps to reproduce the issue

Join server and have the game loaded and be ingame.

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-388 (MC: 1.18.2)
* You are running the latest version

### ItemsAdder Version

Itemsadder version 3.3.0b-r2

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.22V

### LightAPI Version (optional)

LightApi version bukkit-5.2.0

### LibsDisguises Version (optional)

LibsDisguises version 10.0.31-SNAPSHOT

### Error (optional)

```shell
[00:00:00] [Server thread/WARN]: [ItemsAdder] Task #1149 for ItemsAdder v3.3.0b-r2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6
	at ia.m.aO.p(SourceFile:34) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bf.r(SourceFile:89) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bf.aE(SourceFile:113) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bg.m(SourceFile:294) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bg.aK(SourceFile:168) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:00:01] [Server thread/WARN]: [ItemsAdder] Task #1149 for ItemsAdder v3.3.0b-r2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6
	at ia.m.aO.p(SourceFile:34) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bf.r(SourceFile:89) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bf.aE(SourceFile:113) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bg.m(SourceFile:294) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at ia.m.bg.aK(SourceFile:168) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
It's something wrong about huds.
Did some of your huds failed to load?
Check your complete log.

**Comment by LoneDev6** [comment]
Seems one of your huds has a wrong amount of frames compared to the max value.
So it goes outside.

Your hud has 6 images but it should have 10.
