### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by pandarua** [PluginBugs/Issues-ItemsAdder#2249]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

find warn when the server start.
[16:34:19] [Server thread/WARN]: [ItemsAdder] Task #147 for ItemsAdder v3.3.0b-r2 generated an exceptionjava.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap	at ia.nms.aX.impl.v1_17_R1.cf(SourceFile:245) ~[?:?]	at ia.m.eQ.by(SourceFile:22) ~[?:?]	at ia.m.I.a(SourceFile:2409) ~[?:?]	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at java.lang.Thread.run(Thread.java:833) [?:?]Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]	... 11 more

and i can't get anything in ia menu.
error report next

[16:41:06] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.22org.bukkit.event.EventException: null	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2427) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	at java.lang.Thread.run(Thread.java:833) [?:?]Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "this.h" is null	at ia.m.hI.a(SourceFile:109) ~[?:?]	at ia.m.hH.a(SourceFile:208) ~[?:?]	at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[?:?]	at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[?:?]	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]	... 18 more

### Steps to reproduce the issue

none

### Server version

1.17.1

### ItemsAdder Version

3.3.0b-r2 

### ProtocolLib Version

4.8.1

### LoneLibs Version

1.0.22 

### LightAPI Version (optional)

5.3.0

**Comment by LoneDev6** [comment]
Please avoid pasting text like that.
Paste it with the correct indentation of it's original console text.

Anyway you might need to update Spigot/Paper.
There is no way for me to identify which build you are using since you didn't specify it and didn't attach any log.
