### ISSUE TITLE
Invalid character in folders/name of file:

### ISSUE THREAD

**Issue by Clarence21Clarence21** [PluginBugs/Issues-ItemsAdder#2252]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Clarence21#4211

### What happened?

I have been trying to iazip and merge a regular minecraft resourcepack that changes the vanilla textures of vanilla blocks, with the custom items and their custom appearances+properties. After following the instructions on how to merge them properly by doing iazip after moving the assets to folder:
ItemsAdder, content, conquest, resourcepack, assets (assests came from the conquest resource pack folder). I get an error for every block that is in the non custom items adder texture pack (the one that only changes the vinalla blocks appearances).

[15:57:01 ERROR]: [ItemsAdder] Invalid character in folders/name of file: /contents/conquest/resourcepack/assets/betterfoliage/minecraft/textures/blocks/Neuer Ordner/leaves_acacia.png
[15:57:01 ERROR]: [ItemsAdder] Invalid character in folders/name of file: /contents/conquest/resourcepack/assets/betterfoliage/minecraft/textures/blocks/Neuer Ordner/leaves_big_oak.png
[15:57:01 ERROR]: [ItemsAdder] Invalid character in folders/name of file: /contents/conquest/resourcepack/assets/betterfoliage/minecraft/textures/blocks/Neuer Ordner/leaves_birch.png

The error comes up 1000+ plus times. After that I noticed that the output folder genrated.zip got bigger by 123,000KB but I hosted the new generated.zip folder and the textures did not change and where just the regular minecraft blocks. 

Upon entering the game and hitting yes to download the rp it stated

[15:48:30 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (external-host). Url: https://www.dropbox.com/s/uu9vliy8xbmjmmw/generated.zip?raw=1
[15:48:30 WARN]: [ItemsAdder] Warning: null checksum. Make sure to run /iazip command to generate the resourcepack!
[15:48:46 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.3.0b-r2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1339) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

 

### Steps to reproduce the issue

1. Download a minecraft resourcepack like conquest 
2. Follow the merge instructions by making the ItemsAdder content conquest resourcepack folder and copy the assets from conquest too the resourcepack folder
3. log in and do /iazip
4. Recieve 1000+ errors that look like this:

Invalid character in folders/name of file: /contents/conquest/resourcepack/assets/betterfoliage/minecraft/textures/blocks/Neuer Ordner/leaves_birch.png

6. Take the new and larger output folder and dropbox host it (I use dropbox because it is the only hosting that worked for me and other players)\
7. Hit yes to load the new texture 
8. See that no changes to textures have been made after loading with the error:
 
[15:48:30 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (external-host). Url: https://www.dropbox.com/s/uu9vliy8xbmjmmw/generated.zip?raw=1
[15:48:30 WARN]: [ItemsAdder] Warning: null checksum. Make sure to run /iazip command to generate the resourcepack!
[15:48:46 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.3.0b-r2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1339) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c

### Server version

Server version
Spigot 1.15.2

"This server is running CraftBukkit version git-Spigot-a99063f-8731c97 (MC 1.15.2) (Implementing API Version 1.15.2-R0.1-Snapshot)

### ItemsAdder Version

ItemsAdder Version
version 3.3.0b-r2

### ProtocolLib Version

ProtocolLib Version
version 4.8.0

### LoneLibs Version

LoneLibs Version
version 1.0.22

### LightAPI Version (optional)

LightAPI Version (optional)
version bukkit-5.3.0 (build SNAPSHOT)

### FULL server log

[fullserverlog1192023.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10377946/fullserverlog1192023.txt)

**Comment by LoneDev6** [comment]
>  Invalid character in folders/name of file: /contents/conquest/resourcepack/assets/betterfoliage/minecraft/textures/blocks/Neuer Ordner/leaves_birch.png

`Neuer Ordner` is an invalid folder name.
Please don't ignore logs.

Do not use spaces and uppercase characters.
A valid name could be: `neuer_ordner`.
