### ISSUE TITLE
The bug only occurs on my server, The personal computer is OK

### ISSUE THREAD

**Issue by StarYunmeng** [PluginBugs/Issues-ItemsAdder#2259]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

星云梦#3767

### What happened?

Enter /iazip progress bar to stop at 100%, and error reason "<local2>" is null appears in the background
This problem has never occurred on my computer, which makes me very distressed

### Steps to reproduce the issue

This is how the plugin is installed

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Paper-280 (MC: 1.19.2)

### ItemsAdder Version

 ItemsAdder version 3.3.0b-r3

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
`> iazip
[08:48:06 INFO]: [ItemsAdder] [Host] Stopped self-host webserver on port: 7102
[08:48:06 INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 7102
[08:48:06 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[08:48:06 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[08:48:06 INFO]: [ItemsAdder] Loaded 7 items
[08:48:06 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[08:48:06 INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[08:48:06 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[08:48:06 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[08:48:06 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[08:48:06 INFO]: [ItemsAdder] Used 6/6608 font_images
[08:48:06 INFO]: [ItemsAdder] [Init] Loaded 1 categories
[08:48:06 INFO]: [ItemsAdder] [Init] Loaded successfully in 86ms
[08:48:06 INFO]: [ItemsAdder]
[08:48:06 INFO]: [ItemsAdder]
[08:48:06 INFO]: [ItemsAdder] [Pack] Started generation
[08:48:06 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[08:48:06 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[08:48:06 INFO]: [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
[08:48:07 INFO]: [ItemsAdder]
[08:48:07 INFO]: [ItemsAdder] [Pack] Generated resourcepack
[08:48:07 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[08:48:07 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/minecraft/animations/player.iaentitymodel
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/font/gui.json
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/anvil_repair.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/blank_menu.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/cooking.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/crafting.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/no_craft_permission_notification.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/no_recipe.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/gui/smithing.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_arrow_chest.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_back_orange.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_cancel.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_left_blue.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_next_orange.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_right_blue.png
[08:48:07 ERROR]: [ItemsAdder] Invalid character in folders/name of file: D:/plugins/ItemsAdder/contents/_iainternal/resourcepack/assets/_iainternal/textures/icons/icon_search.png
[08:48:07 INFO]: [ItemsAdder]
[08:48:07 INFO]: [ItemsAdder]
[08:48:07 WARN]: [ItemsAdder] Plugin ItemsAdder v3.3.0b-r3 generated an exception while executing task 26606
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "<local2>" is null
        at ia.m.js.d(SourceFile:625) ~ItemsAdder_3.3.0b-r3.jar:?]
        at ia.m.hT.I(SourceFile:238) ~ItemsAdder_3.3.0b-r3.jar:?]
        at ia.m.iu.ai(SourceFile:79) ~ItemsAdder_3.3.0b-r3.jar:?]
        at ia.m.I.a(SourceFile:2652) ~ItemsAdder_3.3.0b-r3.jar:?]
        at ia.m.hT.a(SourceFile:431) ~ItemsAdder_3.3.0b-r3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]`
```

### Other files, you can drag and drop them here to upload. (optional)

[ItemsAdder.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10397416/ItemsAdder.zip)

**Comment by StarYunmeng** [comment]
The problem seems to only appear in 1.19.2. My personal computer uses 1.19.3

**Comment by LoneDev6** [comment]
It probably is a 1.19.2 bug, please update to 1.19.3.
I suggest Paper.
https://papermc.io/

Or make sure you are running the SAME 1.19.2 jar on both servers.

**Comment by StarYunmeng** [comment]
After testing, the same version and plug-in on my PC do not have the same problem

**Comment by LoneDev6** [comment]
> It might also be possible that you have bad files permissions. Make sure to set files permission `777` recursively on `ItemsAdder` folder.

**Comment by StarYunmeng** [comment]
The problem has been solved, which seems to be caused by the update of the latest ProtocolLib

**Comment by LoneDev6** [comment]
Amazing!
I'm very happy that you found the cause of the issue.
I sadly don't have much control over other plugins but only on my plugin.

I hope you will consider leaving a 5 stars review on Spigot, it will help me so much for the next update.
https://www.spigotmc.org/resources/73355/
