### ISSUE TITLE
BungeePackFix Error

### ISSUE THREAD

**Issue by Saharo4eks** [PluginBugs/Issues-ItemsAdder#2268]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Zopka))0)#2628

### What happened?

I downloaded the latest version of the BungeePackFix plugin and it started with an error, and then turned off. The old version works without problems.

### Steps to reproduce the issue

1. Download BungeePackFix 1.1.0-r2 - BETA
2. Start server

### Server version

WaterFall 1.19.3

### ItemsAdder Version

-

### ProtocolLib Version

-

### LoneLibs Version

-

### LightAPI Version (optional)

-

### LibsDisguises Version (optional)

-

### FULL server log

container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
Digest: sha256:ba880156e2489988f637d10860388201a9b003e46b68e53767c0158d354b94a3 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -jar BungeeCord.jar
[15:55:39 INFO]: InsaneProxy > Compression > Checking if libdeflate is available...
[15:55:39 INFO]: InsaneProxy > Compression > libdeflate is available, now using it to compress packets!
[15:55:39 INFO]: Using mbed TLS based native cipher.
[15:55:39 INFO]: InsaneProxy > Compression > Checking if libdeflate is available...
[15:55:39 INFO]: InsaneProxy > Compression > libdeflate is available, now using it to compress packets!
[15:55:39 INFO]: Using zlib based native compressor.
[15:55:39 INFO]: Enabled InsaneProxy version 3.0.6-CR4ZY
[15:55:39 INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[15:55:39 INFO]: Epoll is working, utilising it!
[15:55:39 WARN]: Couldn't detect bungee version. Custom build?
[15:55:39 INFO]: Loaded plugin MiniMOTD version 2.0.10 by jmp
[15:55:39 INFO]: Loaded plugin HubUtils version 2.0-${build.number} by roblabla,Cshark
[15:55:39 INFO]: Loaded plugin SkinsRestorer version 14.2.6 by knat, AlexProgrammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[15:55:39 INFO]: Loaded plugin BungeePackFix version 1.1.0-r2 by LoneDev
[15:55:40 WARN]: Forced host server pvp is not defined
[15:55:40 INFO]: InsaneProxy > ------------------------------------------------------------------
[15:55:40 INFO]: InsaneProxy > 
[15:55:40 INFO]: InsaneProxy > ██╗███╗   ██╗███████╗ █████╗ ███╗   ██╗███████╗██████╗ ██████╗  ██████╗ ██╗  ██╗██╗   ██╗
[15:55:40 INFO]: InsaneProxy > ██║████╗  ██║██╔════╝██╔══██╗████╗  ██║██╔════╝██╔══██╗██╔══██╗██╔═══██╗╚██╗██╔╝╚██╗ ██╔╝
[15:55:40 INFO]: InsaneProxy > ██║██╔██╗ ██║███████╗███████║██╔██╗ ██║█████╗  ██████╔╝██████╔╝██║   ██║ ╚███╔╝  ╚████╔╝ 
[15:55:40 INFO]: InsaneProxy > ██║██║╚██╗██║╚════██║██╔══██║██║╚██╗██║██╔══╝  ██╔═══╝ ██╔══██╗██║   ██║ ██╔██╗   ╚██╔╝  
[15:55:40 INFO]: InsaneProxy > ██║██║ ╚████║███████║██║  ██║██║ ╚████║███████╗██║     ██║  ██║╚██████╔╝██╔╝ ██╗   ██║   
[15:55:40 INFO]: InsaneProxy > ╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   
[15:55:40 INFO]: InsaneProxy > 
[15:55:40 INFO]: InsaneProxy > ------------------------------------------------------------------
[15:55:40 INFO]: InsaneProxy > Loading InsaneProxy 3.0.6-CR4ZY
[15:55:40 INFO]: InsaneProxy > 
[15:55:40 INFO]: InsaneProxy > If you have any issue, please contact me on Discord:
[15:55:40 INFO]: InsaneProxy > https://discord.insaneprojects.club
[15:55:40 INFO]: InsaneProxy > ------------------------------------------------------------------
[15:55:40 INFO]: Thanks for buying InsaneProxy.
[15:55:40 INFO]: If you're using a leaked version
[15:55:40 INFO]: consider buying a license if you
[15:55:40 INFO]: like InsaneProxy, that helps me to
[15:55:40 INFO]: keep developing this.
[15:55:40 INFO]: Also, if you're a leaker, don't remove this message.
[15:55:40 INFO]: ~ gatogamer
[15:55:40 INFO]: InsaneProxy > ------------------------------------------------------------------
[15:55:40 INFO]: InsaneProxy > Looks you're not using root user and you have linux commands module
[15:55:40 INFO]: InsaneProxy > enabled, it can cause a lot of problems, please run InsaneProxy
[15:55:40 INFO]: InsaneProxy > under root, or disable that module. Arigato! n.n
[15:55:40 INFO]: InsaneProxy > ------------------------------------------------------------------
[15:55:40 INFO]: InsaneProxy > InsaneProxy is now using FastConnections, mode is 3
[15:55:40 INFO]: Enabled plugin MiniMOTD version 2.0.10 by jmp
[15:55:40 INFO]: Enabled plugin HubUtils version 2.0-${build.number} by roblabla,Cshark
[15:55:40 INFO]: Enabled plugin SkinsRestorer version 14.2.6 by knat, AlexProgrammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[15:55:40 ERROR]: java.nio.file.NoSuchFileException: plugins/BungeePackFix/config.yml
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
[15:55:40 ERROR]:       at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newInputStream(Files.java:160)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newBufferedReader(Files.java:2955)
[15:55:40 ERROR]:       at dev.lone.shaded.bungeepackfix.net.skinsrestorer.axiom.AxiomConfiguration.load(AxiomConfiguration.java:48)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.generic.YamlConfig.load(YamlConfig.java:190)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.generic.AbstractSettings.<init>(AbstractSettings.java:39)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.bungee.Settings.<init>(Settings.java:14)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.bungee.Main.onEnable(Main.java:36)
[15:55:40 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:287)
[15:55:40 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:251)
[15:55:40 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:45)
[15:55:40 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[15:55:40 ERROR] [BungeePackFix]: Disabling plugin.
[15:55:40 INFO]: Enabled plugin BungeePackFix version 1.1.0-r2 by LoneDev
[15:55:41 INFO]: Listening on /0.0.0.0:24555
container@pterodactyl~ Server marked as running...
[15:55:41 INFO]: [SkinsRestorer] ----------------------------------------------
[15:55:41 INFO]: [SkinsRestorer]     +==================+
[15:55:41 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[15:55:41 INFO]: [SkinsRestorer]     +==================+
[15:55:41 INFO]: [SkinsRestorer] ----------------------------------------------
[15:55:41 INFO]: [SkinsRestorer]     Current version: 14.2.6
[15:55:41 INFO]: [SkinsRestorer]     This is the latest version!
[15:55:41 INFO]: [SkinsRestorer] ----------------------------------------------
[15:57:48 INFO]: Command not found
[15:57:53 INFO]: InsaneProxy > We are running InsaneProxy v3.0.6-CR4ZY by gatogamer#6666.

### Error (optional)

```shell
[15:55:40 ERROR]: java.nio.file.NoSuchFileException: plugins/BungeePackFix/config.yml
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[15:55:40 ERROR]:       at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
[15:55:40 ERROR]:       at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newInputStream(Files.java:160)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
[15:55:40 ERROR]:       at java.base/java.nio.file.Files.newBufferedReader(Files.java:2955)
[15:55:40 ERROR]:       at dev.lone.shaded.bungeepackfix.net.skinsrestorer.axiom.AxiomConfiguration.load(AxiomConfiguration.java:48)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.generic.YamlConfig.load(YamlConfig.java:190)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.generic.AbstractSettings.<init>(AbstractSettings.java:39)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.bungee.Settings.<init>(Settings.java:14)
[15:55:40 ERROR]:       at dev.lone.bungeepackfix.bungee.Main.onEnable(Main.java:36)
[15:55:40 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:287)
[15:55:40 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:251)
[15:55:40 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:45)
[15:55:40 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[15:55:40 ERROR] [BungeePackFix]: Disabling plugin.
```

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

-

### Screenshots/Videos (you can drag and drop files or paste links)

-

**Comment by dinobossytnew** [comment]
wtf....

**Comment by LoneDev6** [comment]
Try to create the config.yml file manually.
The error is pretty clear about what is not working.
https://github.com/LoneDev6/BungeePackFix/blob/main/src/main/resources/config.yml

I'll post an update today, thanks.
Anyway next time use the correct repository, this is not the repository of BungeePackFix.

**Comment by LoneDev6** [comment]
Update: https://www.spigotmc.org/resources/%E2%9A%99%EF%B8%8Fbungeepackfix.96794/
