### ISSUE TITLE
A WARN on Arclight

### ISSUE THREAD

**Issue by Sam-Chai** [PluginBugs/Issues-ItemsAdder#2276]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Sam_Chai#4677

### What happened?

When the server started (After "type /help for help"), the ia reports me a WARN message

### Steps to reproduce the issue

just started the server then crash this

### Server version

This server is running Arclight version arclight-1.18.2-1.0.7-40114eb5 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder_3.3.0b-r5

### ProtocolLib Version

 ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
[20:03:34 WARN] [ItemsAdder]: Task #37 for ItemsAdder v3.3.0b-r5 generated an exception
java.lang.ClassCastException: class java.util.HashMap cannot be cast to class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap (java.util.HashMap is in module java.base of loader 'bootstrap'; it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.6 of loader 'MC-BOOTSTRAP' @1e730495)
        at ia.nms.aX.impl.v1_18_R2.cf(SourceFile:323) ~[?:?]
        at ia.m.eQ.by(SourceFile:22) ~[?:?]
        at ia.m.I.a(SourceFile:2401) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2370!/:arclight-1.18.2-1.0.7-40114eb5]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2370!/:arclight-1.18.2-1.0.7-40114eb5]
        at net.minecraft.server.MinecraftServer.handler$zng000$arclight$runScheduler(MinecraftServerMixin.java:2381) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by LoneDev6** [comment]
Arclight is a custom unofficial fork of Spigot, I have no idea of what trickery they are doing in their code so I cannot do anything about that.
Ask its developers to read this page and contact me there, we might find a solution.
