### ISSUE TITLE
Could not pass event PlayerInteractEvent to ItemsAdder

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2295]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cats#0935

### What happened?

Custom Leaves (chorus berries), real_note based blocks are a bug
There is an overall twisted error after outputting the corresponding console log.

### Steps to reproduce the issue

Well, that's what happens when you interact after you appear on the console log. Or it turns itself into a note block.

### ItemsAdder Version

3.3.0b-r5 (r4->r5 update ok) 

### ProtocolLib Version

612

### LoneLibs Version

1.0.23

### Error (optional)

```shell
[00:28:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
[00:28:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
[00:28:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
[00:28:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
[00:28:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
[00:28:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r4
java.lang.NullPointerException: null
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-01-26_02 42 43](https://user-images.githubusercontent.com/87476958/214680308-4f5bbe8f-366b-4d90-98e4-a334167240b8.png)

**Comment by LoneDev6** [comment]
Post the whole log, this is only a part of the error.

**Comment by cats-love** [comment]
[09:11:01] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: Cannot invoke "ia.m.en.i(org.bukkit.Location)" because "<local5>" is null
	at ia.m.bZ.g(SourceFile:226) ~[ItemsAdder_3.3.0b-r5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1459.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:526) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1970) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:11:01] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: Cannot invoke "ia.m.en.i(org.bukkit.Location)" because "<local5>" is null
	at ia.m.bZ.g(SourceFile:226) ~[ItemsAdder_3.3.0b-r5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1459.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:526) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1970) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:11:02] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: Cannot invoke "ia.m.en.i(org.bukkit.Location)" because "<local5>" is null
	at ia.m.bZ.g(SourceFile:226) ~[ItemsAdder_3.3.0b-r5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1459.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:526) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1970) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:11:05] [Server thread/INFO]: d3namuni issued server command: /stats
[09:11:06] [Votifier NIO worker/INFO]: [Votifier] Got a protocol v1 vote record from /34.64.81.132:49880 -> Vote (from:MineList.kr username:junghwa1101 address:14.34.225.111 timeStamp:Thu Feb 16 2023 00:11:07 GMT+0000 (Coordinated Universal Time) additionalData:null)
[09:11:06] [Server thread/INFO]: [VotingPlugin] Received a vote from service site 'MineList.kr' by player 'junghwa1101'!
[09:11:06] [Timer-2/INFO]: [추천] junghwa1101 님이 마인리스트로 서버를 추천하셨습니다! (/추천)
[09:11:07] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
[09:11:08] [Server thread/INFO]: casa1230 issued server command: /cmi baltop casa1230 2
[09:11:08] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
[09:11:08] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
[09:11:09] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
[09:11:09] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
[09:11:10] [Server thread/INFO]: dfgvd issued server command: /shop
[09:11:10] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.0b-r5
java.lang.NullPointerException: null
