### ISSUE TITLE
all ItemsAdder Block does not break

### ISSUE THREAD

**Issue by Eccessiv0** [PluginBugs/Issues-ItemsAdder#2296]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ecc3ssivo#9571

### What happened?

All blocks can only be destroyed by the command: "/killall named" 

### Steps to reproduce the issue

1. the block does not break and there is no error

### Server version

This server is running Paper version git-Paper-787 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 7 version(s) behind
Previous version: git-Paper-790 (MC: 1.16.5)

### ItemsAdder Version

ItemsAdder  version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

```
OreRegenerator] Enabling OreRegenerator v1.2.22
[23:25:19] [Server thread/INFO]: [OreRegenerator] Creating managers...
[23:25:19] [Server thread/INFO]: [OreRegenerator] Unable to find a valid material named: glowing_redstone_ore
[23:25:19] [Server thread/INFO]: [OreRegenerator] Unable to find a valid material named: glowing_redstone_ore
[23:25:19] [Server thread/INFO]: [OreRegenerator] Adding override: example-region
[23:25:19] [Server thread/INFO]: [OreRegenerator] Finished creating managers!
[23:25:19] [Server thread/INFO]: [OreRegenerator] Registering events...
[23:25:19] [Server thread/INFO]: [OreRegenerator] Finished registering events!
[23:25:19] [Server thread/INFO]: [OreRegenerator] Registering commands...
[23:25:19] [Server thread/INFO]: [OreRegenerator] [ACF] Enabled Asynchronous Tab Completion Support!
[23:25:19] [Server thread/INFO]: [OreRegenerator] Finished registering commands!
[23:25:19] [Server thread/INFO]: [OreRegenerator] Registering hooks...
[23:25:19] [Server thread/INFO]: [OreRegenerator] Worldguard support: true
[23:25:19] [Server thread/INFO]: [OreRegenerator] Lands support: false
[23:25:19] [Server thread/INFO]: [OreRegenerator] Towny support: false
[23:25:19] [Server thread/INFO]: [OreRegenerator] Finished registering hooks!
[23:25:19] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.3.0b-r5
[23:25:19] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R3! Trying to find NMS support
[23:25:19] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_16_R3' loaded!
[23:25:19] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[23:25:19] [Server thread/WARN]: [ItemsAdder] [m[0;33;1mCustom player emotes require Minecraft 1.17+. Feature disabled.[m
[23:25:19] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m
[0;36;1m  ___  ___        __        __   __   ___  __  [0;32;22m    ItemsAdder[0;37;22m 3.3.0b-r5
[0;36;1m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [0;32;22m    LoneLibs[0;37;22m 1.0.22
[0;36;1m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [0;30;1m    Paper git-Paper-787 (MC: 1.16.5)
[0;36;1m                                               [m
[23:25:19] [Server thread/WARN]: [ItemsAdder] [m[0;33;1mCustom player emotes require Minecraft 1.17+. Feature disabled.[m
[23:25:19] [Server thread/INFO]: [ItemsAdder] [mRegistered Citizens NPC Trait: customentity[m
[23:25:19] [Server thread/INFO]: [LockettePro] Enabling LockettePro v2.10.10
[23:25:19] [Server thread/INFO]: [LockettePro] Compatible server version detected: 1.16.5
[23:25:19] [Server thread/INFO]: [LockettePro] ===================================
[23:25:19] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.coreprotect.CoreProtect.getAPI()" because the return value of "net.coreprotect.CoreProtect.getInstance()" is null
[23:25:19] [Server thread/WARN]: 	at me.crafter.mc.lockettepro.Dependency.<init>(Dependency.java:38)
[23:25:19] [Server thread/WARN]: 	at me.crafter.mc.lockettepro.LockettePro.onEnable(LockettePro.java:46)
[23:25:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:25:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[23:25:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[23:25:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[23:25:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[23:25:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[23:25:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[23:25:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[23:25:19] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[23:25:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[23:25:19] [Server thread/INFO]: [QualityArmory] Enabling QualityArmory v2.0.8.2
[23:25:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: qualityarmory [2.0.8.2]
[23:25:19] [Server thread/INFO]: [QualityArmory] Found PlaceholderAPI. Loaded support
[23:25:19] [Server thread/WARN]: [QualityArmory] Invalid material name: LIGHT_GREY_STAINED_GLASS.
[23:25:19] [Server thread/WARN]: [QualityArmory] Invalid material name: LIGHT_GREY_STAINED_GLASS_PANE.
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loaded 11 Ammo types.
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loaded 16 Misc.
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loaded 99 Gun types.
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loading Attachment: glocksilenziata80
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loading Attachment: glocksilenziata30
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loading Attachment: glocksilenziata
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loaded 3 Attachment types.
[23:25:19] [Server thread/INFO]: [QualityArmory] -Loaded 4 Armor types.
[23:25:20] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v21.2
[23:25:20] [Server thread/INFO]: [CoreProtect] CoreProtect ora ? abilitato! 
[23:25:20] [Server thread/INFO]: [CoreProtect] Usando SQLite per la memorizzazione dei dati.
[23:25:20] [Server thread/INFO]: --------------------
[23:25:20] [Server thread/INFO]: [CoreProtect] Divertiti CoreProtect? Unisciti al nostro Discord!
[23:25:20] [Server thread/INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[23:25:20] [Server thread/INFO]: --------------------
[23:25:20] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[23:25:20] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[23:25:20] [Server thread/INFO]: [Geyser-Spigot] 
[23:25:20] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser version 2.1.0-SNAPSHOT (git-master-48d7872)
[23:25:20] [Server thread/INFO]: [Geyser-Spigot] 
[23:25:20] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[23:25:20] [ForkJoinPool.commonPool-worker-7/WARN]: [PlaceholderAPI] Loaded class net.ess3.api.IEssentials from Essentials v2.20.0-dev+5-d891268 which is not a depend, softdepend or loadbefore of this plugin.
[23:25:20] [ForkJoinPool.commonPool-worker-7/WARN]: [PlaceholderAPI] Loaded class org.codemc.worldguardwrapper.WorldGuardWrapper from OreRegenerator v1.2.22 which is not a depend, softdepend or loadbefore of this plugin.
[23:25:23] [Network Listener - #0/INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:25565
[23:25:23] [Server thread/INFO]: [Geyser-Spigot] Done (2.388s)! Run /geyser help for help!
[23:25:23] [Server thread/INFO]: Running delayed init tasks
[23:25:23] [Craft Scheduler Thread - 33/INFO]: [Vault] Checking for Updates ... 
[23:25:23] [Craft Scheduler Thread - 21/INFO]: [Essentials] Caricamento delle informazione sulla versione...
[23:25:23] [Craft Scheduler Thread - 18/INFO]: [PlayerVaults] We didn't find an update!
[23:25:23] [Server thread/WARN]: [FastAsyncWorldEdit] Loaded class com.sk89q.worldguard.protection.association.RegionAssociable from WorldGuard v7.0.5+3827266 which is not a depend, softdepend or loadbefore of this plugin.
[23:25:23] [Server thread/INFO]: [com.fastasyncworldedit.bukkit.regions.WorldGuardFeature] Plugin 'WorldGuard' found. Using it now.
[23:25:23] [Server thread/INFO]: [com.fastasyncworldedit.bukkit.FaweBukkit] Attempting to use plugin 'WorldGuard'
[23:25:23] [Craft Scheduler Thread - 13/INFO]: ---------------------------------
[23:25:23] [Craft Scheduler Thread - 13/INFO]: Validating the license
[23:25:23] [Craft Scheduler Thread - 13/INFO]: for NxtorAH...
[23:25:23] [Craft Scheduler Thread - 13/INFO]: 
[23:25:23] [Craft Scheduler Thread - 13/INFO]: Invalid license!
[23:25:23] [Craft Scheduler Thread - 13/INFO]: Code: 12002
[23:25:23] [Craft Scheduler Thread - 13/INFO]: ---------------------------------
[23:25:23] [Craft Scheduler Thread - 25/INFO]: Il sistema delle licenze e' offline e per questo la licenza e' automaticamente valida.
[23:25:23] [Craft Scheduler Thread - 25/INFO]: ---------------------------------
[23:25:23] [Craft Scheduler Thread - 25/INFO]: Validating the license
[23:25:23] [Craft Scheduler Thread - 25/INFO]: for RPCore...
[23:25:23] [Craft Scheduler Thread - 25/INFO]: 
[23:25:23] [Craft Scheduler Thread - 25/INFO]: Valid license!
[23:25:23] [Craft Scheduler Thread - 25/INFO]: Code: 200
[23:25:23] [Craft Scheduler Thread - 25/INFO]: ---------------------------------
[23:25:23] [Craft Scheduler Thread - 13/INFO]: [NxtorAH] Disabling NxtorAH v1.0
[23:25:23] [Craft Scheduler Thread - 6/INFO]: [InventoryRollbackPlus] Checking for updates...
[23:25:23] [Craft Scheduler Thread - 33/INFO]: [Vault] No new version available
[23:25:23] [Craft Scheduler Thread - 13/INFO]: NxtorAH disabled successfully.
[23:25:23] [Craft Scheduler Thread - 27/INFO]: [ItemsAdder] [m[0;32;1m[License] Spigot product licensed to: [0;36;1mEccessivo (1497630)[m
[23:25:23] [Craft Scheduler Thread - 22/INFO]: [ItemEdit] New Update at https://spigotmc.org/resources/40993
[23:25:23] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.16.4/5 (754)
[23:25:23] [Server thread/WARN]: [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 16.0.1). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[23:25:23] [Craft Scheduler Thread - 6/INFO]: 
===============================================================================
A minor update to InventoryRollbackPlus is available!
Download at https://www.spigotmc.org/resources/inventoryrollbackplus-1-8-1-16-x.85811/
(current: 1.6.7, latest: 1.6.8)
===============================================================================

[23:25:23] [Craft Scheduler Thread - 15/WARN]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mFailed to get release info from api.github.com. 
 If this message is repeated a lot, please see http://skinsrestorer.net/firewall[0;39m
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'bancharelle' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'tim1' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'caramela' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'bosco' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'compra' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'venditore' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'stradina' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'chiesa2' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'S2' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'a' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'nike' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'santanna' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'compratore' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'pizzeria' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Gdf' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'GuardiaCostiera' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'sg' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'governo' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Market' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'magazzini' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'motor' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'tribunale' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'rifornimenti-motor' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'benvenuto' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'giardini' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'tim' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'mc' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'segreteria' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Ospedale' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'inps' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'discoteca' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'condominio' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'vdfaccademia2' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'scuola' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Miniera' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Procur' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'ZonaMilitare' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'BarIkea' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Accademia2' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Ikea' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Ikeaentrata' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'Officina' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'posta' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'prigionee' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'ParkourFinanza' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'ParkourFinanzaInizio' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'chiesa' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'AccMilitari' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'AccMilitari2' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'magazzino' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'vdfaccademia1' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'vdfaccademiaa' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'depex' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'bunkerr' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'ghetto' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'tribunalee' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'libreria' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'accpol' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'mysql' not found, skipping it.
[23:25:23] [Server thread/WARN]: [HolographicDisplays] Hologram 'aushwitz' was in the world 'asd4' but it wasn't loaded.
[23:25:23] [Server thread/INFO]: [PlayerVaults] ** Vaults have already been converted to UUIDs. If this is incorrect, shutdown your server and rename the plugins/PlayerVaults/uuidvaults directory.
[23:25:23] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[23:25:23] [Server thread/INFO]: [BigDoors] Checking for updates...
[23:25:23] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Extracting internal contents from .jar[m
[23:25:23] [Server thread/INFO]: [ItemsAdder] [m[0;32;1m[Pack] DONE extracting internal contents from .jar[m
[23:25:23] [ForkJoinPool.commonPool-worker-11/INFO]: [BigDoors] No new updates available.
[23:25:23] [Server thread/INFO]: [CoreProtect] WorldEdit registrazione con successo inizializzato.
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: localtime [1.2]
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.5.0]
[23:25:23] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.4.30 which is not a depend, softdepend or loadbefore of this plugin.
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms [5.1-R2]
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: essentials [1.4.0]
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [1.8.0]
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: worldguard [1.4.2]
[23:25:23] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.7.0]
[23:25:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bungee [1.0.1]
[23:25:23] [Server thread/INFO]: 8 placeholder hook(s) registered! 6 placeholder hook(s) have an update available.
[23:25:23] [Server thread/WARN]: [Geyser-Spigot] You are using an outdated version of ViaVersion; please download the newest version from https://ci.viaversion.com/job/ViaVersion/
[23:25:24] [Server thread/INFO]: [Citizens] Loaded 25 NPCs.
[23:25:24] [Server thread/INFO]: [HolographicDisplays] Found a new version available: v3.0.0
[23:25:24] [Server thread/INFO]: [HolographicDisplays] Download it on Bukkit Dev:
[23:25:24] [Server thread/INFO]: [HolographicDisplays] dev.bukkit.org/projects/holographic-displays
[23:25:24] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[23:25:24] [Server thread/INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.11.2) is available at:
[23:25:24] [Server thread/INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
[23:25:24] [Server thread/WARN]: [ViaVersion] There is a newer plugin version available: 4.5.1, you're on: 4.2.1
[23:25:24] [Server thread/INFO]: Done (34.242s)! For help, type "help"
[23:25:24] [Server thread/INFO]: Timings Reset
[23:25:24] [Craft Scheduler Thread - 12/INFO]: [Simple Elevators] A new update is available at:
[23:25:24] [Craft Scheduler Thread - 12/INFO]: https://www.spigotmc.org/resources/44462/updates
[23:25:24] [Craft Scheduler Thread - 8/ERROR]: [ItemsAdder] [m[0;31;1mIngredient not found 'COPPER_INGOT' for recipe 'raw_tin_and_copper_ingot_dust'. File: /contents/iasurvival/configs/ores/recipes/recipe_tin.yml[m
[23:25:24] [Craft Scheduler Thread - 8/ERROR]: [ItemsAdder] [m[0;31;1mCave decorators are supported only on Spigot 1.17+.[m
[23:25:24] [Craft Scheduler Thread - 8/ERROR]: [ItemsAdder] [m[0;31;1m[0;31;1mWorld populator [0;33;22mnether_alchemy_ore [0;31;1mfailed to load. No world matched [0;33;22mworld_nether[0;31;1m. Maybe wrong name or it doesn't exists. [0;33;22mFile: /contents/iaalchemy/configs/worlds_populators_1_18.yml[m
[23:25:24] [Craft Scheduler Thread - 8/ERROR]: [ItemsAdder] [m[0;31;1m[0;31;1mWorld populator [0;33;22mend_ore [0;31;1mfailed to load. No world matched [0;33;22mworld_the_end[0;31;1m. Maybe wrong name or it doesn't exists. [0;33;22mFile: /contents/iasurvival/configs/ores/worlds_populators_1_18.yml[m
[23:25:24] [Craft Scheduler Thread - 8/ERROR]: [ItemsAdder] [m[0;31;1m[0;31;1mWorld populator [0;33;22mblaze_powder_ore [0;31;1mfailed to load. No world matched [0;33;22mworld_nether[0;31;1m. Maybe wrong name or it doesn't exists. [0;33;22mFile: /contents/iasurvival/configs/ores/worlds_populators_1_18.yml[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mLoaded [0;36;1m458[0;33;1m items[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m188[0;33;1m REAL block IDs[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m29[0;33;1m/[0;36;1m750[0;33;1m REAL_NOTE block IDs[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m63[0;33;1m REAL_TRANSPARENT block IDs[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m127[0;33;1m REAL_WIRE block IDs[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m14[0;33;1m FIRE block IDs[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m570[0;33;1m/[0;36;1m6608[0;33;1m font_images[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded [0;36;1m35[0;33;1m categories[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded successfully.[m
[23:25:24] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url... [m
[23:25:24] [Craft Scheduler Thread - 21/WARN]: [Essentials] Sei 93 EssentialsX dev build(s) obsoleto!
[23:25:24] [Craft Scheduler Thread - 21/WARN]: [Essentials] Scaricalo qui: https://essentialsx.net/downloads.html
[23:25:24] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:25:24] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:25:25] [Thread-39/INFO]: --------------------
[23:25:25] [Thread-39/INFO]: [CoreProtect] Versione 21.3 adesso ? disponibile.
[23:25:25] [Thread-39/INFO]: [CoreProtect] Scaricamento: www.coreprotect.net/download/
[23:25:25] [Thread-39/INFO]: --------------------
[23:25:25] [Server thread/INFO]: [OreRegenerator] Loaded region.
[23:25:25] [Server thread/INFO]: [OreRegenerator] Loaded region.
[23:25:25] [Server thread/INFO]: [OreRegenerator] Loaded region.
[23:25:25] [Craft Scheduler Thread - 7/INFO]: [Images] Loaded 35 images...
[23:25:26] [Craft Scheduler Thread - 8/INFO]: [ItemsAdder] [m[0;32;1m[Pack] Resourcepack URL is valid (external-host). Url: https://www.dropbox.com/s/hzofdgw732j1kx9/generated.zip?raw=1[m
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/GnYPvbsaOWo

**Comment by LoneDev6** [comment]
Blocks are not entities, I don't know what you mean, you can't kill them using the /killall command.
You meant furniture probably, they are entities.

I don't think there is a way to prevent entities from being killed by custom kill commands of other plugins.
Basically these plugins are completely removing any entity from the server, I doubt there is a way for me to avoid that, the Spigot API doesn't provide any method to block removal by these special commands.

**Comment by Eccessiv0** [comment]
probably I have not explained well, I apologize for my English, the real problem is not the command but are the entities are not destroyed with the left button

**Comment by LoneDev6** [comment]
You probably are trying to remove the entities on a protected area or another plugin is cancelling the damage event for the armorstands/itemframes.

Remove every other plugin and test.
