### ISSUE TITLE
Can't place colored water buckets 1.19.3

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#2329]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Can't place colored water buckets

### Steps to reproduce the issue

Place colored water bucket

### Server version

git-Purpur-1894 (MC: 1.19.3)*

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### LibsDisguises Version (optional)

LibsDisguises version 10.0.32-SNAPSHOT

### FULL server log

[21:11:23 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.3.1
java.lang.ClassCastException: class net.minecraft.core.HolderSet$Named cannot be cast to class net.minecraft.core.Holder (net.minecraft.core.HolderSet$Named and net.minecraft.core.Holder are in unnamed module of loader java.net.URLClassLoader @421faab1)
        at ia.nms.aF.impl.v1_19_R2.a(SourceFile:134) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.bQ.e(SourceFile:266) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.cT.a(SourceFile:145) ~[ItemsAdder_3.3.1.jar:?]
        at ia.m.cT.m(SourceFile:235) ~[ItemsAdder_3.3.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1894]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:530) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2040) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Screenshots/Videos (you can drag and drop files or paste links)

x

**Comment by LoneDev6** [comment]
Will be fixed, thanks.
