### ISSUE TITLE
Conflicts with MyPet Plugin

### ISSUE THREAD

**Issue by TUCAOEVER** [PluginBugs/Issues-ItemsAdder#2334]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

```
[20:05:00 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.ArrayIndexOutOfBoundsException: null
[20:05:00 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@6b5cb846[
    a=<null>
    components={TranslatableComponent(format=%(?:(\d+)\$)?([A-Za-z%]|$), translate=death.attack.player.item, with=[TextComponent{text=TUCAOEVER, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=Dinnerbone, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}])}
    b=CHAT
    c=00000000-0000-0000-0000-000000000000
  ]
```

### Steps to reproduce the issue

I got this when someone attack other player's pet.

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-794 (MC: 1.16.5)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/43756134/218257130-bed43753-1363-47b4-9274-a9341c978d6e.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/43756134/218257142-75ee9ecb-f4f2-4f63-ab32-e1d055d8e903.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/43756134/218257154-3a20879c-cc91-49da-8e07-edfd03c8ab79.png)

### Error (optional)

```shell
[20:05:00 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.ArrayIndexOutOfBoundsException: null
[20:05:00 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@6b5cb846[
    a=<null>
    components={TranslatableComponent(format=%(?:(\d+)\$)?([A-Za-z%]|$), translate=death.attack.player.item, with=[TextComponent{text=TUCAOEVER, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=Dinnerbone, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}])}
    b=CHAT
    c=00000000-0000-0000-0000-000000000000
  ]

[17:59:33 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
        at net.md_5.bungee.api.chat.TranslatableComponent.convert(TranslatableComponent.java:179) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.md_5.bungee.api.chat.TranslatableComponent.toLegacyText(TranslatableComponent.java:148) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.md_5.bungee.api.chat.BaseComponent.toLegacyText(BaseComponent.java:540) ~[patched_1.16.5.jar:git-Purpur-1171]
        at ia.m.gC.a(SourceFile:369) ~[?:?]
        at ia.m.gC.c(SourceFile:264) ~[?:?]
        at ia.m.gC.onPacketSending(SourceFile:249) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2033) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer$1.sendMessage(CraftPlayer.java:2475) ~[patched_1.16.5.jar:git-Purpur-1171]
        at de.Keyle.MyPet.compat.v1_16_R3.PlatformHelper.sendMessageRaw(PlatformHelper.java:247) ~[?:?]
        at de.Keyle.MyPet.listeners.MyPetEntityListener.sendDeathMessage(MyPetEntityListener.java:640) ~[?:?]
        at de.Keyle.MyPet.listeners.MyPetEntityListener.onMyPet(MyPetEntityListener.java:550) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor578.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:862) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1643) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1561) ~[patched_1.16.5.jar:git-Purpur-1171]
        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.die(EntityMyPet.java:698) ~[?:?]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1389) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityInsentient.damageEntity(EntityInsentient.java:347) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1229) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2290) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2546) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:59:33 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@3faa98e0[
    a=<null>
    components={TranslatableComponent(format=%(?:(\d+)\$)?([A-Za-z%]|$), translate=death.attack.player.item, with=[TextComponent{text=再多看一眼一眼就会爆炸, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=shenkong1234567, BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}])}
    b=CHAT
    c=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming version
