### ISSUE TITLE
 BungeePackFix-1.1.0-r3.jar not working  1.19.3

### ISSUE THREAD

**Issue by maxedrom** [PluginBugs/Issues-ItemsAdder#2353]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello, i installed BungeePackFix-1.1.0-r3.jar, but when the server starts, cannot load de pluguin, invalid pluguin.yml

Server Version: Spigot 1.19.3

All LoneDev apps updated to now.

`[00:14:01 ERROR]: Could not load 'plugins/BungeePackFix-1.1.0-r3.jar' in folder 'plugins'

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:179) \~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:157) \~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

    at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) \~[paper-1.19.3.jar:git-Paper-399]

    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) \~[paper-1.19.3.jar:git-Paper-399]

    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) \~[paper-1.19.3.jar:git-Paper-399]

    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) \~[paper-1.19.3.jar:git-Paper-399]

    at java.lang.Thread.run(Thread.java:833) \~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
  ... 7 more`

### Steps to reproduce the issue

1. Upload Pluguin
2. Start Server
3. Error Appear

### Server version

This server is running Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-383 (MC: 1.19.3)

### ItemsAdder Version

 Items Adder 3.3.1

### ProtocolLib Version

ProtocolLib Version: 5.0.0.SNAPSHOT-B612

### LoneLibs Version

Lonelibs version: 1.0.23

### LightAPI Version (optional)

LightApi: 5.3.0

### FULL server log

[05:57:02] [Server thread/ERROR]: Could not load 'plugins/BungeePackFix-1.1.0-r3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:179) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:157) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-399]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/6577300/219972397-8ae283ed-f6b6-4526-a3ce-383a30ed05db.png)

**Comment by LoneDev6** [comment]
This is not a Spigot plugin, it's a bungeecord plugin.
