### ISSUE TITLE
HUD trigger max value bug

### ISSUE THREAD

**Issue by Niinnee** [PluginBugs/Issues-ItemsAdder#2393]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Niinnee#1900

### What happened?

When executing the contents of the trigger, the capacity of the maximum value you set will be infinitely increased. For example, you set 10, but it will become 11, 12, and an error will occur, and the HUD function will be disabled

The minimum does not have this problem

### Steps to reproduce the issue

Font image displays normally, but when the value exceeds 10, it will crash, and will always prompt the value overflow. When the value is less than 0, this error will not occur

### Server version

Current: git-Purpur-1925 (MC: 1.19.3)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

itemsAdder version 3.4.0-beta-r11

### ProtocolLib Version

protocollib version 5.0.0-SNAPSHOT-B614

### LoneLibs Version

LONEDEV version 1.0.23

### FULL server log

[2023-03-06-11.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10899571/2023-03-06-11.log)

### Error (optional)

```shell
[22:55:20] [pool-16-thread-6/ERROR]: Thread pool-16-thread-6 failed main thread check: block remove
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.world.level.block.state.BlockBehaviour.onRemove(BlockBehaviour.java:161) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:1037) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:601) ~[?:?]
	at ia.nms.aI.impl.v1_19_R2.a(SourceFile:61) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.nms.aI.impl.v1_19_R2.K(SourceFile:29) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.cz.f(SourceFile:232) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.cz.a(SourceFile:507) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.cG.b(SourceFile:42) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.cH.a(SourceFile:118) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.cX.a(SourceFile:78) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:55:20] [Server thread/WARN]: [ItemsAdder] Task #101 for ItemsAdder v3.4.0-beta-r11 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
	at ia.m.aP.o(SourceFile:33) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.bk.r(SourceFile:88) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.bk.aI(SourceFile:114) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.bg.m(SourceFile:319) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at ia.m.bg.aG(SourceFile:174) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1925]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: myitem
huds:
   stamina:
    enabled: true
    show:
      auto: true
      creative: false
    type: FRAMES
    x_position_pixels: 10
    direction: LEFT
    value:
      player_stat_name: stamina
      start: 10
      min: 0
      max: 10
      triggers:
        decrement:
          generic_over_time_minutes_inside:
            min_sky_light: 10
            max_sky_light: 15
            every_ticks: 300
            amount: 1
          food_level_change:
            amount: 1
        increment:
          generic_over_time_minutes_inside:
            min_sky_light: 0
            max_sky_light: 9
            every_ticks: 300
            amount: 1
          food_level_change:
            amount: 5
          player_respawn:
            amount: 5
        on_min_value:
          damage_player:
            every_ticks: 100
            damage: 0.5
    images:
      frames:
      - myitem:stamina_hud_1
      - myitem:stamina_hud_2
      - myitem:stamina_hud_3
      - myitem:stamina_hud_4
      - myitem:stamina_hud_5
      - myitem:stamina_hud_6
      - myitem:stamina_hud_7
      - myitem:stamina_hud_8
      - myitem:stamina_hud_9
      - myitem:stamina_hud_10

info:
  namespace: myitem
font_images:
  stamina_hud_1:
    suggest_in_command: false
    path: huds/stamina/stamina1.png
    y_position: 10
  stamina_hud_2:
    suggest_in_command: false
    path: huds/stamina/stamina2.png
    y_position: 15
  stamina_hud_3:
    suggest_in_command: false
    path: huds/stamina/stamina3.png
    y_position: 20
  stamina_hud_4:
    suggest_in_command: false
    path: huds/stamina/stamina4.png
    y_position: 22
  stamina_hud_5:
    suggest_in_command: false
    path: huds/stamina/stamina5.png
    y_position: 23
  stamina_hud_6:
    suggest_in_command: false
    path: huds/stamina/stamina6.png
    y_position: 25
  stamina_hud_7:
    suggest_in_command: false
    path: huds/stamina/stamina7.png
    y_position: 27
  stamina_hud_8:
    suggest_in_command: false
    path: huds/stamina/stamina8.png
    y_position: 30
  stamina_hud_9:
    suggest_in_command: false
    path: huds/stamina/stamina9.png
    y_position: 32
  stamina_hud_10:
    suggest_in_command: false
    path: huds/stamina/stamina10.png
    y_position: 35
```

**Comment by LoneDev6** [comment]
Hello, I'll check this, thanks
