### ISSUE TITLE
java.lang.NoSuchMethodError: 'void net.citizensnpcs.Citizens.storeNPCs(net.citizensnpcs.api.command.CommandContext)'

### ISSUE THREAD

**Issue by sefacoban** [PluginBugs/Issues-ItemsAdder#2411]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

java.lang.NoSuchMethodError: 'void net.citizensnpcs.Citizens.storeNPCs(net.citizensnpcs.api.command.CommandContext)' Error
![image](https://user-images.githubusercontent.com/127690482/224567557-5e77b001-7c41-4da0-aa1e-a631bf4d2067.png)

### Steps to reproduce the issue

Start Sever
Enable itemsadder vaild pack
Error.

### Server version

1.16.5

### ItemsAdder Version

itemsader 3

### ProtocolLib Version

Lasted

### LoneLibs Version

Lasted

### Error (optional)

```shell
java.lang.NoSuchMethodError: 'void net.citizensnpcs.Citizens.storeNPCs(net.citizensnpcs.api.command.CommandContext)'
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.reload(SourceFile:55) ~[?:?]
        at dev.lone.itemsadder.main.bd.a(SourceFile:293) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at dev.lone.itemsadder.main.if.a(SourceFile:41) ~[?:?]
        at dev.lone.itemsadder.main.aA.b(SourceFile:2068) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by LoneDev6** [comment]
Do not post errors as screenshots.
Post text.

Make sure you are running the latest citizens version https://ci.citizensnpcs.co/job/citizens2/
