### ISSUE TITLE
Region files resources not getting released on world unload

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#2417]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I am using mythic dungeons to have dungeons on the server, it generates instances and deletes them when they are no longer used, the problem is when mythicdungeons wants to delete them with the new itemsadder configuration since it is using the new configuration in the most current version, no manages to delete the instance and leaves it with an error as a world apart, this does not happen in versions of items adder 3.3.1 or earlier

### Steps to reproduce the issue

when i enter a dungeon and i leave

### Server version

git-Pufferfish-47 (MC: 1.19.2)

### ItemsAdder Version

3.4.0c-beta

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.23

### FULL server log

[20:48:13] [Server thread/INFO]: [MythicDungeons] [STDOUT] §d-= Unloading world dungeon1_1 processed in 101ms. =-
[20:48:13] [Server thread/INFO]: [MythicDungeons] [STDOUT] §d-= Cleaning up dungeon1_1 processed in 103ms. =-
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: org.apache.commons.io.IOExceptionList: .\dungeon1_1
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at MythicDungeons-1.1.2-SNAPSHOT.jar//net.playavalon.mythicdungeons.dungeons.Instance.lambda$dispose$3(Instance.java:494)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: Caused by: java.io.IOException: Cannot delete file: .\dungeon1_1\itemsadder
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	... 8 more
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: Caused by: java.nio.file.FileSystemException: .\dungeon1_1\itemsadder\region\r.-1.-1.pregion: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	... 9 more

### Error (optional)

```shell
[20:48:13] [Server thread/INFO]: [MythicDungeons] [STDOUT] §d-= Unloading world dungeon1_1 processed in 101ms. =-
[20:48:13] [Server thread/INFO]: [MythicDungeons] [STDOUT] §d-= Cleaning up dungeon1_1 processed in 103ms. =-
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: org.apache.commons.io.IOExceptionList: .\dungeon1_1
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at MythicDungeons-1.1.2-SNAPSHOT.jar//net.playavalon.mythicdungeons.dungeons.Instance.lambda$dispose$3(Instance.java:494)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: Caused by: java.io.IOException: Cannot delete file: .\dungeon1_1\itemsadder
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	... 8 more
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: Caused by: java.nio.file.FileSystemException: .\dungeon1_1\itemsadder\region\r.-1.-1.pregion: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
[20:48:13] [Craft Scheduler Thread - 37 - MythicDungeons/WARN]: 	... 9 more
```

**Comment by LoneDev6** [comment]
Probably the file access is not released after world is unloaded, I have to check.
Thanks

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming update.
I did some tests and now the files are released every time a world is unloaded. For some reason it wasn't working before.

**Comment by WindUnwaken** [comment]
issue happens again ,on itemsadder 3.5.0c-r2 paper 1.19.4
https://mythiccraft.io/index.php?pages/official-mythicdungeons-download/&version=1.1.1
there is free version can test
