### ISSUE TITLE
itemsadder bug

### ISSUE THREAD

**Issue by wwqwqz** [PluginBugs/Issues-ItemsAdder#2446]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

wwqwqz#2670

### What happened?

Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder

### Steps to reproduce the issue

I don't know exactly how it happened, but something like this:
first I uploaded a folder backup for the ItemsAdder plugin, because due to an incident it did not work
already after downloading the backup, I rebooted the server, everything worked, but after adding a new item through ItemsAdder and MMOItems, I registered /iazip, then /iareload. after that, the plugin completely refused to work, updated protocolib, lonelibs, changed the server core from spigot to paper, nothing helps. climbed the configs, it did not help either. and all this happens after entering the server of any player.

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
Previous version: git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.4.1

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[2023-03-23-6.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11052490/2023-03-23-6.log)

### Error (optional)

```shell
[17:48:23 INFO]: shpinat[/80.234.77.134:7506] logged in with entity id 928 at ([world]4585.33754941062, 73.74313548392374, 3776.699999988079)
[17:48:23 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NoSuchFieldError: SYSTEM_CHAT
        at ia.m.bj.onPacketSending(SourceFile:292) ~[ItemsAdder_3.4.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
        at ia.nms.A.impl.v1_18_R2.Q(SourceFile:47) ~[ItemsAdder_3.4.1.jar:?]
        at ia.nms.A.A.Q(SourceFile:34) ~[ItemsAdder_3.4.1.jar:?]
        at ia.m.iJ.al(SourceFile:58) ~[ItemsAdder_3.4.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:48:23 INFO]: [AuthMe] shpinat logged in 80.234.77.134
[17:48:23 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSetActionBarTextPacket@140aa089[
    a=TextComponent{text='', siblings=[TextComponent{text=' ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
  ]
```

**Comment by wwqwqz** [comment]
@LoneDev6 just in case

**Comment by LoneDev6** [comment]
Update ProtocolLib to `5.0.0` https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
You have a very old version.
