### ISSUE TITLE
/iagive command doesnt work

### ISSUE THREAD

**Issue by EagL3-GIT** [PluginBugs/Issues-ItemsAdder#2455]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Its throwing an error when using /iagive command.

### Steps to reproduce the issue

1. Use /iagive command.

### Server version

This server is running Paper version git-Paper-468 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9087a64)

### ItemsAdder Version

ItemsAdder version 3.4.1-r2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b618

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
[17:07:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iagive' in plugin ItemsAdder v3.4.1-r2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-468]
at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-468]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2280) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2240) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.4.jar:git-Paper-468]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/Indyuce/mmoitems/MMOItems
at dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:24) ~[ItemsAdder_3.4.1-r2.jar:?]
at ia.m.I.a(SourceFile:3395) ~[ItemsAdder_3.4.1-r2.jar:?]
at ia.m.hq.onCommand(SourceFile:48) ~[ItemsAdder_3.4.1-r2.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
... 23 more
Caused by: java.lang.ClassNotFoundException: net.Indyuce.mmoitems.MMOItems
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:24) ~[ItemsAdder_3.4.1-r2.jar:?]
at ia.m.I.a(SourceFile:3395) ~[ItemsAdder_3.4.1-r2.jar:?]
at ia.m.hq.onCommand(SourceFile:48) ~[ItemsAdder_3.4.1-r2.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
... 23 more
```

**Comment by LoneDev6** [comment]
If you have MMOitems installed please provide here its version.
Make sure you installed MMOitems the latest version first.

If you don't have installed MMOitems, this is a bug and I'll fix it.

Let me know.

**Comment by LoneDev6** [comment]
Tested with MMOItems-6.9.2 and works fine.
