### ISSUE TITLE
Problem with AdvancedSlimePaper

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#2459]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After connecting to the slime world in the console errors

### Steps to reproduce the issue

just teleport to slime world

### Server version

> ver
[04:25:10 INFO]: Checking version, please wait...
[04:25:11 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-76 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: de1a62a on paper_upstream)
Unknown version

### ItemsAdder Version

> ver ItemsAdder
[04:25:19 INFO]: ItemsAdder version 3.4.1-r2
[04:25:19 INFO]: Customized Minecraft without client mods!
[04:25:19 INFO]: Website: devs.beer
[04:25:19 INFO]: Author: LoneDev
>

### ProtocolLib Version

[04:25:32 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b618
[04:25:32 INFO]: Provides read/write access to the Minecraft protocol.
[04:25:32 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> ver LoneLibs
[04:25:43 INFO]: LoneLibs version 1.0.24
[04:25:43 INFO]: Collection of libs used by my plugins
[04:25:43 INFO]: Authors: LoneDev and others
>

### FULL server log

[04:21:39 WARN]: [ItemsAdder] Task #1925 for ItemsAdder v3.4.1-r2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 84 out of bounds for length 24
        at net.minecraft.world.level.chunk.ChunkAccess.getSection(ChunkAccess.java:206) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:559) ~[?:?]
        at ia.nms.aI.impl.v1_19_R3.a(SourceFile:61) ~[ItemsAdder_3.4.1-r2-cracjka.jar:?]
        at ia.nms.aI.impl.v1_19_R3.L(SourceFile:29) ~[ItemsAdder_3.4.1-r2-cracjka.jar:?]
        at ia.m.cA.f(SourceFile:233) ~[ItemsAdder_3.4.1-r2-cracjka.jar:?]
        at ia.m.cA.a(SourceFile:520) ~[ItemsAdder_3.4.1-r2-cracjka.jar:?]
        at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r2-cracjka.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1411) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[slimeworldmanager-1.19.4.jar:git-SlimeWorldManager-76]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by LoneDev6** [comment]
Slime worlds are not currently compatible, will be worked on in the future.
Already asked here https://github.com/PluginBugs/Issues-ItemsAdder/issues/1589
