### ISSUE TITLE
Iris not compatible with ItemsAdder anymore

### ISSUE THREAD

**Issue by Pipokas** [PluginBugs/Issues-ItemsAdder#2464]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Pipokas#4995

### What happened?

Joining ItemsAdder with Iris gives error, even using ItemsAdderBlocksInjector compatibility

### Steps to reproduce the issue

Start the Server and wait for the error to appear when starting Iris and ItemsAdder

### Server version

git-Purpur-1933 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### ItemsAdder Version

3.4.1-r2

### ProtocolLib Version

v5.0.0-SNAPSHOT-b624

### LoneLibs Version

1.0.24

### Error (optional)

```shell
[14:09:27 INFO]: [Iris] Enabling Iris v2.4.3-1.19.3
[14:09:27 INFO]: [Iris] [Iris]: Locating NMS Binding for v1_19_R2
[14:09:27 INFO]: [Iris] [Iris]: Craftbukkit v1_19_R2  NMSBinding19_3 Successfully Bound
[14:09:27 ERROR]: Error occurred while enabling Iris v2.4.3-1.19.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at dev.lone.itemsadder.api.CustomStack.getNamespacedIdsInRegistry(SourceFile:41) ~[ItemsAdder_3.4.1-r2.jar:?]
        at com.volmit.iris.core.link.ItemAdderDataProvider.getItemTypes(ItemAdderDataProvider.java:58) ~[Iris-2.4.3-1.19.3.jar:?]
        at com.volmit.iris.core.link.ItemAdderDataProvider.init(ItemAdderDataProvider.java:24) ~[Iris-2.4.3-1.19.3.jar:?]
        at com.volmit.iris.core.service.ExternalDataSVC.addProvider(ExternalDataSVC.java:54) ~[Iris-2.4.3-1.19.3.jar:?]
        at com.volmit.iris.core.service.ExternalDataSVC.onEnable(ExternalDataSVC.java:40) ~[Iris-2.4.3-1.19.3.jar:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
        at com.volmit.iris.Iris.enable(Iris.java:442) ~[Iris-2.4.3-1.19.3.jar:?]
        at com.volmit.iris.Iris.onEnable(Iris.java:533) ~[Iris-2.4.3-1.19.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null
        at ia.m.I.<clinit>(SourceFile:111) ~[ItemsAdder_3.4.1-r2.jar:?]
        ... 18 more
[14:09:27 INFO]: [Iris] Disabling Iris v2.4.3-1.19.3
[14:09:27 ERROR]: Error occurred (in the plugin loader) while disabling Iris v2.4.3-1.19.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.volmit.iris.util.scheduling.Looper.interrupt()" because "this.dereferencer" is null
        at com.volmit.iris.core.service.PreservationSVC.onDisable(PreservationSVC.java:99) ~[Iris-2.4.3-1.19.3.jar:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
        at com.volmit.iris.Iris.onDisable(Iris.java:540) ~[Iris-2.4.3-1.19.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:09:27 INFO]: [ItemsAdderBlocksInjector] Enabling ItemsAdderBlocksInjector v0.0.9

...

[14:09:36 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r2
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1933 (MC: 1.19.3)
                                               
[14:09:36 ERROR]: Error occurred while enabling ItemsAdder v3.4.1-r2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
        at dev.lone.itemsadder.Main.onEnable(SourceFile:426) ~[ItemsAdder_3.4.1-r2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:09:36 INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1-r2
```

**Comment by LoneDev6** [comment]
Iris is trying to load before ItemsAdder.
This is the issue.

I have no idea why this happens only on your server.

**Comment by Pipokas** [comment]
On other Servers this is also happening! In the last update of Iris, the developer "reimplemented" the ItemsAdder to work, but it only gave errors, would you not be able to adapt to the current changes of Iris? Or is the error due to Iris?

Iris latest release (see the changelog): https://github.com/VolmitSoftware/Iris/releases/tag/2.4.3-1.19.3

**Comment by LoneDev6** [comment]
The error is due to Iris because they somehow don't wait ItemsAdder to load before using the ItemsAdder API.
They for some reason removed softdepend list from their plugin so I have no idea.
Here:
https://github.com/VolmitSoftware/Iris/commit/6990e341380b479e10d9cdfcf093123fbf839327

**Comment by NextdoorPsycho** [comment]
> The error is due to Iris because they somehow don't wait ItemsAdder to load before using the ItemsAdder API. They for some reason removed softdepend list from their plugin so I have no idea. Here: [VolmitSoftware/Iris@6990e34](https://github.com/VolmitSoftware/Iris/commit/6990e341380b479e10d9cdfcf093123fbf839327)

If we have you as a softdepend we are in the STARTUP section, and that pulls you into startup, and anything else that depends on you, and Itemsadder becomes unavailable for some other things that just do reflection. there are other issues, but thats the gist. I can readd it but it will cause other issues down the line if i recall

**Comment by Pipokas** [comment]
> If we have you as a softdepend we are in the STARTUP section, and that pulls you into startup, and anything else that depends on you, and Itemsadder becomes unavailable for some other things that just do reflection. there are other issues, but thats the gist. I can readd it but it will cause other issues down the line if i recall

Simply removing "load: STARTUP" and reimplementing the softdepend line solved the problem! Thanks

**Comment by NextdoorPsycho** [comment]
well, Iris needs to be in the startup to implement resources and datapacks,
and for a plethora of other NMS, and reflection changes that need to be
implemented. I wouldn’t recommend doing this, as yes, you might have an
immediate fix. But you are now going to have unforeseen consequences

**Comment by LoneDev6** [comment]
The other solution would be Iris calling `ItemAdderDataProvider` only after [ItemsAdderLoadDataEvent](https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/Events/ItemsAdderLoadDataEvent.java) is called and the cause is `FIRST_LOAD`.

But idk if it's doable on your side without adding crazy hacks to your code.
