### ISSUE TITLE
IA Crashes on start up when loading with Iris

### ISSUE THREAD

**Issue by AtmosphereRGS** [PluginBugs/Issues-ItemsAdder#2474]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When loading Items Adder both on its own and with Iris it stops both plugins from loading. This was not an issue when I ran both plugins on 1.19.2. I updated to 1.19.3 and updated both versions of the plugins and then started having this issue. Tried downgrading with no luck. It doesn't matter if I'm only loading IA or loading Iris as well. Both times IA crashes.

### Steps to reproduce the issue

1. Download IA and Iris
2. Install into the server
3. Load the server
4. Check the log for the crash

### Server version

Purpur version git-Purpur-1933 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 72b7579 on HEAD)

### ItemsAdder Version

ItemsAdder v3.4.1-r3

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b616

### LoneLibs Version

LoneLibs v1.0.24

### FULL server log

[2023-03-30-4.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11107970/2023-03-30-4.log)

### Error (optional)

```shell
[05:05:47] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.4.1-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
	at dev.lone.itemsadder.Main.onEnable(SourceFile:426) ~[ItemsAdder_3.4.1-r3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:05:47] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1-r3
```

**Comment by LoneDev6** [comment]
I think it's related to that: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2464
Also try to redownload ItemsAdder JAR again as it might be corrupted.
