### ISSUE TITLE
v1_18_R2.scheduler.CraftTask.run [and I can't iazip is stuck pack compressing]

### ISSUE THREAD

**Issue by JasperRuiz96** [PluginBugs/Issues-ItemsAdder#2482]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

JasperRuiz#9282

### What happened?

[20:57:31 INFO]: [ArsusNetwork] [Pack] Started generation
[20:57:31 INFO]: Successfully registered expansion: img [1.0.1]
[20:57:31 INFO]: Successfully registered expansion: iaplayerstat [1.0.1]
[20:57:32 WARN]: Plugin ItemsAdder v3.3.0 generated an exception while executing task 14908
java.lang.ArithmeticException: / by zero
	at ia.m.ib.a(SourceFile:219) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.ib.f(SourceFile:210) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.id.a(SourceFile:283) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.id.cv(SourceFile:105) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.hT.cp(SourceFile:647) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.I.a(SourceFile:2647) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.ht.a(SourceFile:85) ~[ItemsAdder_3.3.0.jar:?]
	at ia.m.I.a(SourceFile:2453) ~[ItemsAdder_3.3.0.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	
	
I'am using crafting plugin is a The Core -> TheCrafting
server version 1.18.2
![image](https://user-images.githubusercontent.com/126576073/229196764-b64a96a4-536a-4505-8f7d-9497db8cf4f0.png)

### Steps to reproduce the issue

.

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder v3.4.1-r4.jar

### ProtocolLib Version

v4.8.0

### LoneLibs Version

v1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11124768/latest.log)

**Comment by JasperRuiz96** [comment]
[09:36:29 INFO]: [ArsusNetwork]  
[09:36:29 INFO]: [ArsusNetwork] [Pack] Started generation
[09:36:29 INFO]: Successfully registered expansion: img [1.0.1]
[09:36:29 INFO]: Successfully registered expansion: iaplayerstat [1.0.1]
[09:36:29 WARN]: Plugin ItemsAdder v3.4.1-r4 generated an exception while executing task 21479
java.lang.ArithmeticException: / by zero
	at ia.m.iN.a(SourceFile:219) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.iN.f(SourceFile:210) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.iP.a(SourceFile:283) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.iP.cE(SourceFile:105) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.iD.cu(SourceFile:643) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.I.a(SourceFile:2654) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.hK.a(SourceFile:86) ~[ItemsAdder_3.4.1-r4.jar:?]
	at ia.m.I.a(SourceFile:2453) ~[ItemsAdder_3.4.1-r4.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:36:49 WARN]: [ArsusNetwork] Already reloading... Please wait before using /iazip
[09:40:03 INFO]: Players data was saved.
[09:40:03 INFO]: Entities/NPC data was saved.
[09:45:03 INFO]: Players data was saved.
[09:45:03 INFO]: Saving the game (this may take a moment!)
[09:45:03 INFO]: Entities/NPC data was saved.
[09:45:03 INFO]: Saved the game
[09:45:47 WARN]: [ArsusNetwork] Already reloading... Please wait before using /iazip

**Comment by JasperRuiz96** [comment]
fixed

**Comment by LoneDev6** [comment]
> fixed

Would you mind adding some information?
