### ISSUE TITLE
ItemsAdder Worldedit does not work properly under 1.19.3

### ISSUE THREAD

**Issue by omiyocn** [PluginBugs/Issues-ItemsAdder#2493]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

#ItemsAdder-WorldEdit

### What happened?

Hello, itemsadder developers
ItemsAdder-WorldEdit the plug-in does not work properly on 1.19.3

### Steps to reproduce the issue

1.Select the custom box
2.Custom blocks disappear automatically
3.//set blocks with itemsadder cannot be used

### Server version

This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)
Error obtaining version information
Previous version: git-Paper-383 (MC: 1.19.3)

### ItemsAdder Version

[22:00:09 INFO]: ItemsAdder version 3.4.1-r4
[22:00:09 INFO]: Customized Minecraft without client mods!
[22:00:09 INFO]: Website: devs.beer
[22:00:09 INFO]: Author: LoneDev

### ProtocolLib Version

[22:00:36 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b616
[22:00:36 INFO]: Provides read/write access to the Minecraft protocol.
[22:00:36 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[22:00:49 INFO]: LoneLibs version 1.0.24
[22:00:49 INFO]: Collection of libs used by my plugins
[22:00:49 INFO]: Authors: LoneDev and others

### Other files, you can drag and drop them here to upload. (optional)

WorldEdit version 7.2.13+46576cc

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-04-03 22-13-33_美化_gif](https://user-images.githubusercontent.com/84655411/229538554-c4a648bf-5300-4bc9-b9a5-662bdb9271c1.gif)

**Comment by omiyocn** [comment]
unable to display furniture texture after duplication

**Comment by omiyocn** [comment]
hellp,it seems that something went wrong

[22:16:53 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
[22:16:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:97)
[22:16:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:76)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.nms.impl.CraftItemStack_v1_19_R2.a(SourceFile:36)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.nms.impl.CraftItemStack_v1_19_R2.g(SourceFile:20)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.NItem.<init>(SourceFile:19)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:36)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:29)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.<init>(SourceFile:35)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:57)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:66)
[22:16:53 WARN]:        at ItemsAdder-WorldEdit_1.1.3.jar//dev.lone.iaedit.hook.CustomBlocksInputParser.parseFromInput(SourceFile:76)
[22:16:53 WARN]:        at ItemsAdder-WorldEdit_1.1.3.jar//dev.lone.iaedit.hook.CustomBlocksInputParser.parseFromInput(SourceFile:24)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497)
[22:16:53 WARN]:        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[22:16:53 WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
[22:16:53 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[22:16:53 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[22:16:53 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[22:16:53 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:16:53 WARN]:        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[22:16:53 WARN]:        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[22:16:53 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:16:53 WARN]:        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[22:16:53 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
[22:16:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:97)
[22:16:53 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:76)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.nms.impl.CraftItemStack_v1_19_R2.a(SourceFile:36)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.nms.impl.CraftItemStack_v1_19_R2.g(SourceFile:20)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//ia.nms.nbt.NItem.<init>(SourceFile:19)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:36)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:29)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.<init>(SourceFile:35)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:57)
[22:16:53 WARN]:        at ItemsAdder_3.4.1-r5.jar//dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:66)
[22:16:53 WARN]:        at ItemsAdder-WorldEdit_1.1.3.jar//dev.lone.iaedit.hook.CustomBlocksInputParser.parseFromInput(SourceFile:76)
[22:16:53 WARN]:        at ItemsAdder-WorldEdit_1.1.3.jar//dev.lone.iaedit.hook.CustomBlocksInputParser.parseFromInput(SourceFile:24)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:89)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.extension.factory.parser.pattern.RichPatternParser.parseFromInput(RichPatternParser.java:130)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:150)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.factory.PatternFactory.parseFromInput(PatternFactory.java:80)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:144)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.conversionFailedException(CommandParser.java:188)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:430)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//org.enginehub.piston.CommandManager.execute(CommandManager.java:154)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:730)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:751)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:732)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:702)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:28)
[22:16:53 WARN]:        at FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-396.jar//com.fastasyncworldedit.core.util.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:45)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[22:16:53 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by LoneDev6** [comment]
> however, the selected furniture cannot be reproduced, and it cannot be compatible with worldedit

I don't understand what you mean.
WorldEdit will copy furniture just fine.
The only issue is that you must not click on them using the wand. Try to select the area without clicking on the furniture, copy and paste, and let me know if it works.
Also please do not share GIF, share MP4 next time. It's impossible for me to watch the video multiple times if I cannot have the progress bar under the video.

> this is different from what is shown in your video, in which the square can be extended without trace

Please do not report multiple issues in the same issue report.
