### ISSUE TITLE
NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'

### ISSUE THREAD

**Issue by VzFusIIon** [PluginBugs/Issues-ItemsAdder#2498]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

CONSOLE SPAM when a player connect

### Steps to reproduce the issue

start server
player connect 
then spam

### Server version

spigot-1.19.4-R0.1-SNAPSHOT.jar

### ItemsAdder Version

3.4.1 r5

### ProtocolLib Version

5.0.0 b630

### LoneLibs Version

1.0.24

### FULL server log

[19:20:07] [Server thread/WARN]: [ItemsAdder] Task #135 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: org/bukkit/craftbukkit/v1_19_R3/CraftChunk.getHandle()Lnet/minecraft/world/level/chunk/Chunk; (loaded from file:/home/container/bundler/versions/spigot-1.19.4-R0.1-SNAPSHOT.jar by java.net.URLClassLoader@3a200ba0) called from class ia.nms.bA.impl.v1_19_R3 (loaded from file:/home/container/plugins/ItemsAdder_3.4.1-r5.jar by org.bukkit.plugin.java.PluginClassLoader@a68976c0).
at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[?:?]
at ia.m.cA.a(SourceFile:510) ~[?:?]
at ia.m.cI.c(SourceFile:43) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at java.lang.Thread.run(Thread.java:858) ~[?:?]

### Error (optional)

```shell
[19:20:07] [Server thread/WARN]: [ItemsAdder] Task #135 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: org/bukkit/craftbukkit/v1_19_R3/CraftChunk.getHandle()Lnet/minecraft/world/level/chunk/Chunk; (loaded from file:/home/container/bundler/versions/spigot-1.19.4-R0.1-SNAPSHOT.jar by java.net.URLClassLoader@3a200ba0) called from class ia.nms.bA.impl.v1_19_R3 (loaded from file:/home/container/plugins/ItemsAdder_3.4.1-r5.jar by org.bukkit.plugin.java.PluginClassLoader@a68976c0).
at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[?:?]
at ia.m.cA.a(SourceFile:510) ~[?:?]
at ia.m.cI.c(SourceFile:43) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3712-Spigot-b31949f-be8682a]
at java.lang.Thread.run(Thread.java:858) ~[?:?]
```

**Comment by ErythroCraft** [comment]
> 

Latest server build dev-Spigot-b31949f-be8682a (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) I use.

I can not use Paper, because many plugins on my server are not working with the Paper.

**Comment by ErythroCraft** [comment]
Missing ia.nms.bA.impl.v1_19_R4.class in your plugin

Is your plugin updated to ["NMS mapping - v1.19.4"](https://nms.screamingsandals.org/1.19.4/)

**Comment by ErythroCraft** [comment]
@LoneDev6

Missing ia.nms.bA.impl.v1_19_R4.class in your plugin.

Latest server build dev-Spigot-b31949f-be8682a (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) I use.

**Comment by qrawless** [comment]
i am having the same problem.

**Comment by DrTheodor** [comment]
I have the same issue.

**Comment by DrTheodor** [comment]
It seems like on 1.19.4 there is no `CraftChunk#getHandle()` method, only `CraftChunk#getHandle(ChunkStatus)` and it returns `IChunkAccess` and not `Chunk`... Maybe, that's the issue?

**Comment by ErythroCraft** [comment]
New BuildTools update today.

CraftBukkit version dev-Spigot-d2fdfe3-790be71 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

Same issue [Could not pass event BlockPhysicsEvent to ItemsAdder v3.4.1-r5]
Caused by: 
     java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk 
     org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at ia.nms.aI.impl.v1_19_R3.K(SourceFile:54) ~[?:?]
        at ia.nms.aI.aP.g(SourceFile:50) ~[?:?]
        at ia.m.cT.a(SourceFile:695) ~[?:?]
        at ia.m.cT.b(SourceFile:689) ~[?:?]
        at ia.m.cz.a(SourceFile:93) ~[?:?]

        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 18 more

**Comment by RFSMassacre** [comment]
The latest version of Paper is the problem. It removed a method that is in 1.19.4#490 that isn't in 1.19.4#509 anymore.

**Comment by ErythroCraft** [comment]
> @RFSMassacre Spigot same
The imlementated version of nms is outdated
    
    at ia.nms.aI.impl.v1_19_R3.K(SourceFile:54) ~[?:?]
    at ia.nms.aI.aP.g(SourceFile:50) ~[?:?]

**Comment by RFSMassacre** [comment]
Just use the April 3rd build until the next update comes out if you need it for 1.19.4 that badly.

**Comment by ErythroCraft** [comment]
@RFSMassacre 
Thanks, but it doesn't work. 
I prefer to wait for the release and play on one of my other game servers while it is released.

**Comment by RFSMassacre** [comment]
Well, I am having the same issue. I tried using a fresh world but it still happened. Using Paper #4900 from the day the plugin updated and #509 that came out today

**Comment by LoneDev6** [comment]
Will be checked today.
Probably something changed in Paper internals.

**Comment by aXe18** [comment]
> Will be checked today. Probably something changed in Paper internals.

Awesome ! Hopefully fast fix so i can update paper finally :)

**Comment by LoneDev6** [comment]
No worries, I was offline because I took a break during the Easter weekend.

**Comment by aXe18** [comment]
Yeah i think i saw some post about that :) Dont worry ! Its more than fine take breaks, preferred to even :D I should too, but too busy everyday... :D

**Comment by LoneDev6** [comment]
An update will be published today.
