### ISSUE TITLE
Error starting IA on paper 1.19.4

### ISSUE THREAD

**Issue by fnrcum** [PluginBugs/Issues-ItemsAdder#2503]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

`xafnir#1337`

### What happened?

Basically when trying to load the server with the latest IA i get this

```ps1
[00:08:33 INFO]: [ItemsAdder] Enabling ItemsAdder v3.4.1-r5
[00:08:34 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
[00:08:34 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R3' loaded!
[00:08:34 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[00:08:34 INFO]: [ItemsAdder]
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r5
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-481 (MC: 1.19.4)

[00:08:34 ERROR]: Error occurred while enabling ItemsAdder v3.4.1-r5 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
        at dev.lone.itemsadder.Main.onEnable(SourceFile:426) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-481]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-481]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-481]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-481]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:08:34 INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1-r5
```

After this, obiously every plugin that depends on IA dies

### Steps to reproduce the issue

I only put IA in the plugin folder as usual nothing special done

### Server version

`paper-1.19.4-481.jar`

### ItemsAdder Version

`v3.4.1-r5`

### ProtocolLib Version

Latest version on their jenkins

### LoneLibs Version

latest

### Error (optional)

```shell
[00:08:33 INFO]: [ItemsAdder] Enabling ItemsAdder v3.4.1-r5
[00:08:34 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
[00:08:34 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R3' loaded!
[00:08:34 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[00:08:34 INFO]: [ItemsAdder]
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r5
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-481 (MC: 1.19.4)

[00:08:34 ERROR]: Error occurred while enabling ItemsAdder v3.4.1-r5 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
        at dev.lone.itemsadder.Main.onEnable(SourceFile:426) ~[ItemsAdder_3.4.1-r5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-481]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-481]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-481]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-481]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-481]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:08:34 INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1-r5
```

**Comment by fnrcum** [comment]
Also, it doesn't happen with `v3.4.1-r4`

**Comment by ErythroCraft** [comment]
@LoneDev6 

Missing ia.nms.bA.impl.v1_19_R4.class in your plugin.
