### ISSUE TITLE
ItemsAdder turns off for no reason

### ISSUE THREAD

**Issue by Martinou2x** [PluginBugs/Issues-ItemsAdder#2523]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Martinouxx#2587

### What happened?

The plugin automatically deactivates for no reason, I am in 1.19.2 and there was nobody on the server. Just shut down with an error. It's not the first time this has happened to me.

### Steps to reproduce the issue

I don't know

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)*
* You are running the latest version

### ItemsAdder Version

 ItemsAdder version 3.4.1-r

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b632

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
1:

13:14:50 WARN]: Can't keep up! Is the server overloaded? Running 6065ms or 121 ticks behind
[13:26:01 WARN]: java.lang.AbstractMethodError
[13:26:01 WARN]:        at ia.m.fN.a(class:548)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.util.FastMath$lnMant.a(class:3953)
[13:26:01 WARN]:        at dev.lone.itemsadder.api.FontImages.FontImageWrapper.a(class:2373)
[13:26:01 WARN]:        at ia.nms.aR.c.a(class:3314)
[13:26:01 WARN]:        at ia.nms.nbt.nms.INBTTagList.a(class:990)
[13:26:01 WARN]:        at ia.m.fM.a(class:1287)
[13:26:01 WARN]:        at ia.nms.aW.impl.v1_19_R3.a(class:1290)
[13:26:01 WARN]:        at ia.nms.aT.impl.v1_18_R2.a(class:2794)
[13:26:01 WARN]:        at dev.lone.itemsadder.Campfire.Events.MoveItemToCampfireEvent.a(class:3111)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.distribution.NormalDistribution.a(class:2096)
[13:26:01 WARN]:        at ia.m.gK.a(class:3517)
[13:26:01 WARN]:        at ia.nms.nbt.NCompound.a(class:2173)
[13:26:01 WARN]:        at ia.nms.aG.impl.v1_17_R1.a(class:2599)
[13:26:01 WARN]:        at ia.m.hu.a(class:3367)
[13:26:01 WARN]:        at ia.m.da.a(class:2629)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.internal.function.PathFunctionFactory.a(class:2374)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.internal.EvaluationAbortException.a(class:2843)
[13:26:01 WARN]:        at ia.m.jN.a(class:5861)
[13:26:01 WARN]:        at ia.m.hz.a(class:4660)
[13:26:01 WARN]:        at ia.nms.aT.impl.v1_15_R1.a(class:1859)
[13:26:01 WARN]:        at ia.m.bQ.a(class:3926)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.internal.filter.EvaluatorFactory$GreaterThanEvaluator.a(class:1322)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.internal.path.RootPathToken$1.a(class:5106)
[13:26:01 WARN]:        at ia.nms.A.impl.v1_17_R1.a(class:2275)
[13:26:01 WARN]:        at ia.m.eA.a(class:6150)
[13:26:01 WARN]:        at ia.sh.net.minidev.json.writer.ArraysMapper$10.a(class:2354)
[13:26:01 WARN]:        at ia.m.go.a(class:4955)
[13:26:01 WARN]:        at ia.m.j.a(class:12)
[13:26:01 WARN]:        at ia.m.kj.a(class:604)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.exception.ZeroException.a(class:2241)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.util.FastMathLiteralArrays.a(class:4006)
[13:26:01 WARN]:        at ia.nms.aF.impl.v1_19_R3.a(class:2570)
[13:26:01 WARN]:        at ia.m.em.a(class:3387)
[13:26:01 WARN]:        at ia.nms.aX.impl.v1_16_R3.a(class:4003)
[13:26:01 WARN]:        at ia.m.db.a(class:1301)
[13:26:01 WARN]:        at ia.m.fm.a(class:1994)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.EvaluationListener$FoundResult.a(class:4258)
[13:26:01 WARN]:        at ia.sh.net.minidev.json.writer.BeansMapper$BeanNoConv.a(class:3469)
[13:26:01 WARN]:        at ia.nms.aF.aK.a(class:7)
[13:26:01 WARN]:        at ia.nms.aX.impl.c.a(class:5183)
[13:26:01 WARN]:        at ia.m.cQ.a(class:3118)
[13:26:01 WARN]:        at dev.lone.itemsadder.api.FontImages.PlayerHudWrapper.a(class:3923)
[13:26:01 WARN]:        at ia.nms.aU.bJ.a(class:470)
[13:26:01 WARN]:        at ia.m.ef.a(class:4644)
[13:26:01 WARN]:        at ia.m.fw.a(class:5584)
[13:26:01 WARN]:        at dev.lone.itemsadder.c.a(class:1300)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.exception.NoDataException.a(class:901)
[13:26:01 WARN]:        at ia.nms.aW.impl.v1_19_R3.a(class:1166)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.util.MathArrays$3.a(class:810)
[13:26:01 WARN]:        at dev.lone.itemsadder.api.ItemsAdder$Advanced$InjectedItemModifier.a(class:5062)
[13:26:01 WARN]:        at ia.nms.aa.impl.v1_15_R1.a(class:3164)
[13:26:01 WARN]:        at dev.lone.itemsadder.c.a(class:5275)
[13:26:01 WARN]:        at ia.m.kN.a(class:827)
[13:26:01 WARN]:        at ia.nms.aC.impl.v1_17_R1.a(class:3636)
[13:26:01 WARN]:        at ia.nms.aJ.impl.v1_18_R2.a(class:410)
[13:26:01 WARN]:        at dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.mechanics.BoneMechanic.a(class:5456)
[13:26:01 WARN]:        at ia.m.aO.a(class:2601)
[13:26:01 WARN]:        at ia.nms.aT.impl.v1_18_R2.a(class:4543)
[13:26:01 WARN]:        at ia.sh.com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider$BigIntegerReader.a(class:1706)
[13:26:01 WARN]:        at ia.nms.aV.bR.a(class:2070)
[13:26:01 WARN]:        at ia.nms.aZ.impl.v1_19_R2.a(class:5740)
[13:26:01 WARN]:        at ia.nms.nbt.nms.impl.NBTTagList_v1_17_R1.a(class:5047)
[13:26:01 WARN]:        at ia.m.fS.a(class:6250)
[13:26:01 WARN]:        at ia.m.N.a(class:5128)
[13:26:01 WARN]:        at ia.m.eK.a(class:2227)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.geometry.euclidean.threed.Euclidean3D$LazyHolder.a(class:3477)
[13:26:01 WARN]:        at ia.sh.net.minidev.json.JSONUtil$JsonSmartFieldFilter.a(class:6297)
[13:26:01 WARN]:        at ia.sh.net.minidev.json.reader.JsonWriter$5.a(class:865)
[13:26:01 WARN]:        at ia.m.hi.a(class:5572)
[13:26:01 WARN]:        at ia.sh.org.apache.commons.math3.excepti

2:

[13:29:48 WARN]: Unexpected exception while parsing console command "ia"
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v3.4.1-r5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:925) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
You have a broken jar file, try to redownload it.
Also I cannot find you on my Discord server.

**Comment by Martinou2x** [comment]
I reinstalled the plugin but still the same error and now the resourcepack does not download everything
![image](https://user-images.githubusercontent.com/104445025/231459306-8cfc9207-bb23-4062-bc2a-841ff9fc4f1d.png)

**Comment by LoneDev6** [comment]
Please share the full log there is something wrong in the server.
I'll help you
