### ISSUE TITLE
1.19.4 There is no CraftChunk#getHandle() method

### ISSUE THREAD

**Issue by zikehalil3535** [PluginBugs/Issues-ItemsAdder#2524]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Whiskey#0003

### What happened?

Itemsadder: 3.4.1-r5
Server: git-Purpur-1957 (MC: 1.19.4)

If I upgrade my server to the latest version purpur or paper Im getting spam warning like this.

For old versions working correctly 
Example: git-Purpur-1948 (MC: 1.19.4)

It seems like on 1.19.4 there is no CraftChunk#getHandle() method, only CraftChunk#getHandle(ChunkStatus) and it returns IChunkAccess and not Chunk... Maybe, that's the issue?

### Steps to reproduce the issue

1. Starting the server
2. Getting warning spam like this.

### Server version

git-Purpur-1957 (MC: 1.19.4)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b627

### LoneLibs Version

1.0.24

### FULL server log

https://mclo.gs/pYJUDM2

### Error (optional)

```shell
[17:16:12] [Server thread/WARN]: [ItemsAdder] Task #487 for ItemsAdder v3.4.1-r5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
	at ia.nms.bA.impl.v1_19_R3.c(SourceFile:237) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cA.a(SourceFile:510) ~[ItemsAdder_3.4.1-r5.jar:?]
	at ia.m.cI.c(SourceFile:43) ~[ItemsAdder_3.4.1-r5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/88826436/231199149-93c0a199-e19b-4d02-b412-cf5abce19dad.png)

**Comment by DexterSK** [comment]
yup same problem, with colored waters too

**Comment by dinobossytnew** [comment]
yea confirm x2

**Comment by SrMast3r** [comment]
I confirm what happened +1

**Comment by WMGameLive** [comment]
same

**Comment by GabrielTK** [comment]
Reproductible on Any Paper Build >= 499
