### ISSUE TITLE
Failed to parse ialiquids:worldgen/biome/green_water.json from pack file/ia_ialiquids

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#2525]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

see log

### Steps to reproduce the issue

start the server

### Server version

purpur-1.19.4.jar:git-Purpur-1957

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b632

### LoneLibs Version

v1.0.24

### Error (optional)

```shell
> Errors in registry minecraft:worldgen/biome:
>> Errors in element ialiquids:green_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/green_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":32768,"water_fog_color":32768,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
>> Errors in element ialiquids:orange_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/orange_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":16753920,"water_fog_color":16753920,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
>> Errors in element ialiquids:purple_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/purple_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":8388736,"water_fog_color":8388736,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
>> Errors in element ialiquids:red_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/red_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":16711680,"water_fog_color":16711680,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
>> Errors in element ialiquids:white_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/white_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":16777215,"water_fog_color":16777215,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
>> Errors in element ialiquids:yellow_water:
java.lang.IllegalStateException: Failed to parse ialiquids:worldgen/biome/yellow_water.json from pack file/ia_ialiquids
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:152)
        at net.minecraft.resources.RegistryDataLoader$b.a(RegistryDataLoader.java:166)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:62)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:54)
        at net.minecraft.server.WorldLoader.b(WorldLoader.java:58)
        at net.minecraft.server.WorldLoader.a(WorldLoader.java:31)
        at net.minecraft.server.Main.lambda$main$1(Main.java:247)
        at net.minecraft.SystemUtils.a(SystemUtils.java:808)
        at net.minecraft.SystemUtils.c(SystemUtils.java:803)
        at net.minecraft.server.Main.main(Main.java:246)
        at org.bukkit.craftbukkit.Main.main(Main.java:323)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No key has_precipitation in MapLike[{"surface_builder":"minecraft:grass","depth":0.125,"scale":0.05,"temperature":0.8,"downfall":0.4,"precipitation":"rain","category":"plains","effects":{"sky_color":7907327,"fog_color":12638463,"water_color":16777031,"water_fog_color":16777031,"foliage_color":7842607,"grass_color":9551193},"starts":[],"spawners":{},"spawn_costs":{},"carvers":{},"features":[]}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
        at net.minecraft.resources.RegistryDataLoader.a(RegistryDataLoader.java:148)
        ... 14 more
```

**Comment by LoneDev6** [comment]
Thanks, seems spigot 1.19.4 changed [something](https://www.reddit.com/r/MinecraftCommands/comments/125n773/how_do_you_add_custom_biomes_1194/) about biomes.
I'll fix it.
