### ISSUE TITLE
Plugin dont work

### ISSUE THREAD

**Issue by noopythepaster** [PluginBugs/Issues-ItemsAdder#2553]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Noopy#4459

### What happened?

Hi, i have merge my itemsadder with ModelEngine, i have remove the merge in the config.yml 
Versions of IA : ItemsAdder_3.4.0c-beta 
(with the latest versions my server is crashing

### Steps to reproduce the issue

Run the server

### Server version

1.19.2 Purpur 

### ItemsAdder Version

ItemsAdder_3.4.0c-beta

### ProtocolLib Version

ProtocolLib Version : 5.0.0-SNAPSHOT-b614

### LoneLibs Version

1.0.23

### FULL server log

(i cant because i use screen with my vps)

### Error (optional)

```shell
i have this error : 
[09:53:28 INFO]: [ItemsAdder] [Host] Stopped self-host webserver on port: 25567
[09:53:28 INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 25567
[09:53:28 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[09:53:28 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[09:53:28 WARN]: [ItemsAdder] Detected legacy ItemsAdder pack (pre 3.3.0).
[09:53:28 WARN]: [ItemsAdder] Trying to load files, unexpected results might occur.
[09:53:28 WARN]: [ItemsAdder] It's adviced to follow the new guidelines: https://a.devs.beer/ia-new-guidelines-330
[09:53:28 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[09:53:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
[09:53:28 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
[09:53:28 WARN]:        at java.base/java.lang.String.charAt(String.java:1513)
[09:53:28 WARN]:        at ItemsAdder_3.4.0c-beta.jar//ia.m.aK.o(SourceFile:250)
[09:53:28 WARN]:        at ItemsAdder_3.4.0c-beta.jar//ia.m.aJ.aA(SourceFile:171)
[09:53:28 WARN]:        at ItemsAdder_3.4.0c-beta.jar//ia.m.I.b(SourceFile:671)
[09:53:28 WARN]:        at ItemsAdder_3.4.0c-beta.jar//ia.m.I.a(SourceFile:573)
[09:53:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[09:53:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:53:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500)
[09:53:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[09:53:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[09:53:28 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[09:53:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[09:53:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/107602068/232772495-a6c00a2f-ad28-45da-a4dc-a40a5da91133.png)
![image](https://user-images.githubusercontent.com/107602068/232772555-80dbe6a9-41e4-4f4d-9307-b013edaf6208.png)

**Comment by LoneDev6** [comment]
Please next time do not report issues of outdated versions. You're still on `ItemsAdder_3.4.0c-beta`.
Update to the latest one and share the updated error.
Thanks.

Anyway you seem to have a misconfigured `font_image` or you have reached the max amount of font images.
How many font images did you add? 
The max amount is around `6608`.
