### ISSUE TITLE
Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutEntityEffect

### ISSUE THREAD

**Issue by Agriosz97** [PluginBugs/Issues-ItemsAdder#2557]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Agriosz#5743

### What happened?

Hello.
I simply see the next event every time I log in.
I read in another report to set this option to true.
log-loots-loading: true
This happened, but the phenomenon is still present

### Steps to reproduce the issue

This phenomenon appears simply every time you connect to a server

### Server version

> Current: git-Purpur-1933 (MC: 1.19.3)*

### ItemsAdder Version

ItemsAdder 3.4.1-r6

### ProtocolLib Version

ProtocolLib 5.0.0-SPANSHOT-b607

### LoneLibs Version

LoneLibs 1.0.24

### Error (optional)

```shell
Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.4.1-r6
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutEntityEffect
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:97) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:101) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:111) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at ia.nms.aU.bK.a(SourceFile:325) ~[ItemsAdder_3.4.1-r6.jar:?]
        at ia.nms.aU.bK.a(SourceFile:319) ~[ItemsAdder_3.4.1-r6.jar:?]
        at ia.m.iI.aj(SourceFile:140) ~[ItemsAdder_3.4.1-r6.jar:?]
        at ia.m.iA.a(SourceFile:160) ~[ItemsAdder_3.4.1-r6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1073.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1933]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
I'll check this, thanks
