### ISSUE TITLE
CustomEntity = Could not pass event ChunkLoadEvent

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2566]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

When summoning an entity with "/iaentity summon entity:ninja_skeleton", an error appears in the console. (the skeleton is not summoned)

### Steps to reproduce the issue

1. Add any entity
2. Summon it with /iaentity summon

### Server version

![image](https://user-images.githubusercontent.com/66962762/233799324-7b743be5-9a48-4b4b-a17e-f5fccb86c3f8.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/66962762/233799331-456585b0-417b-4fff-8135-243d7b4ce237.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/66962762/233799338-e989c246-0ba3-455a-bdb6-bc39d52ec281.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/66962762/233799347-3e0c5fda-ffc2-40f8-be3b-47506ed7b3a6.png)

### Error (optional)

```shell
[16:43:25] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to ItemsAdder v3.4.1-r6
java.lang.NullPointerException: Cannot read field "N" because "this.a" is null
	at ia.m.aa.a(SourceFile:239) ~[?:?]
	at ia.m.aa.a(SourceFile:182) ~[?:?]
	at ia.m.aa.a(SourceFile:177) ~[?:?]
	at ia.m.Y.a(SourceFile:637) ~[?:?]
	at ia.m.Y.a(SourceFile:609) ~[?:?]
	at ia.m.ay.f(SourceFile:102) ~[?:?]
	at ia.m.ay.a(SourceFile:80) ~[?:?]
	at ia.m.ay.a(SourceFile:453) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:1024) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:818) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:202) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1259) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:838) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1349) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
```


### Problematic items yml configuration file (optional)

```shell
info:
  namespace: entity
entities:
  ninja_skeleton:
    display_name: "Ниндзя скелет"
    type: ZOMBIE
    model_folder: entity/ninja_skeleton
```
```


### Other files, you can drag and drop them here to upload. (optional)

_No response_

### Screenshots/Videos (you can drag and drop files or paste links)

_No response_

**Comment by LoneDev6** [comment]
This will be checked, very strange.

Sorry for the delay, as I [previously announced](https://forum.devs.beer/d/298-inactivity-march-2023) I was on a little vacancy the previous week to rest and be ready to help you all better than before!
Thanks a lot for the patience.

**Comment by LoneDev6** [comment]
By reading your log seems somehow the entity animations are not loaded correctly because they might not exist.
The error basically tells you that ItemsAdder could not find the default idle animation of the entity.
Try to follow the tutorial again.
