### ISSUE TITLE
use_mmoitem_displayname issue related to mmoitem modifiers

### ISSUE THREAD

**Issue by AllayBreeze** [PluginBugs/Issues-ItemsAdder#2573]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Raenzil#7359

### What happened?

(1) If an mmoitem has modifiers that have prefixes, when create an IA item linked to this mmoitem, set "use_mmoitem_displayname" to true, and use /iaget to get the IA item, its display name will always have the same prefix, no matter what the actural modifier this item has, until /iareload.
(2) If an mmoitem doesn't have display name, when create an IA item linked to this mmoitem, and set "use_mmoitem_displayname" to true, /iaget will fail and send "internal error occured" message.
### Steps to reproduce the issue

1. Create an mmoitem, and set one or multiple modifiers. There's the mmoitem config I set, which doesn't have display name, to trigger (2):
```yml
STONE_SWORD:
  base:
    material: STONE_SWORD
    attack-damage: 4.0
    attack-speed: 1.4
    critical-strike-chance: 0.0
  modifiers:
    damaged:
      chance: 0.5
      prefix: §7Damaged Stone Sword
      weight: 1
      stats:
        tier: VERY_COMMON
        attack-damage: -0.525
        lore:
        - '&8Modifiers:'
        - '&7-15% &8Attack Damage'
```
2. Create an IA item that is linked with this mmoitem. My config:
```yml
info:
  namespace: equipments
items:
  stone_sword:
    mmoitem:
      type: SWORD
      id: STONE_SWORD
      use_mmoitem_displayname: true
    resource:
      material: STONE_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
```
3. After reloading MI and IA, try multiple times to use /iaget to get this item.
4. With these two configs, after an /iareload, when use /iaget equipments:stone_sword:
(1) 50% chance to give player a Damaged Stone Sword. Then /iaget equipments:stone_sword will always give player a stone sword named "Damaged Stone Sword" (but sometimes there are the "damaged" modifer's lore, sometimes not, indicating that the modifiers of these swords are acturally different), until the next /iareload.
(2) 50% chance to fail to execute the command. Then /iaget equipments:stone_sword will always fail until the next /iareload.

### Server version

Current: git-Purpur-1956 (MC: 1.19.4)*
Previous: git-Paper-487 (MC: 1.19.4)
* You are 8 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11322701/latest.log)

### Error (optional)

```shell
[20:56:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iaget' in plugin ItemsAdder v3.4.1-r6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2381) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2341) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1956]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonParseException: Don't know how to turn null into a Component
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:323) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:88) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
	at ia.nms.aE.aE.a(SourceFile:80) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.ep.a(SourceFile:1511) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.ep.a(SourceFile:1498) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.ep.e(SourceFile:1546) ~[ItemsAdder_3.4.1-r6.jar:?]
	at dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:75) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.I.a(SourceFile:3398) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.hp.onCommand(SourceFile:47) ~[ItemsAdder_3.4.1-r6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by LoneDev6** [comment]
This will be checked, very strange.

**Comment by LoneDev6** [comment]
Can you share screenshots of the items in your step by step guide?
Thanks.

**Comment by AllayBreeze** [comment]
This is the two possible situations I described in the 4th step (what will happen when executing /iaget to get this stone sword):
![3](https://user-images.githubusercontent.com/108282297/236174251-da096bb3-bf5c-465e-9615-8997bad35d2f.png)
Either the swords are always named "Damaged Stone Sword", but their Attack Damage and modifier lores are not the same; or the commands always fail.
The intended behavior should be that the given item will have a 50% chance to be a stone sword, no display name, no modifier lore and 4 attack damage; and 50% to be a stone sword named "Damaged Stone Sword", having modifier lore"-15% Attack Damage" and 3.5 attack damage.
And this is when using /mi give SWORD STONE_SWORD to get this item by mmoitem's command, which will give the correct items.
![2](https://user-images.githubusercontent.com/108282297/236175903-02ff1ce9-59ab-4bf0-9957-2fe666cfaf9d.png)

**Comment by LoneDev6** [comment]
I cannot reproduce the issue using the latest ItemsAdder 3.4.1b.
Anyway one fix could be to make sure to set a display name for your ItemsAdder item.
It will be used as fallback display name if the mmoitem chance is not triggered.

```yml
info:
  namespace: equipments
items:
  stone_sword:
    display_name: Stone Sword
    mmoitem:
      type: SWORD
      id: STONE_SWORD
      use_mmoitem_displayname: true
    resource:
      material: STONE_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
```
