### ISSUE TITLE
Failed to protect resourcepack

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2576]
More info:
https://forum.devs.beer/d/439-ia-failing-to-protect-zip-file

--- 
## Message from [kaiserkrister](https://forum.devs.beer/u/kaiserkrister)

Tested this on Arclight (hybrid) and on paper both give this error.
Not sure if they are related to eachother, but ill add the warns that are under the intial error.

```
[17:10:47 ERROR]: [ItemsAdder] Failed to protect zip file.
[17:10:47 WARN]: java.lang.IndexOutOfBoundsException
[17:10:47 WARN]: at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
[17:10:47 WARN]: at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:558)
[17:10:47 WARN]: at ia.m.iM.d(SourceFile:116)
[17:10:47 WARN]: at ia.m.iz.a(SourceFile:227)
[17:10:47 WARN]: at ia.m.iD.a(SourceFile:421)
[17:10:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:10:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:10:47 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:10:47 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:10:47 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:10:47 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
I tried with your pack and it correctly protects it without any error.
I think there is something wrong in your server and sadly I cannot think about any other solution:

* update your server
* update your dependencies
* update itemsadder
* redownload itemsadder
* disable **protection 2** and use only **protection 1**.

  ```yml
    zip:
      protect-file-from-unzip:
        protection_1: true
        protection_2: false
  ```
