### ISSUE TITLE
resources are not loaded by itemsAdder

### ISSUE THREAD

**Issue by NvyWeed** [PluginBugs/Issues-ItemsAdder#2583]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

resources are not loaded by itemsAdder when i enter the server.

### Steps to reproduce the issue

resources are not loaded by itemsAdder when i enter the server.

and the error appears as soon as I enter

### Server version

paper 1.17.1

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[23:36:20] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:36:21] [main/INFO]: Reloading ResourceManager: Default, bukkit
[23:36:21] [Worker-Main-2/INFO]: Loaded 7 recipes
[23:36:23] [Server thread/INFO]: Starting minecraft server version 1.17.1
[23:36:23] [Server thread/WARN]: ****************************
[23:36:23] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[23:36:23] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[23:36:23] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[23:36:23] [Server thread/WARN]: ****************************
[23:36:23] [Server thread/INFO]: Loading properties
[23:36:23] [Server thread/INFO]: This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
[23:36:23] [Server thread/INFO]: Server Ping Player Sample Count: 12
[23:36:23] [Server thread/INFO]: Using 4 threads for Netty based IO
[23:36:24] [Server thread/INFO]: Default game type: SURVIVAL
[23:36:24] [Server thread/INFO]: Generating keypair
[23:36:24] [Server thread/INFO]: Starting Minecraft server on *:25570
[23:36:24] [Server thread/INFO]: Using epoll channel type
[23:36:24] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[23:36:24] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[23:36:24] [Server thread/WARN]: [io.netty.util.internal.MacAddressUtil] Failed to find a usable hardware address from the network interfaces; using random bytes: db:7e:8c:c6:44:9f:81:3f
[23:36:25] [Server thread/INFO]: [CoreProtect] Loading CoreProtect v21.2
[23:36:25] [Server thread/INFO]: [LastLog] Loading LastLog v1.2.0
[23:36:25] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.6.2
[23:36:25] [Server thread/INFO]: [ViaVersion] ViaVersion 4.6.2 is now loaded. Registering protocol transformers and injecting...
[23:36:25] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[23:36:25] [Server thread/INFO]: [Blue Slime Core] Loading BlueSlimeCore v2.6.1.222-Beta
[23:36:25] [Server thread/INFO]: [LoneLibs] Loading LoneLibs v1.0.24
[23:36:25] [Server thread/INFO]: [LightAPI] Loading LightAPI v3.5.2
[23:36:25] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[23:36:25] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[23:36:26] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.41
[23:36:27] [Server thread/INFO]: [Essentials] Loading Essentials v2.20.0-dev+5-0ca58ce
[23:36:27] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v3.4.1-r6
[23:36:27] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:36:27] [Server thread/INFO]: [Blue Slime Core] Enabling BlueSlimeCore v2.6.1.222-Beta
[23:36:27] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.24
[23:36:27] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[23:36:27] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[23:36:27] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.41
[23:36:27] [Server thread/INFO]:         __    
[23:36:27] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.41
[23:36:27] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[23:36:27] [Server thread/INFO]: 
[23:36:27] [Server thread/INFO]: [LuckPerms] Loading configuration...
[23:36:27] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[23:36:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[23:36:27] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[23:36:28] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[23:36:28] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[23:36:28] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[23:36:28] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1323ms)
[23:36:28] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:36:28] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:36:28] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[23:36:28] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:36:28] [Server thread/INFO]: Preparing level "world"
[23:36:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:36:29] [Server thread/INFO]: Time elapsed: 524 ms
[23:36:29] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[23:36:30] [Server thread/INFO]: Preparing spawn area: 0%
[23:36:30] [Server thread/INFO]: Preparing spawn area: 0%
[23:36:30] [Server thread/INFO]: Preparing spawn area: 0%
[23:36:30] [Server thread/INFO]: Preparing spawn area: 0%
[23:36:30] [Server thread/INFO]: Time elapsed: 1506 ms
[23:36:30] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[23:36:31] [Server thread/INFO]: Preparing spawn area: 0%
[23:36:31] [Server thread/INFO]: Time elapsed: 245 ms
[23:36:31] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v21.2
[23:36:31] [Server thread/INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[23:36:31] [Server thread/INFO]: [CoreProtect] Using SQLite for data storage.
[23:36:31] [Server thread/INFO]: --------------------
[23:36:31] [Server thread/INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[23:36:31] [Server thread/INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[23:36:31] [Server thread/INFO]: --------------------
[23:36:31] [Server thread/INFO]: [LastLog] Enabling LastLog v1.2.0
[23:36:31] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.6.2
[23:36:31] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.17.1 (756)
[23:36:31] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.5.2
[23:36:31] [Server thread/INFO]: [LightAPI] Loading CraftBukkit implementation for Paper server v1_17_R1.
[23:36:31] [Server thread/INFO]: [Essentials] Enabling Essentials v2.20.0-dev+5-0ca58ce
[23:36:31] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[23:36:31] [Server thread/INFO]: [Essentials] No kits found to migrate.
[23:36:31] [Server thread/INFO]: [Essentials] Loaded 38132 items from items.json.
[23:36:31] [Server thread/INFO]: [Essentials] Using locale en_US
[23:36:32] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[23:36:32] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[23:36:32] [Server thread/WARN]: [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
[23:36:32] [Server thread/WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[23:36:32] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[23:36:32] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.4.1-r6
[23:36:32] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[23:36:32] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_17_R1' loaded!
[23:36:32] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[23:36:32] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m
[0;36;1m  ___  ___        __        __   __   ___  __  [0;32;22m    ItemsAdder[0;37;22m 3.4.1-r6
[0;36;1m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [0;32;22m    LoneLibs[0;37;22m 1.0.24
[0;36;1m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [0;30;1m    Paper git-Paper-411 (MC: 1.17.1)
[0;36;1m                                               [m
[23:36:33] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m[Host] Starting self-host webserver on port: 8163[m
[23:36:33] [Server thread/INFO]: Running delayed init tasks
[23:36:33] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Extracting internal contents from .jar[m
[23:36:33] [Craft Scheduler Thread - 1 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[23:36:33] [Craft Scheduler Thread - 1 - Essentials/INFO]: [Essentials] Fetching version information...
[23:36:33] [Craft Scheduler Thread - 1 - Essentials/INFO]: [Essentials] Update checking disabled in config.
[23:36:33] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[License] Spigot product licensed to: [0;36;1mNvyWeed (1647895)[m
[23:36:33] [Craft Scheduler Thread - 4 - BlueSlimeCore/INFO]: [Blue Slime Core]  
[23:36:33] [Craft Scheduler Thread - 4 - BlueSlimeCore/INFO]: [Blue Slime Core] [Update Checker] A possible update was found for plugin 'BlueSlimeCore'.
[23:36:33] [Craft Scheduler Thread - 4 - BlueSlimeCore/INFO]: [Blue Slime Core] [Update Checker] Current Version: 2.6.1.222-Beta
[23:36:33] [Craft Scheduler Thread - 4 - BlueSlimeCore/INFO]: [Blue Slime Core] [Update Checker] New Version: 2.9.0.346
[23:36:33] [Craft Scheduler Thread - 4 - BlueSlimeCore/INFO]: [Blue Slime Core] [Update Checker] Download Link: https://www.spigotmc.org/resources/83189/
[23:36:33] [Server thread/INFO]: [ItemsAdder] [m[0;32;1m[Pack] DONE extracting internal contents from .jar[m
[23:36:33] [Server thread/WARN]: [ItemsAdder] [m[0;33;1mDetected legacy ItemsAdder pack (pre 3.3.0).[m
[23:36:33] [Server thread/WARN]: [ItemsAdder] [m[0;33;1mTrying to load files, unexpected results might occur.[m
[23:36:33] [Server thread/WARN]: [ItemsAdder] [m[0;33;1mIt's adviced to follow the new guidelines: https://a.devs.beer/ia-new-guidelines-330[m
[23:36:34] [Server thread/INFO]: Done (10.564s)! For help, type "help"
[23:36:34] [Server thread/INFO]: Timings Reset
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mLoaded [0;36;1m128[0;33;1m items[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m188[0;33;1m REAL block IDs[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m12[0;33;1m/[0;36;1m750[0;33;1m REAL_NOTE block IDs[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m63[0;33;1m REAL_TRANSPARENT block IDs[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m127[0;33;1m REAL_WIRE block IDs[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m14[0;33;1m FIRE block IDs[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m704[0;33;1m/[0;36;1m6608[0;33;1m font_images[m
[23:36:34] [Thread-13/INFO]: --------------------
[23:36:34] [Thread-13/INFO]: [CoreProtect] Version 21.3 is now available.
[23:36:34] [Thread-13/INFO]: [CoreProtect] Download: www.coreprotect.net/download/
[23:36:34] [Thread-13/INFO]: --------------------
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded [0;36;1m8[0;33;1m categories[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded successfully.[m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url... [m
[23:36:34] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [m[0;32;1m[Pack] Resourcepack URL (self-host): http://185.25.206.229:8163/generated.zip[m
[23:36:36] [Server thread/INFO]: -------< LightAPI-fork 3.5.2 >-------
[23:36:36] [Server thread/INFO]: You are running the latest version!
[23:36:43] [Server thread/INFO]: LoneLibs version 1.0.24
[23:36:43] [Server thread/INFO]: Collection of libs used by my plugins
[23:36:43] [Server thread/INFO]: Authors: LoneDev and others
[23:37:05] [User Authenticator #1/WARN]: [LuckPerms] LuckPerms already has data for player 'NvyWeed' - but this data is stored under a different UUID.
[23:37:05] [User Authenticator #1/WARN]: [LuckPerms] 'NvyWeed' has previously used the unique ids [a3c76ff9-abc5-4853-a2f8-74e49d89daf2] but is now connecting with 'b85b2fe6-dde5-34b1-80f6-ada7bf119d56'
[23:37:05] [User Authenticator #1/WARN]: [LuckPerms] The UUID the player is connecting with now is NOT Mojang-assigned (type 3). This implies that THIS server is not authenticating correctly, but one (or more) of the other servers/proxies in the network are.
[23:37:05] [User Authenticator #1/WARN]: [LuckPerms] If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers!
[23:37:05] [User Authenticator #1/WARN]: [LuckPerms] See here for more info: https://luckperms.net/wiki/Network-Installation#pre-setup
[23:37:05] [User Authenticator #1/INFO]: UUID of player NvyWeed is b85b2fe6-dde5-34b1-80f6-ada7bf119d56
[23:37:05] [Server thread/INFO]: NvyWeed joined the game
[23:37:05] [Server thread/INFO]: NvyWeed[/185.25.206.229:52776] logged in with entity id 188 at ([world]20.90197489942343, 72.0, 130.4377426116708)
[23:37:05] [Netty Epoll Server IO #1/WARN]: [ViaVersion] No light data found for chunk at 1, 8. Chunk was already loaded: false
[23:37:06] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NoSuchFieldError: SYSTEM_CHAT
	at ia.m.bj.onPacketSending(SourceFile:292) ~[ItemsAdder_3.4.1-r6.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
	at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1997) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1983) ~[app:?]
	at ia.nms.A.impl.v1_17_R1.Q(SourceFile:47) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.nms.A.A.Q(SourceFile:34) ~[ItemsAdder_3.4.1-r6.jar:?]
	at ia.m.iJ.cC(SourceFile:70) ~[ItemsAdder_3.4.1-r6.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:37:06] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSetActionBarTextPacket@499b2aab[
    a=TextComponent{text='', siblings=[TextComponent{text=' ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
  ]

[23:38:44] [Server thread/INFO]: NvyWeed lost connection: Disconnected
[23:38:44] [Server thread/INFO]: NvyWeed left the game

### Screenshots/Videos (you can drag and drop files or paste links)

![fsdfsdf](https://user-images.githubusercontent.com/113480797/235381344-8e2cf950-dc10-4e3e-bdc5-cb4323bed030.PNG)

**Comment by LoneDev6** [comment]
Update LoneLibs and ProtocolLib.
https://www.spigotmc.org/resources/lonelibs.75974/
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
