### ISSUE TITLE
Plugin crashes server when installed

### ISSUE THREAD

**Issue by UngyIsHere** [PluginBugs/Issues-ItemsAdder#2597]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Whenever ItemsAdder is installed on the client, it permanently shuts the server down with no clear indication of how or why. Forcing to either reinstall a previous backup, or deleting the plugin outright. ProtocolLib and LoneLibs does fine by itself without crashing the server. However, when ItemsAdder is installed no errors, no communication, and complete shutdown of the server occurs. I have tried using Paper and Spigot with the same results occurring every time. I have even tried an isolated "clean" server with no plugins to interfere and it still occurs. Please contact me on a solution for this problem. 

### Steps to reproduce the issue

1. Stop server
2. Install ProtocolLib
3. Install LoneLibs
4. Install ItemsAdder
5. Start server
6. Server is turned permanently offline even when rebooted

### Server version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version

### ItemsAdder Version

Unknown since every time ItemsAdder is installed the server crashes.

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-639

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
Server starting, setting up fifo connections and writing server ready.
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 5.19.0-41-generic (amd64)
Loading libraries, please wait...
2023-05-03 19:45:16,691 ServerMain WARN Advanced terminal features are not available in this environment
[19:45:18 INFO]: Building unoptimized datafixer
[19:45:20 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:45:21 INFO]: Loaded 7 recipes
[19:45:22 INFO]: Starting minecraft server version 1.19
[19:45:22 INFO]: Loading properties
[19:45:22 INFO]: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
[19:45:22 INFO]: Server Ping Player Sample Count: 12
[19:45:22 INFO]: Using 4 threads for Netty based IO
[19:45:22 INFO]: Default game type: SURVIVAL
[19:45:22 INFO]: Generating keypair
[19:45:22 INFO]: Starting Minecraft server on *:25575
[19:45:22 INFO]: Using epoll channel type
[19:45:22 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[19:45:22 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[19:45:23 INFO]: [MinehutPlugin] Found matching server revision (V1_19)
[19:45:23 INFO]: [ViaVersion] Loading ViaVersion v4.6.2
[19:45:23 INFO]: [ViaVersion] ViaVersion 4.6.2 is now loaded. Registering protocol transformers and injecting...
[19:45:23 INFO]: [ViaVersion] Loading block connection mappings ...
```

**Comment by LoneDev6** [comment]
Please post the whole log.
Thanks.

**Comment by UngyIsHere** [comment]
[14:40:23 INFO]: [ViaVersion] Enabling ViaVersion v4.6.2
[14:40:23 INFO]: [ViaVersion] ViaVersion detected server version: 1.19 (759)
[14:40:24 INFO]: [MinehutPlugin] Enabling MinehutPlugin v0.0.27-SNAPSHOT
[14:40:24 INFO]: [ItemsAdder] Enabling ItemsAdder v3.4.1b
[14:40:24 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[14:40:24 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R1' loaded!
[14:40:24 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m????????????????????????????????????????????????????????????????????[m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1mThis server version is not supported: 1.19.0[m
[14:40:24 WARN]: [ItemsAdder] [m[0;33;1mYou're running an outdated version of Spigot. Please update it to 1.19.3.[m
[14:40:24 WARN]: [ItemsAdder] [m[0;33;1mOpen config.yml and set 'ignore-server-compatibility-check: true' 
to load the plugin anyway and see to report them on Github:
> http://a.devs.beer/ia-not-compat-git <[m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m [m
[14:40:24 ERROR]: [ItemsAdder] [m[0;31;1m????????????????????????????????????????????????????????????????????[m
[14:40:24 INFO]: Running delayed init tasks
[14:40:24 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[14:40:24 INFO]: Done (15.716s)! For help, type "help"
[14:40:24 INFO]: Stopping server
[14:40:24 INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1b
[14:40:24 INFO]: [ProtocolLib] Disabling ProtocolLib v5.0.0-SNAPSHOT-639
[14:40:24 INFO]: [MinehutPlugin] Disabling MinehutPlugin v0.0.27-SNAPSHOT
[14:40:24 INFO]: [LoneLibs] Disabling LoneLibs v1.0.24
[14:40:24 INFO]: [ViaVersion] Disabling ViaVersion v4.6.2
[14:40:24 INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[14:40:24 WARN]: [ViaVersion] Plugin ViaVersion v4.6.2 generated an exception while executing task 8
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.viaversion.viaversion.update.UpdateUtil.getUpdateMessage(UpdateUtil.java:72) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.update.UpdateUtil.lambda$sendUpdateMessage$3(UpdateUtil.java:51) ~[ViaVersion.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-81]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:40:24 INFO]: Saving players
[14:40:24 INFO]: Saving worlds
[14:40:25 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:40:25 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[14:40:25 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[14:40:25 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:40:25 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:40:25 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:40:25 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:40:25 INFO]: Flushing Chunk IO
2023-05-04 14:40:25,340 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[14:40:25 INFO]: Closing Thread Pool
[14:40:25 INFO]: Closing Server
Server starting, setting up fifo connections and writing server ready.

**Comment by LoneDev6** [comment]
> [14:40:24 WARN]: [ItemsAdder] �[m�[0;33;1mYou're running an outdated version of Spigot. Please update it to 1.19.3.�[m

**Comment by UngyIsHere** [comment]
Is there a 1.19 version I can download or do I have to actually change my server

**Comment by LoneDev6** [comment]
There is no reason to stay on a broken old Minecraft version.
You always must update to the latest build for the current version of the game.
1.19 is old and has plenty of issues, update to 1.19.3.
