### ISSUE TITLE
IAZIP Error 

### ISSUE THREAD

**Issue by Sawamo** [PluginBugs/Issues-ItemsAdder#2614]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I was adding new stuff and when I wanted to zip everything it didn't work.

### Steps to reproduce the issue

1-Added stuff
2- Ran /iazip

### Server version

Crafbukkit version 3670-Spigot-454acb7-bd29f41 (MC:1.19.3)

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.0.0-SNAPSHOT-636

### LoneLibs Version

1.0.24

### Error (optional)

```shell
[23:20:11 INFO]: Shiget0ra_ issued server command: /iazip
[23:20:11 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[23:20:11 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[23:20:11 ERROR]: [ItemsAdder] Failed to load item platinum_leggings. The slot 'leg' is not a valid armor slot. File: /contents/custom/configs/platinum_leggings.yml
[23:20:11 INFO]: [ItemsAdder] Loaded 84 items
[23:20:11 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[23:20:11 INFO]: [ItemsAdder] Used 1/750 REAL_NOTE block IDs
[23:20:11 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[23:20:11 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[23:20:11 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[23:20:11 INFO]: [ItemsAdder] Used 84/6608 font_images
[23:20:11 INFO]: [ItemsAdder] [Init] Loaded 2 categories
[23:20:11 INFO]: [ItemsAdder] [Init] Loaded successfully in 342ms
[23:20:11 INFO]: [ItemsAdder]  
[23:20:11 INFO]: [ItemsAdder]  
[23:20:11 INFO]: [ItemsAdder] [Pack] Started generation
[23:20:11 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:20:11 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:20:11 INFO]: [Mythic] Reloading plugin...
[23:20:11 INFO]: [MythicMobs] Mythic beginning reload procedure...
[23:20:11 INFO]: [MythicMobs] Loading Packs...
[23:20:11 INFO]: [MythicMobs] PACK C:\Users\Shigetora\Desktop\Survival Server\plugins\MythicMobs\Packs\littleroom\packinfo.yml
[23:20:11 INFO]: [MythicMobs] Loading Items...
[23:20:11 INFO]: [MythicMobs] Loading Item Groups...
[23:20:11 INFO]: [MythicMobs] Loading Skills...
[23:20:11 WARN]: [MythicMobs] Failed to parse Placeholder '<skill.var.damage-amount>': Math and variables in numeric values require premium! Consider getting MythicMobs Premium at www.mythiccraft.io
[23:20:11 WARN]: [MythicMobs] Failed to parse Placeholder '<skill.var.damage-amount>': Math and variables in numeric values require premium! Consider getting MythicMobs Premium at www.mythiccraft.io
[23:20:11 WARN]: [MythicMobs] Failed to parse Placeholder '<caster.level>': Math and variables in numeric values require premium! Consider getting MythicMobs Premium at www.mythiccraft.io
[23:20:11 WARN]: [MythicMobs] Failed to parse Placeholder '1.0E-5': Math and variables in numeric values require premium! Consider getting MythicMobs Premium at www.mythiccraft.io
[23:20:11 INFO]: [MythicMobs] Loading Drop Tables...
[23:20:11 INFO]: [MythicMobs] Loading Random Spawns...
[23:20:11 WARN]: [MythicMobs] ✗ Configuration Error in RandomSpawn RandomFrog
[23:20:11 WARN]: [MythicMobs] --| File: Unknown
[23:20:11 WARN]: [MythicMobs] --| Error Message: No valid mob types configured
[23:20:11 INFO]: [MythicMobs] Loading Spawn Blocks...
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 31 mobs.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 5 vanilla mob overrides.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 88 skills.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 10 random spawns.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 10 mythic items.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 4 drop tables.
[23:20:11 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[23:20:11 INFO]: [MythicMobs] Attached traits to items.
[23:20:11 INFO]: [Mythic] Mythic has finished reloading!
[23:20:11 INFO]: [MythicMobs] Mythic has finished reloading!
[23:20:11 ERROR]: [ItemsAdder] Failed to generate armor atlas.
[23:20:11 WARN]: java.lang.ArithmeticException: / by zero
[23:20:11 WARN]: 	at ia.m.iN.b(SourceFile:234)
[23:20:11 WARN]: 	at ia.m.iN.g(SourceFile:224)
[23:20:11 WARN]: 	at ia.m.iP.a(SourceFile:380)
[23:20:11 WARN]: 	at ia.m.iP.a(SourceFile:256)
[23:20:11 WARN]: 	at ia.m.iP.cE(SourceFile:245)
[23:20:11 WARN]: 	at ia.m.iD.cu(SourceFile:653)
[23:20:11 WARN]: 	at ia.m.I.a(SourceFile:2659)
[23:20:11 WARN]: 	at ia.m.hK.a(SourceFile:86)
[23:20:11 WARN]: 	at ia.m.I.a(SourceFile:2458)
[23:20:11 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82)
[23:20:11 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:20:11 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:20:11 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:20:11 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:20:12 WARN]: [ItemsAdder] Plugin ItemsAdder v3.4.1-r6 generated an exception while executing task 2938
java.lang.ArithmeticException: / by zero
	at ia.m.iN.b(SourceFile:234) ~[?:?]
	at ia.m.iN.a(SourceFile:218) ~[?:?]
	at ia.m.iP.a(SourceFile:830) ~[?:?]
	at ia.m.iP.cH(SourceFile:671) ~[?:?]
	at ia.m.iD.cu(SourceFile:656) ~[?:?]
	at ia.m.I.a(SourceFile:2659) ~[?:?]
	at ia.m.hK.a(SourceFile:86) ~[?:?]
	at ia.m.I.a(SourceFile:2458) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3670-Spigot-454acb7-bd29f41]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[23:20:12 WARN]: [MythicMobs] ✗ Configuration Error in Drop pelt
[23:20:12 WARN]: [MythicMobs] --| File: DropItemMechanic
[23:20:12 WARN]: [MythicMobs] --| Error Message: Drop type not found.
[23:20:12 WARN]: [MythicMobs] ✗ Configuration Error in Drop pelt
[23:20:12 WARN]: [MythicMobs] --| File: DropItemMechanic
[23:20:12 WARN]: [MythicMobs] --| Error Message: Drop type not found.
[23:20:12 WARN]: [MythicMobs] ✗ Configuration Error in Drop pelt
[23:20:12 WARN]: [MythicMobs] --| File: DropItemMechanic
[23:20:12 WARN]: [MythicMobs] --| Error Message: Drop type not found.
```

**Comment by SirCraftypants** [comment]
`[23:20:11 ERROR]: [ItemsAdder] Failed to generate armor atlas.`

check you have `1_19_3_atlas_support: true`  set to true in IA config.

ERROR]: [ItemsAdder] Failed to load item platinum_leggings. The slot 'leg' is not a valid armor slot. File: /contents/custom/configs/platinum_leggings.yml

It should be `        slot: legs` not `leg`

Also recommended you switch from Spigot to Paper Spigot, a lot more stable and better performance.

**Comment by LoneDev6** [comment]
Probably related to the same error: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2482
Changing `legs` to `leg` should let the plugin load fine.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/ce41635a-f3d8-4c0a-9e56-4ff702688336)


Please stop editing your files manually. Use the official vscode extension.
https://itemsadder.devs.beer/plugin-usage/files-editor
