### ISSUE TITLE
Plugin disables after some minutes in 1.19.4

### ISSUE THREAD

**Issue by Rakise** [PluginBugs/Issues-ItemsAdder#2626]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After every 30-40 minutes when I start the server. The plugin disables itself and gives some errors in console

### Steps to reproduce the issue

1. Start the server
2. Wait some minutes
3. Plugin disables itself

### Server version

Current: git-Purpur-1972 (MC: 1.19.4)

### ItemsAdder Version

Itemsadder version 3.4.1c

### ProtocolLib Version

protocollib version 5.1.0-SNAPSHOT-644

### LoneLibs Version

Lonelibs version 1.0.24

### FULL server log

[18:14:48] [Thread-32/ERROR]: [ItemsAdder] [m[0;31;1mUnexpected I/O error while handling webserver request: [m
[18:14:48] [Thread-32/WARN]: java.net.SocketException: Connection reset
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[18:14:48] [Thread-32/WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[18:14:48] [Thread-32/WARN]: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[18:14:48] [Thread-32/WARN]: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[18:14:48] [Thread-32/WARN]: 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
[18:14:48] [Thread-32/WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[18:14:48] [Thread-32/WARN]: 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[18:14:48] [Thread-32/WARN]: 	at FREE ItemsAdder_3.4.1c.jar//ia.m.jm.run(SourceFile:40)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: java.lang.StackOverflowError
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.im.a(class:4208)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.WireFormat.a(class:2082)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.StringSerializer$STRING.a(class:1654)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.cm.a(class:4853)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.ByteVector.a(class:4934)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.fk.a(class:56)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.Frame.a(class:1585)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.filter.Evaluator.a(class:2003)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.math.fast.CommonsAccurateMath$ExpIntTable.a(class:6206)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider$DateReader.a(class:2378)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.ij.a(class:688)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.path.PathTokenFactory.a(class:4324)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.aK.a(class:410)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.function.ParamType.a(class:6230)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.A.impl.v1_19_R3.a(class:4397)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.kP.a(class:2590)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.d.a(class:276)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.gs.a(class:1052)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.aX.impl.g.a(class:236)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.bX.a(class:6610)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.fI.a(class:5833)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.hO.a(class:4334)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Campfire.Events.RemoveItemFromCampfireEvent.a(class:1798)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.T.a(class:6649)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.aJ.aR.a(class:4401)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.math.fast.SpeedyMath.a(class:2184)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.aV.bM.a(class:2651)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.du.a(class:5179)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.cU.a(class:2691)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.hY.a(class:2474)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.dZ.a(class:4539)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.aU.impl.v1_18_R2.a(class:2405)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.Utils.a(class:3897)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.rwg.RwgCompat.a(class:6168)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.aN.impl.v1_18_R2.a(class:2826)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.eo.a(class:6414)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.InvalidModificationException.a(class:4935)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.net.minidev.json.writer.ArraysMapper$2.a(class:494)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.nbt.NFile.a(class:6410)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.gw.a(class:3157)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.filter.FilterCompiler$1.a(class:6631)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.util.MathArrays$3.a(class:6559)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.nbt.nms.impl.CraftItemStack_v1_19_R3.a(class:3362)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.WireFormat$FieldType$1.a(class:2056)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.path.PredicateContextImpl.a(class:2410)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.Field.a(class:5740)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.iJ.a(class:5467)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.nms.nbt.nms.impl.NBTTagList_v1_18_R2.a(class:5791)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.net.minidev.json.writer.ArraysMapper$16.a(class:1740)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Vault.VaultHook.a(class:4141)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.dD.a(class:3486)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.gF.a(class:3005)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.gb.a(class:4773)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.m.hi.a(class:82)
[19:01:33] [Craft Scheduler Thread - 59 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.Field.a(class:6274)
[19:01:33] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1c
[19:01:33] [Server thread/INFO]: [ItemsAdder] [mSaving custom entities...[m
[19:01:33] [Server thread/INFO]: [ItemsAdder] [mSaved 0 custom entities successfully

**Comment by LoneDev6** [comment]
This log is incomplete, please provide your full log.
