### ISSUE TITLE
Mob fails to load with a NullPointerException

### ISSUE THREAD

**Issue by imh3ro** [PluginBugs/Issues-ItemsAdder#2635]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Hero#4463

### What happened?

When i try to load a mob and reload, it shows an error on console and fails to load the mob. I can use another mob but not this one. I am not sure if it's something about the model but i followed the wiki. 

### Steps to reproduce the issue

1.Put the model files into right plugin folder.
2.Reload the plugin.
3.See the error on console.

### Server version

This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
[14:30:31 ERROR]: [ItemsAdder] Failed to load: aximob:redknight
[14:30:31 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.am.a(SourceFile:247)
[14:30:31 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.am.a(SourceFile:213)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.am.b(SourceFile:149)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.am.k(SourceFile:383)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.X.a(SourceFile:236)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.I.b(SourceFile:1748)
[14:30:31 WARN]:        at ItemsAdder_3.4.1c.jar//ia.m.I.c(SourceFile:577)
[14:30:31 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:30:31 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:30:31 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[14:30:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[14:30:31 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[14:30:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:30:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:30:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
You have an animation with a broken sound. It's strange since it shouldn't really happen.
Check all your animations sounds keyframes to see if any is missing the `name`.

**Comment by imh3ro** [comment]
Yes. That was the issue. It works now. Thanks.
