### ISSUE TITLE
PlayerInteractAtEntityEvent - java.lang.NullPointerException: Cannot read field "a" because "<local4" is null

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2638]
### Discord tag (optional)

DinoBoss#6985

### What happened?

I don't know why I suppose that some configuration that works with the event fails.

### Server version

[03:28:29 INFO]: Checking version, please wait...
[03:28:29 INFO]: Current: git-Purpur-1970 (MC: 1.19.4)*
Previous: git-Purpur-1968 (MC: 1.19.4)
* You are 6 version(s) behind

### ItemsAdder Version

[03:28:00 INFO]: ItemsAdder version 3.4.1c
[03:28:00 INFO]: Customized Minecraft without client mods!
[03:28:00 INFO]: Website: devs.beer
[03:28:00 INFO]: Author: LoneDev

### ProtocolLib Version

[03:28:54 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-636
[03:28:54 INFO]: Provides read/write access to the Minecraft protocol.
[03:28:54 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[03:27:47 INFO]: LoneLibs version 1.0.24
[03:27:47 INFO]: Collection of libs used by my plugins
[03:27:47 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/zB5cy9E#L183

### Error (optional)

```shell
[02:39:01 ERROR]: Could not pass event PlayerInteractAtEntityEvent to ItemsAdder v3.4.1c
java.lang.NullPointerException: Cannot read field "a" because "<local4" is null
at ia.m.ce.f(SourceFile:529) ~[ItemsAdder_3.4.1c.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1970]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1970]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1970]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$6.performInteraction(ServerGamePacketListenerImpl.java:2902) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2957) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:161) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2891) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1970]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
No idea, for some reason someone is interacting with a vehicle which loaded partially.
Check your previous log lines to see if itemsadder printed some other warnings or errors.

**Comment by dinobossytnew** [comment]
ok wait plise
