### ISSUE TITLE
Color water cannot be placed

### ISSUE THREAD

**Issue by 1111qqjzja** [PluginBugs/Issues-ItemsAdder#2639]
### What happened?

Color water cannot be placed,I restart the server it's not working,when I placed the color water the background will report an error

### Server version

This server is running Paper version git-Paper-306 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b07d5e0)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)

### ItemsAdder Version

itemsadder version 3.4.1c

### ProtocolLib Version

protocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

lonelibs version 1.0.24

**Comment by LoneDev6** [comment]
do not post screenshots of errors, always post text.

**Comment by 1111qqjzja** [comment]
[21:29:14] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1cjava.lang.ClassCastException: class com.mojang.serialization.DataResult cannot be cast to class net.minecraft.core.Holder (com.mojang.serialization.DataResult and net.minecraft.core.Holder are in unnamed module of loader java.net.URLClassLoader @5eb5c224)	at ia.nms.aF.impl.v1_19_R1_2.a(SourceFile:96) ~[ItemsAdder_3.4.1c.jar:?]	at ia.nms.aF.impl.v1_19_R1_2.d(SourceFile:82) ~[ItemsAdder_3.4.1c.jar:?]	at ia.m.bQ.e(SourceFile:326) ~[ItemsAdder_3.4.1c.jar:?]	at ia.m.db.a(SourceFile:145) ~[ItemsAdder_3.4.1c.jar:?]	at ia.m.db.k(SourceFile:235) ~[ItemsAdder_3.4.1c.jar:?]	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-306]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:526) ~[?:?]	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1969) ~[?:?]	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-306]	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-306]	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 1111qqjzja** [comment]
https://mclo.gs/wivgC4q

**Comment by 1111qqjzja** [comment]
log

**Comment by LoneDev6** [comment]
Update to 1.19.2-307 or update to 1.19.4.
https://papermc.io/downloads/all
