### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WhiteProject1** [PluginBugs/Issues-ItemsAdder#2646]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

! Batuhan#0101

### What happened?

console error spaming

### Steps to reproduce the issue

I dont know

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/c7ac373c-214a-41a4-ab1d-c6e5d6498ab5)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/586d5351-7434-46e8-8704-bc7f618326db)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/fa149b39-7233-4e4a-8bd2-b60ef0758fa2)

### Error (optional)

```shell
[13:56:27 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NoSuchFieldError: SYSTEM_CHAT
        at ia.m.bi.onPacketSending(SourceFile:292) ~[ItemsAdder_3.4.1c.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib (4).jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib (4).jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1998) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1984) ~[app:?]
        at ia.nms.A.impl.v1_17_R1.a(SourceFile:36) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.nms.A.A.a(SourceFile:44) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.bj.aH(SourceFile:126) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.bf.m(SourceFile:326) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.bf.aF(SourceFile:174) ~[ItemsAdder_3.4.1c.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:56:27 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSetActionBarTextPacket@686a32d4[
    a=TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
  ]
```

**Comment by WhiteProject1** [comment]
updated protocollib my bad sorry
