### ISSUE TITLE
Could not pass event EntityDamageEvent to ItemsAdder v3.4.1c

### ISSUE THREAD

**Issue by Thangsss** [PluginBugs/Issues-ItemsAdder#2657]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Thangss#5555

### What happened?

console errors
https://pastes.dev/ofhElRxbFl

### Steps to reproduce the issue

Sometimes its random when IA tries to do something, or when interacting with a player or AI

### Server version

This server is running Paper version git-Paper-450 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 646f590)
You are 88 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-448 (MC: 1.19.3)

### ItemsAdder Version

3.4.1c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.24

### Error (optional)

```shell
[23:05:17 ERROR]: Could not pass event EntityDamageEvent to ItemsAdder v3.4.1c
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
        at ia.m.bR.a(SourceFile:228) ~[ItemsAdder_3.4.1c.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-450]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-450]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-450]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[paper-1.19.4.jar:git-Paper-450]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1154) ~[paper-1.19.4.jar:git-Paper-450]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1128) ~[paper-1.19.4.jar:git-Paper-450]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964) ~[paper-1.19.4.jar:git-Paper-450]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2148) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
        at net.minecraft.world.entity.animal.Squid.hurt(Squid.java:172) ~[?:?]
        at net.minecraft.world.entity.GlowSquid.hurt(GlowSquid.java:82) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.world.entity.animal.WaterAnimal.handleAirSupply(WaterAnimal.java:53) ~[?:?]
        at net.minecraft.world.entity.animal.WaterAnimal.baseTick(WaterAnimal.java:65) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:779) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2934) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:432) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1210) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:926) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1544) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-450]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
        ... 32 more
```

**Comment by Thangsss** [comment]
I am using the latest version of everything. I updated paper tho, everything seems to be good now. I appreciate the help
