### ISSUE TITLE
ItemsAdder custom entity uses entity name rather than namespace for model path

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#2680]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Andre_601#0601

### What happened?

For unknown reasons is ItemsAdder using the entity name for the model path inside the generated `potion.json` model file.

This only seems to happen with one particular entity (My own) even tho the configuration and model files are all set up properly (See below).

A `/iacleancache items` has been performed already without any success.

### Steps to reproduce the issue

1. Setup an IAEntity (See files below)
2. Create zip with `/iazip`
3. Check resource pack file
4. Notice wrong path in `potion.json` file for the entity

### Server version

[17:11:08 INFO]: This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

[17:11:25 INFO]: ItemsAdder version 3.4.1d
[17:11:25 INFO]: Customized Minecraft without client mods!
[17:11:25 INFO]: Website: devs.beer
[17:11:25 INFO]: Author: LoneDev

### ProtocolLib Version

[17:12:03 INFO]: ProtocolLib version 5.0.0
[17:12:03 INFO]: Provides read/write access to the Minecraft protocol.
[17:12:03 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:12:15 INFO]: LoneLibs version 1.0.24
[17:12:15 INFO]: Collection of libs used by my plugins
[17:12:15 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/OxTqER6

(Note: While I use Nova to host the resource pack, is the `generated.zip` file already having the wrong path applied)

### Error (optional)

```shell
May or may not be related:

[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/ERROR]: [ItemsAdder] [m[0;31;1mFailed to load: iainternal:player[m
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.I.a(SourceFile:2918)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.am.a(SourceFile:109)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.am.b(SourceFile:71)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.X.a(SourceFile:185)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.X.u(SourceFile:319)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at ItemsAdder_3.4.1d.jar//ia.m.I.a(SourceFile:2321)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:42:56] [Craft Scheduler Thread - 6 - ItemsAdder/ERROR]: [ItemsAdder] [m[0;31;1mFailed to read player animation data. player model is null.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: fox_backpack
items:
  red_fox_backpack_item:
    display_name: "Red Fox Backpack"
    resource:
      material: IRON_HORSE_ARMOR
      generate: false
      model_path: item/red_fox_backpack_item.json
  snow_fox_backpack_item:
    display_name: "Snow Fox Backpack"
    resource:
      material: IRON_HORSE_ARMOR
      generate: false
      model_path: item/white_fox_backpack_item.json
entities:
  red_fox_backpack: # <-- This name is somehow used for the file path.
    display_name: "Red Fox Backpack"
    type: ZOMBIE
    model_folder: "entity/red_fox"
    silent: true
    can_sun_burn: false
    speed:
      movement: 1
      flying: 0
    max_health: 20
  snow_fox_backpack:
    display_name: "Snow Fox Backpack"
    type: ZOMBIE
    model_folder: "entity/white_fox"
    silent: true
    can_sun_burn: false
    speed:
      movement: 1
      flying: 0
    max_health: 20
```

### Other files, you can drag and drop them here to upload. (optional)

The faulty potion.json file (Search `fox_backpack` to find it):
https://paste.helpch.at/ucifikunet.json

**Comment by Andre601** [comment]
Also, to clarify did I try it with a different entity name (red_fox_backpack_entity) without any luck. The name is still used within the resource path.

And to cofirm it's really a broken path did I do a simple find-replace in the generated.zip's potion.json by replacing the `red_fox_backpack_entity` with `red_fox` and `snow_fox_backpack_entity` with `white_fox`, followed by a recreation of the final RP in Nova, whoch showed the models as they should.

And as mentioned before are other models unaffected by this somehow...

**Comment by LoneDev6** [comment]
> A `/iacleancache items` has been performed already without any success.

Seems the error is related to a bug with the `/iacleancache items` command: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2666

About the entity not applying the correct path I don't know. Make sure your files structure is correct. Refer to my example entities.

**Comment by Andre601** [comment]
The file structure is right as I use the Blockbench plugin to export the files. And I made sure the folders do have the right names applied, which they do.

However! There is one minor bug that annoys me (And that I haven't reported yet, but probs will), which is, that f.e. a export with `fox_backpack` as namespace and `red_fox` as name puts texture paths always to `fox_backpack:entity/red_fox/...` even if textures have a separate folder.

As an example, one texture I have is `entity/backpack/backpack.png`, which is also imported into BlockBench as such, yet the export creates a JSON file with `fox_backpack:entity/red_fox/backpack` as the path, forcing me to manually edit it.

(tl;dr the BB plugin ignores paths used for texture files and applies some that make no sense)

**Comment by Andre601** [comment]
I posted it on Discord, but I'll post it here too.
The folder structure when opening the contents folder is this for the fox_backpack:
```
fox_backpack/
├── configs/
│   └── fox_backpack.yml
└── resourcepack/
    └── assets/
        └── fox_backpack/
            ├── models/
            │   ├── entity/
            │   │   ├── red_fox/
            │   │   │   └── ... <ia entity items>
            │   │   └── white_fox/
            │   │       └── ... <ia entity items>
            │   └── item/
            │       ├── red_fox_backpack_item.json
            │       └── white_fox_backpack_item.json
            └── textures/
                └── entity/
                    ├── backpack/
                    │   ├── backpack.png
                    │   └── backpack_straps.png
                    ├── red_fox/
                    │   ├── head.png
                    │   ├── head.png.mcmeta
                    │   ├── legs.png
                    │   └── tail.png
                    └── white_fox/
                        ├── head.png
                        ├── head.png.mcmeta
                        ├── legs.png
                        └── tail.png
```
The files inside the entity directories do have the right texture paths applied (except for the above mentioned issue, which a manual fix works).

They just aren't applied properly during the resource pack creation having the entity name applied for the path rather than the namespace itself, so IA for whatever reason picks up the entity name rather than the namespace defined for these files...

**Comment by LoneDev6** [comment]
Send me on Discord your bbmodel model file of the entity which doesn't load correctly

**Comment by LoneDev6** [comment]
Yea, it's caused by this shit, since you really are not supposed to set different names from the entity itself and the model folder.
`modelPath = getNamespace() + ":entity/" + entityModel.getId() + "/" + id;`

I'll fix this, but generally you should avoid that since it can cause confusion of where the models for an entity are.
