### ISSUE TITLE
Breaking custom block will fire the PlayerItemBreakEvent wrongly

### ISSUE THREAD

**Issue by iamyou** [PluginBugs/Issues-ItemsAdder#2687]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Breaking custom block will fire the PlayerItemBreakEvent wrongly

### Steps to reproduce the issue

1. making a test plugin to listen the PlayerItemBreakEvent
2. placing a custom block and break it using tools

### Server version

git-Purpur-1972 (MC: 1.19.4)*

### ItemsAdder Version

3.4.1c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.24

### Error (optional)

```shell
java.lang.RuntimeException: Test exception
        at io.github.iamyou.testplugin.TestPlugin.onItemBreak(TestPlugin.java:25) ~[TestPlugin-1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor47.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1972]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at ia.m.kO.a(SourceFile:68) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.er.a(SourceFile:472) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.er.a(SourceFile:449) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.er.a(SourceFile:376) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.er.a(SourceFile:370) ~[ItemsAdder_3.4.1c.jar:?]
        at ia.m.cr.bc(SourceFile:207) ~[ItemsAdder_3.4.1c.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1972]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by iamyou** [comment]
Will causing #2219 because of https://github.com/Sefiraat/SlimeTinker/blob/2b6eeb317d61cc6fe387cc1ddd90c5380f75720d/src/main/java/io/github/sefiraat/slimetinker/listeners/DurabilityListener.java#L88

**Comment by LoneDev6** [comment]
Thanks for the details.
I somehow made a mistake and called `PlayerItemBreakEvent` instead of `PlayerItemDamageEvent`.
