### ISSUE TITLE
Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e 

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#2702]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DOGE#1690

### What happened?

Error again appeared in a console 

### Steps to reproduce the issue

Go to console and see this error
Happens when i dont expect it, when i reload the plugin i dont see any errors, Ill send a reload log in "other files" graph

### Server version

git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.4.1e

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11649299/latest.log)
in latest log you can see this error and here is a log from yesterday (04.06.23) just in case you will need it, there is kinda similar error, dont know why they keep appearing
[2023-06-04-8.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11649305/2023-06-04-8.log)

### Error (optional)

```shell
[02:36:28 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.4.1e
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
	at net.minecraft.core.NonNullList.get(NonNullList.java:44) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.block.CraftCampfire.getItem(CraftCampfire.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at ia.m.ie.a(SourceFile:246) ~[ItemsAdder_3.4.1e.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:229) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1843) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

[09:27:06 INFO]: [ItemsAdder] [m[0;33;1mReloading...[m
[09:27:06 INFO]: [ItemsAdder] [m[0;36;1m[Host] Stopped self-host webserver on port: 6328[m
[09:27:06 INFO]: [ItemsAdder] [m[0;36;1m[Host] Starting self-host webserver on port: 6328[m
[09:27:06 INFO]: [ItemsAdder] [m[0;36;1m[Pack] Extracting internal contents from .jar[m
[09:27:06 INFO]: [ItemsAdder] [m[0;32;1m[Pack] DONE extracting internal contents from .jar[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mLoaded [0;36;1m1055[0;33;1m items[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m7[0;33;1m/[0;36;1m188[0;33;1m REAL block IDs[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m30[0;33;1m/[0;36;1m750[0;33;1m REAL_NOTE block IDs[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m4[0;33;1m/[0;36;1m63[0;33;1m REAL_TRANSPARENT block IDs[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m127[0;33;1m REAL_WIRE block IDs[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m0[0;33;1m/[0;36;1m14[0;33;1m FIRE block IDs[m
[09:27:07 INFO]: [ItemsAdder] [m[0;33;1mUsed [0;36;1m566[0;33;1m/[0;36;1m6608[0;33;1m font_images[m
[09:27:07 INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded [0;36;1m35[0;33;1m categories[m
[09:27:07 INFO]: [ItemsAdder] [m[0;32;1m[Init] Loaded successfully in [0;36;1m659ms[m
[09:27:07 INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url... [m
[09:27:07 INFO]: [ItemsAdder] [m[0;32;1m[Pack] Resourcepack URL (self-host): http://37.230.162.139:6328/generated.zip[m
[09:27:07 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[09:27:07 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[09:27:07 INFO]: [ItemsAdder] [mReloading ItemsAdder Custom Entities Citizens NPCs[m
[09:27:07 WARN]: [BeautyQuests] Citizens has been reloaded whereas it is highly not recommended for plugins compatibilities. Unexpected behaviors may happen.

**Comment by WataLaker37821** [comment]
It's an error that i reported in a previous plugin version, i really wonder why it could appear, maybe cos of some content i added...

**Comment by WataLaker37821** [comment]
okay, ill disable it until then, thank you for your great work on a plugin!
