### ISSUE TITLE
Unhandled exception number 1024 occurred in onPacketSending(PacketEvent) for ItemsAdder

### ISSUE THREAD

**Issue by bluebombies** [PluginBugs/Issues-ItemsAdder#2733]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

StudyingArchitecture#8511

### What happened?

everytime i do iareload or iazip (and even when the server start up) , this error appear on console

### Steps to reproduce the issue

1. start up the server or do /iareload /iazip

### Server version

This server is running Mohist version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.9)

### ItemsAdder Version

ItemsAdder version 3.4.1f2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-649

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11715342/latest.1.log)

### Error (optional)

```shell
[17:24:31 ERROR]: [ItemsAdder] Unhandled exception number 1024 occurred in onPacketSending(PacketEvent) for ItemsAdder
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?] {}
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:245) ~[?:?] {}
        at ia.m.ay.onPacketSending(SourceFile:26) ~[?:?] {}
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?] {}
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?] {}
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?] {}
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?] {}
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[?:?] {}
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[?:?] {}
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?] {}
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[?:?] {}
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[?:?] {}
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?] {}
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?] {}
        at net.minecraft.network.Connection.m_129520_(Connection.java:211) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,re:mixin}
        at net.minecraft.network.Connection.m_129514_(Connection.java:192) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,re:mixin}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9831_(ServerGamePacketListenerImpl.java:1552) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:mixin,re:classloading,pl:mixin:APP:cpm.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:plasmovoice.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_141995_(ServerGamePacketListenerImpl.java:1539) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:mixin,re:classloading,pl:mixin:APP:cpm.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:plasmovoice.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:A,re:mixin,re:mixin,re:mixin,re:mixin}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1021) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:964) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin}
```

**Comment by LoneDev6** [comment]
Try with Spigot or Paper and let me know if the issue still persists.
You're using an unofficial fork of Spigot, this might be a Mohist bug.
