### ISSUE TITLE
2x2 Crafting Recipe Breaks On Specific Pattern

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2736]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

One very specific config of a recipe pattern throws an error in console and does not load the crafting recipe. I have attached both the working and not working pattern.

I am running a modified version of [Builder's Basics for ItemsAdder](https://www.spigotmc.org/resources/blocks-builders-basics-for-itemsadder.78339/), and have also provided a pastebin for the whole file.

### Steps to reproduce the issue

1. Copy working .yml for item
2. /iareload
3. Everything works
4. Copy broken .yml for item
5. /iareload
6. Error in console.

### Server version

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-1769 (MC: 1.19.2)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.4.1f2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

https://pastebin.com/fBiEasQE

### Error (optional)

```shell
[20:07:08 ERROR]: [ItemsAdder] Error loading recipe: buildersbasics:chisel_0. Please check shape characters and materials. You may have missed one or used a wrong character
[20:07:08 WARN]: java.lang.IllegalArgumentException: Symbol does not appear in the shape: [i]
[20:07:08 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:180)
[20:07:08 WARN]:        at org.bukkit.inventory.ShapedRecipe.setIngredient(ShapedRecipe.java:179)
[20:07:08 WARN]:        at ItemsAdder_3.4.1f2.jar//ia.m.fo.a(SourceFile:67)
[20:07:08 WARN]:        at ItemsAdder_3.4.1f2.jar//ia.m.fo.a(SourceFile:35)
[20:07:08 WARN]:        at ItemsAdder_3.4.1f2.jar//ia.m.eZ.a(SourceFile:27)
[20:07:08 WARN]:        at ItemsAdder_3.4.1f2.jar//ia.m.eZ.a(SourceFile:38)
[20:07:08 WARN]:        at ItemsAdder_3.4.1f2.jar//ia.m.G.a(SourceFile:2411)
[20:07:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:07:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[20:07:08 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1510)
[20:07:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[20:07:08 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[20:07:08 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
[20:07:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[20:07:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: buildersbasics
items:
  chisel:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.buildersbasics.chisel\"}'}}"
    #display_name: Chisel
    permission: buildersbasics
    durability:
      max_custom_durability: 200
    resource:
      material: STONE_SWORD
      generate: true
      textures:
      - item/chisel.png
recipes:
  crafting_table:       
    chisel:
      permission: buildersbasics
      enabled: true
      pattern:
      - XXI
      - XSX
      ingredients:
        S: STICK
        I: IRON_INGOT
      result:
        item: buildersbasics:chisel
        amount: 1
```

### Other files, you can drag and drop them here to upload. (optional)

Working config:

info:
  namespace: buildersbasics
items:
  chisel:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.buildersbasics.chisel\"}'}}"
    #display_name: Chisel
    permission: buildersbasics
    durability:
      max_custom_durability: 200
    resource:
      material: STONE_SWORD
      generate: true
      textures:
      - item/chisel.png
recipes:
  crafting_table:       
    chisel:
      permission: buildersbasics
      enabled: true
      pattern:
      - XIX
      - SXX
      ingredients:
        S: STICK
        I: IRON_INGOT
      result:
        item: buildersbasics:chisel
        amount: 1

Whole .yml - https://pastebin.com/Z8LrMEe9

**Comment by LoneDev6** [comment]
Will be checked, thanks
