### ISSUE TITLE
mythicmobs itemsadder error :D

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2739]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dinobossyt

### What happened?

First I will say that I started to test the ia with mythicmobs as soon as I put the mythicmobs because it began to give this error when starting the server.

### Steps to reproduce the issue

first step is to download the latest version of ia.
second download all its dependencies.
last download mythicmobs debuild latest stable version.

### Server version

[11:12:41 INFO]: Checking version, please wait...
[11:12:42 INFO]: Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Paper-549 (MC: 1.19.4)
* You are running the latest version

### ItemsAdder Version

[11:12:32 INFO]: ItemsAdder version 3.5.0
[11:12:32 INFO]: Customized Minecraft without client mods!
[11:12:32 INFO]: Website: devs.beer
[11:12:32 INFO]: Author: LoneDev

### ProtocolLib Version

[11:12:17 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-652
[11:12:17 INFO]: Provides read/write access to the Minecraft protocol.
[11:12:17 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[11:11:40 INFO]: LoneLibs version 1.0.25
[11:11:40 INFO]: Collection of libs used by my plugins
[11:11:40 INFO]: Authors: LoneDev and others

### FULL server log

https://bin.bloom.host/agugitopeb.yaml

### Error (optional)

```shell
https://bin.bloom.host/uxiwineqoh.properties
```

**Comment by evilsaloon** [comment]
+1, same issue on latest stable MythicMobs 5.3.0-8e98a03c, IA 3.5.0, LL 1.0.25, Purpur 1995 (1.20.1)

**Comment by LoneDev6** [comment]
This is a bug of MythisMobs.
The error is triggered by `/mythicmobs reload` command.

`NoSuchMethodError: 'io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor.nearestColorTo(java.util.List, io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor)'
`

```
Caused by: java.lang.NoSuchMethodError: 'io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor.nearestColorTo(java.util.List, io.lumine.mythic.bukkit.utils.adventure.text.format.TextColor)'
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.toLegacyCode(LegacyComponentSerializerImpl.java:186) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.access$300(LegacyComponentSerializerImpl.java:52) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:343) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$StyleState.applyFullFormat(LegacyComponentSerializerImpl.java:432) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$StyleState.applyFormat(LegacyComponentSerializerImpl.java:411) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:329) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$2(ComponentFlattenerImpl.java:114) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:92) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:97) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:97) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:271) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.text.Text.toLegacy(Text.java:118) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.text.Text.sendMessage(Text.java:154) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.commands.CommandHelper.sendSuccess(CommandHelper.java:28) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.commands.ReloadCommand.onCommand(ReloadCommand.java:45) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.commands.Command.onCommand(Command.java:64) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at io.lumine.mythic.bukkit.utils.commands.Command.onCommand(Command.java:55) ~[MythicMobs-5.3.0-SNAPSHOT (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]

```
