### ISSUE TITLE
Could not pass event InventoryClickEvent to LoneLibs v1.0.25

### ISSUE THREAD

**Issue by boringwolf** [PluginBugs/Issues-ItemsAdder#2743]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

boringwolf#0905

### What happened?

When click on the /ia menu, it report the error in the console.

seems the functions are work good, but the error is annoying

### Steps to reproduce the issue

1. /ia
2. click the category
3. click the items
4. start spam error in the console.

### Server version

This server is running Paper version git-Paper-22 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f7b386d)

### ItemsAdder Version

[16:49:19 INFO]: ItemsAdder version 3.5.0
[16:49:19 INFO]: Customized Minecraft without client mods!
[16:49:19 INFO]: Website: devs.beer
[16:49:19 INFO]: Author: LoneDev

### ProtocolLib Version

[16:51:44 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-652
[16:51:44 INFO]: Provides read/write access to the Minecraft protocol.
[16:51:44 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:49:36 INFO]: LoneLibs version 1.0.25
[16:49:36 INFO]: Collection of libs used by my plugins
[16:49:36 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11763147/latest.log)

### Error (optional)

```shell
[16:42:19 INFO]: CP_boringwolf issued server command: /ia
[16:42:38 ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
java.lang.IllegalArgumentException: lines (4) must be lower than 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1018) ~[paper-1.20.1.jar:git-Paper-22]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1007) ~[paper-1.20.1.jar:git-Paper-22]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1002) ~[paper-1.20.1.jar:git-Paper-22]
        at ia.m.id.bT(SourceFile:120) ~[ItemsAdder_3.5.0.jar:?]
        at ia.m.hX.O(SourceFile:460) ~[ItemsAdder_3.5.0.jar:?]
        at ia.m.hX.c(SourceFile:355) ~[ItemsAdder_3.5.0.jar:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs.jar:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-22]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-22]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3197) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Will be checked, thanks

**Comment by boringwolf** [comment]
After several test, I found that one of the problem is from clicking search button.
