### ISSUE TITLE
1.20.1 WorldGuard error

### ISSUE THREAD

**Issue by matyasvane** [PluginBugs/Issues-ItemsAdder#2767]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sinfilex

### What happened?

When clicking on the ground, an error is written to the console

### Steps to reproduce the issue

1. Download latest version 1.20.1
2. Download latest ItemsAdder (with Libs)
3. Download latest WorldGuard
4. Join to server and click to ground

### Server version

[15:36:54 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-15148 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 0eb75ac on paper_upstream)
Unknown version
Previous version: git-SlimeWorldManager-15076 (MC: 1.19.4)

### ItemsAdder Version

Previous version: git-SlimeWorldManager-15076 (MC: 1.19.4)
[15:37:15 INFO]: ItemsAdder version 3.5.0
[15:37:15 INFO]: Customized Minecraft without client mods!
[15:37:15 INFO]: Website: devs.beer
[15:37:15 INFO]: Author: LoneDev

### ProtocolLib Version

[15:37:31 INFO]: ProtocolLib version 5.0.0
[15:37:31 INFO]: Provides read/write access to the Minecraft protocol.
[15:37:31 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:37:47 INFO]: LoneLibs version 1.0.25
[15:37:47 INFO]: Collection of libs used by my plugins
[15:37:47 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[15:38:14 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.5.0
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at dev.lone.itemsadder.Core.OtherPlugins.ProtectionPlugins.WorldGuardFlagsManager.testBlockFlag(SourceFile:113) ~[ItemsAdder_3.5.0 (1).jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.ProtectionPlugins.ProtectionPlugins.canInteract_block(SourceFile:274) ~[ItemsAdder_3.5.0 (1).jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.ProtectionPlugins.ProtectionPlugins.canInteract_placedBlock(SourceFile:232) ~[ItemsAdder_3.5.0 (1).jar:?]
        at ia.m.ck.d(SourceFile:731) ~[ItemsAdder_3.5.0 (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-15148]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1354) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1331) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1324) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1302) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1190) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15148]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 29 more
```

**Comment by LoneDev6** [comment]
Check that you're running the latest WorldGuard jar.
