### ISSUE TITLE
IllegalArgumentException: lines (4) must be lower than 4

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2788]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dinobossyt

### What happened?

I installed the latest version of IA to my test server and it crashed with lonelibs when I clicked on the /ia search engine i.e. the item sign.

### Steps to reproduce the issue

step 1 install itemsadder latest stable version.
step 2 Install dependencies.
step 3 login to the server.
step 4 use /ia
step 5 click on the item sign to search for 1 model.

### Server version

[18:05:36 INFO]: Checking version, please wait...
[18:05:37 INFO]: Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Paper-549 (MC: 1.19.4)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
>

### ItemsAdder Version

[18:05:45 INFO]: ItemsAdder version 3.5.0b
[18:05:45 INFO]: Customized Minecraft without client mods!
[18:05:45 INFO]: Website: devs.beer
[18:05:45 INFO]: Author: LoneDev

### ProtocolLib Version

[18:06:02 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-652
[18:06:02 INFO]: Provides read/write access to the Minecraft protocol.
[18:06:02 INFO]: Authors: dmulloy2 and comphenix
>

### LoneLibs Version

> ver lonelib
[17:55:44 INFO]: LoneLibs version 1.0.25
[17:55:44 INFO]: Collection of libs used by my plugins
[17:55:44 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/nvgxXLZ

### Error (optional)

```shell
[17:55:11 ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
java.lang.IllegalArgumentException: lines (4) must be lower than 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1023) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1012) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1007) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at ia.m.id.bT(SourceFile:120) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.O(SourceFile:460) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.c(SourceFile:355) ~[ItemsAdder_3.5.0b.jar:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs.jar:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3294) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:55:11 ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
java.lang.IllegalArgumentException: lines (4) must be lower than 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1023) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1012) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1007) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at ia.m.id.bT(SourceFile:120) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.O(SourceFile:460) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.c(SourceFile:355) ~[ItemsAdder_3.5.0b.jar:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs.jar:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3294) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
[17:55:11 ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
java.lang.IllegalArgumentException: lines (4) must be lower than 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1023) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1012) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1007) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at ia.m.id.bT(SourceFile:120) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.O(SourceFile:460) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.c(SourceFile:355) ~[ItemsAdder_3.5.0b.jar:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs.jar:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3294) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:55:11 ERROR]: Could not pass event InventoryClickEvent to LoneLibs v1.0.25
java.lang.IllegalArgumentException: lines (4) must be lower than 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:193) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1023) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1012) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendSignChange(CraftPlayer.java:1007) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at ia.m.id.bT(SourceFile:120) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.O(SourceFile:460) ~[ItemsAdder_3.5.0b.jar:?]
        at ia.m.hX.c(SourceFile:355) ~[ItemsAdder_3.5.0b.jar:?]
        at fr.mrmicky.fastinv.FastInv.handleClick(FastInv.java:316) ~[LoneLibs.jar:?]
        at fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(FastInvManager.java:50) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3294) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
I can't reproduce the issue, works fine on both Purpur and Spigot latest version.
