### ISSUE TITLE
Paper - crash after sitting and closing client

### ISSUE THREAD

**Issue by BerndPixel** [PluginBugs/Issues-ItemsAdder#2808]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Good day to all, 

unfortunately I have a very unpleasant bug with ItemsAdder. After I had added seating options (benches), was still in the 1.19.3, there it still worked, it came since a few days to server crashes. These are caused when players sit on these benches and close their client, then the server crashes with a crash report. 

This problem exists only since the 1.20.1. As I said, with the 1.19.3/1.19.4 it worked flawlessly.

### Steps to reproduce the issue

1) Player sits down on a bench of ItemsAdder
2) Player closes the client
3) Server crashes

### Server version

This server is running Paper version git-Paper-45 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b169678)

### ItemsAdder Version

ItemsAdder version 3.5.0b

### ProtocolLib Version

ProtocolLib version 5.1.0-Snapshot-654

### LoneLibs Version

LoneLibs version 1.0.25

### Error (optional)

```shell
-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-
Time: 2023-06-23 18:42:35
Description: Exception in server tick loop

java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66)
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4712)
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4697)
	at net.minecraft.server.players.PlayerList.lambda$remove$2(PlayerList.java:639)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:584)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2102)
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:818)
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
	at java.base/java.lang.Thread.run(Thread.java:833)

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-

[18:42:35] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4712) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4697) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.players.PlayerList.lambda$remove$2(PlayerList.java:639) ~[paper-1.20.1.jar:git-Paper-45]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:584) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2102) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Please post your full server log.
If you are using ViaVersion and ViaBackwards make sure to update them.
Also update ProtocolLib.

**Comment by jeongys1019** [comment]
Many servers are attack... in 1.20.1 server @LoneDev6

**Comment by LoneDev6** [comment]
> Many servers are attack..

What do you mean? I don't understand.

**Comment by BerndPixel** [comment]
ProtocolLib, ViaVersion and ViaBackwards are now up to date, but still the same problem. I would like to open a ticket with you in DC, but there is no such thing. I am always so critical when posting logs.

**Comment by LoneDev6** [comment]
>  These are caused when players sit on these benches and close their client, then the server crashes with a crash report.

Which benches?

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
Try updating:
- server
- ViaVersion (if you have it)
- ViaBackwards (if you have it)
- ProtocolLib

Remove any other plugin if updating doesn't work and find out which one is causing the issue.

Tested on:
`Purpur version git-Purpur-2001 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8331f1b on HEAD)`

`ItemsAdder v3.5.0b`
`ViaVersion version 4.7.1-SNAPSHOT`
`ViaBackwards version 4.7.1-SNAPSHOT`
`ProtocolLib version 5.1.0-SNAPSHOT-652`

Also tested on 
`CraftBukkit version 3811-Spigot-c62f4bd-85b89c3 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)`


config:
```yml
info:
  namespace: git_2808
items:
  chair_test:
    enabled: true
    display_name: chair_test
    resource:
      generate: false
      model_path: minecraft:block/emerald_block
      material: PAPER
    behaviours:
      furniture:
        enabled: true
      furniture_sit:
        sit_height: 1
```

**Comment by BerndPixel** [comment]
I have written specifically when someone sits and closes the client, not just gets off the furniture or something else. That's why you can't reproduce this. 

1. Player sits down on a bench of ItemsAdder
2. Player closes the client
3. Server crashes

And as I said, everything is now updated and more is not possible. 
Can't you read anything on the error code there?

**Comment by jeongys1019** [comment]
still have problems @LoneDev6

**Comment by LoneDev6** [comment]
It's a Paper bug.
Please report it to Paper developers.

This happens if a player quits the server while riding an armorstand and joins right after.

I tested and doesn't happen on Spigot.
I can't do anything about that since it's not a bug of the plugin itself.

**Comment by spookymgmt** [comment]
> It's a Paper bug. Please report it to Paper developers.
> 
> This happens if a player quits the server while riding an armorstand and joins right after.
> 
> I tested and doesn't happen on Spigot. I can't do anything about that since it's not a bug of the plugin itself.

Paper already had a patch for this. How do I disable players from sitting on furniture on my server? The world guard flags arent working and my server keeps crashing.

**Comment by LoneDev6** [comment]
> Paper already had a patch for this.

Well seems not as you said it keeps crashing, report it to Paper devs.
This happens if a player quits the server while riding an armorstand and joins right after.
I tested and doesn't happen on Spigot. I can't do anything about that since it's not a bug of the plugin itself.

> I need some type of way to mass disable all furniture.

Remove the furniture behaviour from all your items configurations.

**Comment by spookymgmt** [comment]
plugin dev could fix it by removing the player from riding the entity on logout

**Comment by spookymgmt** [comment]
can you do the above? Paper isn't going to fix it, they're claiming it's a bug with itemsadder.

**Comment by DxrkCat** [comment]
same problem

**Comment by DxrkCat** [comment]
![изображение](https://github.com/PluginBugs/Issues-ItemsAdder/assets/124828932/80d3fb62-2560-4a60-b6fa-23917c723571)
The code that fixes this problem.
@spookymgmt @jeongys1019 @BerndPixel

**Comment by LoneDev6** [comment]
> plugin dev could fix it by removing the player from riding the entity on logout

I don't want to remove players from vehicles.
Imagine a player flying with a vehicle. I don't want them to fall on join.

**Comment by DxrkCat** [comment]
> > plugin dev could fix it by removing the player from riding the entity on logout
> 
> I don't want to remove players from vehicles. Imagine a player flying with a vehicle. I don't want them to fall on join.

What is an alternative solution Paper, Purpur, Pufferfish other forks developers some ignored, and some said it was a plugin problem.

**Comment by LoneDev6** [comment]
It's a Paper bug.
Please report it to Paper developers.

This happens if a player quits the server while riding an armorstand and joins right after.

I tested and doesn't happen on Spigot.
I can't do anything about that since it's not a bug of the plugin itself.

Since the bug happens only on Paper and in the stacktrace there is no trace of ItemsAdder it's an issue of Paper itself.
Ask them to fix it, I can't do much about that since the bugged code is their implementation of `EntityScheduler` as clearly shown in the error.

**Comment by spookymgmt** [comment]
> 

Joining has nothing to do with this, it's only on leave.

**Comment by LoneDev6** [comment]
I'll do some tests and implement a workaround.

Anyway I see no reason for Paper to smash my balls because the entity (somehow) is already removed when I call the remove remove, it should just fail silently like Spigot is doing.

**Comment by LoneDev6** [comment]
I can't find a way to bypass this issue.
I contacted Paper developers with a valid simple code to reproduce the issue proving it has nothing to do with ItemsAdder itself.
https://github.com/PaperMC/Paper/issues/9420
