### ISSUE TITLE
sit and quit crash bug 

### ISSUE THREAD

**Issue by jeongys1019** [PluginBugs/Issues-ItemsAdder#2816]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sik1019

### What happened?

#2808 same error 

When you exit the game while sitting down, bukkit crush

plz test your server 

### Steps to reproduce the issue

**

### Server version

the server is runnig  paper version git-paper-43 (MC:1.20.1) (Implementing API version 1.20.1-R0.1-SAPSHOT) (Git: 3756f5b)

### ItemsAdder Version

3.5.0-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-654

### LoneLibs Version

1.0.25

### FULL server log

[15:21:22] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4712) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4697) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.players.PlayerList.lambda$remove$2(PlayerList.java:639) ~[paper-1.20.1.jar:git-Paper-43]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:584) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2102) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:815) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:21:23] [Server thread/ERROR]: This crash report has been saved to: C:\Users\home\Desktop\20230623\.\crash-reports\crash-2023-06-26_15.21.23-server.txt
[15:21:23] [Server thread/INFO]: Stopping server

### Problematic items yml configuration file (optional)

```shell
*
```

### Other files, you can drag and drop them here to upload. (optional)

*

### Screenshots/Videos (you can drag and drop files or paste links)

*

**Comment by jeongys1019** [comment]
viaverstion x

**Comment by LoneDev6** [comment]
This is a duplicate issue of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2808
Please do not open duplicate issues.

It will be handled at soon as possible.
