### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by L0stedMrlion** [PluginBugs/Issues-ItemsAdder#2842]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Mrlion#4679

### What happened?

Error after setting drops from grass

### Steps to reproduce the issue

I tried test my drop from block grass as i set in grass.yml and i got error.

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/87368344/921ba682-1734-4f17-84fc-9fee6778ec8e)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/87368344/db60670f-64ef-4920-ad1a-717736e0417e)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/87368344/23784a23-ed4b-49a9-9bfe-dbf4ce28c45b)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/87368344/b74b2223-5ad4-4788-a50e-10e7168d6ba6)

### FULL server log

[latest(4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11935614/latest.4.log)

### Error (optional)

```shell
[12:00:57 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v3.5.0c
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:322) ~[?:?]
        at ia.m.eI.b(SourceFile:107) ~[ ItemsAdder_3.5.0c.jar:?]
        at ia.m.eI.a(SourceFile:123) ~[ ItemsAdder_3.5.0c.jar:?]
        at ia.m.eI.a(SourceFile:97) ~[ ItemsAdder_3.5.0c.jar:?]
        at ia.m.eS.b(SourceFile:81) ~[ ItemsAdder_3.5.0c.jar:?]
        at ia.m.eL.a(SourceFile:105) ~[ ItemsAdder_3.5.0c.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1980]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:274) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1953) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1980]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
 namespace: lionsproject
loots:
  blocks:
    grass:
      type: GRASS
      items:
        grass:
          item: lionsproject:tomato_seeds
          max_amount: 1
          min_amount: 2
          chance: 70.0
        grass2:
          item: lionsproject:lettuce_seeds
          max_amount: 1
          min_amount: 2
          chance: 70.0
        grass3:
          item: lionsproject:pepper_seeds
          max_amount: 1
          min_amount: 2
          chance: 70.0
        grass4:
          item: lionsproject:garlic_seeds
          max_amount: 1
          min_amount: 2
          chance: 70.0
```

### Other files, you can drag and drop them here to upload. (optional)

x

### Screenshots/Videos (you can drag and drop files or paste links)

x

**Comment by LoneDev6** [comment]
You inverted max and min amount.
