### ISSUE TITLE
Could not pass event ArmorEquipEvent to ItemsAdder v3.5.0c-r2

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#2847]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

idk

### Steps to reproduce the issue

I don't know exactly how to reproduce this issue
**edit**
It happens when someone die

### ItemsAdder Version

v3.5.0c-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-654

### LoneLibs Version

1.0.25

### Error (optional)

```shell
[16:33:56 ERROR]: Could not pass event ArmorEquipEvent to ItemsAdder v3.5.0c-r2
java.lang.NullPointerException: Cannot invoke "dev.lone.LoneLibs.armorequip.ArmorType.ordinal()" because "<parameter1>" is null
        at ia.m.jI.a(SourceFile:1419) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dX.a(SourceFile:93) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dX.a(SourceFile:51) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at dev.lone.LoneLibs.armorequip.ArmorListener.playerDeathEvent(ArmorListener.java:270) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1146.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:934) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:979) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1573) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1006) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1165) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.warden.SonicBoom.lambda$tick$2(SonicBoom.java:68) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.warden.SonicBoom.tick(SonicBoom.java:57) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.world.entity.ai.behavior.warden.SonicBoom.canStillUse(SonicBoom.java:17) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:77) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:445) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:390) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.customServerAiStep(Warden.java:305) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:966) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3448) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:704) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3103) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:460) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.tick(Warden.java:268) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1572) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by DexterSK** [comment]
Ok it happens when someone die

**Comment by LoneDev6** [comment]
Will be checked

**Comment by DexterSK** [comment]
hello, there are still this error in R3

```[17:53:01 ERROR]: Could not pass event ArmorEquipEvent to ItemsAdder v3.5.0c-r3
java.lang.NullPointerException: Cannot invoke "dev.lone.LoneLibs.armorequip.ArmorType.ordinal()" because "<parameter1>" is null
        at ia.m.jI.a(SourceFile:1419) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at ia.m.dX.a(SourceFile:93) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at ia.m.dX.a(SourceFile:51) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2011]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at dev.lone.LoneLibs.armorequip.ArmorListener.playerDeathEvent(ArmorListener.java:270) ~[LoneLibs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1136.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2011]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:936) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:979) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1563) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1006) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1165) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:226) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:217) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by LoneDev6** [comment]
Do not report issues on closed issue pages.
