### ISSUE TITLE
IA disabling itself randomly with big stacktrace

### ISSUE THREAD

**Issue by moonies44** [PluginBugs/Issues-ItemsAdder#2859]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Plugin seems to be disabling itself mid-server, when playing or running commands, or when the server has been online for a while.

### Steps to reproduce the issue

Its not reproducable when i want. Turn on the server and it works, then the plugin seems to die 

### Server version

git-purpur-1930 MC (1.19.3)

### ItemsAdder Version

Version 3.5.0c-r2

### ProtocolLib Version

Version 5.1.0 SNAPSHOT 660

### LoneLibs Version

Version 1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11995894/latest.log)

### Error (optional)

```shell
[14:53:26] [Server thread/INFO]: moonstah issued server command: /ia
[14:53:30] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image. Check ia_gui.yml, attribute: [0;36;1msettings.category_view.font_image.name[m
[14:53:32] [Server thread/INFO]: moonstah issued server command: /ci
[14:53:33] [Server thread/INFO]: moonstah issued server command: /ia
[14:53:35] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image. Check ia_gui.yml, attribute: [0;36;1msettings.category_view.font_image.name[m
[14:53:36] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image for recipe GUI. Check ia_gui.yml file.[m
[14:53:37] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image. Check ia_gui.yml, attribute: [0;36;1msettings.category_view.font_image.name[m
[14:53:37] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image for recipe GUI. Check ia_gui.yml file.[m
[14:53:38] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mGUI error: can't find font_image. Check ia_gui.yml, attribute: [0;36;1msettings.category_view.font_image.name[m
[14:53:46] [Server thread/INFO]: moonstah lost connection: Disconnected
[14:53:46] [Server thread/INFO]: [Quests] DEBUG: PlayerLeaveListener: 7b6cd067-a7a0-4665-9e5a-acecbac74cd5 (moonstah)
[14:53:46] [Server thread/INFO]: [Quests] DEBUG: Unloading and saving player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[14:53:47] [Server thread/INFO]: moonstah left the game
[14:53:47] [Craft Scheduler Thread - 11 - Quests/INFO]: [Quests] DEBUG: Saving player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[14:53:47] [Craft Scheduler Thread - 11 - Quests/INFO]: [Quests] DEBUG: Quest progress file saved for player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5.
[14:56:19] [Craft Scheduler Thread - 13 - LiteBans/INFO]: [LiteBans] A plugin update is available! Your version: 2.11.3, latest version: 2.12.4
[14:56:19] [Craft Scheduler Thread - 13 - LiteBans/INFO]: [LiteBans] Updates can be downloaded from here:
[14:56:19] [Craft Scheduler Thread - 13 - LiteBans/INFO]: [LiteBans] https://www.spigotmc.org/resources/litebans.3715/
[15:21:32] [User Authenticator #1/INFO]: UUID of player moonstah is 7b6cd067-a7a0-4665-9e5a-acecbac74cd5
[15:21:32] [Server thread/INFO]: [Quests] DEBUG: PlayerJoinListener: 7b6cd067-a7a0-4665-9e5a-acecbac74cd5 (moonstah)
[15:21:32] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to SpawnJoin v0.6
java.lang.IllegalArgumentException: location.world
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1296) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1228) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:553) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at me.yoelgamer.events.PlayerListener.onJoin(PlayerListener.java:32) ~[SpawnJoin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor767.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1930]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:319) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:594) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1930]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:21:32] [Server thread/INFO]: moonstah joined the game
[15:21:32] [Server thread/INFO]: moonstah[/82.11.210.101:46042] logged in with entity id 600 at ([world]-56.922119744791225, 69.0, 65.44241293606885)
[15:21:32] [Server thread/INFO]: [Quests] DEBUG: Loading player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[15:21:32] [Craft Scheduler Thread - 77 - Quests/INFO]: [Quests] DEBUG: Querying player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5
[15:21:32] [Craft Scheduler Thread - 77 - Quests/INFO]: [Quests] DEBUG: Quest progress file loaded for player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5.
[15:21:32] [Server thread/INFO]: [Quests] DEBUG: Processing player (full check) 7b6cd067-a7a0-4665-9e5a-acecbac74cd5
[15:21:39] [Server thread/INFO]: moonstah issued server command: /ci
[15:21:42] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandAxe
[15:21:43] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandBow
[15:21:46] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandHoe
[15:21:47] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandPickaxe
[15:21:50] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandShovel
[15:21:52] [Server thread/INFO]: moonstah issued server command: /mm i get ContrabandSword
[15:23:03] [Craft Scheduler Thread - 83 - Quests/INFO]: [Quests] DEBUG: Saving player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[15:23:03] [Craft Scheduler Thread - 83 - Quests/INFO]: [Quests] DEBUG: Quest progress file saved for player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5.
[15:23:04] [Craft Scheduler Thread - 84 - LibsDisguises/INFO]: [LibsDisguises] Now looking for update on Jenkins..
[15:31:39] [Server thread/INFO]: moonstah lost connection: Disconnected
[15:31:39] [Server thread/INFO]: [Quests] DEBUG: PlayerLeaveListener: 7b6cd067-a7a0-4665-9e5a-acecbac74cd5 (moonstah)
[15:31:39] [Server thread/INFO]: [Quests] DEBUG: Unloading and saving player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[15:31:39] [Server thread/INFO]: moonstah left the game
[15:31:39] [Craft Scheduler Thread - 98 - Quests/INFO]: [Quests] DEBUG: Saving player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5...
[15:31:39] [Craft Scheduler Thread - 98 - Quests/INFO]: [Quests] DEBUG: Quest progress file saved for player 7b6cd067-a7a0-4665-9e5a-acecbac74cd5.
[15:33:21] [Server thread/INFO]: /213.136.71.218:32938 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
[16:14:37] [Server thread/INFO]: /213.136.71.218:45916 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: java.lang.NegativeArraySizeException
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.fQ.a(class:1859)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.ConvergenceException.a(class:4163)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.filter.EvaluatorFactory$EqualsEvaluator.a(class:3584)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.gf.a(class:2751)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.K.a(class:5906)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aV.bQ.a(class:2032)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aF.impl.v1_19_R1_2.a(class:4600)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aC.impl.v1_15_R1.a(class:3770)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.hc.a(class:3469)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.ds.a(class:4746)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.Edge.a(class:2472)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.fE.a(class:1487)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.a(class:4757)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aR.bC.a(class:5441)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.bK.a(class:3022)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.cG.a(class:3156)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.bK.a(class:5347)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.a.a(class:2062)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.net.minidev.json.JSONValue.a(class:1395)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aL.aU.a(class:3006)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.LinkedBuffer.a(class:5826)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.distribution.BinomialDistribution.a(class:742)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.Constants.a(class:28)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Denizen.SetCustomBlock.a(class:3556)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.aW.a(class:6398)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aL.impl.v1_17_R1.a(class:5984)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.kS.a(class:3359)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.bp.a(class:4812)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.analysis.solvers.AllowedSolution.a(class:1157)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aR.bB.a(class:310)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aG.impl.v1_15_R1.a(class:203)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.WriteContext.a(class:2695)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.aZ.a(class:5098)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.N.a(class:6203)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.special.Gamma$1.a(class:542)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.net.minidev.json.parser.JSONParserStream.a(class:5050)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.jH.a(class:1487)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.fL.a(class:5255)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.ClassVisitor.a(class:5527)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.kb.a(class:1365)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.gz.a(class:1241)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.kT.a(class:338)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.Events.campfire.CampfireLitEvent.a(class:1172)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.WriteSession.a(class:423)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aL.impl.v1_19_R1_2.a(class:1295)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.filter.EvaluatorFactory$EqualsEvaluator.a(class:4885)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.iy.a(class:1204)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.jQ.a(class:2497)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.I.a(class:874)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.ay.a(class:395)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.path.ScanPathToken$PropertyPathTokenPredicate.a(class:4259)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.net.minidev.json.annotate.JsonSmartAnnotation.a(class:3098)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.cH.a(class:1947)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider$BigIntegerReader.a(class:2386)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.iP.a(class:3349)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aR.i.a(class:4046)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aF.impl.v1_20_R1.a(class:5150)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.m.kL.a(class:1364)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.sh.org.objectweb.asm.MethodTooLargeException.a(class:2159)
[16:43:04] [Craft Scheduler Thread - 243 - ItemsAdder/WARN]: 	at ia.nms.aX.impl.d.a(class:5706)
[16:43:04] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.5.0c-r2
[16:43:04] [Server thread/INFO]: [ItemsAdder] [mSaving custom entities...[m
[16:43:04] [Server thread/INFO]: [ItemsAdder] [mSaved 22 custom entities successfully![m
[16:43:04] [pool-60-thread-1/INFO]: [ItemsAdder] [m[0;36;1m[Host] Stopped self-host webserver on port: 50428[m
```

**Comment by LoneDev6** [comment]
Please do not post partial logs, post the complete server log.

**Comment by LoneDev6** [comment]
You seem to have some broken files from an older version of ItemsAdder.
- Stop the server
- delete `plugins/ItemsAdder/storage/` folder
- start the server
Everything is fixed

**Comment by LoneDev6** [comment]
Also I noticed you removed your review, why did you remove the review?
Did you change your mind about the plugin?
Why removing only 1 review and keep the old one from Mar 14, 2023?
https://www.spigotmc.org/resources/73355/reviews?page=3#review-488508-67925

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/397a2895-f7ea-41c6-9dc2-6a2866707c0f)

**Comment by moonies44** [comment]
Removed for you as requested,
will try above fix today thank you.

**Comment by LoneDev6** [comment]
Please let me know if the fix works, otherwise try to download the plugin again since you might have downloaded a partial or corrupted JAR file.
