### ISSUE TITLE
Firing with guns throws warns

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#2860]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When i fire any type of gun the warning is thrown

### Steps to reproduce the issue

Just fire with any gun

### Server version

git-Purpur-2011 (MC: 1.20.1)*

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.25

### FULL server log

java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
       at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:156)
       at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103)
       at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59)
       at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:183)
       at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:157)
       at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:152)
       at ItemsAdder_3.5.0c-r2.jar//ia.m.kg.a(SourceFile:304)
       at ItemsAdder_3.5.0c-r2.jar//ia.m.kg.u(SourceFile:380)
       at ItemsAdder_3.5.0c-r2.jar//ia.m.bM.b(SourceFile:251)
       at ItemsAdder_3.5.0c-r2.jar//ia.m.dd.a(SourceFile:145)
       at ItemsAdder_3.5.0c-r2.jar//ia.m.dd.h(SourceFile:235)
       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
       at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
       at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
       at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
       at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566)
       at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:523)
       at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:517)
       at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:513)
       at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2102)
       at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
       at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
       at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
       at net.minecraft.server.TickTask.run(TickTask.java:18)
       at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
       at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
       at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
       at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
       at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
       at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
       at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
       at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
       at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
This is rare and seems to happen only when player disconnects during the packet send.
Please bump this issue if it happens again and I will look further into that issue.
