### ISSUE TITLE
Can't apply the default pack

### ISSUE THREAD

**Issue by KarlPro123** [PluginBugs/Issues-ItemsAdder#2862]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

KarlPro123#9259

### What happened?

I am trying to apply the default pack ItemsAdder comes with, but I get an error, which I'm not sure how to get rid of. I think it's actually an issue on my end, but I really would like to get some help, because I am clueless how to fix this problem.

### Steps to reproduce the issue

I set up my config and trying to apply the pack with /iazip doesn't work.

### Server version

This server is running Paper version git-Paper-60 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.5.0c (the same problem happened with previous versions though)

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

There are no errors server side, however I have one from client side.

### Error (optional)

```shell
[11:42:56] [Downloader 0/INFO]: Found file C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\a51c4dbeea17124cdf38cac12dc0dacb65c336a8 without verification hash
[11:42:56] [Downloader 0/ERROR]: Failed to open pack C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\a51c4dbeea17124cdf38cac12dc0dacb65c336a8
java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at ajk.c(SourceFile:44) ~[1.20.1.jar:?]
	at ajk.a(SourceFile:72) ~[1.20.1.jar:?]
	at ajk.a(SourceFile:62) ~[1.20.1.jar:?]
	at ajh.a(SourceFile:30) ~[1.20.1.jar:?]
	at akg.a(SourceFile:71) ~[1.20.1.jar:?]
	at fvn.a(SourceFile:216) ~[1.20.1.jar:?]
	at fvn.a(SourceFile:114) ~[1.20.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:42:56] [Downloader 0/WARN]: Missing metadata in pack server
[11:42:56] [IO-Worker-25/WARN]: Pack application failed: java.lang.IllegalArgumentException: Invalid pack metadata at C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\a51c4dbeea17124cdf38cac12dc0dacb65c336a8, deleting file C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\a51c4dbeea17124cdf38cac12dc0dacb65c336a8
```

### Other files, you can drag and drop them here to upload. (optional)

https://pastebin.com/g6Pa6eq4 - Here's my config. I deleted the ip part from self-host section to not give out private information.
https://prnt.sc/stO9DqOI7zWA - Here's the error that appears when I try to apply it in-game.

**Comment by LoneDev6** [comment]
For some reason your resourcepack zip file doesn't contain any pack.mcmeta file.
This shouldn't happen as itemsadder creates one for you.
Are you actually applying an itemsadder pack?

Please attach your `ItemsAdder/output/generated.zip` file here.

**Comment by KarlPro123** [comment]
[generated.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12014795/generated.zip)

Here it is. It does contain the file though.

**Comment by LoneDev6** [comment]
The pack loads fine for me.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/35c44a69-14ab-4bde-b0bd-19a1b6b16aa6)

Open this folder in your PC and delete everything (while game is closed).
`C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\`

Then join again.
If you are not using selfhost please reupload the file and update the URL.
If you are using selfhost you don't have to do anything else.
