### ISSUE TITLE
Add 1.20 new models compatibility

### ISSUE THREAD

**Issue by Jeremylo1** [PluginBugs/Issues-ItemsAdder#2867]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Jeremylo1

### What happened?

I'd like to create a new brush but I can't use BRUSH as a material. 
Brushes have a unique way of interacting with the suspicious blocks and I can't use another material.

### Steps to reproduce the issue

1. Create this item :
```
info:
  namespace: archeologie
items:
  diamond_brush:
    enabled: true
    display_name: "&fPinceau diamant"
    resource:
      material: BRUSH
      generate: true
      textures:
        - item/diamond_brush
```
2. Use "/iazip"

### Server version

git-Paper-60 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[23:11:54 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[23:11:54 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[23:11:54 WARN]: [ItemsAdder] Detected legacy ItemsAdder pack (pre 3.3.0).
[23:11:54 WARN]: [ItemsAdder] Trying to load files, unexpected results might occur.
[23:11:54 WARN]: [ItemsAdder] It's adviced to follow the new guidelines: https://a.devs.beer/ia-new-guidelines-330
[23:11:54 INFO]: [ItemsAdder] Loaded 229 items
[23:11:54 INFO]: [ItemsAdder] Used 1/188 REAL block IDs
[23:11:54 INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[23:11:54 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[23:11:54 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[23:11:54 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[23:11:54 INFO]: [ItemsAdder] Used 79/6608 font_images
[23:11:54 INFO]: [ItemsAdder] [Init] Loaded 6 categories
[23:11:54 INFO]: [ItemsAdder] [Init] Loaded successfully in 116ms
[23:11:54 INFO]: [ItemsAdder]  
[23:11:54 INFO]: [ItemsAdder]  
[23:11:54 INFO]: [ItemsAdder] [Pack] Started generation
[23:11:54 ERROR]: [ItemsAdder] Error reading vanilla model for material BRUSH, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/brush.json'
[23:11:54 ERROR]: [ItemsAdder] Choose another material, BRUSH is not supported for these items: archeologie:diamond_brush, 
[23:11:54 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:11:54 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:11:54 INFO]: [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
[23:11:54 INFO]: [Mythic] Reloading plugin...
[23:11:54 ERROR]: [ItemsAdder] Failed to process item file: brush
[23:11:54 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonArray(String)" because "<parameter1>" is null
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iZ.b(SourceFile:318)
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iZ.b(SourceFile:329)
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iG.cz(SourceFile:998)
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.G.a(SourceFile:2708)
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.hM.a(SourceFile:86)
[23:11:54 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.G.a(SourceFile:2463)
[23:11:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:11:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:11:54 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:11:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:11:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:11:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:11:54 ERROR]: [ItemsAdder] PNG 'z_cosmetics:cosmetics_slot' not found for model. File: /home/container/plugins/ItemsAdder/contents/cosmetics/resourcepack/assets/z_cosmetics/models/cosmetics_slot.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/end_crystal' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/ender_eye' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/ender_pearl' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/experience_bottle' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/end_crystal' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox_up.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/ender_eye' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox_up.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/ender_pearl' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox_up.json
[23:11:55 ERROR]: [ItemsAdder] PNG 'itemshopplus:itemshopplus/misc/experience_bottle' not found for model. File: /home/container/plugins/ItemsAdder/contents/itemshopplus/resourcepack/assets/itemshopplus/models/itemshopplus/sellbox/misc_sellbox_up.json
[23:11:55 INFO]: [ItemsAdder]  
[23:11:55 INFO]: [ItemsAdder] [Pack] Generated resourcepack
[23:11:55 INFO]: [MythicMobs] Loading Packs...
[23:11:55 INFO]: [MythicMobs] Loading Items...
[23:11:55 INFO]: [MythicMobs] Loading Item Groups...
[23:11:55 INFO]: [MythicMobs] Loading Skills...
[23:11:55 INFO]: [MythicMobs] Loading Drop Tables...
[23:11:55 INFO]: [MythicMobs] Loading Random Spawns...
[23:11:55 INFO]: [MythicMobs] Loading Spawn Blocks...
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 8 mobs.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 3 skills.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 0 random spawns.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 3 mythic items.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 2 drop tables.
[23:11:55 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[23:11:55 INFO]: [Mythic] Mythic has finished reloading!
[23:11:55 INFO]: [MythicMobs] Mythic has finished reloading!
[23:11:55 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[23:11:55 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ... 
[23:11:55 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.remove(String)" because "<parameter1>" is null
[23:11:55 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iG.a(SourceFile:845)
[23:11:55 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iC.a(SourceFile:129)
[23:11:55 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iG.d(SourceFile:402)
[23:11:55 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[23:11:55 WARN]:        at ItemsAdder_3.5.0c-r2.jar//ia.m.iG.a(SourceFile:401)
[23:11:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:11:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:11:55 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:11:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:11:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:11:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:11:55 INFO]: [ItemsAdder] [Pack] Resource pack successfully compressed. Uploading...
[23:11:55 INFO]: [ItemsAdder] [Pack] Uploading resourcepack...
[23:11:55 INFO]: [ItemsAdder] [Pack] Finished uploading resourcepack: http://resourcepack.host/dl/oVO50i3ElHNOmmQnLmRWh7n997apBOu8/pack.zip
[23:11:55 INFO]: [ItemsAdder] [Pack] Compressed in 849ms

### Error (optional)

[23:11:54 ERROR]: [ItemsAdder] Error reading vanilla model for material BRUSH, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/brush.json'
[23:11:54 ERROR]: [ItemsAdder] Choose another material, BRUSH is not supported for these items: archeologie:diamond_brush,
[23:11:54 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:11:54 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:11:54 INFO]: [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
[23:11:54 INFO]: [Mythic] Reloading plugin...
[23:11:54 ERROR]: [ItemsAdder] Failed to process item file: brush

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: archeologie
items:
  diamond_brush:
    enabled: true
    display_name: "&fPinceau diamant"
    resource:
      material: BRUSH
      generate: true
      textures:
        - item/diamond_brush
```

**Comment by Jeremylo1** [comment]
Do you have any idea how to correct this? Do I have to manually create the brush.json in the vanilla resource pack?

**Comment by LoneDev6** [comment]
If you really want to fix it on temporarily you have to open the JAR file of ItemsAdder and add brush.json into `templated/vanilla_items`.
Download the brush.json from here.
[brush.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12036702/brush.zip)

This should work fine but I'm not sure if I have to implement some fixes and compatibility, but you can test.

**Comment by DuneSciFye** [comment]
I'm getting same issue for all 1.20 new items

**Comment by CrystallRPG** [comment]
> If you really want to fix it on temporarily you have to open the JAR file of ItemsAdder and add brush.json into `templated/vanilla_items`. Download the brush.json from here. [brush.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12036702/brush.zip)
> 
> This should work fine but I'm not sure if I have to implement some fixes and compatibility, but you can test.

where this folder should be find? i search it in whole server folder without finding it

I got the same error + unsupported material for Allay Spawn Egg and Camel Spawn Egg

**Comment by CrystallRPG** [comment]
> If you really want to fix it on temporarily you have to open the JAR file of ItemsAdder and add brush.json into `templated/vanilla_items`. Download the brush.json from here. [brush.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12036702/brush.zip)
> 
> This should work fine but I'm not sure if I have to implement some fixes and compatibility, but you can test.

I actually have the same issue with Camel_Spawn_Egg and Allay_Spawn_Egg but i got another error; not supported material;

```
[11:03:39 ERROR]: CrystalSMPPack Â» Error reading vanilla model for material CAMEL_SPAWN_EGG, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/camel_spawn_egg.json'
[11:03:39 ERROR]: CrystalSMPPack Â» Choose another material, CAMEL_SPAWN_EGG is not supported for these items: crystalsmp:camel_spawn_egg,
[11:03:39 ERROR]: CrystalSMPPack Â» Error reading vanilla model for material ALLAY_SPAWN_EGG, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/allay_spawn_egg.json'
[11:03:39 ERROR]: CrystalSMPPack Â» Choose another material, ALLAY_SPAWN_EGG is not supported for these items: crystalsmp:allay_spawn_egg,
[11:03:39 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[11:03:39 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[11:03:39 INFO]: CrystalSMPPack Â» Reloading ItemsAdder Custom Entities Citizens NPCs
[11:03:39 ERROR]: CrystalSMPPack Â» Failed to process item file: camel_spawn_egg
[11:03:39 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonArray(String)" because "<parameter1>" is null
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:318)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:329)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.cz(SourceFile:998)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2708)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.hM.a(SourceFile:86)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2463)
[11:03:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:03:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:03:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:03:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:03:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:03:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:03:39 ERROR]: CrystalSMPPack Â» Failed to process item file: allay_spawn_egg
[11:03:39 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonArray(String)" because "<parameter1>" is null
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:318)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:329)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.cz(SourceFile:998)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2708)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.hM.a(SourceFile:86)
[11:03:39 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2463)
[11:03:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:03:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:03:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:03:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:03:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:03:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:03:40 INFO]: CrystalSMPPack Â»
[11:03:40 INFO]: CrystalSMPPack Â» [Pack] Generated resourcepack
[11:03:40 INFO]: CrystalSMPPack Â» [OK] Your zip file will be protected from unzip (as set in config.yml)
[11:03:40 INFO]: CrystalSMPPack Â» [Pack] Compressing resource_pack ...
[11:03:40 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.remove(String)" because "<parameter1>" is null
[11:03:40 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.a(SourceFile:845)
[11:03:40 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iC.a(SourceFile:129)
[11:03:40 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.d(SourceFile:402)
[11:03:40 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[11:03:40 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.a(SourceFile:401)
[11:03:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:03:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:03:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:03:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:03:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:03:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

```
