### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2868]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

I'm playing an emote from my own plugin on emote, and because of this ItemsAdder is displaying an error in the console.

### Steps to reproduce the issue

.

### Server version

Purpur version git-Purpur-1171 (MC: 1.16.5) 

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/9f6d6bf6-200a-4927-9ebc-528831d784fa)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/b71f7f57-4089-417c-aa84-1550b5294723)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/c8c9e3dc-fa1f-41cb-a8f0-22dd2824182f)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/8bce4f3e-27b3-4283-9f87-5594fbcd975d)

**Comment by Lerphie** [comment]
`[05:03:31] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: Cannot load from object array because "<local4>" is null
	at ia.m.bg.onPacketSending(SourceFile:224) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2033) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:560) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[05:03:31] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutTitle@650b71a[
    a=ACTIONBAR
    b=<null>
    c=-1
    d=-1
    e=-1
    components=<null>
  ]

[05:03:31] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NullPointerException: Cannot load from object array because "<local4>" is null
	at ia.m.bg.onPacketSending(SourceFile:224) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2033) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:287) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:560) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[05:03:31] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutTitle@6f0418dc[
    a=ACTIONBAR
    b=<null>
    c=-1
    d=-1
    e=-1
    components=<null>
  ]`

**Comment by LoneDev6** [comment]
Will be checked as soon as possible.

**Comment by Lerphie** [comment]
> Will be checked as soon as possible.

Hello again! The problem was the ActionBar, I removed it (since my emotion plugin puts me on a horse, I removed the actionbar from the horse). Now I have another error coming out, read it here:

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/7084d589-21fc-457e-9eed-dc6ddc32a384)

**Comment by LoneDev6** [comment]
please post text not screenshot of errors.

**Comment by Distolfix** [comment]
@LoneDev6 i have the same error on my console https://pastebin.com/5GwhXR9m

**Comment by LoneDev6** [comment]
> @LoneDev6 i have the same error on my console https://pastebin.com/5GwhXR9m

It's not the same error.
Anyway your error is already reported here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2847
