### ISSUE TITLE
 Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#2871]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Console errors

### Steps to reproduce the issue

idk i just view this in console

### Server version

 ver
[21:23:48 INFO]: Checking version, please wait...
[21:23:49 INFO]: Current: git-Purpur-1980 (MC: 1.19.4)*
* You are 5 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

[21:24:29 INFO]: ItemsAdder version 3.5.0c-r2
[21:24:29 INFO]: Customized Minecraft without client mods!
[21:24:29 INFO]: Website: devs.beer
[21:24:29 INFO]: Author: LoneDev

### ProtocolLib Version

> ver ProtocolLib
[21:24:24 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-655
[21:24:24 INFO]: Provides read/write access to the Minecraft protocol.
[21:24:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> ver LoneLibs
[21:24:17 INFO]: LoneLibs version 1.0.25
[21:24:17 INFO]: Collection of libs used by my plugins
[21:24:17 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[14:46:36] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mFailed to load chunk '-25, 72' | world_the_end -> /itemsadder/region/r.-1.2.pregion[m
[14:46:36] [Server thread/WARN]: ia.sh.io.protostuff.ProtobufException: Protocol message tag had invalid wire type.
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.sh.io.protostuff.ProtobufException.invalidWireType(SourceFile:118)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.sh.io.protostuff.CodedInput.skipField(SourceFile:170)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.sh.io.protostuff.CodedInput.handleUnknownField(SourceFile:1254)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.ir.a(SourceFile:496)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.ir.mergeFrom(SourceFile:442)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.sh.io.protostuff.CodedInput.mergeObjectEncodedAsGroup(SourceFile:359)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.sh.io.protostuff.CodedInput.mergeObject(SourceFile:321)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.is.a(SourceFile:257)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.is.mergeFrom(SourceFile:205)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cQ.a(SourceFile:34)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cQ.a(SourceFile:40)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cQ.a(SourceFile:50)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cQ.a(SourceFile:23)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.kq.g(SourceFile:252)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cT.a(SourceFile:140)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cJ.a(SourceFile:130)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cJ.a(SourceFile:97)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cJ.a(SourceFile:129)
[14:46:36] [Server thread/WARN]: 	at ItemsAdder_3.5.0c-r2(2).jar//ia.m.cI.a(SourceFile:43)
[14:46:36] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:46:36] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[14:46:36] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:46:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:924)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.onChunkLoad(Chunk.java:875)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1057)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1041)
[14:46:36] [Server thread/WARN]: 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:926)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.s(ChunkProviderServer.java:586)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:1040)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:582)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2789)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2812)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1347)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1317)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1205)
[14:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[14:46:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by LoneDev6** [comment]
You probably killed the server or it crashed while saving a region file, so this region file got corrupted.
There is no way to recover it if you don't have backups.
File: `world_the_end/itemsadder/region/r.-1.2.pregion`
