### ISSUE TITLE
ResourcePack Not Work

### ISSUE THREAD

**Issue by SrathYT** [PluginBugs/Issues-ItemsAdder#2891]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

stevenetwork#3757

### What happened?

**I Already Follow The Tutorial But The ResourcePack Was Not Working I Use Betterranks and the resourcepack show was []** 

### Steps to reproduce the issue

*

### Server version

This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[11:22:48 INFO]: [SternalBoard] Enabling SternalBoard v2.2.2
[11:22:48 INFO]: [PlayerReport] Enabling PlayerReport v3.4.3
[11:22:49 INFO]: [ItemsAdderConverter] Enabling ItemsAdderConverter v0.7
[11:22:49 INFO]: [EconomyShopGUI] Enabling EconomyShopGUI v5.6.1
[11:22:49 INFO]: [EconomyShopGUI] [INFO]: Using lang-en.yml as language file.
[11:22:49 INFO]: [EconomyShopGUI] [INFO]: Shops.yml has been found!
[11:22:49 INFO]: [EconomyShopGUI] [INFO]: Sections.yml has been found!
[11:22:49 INFO]: [EconomyShopGUI] [INFO]: Successfully hooked into Vault
[11:22:49 INFO]: [EconomyShopGUI] [DEBUG]: Completed loading '1' economy provider(s) for all 16 shop sections.
[11:22:49 INFO]: [EconomyShopGUI] [INFO]: Using minecraft version 1.20.1...
[11:22:50 INFO]: [EconomyShopGUI] [INFO]: Spawner provider set to DEFAULT in config
[11:22:50 INFO]: [EconomyShopGUI] [INFO]: Using plugin default spawners...
[11:22:50 INFO]: [EconomyShopGUI] [INFO]: Debug mode is enabled.
[11:22:50 INFO]: [EconomyShopGUI] [INFO]: Updating Shop settings...
[11:22:50 INFO]: [EconomyShopGUI] [INFO]: Loading all items...
[11:22:54 INFO]: [EconomyShopGUI] Initialized - Took 5698ms to complete
[11:22:55 INFO]: [GSit] Enabling GSit v1.4.10
[11:22:55 INFO]: [GSit] The plugin was successfully enabled.
[11:22:55 INFO]: [GSit] Link with PlaceholderAPI successful!
[11:22:55 INFO]: [PlaceholderAPI] Successfully registered expansion: gsit [1.4.10]
[11:22:56 INFO]: [GSit] Link with WorldGuard successful!
[11:22:56 INFO]: [Multiverse-Inventories] Enabling Multiverse-Inventories v4.2.3-b523
[11:22:58 INFO]: [Multiverse-Inventories 4.2.3-b523] enabled.
[11:22:58 INFO]: [ImageOnMap] Enabling ImageOnMap v4.2.2
[11:23:00 INFO]: [ImageOnMap] Loaded 1 player map files.
[11:23:00 INFO]: [BPS-Free] Enabling BPS-Free v4.0.19
[11:23:01 INFO]: [QuickShop] Enabling QuickShop v5.1.2.2
[11:23:01 INFO]: [QuickShop] QuickShop Reremake
[11:23:01 INFO]: [QuickShop] Starting plugin self-test, please wait...
[11:23:03 WARN]: [spark] Timed out waiting for world statistics
[11:23:06 INFO]: [QuickShop] [OK] Signature Verify
[11:23:06 INFO]: [QuickShop] [OK] Plugin Manifest Check
[11:23:06 INFO]: [QuickShop] [OK] Potential Infection Characteristics Check
[11:23:06 INFO]: [QuickShop] [OK] Java Runtime Environment Version Test
[11:23:06 INFO]: [QuickShop] Running QuickShop-Reremake on NMS version v1_20_R1 For Minecraft version 1.20.1
[11:23:06 INFO]: [QuickShop] [OK] Spigot Based Server Test
[11:23:06 INFO]: [QuickShop] [OK] Old QuickShop Test
[11:23:06 INFO]: [QuickShop] [OK] ModdedServer Based Test
[11:23:06 INFO]: [QuickShop] [OK] CoreSupport Test
[11:23:09 INFO]: [QuickShop] [OK] Virtual DisplayItem Support Test
[11:23:09 INFO]: [QuickShop] [OK] GameVersion supporting Test
[11:23:09 INFO]: [QuickShop] [OK] PacketListenerAPI Conflict Test
[11:23:09 INFO]: [QuickShop] [OK] End of life Test
[11:23:09 INFO]: [QuickShop] Reading the configuration...
[11:23:10 INFO]: [QuickShop] Developers: PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood (KaiKikuchi), jho5245, Ghost_chu, cakoyo, Ectabro, portlek, log4b0at, Andre601, deadman96385, Vlvxingze, DoctaEnkoda, Mgazul, TiaraRinne, sandtechnology, Starmism, Chris6ix, Rean Schwarzer, mart-r, raphtaliapt, Tim269, creatorfromhell, LoneDev6, judgetread, confuxeon, ibmibmibm, yannicklamprecht, PyvesB, PaulBGD, ORelio, JoschuaSchneider, Starmium, harry0198, efekurbann, tdiant
[11:23:10 INFO]: [QuickShop] Original author: Netherfoam, Timtower, KaiNoMood
[11:23:10 INFO]: [QuickShop] Let's start loading the plugin
[11:23:10 INFO]: [QuickShop] Chat processor selected: Hardcoded BungeeChat Lib
[11:23:12 INFO]: [QuickShop] Loading plugin translations files...
[11:23:12 INFO]: [QuickShop] Game assets server selected: Mojang API
[11:23:12 INFO]: [QuickShop] Loading items translations...
[11:23:14 INFO]: [QuickShop] Loading enchantments translations...
[11:23:14 INFO]: [QuickShop] Loading potions translations...
[11:23:14 INFO]: [QuickShop] Successfully loaded PlaceHolderAPI support!
[11:23:14 INFO]: [QuickShop] Successfully loaded WorldEdit support!
[11:23:14 INFO]: [QuickShop] Using Virtual Item display, loading ProtocolLib support...
[11:23:14 INFO]: [QuickShop] Successfully loaded ProtocolLib support!
[11:23:14 INFO]: [QuickShop] Setting up database...
[11:23:14 INFO]: [QuickShop] Checking and updating database columns, it may take a while...
[11:23:15 INFO]: [QuickShop] Finished!
[11:23:15 INFO]: [QuickShop] Selected permission provider: Bukkit
[11:23:15 INFO]: [QuickShop] Registering commands...
[11:23:18 INFO]: [QuickShop] Loaded 1 rules for listener blacklist.
[11:23:18 INFO]: [QuickShop] EventManager selected: QSEventManager
[11:23:18 INFO]: [QuickShop] Fetching shops from the database...If plugin stuck there, check your database connection.
[11:23:18 INFO]: [QuickShop] Loading shops from the database...
[11:23:18 INFO]: [QuickShop] >> Shop Loader Information
[11:23:18 INFO]: [QuickShop] Total           shops: 0
[11:23:18 INFO]: [QuickShop] Valid           shops: 0
[11:23:18 INFO]: [QuickShop] Pending              : 0
[11:23:18 INFO]: [QuickShop] Waiting worlds loaded: 0
[11:23:18 INFO]: [QuickShop] Waiting chunks loaded: 0
[11:23:18 INFO]: [QuickShop] Done! Used 7ms to loaded shops in database.
[11:23:18 INFO]: [QuickShop] Registering listeners...
[11:23:19 INFO]: [QuickShop] Cleaning MsgUtils...
[11:23:19 INFO]: [QuickShop] Cleaning purchase messages from the database that are over a week old...
[11:23:19 INFO]: [QuickShop] Log actions is enabled, actions will log in the qs.log file!
[11:23:19 INFO]: [QuickShop] [Shop Purger] Purge not enabled!
[11:23:19 INFO]: [QuickShop] QuickShop Loaded! 18797 ms.
[11:23:20 INFO]: [OreAnnouncer] Enabling OreAnnouncer v2.8.4
[11:23:20 INFO]: [OreAnnouncer] Initializing OreAnnouncer v2.8.4
[11:23:37 INFO]: [PlaceholderAPI] Successfully registered expansion: oreannouncer [2.8.4]
[11:23:37 INFO]: [OreAnnouncer] Hooked into PlaceholderAPI
[11:23:37 INFO]: [OreAnnouncer] OreAnnouncer v2.8.4 enabled
[11:23:37 INFO]: [TreeAssist] Enabling TreeAssist v7.3.44
[11:23:37 INFO]: [TreeAssist] sending full Metrics! You can deactivate this in the config.yml
[11:23:37 INFO]: [TreeAssist] debugging: off
[11:23:38 INFO]: [TreeAssist] Checking for updates...
[11:23:38 INFO]: [InteractiveChat] Enabling InteractiveChat v4.2.7.2
[11:23:43 INFO]: [InteractiveChat] Opened Sqlite database successfully
[11:23:43 INFO]: [InteractiveChat] InteractiveChat has hooked into Essentials!
[11:23:44 INFO]: [InteractiveChat] InteractiveChat has hooked into ViaVersion!
[11:23:44 INFO]: [InteractiveChat] InteractiveChat has hooked into LuckPerms!
[11:23:44 INFO]: [PlaceholderAPI] Successfully registered expansion: interactivechat [4.2.7.2]
[11:23:44 INFO]: [InteractiveChat] InteractiveChat has been Enabled!
[11:23:45 INFO]: [DeluxeMentions] Enabling DeluxeMentions v5.7.19
[11:23:45 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.2.10
[11:23:45 INFO]: [AdvancedEnchantments] [STDOUT] [Spigotunlocked.com] - COSMO
[11:23:45 WARN]: Nag author(s): '[AdvancedPlugins]' of 'AdvancedEnchantments v9.2.10' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[11:23:46 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard, PlaceholderAPI, Slimefun.
[11:23:47 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[11:23:47 INFO]: [AdvancedEnchantments] Successfully hooked into Slimefun.
[11:23:47 INFO]: [PlaceholderAPI] Successfully registered expansion: advancedenchantments [1.0.0]
[11:23:47 INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[11:23:47 INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[11:23:47 INFO]: [AdvancedEnchantments] Successfully hooked into Essentials.
[11:23:48 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[11:23:48 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[11:23:52 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)
[11:23:53 INFO]: [UberEnchant] Enabling UberEnchant v8.9.14
[11:23:53 INFO]: [HiddenArmor] Enabling HiddenArmor v1.1.0
[11:23:54 INFO]: [CrazyAuctionsPlus] Enabling CrazyAuctionsPlus v1.3.2.1
[11:23:54 INFO]: [CrazyAuctionsPlus] System default language parameter information is loaded.
[11:23:54 INFO]: [CrazyAuctionsPlus] Configuration file Config.yml successfully loaded!
[11:23:54 INFO]: [CrazyAuctionsPlus] Configuration file Database.yml successfully loaded!
[11:23:54 INFO]: [CrazyAuctionsPlus] Configuration file Category.yml successfully loaded!
[11:23:54 INFO]: [CrazyAuctionsPlus] Configuration file ItemCollection.yml successfully loaded!
[11:23:54 INFO]: [CrazyAuctionsPlus] Configuration file Messages.yml successfully loaded!
[11:23:54 INFO]: CrazyAuctionsPlus >>> Vault found, Economic system has been initialized.
[11:23:55 INFO]: CrazyAuctionsPlus >>> Plugin are enabled! 1009MS.
[11:23:55 INFO]: [Clans] Enabling Clans v0.4.5
[11:23:57 INFO]: [PlaceholderAPI] Successfully registered expansion: clans [0.4.5]
[11:23:57 INFO]: [ItemsAdder] Enabling ItemsAdder v3.5.0c-r2
[11:23:59 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[11:23:59 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[11:23:59 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[11:23:59 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.5.0c-r2
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.25
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-84 (MC: 1.20.1)
                                               
[11:24:03 WARN]: [spark] Timed out waiting for world statistics
[11:24:06 INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[11:24:11 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[11:24:13 INFO]: Running delayed init tasks
[11:24:13 INFO]: [PlaceholderAPI] Successfully registered expansion: playerpoints [3.2.6]
[11:24:14 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[11:24:14 INFO]: [Essentials] Fetching version information...
[11:24:14 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[11:24:15 INFO]: [DecentHolograms] Loading holograms... 
[11:24:18 INFO]: [ExcellentCrates] Auto-save: Saved 0 online users | 0 offline users.
[11:24:18 INFO]: [InteractiveChat] Loading languages...
[11:24:18 INFO]: [Vault] Checking for Updates ... 
[11:24:18 INFO]: [CustomJoinAndQuitMessages] : [SUCCESS] CustomJoinAndQuitMessages is up to date!
[11:24:19 INFO]: [DecentHolograms] Loaded 1 holograms!
[11:24:19 INFO]: [ItemsAdder] You can ignore this message: Can't connect to SpigotMC.org, probably internet connection is blocked.
( Error connecting: 400 ) - User ID: %%__USER__%%
[11:24:19 ERROR]: [ItemsAdder] [License] Unknown user ID: %%__USER__%%
[11:24:20 INFO]: [Vault] No new version available
[11:24:21 INFO]: [Slimefun] Slimefun is already up to date!
[11:24:26 INFO]: [Slimefun] Now running MetricsModule build #29
[11:24:26 INFO]: [Slimefun] with a total of 19/19 chart(s)!
[11:24:26 INFO]: [Slimefun] Metrics build #29 started.
[11:24:27 INFO]: [Slimefun] Collecting Snapshots of all Recipes...
[11:24:28 INFO]: [Slimefun] Found 1,190 Recipes!
[11:24:30 INFO]: 
[11:24:30 INFO]: ######################### - Slimefun vDEV - 1087 (git dc22e665) - #########################
[11:24:30 INFO]: 
[11:24:30 INFO]: Successfully loaded 554 Items and 258 Researches
[11:24:30 INFO]: ( 554 Items from Slimefun, 0 Items from 3 Addons )
[11:24:30 INFO]: 
[11:24:30 INFO]: Slimefun is an Open-Source project that is kept alive by a large community.
[11:24:30 INFO]: Consider helping us maintain this project by contributing on GitHub!
[11:24:30 INFO]: 
[11:24:30 INFO]:  - Source Code:  https://github.com/Slimefun/Slimefun4
[11:24:30 INFO]:  - Wiki:         https://github.com/Slimefun/Slimefun4/wiki
[11:24:30 INFO]:  - Addons:       https://github.com/Slimefun/Slimefun4/wiki/Addons
[11:24:30 INFO]:  - Bug Reports:  https://github.com/Slimefun/Slimefun4/issues
[11:24:30 INFO]:  - Discord:      https://discord.gg/slimefun
[11:24:30 INFO]: 
[11:24:31 INFO]: [Slimefun] Loading Blocks for World "world"
[11:24:31 INFO]: [Slimefun] This may take a long time...
[11:24:31 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 1ms)
[11:24:31 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world"
[11:24:31 INFO]: [Slimefun] Loading Blocks for World "world_nether"
[11:24:31 INFO]: [Slimefun] This may take a long time...
[11:24:31 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[11:24:31 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_nether"
[11:24:31 INFO]: [Slimefun] Loading Blocks for World "world_the_end"
[11:24:31 INFO]: [Slimefun] This may take a long time...
[11:24:31 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[11:24:31 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_the_end"
[11:24:31 INFO]: [dough: protection] Loading Protection Modules...
[11:24:31 INFO]: [dough: protection] This may happen more than once.
[11:24:32 INFO]: [dough: protection] Loaded Protection Module "WorldGuard v7.0.9-beta1+2249-223b80c"
[11:24:32 INFO]: [dough: protection] Loaded Protection Module "RedProtect v8.1.1-SNAPSHOT"
[11:24:33 INFO]: [BPS Free] Successfully enabled v4.0.19
[11:24:33 INFO]: --------------------------------------------------------------------------------------
[11:24:33 INFO]:          Developed by Ruben_Artz
[11:24:33 INFO]: [BPS Free] Version: 4.0.19 is loading... (Current)
[11:24:33 INFO]: [BPS Free] Server: git-Paper-84 (MC: 1.20.1)
[11:24:33 INFO]: [BPS Free] Loading necessary files...
[11:24:33 INFO]: 
[11:24:33 INFO]: BPS Free [Loader] Loaded archive 'config.yml'
[11:24:33 INFO]: BPS Free Starting plugin...
[11:24:33 INFO]: 
[11:24:33 INFO]: [BPS Free] PlaceholderAPI found correctly.
[11:24:33 INFO]: [BPS Free] ProtocolLib found correctly.
[11:24:33 INFO]: 
[11:24:33 INFO]: --------------------------------------------------------------------------------------
[11:24:33 INFO]: [QuickShop] Registering bStats metrics...
[11:24:34 INFO]: [PlaceholderAPI] Successfully registered expansion: mentions [5.7.19]
[11:24:44 INFO]: [Deluxe Mentions] Successfully enabled v5.7.19
[11:24:44 INFO]: --------------------------------------------------------------------------------------
[11:24:44 INFO]:          Developed by Ruben_Artz
[11:24:44 INFO]: [Deluxe Mentions] Version: 5.7.19 is loading...
[11:24:44 INFO]: [Deluxe Mentions] Server: git-Paper-84 (MC: 1.20.1)
[11:24:44 INFO]: [Deluxe Mentions] Loading necessary files...
[11:24:44 INFO]: 
[11:24:44 INFO]: Deluxe Mentions Starting plugin...
[11:24:44 INFO]: 
[11:24:44 INFO]: [Deluxe Mentions] Successfully loaded files
[11:24:44 INFO]: 
[11:24:44 INFO]: --------------------------------------------------------------------------------------
[11:24:46 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[11:24:46 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[11:24:46 WARN]: [ItemsAdder] Detected legacy ItemsAdder pack (pre 3.3.0).
[11:24:46 WARN]: [ItemsAdder] Trying to load files, unexpected results might occur.
[11:24:46 WARN]: [ItemsAdder] It's adviced to follow the new guidelines: https://a.devs.beer/ia-new-guidelines-330
[11:24:46 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:no_recipe'. assets/_iainternal/textures/gui/no_recipe.png
[11:24:47 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:crafting'. assets/_iainternal/textures/gui/crafting.png
[11:24:47 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:cooking'. assets/_iainternal/textures/gui/cooking.png
[11:24:47 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:blank_menu'. assets/_iainternal/textures/gui/blank_menu.png
[11:24:47 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:anvil_repair'. assets/_iainternal/textures/gui/anvil_repair.png
[11:24:47 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:smithing'. assets/_iainternal/textures/gui/smithing.png
[11:24:48 INFO]: [InteractiveChat] Loaded all 1 languages!
[11:25:02 INFO]: [Citizens] Loaded 9 NPCs.
[11:25:02 INFO]: [Multiverse-Inventories] First run!
[11:25:03 INFO]: [QuickShop] Using economy system: EssentialsX Economy
[11:25:04 WARN]: [spark] Timed out waiting for world statistics
[11:25:05 WARN]: [ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
[11:25:05 INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.5]
[11:25:05 INFO]: [PlaceholderAPI] Successfully registered expansion: bungee [1.0.1]
[11:25:05 INFO]: [PlaceholderAPI] Successfully registered expansion: statistic [2.0.1]
[11:25:05 WARN]: [PlaceholderAPI] Cannot load expansion playerstats due to a missing plugin: PlayerStats
[11:25:05 INFO]: [PlaceholderAPI] Successfully registered expansion: pinger [1.0.1]
[11:25:06 INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms [5.4-R2]
[11:25:06 INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.8.1]
[11:25:06 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R1.MinecraftServer
[11:25:06 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[11:25:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[11:25:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[11:25:06 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[11:25:06 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[11:25:06 WARN]:        at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:63)
[11:25:06 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:25:06 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:25:06 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:25:06 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:25:06 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:25:06 WARN]:        at PlaceholderAPI-2.11.3 (1).jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:443)
[11:25:06 WARN]:        at PlaceholderAPI-2.11.3 (1).jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:173)
[11:25:06 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[11:25:06 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[11:25:06 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[11:25:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:25:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:25:06 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[11:25:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:25:06 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[11:25:06 WARN]:        at PlaceholderAPI-2.11.3 (1).jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:356)
[11:25:06 WARN]:        at PlaceholderAPI-2.11.3 (1).jar//me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
[11:25:06 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:25:06 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[11:25:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1112)
[11:25:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[11:25:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:25:06 INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.4.0]
[11:25:06 WARN]: [PlaceholderAPI] Cannot load expansion skript due to a missing plugin: Skript
[11:25:06 INFO]: [PlaceholderAPI] Successfully registered expansion: essentials [1.5.2]
[11:25:06 WARN]: [PlaceholderAPI] Cannot load expansion playertime due to a missing plugin: PlayerTime
[11:25:06 INFO]: [PlaceholderAPI] Successfully registered expansion: playerlist [3.0.3]
[11:25:06 INFO]: 9 placeholder hook(s) registered! 2 placeholder hook(s) have an update available.
[11:25:06 INFO]: [Deluxe Mentions] Using SQLite for player data.
[11:25:06 INFO]: Done (714.405s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[11:25:06 WARN]: Can't keep up! Is the server overloaded? Running 53788ms or 1075 ticks behind
[11:25:06 INFO]: Timings Reset
[11:25:12 INFO]: [ItemsAdder] Loaded 15 items
[11:25:12 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[11:25:12 INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[11:25:12 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[11:25:12 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[11:25:12 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[11:25:12 INFO]: [ItemsAdder] Used 26/6608 font_images
[11:25:13 INFO]: [ItemsAdder] [Init] Loaded 2 categories
[11:25:13 INFO]: [ItemsAdder] [Init] Loaded successfully.
[11:25:14 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[11:25:14 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[11:25:14 INFO]: [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
version
[11:27:15 INFO]: Checking version, please wait...
[11:27:16 WARN]: Can't keep up! Is the server overloaded? Running 100039ms or 2000 ticks behind
[11:27:16 INFO]: This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)
You are running the latest version
[11:27:20 ERROR]: [dough: skins] Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/fuckyhey
[11:27:20 WARN]: [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/fuckyhey
[11:27:20 WARN]: [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!

### Error (optional)

```shell
*d
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: betterranks
font_images:
  admin:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "admin.png"
    scale_ratio: 9
    y_position: 8
  mod:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "mod.png"
    scale_ratio: 9
    y_position: 8
  helper:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "helper.png"
    scale_ratio: 9
    y_position: 8
  player:
    permission: "betterranks.player"
    show_in_gui: true
    suggest_in_command: false
    path: "player.png"
    scale_ratio: 9
    y_position: 8
  builder:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "builder.png"
    scale_ratio: 9
    y_position: 8
  youtube:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "youtube.png"
    scale_ratio: 9
    y_position: 8
  patreon:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "patreon.png"
    scale_ratio: 9
    y_position: 8
  patreon2:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "patreon2.png"
    scale_ratio: 9
    y_position: 8
  java:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "java.png"
    scale_ratio: 9
    y_position: 8
  skript:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "skript.png"
    scale_ratio: 9
    y_position: 8
  developer:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "developer.png"
    scale_ratio: 9
    y_position: 8
  dev:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "dev.png"
    scale_ratio: 9
    y_position: 8
  vip:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "vip.png"
    scale_ratio: 9
    y_position: 8
  vipplus:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "vipplus.png"
    scale_ratio: 9
    y_position: 8
```

### Other files, you can drag and drop them here to upload. (optional)

*

### Screenshots/Videos (you can drag and drop files or paste links)

*

**Comment by SrathYT** [comment]
@LoneDev6 ?
