### ISSUE TITLE
Plugin disabling itself

### ISSUE THREAD

**Issue by Rashdonkey** [PluginBugs/Issues-ItemsAdder#2920]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Rashdonkey

### What happened?

Hello, I'm trying to install ItemsAdder (the most recent version), and it states that the latest version is compatible, but it is crashing due to no discernable reason.
I tried getting the next version, and this one doesn't work either. 

### Steps to reproduce the issue

See attachments above

### Server version

This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
You are running the latest version
Previous version: git-Paper-99 (MC: 1.20.1)

### ItemsAdder Version

Version: 3.5.0c-r3

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest (6).zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12208590/latest.6.zip)

### Error (optional)

```shell
[02:01:27] [Server thread/INFO]: SwampDonkey01 issued server command: /iazip
[02:01:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'iazip' in plugin ItemsAdder v3.5.0c-r3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[paper-1.20.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-100]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

-------------------------

[01:51:46] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.5.0c-r3
[01:51:46] [Votifier epoll boss/ERROR]: [null] Votifier was not able to bind to /192.3.152.87:8192
com.vexsoftware.votifier.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address
[01:51:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[01:51:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[01:51:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[01:51:46] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.5.0c-r3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.25
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-100 (MC: 1.20.1)
                                               
[01:51:46] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.5.0c-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/sourcewriters/spigot/rwg/legacy/api/compatibility/AddonInitializationException
	at dev.lone.itemsadder.Main.onEnable(SourceFile:390) ~[ItemsAdder_3.5.0c-r3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-100]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-100]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.sourcewriters.spigot.rwg.legacy.api.compatibility.AddonInitializationException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[01:51:46] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.5.0c-r3

-----------------------------

[30.07 01:34:37] [Server] [ERROR] Error occurred while enabling ItemsAdder v3.5.0c-r2 (Is it up to date?)
[30.07 01:34:37] [Server] java.lang.NoClassDefFoundErrornet/sourcewriters/spigot/rwg/legacy/api/compatibility/AddonInitializationException
[30.07 01:34:37] [Server]   at dev.lone.itemsadder.Main.onEnable(SourceFile:390) ~[ItemsAdder_3.5.0c-r2.jar:?]
[30.07 01:34:37] [Server]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[30.07 01:34:37] [Server]   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[30.07 01:34:37] [Server]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
[30.07 01:34:37] [Server]   at java.lang.Thread.run(Thread.java:833) ~[?:?]
[30.07 01:34:37] [Server] Caused byjava.lang.ClassNotFoundException: net.sourcewriters.spigot.rwg.legacy.api.compatibility.AddonInitializationException
[30.07 01:34:37] [Server]   at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[30.07 01:34:37] [Server]   at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[30.07 01:34:37] [Server]   at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[30.07 01:34:37] [Server]   ... more
[30.07 01:34:37] [Server] [INFO] [ItemsAdder] Disabling ItemsAdder v3.5.0c-r2
```

**Comment by LoneDev6** [comment]
Contact RWG developer about why this class doesn't exists anymore: `NoClassDefFoundError: net/sourcewriters/spigot/rwg/legacy/api/compatibility/AddonInitializationException`
Link them this issue report.

**Comment by LoneDev6** [comment]
Let me know if the issue was fixed by the RWG developer or if i have to do anything. 
Thanks

**Comment by Rashdonkey** [comment]
Apparently, RWG was outdated and wouldn't support anything after 1.17, and somehow that made ItemsAdder stop working. I've removed RWG completely and that solved the issue. I have no clue why that would happen but all is good! Thanks :)

**Comment by Lauriichan** [comment]
@LoneDev6 you might want to add a isEnabled check for the RWG compatibility because RWG disables itself everything higher than 1.17.1

Once we finally rewrote the plugin there sadly will be an api update cause well full plugin rewrite x)

**Comment by LoneDev6** [comment]
dw, just hit me up when the API will be updated so I can discard the old implementation and hook the new one
