### ISSUE TITLE
Could not pass event ArmorEquipEvent

### ISSUE THREAD

**Issue by yngdrms** [PluginBugs/Issues-ItemsAdder#2924]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yngdrms

### What happened?

After death with cosmetic items from the Magic Cosmetics plugin, an error occurs in the console.

### Steps to reproduce the issue

1. Install ItemsAdder + LoneLibs
2. Install MagicCosmetics
3. Put on a cosmetic item and die from any way

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"b0d4eb6" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r3

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-652

### LoneLibs Version

LoneLibs version 1.0.25

### Error (optional)

```shell
[14:05:53 ERROR]: Could not pass event ArmorEquipEvent to ItemsAdder v3.5.0c-r3
java.lang.NullPointerException: Cannot invoke "dev.lone.LoneLibs.armorequip.ArmorType.ordinal()" because "<parameter1>" is null
        at ia.m.jI.a(SourceFile:1419) ~[?:?]
        at ia.m.dX.a(SourceFile:93) ~[?:?]
        at ia.m.dX.a(SourceFile:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(:40) ~[server.jar:git-Airplane-"b0d4eb6"]
        at co.aikar.timings.TimedEventExecutor.execute(:76) ~[server.jar:git-Airplane-"b0d4eb6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(:70) ~[server.jar:git-Airplane-"b0d4eb6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:624) ~[server.jar:git-Airplane-"b0d4eb6"]
        at dev.lone.LoneLibs.armorequip.ArmorListener.playerDeathEvent(ArmorListener.java:270) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1098.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(:69) ~[server.jar:git-Airplane-"b0d4eb6"]
        at co.aikar.timings.TimedEventExecutor.execute(:76) ~[server.jar:git-Airplane-"b0d4eb6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(:70) ~[server.jar:git-Airplane-"b0d4eb6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:624) ~[server.jar:git-Airplane-"b0d4eb6"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(:892) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(:1001) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(:1393) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(:903) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(:1181) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(:1230) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(:2285) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(:2536) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(:55) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(:12) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(:55) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.TickTask.run(:18) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(:136) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(:23) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(:109) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(:1337) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(:1330) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(:119) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(:1306) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1150) ~[server.jar:git-Airplane-"b0d4eb6"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289) ~[server.jar:git-Airplane-"b0d4eb6"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by luizsusin** [comment]
Just as a comment: I have the same issue on Purpur 1.20.1 with CosmeticsCore instead of MagicCosmetics.

**Comment by LoneDev6** [comment]
Update to r4.
