### ISSUE TITLE
Cannot boot up with AdvancedSlimeWorldManager

### ISSUE THREAD

**Issue by CarmJos** [PluginBugs/Issues-ItemsAdder#2936]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I'm using AdvancedSlimeWorldManager (Not ASP) with newest ItemsAdder, and i got errors.

I'm a minigame developer which must use my own server jar (version 1.18.2), but ASP must use it own jar, that's why i use "AdvancedSlimeWorldManager", which supports by using classfier.

### Steps to reproduce the issue

1. Install "aswm" and "ItemsAdder".
2. Boot up the server.

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-388 (MC: 1.18.2)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.5.0c-r3

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

 LoneLibs version 1.0.25

### FULL server log

```text
WARNING: Using incubator modules: jdk.incubator.vector
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8+7) Host: Linux 4.15.0-213-generic (amd64)
Loading libraries, please wait...
[02:42:41 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[02:42:43 INFO]: Loaded 7 recipes
[02:42:44 INFO]: Starting minecraft server version 1.18.2
[02:42:44 WARN]: ****************************
[02:42:44 WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[02:42:44 WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[02:42:44 WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[02:42:44 WARN]: ****************************
[02:42:44 INFO]: Loading properties
[02:42:44 INFO]: This server is running Purpur version git-Purpur-1632 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: dc4a29b on HEAD)
[02:42:44 INFO]: Server Ping Player Sample Count: 12
[02:42:44 INFO]: Using 4 threads for Netty based IO
[02:42:44 WARN]: [Pufferfish] To improve performance, timings have been disabled by default
[02:42:44 WARN]: [Pufferfish] You can still use timings by using /timings on, but they will not start on server startup unless you set timings.really-enabled to true in paper.yml
[02:42:44 WARN]: [Pufferfish] If you would like to disable this message, either set timings.really-enabled to true or timings.enabled to false.
[02:42:44 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[02:42:44 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[02:42:44 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[02:42:44 INFO]: Default game type: ADVENTURE
[02:42:44 INFO]: Generating keypair
[02:42:45 INFO]: Starting Minecraft server on 0.0.0.0:25507
[02:42:45 INFO]: Using epoll channel type
[02:42:45 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[02:42:45 INFO]: Paper: Using Java cipher from Velocity.
[02:42:46 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[02:42:51 WARN]: Legacy plugin PurpleChat v1.1.1 does not specify an api-version.
[02:42:51 INFO]: [WorldEdit] Loading WorldEdit v7.2.13+46576cc
[02:42:52 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@2ebf3be1]
[02:42:52 INFO]: [SlimeWorldManager] Loading SlimeWorldManager v2.10.0
[02:42:52 INFO]: [com.grinderwolf.swm.internal.hikari.HikariDataSource] HikariPool-1 - Starting...
[02:42:52 INFO]: [com.grinderwolf.swm.internal.hikari.pool.HikariPool] HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@1f978008
[02:42:52 INFO]: [com.grinderwolf.swm.internal.hikari.HikariDataSource] HikariPool-1 - Start completed.
[02:42:53 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.3
[02:42:55 INFO]: [ServerTeleport] Loading ServerTeleport v1.0.0
[02:42:55 INFO]: [ViaVersion] Loading ViaVersion v4.7.0
[02:42:55 INFO]: [ViaVersion] ViaVersion 4.7.0 is now loaded. Registering protocol transformers and injecting...
[02:42:55 INFO]: [ViaVersion] Loading block connection mappings ...
[02:42:56 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[02:42:56 INFO]: [ViaBackwards] Loading translations...
[02:42:56 INFO]: [ViaBackwards] Registering protocols...
[02:42:56 INFO]: [ViaBackwards] Loading ViaBackwards v4.7.0
[02:42:56 INFO]: [LuckPerms] Loading LuckPerms v5.4.98
[02:42:56 INFO]: [NametagEdit] Loading NametagEdit v4.5.20
[02:42:56 INFO]: [LoneLibs] Loading LoneLibs v1.0.25
[02:42:56 INFO]: [ProtocolLib] Loading ProtocolLib v5.1.0-SNAPSHOT-661
[02:42:57 INFO]: [ItemsAdder] Loading ItemsAdder v3.5.0c-r3
[02:42:58 INFO]: [DecentHolograms] Loading DecentHolograms v2.8.3
[02:42:58 INFO]: [PlugManX] Loading PlugManX v2.3.0
[02:42:58 INFO]: true
[02:42:58 INFO]: Server permissions file permissions.yml is empty, ignoring it
[02:42:58 INFO]: [WorldEdit] Enabling WorldEdit v7.2.13+46576cc
[02:42:58 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[02:42:58 INFO]: WEPIF: Using the Bukkit Permissions API.
[02:42:58 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R2.PaperweightAdapter as the Bukkit adapter
[02:42:59 INFO]: [LuckPerms] Enabling LuckPerms v5.4.98
[02:43:00 INFO]:         __    
[02:43:00 INFO]:   |    |__)   LuckPerms v5.4.98
[02:43:00 INFO]:   |___ |      Running on Bukkit - Purpur
[02:43:00 INFO]: 
[02:43:00 INFO]: [LuckPerms] Loading configuration...
[02:43:00 INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[02:43:00 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[02:43:00 WARN]: [LuckPerms] Loaded class org.mariadb.jdbc.Driver from MineSQL v1.4.1 which is not a depend or softdepend of this plugin.
[02:43:01 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[02:43:01 INFO]: [LuckPerms] Loading messaging service... [REDIS]
[02:43:01 INFO]: [LuckPerms] Loading internal permission managers...
[02:43:02 INFO]: [LuckPerms] Performing initial data load...
[02:43:02 INFO]: [LuckPerms] Successfully enabled. (took 2468ms)
[02:43:02 INFO]: [LoneLibs] Enabling LoneLibs v1.0.25
[02:43:02 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0-SNAPSHOT-661
[02:43:02 INFO]: [PlugManX] Enabling PlugManX v2.3.0
[02:43:03 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[02:43:03 WARN]: The server will make no attempt to authenticate usernames. Beware.
[02:43:03 WARN]: Whilst this makes it possible to use BungeeCord or Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[02:43:03 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[02:43:03 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[02:43:03 INFO]: Preparing level "world"
[02:43:03 INFO]: Preparing start region for dimension minecraft:overworld
[02:43:03 INFO]: Time elapsed: 376 ms
[02:43:03 INFO]: [SlimeWorldManager] Enabling SlimeWorldManager v2.10.0
[02:43:04 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[02:43:04 INFO]: [PlaceholderAPI] Fetching available expansion information...
[02:43:04 INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2596)
[02:43:05 INFO]: [Skulls] Enabling Skulls v3.9.0
[02:43:05 INFO]:  
[02:43:05 INFO]: =============================
[02:43:05 INFO]: Skulls v3.9.0 by Tweetzy
[02:43:05 INFO]: Developer: Kiran Hart
[02:43:05 INFO]: [FlightCore] Enabling metrics for Skulls
[02:43:05 INFO]: =============================
[02:43:05 INFO]:  
[02:43:05 INFO]: [DeluxeMenus] Enabling DeluxeMenus v1.13.5-Release
[02:43:05 INFO]: [DeluxeMenus] Successfully hooked into PlaceholderAPI!
[02:43:06 WARN]: [DeluxeMenus] command: menu specified for menu: menu already exists for another menu!
[02:43:06 WARN]: [DeluxeMenus] Skipping command: menu in menu: menu
[02:43:06 WARN]: [DeluxeMenus] command: store specified for menu: test already exists for another menu!
[02:43:06 WARN]: [DeluxeMenus] Skipping command: store in menu: test
[02:43:06 INFO]: [DeluxeMenus] 5 GUI menus loaded!
[02:43:06 INFO]: [DeluxeMenus] You are running the latest version of DeluxeMenus!
[02:43:06 INFO]: [PlaceholderAPI] Successfully registered expansion: deluxemenus [1.13.5-Release]
[02:43:06 INFO]: [ViaVersion] Enabling ViaVersion v4.7.0
[02:43:06 INFO]: [ViaVersion] ViaVersion detected server version: 1.18.2 (758)
[02:43:06 INFO]: [ViaBackwards] Enabling ViaBackwards v4.7.0
[02:43:06 INFO]: [NametagEdit] Enabling NametagEdit v4.5.20
[02:43:06 INFO]: [NametagEdit] Successfully loaded using bukkit version: v1_18_R1
[02:43:06 INFO]: [NametagEdit] Found LuckPerms! Hooking in.
[02:43:06 INFO]: [ItemsAdder] Enabling ItemsAdder v3.5.0c-r3
[02:43:06 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
[02:43:06 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_18_R2' loaded!
[02:43:06 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[02:43:06 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.5.0c-r3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.25
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1632 (MC: 1.18.2)
                                               
[02:43:06 ERROR]: Error occurred while enabling ItemsAdder v3.5.0c-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/infernalsuite/aswm/api/SlimePlugin
        at dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.<init>(SourceFile:21) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.init(SourceFile:16) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:441) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.infernalsuite.aswm.api.SlimePlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 14 more
[02:43:06 INFO]: [ItemsAdder] Disabling ItemsAdder v3.5.0c-r3
```

### Error (optional)

```shell
I'm using AdvancedSlimeWorldManager (Not ASP because I must use my own server jar) with newest ItemsAdder, but i got this error:


[02:43:06 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.5.0c-r3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.25
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1632 (MC: 1.18.2)
                                               
[02:43:06 ERROR]: Error occurred while enabling ItemsAdder v3.5.0c-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/infernalsuite/aswm/api/SlimePlugin
        at dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.<init>(SourceFile:21) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.AdvancedSlimePaperWrapper.init(SourceFile:16) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:441) ~[ItemsAdder_3.5.0c-r3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.infernalsuite.aswm.api.SlimePlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 14 more
```

### Other files, you can drag and drop them here to upload. (optional)

[slimeworldmanager.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12263796/slimeworldmanager.zip)

**Comment by phquathi** [comment]
me too

**Comment by LoneDev6** [comment]
Are you using the latest AdvancedSlimeWorldManager paper fork?
ItemsAdder is compatible only with AdvancedSlimeWorldManager paper fork.

How to install: https://github.com/InfernalSuite/AdvancedSlimePaper/blob/main/.docs/usage/install.md

**Comment by CarmJos** [comment]
I'm a minigame developer which must use my own server jar (version 1.18.2), but ASP must use it own jar, that's why i use "AdvancedSlimeWorldManager", which supports by using classfier.
