### ISSUE TITLE
Could not pass event ProjectileLaunchEvent

### ISSUE THREAD

**Issue by GsTio86** [PluginBugs/Issues-ItemsAdder#2952]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

galen86

### What happened?

When I use Snow ball and Ender Pearl, I get an error in the console

### Steps to reproduce the issue

Demo: https://gyazo.com/2ea84f688b2b3fe861d06a571fb420b4

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/74390539/37ef4b7a-63a3-4e3e-af1c-76e9de57ebd8)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/74390539/e6209208-40fd-48b9-b07d-e16212984072)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/74390539/b600fc53-3136-4e1e-ab4a-5f1150a684d2)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/74390539/025a02a6-3b49-433e-adfe-f4f024f62632)

### FULL server log

https://pastebin.com/raw/FpwEHEuY

### Error (optional)

```shell
[09Aug2023 15:15:51.878] [Server thread/ERROR] [Minecraft/]: Could not pass event ProjectileLaunchEvent to ItemsAdder v3.5.0c-r4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactoryMixin.java:1188) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactoryMixin.java:590) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at net.minecraft.world.server.ServerWorld.handler$bdp000$arclight$addEntityEvent(ServerWorldMixin.java:1803) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorldMixin.java:814) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorldMixin.java:755) ~[?:?]
	at net.minecraft.item.EnderPearlItem.func_77659_a(EnderPearlItemMixin.java:538) ~[?:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStackMixin.java:216) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManagerMixin.java:287) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandlerMixin.java:2268) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacketMixin.java:31) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacketMixin.java:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.md747f08$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1920) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.item.Item net.minecraft.entity.projectile.ProjectileItemEntity.getDefaultItemPublic()'
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftThrowableProjectile.getItem(CraftThrowableProjectile.java:18) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-0203c08f]
	at ia.nms.aG.aL.a(SourceFile:230) ~[?:?]
	at ia.m.jI.a(SourceFile:1175) ~[?:?]
	at ia.m.dd.b(SourceFile:335) ~[?:?]
	... 28 more
```

**Comment by LoneDev6** [comment]
It's not normal, your custom Spigot fork somehow doesn't have `getDefaultItemPublic` method which is internally called by `ThrowableProjectile.getItem()`.
You should ask to the devs of that Spigot fork.
