### ISSUE TITLE
ItemsAdder Error console

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#2962]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

belzzebuh

### What happened?

The console sometimes throws this error spontaneously:

```
[14:34:10 WARN]: [ItemsAdder] Task #11273676 for ItemsAdder v3.5.0c-r4 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.type.NoteBlock (org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData and org.bukkit.block.data.type.NoteBlock are in unnamed module of loader java.net.URLClassLoader @18769467)
        at ia.m.cD.l(SourceFile:552) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.a(SourceFile:547) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.k(SourceFile:538) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.v(SourceFile:242) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Steps to reproduce the issue

.

### Server version

git-Purpur-1985 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.5.0c-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-665

### LoneLibs Version

LoneLibs version 1.0.25

### Error (optional)

```shell
[14:34:10 WARN]: [ItemsAdder] Task #11273676 for ItemsAdder v3.5.0c-r4 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.type.NoteBlock (org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData and org.bukkit.block.data.type.NoteBlock are in unnamed module of loader java.net.URLClassLoader @18769467)
        at ia.m.cD.l(SourceFile:552) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.a(SourceFile:547) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.k(SourceFile:538) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at ia.m.cD.v(SourceFile:242) ~[ItemsAdder_3.5.0c-r4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by LoneDev6** [comment]
I cannot reproduce it but it should be fixed in the upcoming update
