### ISSUE TITLE
Entity error NEED HELP

### ISSUE THREAD

**Issue by UBUB0X-Dev** [PluginBugs/Issues-ItemsAdder#2964]
### Terms

- [ ] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [ ] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ububoxthebest

### What happened?

After following the steps indicated once done /iaentity summon <nome> ese the following inscription "An internal error occurred while attemping to perform this command"

### Steps to reproduce the issue

Follow this step

https://itemsadder.devs.beer/plugin-usage/adding-content/mobs/advanced-method/creation

### Server version

This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information

### ItemsAdder Version

3.3.0-beta-r10

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### Error (optional)

```shell
[21:26:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iaentity' in plugin ItemsAdder v3.3.0-beta-r10
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Paper-788]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-788]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at dev.lone.itemsadder.main.at.a(SourceFile:235) ~[?:?]
	at dev.lone.itemsadder.main.at.a(SourceFile:178) ~[?:?]
	at dev.lone.itemsadder.main.at.a(SourceFile:168) ~[?:?]
	at dev.lone.itemsadder.main.at.a(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.main.ar.a(SourceFile:459) ~[?:?]
	at dev.lone.itemsadder.main.ar.a(SourceFile:391) ~[?:?]
	at dev.lone.itemsadder.main.he.onCommand(SourceFile:181) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
	... 19 more
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/141836746/fe663c52-47a7-479e-87e9-01f280530b15)

**Comment by UBUB0X-Dev** [comment]
@LoneDev6 pls help me

**Comment by LoneDev6** [comment]
Update your plugin before reporting issues.
