### ISSUE TITLE
TORCHFLOWER SEEDS

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2983]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DinoBoss#6985

### What happened?

The plugin should detect vanilla materials and allow us to use their custom data model, but it seems that this material doesn't work for it.

### Steps to reproduce the issue

1) Create a configuration of items with models and model_id.
2) Place a material of type: TORCHFLOWER_SEEDS

### Server version

[01:56:39 INFO]: Checking version, please wait...
[01:56:42 INFO]: This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)
You are running the latest version

### ItemsAdder Version

> ver Itemsadder
[01:56:58 INFO]: ItemsAdder version 3.5.0c-r4
[01:56:58 INFO]: Customized Minecraft without client mods!
[01:56:58 INFO]: Website: devs.beer
[01:56:58 INFO]: Author: LoneDev

### ProtocolLib Version

> ver ProtocolLib
[01:57:40 INFO]: ProtocolLib version 5.1.0
[01:57:40 INFO]: Provides read/write access to the Minecraft protocol.
[01:57:40 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> ver lonelib
[01:57:53 INFO]: LoneLibs version 1.0.25
[01:57:53 INFO]: Collection of libs used by my plugins
[01:57:53 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/XnqUVnA

### Error (optional)

```shell
[01:50:58 ERROR]: [ItemsAdder] Error reading vanilla model for material TORCHFLOWER_SEEDS, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/torchflower_seeds.json'
[01:50:58 ERROR]: [ItemsAdder] Choose another material, TORCHFLOWER_SEEDS is not supported for these items: ui:metals, ui:factory, ui:mechanics, ui:accounting, ui:accountingtwo, ui:mechanicstwo...and more
[01:50:58 ERROR]: [Citizens] El rasgo eglow fallo al cargar la ID del NPC: 3.
[01:50:58 ERROR]: [Citizens] El rasgo eglow fallo al cargar la ID del NPC: 12.
[01:50:58 INFO]: [Mythic] Reloading plugin...
[01:50:58 ERROR]: [ItemsAdder] Model file 'ui/models/blank:auto_generated/blank.json' not found in any pack for item 'ui:blank'. File: /contents/animeworld/configs/ui/ui_item.yml
[01:50:58 INFO]: [MythicMobs] Loading Packs...
[01:50:59 INFO]: [MythicMobs] Loading Items...
[01:50:59 INFO]: [MythicMobs] Loading Item Groups...
[01:50:59 INFO]: [MythicMobs] Loading Skills...
[01:50:59 ERROR]: [ItemsAdder] Failed to process item file: torchflower_seeds
[01:50:59 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonArray(String)" because "<parameter1>" is null
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:318)
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iZ.b(SourceFile:329)
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.cz(SourceFile:998)
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2708)
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.hM.a(SourceFile:86)
[01:50:59 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.G.a(SourceFile:2463)
[01:50:59 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:50:59 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:50:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:50:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:50:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:50:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:50:59 ERROR]: [ItemsAdder] Failed to validate model: contents/animeworld/resourcepack/assets/ui/models/item/paper.json
[01:50:59 ERROR]: [ItemsAdder] com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 108 path $
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ui
items:
  oil:
    display_name: "oil"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6001
      generate: false
      model_path: "item/icons/research/oil"
  metals:
    display_name: "metals"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6002
      generate: false
      model_path: "item/icons/research/metals"
  factory:
    display_name: "factory"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6003
      generate: false
      model_path: "item/icons/research/factory"
  mechanics:
    display_name: "mechanics"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6004
      generate: false
      model_path: "item/icons/research/mechanics"
  accounting:
    display_name: "accounting"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6005
      generate: false
      model_path: "item/icons/research/accounting"
  accountingtwo:
    display_name: "accountingtwo"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6006
      generate: false
      model_path: "item/icons/research/accountingtwo"
  mechanicstwo:
    display_name: "mechanicstwo"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6007
      generate: false
      model_path: "item/icons/research/mechanicstwo"
  goldingot:
    display_name: "goldingot"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6008
      generate: false
      model_path: "item/icons/research/goldingot"
  gasoline:
    display_name: "gasoline"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6009
      generate: false
      model_path: "item/icons/research/gasoline"
  uranium:
    display_name: "uranium"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6010
      generate: false
      model_path: "item/icons/research/uranium"
  diamond:
    display_name: "diamond"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6011
      generate: false
      model_path: "item/icons/research/diamond"
  netherite:
    display_name: "netherite"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6012
      generate: false
      model_path: "item/icons/research/netherite"
  hydrogen:
    display_name: "hydrogen"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6013
      generate: false
      model_path: "item/icons/aresearch/hydrogen"
  accountingthree:
    display_name: "accountingthree"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6014
      generate: false
      model_path: "item/icons/research/accountingthree"
  mechanicsthree:
    display_name: "mechanicsthree"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6015
      generate: false
      model_path: "item/icons/research/mechanicsthree"
  timerone:
    display_name: "timerone"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6016
      generate: false
      model_path: "item/icons/research/timerone"
  timertwo:
    display_name: "timertwo"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6017
      generate: false
      model_path: "item/icons/research/timertwo"
  timerthree:
    display_name: "timerthree"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6018
      generate: false
      model_path: "item/icons/research/timerthree"
  timerfour:
    display_name: "timerfour"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 6019
      generate: false
      model_path: "item/icons/research/timerfour"
  milestones1n:
    display_name: "milestones1n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7001
      generate: false
      model_path: "item/icons/milestones/milestones1n"
  milestones1green:
    display_name: "milestones1green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7002
      generate: false
      model_path: "item/icons/milestones/milestones1green"
  milestones1orange:
    display_name: "milestones1orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7003
      generate: false
      model_path: "item/icons/milestones/milestones1orange"
  milestones2n:
    display_name: "milestones2n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7004
      generate: false
      model_path: "item/icons/milestones/milestones2n"
  milestones2green:
    display_name: "milestones2green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7005
      generate: false
      model_path: "item/icons/milestones/milestones2green"
  milestones2orange:
    display_name: "milestones2orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7006
      generate: false
      model_path: "item/icons/milestones/milestones2orange"
  milestones2red:
    display_name: "milestones2red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7007
      generate: false
      model_path: "item/icons/milestones/milestones2red"
  milestones3n:
    display_name: "milestones3n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7008
      generate: false
      model_path: "item/icons/milestones/milestones3n"
  milestones3green:
    display_name: "milestones3green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7009
      generate: false
      model_path: "item/icons/milestones/milestones3green"
  milestones3orange:
    display_name: "milestones3orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7010
      generate: false
      model_path: "item/icons/milestones/milestones3orange"
  milestones3red:
    display_name: "milestones3red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7011
      generate: false
      model_path: "item/icons/milestones/milestones3red"
  milestones4n:
    display_name: "milestones4n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7012
      generate: false
      model_path: "item/icons/milestones/milestones4n"
  milestones4green:
    display_name: "milestones4green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7013
      generate: false
      model_path: "item/icons/milestones/milestones4green"
  milestones4orange:
    display_name: "milestones4orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7014
      generate: false
      model_path: "item/icons/milestones/milestones4orange"
  milestones4red:
    display_name: "milestones4red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7015
      generate: false
      model_path: "item/icons/milestones/milestones4red"
  milestones5n:
    display_name: "milestones5n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7016
      generate: false
      model_path: "item/icons/milestones/milestones5n"
  milestones5green:
    display_name: "milestones5green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7017
      generate: false
      model_path: "item/icons/milestones/milestones5green"
  milestones5orange:
    display_name: "milesstones5orage"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7018
      generate: false
      model_path: "item/icons/milestones/milestones5orange"
  milestones5red:
    display_name: "milestones5red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7019
      generate: false
      model_path: "item/icons/milestones/milestones5red"
  milestones6n:
    display_name: "milestones6n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7020
      generate: false
      model_path: "item/icons/milestones/milestones6n"
  milestones_milestones6green:
    display_name: "milestones6green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7021
      generate: false
      model_path: "item/icons/milestones/milestones6green"
  milestones_milestones6orange:
    display_name: "milestones_milestones6orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7022
      generate: false
      model_path: "item/icons/milestones/milestones6orange"
  milestones6red:
    display_name: "milestones6red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7023
      generate: false
      model_path: "item/icons/milestones/milestones6red"
  milestones7n:
    display_name: "milestones7n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7024
      generate: false
      model_path: "item/icons/milestones/milestones7n"
  milestones7green:
    display_name: "milestones7green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7025
      generate: false
      model_path: "item/icons/milestones/milestones7green"
  milestones7orange:
    display_name: "milestones7orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7026
      generate: false
      model_path: "item/icons/milestones/milestones7orange"
  milestones7red:
    display_name: "milestones7red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7027
      generate: false
      model_path: "item/icons/milestones/milestones7red"
  milestones8n:
    display_name: "milestones8n"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7028
      generate: false
      model_path: "item/icons/milestones/milestones8n"
  milestones8green:
    display_name: "milestones8green"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7029
      generate: false
      model_path: "item/icons/milestones/milestones8green"
  milestones8orange:
    display_name: "milestones8orange"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7030
      generate: false
      model_path: "item/icons/milestones/milestones8orange"
  milestones8red:
    display_name: "milestones8red"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 7031
      generate: false
      model_path: "item/icons/milestones/milestones8red"
  loockedwheat:
    display_name: "loockedwheat"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8001
      generate: false
      model_path: "item/icons/lockedfactories/lockedwheat"
  lockedbook:
    display_name: "lockedbook"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8002
      generate: false
      model_path: "item/icons/lockedfactories/lockedbook"
  lockedbrick:
    display_name: "lockedbrick"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8003
      generate: false
      model_path: "item/icons/lockedfactories/lockedbrick"
  lockedcharcoal:
    display_name: "lockedcharcoal"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8004
      generate: false
      model_path: "item/icons/lockedfactories/lockedcharcoal"
  lockedcopperingot:
    display_name: "lockedcopperingot"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8005
      generate: false
      model_path: "item/icons/lockedfactories/lockedcopperingot"
  lockeddiamond:
    display_name: "lockeddiamond"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8006
      generate: false
      model_path: "item/icons/lockedfactories/lockeddiamond"
  lockedfirework:
    display_name: "lockedfirework"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8007
      generate: false
      model_path: "item/icons/lockedfactories/lockedfirework"
  lockedgasoline:
    display_name: "lockedgasoline"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8008
      generate: false
      model_path: "item/icons/lockedfactories/lockedgasoline"
  lockedgoldingot:
    display_name: "lockedgoldingot"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8009
      generate: false
      model_path: "item/icons/lockedfactories/lockedgoldingot"
  lockedhydrogen:
    display_name: "lockedhydrogen"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8010
      generate: false
      model_path: "item/icons/lockedfactories/lockedhydrogen"
  lockedironingot:
    display_name: "lockedironingot"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8011
      generate: false
      model_path: "item/icons/lockedfactories/lockedironingot"
  lockeditemframe:
    display_name: "lockeditemframe"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8012
      generate: false
      model_path: "item/icons/lockedfactories/lockeditemframe"
  lockednetherite:
    display_name: "lockednetherite"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8013
      generate: false
      model_path: "item/icons/lockedfactories/lockednetherite"
  lockednetherstar:
    display_name: "lockednetherstar"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8014
      generate: false
      model_path: "item/icons/lockedfactories/lockednetherstar"
  lockedoil:
    display_name: "lockedoil"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8015
      generate: false
      model_path: "item/icons/lockedfactories/lockedoil"
  lockedquartz:
    display_name: "lockedquartz"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8016
      generate: false
      model_path: "item/icons/lockedfactories/lockedquartz"
  lockedstring:
    display_name: "lockedstring"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8017
      generate: false
      model_path: "item/icons/lockedfactories/lockedstring"
  lockeduranium:
    display_name: lockeduranium"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8018
      generate: false
      model_path: "item/icons/lockedfactories/lockeduranium"
  lockedarrow:
    display_name: "lockedarrow"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 8019
      generate: false
      model_path: "item/icons/lockedfactories/lockedarrow"
  blank:
    display_name: "blank"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10007
      generate: false
      model_path: "blank:auto_generated/blank"
  processone:
    display_name: "processone"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10061
      generate: false
      model_path: "item/icons/processone"
  processtwo:
    display_name: "processtwo"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10062
      generate: false
      model_path: "item/icons/processtwo"
  processthree:
    display_name: "processthree"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10063
      generate: false
      model_path: "item/icons/processthree"
  package:
    display_name: "package"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10064
      generate: false
      model_path: "item/icons/package"
  lock:
    display_name: "lock"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10065
      generate: false
      model_path: "item/icons/lock"
  lockopen:
    display_name: "lockopen"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10066
      generate: false
      model_path: "item/icons/lockopen"
  oil:
    display_name: "oil"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10067
      generate: false
      model_path: "item/icons/oil"
  gasoline:
    display_name: gasoline
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10068
      generate: false
      model_path: "item/icons/gasoline"
  hydrogen:
    display_name: "hydrogen"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10069
      generate: false
      model_path: "item/icons/hydrogen"
  uranium:
    display_name: "uranium"
    permission: a.ui
    resource:
      material: TORCHFLOWER_SEEDS
      model_id: 10070
      generate: false
      model_path: "item/icons/uranium"
```

**Comment by LoneDev6** [comment]
Hello!
Should be fixed by this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2867
