### ISSUE TITLE
Circular load order

### ISSUE THREAD

**Issue by bladeRR** [PluginBugs/Issues-ItemsAdder#2995]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

i am setting up ia with mythicmobs and other plugins and my server crashes.
[latest (4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12562242/latest.4.log)

### Steps to reproduce the issue

I put ia and it generates a "circular load order" and the other plugins stop working and the server crashes.

### Server version

[17:17:11 INFO]: This server is running Paper version git-Paper-171 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 33bec7f)
You are running the latest version
Previous version: git-Paper-95 (MC: 1.20.1)

### ItemsAdder Version

17:17:28 INFO]: ItemsAdder version 3.5.0c-r4b
[17:17:28 INFO]: Customized Minecraft without client mods!
[17:17:28 INFO]: Website: devs.beer
[17:17:28 INFO]: Author: LoneDev

### ProtocolLib Version

17:17:44 INFO]: ProtocolLib version 5.1.0
[17:17:44 INFO]: Provides read/write access to the Minecraft protocol.
[17:17:44 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:17:59 INFO]: LoneLibs version 1.0.25
[17:17:59 INFO]: Collection of libs used by my plugins
[17:17:59 INFO]: Authors: LoneDev and others

### FULL server log

[latest (4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12562257/latest.4.log)

### Error (optional)

```shell
[14:13:30] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[14:13:30] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[14:13:30] [Server thread/ERROR]: [SimpleProviderStorage]   ItemsAdder -> MythicMobs -> Multiverse-Core -> CMI -> HyronicFriends -> ItemsAdder
[14:13:30] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[14:13:30] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[14:13:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins ItemsAdder
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.1.jar:git-Paper-171]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[paper-1.20.1.jar:git-Paper-171]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-171]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.1.jar:git-Paper-171]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-171]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-171]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

[latest (4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12562260/latest.4.log)
<img width="1154" alt="Captura de Pantalla 2023-09-08 a la(s) 8 16 09" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/63523864/fd7ad722-b151-4726-833e-bc4b1d46f9b0">

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2363#issuecomment-1448287859
