### ISSUE TITLE
BlockDestroyEvent and PlayerInteractEvent

### ISSUE THREAD

**Issue by khoiangel** [PluginBugs/Issues-ItemsAdder#3003]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

KidoAkira#5896

### What happened?

i spaming me with those bugs on console

### Steps to reproduce the issue

it just randomly appear on my console

### Server version

Current: git-Purpur-2053 (MC: 1.20.1)*

### ItemsAdder Version

ItemsAdder version 3.5.0c-r4b

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-668

### LoneLibs Version

 LoneLibs version 1.0.25

### FULL server log

[latest (4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12589772/latest.4.log)

### Error (optional)

```shell
Could not pass event BlockDestroyEvent to ItemsAdder v3.5.0c-r4b
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eM.a(SourceFile:96)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eM.a(SourceFile:58)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eC.h(SourceFile:73)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.cb.a(SourceFile:35)
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at org.bukkit.event.Event.callEvent(Event.java:45)
	at net.minecraft.world.level.World.a(World.java:844)
	at net.minecraft.world.level.IWorldWriter.a(IWorldWriter.java:23)
	at net.minecraft.world.entity.ai.behavior.BehaviorFarm.c(BehaviorFarm.java:114)
	at net.minecraft.world.entity.ai.behavior.BehaviorFarm.c(BehaviorFarm.java:34)
	at net.minecraft.world.entity.ai.behavior.Behavior.f(Behavior.java:77)
	at net.minecraft.world.entity.ai.behavior.BehaviorGate.f(BehaviorGate.java:67)
	at net.minecraft.world.entity.ai.BehaviorController.e(BehaviorController.java:445)
	at net.minecraft.world.entity.ai.BehaviorController.a(BehaviorController.java:390)
	at net.minecraft.world.entity.npc.EntityVillager.customServerAiStep(EntityVillager.java:354)
	at net.minecraft.world.entity.npc.EntityVillager.W(EntityVillager.java:340)
	at net.minecraft.world.entity.EntityInsentient.fc(EntityInsentient.java:966)
	at net.minecraft.world.entity.EntityLiving.b_(EntityLiving.java:3442)
	at net.minecraft.world.entity.EntityInsentient.b_(EntityInsentient.java:704)
	at net.minecraft.world.entity.EntityAgeable.b_(EntityAgeable.java:155)
	at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:3097)
	at net.minecraft.world.entity.EntityInsentient.l(EntityInsentient.java:460)
	at net.minecraft.world.entity.npc.EntityVillager.l(EntityVillager.java:398)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1435)
	at net.minecraft.server.level.WorldServer.lambda$tick$12(WorldServer.java:896)
	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:873)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1585)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
	at java.base/java.lang.Thread.run(Thread.java:833)

Could not pass event PlayerInteractEvent to ItemsAdder v3.5.0c-r4b
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eM.a(SourceFile:96)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eM.a(SourceFile:58)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.eC.h(SourceFile:73)
	at ItemsAdder_3.5.0c-r4b.jar//ia.m.ca.a(SourceFile:255)
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591)
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:539)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1365)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1342)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1335)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1313)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
Will be checked as soon as possible
