### ISSUE TITLE
Items Adder Error on Console 

### ISSUE THREAD

**Issue by dayritsaultcollege** [PluginBugs/Issues-ItemsAdder#3016]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

_fredrich

### What happened?

When a player joins the server this error will pop up on my console, I'm using the latest version of all dependencies and latest version of items adder. I am running a cross platform minecraft paper server.  

[latest (8).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12622893/latest.8.log)

### Steps to reproduce the issue

1.  Join the server (Latest Version of Items Adder)
2. Then the error will show in the console

### Server version

This server is running Paper version git-Paper-183 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb60bff)
You are running the latest version
Previous version: git-Paper-146 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version: 3.5.0c-r5b (Latest)

### ProtocolLib Version

Protocol Lib Version 5.1.0

### LoneLibs Version

Lonelibs Version 1.0.25

### FULL server log

[latest (8).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12622912/latest.8.log)

### Error (optional)

```shell
[14:13:20] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
com.google.gson.JsonParseException: Don't know how to turn $[0] into a Component
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:323) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:103) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:201) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:160) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:201) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:201) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:969) ~[gson-2.10.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
	at ia.nms.aE.aE.a(SourceFile:80) ~[ItemsAdder_3.5.0c-r5b.jar:?]
	at ia.m.ha.h(SourceFile:117) ~[ItemsAdder_3.5.0c-r5b.jar:?]
	at ia.m.gT.onPacketSending(SourceFile:150) ~[ItemsAdder_3.5.0c-r5b.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (2).jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2210) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2196) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3197) ~[paper-1.20.1.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3185) ~[paper-1.20.1.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3165) ~[paper-1.20.1.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3160) ~[paper-1.20.1.jar:git-Paper-146]
	at jss.customjoinandquitmessages.utils.Util.sendAllPlayerBaseComponent(Util.java:91) ~[CustomJoinAndQuitMessages-1.7.12-beta (1).jar:?]
	at jss.customjoinandquitmessages.json.MessageBuilder.sendToAll(MessageBuilder.java:98) ~[CustomJoinAndQuitMessages-1.7.12-beta (1).jar:?]
	at jss.customjoinandquitmessages.listener.chat.JoinListener.onJoinListener(JoinListener.java:158) ~[CustomJoinAndQuitMessages-1.7.12-beta (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor430.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-146]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.tonimatasdev.perworldplugins.api.PerWorldRegisteredListener.callEvent(PerWorldRegisteredListener.java:64) ~[PerWorldPlugins-1.4.2.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-146]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-146]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-146]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587) ~[paper-1.20.1.jar:git-Paper-146]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-146]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-146]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-146]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-146]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/113551198/13fbc36a-2f2a-48c3-b298-fb4051abccc3

**Comment by LoneDev6** [comment]
The chat component text seems to be maformed.
`{"clickEvent":{"action":"run_command","value":"/say \u003cname\u003e hello server"},"hoverEvent":{"action":"show_text","value":[]},"extra":[{"color":"aqua","text":"["},{"color":"#83ff6f","text":"+"},{"color":"aqua","text":"] "},{"color":"#a157ff","text":"ItsJustZedd"}],"text":""}`

Check which plugin is generating this message and try to fix it. Probably the `"hoverEvent":{"action":"show_text","value":[]}` is the issue.
in this case `"hoverEvent":{"action":"show_text","value":[]}` is wrong has it has no value, your text is empty.
Should be something like this: `"hoverEvent":{"action":"show_text","value":{"text":"hello"}}`
