### ISSUE TITLE
itemsadder doesn't work

### ISSUE THREAD

**Issue by mrkronosbr** [PluginBugs/Issues-ItemsAdder#3020]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

 itemsadder works on the server, but after some time online, be it minutes or hours, it simply stops working

### Steps to reproduce the issue

what happens and what is in the title, it turns off after a while by itself

### Server version

CraftBukkit version 3763-Spigot-7d7b241-5a5e43e (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder 3.4.1e

### ProtocolLib Version

ProtocolLib 5.1.0

### LoneLibs Version

LoneLibs 1.0.25

### FULL server log

[02:58:08] [Craft Scheduler Thread - 380/WARN]: java.lang.IllegalAccessError
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.math.fast.CommonsMathLiterals.a(class:3350)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hN.a(class:2737)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.co.a(class:5658)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.je.a(class:3826)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.is.a(class:6585)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.net.minidev.json.writer.ArraysMapper$15.a(class:5411)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.random.RandomGenerator.a(class:1719)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.cv.a(class:4179)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.jv.a(class:1966)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.B.impl.v1_16_R3.a(class:2968)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.com.jayway.jsonpath.Filter$OrFilter.a(class:4345)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.gB.a(class:4563)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ew.a(class:209)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.aw.a(class:1296)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ii.a(class:3)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.nbt.nms.impl.NBTTagList_v1_19_R1_2.a(class:6366)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.mechanics.BoneMechanic.a(class:5676)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.iL.a(class:4084)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.gU.a(class:1390)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.kD.a(class:4958)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.api.Events.campfire.CampfirePutItemEvent.a(class:1724)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.aX.impl.a.a(class:5647)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.analysis.solvers.BracketedUnivariateSolver.a(class:5226)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.aa.impl.v1_18_R2.a(class:3405)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.api.Events.campfire.CampfireRemoveItemEvent.a(class:3355)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.dg.a(class:4191)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.c.a(class:6243)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.cC.a(class:231)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.eF.a(class:6255)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hA.a(class:3630)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.util.IntegerSequence.a(class:6651)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.fY.a(class:4315)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hC.a(class:2028)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.path.CompiledPath.a(class:2824)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ib.a(class:6648)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.gA.a(class:6619)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.util.Combinations$IterationOrder.a(class:487)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.objectweb.asm.RecordComponentVisitor.a(class:2005)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.bf.a(class:3057)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.je.a(class:3682)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Mimic.MimicRegistryManager.a(class:5775)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ai.a(class:1368)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.kI.a(class:4456)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.mechanics.DismountMechanic.a(class:4979)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Vault.LuckPermsHook.a(class:2813)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hE.a(class:80)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.eP.a(class:5306)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.aC.impl.v1_19_R1_2.a(class:3272)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hl.a(class:4684)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.util.MathArrays$1.a(class:2395)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ih.a(class:1437)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.io.protostuff.WireFormat$1.a(class:5430)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.nbt.nms.impl.NBTTagList_v1_16_R3.a(class:953)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ej.a(class:2738)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.com.jayway.jsonpath.internal.filter.LogicalOperator.a(class:3104)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.ix.a(class:4617)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.L.a(class:4049)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.util.MathArrays$3.a(class:2660)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.aN.impl.v1_19_R1_2.a(class:5480)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.nms.aN.impl.v1_15_R1.a(class:1454)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.fa.a(class:23)
[02:58:08] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.random.RandomGeneratorFactory.a(class:1298)
[02:58:09] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.objectweb.asm.AnnotationWriter.a(class:3721)
[02:58:09] [Craft Scheduler Thread - 380/WARN]: 	at ia.m.hX.a(class:3451)
[02:58:09] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.net.minidev.asm.BeansAccessConfig.a(class:2385)
[02:58:09] [Craft Scheduler Thread - 380/WARN]: 	at ia.sh.org.apache.commons.math3.random.Well19937c.a(class:5843)
[02:58:09] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.4.1e

### Error (optional)

```shell
[03:04:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v3.4.1e - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:864) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:312) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:296) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1919) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

![Screenshot_5](https://github.com/PluginBugs/Issues-ItemsAdder/assets/124117405/0b9ac3ee-f6da-440b-98ab-3820144460e1)

**Comment by LoneDev6** [comment]
This error is only partial, please provide the full server log for me to help you identifying the issue.

**Comment by mrkronosbr** [comment]
I can't, it's saying that the typed text is too big

**Comment by LoneDev6** [comment]
You have to upload it as file...

**Comment by LoneDev6** [comment]
Hello?
Please provide your server log so that I can help you identifying the issue.
