### ISSUE TITLE
Luckperm prefix issue

### ISSUE THREAD

**Issue by Khytlu** [PluginBugs/Issues-ItemsAdder#3033]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Khytlu

### What happened?

Luckperm prefixes not working

### Steps to reproduce the issue

Set a prefix for a group different than default
/lp creategroup groupname
/lp group groupname meta addprefix 100 "prefix"
Set yourself in that group
 /lp user playername parent add groupname
Type in chat to see if you can see that prefix, for me I am not able to see it

### Server version

git-Paper-183 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.5.1

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.26

### FULL server log

I would like to provide it via Discord for privacy

### Error (optional)

```shell
[10:41:20] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v3.5.1
me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for 'fb815e1b-7ac8-4b63-8153-6fd71fa3a551' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:153) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultChat.getUserChatPrefix(LuckPermsVaultChat.java:96) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultChat.getPlayerPrefix(AbstractVaultChat.java:166) ~[?:?]
	at dev.lone.itemsadder.Core.OtherPlugins.Vault.VaultHook.getPlayerPrefix(SourceFile:70) ~[ItemsAdder_3.5.1.jar:?]
	at ia.m.hd.b(SourceFile:550) ~[ItemsAdder_3.5.1.jar:?]
	at ia.m.hd.e(SourceFile:604) ~[ItemsAdder_3.5.1.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-183]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-183]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-183]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:41:20] [Server thread/INFO]: Khytlu joined the game
```

**Comment by Khytlu** [comment]
Seems like it only happens when it connects you to server with MMOProfiles plugin

**Comment by Khytlu** [comment]
I was misconfigured a different plugin, I thought it was about itemsadder cuz error said so.
