### ISSUE TITLE
Circular plugin loading

### ISSUE THREAD

**Issue by YKDZ** [PluginBugs/Issues-ItemsAdder#3060]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

It seems that a plugin looping loading problem occurs, and deleting any of the plugins in the loop solves the problem, rightfully so.

### Steps to reproduce the issue

1. Install plugin in the loop.
2. Find the problem.

### Server version

git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.0

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-653

### LoneLibs Version

LoneLibs version 1.0.27

### Error (optional)

```shell
[22:02:04 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[22:02:04 ERROR]: [SimpleProviderStorage] Circular load order:
[22:02:04 ERROR]: [SimpleProviderStorage]   ItemsAdder -> MythicMobs -> Multiverse-Core -> CrazyCrates -> CMI -> HyronicFriends -> ItemsAdder
[22:02:04 ERROR]: [SimpleProviderStorage]   ItemsAdder -> MythicMobs -> Multiverse-Core -> CrazyCrates -> ItemsAdder
[22:02:04 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[22:02:04 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[22:02:04 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins ItemsAdder, ItemsAdder
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:522) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2049]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2363#issuecomment-1448287859
