### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to ItemsAdder v3.6.0

### ISSUE THREAD

**Issue by AnilTR06** [PluginBugs/Issues-ItemsAdder#3061]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I am using Faledskyblock plugin. While breaking cobblestones in the broken cobblestone generator, it suddenly did not break and this error appeared on the console. 
I did not create any blocks in the itemadder plugin.

### Steps to reproduce the issue

I am using Faledskyblock plugin. While breaking cobblestones in the broken cobblestone generator, it suddenly did not break and this error appeared on the console. 
I did not create any blocks in the itemadder plugin.

### Server version

Spigot 1.16.5 - API VERS. 1.16.5-R0.1-SNAPSHOT

### ItemsAdder Version

Itemsadder 3.6.0

### ProtocolLib Version

Protocollib version 5.1.0

### LoneLibs Version

Lonelibs version 1.0.27

### Error (optional)

```shell
Could not pass event PrepareItemCraftEvent to ItemsAdder v3.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1178) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:83) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.lambda$0(ContainerWorkbench.java:93) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.lambda$0(ContainerAccess.java:61) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess$2.a(ContainerAccess.java:48) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.a(ContainerAccess.java:60) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:92) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.InventoryCrafting.setItem(InventoryCrafting.java:142) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Slot.set(SourceFile:82) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.b(Container.java:372) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.a(Container.java:198) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2444) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays
	at ia.m.kE.a(SourceFile:51) ~[?:?]
	at ia.m.kX.hashCode(SourceFile:28) ~[?:?]
	at ia.m.fx.a(SourceFile:323) ~[?:?]
	at ia.m.fx.a(SourceFile:329) ~[?:?]
	at ia.m.fz.a(SourceFile:301) ~[?:?]
	at ia.m.fz.a(SourceFile:244) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	... 29 more
[01:40:52] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v3.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1178) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:83) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.lambda$0(ContainerWorkbench.java:93) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.lambda$0(ContainerAccess.java:61) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess$2.a(ContainerAccess.java:48) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.a(ContainerAccess.java:60) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:92) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.InventoryCrafting.splitStack(InventoryCrafting.java:133) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Slot.a(SourceFile:104) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.b(Container.java:381) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.a(Container.java:198) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2444) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays
	at ia.m.kE.a(SourceFile:51) ~[?:?]
	at ia.m.kX.hashCode(SourceFile:28) ~[?:?]
	at ia.m.fx.a(SourceFile:323) ~[?:?]
	at ia.m.fx.a(SourceFile:329) ~[?:?]
	at ia.m.fz.a(SourceFile:301) ~[?:?]
	at ia.m.fz.a(SourceFile:244) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	... 29 more
[01:40:53] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v3.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1178) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:83) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.lambda$0(ContainerWorkbench.java:93) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.lambda$0(ContainerAccess.java:61) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess$2.a(ContainerAccess.java:48) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerAccess.a(ContainerAccess.java:60) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:92) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.InventoryCrafting.setItem(InventoryCrafting.java:142) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Slot.set(SourceFile:82) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.b(Container.java:372) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.Container.a(Container.java:198) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2444) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays
	at ia.m.kE.a(SourceFile:51) ~[?:?]
	at ia.m.kX.hashCode(SourceFile:28) ~[?:?]
	at ia.m.fx.a(SourceFile:323) ~[?:?]
	at ia.m.fx.a(SourceFile:329) ~[?:?]
	at ia.m.fz.a(SourceFile:301) ~[?:?]
	at ia.m.fz.a(SourceFile:244) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	... 29 more
[01:40:53] [Server thread/ERROR]: Could not pass event CraftItemEvent to ItemsAdder v3.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2436) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1037) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays
	at ia.m.kE.a(SourceFile:51) ~[?:?]
	at ia.m.kX.hashCode(SourceFile:28) ~[?:?]
	at ia.m.fx.a(SourceFile:323) ~[?:?]
	at ia.m.fx.a(SourceFile:329) ~[?:?]
	at ia.m.fz.a(SourceFile:301) ~[?:?]
	at ia.m.fz.b(SourceFile:318) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	... 18 more
```

**Comment by LoneDev6** [comment]
> NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays

Use Paper/Purpur 1.16.5 instead of Spigot 1.16.5.
Minecraft 1.16.5 is outdated and not maintained anymore, using Spigot is not a good idea as it's more outdated compared to Paper and its forks.
