### ISSUE TITLE
Warning spam when a player is in the world - Cannot invoke "java.lang.reflect.Field.get(Object)"

### ISSUE THREAD

**Issue by tomhmagic** [PluginBugs/Issues-ItemsAdder#3068]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tomhmagic

### What happened?

The console is getting spammed with a warning when a player is in the lobby (pack host) server. 

### Steps to reproduce the issue

updated server to purpur 1.20.2, updated IA to 3.6.0.
Join server
console spams
leave server or switch to other server in network, console stops spamming

### Server version

[15:47:45 INFO]: Current: git-Purpur-2074 (MC: 1.20.2)*
Previous: git-Purpur-2058 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

[15:48:14 INFO]: ItemsAdder version 3.6.0
[15:48:14 INFO]: Customized Minecraft without client mods!
[15:48:14 INFO]: Website: devs.beer
[15:48:14 INFO]: Author: LoneDev

### ProtocolLib Version

[15:49:00 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-669
[15:49:00 INFO]: Provides read/write access to the Minecraft protocol.
[15:49:00 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:49:15 INFO]: LoneLibs version 1.0.27
[15:49:15 INFO]: Collection of libs used by my plugins
[15:49:15 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12820481/latest.log)

### Error (optional)

```shell
[15:45:50 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "ia.nms.aS.impl.v1_20_R2.l" is null
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.nms.aS.impl.v1_20_R2.a(SourceFile:38)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.nms.aS.impl.v1_20_R2.c(SourceFile:19)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.nms.aS.bD.c(SourceFile:41)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.nms.aD.impl.v1_20_R2.b(SourceFile:617)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.nms.aD.impl.v1_20_R2.h(SourceFile:388)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.as.am(SourceFile:599)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.as.a(SourceFile:445)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.as.a(SourceFile:266)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.ar.a(SourceFile:86)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.ar.a(SourceFile:81)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.aq.ab(SourceFile:132)
[15:45:50 WARN]: 	at ItemsAdder_3.6.0.jar//ia.m.V.D(SourceFile:1038)
```

**Comment by tomhmagic** [comment]
Seems to have changed to this now

[22:30:37 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.0 generated an exception while executing task 132
java.lang.NullPointerException: null
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:37 WARN]: java.lang.NullPointerException
[22:30:38 WARN]: java.lang.NullPointerException

**Comment by envizar** [comment]
Faced same issue with `Cannot invoke "java.lang.reflect.Field.get(Object)" because "ia.nms.aS.impl.v1_20_R2.l" is null`, but only when trying to execute /emote

**Comment by LoneDev6** [comment]
@envizar post the full error not only a part of it

**Comment by envizar** [comment]
> @envizar post the full error not only a part of it
```
[11:32:52 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "ia.nms.aS.impl.v1_20_R2.l" is null
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.nms.aS.impl.v1_20_R2.a(SourceFile:38)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.nms.aS.impl.v1_20_R2.c(SourceFile:19)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.nms.aS.bD.c(SourceFile:41)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.nms.aD.impl.v1_20_R2.b(SourceFile:617)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.nms.aD.impl.v1_20_R2.h(SourceFile:388)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.as.am(SourceFile:599)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.as.a(SourceFile:445)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.as.a(SourceFile:266)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.ar.a(SourceFile:86)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.ar.a(SourceFile:81)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.aq.ab(SourceFile:132)
[11:32:52 WARN]:        at ItemsAdder_3.6.0(2).jar//ia.m.V.D(SourceFile:1038)
[11:32:52 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[11:32:52 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[11:32:52 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[11:32:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:32:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:32:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
```
It spams warnings in console after `/emote` execution
and player just disappears until shift is pressed

**Comment by WMGameLive** [comment]
I don't know if this is same issue, it also appear while disabling server.
```[21:21:29 ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v3.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "ia.nms.aS.impl.v1_20_R2.l" is null
        at ia.nms.aS.impl.v1_20_R2.W(SourceFile:66) ~[ItemsAdder_3.6.0.jar:?]
        at ia.nms.aS.bC.f(SourceFile:34) ~[ItemsAdder_3.6.0.jar:?]
        at dev.lone.itemsadder.Main.onDisable(SourceFile:734) ~[ItemsAdder_3.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.disablePlugins(CraftServer.java:589) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:941) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:854) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2078]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by envizar** [comment]
> I don't know if this is same issue, it also appear while disabling server.
> ```
> [21:21:29 ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v3.6.0 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "ia.nms.aS.impl.v1_20_R2.l" is null...

Yes, it appears while disabling on my server too

**Comment by LoneDev6** [comment]
It's being fixed and will probably be published tomorrow
