### ISSUE TITLE
Error starting the plugin

### ISSUE THREAD

**Issue by elianvilar** [PluginBugs/Issues-ItemsAdder#3080]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I started the server and it dont started the plugin

### Steps to reproduce the issue

Start the server

### Server version

git-Purpur-2062 (MC: 1.20.1)*

### ItemsAdder Version

latest (3.6.0)

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.27

### FULL server log

[00:05:52] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:05:53] [ServerMain/INFO]: Loaded 7 recipes
[00:05:54] [Server thread/INFO]: Starting minecraft server version 1.20.1
[00:05:54] [Server thread/INFO]: Loading properties
[00:05:54] [Server thread/INFO]: This server is running Purpur version git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6fd5f6 on HEAD)
[00:05:54] [Server thread/INFO]: Server Ping Player Sample Count: 12
[00:05:54] [Server thread/INFO]: Using 4 threads for Netty based IO
[00:05:54] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[00:05:55] [Server thread/INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[00:05:55] [Server thread/INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[00:05:55] [Server thread/INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[00:05:55] [Server thread/INFO]: Default game type: SURVIVAL
[00:05:55] [Server thread/INFO]: Generating keypair
[00:05:55] [Server thread/INFO]: Starting Minecraft server on *:25569
[00:05:55] [Server thread/INFO]: Using default channel type
[00:05:55] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[00:05:55] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[00:05:55] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ItemsAdder_3.6.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: ia/m/Q
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ia/m/Q
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
	... 9 more
Caused by: java.lang.ClassNotFoundException: ia.m.Q
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
	... 9 more
[00:05:55] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[00:05:56] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.27
[00:05:56] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.55
[00:05:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:05:56] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[00:05:56] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.27
[00:05:56] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[00:05:56] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[00:05:56] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[00:05:56] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[00:05:56] [Server thread/INFO]: Preparing level "world"
[00:05:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:05:56] [Server thread/INFO]: Time elapsed: 168 ms
[00:05:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[00:05:56] [Server thread/INFO]: Time elapsed: 20 ms
[00:05:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[00:05:56] [Server thread/INFO]: Time elapsed: 19 ms
[00:05:56] [Server thread/INFO]: [spark] Enabling spark v1.10.55
[00:05:57] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[00:05:57] [Server thread/INFO]: [spark] Starting background profiler...
[00:05:57] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[00:05:57] [Server thread/INFO]: Running delayed init tasks
[00:05:57] [Server thread/INFO]: Done (3.147s)! For help, type "help"
[00:11:47] [User Authenticator #0/INFO]: UUID of player GreenDodge1 is 931a1381-492f-37e6-9673-4be6a911f84f
[00:11:47] [Server thread/INFO]: GreenDodge1 joined the game
[00:11:48] [Server thread/INFO]: GreenDodge1[/127.0.0.1:57230] logged in with entity id 155 at ([world]6.5, 76.0, 6.5)
[00:11:55] [Server thread/INFO]: GreenDodge1 issued server command: /ia
[00:11:57] [Server thread/INFO]: GreenDodge1 issued server command: /pl
[00:25:15] [Server thread/INFO]: GreenDodge1 lost connection: Disconnected
[00:25:15] [Server thread/INFO]: GreenDodge1 left the game
[00:44:50] [Server thread/INFO]: Stopping server
[00:44:50] [Server thread/INFO]: [spark] Disabling spark v1.10.55
[00:44:50] [Server thread/INFO]: [LoneLibs] Disabling LoneLibs v1.0.27
[00:44:50] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
[00:44:50] [Server thread/INFO]: Saving players
[00:44:50] [Server thread/INFO]: Saving worlds
[00:44:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[00:44:50] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[00:44:50] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[00:44:50] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[00:45:01] [Server thread/INFO]: [ChunkHolderManager] Saved 150 chunks (8,92%) in world 'world'
[00:45:11] [Server thread/INFO]: [ChunkHolderManager] Saved 250 chunks (14,89%) in world 'world'
[00:45:21] [Server thread/INFO]: [ChunkHolderManager] Saved 350 chunks (20,87%) in world 'world'
[00:45:35] [Server thread/INFO]: [ChunkHolderManager] Saved 485 chunks (28,79%) in world 'world'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Saved 1610 block chunks, 103 entity chunks, 2 poi chunks in world 'world' in 53,68s
[00:45:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[00:45:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 13 entity chunks, 0 poi chunks in world 'world_nether' in 0,00s
[00:45:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:45:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[00:45:44] [Server thread/INFO]: [ChunkHolderManager] Saved 10 block chunks, 10 entity chunks, 0 poi chunks in world 'world_the_end' in 0,01s
[00:45:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:45:44] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[00:45:44] [Server thread/INFO]: Flushing Chunk IO
[00:45:44] [Server thread/INFO]: Closing Thread Pool
[00:45:44] [Server thread/INFO]: Closing Server

### Error (optional)

```shell
[00:05:55 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ItemsAdder_3.6.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: ia/m/Q
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ia/m/Q
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: ia.m.Q
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
        ... 9 more
```

**Comment by LoneDev6** [comment]
Redownload the plugin.
It works fine for me.
For some reason your jar file is corrupted.
