### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#3087]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mc_coder

### What happened?

Check log, spam

### Steps to reproduce the issue

.

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/54fc1059-5351-44ac-b94f-66e4190da07b)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/efbf957f-e80a-4ce9-be00-fb5771f99183)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/b13866a9-ac32-4419-9258-a7920771e28b)

### FULL server log

https://pastes.dev/PwamOhs8Wp

### Error (optional)

```shell
[11:03:37] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "<parameter1>" is null
	at ia.m.df.b(SourceFile:211) ~[?:?]
	at ia.m.df.k(SourceFile:135) ~[?:?]
	at ia.m.ku.run(SourceFile:140) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]



[11:42:28] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: null
[11:42:28] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: null
[11:42:28] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: null
[11:42:28] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: null
[11:42:28] [Server thread/WARN]: [ItemsAdder] Task #1207 for ItemsAdder v3.6.1-beta generated an exception
java.lang.NullPointerException: null
```

**Comment by Lerphie** [comment]
https://pastes.dev/PKYF2MRdXn

**Comment by LoneDev6** [comment]
Will be checked as soon as possible, thanks
