### ISSUE TITLE
Console error "Particle BLOCK_CRACK requires data"

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#3090]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

*

### Steps to reproduce the issue

*

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/2e54e44a-060a-4627-a2bb-c38d0f951403)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/44aa2026-79c1-4a84-ba34-4c211567852d)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/876adb73-b361-457c-8b8f-2a41039c2ee4)

### Error (optional)

```shell
[18:02:37] [Server thread/INFO]: Kinder4k issued server command: /tpa Mihashuvak
[18:02:37] [Server thread/INFO]: [GunGaleWorldSyncCore] Command sender CraftPlayer{name=Kinder4k} run command org.bukkit.command.PluginCommand(tpa, GunGaleWorldSyncCore v4.0.1-SNAPSHOT-2) Mihashuvak
[18:02:38] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.6.1-beta-r2
java.lang.IllegalArgumentException: Particle BLOCK_CRACK requires data, null provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftParticle.toNMS(CraftParticle.java:146) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2558) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2548) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2537) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2517) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2497) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2487) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2482) ~[patched_1.16.5.jar:git-Purpur-1171]
	at ia.m.dG.a(SourceFile:24) ~[?:?]
	at ia.m.dV.a(SourceFile:181) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.da.a(SourceFile:949) ~[?:?]
	at ia.m.ex.a(SourceFile:556) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.ej.b(SourceFile:258) ~[?:?]
	at ia.m.df.a(SourceFile:177) ~[?:?]
	at ia.m.df.d(SourceFile:483) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1106) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:991) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:946) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1138) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1977) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:985) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1287) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:902) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1186) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1229) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2290) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2546) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:02:42] [Async Chat Thread - #90/INFO]: [Стафф] ꑡ bob_kakao_air: вот баф
[18:02:44] [Async Chat Thread - #90/INFO]: [Стафф] ❊ Mihashuvak:  помолчи нубло
[18:02:45] [Server thread/INFO]: Kinder4k issued server command: /spawn
[18:02:45] [Server thread/INFO]: [GunGaleWorldSyncCore] Command sender CraftPlayer{name=Kinder4k} run command org.bukkit.command.PluginCommand(spawn, GunGaleWorldSyncCore v4.0.1-SNAPSHOT-2) 
[18:02:45] [Craft Scheduler Thread - 4299 - GunGaleWorldSyncCore/INFO]: [GunGaleWorldSyncCore] Send message TeleportMessage[source=vp_server1, name=kinder4k, location=ServerLocation[world=world, x=-19.5, y=64.0, z=41.5, pitch=0.0, yaw=90.0], animation=null, message=null, force=false] on server vp_spawn1 by GGWSTPInit:Simple
[18:02:45] [Craft Scheduler Thread - 5 - GunGaleWorldSyncCore/INFO]: [GunGaleWorldSyncCore] Receive answer AnswerMessage[source=vp_spawn1, player=kinder4k, status=OK] by GGWSTPAnswer:Simple 
[18:02:46] [Server thread/INFO]: Kinder4k lost connection: Disconnected
[18:02:46] [Server thread/INFO]: [GunGaleWorldSyncCore] Save player location CraftPlayer{name=Kinder4k} for player GlobalLocation{server='vp_server1', world='world', x=5329.738384527099, y=93.0, z=956.6148186408954, pitch=33.000065, yaw=-130.3502}
[18:02:47] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.6.1-beta-r2
java.lang.IllegalArgumentException: Particle BLOCK_CRACK requires data, null provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftParticle.toNMS(CraftParticle.java:146) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2558) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2548) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2537) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2517) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2497) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2487) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2482) ~[patched_1.16.5.jar:git-Purpur-1171]
	at ia.m.dG.a(SourceFile:24) ~[?:?]
	at ia.m.dV.a(SourceFile:181) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.da.a(SourceFile:949) ~[?:?]
	at ia.m.ex.a(SourceFile:556) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.ej.b(SourceFile:258) ~[?:?]
	at ia.m.df.a(SourceFile:177) ~[?:?]
	at ia.m.df.d(SourceFile:483) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1106) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:991) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:946) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1138) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1977) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:985) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1287) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:902) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1186) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1229) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2290) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2546) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by LoneDev6** [comment]
Currently BLOCK_CRACK is not supported as particle type because would require to specify a blockdata.
Is this feature required?
