### ISSUE TITLE
API FontImageWrapper - IndexOutOfBoundsException: Index 2 out of bounds for length 0

### ISSUE THREAD

**Issue by Nooxico** [PluginBugs/Issues-ItemsAdder#3092]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Nooxico

### What happened?

Hello, for some reason, I'm randomly getting errors from ItemsAdder in my console 

### Steps to reproduce the issue

It seems to be related to custom entities, I'm not sure.

### Server version

Current: git-Purpur-1985 (MC: 1.19.4)*

### ItemsAdder Version

ItemAdder version 3.6.1-beta-r2

### ProtocolLib Version

ProtocolLibs version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.26

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13034641/latest.log)

### Error (optional)

```shell
[11:33:40] [Server thread/WARN]: [ItemsAdder] Task #1343 for ItemsAdder v3.6.0 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at java.util.Collections$SynchronizedList.get(Collections.java:2718) ~[?:?]
	at ia.m.aL.p(SourceFile:77) ~[ItemsAdder_3.6.0.jar:?]
	at ia.m.bj.s(SourceFile:89) ~[ItemsAdder_3.6.0.jar:?]
	at ia.m.bj.aJ(SourceFile:115) ~[ItemsAdder_3.6.0.jar:?]
	at ia.m.bf.m(SourceFile:327) ~[ItemsAdder_3.6.0.jar:?]
	at ia.m.bf.aH(SourceFile:175) ~[ItemsAdder_3.6.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LoneDev6** [comment]
It's related to custom huds.
It's related to the fact that some custom huds parts are removed during gameplay and causes the error, it's strange as that error shouldn't happen.

Please let me know if it's frequent and provide me info about which plugin uses ItemsAdder custom huds.

**Comment by Nooxico** [comment]
Hello,

Thank you for your reply,

You're right. Origin of the problem is from custom HUD.
I was able to solve it by initializing FontImageWrapper one time, and store them into a HashMap like so:
private static final HashMap<Integer, FontImageWrapper> fontImages = new HashMap<>() {{
        for (int i = 1; i <= 10; i++) {
            put(i, new FontImageWrapper("namespace:image_name_"+i));
        }
    }};

Before that (when I had this error), each five ticks I was instantiating 30 FontImageWrapper per player.
I followed the example you provided on github.
https://github.com/LoneDev6/API-ItemsAdder-Example-ServerMonitor/blob/master/src/main/java/dev/lone/ServerMonitor/PlayersManager.java
(You instantiate FontImageWrapper each 5 ticks, that's why I though, it was minimal performance gain to store them aside)

Thank you
Nooxico

**Comment by LoneDev6** [comment]
Amazing! :D

**Comment by Dragonox77** [comment]
Verdict: It is not misconfigured.
It should not throw an error anyway.

You should take a look why.

**Comment by LoneDev6** [comment]
I consider this an API misuse which causes the error, this is why I marked it as misconfigured, I don't have a tag for API misuse.

**Comment by Dragonox77** [comment]
So what, you misuse your own API ?
As I said earlier, and in other words, this can be replecated with your github plugin to show cpu/ram usage.
Instantiating a class, should not create error, or you should specify a context if so.

**Comment by Dragonox77** [comment]
In addition,
This error cannot be catch since it is in one of your internal scheduler this error occur.

If it is a misuse of the api, it should throw error from the method api, not from your internal computing

**Comment by LoneDev6** [comment]
> So what, you misuse your own API ?

Yes, in the ServerMonitor plugin.

Anyway I reopened that since I want to investigate more and find out a precise way to trigger the issue, as with my previous tests I couldn't trigger it.

**Comment by Dragonox77** [comment]
Error occured again
Storing FontImageWrapper into static hashmap won't help.

**Comment by LoneDev6** [comment]
Provide a precise way to trigger the issue, I need a code which can trigger the issue and that I can simply copy and paste into my test plugin.
Thanks

**Comment by LoneDev6** [comment]
I added some sync checks to avoid concurrency, but this is quite strange since all calls should be done on the same thread already, maybe you were using a non-Bukkit thread.
