### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#3107]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

*

### Steps to reproduce the issue

*

### Server version

Purpur version git-Purpur-1171 (MC: 1.16.5)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/5a9d8037-684e-4762-b807-5c7183c1e73c)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/9948429a-4dcd-4dff-8521-bf25d8e15c94)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/14b6139c-caef-4f34-ac09-67d332c9aa28)

### Error (optional)

```shell
[17:37:15] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.6.1-beta-r2
java.lang.IllegalArgumentException: Particle BLOCK_CRACK requires data, null provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftParticle.toNMS(CraftParticle.java:146) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2558) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2548) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2537) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2517) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2497) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2487) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2482) ~[patched_1.16.5.jar:git-Purpur-1171]
	at ia.m.dG.a(SourceFile:24) ~[?:?]
	at ia.m.dV.a(SourceFile:181) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.da.a(SourceFile:949) ~[?:?]
	at ia.m.ex.a(SourceFile:556) ~[?:?]
	at ia.m.bm.a(SourceFile:258) ~[?:?]
	at ia.m.ej.b(SourceFile:258) ~[?:?]
	at ia.m.df.a(SourceFile:177) ~[?:?]
	at ia.m.df.d(SourceFile:483) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1171]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1106) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:991) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:946) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1138) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1977) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:985) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1287) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:902) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1186) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityWolf.attackEntity(EntityWolf.java:413) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:150) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:871) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2936) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:650) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityAgeable.movementTick(EntityAgeable.java:152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityAnimal.movementTick(EntityAnimal.java:60) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityWolf.movementTick(EntityWolf.java:303) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2662) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:404) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityWolf.tick(EntityWolf.java:319) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1512) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.World.a(World.java:1072) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Lerphie** [comment]
Oops, I accidentally posted the same mistake. Can you delete it...?
