### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by m4pDieKarte** [PluginBugs/Issues-ItemsAdder#3122]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

der.jared

### What happened?

I wanted to enter the server and noticed that the texture pack was no longer loading. I found the following error in my client log

### Steps to reproduce the issue

im join the server

### Server version

1.20.1 Paper

### ItemsAdder Version

3.6.2-beta-r2

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

1.0.27

### FULL server log

https://hastebin.com/share/inujujarir.makefile

### Error (optional)

```shell
[23:59:08] [Downloader 0/INFO]: Found file C:\Users\Jared\AppData\Roaming\.minecraft\server-resource-packs\4cf81777c76011c33bd985646c77a0dc512585c5 without verification hash
[23:59:08] [Downloader 0/ERROR]: Failed to open pack C:\Users\Jared\AppData\Roaming\.minecraft\server-resource-packs\4cf81777c76011c33bd985646c77a0dc512585c5
java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1599) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1607) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1445) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1407) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:250) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:179) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:193) ~[?:?]
	at ajk.c(FilePackResources.java:52) ~[ajk.class:?]
	at ajk.a(FilePackResources.java:85) ~[ajk.class:?]
	at ajk.a(FilePackResources.java:74) ~[ajk.class:?]
	at ajh.a(SourceFile:30) ~[ajh.class:?]
	at akg.a(SourceFile:71) ~[akg.class:?]
	at fvn.a(SourceFile:216) ~[fvn.class:?]
	at fvn.a(SourceFile:114) ~[fvn.class:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:59:08] [Downloader 0/WARN]: Missing metadata in pack server
[23:59:08] [IO-Worker-12/WARN]: Pack application failed: java.lang.IllegalArgumentException: Invalid pack metadata at C:\Users\Jared\AppData\Roaming\.minecraft\server-resource-packs\4cf81777c76011c33bd985646c77a0dc512585c5, deleting file C:\Users\Jared\AppData\Roaming\.minecraft\server-resource-packs\4cf81777c76011c33bd985646c77a0dc512585c5
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://prnt.sc/bK7hS_-juK3c

**Comment by LoneDev6** [comment]
For some reason the zip file can't be read by the client.
Try to disable pack protection in config.yml of itemsadder and run /iazip again.
Anyway I find it quite strange that this happens, the resourcepack protector was extensively tested and working for years and no one encountered this issue.
Let me know.

**Comment by LoneDev6** [comment]
Another reason could be that your client has a partial download which is broken.

Open this folder in your PC and delete everything (while game is closed).
`C:\Users\Karl\AppData\Roaming\.minecraft\server-resource-packs\`

Then join again.
If you are not using selfhost please reupload the file and update the URL.
If you are using selfhost you don't have to do anything else.
