### ISSUE TITLE
Advanced emote not working: StringIndexOutOfBoundsException: begin -1, end 99, length 99

### ISSUE THREAD

**Issue by Yassounou** [PluginBugs/Issues-ItemsAdder#3124]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yassou_

### What happened?

I did follow the exacte methode of installing the advanced methode emote, i did get the exemple and installed it in my server, 

normal classique emots works for me , as the exemple in the image
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/ec50c7b5-7f8a-4644-a3a3-8afaa83b68fe)

but the advanced methode is not here is some screen that show that the foldes is correcte
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/b410ef24-2546-4c64-b244-32b1b01d3e73)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/575bc2a6-3d51-4f55-9b3b-9c684468a8a9)

And I have a consol error its in the server log

### Steps to reproduce the issue

Installl advanced emote from the wiki exemple
iaz than do /emot (not working)

### Server version

git-Purpur-2006(MC: 1.20.1)

### ItemsAdder Version

3.6.2-beta-r2

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.27

### FULL server log

```
[20:53:38 ERROR]: [ItemsAdder] Failed to load player animations from file: /home/container/plugins/ItemsAdder/contents/emots/models/entity/advanced/.player_advanced_animations
[20:53:38 WARN]: java.lang.StringIndexOutOfBoundsException: begin -1, end 99, length 99
[20:53:38 WARN]:        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
[20:53:38 WARN]:        at java.base/java.lang.String.substring(String.java:2709)
[20:53:38 WARN]:        at java.base/java.lang.String.substring(String.java:2682)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.kl.i(SourceFile:748)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.V.a(SourceFile:512)
[20:53:38 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.V.v(SourceFile:496)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.G.a(SourceFile:2458)
[20:53:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:53:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:53:38 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:53:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:53:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:53:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
Please share your advanced emote blockbench project file so that I can check it, it's very strange as my example pack works fine: https://builtbybit.com/resources/34-detailed-emotes-pack-for-itemsadder.29141/

**Comment by Yassounou** [comment]
as you can see its you exemple from the wiki, I juste change the name of the animation and the work space so it match the forlder ine the pack
[advanced.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/13217873/advanced.zip)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/69d5f545-f1e1-4b27-b0a8-cba737fd6d3c)

**Comment by LoneDev6** [comment]
You are using an old version of the plugin.
Please always update the plugin before reporting bugs.

I cannot reproduce the bug using the latest version of the plugin.

[advanced_emotes_fix_lonedev.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/13348437/advanced_emotes_fix_lonedev.zip)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3d9e4e8a-c32f-4bca-89e6-7b218dfbe38b

**Comment by Yassounou** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/1fb0b173-f121-47ea-92c1-065d05685288)
I did use the latest one !

**Comment by LoneDev6** [comment]
Not in the log `ItemsAdder_3.5.1 (1).jar`

 ```
 [20:53:38 ERROR]: [ItemsAdder] Failed to load player animations from file: /home/container/plugins/ItemsAdder/contents/emots/models/entity/advanced/.player_advanced_animations
[20:53:38 WARN]: java.lang.StringIndexOutOfBoundsException: begin -1, end 99, length 99
[20:53:38 WARN]:        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
[20:53:38 WARN]:        at java.base/java.lang.String.substring(String.java:2709)
[20:53:38 WARN]:        at java.base/java.lang.String.substring(String.java:2682)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.kl.i(SourceFile:748)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.V.a(SourceFile:512)
[20:53:38 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.V.v(SourceFile:496)
[20:53:38 WARN]:        at ItemsAdder_3.5.1 (1).jar//ia.m.G.a(SourceFile:2458)
[20:53:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:53:38 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:53:38 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:53:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:53:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:53:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Anyway I cannot reproduce the issue, please try again with the zip I provided and let me know, thanks

**Comment by Yassounou** [comment]
Hello I comeback with the same error, I did put your exemple file  [advanced_emotes_fix_lonedev.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/13348437/advanced_emotes_fix_lonedev.zip)
i have this 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/18ef51ab-bc6b-4ef9-b9d6-f1ebbcb66533)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/0dad41d3-9c60-4392-80bc-26b6ac37834c)
I really dont know what I make wrong !
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69685202/9c60aa25-d70e-4bbc-b7bb-1a0a90844ac9)

**Comment by LoneDev6** [comment]
I will check again, anyway I posted a video showing that the emote file works fine.

**Comment by Yassounou** [comment]
Yes I have seen the video and I turst it, but I dont know why mine dont work, I can't see what i'am doing wrong
