### ISSUE TITLE
Timings Report 400% for itemsadder?

### ISSUE THREAD

**Issue by Mr-Errors** [PluginBugs/Issues-ItemsAdder#3138]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

appreciate

### What happened?

Hello could someone send me something or show me something that would be making my timings report for itemsadder to be over 400%? newest verison on everything I'm trying to get the timings report now https://timings.aikar.co/dev/?id=a2e1f0232a4d4accad7c08971e1a6b4a 

### Steps to reproduce the issue

1. Someone Joins the server
2. Server Throws like 50 errors of error provided
3. Server Crashes
4. Repeat

### Server version

[07:54:50 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-84 (MC: 1.20.1)

### ItemsAdder Version

[07:55:04 INFO]: ItemsAdder version 3.6.2-beta-r2
[07:55:04 INFO]: Customized Minecraft without client mods!
[07:55:04 INFO]: Website: devs.beer
[07:55:04 INFO]: Author: LoneDev

### ProtocolLib Version

[07:55:25 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-673
[07:55:25 INFO]: Provides read/write access to the Minecraft protocol.
[07:55:25 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[07:55:50 INFO]: LoneLibs version 1.0.27
[07:55:50 INFO]: Collection of libs used by my plugins
[07:55:50 INFO]: Authors: LoneDev and others

### FULL server log

[crash-2023-11-11_10.13.41-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/13326010/crash-2023-11-11_10.13.41-server.txt)

### Error (optional)

>....[1250.611s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1250.611s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Craft Scheduler Thread - 372"
[1250.612s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[1250.612s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Craft Async Scheduler Management Thread"
[21:04:19 ERROR]: Caught previously unhandled exception :
[21:04:19 ERROR]: Craft Async Scheduler Management Thread
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.lang.Thread.start0(Native Method) ~[?:?]
        at java.lang.Thread.start(Thread.java:809) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1013) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by LoneDev6** [comment]
Timings report are not supposed to be generated on the first few minutes of server uptime.
Please generate reports after 30 minutes of gameplay.
There are multiple reasons why timings reports generated on the first few minutes of gameplay are not to be considered valid, some of them are:
- The Java Virtual Machine works in some complex ways, it optimizes code after some minutes of server uptime
- The plugins load lot of stuff on the first minutes, so obviously you will see a peak in CPU usage
- Other plugins can slowdown the server itself
