### ISSUE TITLE
Plugin halts loadup due to updating another plugin

### ISSUE THREAD

**Issue by iFranticman** [PluginBugs/Issues-ItemsAdder#3142]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When i updated essentials and perworld plugins it did not let the plugin load

### Steps to reproduce the issue

update plugins
start server
Login and itemsadder stops working

### Server version

paper-1.20.2-290

### ItemsAdder Version

ItemsAdder_3.6.2-beta-r2.jar

### ProtocolLib Version

#673 (Oct 25, 2023, 12:08:42 PM)

### LoneLibs Version

[1.0.27](https://www.spigotmc.org/resources/lonelibs.75974/update?update=518286)

### Error (optional)

```shell
[09:47:14 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.2-beta-r2 generated an exception while executing task 278

java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter(org.bukkit.command.TabCompleter)" because the return value of "dev.lone.itemsadder.Main.a(String)" is null

    at ia.m.hs.<init>(SourceFile:80) ~[ItemsAdder_3.6.2-beta-r2.jar:?]

    at ia.m.G.a(SourceFile:895) ~[ItemsAdder_3.6.2-beta-r2.jar:?]

    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-280]

    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-280]

    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
Post the full server log, it's not clear what you're reporting here.
