### ISSUE TITLE
Throws exception upon /iazip

### ISSUE THREAD

**Issue by AsleeppMC** [PluginBugs/Issues-ItemsAdder#3143]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

asleepp

### What happened?

upon trying to /iazip, it would get stuck on "compressing" and when i looked in console, i saw that it had thrown an exception. 

### Steps to reproduce the issue

???

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Paper-110 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-654

### LoneLibs Version

1.0.27

### Error (optional)

```shell
[10:07:50 INFO]: Asleepp issued server command: /iazip
[10:07:50 INFO]: Glacial | [Host] Stopped self-host webserver on port: 20219
[10:07:50 WARN]: Glacial | (Liquids disabled. If you want to use liquids enable them in config.yml please)
[10:07:50 INFO]: Glacial | [Host] Starting self-host webserver on port: 20219
[10:07:50 INFO]: Glacial | [Pack] Extracting internal contents from .jar
[10:07:50 INFO]: Glacial | [Pack] DONE extracting internal contents from .jar
[10:07:50 WARN]: Glacial | Custom entities 'fast_packets_creation' is disabled. This might cause stuttering animations. More info: https://a.devs.beer/ia-delaypackets
[10:07:50 INFO]: Glacial | Loaded 317 items
[10:07:50 INFO]: Glacial | Used 0/188 REAL block IDs
[10:07:50 INFO]: Glacial | Used 305/750 REAL_NOTE block IDs
[10:07:50 INFO]: Glacial | Used 3/63 REAL_TRANSPARENT block IDs
[10:07:50 INFO]: Glacial | Used 0/127 REAL_WIRE block IDs
[10:07:50 INFO]: Glacial | Used 0/14 FIRE block IDs
[10:07:50 INFO]: Glacial | Used 142/6608 font_images
[10:07:50 INFO]: Glacial | [Init] Loaded 2 categories
[10:07:50 INFO]: Glacial | [Init] Loaded successfully in 286ms
[10:07:50 INFO]: Glacial |  
[10:07:50 INFO]: Glacial |  
[10:07:50 INFO]: Glacial | [Pack] Started generation
[10:07:50 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.2-beta-r2 generated an exception while executing task 15462
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at ia.m.js.a(SourceFile:196) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.js.b(SourceFile:146) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.js.j(SourceFile:117) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.jc.b(SourceFile:525) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.G.a(SourceFile:1143) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.ig.a(SourceFile:86) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at ia.m.G.a(SourceFile:919) ~[ItemsAdder_3.6.2-beta-r2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:07:51 INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[10:07:51 INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[10:07:51 INFO]: Glacial | Reloading ItemsAdder Custom Entities Citizens NPCs
```

**Comment by LoneDev6** [comment]
You have a block with too many textures, it must have 6 textures (one per face), you have more.
Let me know
