### ISSUE TITLE
Self host pack doesnt come

### ISSUE THREAD

**Issue by TostCan** [PluginBugs/Issues-ItemsAdder#3146]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Outpot pack don t edited
Problem?

I got the Itemsadder ir plugin from a friend and have a problem

### Steps to reproduce the issue

I start server use command /iareload and /iazip but new pack don t come

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### ItemsAdder Version

3.5.0c-r4

### ProtocolLib Version

Latest

### LoneLibs Version

Latest

### FULL server log

[ItemsAdder] [Pack] Generated resourcepack
[12:21:09 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[12:21:09 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[12:21:09 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.remove(String)" because "<parameter1>" is null
[12:21:09 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.a(SourceFile:845)
[12:21:09 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iC.a(SourceFile:129)
[12:21:09 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.d(SourceFile:402)
[12:21:09 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[12:21:09 WARN]:        at ItemsAdder_3.5.0c-r4.jar//ia.m.iG.a(SourceFile:401)
[12:21:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[12:21:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:21:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:21:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:21:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:21:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:21:09 INFO]: [ItemsAdder]
[12:21:09 INFO]: [ItemsAdder]
[12:21:09 INFO]: [ItemsAdder] [Pack] Saved into Deneme/plugins/ItemsAdder/output/generated.zip
[12:21:09 INFO]: [ItemsAdder] [Pack] Compressed in 8ms
[12:21:09 INFO]: [ItemsAdder] [Pack] Applying to every player...
[12:21:09 INFO]: [ItemsAdder] [Pack] Applied to 1 players

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115925462/47311bb3-0663-4476-8a89-f5034a167d64)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115925462/29900306-d378-4b61-933d-8f7ac8738465)
Problem?

**Comment by TostCan** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115925462/ca29002e-299d-4b04-a4ca-a24c51b32e7a)

**Comment by LoneDev6** [comment]
Update your plugin, also next time provide your full server log.
