### ISSUE TITLE
SetBoundigBox Error

### ISSUE THREAD

**Issue by iSoulEs** [PluginBugs/Issues-ItemsAdder#3168]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

creating an entity and putting the hitbox causes it to break. if does not have this bone, an automatic hitbox is assigned but you cannot modify the hitbox itself.

same steps: https://itemsadder.devs.beer/plugin-usage/adding-content/mobs/advanced-method/hitbox

### Steps to reproduce the issue

1- create a entity with custommodel (guide)
2- use /iaentity summon (entity name)
3- console error.

### Server version

 CatServer version 1.16.5-1d8d6313 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r4
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.27
Collection of libs used by my plugins
Authors: LoneDev and others

### Error (optional)

```shell
[12:29:50 ERROR]: Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v3.6.2-beta-r4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[forge:?]
        at ia.m.lt.a(SourceFile:73) ~[?:?]
        at ia.m.G.c(SourceFile:910) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:90) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[forge:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1046) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:345) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:998) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:815) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.entity.Entity.setBoundingBox(net.minecraft.util.math.AxisAlignedBB)'
        at ia.nms.aF.impl.v1_16_R3.a(SourceFile:165) ~[?:?]
        at ia.m.X.G(SourceFile:302) ~[?:?]
        at ia.m.X.a(SourceFile:250) ~[?:?]
        at ia.m.X.a(SourceFile:183) ~[?:?]
        at ia.m.X.a(SourceFile:178) ~[?:?]
        at ia.m.U.a(SourceFile:840) ~[?:?]
        at ia.m.U.a(SourceFile:811) ~[?:?]
        at ia.m.aw.a(SourceFile:420) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
        ... 12 more
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: example
entities:
  god:
    display_name: "example"
    type: ARMOR_STAND
    model_folder: entity\god
    silent: true
    can_sun_burn: false
    speed:
      movement: 1
      flying: 0
    max_health: 20
```

**Comment by LoneDev6** [comment]
Contact cat server developers and ask them to add the missing method.
`CatServer version 1.16.5-1d8d6313`

Method: `void net.minecraft.entity.Entity.setBoundingBox(net.minecraft.util.math.AxisAlignedBB)`

You are using an unofficial Spigot fork, for some reason it doesn't have this method while it should.
