### ISSUE TITLE
Error Itemsadder Items with MythicMobs conditions

### ISSUE THREAD

**Issue by Ssssimon1041** [PluginBugs/Issues-ItemsAdder#3189]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

molekula_osmoshd

### What happened?

An error occurred at the moment when I was working with the plugin for achievements. The plugin named mythic achievements (version 1.0.0). This plugin is from the developers of mythical mobs and works together with them. To create the conditions necessary for work, and to do the work of creating mythical mobs. The problem is that when I specify a value for getting information (in case the player turns off a certain mode in the invetar), then I want to know the Objects that can be seen, but the mechanical method is simply not perceived in the context of the objects that can be seen. Added options, replaced with new ones, mythicmobs items, mod items - everything works and is used. When I am in the service of a friend, I call him a master who does not recoup, then I get an error:   

[MythicMobs] ✗ Configuration error in Condition hasItem [13:01:11 WARNING]: [MythicMobs] --| Error message: An internal error occurred [13:01:11 WARN]: [MythicMobs] --| Condition string: hasitem{i=nozneza:fiber_fix;amount=1} true [13:07:19 WARN]: java.lang.NullPointerException: "io.lumine.mythic.bukkit.adapters.Bukkit ItemStack.isSimilar(org.bukkit.inventory.ItemStack)" because "this.item" has a null value

### Steps to reproduce the issue

I checked other items from the MythicMobs plugins,MMOitems and vanilla items. Then I saw that everything was working. When I entered Items added items, the previously described error was displayed.

### Server version

git-Purpur-2014 (MC: 1.20.1)*

### ItemsAdder Version

IA ver. 3.6.0

### ProtocolLib Version

Ver. 5.0.0

### LoneLibs Version

LoneLibs version 1.0.27

### Error (optional)

```shell
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] ✗ Configuration Error in Condition HasItem
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] --| Error Message: An internal error occurred
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] --| Condition Line: hasitem{m=ribalka:tuna;amount=1} true
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)" because "this.item" is null
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.conditions.all.HasItemCondition.checkInventory(HasItemCondition.java:75)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.conditions.all.HasItemCondition.check(HasItemCondition.java:58)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.SkillCondition.evaluateToEntity(SkillCondition.java:167)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicAchievements-Premium-0.0.5.jar//io.lumine.achievements.achievement.Criteria.checkConditions(Criteria.java:110)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicAchievements-Premium-0.0.5.jar//io.lumine.achievements.achievement.criteria.ConditionalCriteria.run(ConditionalCriteria.java:49)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToConsumer.accept(Delegates.java:93)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.bukkit.utils.Schedulers$LumineTask.run(Schedulers.java:184)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by LoneDev6** [comment]
Post the whole error not only a part of it, if you have it, thanks!

**Comment by Ssssimon1041** [comment]
> Post the whole error not only a part of it, if you have it, thanks!

[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] ✗ Configuration Error in Condition HasItem
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] --| Error Message: An internal error occurred
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: [MythicMobs] --| Condition Line: hasitem{m=ribalka:tuna;amount=1} true
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)" because "this.item" is null
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.conditions.all.HasItemCondition.checkInventory(HasItemCondition.java:75)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.conditions.all.HasItemCondition.check(HasItemCondition.java:58)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.core.skills.SkillCondition.evaluateToEntity(SkillCondition.java:167)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicAchievements-Premium-0.0.5.jar//io.lumine.achievements.achievement.Criteria.checkConditions(Criteria.java:110)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicAchievements-Premium-0.0.5.jar//io.lumine.achievements.achievement.criteria.ConditionalCriteria.run(ConditionalCriteria.java:49)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToConsumer.accept(Delegates.java:93)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at MythicMobs-5.5.0.jar//io.lumine.mythic.bukkit.utils.Schedulers$LumineTask.run(Schedulers.java:184)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:19:43] [Craft Scheduler Thread - 32 - MythicMobs/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by LoneDev6** [comment]
Why do you feel like it's related to ItemsAdder?
Seems an issue with their code, I see no trace of ItemsAdder in the error.
The issue is in this part of their code: `io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)`
They should do a null check on the item parameter.

Let me know.

**Comment by Ssssimon1041** [comment]
> Why do you feel like it's related to ItemsAdder? Seems an issue with their code, I see no trace of ItemsAdder in the error. The issue is in this part of their code: `io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)` They should do a null check on the item parameter.
> 
> Let me know.

They just ignore me >_<  . I read the same or similar issues on they discord server... I apologize they really don't like itemsadder... It's seems they are big haters of your plugin. It's sad! I hope they answer to me. But on that moment it's quiet.

**Comment by Ssssimon1041** [comment]
> Why do you feel like it's related to ItemsAdder? Seems an issue with their code, I see no trace of ItemsAdder in the error. The issue is in this part of their code: `io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)` They should do a null check on the item parameter.
> 
> Let me know.

In general, they answered me. In short, all my attempts to explain my problem to them came down only to the fact that I was to blame for using the Itemsadder plugin. They say that we don't support this plugin and it shouldn't work and it's not their fault. They also said that this error is caused by the plugin trying to find a Mythic-Item with the same name as ItemsAdder, does not find it and returns an error. They said that if the itemsadder developer fixes it himself, then you're in luck. If it doesn't fix it, they're not going to change anything... Some kind of not very kind community at MythicMobs... :(

**Comment by Ssssimon1041** [comment]
> Why do you feel like it's related to ItemsAdder? Seems an issue with their code, I see no trace of ItemsAdder in the error. The issue is in this part of their code: `io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)` They should do a null check on the item parameter.
> 
> Let me know.

I have new information. After update all plugins, error evolved to this format :  
 [23:40:02 WARN]: [MythicMobs] ✗ Configuration Error in Condition HasItem
[23:40:02 WARN]: [MythicMobs] --| File: Unknown
[23:40:02 WARN]: [MythicMobs] --| Error Message: 'nozneza:fiber_fix' is not a valid material.
[23:40:02 WARN]: [MythicMobs] --| Mechanic Line: hasitem{i=nozneza:fiber_fix;amount=>0}

**Comment by Ssssimon1041** [comment]
> Why do you feel like it's related to ItemsAdder? Seems an issue with their code, I see no trace of ItemsAdder in the error. The issue is in this part of their code: `io.lumine.mythic.bukkit.adapters.BukkitItemStack.isSimilar(org.bukkit.inventory.ItemStack)` They should do a null check on the item parameter.
> 
> Let me know.

YEEEAHHHHH!!!!! WE WIN!!! Developer of MythicMobs fixed this bug!!! He noticed my post and release patch 5.5.2 of myhticmobs dev build where he fixed this!!! Now conditions works with itemsadder items!!!! Unbelievable!!! ＼(^^)／ @LoneDev6 
![upload_2023_12_10_07_09_52_042](https://github.com/PluginBugs/Issues-ItemsAdder/assets/152868757/fe70a9a2-48fd-44ef-a598-07ca81640b37)

**Comment by LoneDev6** [comment]
Nothing new to me, they are known to always blame other plugins about their issues instead of actually using 15 minutes to check if the issue is on their side or not.

Happy you managed to sort it out with my suggestions.
Have a nice week and happy new year :D
