### ISSUE TITLE
NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isSneaking()'

### ISSUE THREAD

**Issue by redgabri** [PluginBugs/Issues-ItemsAdder#3199]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

javathread

### What happened?

I just installed protocollib (latest), lonelibs and itemsadder, and when i started the server many errors started spamming in the console

### Steps to reproduce the issue

1) Make a server
2) Put itemsadder & dependencies in the plugin's folder
3) Start the server

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### ItemsAdder Version

[00:21:44] [Server thread/INFO]: ItemsAdder version 3.6.2c
[00:21:44] [Server thread/INFO]: Customized Minecraft without client mods!
[00:21:44] [Server thread/INFO]: Website: devs.beer
[00:21:44] [Server thread/INFO]: Author: LoneDev

### ProtocolLib Version

[00:21:47] [Server thread/INFO]: ProtocolLib version 5.0.0
[00:21:47] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[00:21:47] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[00:23:32] [Server thread/INFO]: LoneLibs version 1.0.31
[00:23:32] [Server thread/INFO]: Collection of libs used by my plugins
[00:23:32] [Server thread/INFO]: Authors: LoneDev and others

### FULL server log

Too long to paste it in here! It's just the server starting and then exploding

### Error (optional)

```shell
[00:23:35] [Server thread/ERROR]: Could not pass event GenericGameEvent to ItemsAdder v3.6.2c
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isSneaking()'
	at ia.m.cn.a(SourceFile:241) ~[ItemsAdder_3.6.2c.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Level.postGameEventInRadius(Level.java:1429) ~[?:?]
	at net.minecraft.server.level.ServerLevel.gameEvent(ServerLevel.java:1547) ~[?:?]
	at net.minecraft.world.entity.Entity.gameEvent(Entity.java:1452) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.world.entity.Entity.gameEvent(Entity.java:1460) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.world.entity.Entity.gameEvent(Entity.java:1464) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.world.entity.Entity.move(Entity.java:1088) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2814) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2769) ~[?:?]
	at net.minecraft.world.entity.monster.Strider.travelWithInput(Strider.java:283) ~[?:?]
	at net.minecraft.world.entity.ItemSteerable.travel(ItemSteerable.java:51) ~[?:?]
	at net.minecraft.world.entity.monster.Strider.travel(Strider.java:269) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3315) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:627) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
	at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:61) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2917) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:395) ~[?:?]
	at net.minecraft.world.entity.monster.Strider.tick(Strider.java:330) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1135) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:936) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:674) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:654) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
Didn't even open the config
```

**Comment by LoneDev6** [comment]
Thanks! This will be fixed as soon as possible!

**Comment by teamTheK** [comment]
I'm having this problem too

**Comment by LoneDev6** [comment]
Working on it today
