### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class ia.m.G

### ISSUE THREAD

**Issue by KendiXYT** [PluginBugs/Issues-ItemsAdder#3201]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

KendiX

### What happened?

i have this error when i started my server

[19:27:27 INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.2b
[19:27:28 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.2b
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.31
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-2062 (MC: 1.20.1)
                                               
[19:27:28 ERROR]: Error occurred while enabling ItemsAdder v3.6.2b (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.G
        at dev.lone.itemsadder.Main.onEnable(SourceFile:443) ~[ItemsAdder_3.6.2b.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at ia.m.G.<clinit>(SourceFile:100) ~[ItemsAdder_3.6.2b.jar:?]
        at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:39) ~[ItemsAdder_3.6.2b.jar:?]
        at dev.lone.cosmeticscore.main.O.<init>(SourceFile:24) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.main.O.af(SourceFile:36) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.main.j.b(SourceFile:325) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:76) ~[CosmeticsCore_1.2.3-r5.jar:?]
        ... 12 more

### Steps to reproduce the issue

I don't really understand the question... ?
I juste started my server.

### Server version

git-Purpur-2060 (MC 1.20.1)

### ItemsAdder Version

Itemsadder_3.6.2c.jar

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.31

### Error (optional)

```shell
[19:27:27 INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.2b
[19:27:28 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.2b
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.31
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-2062 (MC: 1.20.1)
                                               
[19:27:28 ERROR]: Error occurred while enabling ItemsAdder v3.6.2b (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.G
        at dev.lone.itemsadder.Main.onEnable(SourceFile:443) ~[ItemsAdder_3.6.2b.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at ia.m.G.<clinit>(SourceFile:100) ~[ItemsAdder_3.6.2b.jar:?]
        at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:39) ~[ItemsAdder_3.6.2b.jar:?]
        at dev.lone.cosmeticscore.main.O.<init>(SourceFile:24) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.main.O.af(SourceFile:36) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.main.j.b(SourceFile:325) ~[CosmeticsCore_1.2.3-r5.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:76) ~[CosmeticsCore_1.2.3-r5.jar:?]
        ... 12 more
```

**Comment by MomaCods** [comment]
Similar issue here for items adder

**Comment by KendiXYT** [comment]
Itemsadder and cosmeticscore don't work together, I had to put an old version of cosmetics core for it to work

**Comment by LoneDev6** [comment]
`java.lang.NoClassDefFoundError: Could not initialize class ia.m.G`
This can happen if your JAR file is corrupted.
Try to download it again please and make sure to replace the old one with the new one

**Comment by LoneDev6** [comment]
Provide your full log as this error might indicate that there was another error before this one posted.
Thanks.

**Comment by KendiXYT** [comment]
Okay, I will ask my friend to update the latest version and send the logs

**Comment by KendiXYT** [comment]
The old cosmeticscore works perfectly with itemsadder but not the new version of cosmeticscore

**Comment by LoneDev6** [comment]
Please provide your full server log of when the issue occurred, otherwise I cannot find the cause of the issue, thanks.
You might also try to update [LoneLibs](https://www.spigotmc.org/resources/lonelibs.75974/).

**Comment by MomaCods** [comment]
Hello I have followed the instruction given for other user with similar issue. I have updated plugins and ensured Items Adder was a fresh download of the latest jar, but I continue to have an issue. I am not sure what to do now 

I am running Paper 1.20.2 
Items Adder was working PERFECTLY until I updated it as well as the updates of the LoneLibs and ProtocolLib the other day and now it will not run at all. 

this is a link to the console information

https://paste.revivenode.com/amihipukob

I dont want to be a bother.. .I just really like the plugin and been a few days since it worked. Was waiting to see if this poster had resolution, I am a verified customer as well. I have the same Username on all platforms so you can find me on Spigot as a paying customer :)

**Comment by LoneDev6** [comment]
For some reason ItemsAdder can't find the command `/iaimage` which is strange.
I am trying to find the cause since it seems to happen only on some servers. I cannot reproduce it on my server.

**Comment by LoneDev6** [comment]
You might have some other plugin registering the same command name?
You can try removing all other plugins and check if it works fine.

**Comment by MomaCods** [comment]
Yea I tried that the other day but forgot to copy the output in the console but the same thing happened. I just did a fresh backup so I will see how that goes. I just have to get my littles off to school for the day and I will get down to brass tacks.

thanks for your help on this issues :)

**Comment by MomaCods** [comment]
![Pluginsfolder](https://github.com/PluginBugs/Issues-ItemsAdder/assets/17677132/c40d6409-1a2c-4ac9-bd59-662d41914f05)

**Comment by MomaCods** [comment]
https://paste.revivenode.com/ukuyaworis

**Comment by MomaCods** [comment]
Only have ItemsAdder and the dependancies running... and this is what it does now

**Comment by MomaCods** [comment]
OK ... went and got a dev build of ProtocolLib and it seems to be working now... 
Here is the console

I am hoping I can restore back up and try the devbuild and see if that solves the issue

https://paste.revivenode.com/hidizavadi

**Comment by MomaCods** [comment]
I brought back my server with all plugins from backup .. updated protocollib to the dev build, started server 

the error about "tabcompleter" is back

https://paste.revivenode.com/zinomimeji

**Comment by LoneDev6** [comment]
> I am going to go back to only items adder and add each plugin back 1 by 1 and see if I can sus out which might be having a confiction

So basically it's another plugin interfering as I supposed, correct?
The trick is to add 1 plugin at a time (or a group of 5 plugins) and find out the cause.
There is no other way to fix this kind of issues, which are common with all plugins in general.

Let me know! :D

**Comment by ColorsASD** [comment]
I also encounter this error with numerous plugins, such as ChatControlRed. Try using 'load: STARTUP' in the plugins.yml file and hope that everything works well afterwards. Alternatively, if you know the plugin causing the issue, use the 'loadbefore:' option. This resolves many issues, as there are numerous plugins with various functionalities, and some plugins may conflict due to libraries, but there's no real problem with that.

**Comment by LoneDev6** [comment]
Still it's a mystery why the Bukkit API function fails to find the ItemsAdder command. Seems unrelated to libraries or plugins loading order.
