### ISSUE TITLE
ussie with new version

### ISSUE THREAD

**Issue by BronzWarq** [PluginBugs/Issues-ItemsAdder#3222]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sholomon

### What happened?

After I installed a new version of the plugin having previously updated LoneLibs I got an error and eternal reboot of the server

### Steps to reproduce the issue

just intalled new version IA

### Server version

1.20.2

### ItemsAdder Version

3.6.2d-beta-2

### ProtocolLib Version

ProtocolLib v5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs 1.0.40

### FULL server log

ServerLog https://paste.helpch.at/hakucoqiro.makefile

**Comment by EagL3-GIT** [comment]
+1

**Comment by vpttyn** [comment]
+1

**Comment by JuergenUniVie** [comment]
[09:15:10 INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.2d-beta-2
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 ERROR]: [ItemsAdder] Please update LoneLibs! https://a.devs.beer/ia-install-lonelibs
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 ERROR]: [ItemsAdder]
[09:15:10 INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.2d-beta-2
[09:15:10 ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v3.6.2d-beta-2 (Is it up to date?)
java.lang.NoClassDefFoundError: lonelibs/dev/lone/fastnbt/nms/Version
        at ia.m.my.<clinit>(SourceFile:105) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at dev.lone.itemsadder.Main.onDisable(SourceFile:694) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:213) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: lonelibs.dev.lone.fastnbt.nms.Version
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 19 more
[09:15:10 ERROR]: Error occurred while enabling ItemsAdder v3.6.2d-beta-2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.my
        at dev.lone.itemsadder.Main.onEnable(SourceFile:221) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: lonelibs/dev/lone/fastnbt/nms/Version [in thread "Server thread"]
        at ia.m.my.<clinit>(SourceFile:105) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at dev.lone.itemsadder.Main.onDisable(SourceFile:694) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:213) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        ... 12 more

**Comment by VictorAlonsoo** [comment]
same

**Comment by VictorAlonsoo** [comment]
+1
same

**Comment by KRsan0412** [comment]
me too.
It doesn't work with latest version of lonelibs.

**Comment by Exanthiax** [comment]
I've got the same error, Purpur 1.17.1 and Purpur 1.20.1

**Comment by LoneDev6** [comment]
Update LoneLibs again, I uploaded the wrong JAR.
https://www.spigotmc.org/resources/lonelibs.75974/
Thanks
