### ISSUE TITLE
1.20.4 Paper Villager Error

### ISSUE THREAD

**Issue by paiow** [PluginBugs/Issues-ItemsAdder#3250]
### What happened?

1.20.4 Paper
When you right-click a Villager, an error occurs as shown in the log below

```
[23:24:13 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.id
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:202) ~[LoneLibs.jar:?]
        at ia.m.iL.a(SourceFile:109) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at ia.m.hz.onPacketSending(SourceFile:170) ~[ItemsAdder_3.6.2d-beta-2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:242) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:227) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1608) ~[?:?]
        at net.minecraft.world.item.trading.Merchant.openTradingScreen(Merchant.java:41) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.startTrading(Villager.java:352) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobInteract(Villager.java:330) ~[?:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1333) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1130) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2743) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2763) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2704) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-342]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-342]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.id
        at com.google.gson.Gson.fromJson(Gson.java:1238) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:157) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:60) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:218) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:74) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:198) ~[LoneLibs.jar:?]
        ... 44 more
Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.id
        at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:187) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ShowEntitySerializer.read(ShowEntitySerializer.java:66) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ShowEntitySerializer.read(ShowEntitySerializer.java:42) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:157) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:60) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:218) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:74) ~[LoneLibs.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:198) ~[LoneLibs.jar:?]
        ... 44 more
[23:24:13 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutOpenWindow@7c46943b[
    a=3
    b=net.minecraft.world.inventory.Containers@75bdad05
    c=translation{key='entity.minecraft.villager.armorer', args=[]}[style={hoverEvent=d[action=<action show_entity>, value=net.minecraft.network.chat.ChatHoverable$b@cd80e819],insertion=7a0e4185-aec9-4a09-a844-407740335528}]
  ]
```

### Steps to reproduce the issue

1. 1.20.4 Paper
2. ItemsAdder 3.6.2d-beta-2
3. Villager Right-Click
4. Bukkit Error

### ItemsAdder Version

ItemsAdder 3.6.2d-beta-2

### ProtocolLib Version

ProtocolLib v5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs v1.0.40

**Comment by LoneDev6** [comment]
Will be fixed in the next LoneLibs update. Thanks!
