### ISSUE TITLE
Plugin don't executred in start server

### ISSUE THREAD

**Issue by srnexuls** [PluginBugs/Issues-ItemsAdder#3259]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sr.nexuls

### What happened?

In executed server:

This server version is not supported: 1.16.4
You're running an outdated version of Spigot. Please update it to 1.16.5.[m
Open config.yml and set 'ignore-server-compatibility-check: true' to load the plugin anyway and to report them on Github: http://a.devs.beer/ia-not-compat-git

### Steps to reproduce the issue

only when running the server

### Server version

Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder_3.6.2d-beta-2

### ProtocolLib Version

version: 5.1.0

### LoneLibs Version

version: 1.0.42

**Comment by LoneDev6** [comment]
> You're running an outdated version of Spigot. Please update it to 1.16.5

I don't see any reason to use 1.16.4 as it's outdated and has lot of issues. Update to 1.16.5.

**Comment by srnexuls** [comment]
I updated spigot to 1.16.5, but now the following error is occurring:

[01:06:09] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.2d-beta-2 (Is it up to date?)
java.lang.UnsupportedClassVersionError: ia/m/ji has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at ia.m.iN.a(SourceFile:170) ~[?:?]
	at ia.m.iN.a(SourceFile:105) ~[?:?]
	at ia.m.iN.a(SourceFile:42) ~[?:?]
	at ia.m.iN.b(SourceFile:36) ~[?:?]
	at ia.m.my.<init>(SourceFile:26) ~[?:?]
	at ia.m.my.init(SourceFile:42) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:221) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by srnexuls** [comment]
I noticed that the new version of the plugin is causing a lot of incompatibility with Paper 1.16.5 (among other versions). So, I downloaded Purpur 1.16.5 and I downloaded the ItemsAdder 3.6.2c version and it worked correctly.

Thank you for your attention!

**Comment by LoneDev6** [comment]
Update your java installation to java 17.
Let me know
