### ISSUE TITLE
DecoderException when using emojis in chat

### ISSUE THREAD

**Issue by ubdeadhaha** [PluginBugs/Issues-ItemsAdder#3260]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

freezin_

### What happened?

When sending an emoji, or even when some players join, they are kicked from the bungee server and presented this error.

![2023-12-28_18 56 00](https://github.com/PluginBugs/Issues-ItemsAdder/assets/125194180/4e2a8bc8-0a67-4b13-839c-cd456f3b2c41)

Here's the error provided by the bungee server - https://pastebin.com/yirJi1xm

### Steps to reproduce the issue

Install latest updates

send an emoji in chat

### Server version

git-Paper-309 (MC: 1.20.2)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-3

CosmeticsCore version 1.2.3b

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.42

### FULL server log

01:52:51 [WARNING] [gweench] <-> DownstreamBridge <-> [slimefun] - could not decode packet!
io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"hoverEvent":{"action":"show_text","contents":{"italic":0,"extra":[{"color":"white","extra":[""," \nUsage: "],"text":"Emoji: ","type":"text"},{"color":"gray","text":":salad: \n\n","type":"text"},{"color":"yellow","text":"HINT: \n","type":"text"},{"color":"gray","text":"You can use the ","type":"text"},{"color":"yellow","text":"/e ","type":"text"},{"color":"gray","text":"command to send public \nmessages/commands with emojis easier. \nWrite the emoji name and press ","type":"text"},{"color":"yellow","text":"TAB. \n \nExamples: \n","type":"text"},{"color":"yellow","text":"/e Hello smile \n","type":"text"},{"color":"gray","text":"prints ","type":"text"},{"color":"white","text":"Hello :smile: \n \n","type":"text"},{"color":"yellow","text":"/e /tell Notch Hello smile \n","type":"text"},{"color":"gray","text":"sends the command ","type":"text"},{"color":"white","text":"/tell Notch Hello :smile:","type":"text"}],"text":"","type":"text"}},"text":"§f§r","type":"text"}]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"hoverEvent":{"action":"show_text","contents":{"italic":0,"extra":[{"color":"white","extra":[""," \nUsage: "],"text":"Emoji: ","type":"text"},{"color":"gray","text":":salad: \n\n","type":"text"},{"color":"yellow","text":"HINT: \n","type":"text"},{"color":"gray","text":"You can use the ","type":"text"},{"color":"yellow","text":"/e ","type":"text"},{"color":"gray","text":"command to send public \nmessages/commands with emojis easier. \nWrite the emoji name and press ","type":"text"},{"color":"yellow","text":"TAB. \n \nExamples: \n","type":"text"},{"color":"yellow","text":"/e Hello smile \n","type":"text"},{"color":"gray","text":"prints ","type":"text"},{"color":"white","text":"Hello :smile: \n \n","type":"text"},{"color":"yellow","text":"/e /tell Notch Hello smile \n","type":"text"},{"color":"gray","text":"sends the command ","type":"text"},{"color":"white","text":"/tell Notch Hello :smile:","type":"text"}],"text":"","type":"text"}},"text":"§f§r","type":"text"}]
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:140)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:140)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:28)
	at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:122)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:140)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:31)
	at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:15)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1300)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:157)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1329)
	at com.google.gson.Gson.fromJson(Gson.java:1271)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:118)
	at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:112)
	at net.md_5.bungee.protocol.packet.SystemChat.read(SystemChat.java:27)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:507)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:42)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:11)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 24 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"hoverEvent":{"action":"show_text","contents":{"italic":0,"extra":[{"color":"white","extra":[""," \nUsage: "],"text":"Emoji: ","type":"text"},{"color":"gray","text":":salad: \n\n","type":"text"},{"color":"yellow","text":"HINT: \n","type":"text"},{"color":"gray","text":"You can use the ","type":"text"},{"color":"yellow","text":"/e ","type":"text"},{"color":"gray","text":"command to send public \nmessages/commands with emojis easier. \nWrite the emoji name and press ","type":"text"},{"color":"yellow","text":"TAB. \n \nExamples: \n","type":"text"},{"color":"yellow","text":"/e Hello smile \n","type":"text"},{"color":"gray","text":"prints ","type":"text"},{"color":"white","text":"Hello :smile: \n \n","type":"text"},{"color":"yellow","text":"/e /tell Notch Hello smile \n","type":"text"},{"color":"gray","text":"sends the command ","type":"text"},{"color":"white","text":"/tell Notch Hello :smile:","type":"text"}],"text":"","type":"text"}},"text":"§f§r","type":"text"}]
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:154)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 120 more
01:52:51 [INFO] [gweench] disconnected with: §f§fDecoderException : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"hoverEvent":{"action":"show_text","contents":{"italic":0,"extra":[{"color":"white","extra":[""," \nUsage: "],"text":"Emoji: ","type":"text"},{"color":"gray","text":":salad: \n\n","type":"text"},{"color":"yellow","text":"HINT: \n","type":"text"},{"color":"gray","text":"You can use the ","type":"text"},{"color":"yellow","text":"/e ","type":"text"},{"color":"gray","text":"command to send public \nmessages/commands with emojis easier. \nWrite the emoji name and press ","type":"text"},{"color":"yellow","text":"TAB. \n \nExamples: \n","type":"text"},{"color":"yellow","text":"/e Hello smile \n","type":"text"},{"color":"gray","text":"prints ","type":"text"},{"color":"white","text":"Hello :smile: \n \n","type":"text"},{"color":"yellow","text":"/e /tell Notch Hello smile \n","type":"text"},{"color":"gray","text":"sends the command ","type":"text"},{"color":"white","text":"/tell Notch Hello :smile:","type":"text"}],"text":"","type":"text"}},"text":"§f§f","type":"text"}] @ io.netty.handler.codec.MessageToMessageDecoder:98
01:52:51 [INFO] [gweench] -> UpstreamBridge has disconnected
01:52:51 [INFO] [gweench] <-> DownstreamBridge <-> [slimefun] has disconnected

**Comment by LoneDev6** [comment]
This seems to be a bug of the parser of Bungeecord which doesn't handle JSON array messages correctly.
Very strange
