### ISSUE TITLE
Circular plugin loading detected

### ISSUE THREAD

**Issue by WsJohn** [PluginBugs/Issues-ItemsAdder#3273]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Console error: Circular plugin loading detected,
and told me to report this to the plugin authors of the first plugin of each loop.

### Steps to reproduce the issue

[22:15:25 ERROR]: [SimpleProviderStorage]   ItemsAdder -> ExecutableItems -> CustomCrafting -> eco -> ItemsAdder
[22:15:25 ERROR]: [SimpleProviderStorage]   ItemsAdder -> ExecutableItems -> CustomCrafting -> ItemsAdder
[22:15:25 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.

### Server version

paper-1.20.4-346

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

Dev build #679

### LoneLibs Version

1.0.42

### FULL server log

[22:15:25 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[22:15:25 ERROR]: [SimpleProviderStorage] Circular load order:
[22:15:25 ERROR]: [SimpleProviderStorage]   ItemsAdder -> ExecutableItems -> CustomCrafting -> eco -> ItemsAdder
[22:15:25 ERROR]: [SimpleProviderStorage]   ItemsAdder -> ExecutableItems -> CustomCrafting -> ItemsAdder
[22:15:25 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[22:15:25 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[22:15:25 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins ItemsAdder, ItemsAdder
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.4.jar:git-Paper-346]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:42) ~[paper-1.20.4.jar:git-Paper-346]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-346]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-346]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-346]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[22:15:25 ERROR]: This crash report has been saved to: C:\WD\Survival\.\crash-reports\crash-2023-12-31_22.15.25-server.txt

**Comment by WsJohn** [comment]
btw this is what ive been told to do so i report it here, i know the solution.

**Comment by LoneDev6** [comment]
You can set `-Dpaper.useLegacyPluginLoading=true` in your Java arguments, but I guess you already know.
I'll try to find a solution but it's probably impossible to fix that because of how some plugins depend on each other.
