### ISSUE TITLE
1.20.4 - java.lang.IllegalAccessError: class ia.m.ml tried to access protected field net.minecraft.server.network.ServerCommonPacketListenerImpl.c

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3274]
Reorganized from https://github.com/PluginBugs/Issues-ItemsAdder/issues/3271

`4002-Spigot-cdc4e03-6902782 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)`

[Full log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13799936/err_log.txt).

```
[11:44:25] [Craft Scheduler Thread - 1/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-5 generated an exception while executing task 334
java.lang.IllegalAccessError: class ia.m.ml tried to access protected field net.minecraft.server.network.ServerCommonPacketListenerImpl.c (ia.m.ml is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @79a0d064; net.minecraft.server.network.ServerCommonPacketListenerImpl is in unnamed module of loader java.net.URLClassLoader @7e32c033)
        at ia.m.ml.a(SourceFile:25) ~[?:?]
        at ia.m.md.a(SourceFile:40) ~[?:?]
        at ia.m.qs.e(SourceFile:178) ~[?:?]
        at ia.m.qB.at(SourceFile:64) ~[?:?]
        at ia.m.qs.aa(SourceFile:128) ~[?:?]
        at ia.m.il.b(SourceFile:182) ~[?:?]
        at ia.m.il.b(SourceFile:104) ~[?:?]
        at ia.m.G.a(SourceFile:1231) ~[?:?]
        at ia.m.pR.a(SourceFile:455) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4002-Spigot-cdc4e03-6902782]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4002-Spigot-cdc4e03-6902782]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by TectonicGrinch** [comment]
Ah thanks im assuming it's because it is ExFat as i mess with linux sometimes ill re partition

**Comment by LoneDev6** [comment]
No it's not, I fixed it in the upcoming update.
If you're referring to [this other issue](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3271) please do not comment here as this is another issue I created because you reported two issues on the same page.

Have a nice day
