### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#3279]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Errors are spamming console

### Steps to reproduce the issue

I'm not sure

### Server version

git-Purpur-2083 (MC: 1.20.2)*

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.42

### Error (optional)

```shell
[16:44:41 WARN]: [ItemsAdder] Task #50852592 for ItemsAdder v3.6.3-beta-5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
        at ia.m.nC.a(SourceFile:454) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at ia.m.nC.a(SourceFile:365) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at ia.m.nC.a(SourceFile:194) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]




[16:50:39 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([321...70])
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:225) ~[LoneLibs (6).jar:?]
        at ia.m.iI.a(SourceFile:97) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at ia.m.hy.onPacketSending(SourceFile:173) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection$PacketSendAction.lambda$new$0(Connection.java:965) ~[?:?]
        at net.minecraft.network.Connection$WrappedConsumer.accept(Connection.java:949) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:562) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:523) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:412) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:276) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:261) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1642) ~[?:?]
        at net.minecraft.world.item.trading.Merchant.openTradingScreen(Merchant.java:41) ~[?:?]
        at net.minecraft.world.entity.npc.WanderingTrader.mobInteract(WanderingTrader.java:163) ~[?:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1376) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1174) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2812) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2832) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2771) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([321...70])
        at net.minecraft.util.GsonHelper.convertToString(GsonHelper.java:97) ~[?:?]
        at net.minecraft.util.GsonHelper.getAsString(GsonHelper.java:103) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$EntityTooltipInfo.create(HoverEvent.java:177) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$Action.deserialize(HoverEvent.java:136) ~[?:?]
        at net.minecraft.network.chat.HoverEvent.deserialize(HoverEvent.java:80) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.getHoverEvent(Style.java:405) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:377) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:364) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.1.jar:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:361) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:222) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:536) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:221) ~[LoneLibs (6).jar:?]
        ... 47 more
[16:50:39 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutOpenWindow@4f6cda79[
    a=97
    b=net.minecraft.world.inventory.Containers@21ec70a
    c=translation{key='entity.minecraft.wandering_trader', args=[]}[style={hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@f17b8d88'},insertion=132573ca-8ec7-4b72-9b7a-e049470795ee}]
  ]
```

**Comment by LoneDev6** [comment]
Make sure you're running LoneLibs 1.0.42.
Check your server log, thanks!
I already fixed that issue in the latest LoneLibs update.

**Comment by DexterSK** [comment]
> Make sure you're running LoneLibs 1.0.42. Check your server log, thanks! I already fixed that issue in the latest LoneLibs update.

I'm already using 1.0.42


[18:00:34 INFO]: LoneLibs version 1.0.42
[18:00:34 INFO]: Collection of libs used by my plugins
[18:00:34 INFO]: Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Can you try this other JAR file?
Thanks.
https://lobfile.com/file/GLI8.jar

**Comment by LoneDev6** [comment]
About this error:
```
[16:44:41 WARN]: [ItemsAdder] Task #50852592 for ItemsAdder v3.6.3-beta-5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
        at ia.m.nC.a(SourceFile:454) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at ia.m.nC.a(SourceFile:365) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at ia.m.nC.a(SourceFile:194) ~[ItemsAdder_3.6.3-beta-5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

I need you to let me know which recipe triggers this issue as I cannot trigger this error with my recipes.

**Comment by SirCraftypants** [comment]
He's closed your github entry because you are not giving him what he needs to reproduce, leaving him a poor review was not appropriate. 

You need to provide all information required for him to fix the problem, if you don't then how can you expect him to fix it.

Remove the review, provide the information he requested so he can fix it.

Also as you are not a Beta Tester you shouldn't be downloading Beta versions if you have not got the patience, you should have downloaded the last stable version and if you didn't know the last stable version then, you should have asked on Discord and i would have told you.
