### ISSUE TITLE
VERY bad error

### ISSUE THREAD

**Issue by 44wrw44** [PluginBugs/Issues-ItemsAdder#3283]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I tried to upgrade to 1.20.4 it stopped working properly. And when you log in, the server turns off.

### Steps to reproduce the issue

1. Install an empty purpur 1.20.4 kernel.
2. Start the server.

### Server version

PurPur 1.20.4  #2113

### ItemsAdder Version

ItemsAdder 3.6.3-beta-5

### ProtocolLib Version

ProtocolLib [#679](https://ci.dmulloy2.net/job/ProtocolLib/679/)

### LoneLibs Version

LoneLibs 1.0.42

### Error (optional)

```shell
[18:58:44 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-5

java.lang.ArrayIndexOutOfBoundsException: Index -4 out of bounds for length 24

at ia.m.kU.a(SourceFile:83) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at ia.m.kU.N(SourceFile:76) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at ia.m.kT.g(SourceFile:50) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at ia.m.da.a(SourceFile:749) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at ia.m.cG.a(SourceFile:94) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2112]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2112]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2112]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:132) ~[?:?]

at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:45) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1991) ~[?:?]

at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2624) ~[?:?]

at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:1077) ~[?:?]

at net.minecraft.world.level.Level.setBlock(Level.java:1044) ~[?:?]

at net.minecraft.world.level.Level.setBlock(Level.java:958) ~[?:?]

at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.setTypeAndData(CraftBlock.java:206) ~[purpur-1.20.4.jar:git-Purpur-2112]

at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.setTypeAndData(CraftBlock.java:191) ~[purpur-1.20.4.jar:git-Purpur-2112]

at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.setBlockData(CraftBlock.java:187) ~[purpur-1.20.4.jar:git-Purpur-2112]

at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.setBlockData(CraftBlock.java:181) ~[purpur-1.20.4.jar:git-Purpur-2112]

at ia.m.cG.a(SourceFile:127) ~[ItemsAdder_3.6.3-beta-5.jar:?]

at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2112]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2112]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2112]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:1092) ~[?:?]

at net.minecraft.world.level.Level.setBlock(Level.java:1044) ~[?:?]

at net.minecraft.world.level.Level.setBlock(Level.java:958) ~[?:?]

at net.minecraft.world.level.block.FireBlock.tick(FireBlock.java:192) ~[?:?]

at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1276) ~[?:?]

at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1441) ~[?:?]

at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]

at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]

at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:874) ~[?:?]

at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1746) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2112]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2112]

at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

[crash-2024-01-03_14.57.32-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/13821159/crash-2024-01-03_14.57.32-server.txt)

**Comment by LoneDev6** [comment]
Thanks, I will post a fix as soon as possible!

**Comment by 44wrw44** [comment]
Thanks
