### ISSUE TITLE
IaReload in onlinesv

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#3293]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dinobossyt

### What happened?

Hello, well, the problem that occurs is in the last 2 versions of itemsadder beta. It is related to when I remove content from the "contains" or delete entire folders; itemsadder gets stuck, which didn't happen before. Additionally, it returns 1 error.

### Steps to reproduce the issue

Well, the installation of ItemsAdder is normal, as well as the elitecreatures packs.

### Server version

[10:01:06 INFO]: Checking version, please wait...
[10:01:07 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-346 (MC: 1.20.4)

### ItemsAdder Version

[10:01:21 INFO]: ItemsAdder version 3.6.3-beta-3
[10:01:21 INFO]: Customized Minecraft without client mods!
[10:01:21 INFO]: Website: devs.beer
[10:01:21 INFO]: Author: LoneDev

[10:01:21 INFO]: ItemsAdder version 3.6.3-beta-5
[10:01:21 INFO]: Customized Minecraft without client mods!
[10:01:21 INFO]: Website: devs.beer
[10:01:21 INFO]: Author: LoneDev

### ProtocolLib Version

[10:02:09 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[10:02:09 INFO]: Provides read/write access to the Minecraft protocol.
[10:02:09 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[10:02:18 INFO]: LoneLibs version 1.0.40
[10:02:18 INFO]: Collection of libs used by my plugins
[10:02:18 INFO]: Authors: LoneDev and others 

[10:02:18 INFO]: LoneLibs version 1.0.42
[10:02:18 INFO]: Collection of libs used by my plugins
[10:02:18 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/DJaNiuN

### Error (optional)

```shell
[09:58:07 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[09:58:07 WARN]: java.util.ConcurrentModificationException
[09:58:07 WARN]:        at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1619)
[09:58:07 WARN]:        at ItemsAdder_3.6.3-beta-3.jar//ia.m.G.b(SourceFile:628)
[09:58:07 WARN]:        at ItemsAdder_3.6.3-beta-3.jar//ia.m.G.c(SourceFile:573)
[09:58:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[09:58:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[09:58:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1470)
[09:58:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[09:58:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1379)
[09:58:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[09:58:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[09:58:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
> iaz
[09:58:09 WARN]: [ItemsAdder] Already reloading... Please wait before using /iazip
```

### Problematic items yml configuration file (optional)

```shell
null
```

### Other files, you can drag and drop them here to upload. (optional)

null

### Screenshots/Videos (you can drag and drop files or paste links)

null

**Comment by LoneDev6** [comment]
Can't reproduce it but I will fix it as soon as possible
