### ISSUE TITLE
Conflict with Plugin

### ISSUE THREAD

**Issue by PlayGlowCraft** [PluginBugs/Issues-ItemsAdder#3317]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [ ] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

glowcraft

### What happened?

restricting advancedkits

### Steps to reproduce the issue

1. Load Jars

### Server version

This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-7t

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[00:37:53] [Server thread/INFO]: [AdvancedKits] [NBTAPI] NMS support 'MC1_20_R3' loaded!
[00:37:53] [Server thread/ERROR]: Error occurred while enabling AdvancedKits v1.2.2 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.lookupClass(SimpleListPluginClassLoaderGroup.java:46) ~[paper-1.20.4.jar:git-Paper-381]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.20.4.jar:git-Paper-381]
	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.20.4.jar:git-Paper-381]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:136) ~[paper-1.20.4.jar:git-Paper-381]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.4.jar:git-Paper-381]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at me.extremall.advancedkits.proguard.C.a(HookManager.java:103) ~[AdvancedKits-1.2.2.jar:?]
	at me.extremall.advancedkits.proguard.C.<init>(HookManager.java:29) ~[AdvancedKits-1.2.2.jar:?]
	at me.extremall.advancedkits.AdvancedKits.onEnable(AdvancedKits.java:237) ~[AdvancedKits-1.2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-381]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-381]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-381]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-381]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-381]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:37:53] [Server thread/INFO]: [AdvancedKits] Disabling AdvancedKits v1.2.2
[00:37:53] [Server thread/INFO]: [AdvancedKits] Successfully force-disabled in 0 ms!
```

**Comment by PlayGlowCraft** [comment]
I will try and explain a little better the situation. I have a Dev Server setup. I am Upgrading to 1.20.4. I had issues with AdvancedKits Loading. I went through and started removing Plugins. As soon as i removed Itemsaddr advancedkits will load. I talked to the developer of advanced kits and he gave me this code snipet and said this is the only part of the api for itemsaddr he uses. Any help would be Greatly appreciated.

public class ItemsAdderItem extends ItemHook
{
    public ItemsAdderItem(@NotNull String name)
    {
        super(name);
    }

    @Override
    public @NotNull String getName()
    {
        return this.name;
    }

    @Override
    public @Nullable ItemStack getItem(String value, UUID uuid)
    {
        CustomStack customStack = CustomStack.getInstance(value);
        if (customStack == null) return null;
        return customStack.getItemStack().clone();
    }
}

**Comment by LoneDev6** [comment]
Post the whole log of when the issue occurred, I think there is more information about that since there is no valuable information in the error.

**Comment by LoneDev6** [comment]
I have no idea what this code does:
```java
	at me.extremall.advancedkits.proguard.C.a(HookManager.java:103) ~[AdvancedKits-1.2.2.jar:?]
	at me.extremall.advancedkits.proguard.C.<init>(HookManager.java:29) ~[AdvancedKits-1.2.2.jar:?]
	at me.extremall.advancedkits.AdvancedKits.onEnable(AdvancedKits.java:237) ~[AdvancedKits-1.2.2.jar:?]
```

Anyway `java.lang.IllegalStateException: zip file closed` is usually thrown when jar files are corrupted or during reloads.
Ask the dev of AdvancedKits to join this chat to help me understanding what is `HookManager` doing because the cause might be in their code.

**Comment by PlayGlowCraft** [comment]
sent request in support ticket

**Comment by extremall-dev** [comment]
Hello, the HookManager.java:103 is just hooking into the Essentials plugin.

**Comment by LoneDev6** [comment]
For some reason that hooking is trying to load some classes from a JAR which throws  `java.lang.IllegalStateException: zip file closed`.

@PlayGlowCraft  Can you try redownloading the Essentials jar please?

**Comment by PlayGlowCraft** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13956504/latest.log)

This is the latest log with the latest essentials dev build EssentialsX-2.21.0-dev+25-fbfd7e9

**Comment by PlayGlowCraft** [comment]
ok just out of curiousity i removed essentials and ran startup both itemsaddr and advancedkits ran fine together without essentials

**Comment by PlayGlowCraft** [comment]
Something in the Latest Paper update fixed the issue i updated to Paper 389 and everything is loading fine now.
