### ISSUE TITLE
Failed to check ClientboundSystemChatPacket for adventure Component field

### ISSUE THREAD

**Issue by Waritphat** [PluginBugs/Issues-ItemsAdder#3318]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

17dome

### What happened?

I try to update Itemadder,  ProtocolLib, LoneLibs in lastest version. when I ran the server, I got error Failed to check ClientboundSystemChatPacket for adventure Component field

### Steps to reproduce the issue

1. Download Itemadder,  ProtocolLib, LoneLibs in the lastest version.
2. Move files to plugins.
3. Run the server.

### Server version

paper-1.18.2

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13897493/latest.log)

### Error (optional)

```shell
[11:51:03] [Server thread/ERROR]: [ItemsAdder] �[m�[0;31;1mFailed to check ClientboundSystemChatPacket for adventure Component field.�[m
[11:51:03] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not find packet for type SYSTEM_CHAT
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$1(PacketRegistry.java:437)
[11:51:03] [Server thread/WARN]: at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:437)
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113)
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.events.PacketContainer.(PacketContainer.java:117)
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:389)
[11:51:03] [Server thread/WARN]: at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.createPacket(PacketFilterManager.java:384)
[11:51:03] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-7.jar//ia.m.iT.init(SourceFile:112)
[11:51:03] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-7.jar//ia.m.iQ.init(SourceFile:372)
[11:51:03] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-7.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:218)
[11:51:03] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:51:03] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:51:03] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[11:51:03] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[11:51:03] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[11:51:03] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[11:51:03] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[11:51:03] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[11:51:03] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[11:51:03] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:51:03] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by LoneDev6** [comment]
Update ProtocolLib.
https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by brnxx** [comment]
`> version Protocol
[17:48:15 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[17:48:15 INFO]: Provides read/write access to the Minecraft protocol.
[17:48:15 INFO]: Authors: dmulloy2 and comphenix
> version ItemsAdder
[17:48:16 INFO]: ItemsAdder version 3.6.3-beta-7
[17:48:16 INFO]: Customized Minecraft without client mods!
[17:48:16 INFO]: Website: devs.beer
[17:48:16 INFO]: Author: LoneDev
> version LoneLib
[17:48:20 INFO]: LoneLibs version 1.0.45
[17:48:20 INFO]: Collection of libs used by my plugins
[17:48:20 INFO]: Authors: LoneDev and others`

I did this update and I still have the same error too.

https://pastebin.com/MgG9wfSQ
