### ISSUE TITLE
Loading ItemsAdder on server without network access

### ISSUE THREAD

**Issue by TUCAOEVER** [PluginBugs/Issues-ItemsAdder#3321]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After updating to beta-7 from 3.5.1 i got error in console which prevents me from using ItemsAdder

### Steps to reproduce the issue

After running the server.

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13911039/latest.log)

### Error (optional)

```shell
[10:51:05] [Server thread/ERROR]: Could not load 'plugins\ItemsAdder_3.6.3-beta-7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Error resolving libraries
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Error resolving libraries
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 7 more
Caused by: org.bukkit.craftbukkit.libs.org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.apache.httpcomponents:httpmime:jar:4.5.14
	at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 7 more
Caused by: org.bukkit.craftbukkit.libs.org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.apache.httpcomponents:httpmime:jar:4.5.14
	at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:288) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 7 more
```

**Comment by TUCAOEVER** [comment]
> For some reason on 1.16 your server is trying to load libraries from the plugin.yml This is a behaviour of 1.17+ only.
> 
> Anyway your server cannot reach `repo.maven.apache.org` to download some of the needed libraries of the plugin. Can you check if your hosting is blocking connections to these repositories?

Actually it runs on vitural environment with no internet connected, so will there be a backup solution to use IA offline?

**Comment by LoneDev6** [comment]
Why are you running a server on an offline machine?
Lot of other plugins and even Spigot itself downloads some libs on startup, so this is not really an issue isolated to ItemsAdder (as I'm using the Spigot API to download dependencies).

The only idea I have is to launch the server with internet connectivity, let it download the libs, turn it off and remove internet access.
It should now have the libs cached and no need to download them again.
Let me know

**Comment by LoneDev6** [comment]
> And the solution is actually what u said, using a pc with access to those link, cached the libs, copy and paste.

You can do that, it will probably work.
