### ISSUE TITLE
./iazip % /iareload not working.

### ISSUE THREAD

**Issue by JrRequeim** [PluginBugs/Issues-ItemsAdder#3336]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello, i cant load my resourcepack from IA. Sometimes it works, sometimes not -it is pretty werid, it works for first person who joined to server, the rest of players cant even see button to download resourcepack. (Im testing all in localhost)

### Steps to reproduce the issue

After server restart it just stop working, cant even use /iazip and /iareload.

### Server version

paper 2033

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.44

### Error (optional)

```shell
[15:13:30] [Server thread/INFO]: JrRequeim issued server command: /iareload
[15:13:30] [Server thread/INFO]: [ItemsAdder] Reloading...
[15:13:30] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.cancel()" because "this.bukkitTask" is null
[15:13:30] [Server thread/WARN]: 	at LoneLibs.jar//dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.cancelTask(WeakConcurrentCacheHashMap.java:113)
[15:13:30] [Server thread/WARN]: 	at LoneLibs.jar//dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.deleteCompletely(WeakConcurrentCacheHashMap.java:91)
[15:13:30] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.fc.bz(SourceFile:64)
[15:13:30] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.G.f(SourceFile:442)
[15:13:30] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.G.a(SourceFile:468)
[15:13:30] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.if.b(SourceFile:80)
[15:13:30] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.if.onCommand(SourceFile:55)
[15:13:30] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:13:30] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[15:13:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021)
[15:13:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:13:30] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:332)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:316)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2395)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:13:30] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[15:13:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:13:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[15:13:30] [Server thread/ERROR]: [ItemsAdder] Failed to reload the plugin. Please check before this message for more information.
[15:13:31] [Server thread/INFO]: JrRequeim issued server command: /iazip
[15:13:31] [Server thread/ERROR]: [ItemsAdder] Failed to zip resourcepack, uncaught error. Something is probably misconfigured.
[15:13:31] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.cancel()" because "this.bukkitTask" is null
[15:13:31] [Server thread/WARN]: 	at LoneLibs.jar//dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.cancelTask(WeakConcurrentCacheHashMap.java:113)
[15:13:31] [Server thread/WARN]: 	at LoneLibs.jar//dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.deleteCompletely(WeakConcurrentCacheHashMap.java:91)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.fc.bz(SourceFile:64)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.G.f(SourceFile:442)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.G.a(SourceFile:468)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.if.b(SourceFile:80)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.io.a(SourceFile:82)
[15:13:31] [Server thread/WARN]: 	at ItemsAdder_3.6.3-beta-7.jar//ia.m.io.onCommand(SourceFile:57)
[15:13:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:13:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[15:13:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021)
[15:13:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:13:31] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:332)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:316)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2395)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:13:31] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[15:13:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:13:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
[15:13:34] [Server thread/INFO]: JrRequeim issued server command: /ia icons
[15:13:37] [Server thread/INFO]: JrRequeim issued server command: /ia all
[15:13:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
[15:13:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[15:13:40] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'AuctionHouse' to create a bStats instance!
[15:14:41] [User Authenticator #2/INFO]: UUID of player Test_doll is da8ae678-1ea4-309b-948a-c9cb573a7dca
[15:14:41] [Server thread/INFO]: [AuctionHouse] Updating profile player reference for: Test_doll
[15:14:41] [Server thread/INFO]: Test_doll[/127.0.0.1:53507] logged in with entity id 3011 at ([world]31.497304918824792, 169.0, -22.51747930595802)
```

**Comment by JrRequeim** [comment]
even after reinstall whole plugin it still not working :/

**Comment by PortableGames** [comment]
I think it's time for LoneDev to stop supporting several years old versions of mc and focus the plugin on the new versions 1.20.4+ . While it's commendable to maintain those old versions , but why on earth?  Why maintain such a perfect plugin even for versions that don't support modern features like blockentity or new resourcepack features.. maintaining support for those versions costs too much time and constant bug fixing. It would be enough to catch the new wave and be modern..

**Comment by LoneDev6** [comment]
Update LoneLibs.
You're using an old version
https://www.spigotmc.org/resources/lonelibs.75974/
