### ISSUE TITLE
Could not pass event PlayerAnimationEvent to ItemsAdder

### ISSUE THREAD

**Issue by Shmeeb** [PluginBugs/Issues-ItemsAdder#3339]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

shmeeb

### What happened?

Upon opening crate keys, occasionally an exception will be fired: https://pastebin.com/B9GQK3mk

### Steps to reproduce the issue

Not sure how to reproduce

### Server version

This server is running Mohist version 1.20.2-134 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT, Forge version 48.1.0)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-7

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

https://pastebin.com/B9GQK3mk

### Error (optional)

```shell
[13:48:15] [Server thread/ERROR] [Minecraft]: Could not pass event PlayerAnimationEvent to ItemsAdder v3.6.3-beta-7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge-1.20.2-48.1.0-universal.jar%23183!/:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.2-48.1.0-universal.jar%23183!/:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[forge-1.20.2-48.1.0-universal.jar%23183!/:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:585) ~[forge-1.20.2-48.1.0-universal.jar%23183!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7953_(ServerGamePacketListenerImpl.java:1881) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.m_5797_(ServerboundSwingPacket.java:25) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.m_5797_(ServerboundSwingPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:169) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:907) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23178!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryView.getType()" because the return value of "org.bukkit.entity.Player.getOpenInventory()" is null
	at ia.m.az.b(SourceFile:351) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge-1.20.2-48.1.0-universal.jar%23183!/:?]
	... 20 more
```

**Comment by LoneDev6** [comment]
> because the return value of "org.bukkit.entity.Player.getOpenInventory()" is null



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/52ad34b8-e8e7-4887-a823-83f8bd12e293)

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/HumanEntity.html#getOpenInventory()

This is a bug of your Spigot fork.
Contact the authors of this fork to tell them that they must not return a null value from this call.
You will have the same issue with multiple plugins, this is not something caused directly by ItemsAdder.
Let me know what they answer, thanks!
