### ISSUE TITLE
Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent

### ISSUE THREAD

**Issue by bladeRR** [PluginBugs/Issues-ItemsAdder#3346]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

when I enter the server an error appears in the console, only when I enter the players

### Steps to reproduce the issue

1.- you enter the server
2.- the error appears in the console

### Server version

[16:48:07 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-241 (MC: 1.20.2)

### ItemsAdder Version

[16:48:34 INFO]: ItemsAdder version 3.6.3-beta-8
[16:48:34 INFO]: Customized Minecraft without client mods!
[16:48:34 INFO]: Website: devs.beer
[16:48:34 INFO]: Author: LoneDev

### ProtocolLib Version

[16:49:00 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-669
[16:49:00 INFO]: Provides read/write access to the Minecraft protocol.
[16:49:00 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:49:16 INFO]: LoneLibs version 1.0.45
[16:49:16 INFO]: Collection of libs used by my plugins
[16:49:16 INFO]: Authors: LoneDev and others

### FULL server log

[latest (10).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13966159/latest.10.log)

### Error (optional)

```shell
[16:47:37 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[LoneLibs (1).jar:?]
        at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[LoneLibs (1).jar:?]
        at ia.m.hE.a(SourceFile:24) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hC.i(SourceFile:124) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hv.onPacketSending(SourceFile:99) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (1).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:242) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:227) ~[paper-1.20.2.jar:git-Paper-318]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:288) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:559) ~[ProtocolLib (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[LoneLibs (1).jar:?]
        ... 30 more
[16:47:37 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@6b42bfa7[
    content=<null>
    b=false
  ]
```

**Comment by LoneDev6** [comment]
Do you have Discord or a [forum](https://forum.devs.beer/) account where I can share a beta JAR with you to test?
Thanks.

**Comment by bladeRR** [comment]
Yes, https://forum.devs.beer/u/bladerr1

**Comment by LoneDev6** [comment]
Sent you a file on the forum.
https://forum.devs.beer/d/2155-beta-testing
