### ISSUE TITLE
NoClassDefFoundError: net/Indyuce/mmoitems/MMOItems

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3354]
```
[06:28:50] [Server thread/ERROR]: [superelite] Error loading the plugin, something is not configured right or an exception occured. More detail:
[06:28:50] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/Indyuce/mmoitems/MMOItems
[06:28:50] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-9.jar//dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:99)
[06:28:50] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-9.jar//ia.m.fr.bI(SourceFile:952)
[06:28:50] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.b(SourceFile:774)
[06:28:50] [Server thread/WARN]: at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.c(SourceFile:624)
[06:28:50] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:28:50] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[06:28:50] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1111)
[06:28:50] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[06:28:50] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[06:28:50] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.Indyuce.mmoitems.MMOItems
[06:28:50] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[06:28:50] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[06:28:50] [Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[06:28:50] [Server thread/WARN]: ... 9 more
```

**Comment by LoneDev6** [comment]
You might have MMOItems disabled in your server and this is causing itemsadder to fail to hook into it.
I will add a better logging for that particular case and skip instead of breaking the ItemsAdder loading.
