### ISSUE TITLE
Error loading the plugin, something is not configured right or an exception occured - 3.6.3-beta-6 to 3.6.3-beta-9

### ISSUE THREAD

**Issue by Jeremylo1** [PluginBugs/Issues-ItemsAdder#3367]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Jeremylo1

### What happened?

Hi,

Since updating to version "3.6.3-beta-9" of the ItemsAdder plugin, I am experiencing an issue: the plugin no longer loads correctly. I tried resolving the issue by deleting the config.yml file, but this did not work. The only workaround I have found so far to get the plugin working is to delete all files and manually replace them. However, this method causes a mix-up in the textures associated with NBTs, particularly for ARMOR STAND and EMOJI.

### Steps to reproduce the issue

1) ItemsAdder 3.6.3-beta-3
2) Update to ItemsAdder 3.6.3-beta-9
3) Start the server

### Server version

This server is running Paper version git-Paper-397 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 76da4bc)
You are running the latest version
Previous version: git-Paper-350 (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-9

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[00:07:33 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[00:07:33 WARN]: java.lang.RuntimeException: Failed to find YML configurations files.
[00:07:33 WARN]:        at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.a(SourceFile:2014)
[00:07:33 WARN]:        at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.b(SourceFile:1941)
[00:07:33 WARN]:        at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.b(SourceFile:665)
[00:07:33 WARN]:        at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.c(SourceFile:624)
[00:07:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[00:07:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[00:07:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1141)
[00:07:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:07:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[00:07:33 WARN]: Caused by: java.nio.file.NoSuchFileException: /home/container/plugins/ItemsAdder/data/items_packs
[00:07:33 WARN]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[00:07:33 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[00:07:33 WARN]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[00:07:33 WARN]:        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[00:07:33 WARN]:        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[00:07:33 WARN]:        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[00:07:33 WARN]:        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[00:07:33 WARN]:        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
[00:07:33 WARN]:        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
[00:07:33 WARN]:        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
[00:07:33 WARN]:        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
[00:07:33 WARN]:        at java.base/java.nio.file.Files.walk(Files.java:3918)
[00:07:33 WARN]:        at java.base/java.nio.file.Files.walk(Files.java:3973)
[00:07:33 WARN]:        at ItemsAdder_3.6.3-beta-9.jar//ia.m.G.a(SourceFile:1955)
[00:07:33 WARN]:        ... 8 more
```

**Comment by Jeremylo1** [comment]
No, actually, I don't have anything under that name in the `data` folder. It seems that the 'items_packs' folder is missing. 
However, I managed to fix my problem by regenerating the ItemsAdder folder and reinstating all the directories, including my last `data` folder.

**Comment by LoneDev6** [comment]
Probably it's the issue, ItemsAdder tries to check if the folder exists but fails, even if it's an optional folder.
I'll do some testing, probably it's related to some recent changes to the folders checking code.
