### ISSUE TITLE
Duplication issue with villagers

### ISSUE THREAD

**Issue by gary81013** [PluginBugs/Issues-ItemsAdder#3372]
REDACTED

**Comment by gary81013** [comment]
This is a very serious problem. It caused a flood of items on my server. I didn’t even know about this bug until 10 days later.

**Comment by LoneDev6** [comment]
Do not report duplication bug publicly.
Your account will be suspended if further duplication issues will be reported from your account.
Please make sure to use the correct section to report this kind of issues.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7746f10b-555d-4c67-ba40-84381a2d71b9)

Thanks.

**Comment by LoneDev6** [comment]
In the meantime disable this setting in config.yml of ItemsAdder.
`fix_trades_guis_match_custom_items: false`

**Comment by gary81013** [comment]
Sorry, my English is not very good. I can't confirm what problems others reported.

**Comment by LoneDev6** [comment]
Do not worry, please in the meantime set the option to false to avoid this issue.

**Comment by gary81013** [comment]
Thanks

**Comment by LoneDev6** [comment]
Strangely I cannot reproduce the issue.
We have to find out a clear way to reproduce this particular situation, I hope you will be able to do that by checking your configurations.


https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/d7d1f1e7-9f60-497f-9bde-c9d9bb33dde4

**Comment by gary81013** [comment]
Maybe you should use these two plugins to simulate villagers trading 'Citizens' 'Shopkeepers'

**Comment by sennby** [comment]
vouch this is a real thing. and good luck repeating it. I have been blindly trying to figure out what this was for 8 days now hours and hours a day. disabled villagers. it takes hours for it to happen on my live server and completely random. Test server couldnt repeat it. I have been working with admincraft, bloom host, etc to trouble shoot this. Finally someone in paper discord pointed to itemsadder.

**Comment by LoneDev6** [comment]
@sennby I just have to find out why it doesn't happen on all my test servers, currently I have no clear way to reproduce the issue.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/1d90c3db-9cfb-47e0-a9c8-5b55764d9e48

**Comment by LoneDev6** [comment]
Managed to reproduce the issue, it's quite hard to do.
I should have fixed it completely in the upcoming update.

**Comment by gary81013** [comment]
[07:06:59 WARN]: [ItemsAdder] Task #185393 for ItemsAdder v3.6.3-beta-11 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryCrafting cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryMerchant (org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryCrafting and org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryMerchant are in unnamed module of loader java.net.URLClassLoader @504bae78)
        at ia.m.oY.a(SourceFile:81) ~[ItemsAdder_3.6.3-beta-11.jar:?]
        at ia.m.oY.a(SourceFile:47) ~[ItemsAdder_3.6.3-beta-11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by LoneDev6** [comment]
Do not report issues on already closed issue pages.
Instead create new ones.
I made a new page for you this time: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3392

**Comment by gary81013** [comment]
Okay, thank you. There are too many steps to report a problem. My English is not very good.

**Comment by LoneDev6** [comment]
Don't worry @gary81013 , understandable
