### ISSUE TITLE
Resource pack not generating properly - 1.16.5

### ISSUE THREAD

**Issue by PluckyLeVrai** [PluginBugs/Issues-ItemsAdder#3380]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@pluckylevrai

### What happened?

Hello!
I have an error with ItemsAdder where when I start my server, an error is displayed in the console. This error causes the inability to generate the ressource pack.

### Steps to reproduce the issue

1. Start your server with ItemsAdder 3.6.3-beta-9.

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-9

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[15:16:52 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-9 generated an exception while executing task 270
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
        at ia.m.rG.Y(SourceFile:578) ~[?:?]
        at ia.m.iI.bV(SourceFile:291) ~[?:?]
        at ia.m.iL.<init>(SourceFile:100) ~[?:?]
        at ia.m.G.a(SourceFile:914) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 10 more
```

**Comment by LoneDev6** [comment]
I will do some checks but strangely your server doesn't have a required library which should be included in the server JAR.
I'll let you know, thanks.
