### ISSUE TITLE
itemsAdderblocksinjector doesnt work after 3.6.2 itemsAdder

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#3386]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

the itemsadder plugin gets disabled if you use itemsadderblocksinjector with 3.6.3 version. i tried 3.6.3beta10 and beta9 and it doesnt work in both. theres no problem in 3.6.2d and 3.6.2c

### Steps to reproduce the issue

install itemsadder 3.6.3beta10
install itemsadderblocksinjector
itemsadder is then disabled

### Server version

git-Purpur-2134 (MC: 1.20.4)*

### ItemsAdder Version

3.6.3-beta-10

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by LoneDev6** [comment]
Please post a log of when the issue occurs, thanks

**Comment by umutardafiliz** [comment]
[00:02:13] [Server thread/INFO]: [ItemsAdderBlocksInjector] Loading server plugin ItemsAdderBlocksInjector v0.0.13
[00:02:13] [Server thread/ERROR]: [ItemsAdderBlocksInjector] Error initializing plugin 'itemsadder-blocks-injector_0.0.13.jar' in folder 'plugins' (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at dev.lone.itemsadder.api.ItemsAdder$Advanced.getBlockDataByInternalId(SourceFile:478) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.getItemsAdderBlockDataByInternalId(CustomBlocksInjector.java:134) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.v1_20_R3.calculateSpoofedNmsBlockIdFromCachedItemsAdderId(v1_20_R3.java:180) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.CachedCustomBlockInfo.<init>(CachedCustomBlockInfo.java:20) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadCacheFile(CustomBlocksInjector.java:96) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadFromCache(CustomBlocksInjector.java:68) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.Main.onLoad(Main.java:22) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:547) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at dev.lone.LoneLibs.Scheduler.asyncLoop(Scheduler.java:97) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.init(WeakConcurrentCacheHashMap.java:33) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.<init>(WeakConcurrentCacheHashMap.java:21) ~[LoneLibs.jar:?]
	at ia.m.fi.<clinit>(SourceFile:28) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	... 16 more

after this theres these

[00:02:31] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-10
[00:02:31] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[00:02:31] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R3' loaded!
[00:02:32] [Server thread/INFO]: SISTEM ⊳ 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-10
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.45
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-2134 (MC: 1.20.4)
                                               
[00:02:32] [Server thread/INFO]: SISTEM ⊳ Registered Citizens NPC Trait: customentity
[00:02:32] [Server thread/ERROR]: SISTEM ⊳ Please set 'enable-api: true' in Vulcan anticheat config.yml in order to enable compatibility and run '/vulcan reload'.
[00:02:32] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.3-beta-10 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.fi
	at ia.m.G.f(SourceFile:456) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at ia.m.G.a(SourceFile:482) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at ia.m.G.<init>(SourceFile:278) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at ia.m.G.a(SourceFile:297) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:418) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Plugin cannot be null [in thread "Server thread"]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:547) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at dev.lone.LoneLibs.Scheduler.asyncLoop(Scheduler.java:97) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.init(WeakConcurrentCacheHashMap.java:33) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.<init>(WeakConcurrentCacheHashMap.java:21) ~[LoneLibs.jar:?]
	at ia.m.fi.<clinit>(SourceFile:28) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.itemsadder.api.ItemsAdder$Advanced.getBlockDataByInternalId(SourceFile:478) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.getItemsAdderBlockDataByInternalId(CustomBlocksInjector.java:134) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.v1_20_R3.calculateSpoofedNmsBlockIdFromCachedItemsAdderId(v1_20_R3.java:180) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.CachedCustomBlockInfo.<init>(CachedCustomBlockInfo.java:20) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadCacheFile(CustomBlocksInjector.java:96) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadFromCache(CustomBlocksInjector.java:68) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.Main.onLoad(Main.java:22) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.4.jar:git-Purpur-2134]
	... 3 more
[00:02:32] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.3-beta-10
[00:02:32] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v3.6.3-beta-10
java.lang.NoClassDefFoundError: Could not initialize class ia.m.fi
	at dev.lone.itemsadder.Main.onDisable(SourceFile:675) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Plugin cannot be null [in thread "Server thread"]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:547) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:250) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at dev.lone.LoneLibs.Scheduler.asyncLoop(Scheduler.java:97) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.init(WeakConcurrentCacheHashMap.java:33) ~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.data.WeakConcurrentCacheHashMap.<init>(WeakConcurrentCacheHashMap.java:21) ~[LoneLibs.jar:?]
	at ia.m.fi.<clinit>(SourceFile:28) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.itemsadder.api.ItemsAdder$Advanced.getBlockDataByInternalId(SourceFile:478) ~[ItemsAdder_3.6.3-beta-10.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.getItemsAdderBlockDataByInternalId(CustomBlocksInjector.java:134) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.v1_20_R3.calculateSpoofedNmsBlockIdFromCachedItemsAdderId(v1_20_R3.java:180) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.CachedCustomBlockInfo.<init>(CachedCustomBlockInfo.java:20) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadCacheFile(CustomBlocksInjector.java:96) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.loadFromCache(CustomBlocksInjector.java:68) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.Main.onLoad(Main.java:22) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519) ~[purpur-1.20.4.jar:git-Purpur-2134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.4.jar:git-Purpur-2134]
	... 3 more

**Comment by LoneDev6** [comment]
Post the whole log, ItemsAdder didn't load at all for some reason which was reported before that log lines.
`NoClassDefFoundError` are triggered by a previous error.

**Comment by umutardafiliz** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14124574/latest.log)

**Comment by LoneDev6** [comment]
Update LoneLibs, ItemsAdder and ItemsAdderBlocksInjector to the today update.
I fixed the reported issue, have a nice week

**Comment by umutardafiliz** [comment]
thanks you too
