### ISSUE TITLE
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryCrafting

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3392]
```
[07:06:59 WARN]: [ItemsAdder] Task #185393 for ItemsAdder v3.6.3-beta-11 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryCrafting cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryMerchant (org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryCrafting and org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryMerchant are in unnamed module of loader java.net.URLClassLoader @504bae78)
        at ia.m.oY.a(SourceFile:81) ~[ItemsAdder_3.6.3-beta-11.jar:?]
        at ia.m.oY.a(SourceFile:47) ~[ItemsAdder_3.6.3-beta-11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by LoneDev6** [comment]
Probably the player has closed the trading and opened another inventory in less than 1 tick.

**Comment by LoneDev6** [comment]
An update will be released in the next days with a fix for this rare issue.
