### ISSUE TITLE
Bug ItemsAdder

### ISSUE THREAD

**Issue by hgtoiwr** [PluginBugs/Issues-ItemsAdder#3395]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I log on to the server, ItemsAdder spams an error, although the resource pack loads perfectly, I do not want to see errors in the console

### Steps to reproduce the issue

1. Join at the server.
2. Open console.
3. Scroll down.
4. See a bug.

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-8

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[2024-02-03-1.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/14152304/2024-02-03-1.log.gz)

### Error (optional)

```shell
[20:18:20 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[LoneLibs.jar:?]
        at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[LoneLibs.jar:?]
        at ia.m.hE.a(SourceFile:24) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hC.i(SourceFile:124) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at ia.m.hv.onPacketSending(SourceFile:99) ~[ItemsAdder_3.6.3-beta-8.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:276) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:2049) ~[?:?]
        at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:1437) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:1423) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:356) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast net.kyori.adventure.text.TextComponentImpl to net.minecraft.network.chat.IChatBaseComponent
        at java.lang.Class.cast(Class.java:4067) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[LoneLibs.jar:?]
        ... 39 more
[20:18:20 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@7e0ed67e[
    content=<null>
    b=false
  ]
```

**Comment by LoneDev6** [comment]
Update the plugin, I already fixed that
