### ISSUE TITLE
Failed to calculate resourcepack hash connection timed out

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#3413]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

belzzebuh

### What happened?

for some reason it doesn't work when starting the server and stays in standby and I don't know why it happens, just update itemsadder together with lonelibs.

### Steps to reproduce the issue

only start server

### Server version

This server is running UniverseSpigot version git-UniverseSpigot-"d0a1684" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d0a1684 on ver/1.20.4-stable)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

[02:33:32 INFO]: LoneLibs version 1.0.45

### Error (optional)

```shell
[02:30:41 ERROR]: [ItemsAdder] Failed to calculate resourcepack hash: 
[02:30:41 WARN]: java.net.ConnectException: Connection timed out
[02:30:41 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[02:30:41 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[02:30:41 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[02:30:41 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
[02:30:41 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[02:30:41 WARN]:        at java.base/java.net.Socket.connect(Socket.java:583)
[02:30:41 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[02:30:41 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[02:30:41 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[02:30:41 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
[02:30:41 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
[02:30:41 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[02:30:41 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[02:30:41 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[02:30:41 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.qG.t(SourceFile:440)
[02:30:41 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.qG.cU(SourceFile:308)
[02:30:41 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.G.a(SourceFile:912)
[02:30:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100)
[02:30:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:30:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:30:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:30:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:30:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LoneDev6** [comment]
Scroll up, I'm sure there is a warning about the fact that the resourcepack is not reachable.
Make sure to follow the hosting tutorial correctly.
This is all I can say without any full log.

**Comment by Belceebuh** [comment]
the full error is the one above, it takes between 3-5 minutes not to load itemsadder and then loads but sends the error provided in the first line

**Comment by LoneDev6** [comment]
The resourcepack URL is not reachable, this is what the error reports.
Make sure that the configured resourcepack hosting is reachable.

**Comment by LoneDev6** [comment]
The resourcepack URL is not reachable, this is what the error reports.
Make sure that the configured resourcepack hosting is reachable.
In the previous log lines you should see your resourcepack URL, this is useful to identify the issue.
What is your hosting method?

**Comment by svaningelgem** [comment]
I have the same issue.

I'm working with Pterodactyl, and because of that the complete server is hidden behind its firewall rules.
After opening up the pack-port (hint to Ptero-users: server-allocation of another port, use port in the IA config), the users can download the resource pack without a problem, but the resource hash cannot be calculated somehow.

Q: why doesn't IA just calculate the hash locally without going to the web to download it?
