### ISSUE TITLE
Flooding of Noteplay Event Errors in Console

### ISSUE THREAD

**Issue by WinteryFlames** [PluginBugs/Issues-ItemsAdder#3420]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

WinteryFlame#7272

### What happened?

Flooding the Console with Errors relating to a note Event. Causing the Server to be very slow and laggy, and lose TPS.

### Steps to reproduce the issue

First Installation, and also added Self-Mysql, yet it appears to be flooding the console with these errors.

### Server version

arclight-1.16.5-1.0.25-7cf92be3 (MC:1.16.5) (Implementing API Version 1.16.5-R0.1-SNAPSHOT

### ItemsAdder Version

ItemsAdder_3.6.3-beta-12

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

### FULL server log

[Sat 12:10:42 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.world.World.func_195593_d(WorldMixin.java:298)
    at net.minecraft.world.server.ServerWorld.func_230547_a_(ServerWorldMixin.java:1375)
    at net.minecraft.world.World.markAndNotifyBlock(WorldMixin.java:236)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:212)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:47)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.min
- [Sat 12:10:43 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:43 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:43 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
  [Sat 12:10:43 INFO  GroupManager] Async Player Login event refresh data... 
  [Sat 12:10:43 INFO  GroupManager] Async Player Login event finshed. 
  [Sat 12:10:43 INFO  Minecraft/ServerLoginNetHandler] UUID of player RosieFae is 3b36e771-f764-4ba4-972b-ff26457b90d0
- [Sat 12:10:43 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:43 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.world.World.func_195593_d(WorldMixin.java:298)
    at net.minecraft.world.server.ServerWorld.func_230547_a_(ServerWorldMixin.java:1375)
    at net.minecraft.world.World.markAndNotifyBlock(WorldMixin.java:236)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:212)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:47)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.min
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.world.World.func_195593_d(WorldMixin.java:298)
    at net.minecraft.world.server.ServerWorld.func_230547_a_(ServerWorldMixin.java:1375)
    at net.minecraft.world.World.markAndNotifyBlock(WorldMixin.java:236)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:212)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:47)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.min
- [Sat 12:10:44 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callNotePlayEvent(CraftEventFactoryMixin.java:1230)
    at net.minecraft.block.NoteBlock.handler$zek000$arclight$notePlay(NoteBlockMixin.java:554)
    at net.minecraft.block.NoteBlock.func_196482_a(NoteBlockMixin.java:54)
    at net.minecraft.block.NoteBlock.play(NoteBlockMixin.java:543)
    at net.minecraft.block.NoteBlock.redirect$zek000$arclight$callNote1(NoteBlockMixin.java:531)
    at net.minecraft.block.NoteBlock.func_220069_a(NoteBlockMixin.java:44)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock_AbstractBlockStateMixin.java:583)
    at net.minecraft.world.World.func_190524_a(WorldMixin.java:339)
    at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlockMixin.java:168)
    at net.minecraft.block.RedstoneDiodeBlock.func_220082_b(RedstoneDiodeBlockMixin.java:153)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215705_a(AbstractBlock_AbstractBlockStateMixin.java:612)
    at net.minecraft.world.chunk.Chunk.func_177436_a(ChunkMixin.java:283)
    at net.minecraft.world.World.func_241211_a_(WorldMixin.java:199)
    at net.minecraft.world.World.func_180501_a(WorldMixin.java:176)
    at net.minecraft.block.RedstoneDiodeBlock.func_225534_a_(RedstoneDiodeBlockMixin.java:43)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock_AbstractBlockStateMixin.java:620)
    at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorldMixin.java:592)
    at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84)
    at net.minecraft.world.server.ServerWorld.func
- [Sat 12:10:45 ERROR Minecraft] Could not pass event NotePlayEvent to ItemsAdder v3.6.3-beta-12
org.bukkit.event.EventException

**Comment by LoneDev6** [comment]
Any reason why this was marked as closed?
