### ISSUE TITLE
ViaVersion, Velocity error - related to scoreboard hide numbers

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3424]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

exxslider

### What happened?

Server 1.20.4 with velocity latest version, viaversion latestversion, viabackwards latest version getting this error in console: (added behind)
        i tried disabling the title and map last location and dosnt work.

### Steps to reproduce the issue

Just a server with ViaVersion, ViaBackwards, items adder send the error.

if i desactivate items adder the error are fixes :/

### Server version

>....[01:17:24 INFO]: Velocity 3.3.0-SNAPSHOT (git-15897c52-b357)
[01:17:24 INFO]: Copyright 2018-2023 Velocity Contributors. Velocity está licenciado bajo los términos de la Licencia Pública General de GNU v3.
[01:17:24 INFO]: velocitypowered.com - GitHub

[01:17:58 INFO]: Checking version, please wait...
[01:17:58 INFO]: This server is running Pufferfish version git-Pufferfish-44 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: f5fa99a on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-29 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-12

### ProtocolLib Version

[01:18:44 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[01:18:44 INFO]: Provides read/write access to the Minecraft protocol.
[01:18:44 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:18:59 INFO]: LoneLibs version 1.0.45
[01:18:59 INFO]: Collection of libs used by my plugins
[01:18:59 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14254458/latest.log)

### Error (optional)

```shell
[01:14:10 WARN] [viaversion]: ERROR IN Protocol1_17_1To1_18 IN REMAP OF UPDATE_SCORE (0x56)
[01:14:10 ERROR]: [server connection] SliderKP -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@2b255309
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: §b}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: §b}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
Caused by: java.io.IOException: Unable to read type VarInt, found ByteType
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:54) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:48) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-357.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        ... 29 more
```

### Problematic items yml configuration file (optional)

```shell
not necesary
```

### Other files, you can drag and drop them here to upload. (optional)

not necesary

### Screenshots/Videos (you can drag and drop files or paste links)

not necesary

**Comment by LoneDev6** [comment]
It's caused by the hide scoreboard numbers option, disable it in the meantime.
It was tested with ViaVersion, ViaBackwards and Paper 1.20.4 and worked fine, so this is strange.

**Comment by SliderKP** [comment]
> It's caused by the hide scoreboard numbers option, disable it in the meantime. It was tested with ViaVersion, ViaBackwards and Paper 1.20.4 and worked fine, so this is strange.


Indeed, deactivating the TAB plugin the problem is solved, but in my case I tried to just deactivate the hide numbers option and it gave this error:

https://paste.gg/p/anonymous/ea4b8639ecdb4256bf788c9467f8ce5a
i think is the same error but im not sure
so in new versions can be solved ?

**Comment by LoneDev6** [comment]
Are we sure this is not a bug of ViaVersion?
This other user reported the same issue on ViaVersion Github page and they don't have ItemsAdder installed (by checking their **[ViaVersion dump info](https://dump.viaversion.com/036c7ce4fc67e66a792aa51013e5c63185722a7287cb238a2f4ae68dd9c26130)**).
https://github.com/ViaVersion/ViaVersion/issues/3666
