### ISSUE TITLE
Java Unsupported Class Version Error

### ISSUE THREAD

**Issue by WaterArchery** [PluginBugs/Issues-ItemsAdder#3437]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Plugin can't run on my 1.16.5 server which has JDK 16. I saw another person that got this issue but he was trying to run it JDK 11.  I posted the error below.

java.lang.UnsupportedClassVersionError: ia/m/jm has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

### Steps to reproduce the issue

1 - Install plugin and its dependencies
2 - Start server with jdk 16

### Server version

> version
[19:38:14 INFO]: Checking version, please wait...
[19:38:15 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[19:38:40 INFO]: ItemsAdder version 3.6.3-beta-12
[19:38:40 INFO]: Customized Minecraft without client mods!
[19:38:40 INFO]: Website: devs.beer
[19:38:40 INFO]: Author: LoneDev

### ProtocolLib Version

[19:38:51 INFO]: ProtocolLib version 5.1.0
[19:38:51 INFO]: Provides read/write access to the Minecraft protocol.
[19:38:51 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[19:39:00 INFO]: LoneLibs version 1.0.45
[19:39:00 INFO]: Collection of libs used by my plugins
[19:39:00 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[19:36:34 ERROR]: Error occurred while enabling ItemsAdder v3.6.3-beta-12 (Is it up to date?)
java.lang.UnsupportedClassVersionError: ia/m/jm has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at ia.m.iS.a(SourceFile:170) ~[?:?]
        at ia.m.iS.a(SourceFile:105) ~[?:?]
        at ia.m.iS.a(SourceFile:42) ~[?:?]
        at ia.m.iS.b(SourceFile:36) ~[?:?]
        at ia.m.mt.<init>(SourceFile:35) ~[?:?]
        at ia.m.mt.init(SourceFile:51) ~[?:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:219) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by LoneDev6** [comment]
Very strange, version 61 means Java 17.
ItemsAdder has a 1.16.5 implementation and for no reason it should be compiled to Java 17.
I will do some checks, probably some Maven bug/issue.

Thanks a lot for the patience, I'm working hard on a very big plugin update for my plugin CinematicsCore and it's taking a lot of my time.
