### ISSUE TITLE
[CRITICAL - 1.20.4] I can't break the chair / Paper Break API

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#3439]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

I can't break the chair

### What happened?

I can't break the chair
```
[22:48:27 WARN]: [ItemsAdder] Task #104067278 for ItemsAdder v3.6.3-beta-12 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(org.bukkit.entity.Entity, org.bukkit.entity.Entity, org.bukkit.event.entity.EntityDamageEvent$DamageCause, java.util.Map, java.util.Map)'
	at ia.m.sj.<init>(SourceFile:19) ~[ItemsAdder_3.6.3-beta-12(1).jar:?]
	at ia.m.rt.a(SourceFile:636) ~[ItemsAdder_3.6.3-beta-12(1).jar:?]
	at ia.m.cf.b(SourceFile:159) ~[ItemsAdder_3.6.3-beta-12(1).jar:?]
	at ia.m.cf.a(SourceFile:118) ~[ItemsAdder_3.6.3-beta-12(1).jar:?]
	at ia.m.cf.a(SourceFile:396) ~[ItemsAdder_3.6.3-beta-12(1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2141]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce the issue

https://youtu.be/ae_5FcsE5bM

### Server version

Purpur 1.20.4 (Paper change API)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/124828932/5368143b-ac1f-4cf4-88db-4079d6c7d84f)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/124828932/bba4e3e6-70a1-4ce0-90c8-921e75450033)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/124828932/a39e5dc8-5921-4897-80a1-bf35cfeeca19)

**Comment by maximbreitman** [comment]
Same

**Comment by whereareiam** [comment]
Same

![](https://github.com/PluginBugs/Issues-ItemsAdder/assets/57540404/f9520bc7-fe0c-470d-aee8-1be110ddedef)

**Comment by PQguanfang** [comment]
> EntityDamageByEntityEvent

Haha, this usually occurs in the initial release of Spigot API 1.20.4, which did not include this method. This method was only added in later updates, and your users can solve this problem by updating their server core to latest.

**Comment by LoneDev6** [comment]
Thanks for the info @PQguanfang, strange since this method was available also on previous Spigot versions.
Anyway the issue should be mitigated by using the deprecated method.
