### ISSUE TITLE
1.16.5 - Issue with block configuration

### ISSUE THREAD

**Issue by PluckyLeVrai** [PluginBugs/Issues-ItemsAdder#3443]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@pluckylevrai

### What happened?

Hello, I found a bug in ItemsAdder where, when I place or break a block with the attribute [placed_model, type: tile], an error appears in the console.

### Steps to reproduce the issue

Place or break a block with the attribute [placed_model, type: tile].

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[15:13:46 WARN]: [ItemsAdder] Task #5070 for ItemsAdder v3.6.3-beta-12 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.d(SourceFile:496) ~[?:?]
        at ia.m.eK.c(SourceFile:286) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]




[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:681) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:636) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2320) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:551) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:681) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:637) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2320) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:551) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:681) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:639) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2320) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:551) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:681) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:640) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2320) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:551) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:681) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:641) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2320) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:551) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[15:14:01 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v3.6.3-beta-12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.TileEntityMobSpawner.save(net.minecraft.server.v1_16_R3.NBTTagCompound)" because "<local5>" is null
        at ia.m.jU.e(SourceFile:70) ~[?:?]
        at ia.m.fi.x(SourceFile:518) ~[?:?]
        at ia.m.fi.L(SourceFile:505) ~[?:?]
        at ia.m.cQ.a(SourceFile:430) ~[?:?]
        at ia.m.cQ.b(SourceFile:413) ~[?:?]
        at ia.m.cQ.c(SourceFile:554) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:565) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.a(World.java:588) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: enoziaia
items:
  enozium_block:
    display_name: "&5Bloc de Enozium"
    resource:
      generate: true
      material: STONE
      textures:
        - enoziaia:block/enozium_block
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: BLOCK
        cancel_drop: false
        break_tools_whitelist:
          - enoziaia:enozium_hammer
          - enoziaia:netherite_hammer
          - enoziaia:enozium_pickaxe
          - NETHERITE_PICKAXE
        hardness: 10
        sound:
          break:
            name: minecraft:block.stone.break
          place:
            name: minecraft:block.stone.place
```

**Comment by PluckyLeVrai** [comment]
**Problem solved.**
