### ISSUE TITLE
Reloading a plug-in and generating a resource pack will not load properly,

### ISSUE THREAD

**Issue by ximuya2** [PluginBugs/Issues-ItemsAdder#3447]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Reloading a plug-in and generating a resource pack will not load properly, and different sub-servers will not generate the same resource pack even if they have exactly the same configuration, it is always a little different

### Steps to reproduce the issue

1.reload the plugin
2./iazip

### Server version

 Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Paper-196 (MC: 1.20.1

### ItemsAdder Version

[12:39:19 INFO]: ItemsAdder version 3.6.3-beta-12
[12:39:19 INFO]: Customized Minecraft without client mods!
[12:39:19 INFO]: Website: devs.beer
[12:39:19 INFO]: Author: LoneDev

### ProtocolLib Version

[12:41:53 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[12:41:53 INFO]: Provides read/write access to the Minecraft protocol.
[12:41:53 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:42:31 INFO]: LoneLibs version 1.0.45
[12:42:31 INFO]: Collection of libs used by my plugins
[12:42:31 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14326462/latest.log)

### Error (optional)

```shell
[12:26:51 WARN]: [ItemsAdder] Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
[12:26:51 WARN]: [ItemsAdder] Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
[12:26:51 WARN]: [ItemsAdder] Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
[12:26:51 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[12:26:51 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[12:26:51 INFO]: [ItemsAdder] Loaded 295 items
[12:26:51 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[12:26:51 INFO]: [ItemsAdder] Used 29/750 REAL_NOTE block IDs
[12:26:51 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[12:26:51 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[12:26:51 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[12:26:51 INFO]: [ItemsAdder] Used 198/6608 font_images
[12:27:12 ERROR]: [ItemsAdder] Failed to calculate resourcepack hash:
[12:27:12 WARN]: java.net.ConnectException: Connection timed out: connect
[12:27:12 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[12:27:12 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:589)
[12:27:12 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:578)
[12:27:12 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[12:27:12 WARN]:        at java.base/java.net.Socket.connect(Socket.java:751)
[12:27:12 WARN]:        at java.base/java.net.Socket.connect(Socket.java:686)
[12:27:12 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[12:27:12 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[12:27:12 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[12:27:12 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
[12:27:12 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[12:27:12 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1304)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1052)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[12:27:12 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[12:27:12 WARN]:        at java.base/java.net.URL.openStream(URL.java:1325)
[12:27:12 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.qG.t(SourceFile:440)
[12:27:12 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.qG.cU(SourceFile:308)
[12:27:12 WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.G.a(SourceFile:912)
[12:27:12 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:27:12 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:27:12 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:27:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:27:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:27:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:27:12 INFO]: [ItemsAdder] [Init] Loaded 13 categories
[12:27:12 INFO]: [ItemsAdder] [Init] Loaded successfully in 21365ms
[12:27:12 INFO]: [ItemsAdder]
[12:27:12 INFO]: [ItemsAdder]
[12:27:12 INFO]: [ItemsAdder] [Pack] Started generation
[12:27:12 INFO]: [EconomyShopGUI-Premium] [INFO]: Enabled ItemsAdder hook...
[12:27:12 INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[12:27:12 INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[12:27:12 INFO]: [Mythic] Reloading plugin...
[12:27:12 INFO]: [MythicMobs] Loading Packs...
[12:27:13 INFO]: [MythicMobs] Loading Items...
[12:27:13 INFO]: [MythicMobs] Loading Item Groups...
[12:27:13 INFO]: [MythicMobs] Loading Skills...
[12:27:13 INFO]: [MythicMobs] Loading stat ATTACK_DAMAGE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat ATTACK_SPEED from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat BONUS_DAMAGE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat CRITICAL_STRIKE_CHANCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat CRITICAL_STRIKE_DAMAGE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat CRITICAL_STRIKE_RESILIENCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DAMAGE_REDUCTION from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DEFENSE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DODGE_CHANCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DODGE_NEGATION from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat HEALTH from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat HEALTH_REGENERATION from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat LIFESTEAL_CHANCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat LIFESTEAL_POWER from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat MOVEMENT_SPEED from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat PARRY_CHANCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat PARRY_NEGATION from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat PARRY_POWER from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat PARRY_COUNTERATTACK from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat ARMOR_GENERIC from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat ARMOR_BLUNT from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat ARMOR_SHARP from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DAMAGE_BLUNT from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat DAMAGE_SHARP from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat FIRE_RESISTANCE from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading stat SPEED from D:\Java Server\plugins\MythicMobs\stats.yml
[12:27:13 INFO]: [MythicMobs] Loading Drop Tables...
[12:27:13 INFO]: [MythicMobs] Loading Random Spawns...
[12:27:13 INFO]: [MythicMobs] Loading Spawn Blocks...
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 60 mobs.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 572 skills.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 0 random spawns.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 25 mythic items.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 10 drop tables.
[12:27:13 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[12:27:13 INFO]: [Mythic] Mythic has finished reloading!
[12:27:13 INFO]: [MythicMobs] Mythic has finished reloading!
[12:27:13 INFO]: [ItemsAdder]
[12:27:13 INFO]: [ItemsAdder] [Pack] Generated resourcepack
[12:27:13 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[12:27:13 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[12:27:14 WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[12:27:14 INFO]: [ItemsAdder]
[12:27:14 INFO]: [ItemsAdder]
[12:27:14 INFO]: [ItemsAdder] [Pack] Saved into Java Server/plugins/ItemsAdder/output/generated.zip
[12:33:10 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-12 generated an exception while executing task 610505
java.lang.NullPointerException: Cannot invoke "String.length()" because "hash" is null
        at net.minecraft.network.protocol.game.ClientboundResourcePackPacket.<init>(ClientboundResourcePackPacket.java:17) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.sendTexturePack(ServerPlayer.java:2155) ~[?:?]
        at ia.m.mp.a(SourceFile:22) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.qG.ax(SourceFile:187) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.qP.av(SourceFile:68) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at ia.m.qG.ay(SourceFile:126) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LoneDev6** [comment]
> [12:27:12 ERROR]: [ItemsAdder] Failed to calculate resourcepack hash:
[12:27:12 WARN]: java.net.ConnectException: Connection timed out: connect

Your resource pack URL is unreachable.

> different sub-servers will not generate the same resource pack even if they have exactly the same configuration, it is always a little different

You should not generate the same pack on different servers, but let one server generate the pack and use external-host on the other servers referencing the main server resourcepack URL.
