### ISSUE TITLE
CraftMagicNumbers com.mojang.brigadier.exceptions.CommandSyntaxException

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3448]
https://forum.devs.beer/d/2253-packet-abnormality-causing-the-player-to-issue-too-many-packets
Server version: 1.20.2
Plugin: 3.6.3-beta-12
```
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #7/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[22:07:14] [Server thread/ERROR]: [ItemsAdder] Unhandled exception number 64 occurred in onPacketSending(PacketEvent) for ItemsAdder
com.google.gson.JsonSyntaxException: java.io.IOException: lonelibs.net.kyori.adventure.nbt.StringTagParseException: Expected character '{' but got 'f'(at position 0)	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.serializeLegacyHoverEvent(StyleSerializer.java:336) \~[LoneLibs.jar:?]	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:307) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:62) \~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:842) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:712) \~[gson-2.10.1.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:252) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77) \~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196) \~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70) \~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) \~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:842) \~[gson-2.10.1.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:263) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77) \~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:842) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:812) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:759) \~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:736) \~[gson-2.10.1.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:104) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:41) \~[LoneLibs.jar:?]
	at dev.lone.LoneLibs.chat.Comp.componentToJson(Comp.java:147) \~[LoneLibs.jar:?]
	at ia.m.hG.i(SourceFile:115) \~[ItemsAdder_3.6.3-beta-12.jar:?]
	at ia.m.hz.onPacketSending(SourceFile:99) \~[ItemsAdder_3.6.3-beta-12.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) \~[ProtocolLib (1).jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) \~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:392) \~[?:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:276) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:261) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:285) \~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:547) \~[ProtocolLib (1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) \~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:840) \~[?:?]

Caused by: java.io.IOException: lonelibs.net.kyori.adventure.nbt.StringTagParseException: Expected character '{' but got 'f'(at position 0)
	at lonelibs.net.kyori.adventure.nbt.TagStringIO.asCompound(TagStringIO.java:91) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.util.Codec$1.decode(Codec.java:55) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.nbt.api.BinaryTagHolderImpl.get(BinaryTagHolderImpl.java:45) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.json.legacyimpl.NBTLegacyHoverEventSerializerImpl.serializeShowItem(NBTLegacyHoverEventSerializerImpl.java:75) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.serializeShowItem(NBTLegacyHoverEventSerializerImpl.java:55) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.serializeLegacyHoverEvent(StyleSerializer.java:333) \~[LoneLibs.jar:?]
	... 50 more

Caused by: lonelibs.net.kyori.adventure.nbt.StringTagParseException: Expected character '{' but got 'f'(at position 0)
	at lonelibs.net.kyori.adventure.nbt.CharBuffer.makeError(CharBuffer.java:143) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.nbt.CharBuffer.expect(CharBuffer.java:114) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.nbt.TagStringReader.compound(TagStringReader.java:46) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.nbt.TagStringIO.asCompound(TagStringIO.java:85) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.util.Codec$1.decode(Codec.java:55) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.nbt.api.BinaryTagHolderImpl.get(BinaryTagHolderImpl.java:45) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.json.legacyimpl.NBTLegacyHoverEventSerializerImpl.serializeShowItem(NBTLegacyHoverEventSerializerImpl.java:75) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.serializeShowItem(NBTLegacyHoverEventSerializerImpl.java:55) \~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.serializeLegacyHoverEvent(StyleSerializer.java:333) \~[LoneLibs.jar:?]
	... 50 more
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #1/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #4/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #3/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #5/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
[22:07:14] [InteractiveChat Async ChatMessage Processing Thread #0/ERROR]: [org.bukkit.craftbukkit.v1_20_R2.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
player is raised
```

```[22:13:01] [Server thread/INFO]: xxxxxx lost connection: Internal Exception: net.minecraft.network.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutMount is 8468993. Max is 8388608
```

**Comment by LoneDev6** [comment]
I will do some testing but seems to be caused by some malformed JSON message sent by plugins causing ItemsAdder to break due to it using internal Minecraft code to parse JSON messages.
