### ISSUE TITLE
Couldn't place player in world issue

### ISSUE THREAD

**Issue by SkullCN** [PluginBugs/Issues-ItemsAdder#3472]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

SkullCN

### What happened?

https://pastebin.com/bPh4kFw5
I'm pretty sure it's due to the coexistence of itemnbtapi and itemadder 

### Steps to reproduce the issue

**1.**Use any itemadder-supported version of paper
**2.**Install ItemNBTAPI along with itemadder and its associated\dependencies plugins
**3.**Delete the folder related to playerdata in the world folder or have a brand new uuid join the game
**4.**It just happened

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib v5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

https://pastebin.com/qyfbcyE4

### Error (optional)

```shell
[18:28:03] [Server thread/ERROR]: Couldn't place player in world
net.minecraft.ReportedException: Sending packet
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2048) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:280) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:215) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:196) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:84) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:558) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar:?]
	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (13).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (13).jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
	... 13 more
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://bit.ly/4bTRJXB

**Comment by SkullCN** [comment]
> No idea what is itemnbtapi.
> Can you remove it and try to join?

https://www.spigotmc.org/resources/nbt-api.7939/?__cf_chl_tk=ZdJ55rYey46LYFaSXC2Z9OTMh2JY32s8jcUmONkzIn4-1709294328-0.0-1511
https://github.com/tr7zw/Item-NBT-API
Some plugins on my server are using it,  and I've tried removing it, everything became working fine
It may be hard to fix, and if there's no way to fix it, that's okay

**Comment by LoneDev6** [comment]
I know this lib and it should work just fine.
ItemsAdder is not using it by the way, so I don't really see how it can be the cause of the player kick.
Very strange
