### ISSUE TITLE
NullPointerException with cooldown sometimes

### ISSUE THREAD

**Issue by YstalX** [PluginBugs/Issues-ItemsAdder#3488]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After turning on the cooldown, the item stops working and the following error is displayed in the console:

### Steps to reproduce the issue

None

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14567524/latest.log)

### Error (optional)

```shell
[05:05:15] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.6.3-beta-13
java.lang.NullPointerException: Cannot read field "B" because the return value of "java.util.Map.get(Object)" is null
	at ia.m.bp.a(SourceFile:357) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.du.a(SourceFile:192) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
	at dev.lone.LoneLibs.S.mapData(S.java:20) ~[LoneLibs.jar:?]
	at ia.m.du.a(SourceFile:190) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.dp.a(SourceFile:861) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.eM.a(SourceFile:570) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.eM.a(SourceFile:578) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.ey.j(SourceFile:352) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.du.a(SourceFile:176) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at ia.m.du.h(SourceFile:292) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1908) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
posoh:
    display_name: Posoh of Jodah
    permission: posoh
    durability:
      max_custom_durability: 1500
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/posoh
    attribute_modifiers:
      mainhand:
        attackDamage: 14
        attackSpeed: 1.0
    events_settings:
      cooldown:
        indicator: HIDDEN
        ticks: 120
    events:
      interact:
        right:
          execute_commands:
            cmd1:
              command: 'function img:posoh'
              as_console: false
              delay: 0
          play_particle:
            name: FLAME
          damage_near_entities:
            damage: 8
            range: 4
          decrement_durability:
            amount: 20
```

**Comment by YstalX** [comment]
where's the answer? almost a week has passed

**Comment by YstalX** [comment]
cool
