### ISSUE TITLE
'merge_other_plugins_resourcepacks_folders' Issue

### ISSUE THREAD

**Issue by witcharon** [PluginBugs/Issues-ItemsAdder#3497]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

witcharon

### What happened?

I am adding a Hud with the BetterHud plugin, and I'm pulling the assets from within the file through the "merge_other_plugins_resourcepacks_folders" section. Sometimes, when starting the server, I get a related error. Turning it off and back on might not give the error, but it can; it's fair to say it starts up based on luck. To get it to work properly, I might need to turn the server off and on a few times. Once the plugin is correctly loaded, it doesn't cause any issues, but when I need to restart the server, the same cycle occurs.

### Steps to reproduce the issue

1. The server shuts down.
2. An error occurs while the server is starting, and the plugin does not work.
3. Additionally, after the error and the server opens, if I type /iareload, it says '[ItemsAdder] Plugin is still loading... Please wait before using /iareload'.

### Server version

Previous version: git-MultiPaper-"7e90ee5" (MC: 1.20.1)

### ItemsAdder Version

ItemAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[08:25:36 INFO]: Done (27.948s)! For help, type "help"
[08:25:36 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-13 generated an exception while executing task 127
java.io.UncheckedIOException: /root/mmo/plugins/BetterHud/build/assets/betterhud
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2153) ~[commons-io-2.11.0.jar:2.11.0]
        at ia.m.ad.t(SourceFile:496) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.G.a(SourceFile:842) ~[ItemsAdder_3.6.3-beta-13.jar:?]        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[multipaper-1.20.1.jar:MultiPaper-1.2
0.1-14]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[multipaper-1.20.1.ja
r:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: /root/mmo/plugins/BetterHud/build/assets/betterhud
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
        at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:226) ~[?:?]
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
        at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[?:?]
        at java.nio.file.Files.walk(Files.java:3918) ~[?:?]
        at org.apache.commons.io.file.PathUtils.walk(PathUtils.java:1044) ~[commons-io-2.11.0.jar:2.11.0]
        at org.apache.commons.io.FileUtils.streamFiles(FileUtils.java:2971) ~[commons-io-2.11.0.jar:2.11.0]
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2151) ~[commons-io-2.11.0.jar:2.11.0]
        ... 8 more
```

**Comment by LoneDev6** [comment]
Post your config.yml of itemsadder

**Comment by LoneDev6** [comment]
I suspect that these Betterhud folders were created using another linux user compared to the one used to run the server JAR, this causes the plugin (and Spigot server itself) to fail to access the folder.
What you can try to do is rename the `assets\betterhud` folder to `assets\betterhud2`, create a new  `assets\betterhud` folder, move all content of  `assets\betterhud2` into the new folder.
