### ISSUE TITLE
X11

### ISSUE THREAD

**Issue by leonardobarrosbrasil** [PluginBugs/Issues-ItemsAdder#3498]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

leonardobarrosdesign

### What happened?

I use /iazip 

User
java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:?]
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64) ~[?:?]
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59) ~[?:?]
        at sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36) ~[?:?]
        at java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93) ~[?:?]
        at java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84) ~[?:?]
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106) ~[?:?]
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182) ~[?:?]
        at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1171) ~[?:?]
        at ia.m.jr.a(SourceFile:139) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.jr.a(SourceFile:107) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.jr.<init>(SourceFile:44) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.jt.cM(SourceFile:104) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.jh.cC(SourceFile:658) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.G.a(SourceFile:1173) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.il.a(SourceFile:86) ~[ItemsAdder_3.6.2c.jar:?]
        at ia.m.G.a(SourceFile:946) ~[ItemsAdder_3.6.2c.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps to reproduce the issue

/iazip

### Server version

1.20.2

### ItemsAdder Version

3.6.2c

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.31

**Comment by LoneDev6** [comment]
You have some issues in your machine, Java installation Java or libraries.
This has to do with how it's installed.
Normally it works fine on correctly configured Java environments.
