### ISSUE TITLE
Support for linear region format

### ISSUE THREAD

**Issue by TypicalShavonne** [PluginBugs/Issues-ItemsAdder#3502]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

typical.smc

### Describe the solution you'd like

Please implement support for linear region format
it uses zstd compression which help alot for servers with huge maps
Documentations for LinearRegion:
https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools
https://github.com/StupidCraft/LinearPurpur

### Is your feature request related to a problem?

Currently ItemsAdders seem to refuse saving the region of itemsadder custom blocks

```
[19:28:23] [Server thread/ERROR]: [ItemsAdder] Failed to load chunk '635, 280' | world -> /itemsadder/region/r.19.8.pregion
[19:28:23] [Server thread/WARN]: java.util.zip.ZipException: Not in GZIP format
[19:28:23] [Server thread/WARN]:        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
[19:28:23] [Server thread/WARN]:        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[19:28:23] [Server thread/WARN]:        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dg.a(SourceFile:46)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dg.a(SourceFile:23)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.rW.g(SourceFile:242)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:140)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:176)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:182)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:211)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:224)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.a(SourceFile:366)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.dj.isCustomBlock(SourceFile:361)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.cQ.a(SourceFile:426)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.cQ.b(SourceFile:413)
[19:28:23] [Server thread/WARN]:        at ItemsAdder_3.6.3-beta-12.jar//ia.m.cQ.c(SourceFile:554)
[19:28:23] [Server thread/WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[19:28:23] [Server thread/WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:28:23] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:28:23] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:28:23] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:28:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.World.notifyAndUpdatePhysics(World.java:1082)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.World.a(World.java:1034)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.World.a(World.java:948)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.World.a(World.java:1108)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.block.piston.BlockPiston.a(BlockPiston.java:300)
[19:28:23] [Server thread/WARN]:        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:1228)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:2061)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.level.WorldServer.av(WorldServer.java:2047)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:894)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1749)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1548)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1236)
[19:28:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[19:28:23] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

```

### Describe alternatives you've considered

Nope

**Comment by TypicalShavonne** [comment]
Im still getting that error after i converted back to mca regions

**Comment by LoneDev6** [comment]
> Uses slightly more memory than Anvil - it has to store the whole region file in memory for individual chunk access

I'd avoid adding support just for this reason.
