### ISSUE TITLE
1.20.4 - NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutEntityEffect

### ISSUE THREAD

**Issue by FoxtrayStudio** [PluginBugs/Issues-ItemsAdder#3506]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Foxtray

### What happened?

When I connect on the server and load the texture pack I'm getting this error : https://pastebin.com/BxRWQPMe
(The pack load correctly for the player)

### Steps to reproduce the issue

1. Connect to the server and load the pack

### Server version

[01:34:25 INFO]: Checking version, please wait...
[01:34:25 INFO]: Current: git-Purpur-2159 (MC: 1.20.4)*
Previous: git-Purpur-2134 (MC: 1.20.4)
* You are running the latest version

### ItemsAdder Version

[01:35:56 INFO]: ItemsAdder version 3.6.3-beta-13
[01:35:56 INFO]: Customized Minecraft without client mods!
[01:35:56 INFO]: Website: devs.beer
[01:35:56 INFO]: Author: LoneDev

### ProtocolLib Version

[01:36:22 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-673
[01:36:22 INFO]: Provides read/write access to the Minecraft protocol.
[01:36:22 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:36:38 INFO]: LoneLibs version 1.0.45
[01:36:38 INFO]: Collection of libs used by my plugins
[01:36:38 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[00:37:46 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.3-beta-13
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutEntityEffect
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:103) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at ia.m.mX.a(SourceFile:261) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.mX.a(SourceFile:255) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qj.as(SourceFile:142) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qb.a(SourceFile:190) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-"bf86f19"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:73) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:200) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:194) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1352) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1544) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:37:47 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.3-beta-13
java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "<parameter3>" is null
        at ia.m.jR.a(SourceFile:212) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qk.cL(SourceFile:89) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qj.at(SourceFile:186) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qb.a(SourceFile:209) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-"bf86f19"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:73) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[tequila-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:200) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:194) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1352) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1330) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[tequila-1.20.4.jar:git-Paper-"bf86f19"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by LoneDev6** [comment]
In the meantime disable resourcepack player protection in config.yml of ItemsAdder, black screen.

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming update
