### ISSUE TITLE
API - BUG BLOCK IS NULL

### ISSUE THREAD

**Issue by simone2017RR** [PluginBugs/Issues-ItemsAdder#3526]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ububoxthebest

### What happened?

using the api of this plugin I used the event of the custom block interact event, I obtained the clicked block and the normal block then my aim was to modify the blockstates I also obtained the blockstates and, the logic works because the 'I also made it work with a normal block, returning to the custom block it gives me this error "java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "this.calderone" is null" not I know how to solve it, I think the problem is with the ItemsAdder API

### Steps to reproduce the issue

![Screenshot 2024-03-30 191654](https://github.com/PluginBugs/Issues-ItemsAdder/assets/54749913/208e42ee-091d-437d-8600-97a712f6c984)

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-550 (MC: 1.19.4)

### ItemsAdder Version

3.6.3-beta-12

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

### FULL server log

[19:19:46 ERROR]: Could not pass event CustomBlockInteractEvent to saletest v1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getType()" because "this.calderone" is null
        at it.ububox.sale.sale1(sale.java:37) ~[15.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor362.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at ia.m.cv.d(SourceFile:778) ~[ItemsAdder_3.6.3-beta-12.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2015) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: venio
items:
  calderone:
    display_name: 'Calderone'
    resource:
      material: PAPER
      generate: false
      model_path: blocks/calderone
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: false
  calderone_acqua_1:
    display_name: "Calderone 1"
    resource:
      material: PAPER
      generate: false
      model_path: blocks/calderone_acqua_1
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: true
```

**Comment by LoneDev6** [comment]
Do not execute this part of code in the static context.
Execute it when ItemsAdder loads, there is an event for it: ItemsAdderLoadDataEvent.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/e361cb72-e49d-4509-bf05-2116037c1963)

Anyway stop sending screenshots of code, send the actual formatted code text next time.
