### ISSUE TITLE
Index out of Bound error

### ISSUE THREAD

**Issue by L3v3lup** [PluginBugs/Issues-ItemsAdder#3527]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

l0v0lup

### What happened?

This error occured after i adding items to a "Shopkeeper". I created an exchanger for items from 2022 and 2023 for 2024.

new egg nbt: 
```
{CustomModelData:10003,display:{Lore:['{"italic":false,"color":"white","text":""}','{"italic":false,"color":"gray","text":"Info:"}','{"italic":false,"color":"green","text":"Teil des CP Osterevents."}','{"italic":false,"color":"green","text":"Kann am Spawn des Osterevents"}','{"italic":false,"color":"green","text":"eingetauscht werden."}','{"italic":true,"color":"dark_gray","text":"Benötigt das Server-Ressourcepack"}'],Name:'{"italic":false,"color":"gold","text":"Nele\'s Osterei"}'},itemsadder:{id:"egg4",namespace:"easter"}}
``` 

old egg nbt:
``` 
{CustomModelData:10003,display:{Lore:['{"text":""}','{"italic":false,"color":"gray","text":"Info:"}','{"italic":false,"color":"green","text":"Teil des CP Osterevents."}','{"italic":false,"color":"green","text":"Kann am Spawn des Osterevents"}','{"italic":false,"color":"green","text":"eingetauscht werden."}','{"italic":true,"color":"dark_gray","text":"Benötigt das Server-Ressourcepack"}'],Name:'{"italic":false,"color":"gold","text":"Nele\'s Osterei"}'},itemsadder:{id:"egg4",namespace:"easter"}}
``` 

### Steps to reproduce the issue

1. Add an item with the old- and one with a new nbt format to shopkeeper
2. try to exchange it

Note: It does work - sometimes!

### Server version

This server is running Purpur version git-Purpur-2062 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder v3.6.3-beta-13

### ProtocolLib Version

ProtocolLib v5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs v1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14812952/latest.log)

### Error (optional)

```shell
[18:25:40 WARN]: [ItemsAdder] Task #804159 for ItemsAdder v3.6.3-beta-13 generated an exception
java.lang.IndexOutOfBoundsException: Index 9 out of bounds for length 8
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
        at ia.m.oY.a(SourceFile:102) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.oY.a(SourceFile:47) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:857) ~[?:?]
```

**Comment by LoneDev6** [comment]
Thanks for the report, anyway the new ItemsAdder version automatically allows trading recipes to accept items which were renamed or with different NBT.
ItemsAdder checks if the item has the same id and namespace internally now.
It can be disabled and enabled in config.yml
```yml
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true ### <--- here
```

**Comment by L3v3lup** [comment]
Thank you for the quick fix.
It happend quite frequently. I would say about 1 out of 2 or 3 trades.
