### ISSUE TITLE
BUG on load TexturePack

### ISSUE THREAD

**Issue by Hysteriox** [PluginBugs/Issues-ItemsAdder#3530]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Hysteriox

### What happened?

On load of resosurce pack by a player a error are send in Console and block the load of the resourcepack

### Steps to reproduce the issue

Have Already pack loaded, go on a other server and go back on the old server

### Server version

Don't work on all version

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.0

### LoneLibs Version

Last

### Other files, you can drag and drop them here to upload. (optional)

[15:34:54] [Server thread/ERROR]: [ItemsAdder] Unhandled exception number 256 occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[?:?]
        at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[?:?]
        at ia.m.hI.a(SourceFile:24) ~[?:?]
        at ia.m.hG.i(SourceFile:135) ~[?:?]
        at ia.m.hz.onPacketSending(SourceFile:99) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:176) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:157) ~[?:?]
        at com.loohp.interactivechat.objectholders.AsyncChatSendingExecutor.lambda$packetSender$4(AsyncChatSendingExecutor.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1256) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[?:?]
        ... 18 more

**Comment by LoneDev6** [comment]
Update to 1.20.2 or 1.20.4, it is probably a 1.20.1 issue.
