### ISSUE TITLE
Java 16 server error with FastNBT (LoneLibs)

### ISSUE THREAD

**Issue by HeroPB** [PluginBugs/Issues-ItemsAdder#3533]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

herohd

### What happened?

I Installed latest version of LonesLibs, ProtocolLib and ItemsAdder but the server crashed

### Steps to reproduce the issue

1) Download LonesLib, ItemsAdder and ProtocolLib
2) Start the server with java 16
3) The server crash

### Server version

Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

v3.6.3-beta-13

### ProtocolLib Version

ProtocolLib v5.1.0

### LoneLibs Version

1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14836559/latest.log)

### Error (optional)

```shell
[14:18:05] [Server thread/ERROR]: This server is not compatible with FastNBT. Server: git-Paper-794 (MC: 1.16.5) (NMS: v1_16_R3)
[14:18:05] [Server thread/WARN]: java.lang.UnsupportedClassVersionError: lonelibs/dev/lone/fastnbt/nms/nbt/CompoundTag_v1_19_R1 has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
[14:18:05] [Server thread/WARN]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201)
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.Implementation.findClassesInPackage(Implementation.java:129)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.Implementation.listAllClasses(Implementation.java:95)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.Implementation.find(Implementation.java:36)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.nbt.NBT.<clinit>(NBT.java:31)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.<init>(NCompound.java:19)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.<init>(NItem.java:23)
[14:18:05] [Server thread/WARN]: 	at ia.m.eM.<init>(SourceFile:114)
[14:18:05] [Server thread/WARN]: 	at ia.m.fr.bJ(SourceFile:418)
[14:18:05] [Server thread/WARN]: 	at ia.m.G.b(SourceFile:785)
[14:18:05] [Server thread/WARN]: 	at ia.m.G.c(SourceFile:641)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[14:18:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083)
[14:18:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:18:05] [Server thread/ERROR]: [ItemsAdder] [m[0;31;1mError loading the plugin, something is not configured right or an exception occured. More detail:[m
[14:18:05] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.ICompoundTag.newInstance()" because "lonelibs.dev.lone.fastnbt.nms.nbt.NBT.compound" is null
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.<init>(NCompound.java:19)
[14:18:05] [Server thread/WARN]: 	at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.<init>(NItem.java:23)
[14:18:05] [Server thread/WARN]: 	at ia.m.eM.<init>(SourceFile:114)
[14:18:05] [Server thread/WARN]: 	at ia.m.fr.bJ(SourceFile:418)
[14:18:05] [Server thread/WARN]: 	at ia.m.G.b(SourceFile:785)
[14:18:05] [Server thread/WARN]: 	at ia.m.G.c(SourceFile:641)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:18:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[14:18:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083)
[14:18:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:18:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by LoneDev6** [comment]
Update to Java 17 and set `-Paper.IgnoreJavaVersion=true` flag.
Let me know.

**Comment by LoneDev6** [comment]
In the meantime you can try 1.0.27 which should be the last version of LoneLibs which doesn't use FastNBT, which has this Java version bug.
