### ISSUE TITLE
FontImageWrapper#getInternal() doesn't exist

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#3547]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

asleepp

### What happened?

FontImageWrapper#getInternal() doesn't exist, even though it's listed in the JavaDocs/API repository

And yes, it does say Skript error, but that is because I develop a Skript addon for ItemsAdder

### Steps to reproduce the issue

I guess make code with that method?

### Server version

This server is running Paper version git-Paper-418 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: bf6e803)
Previous version: git-Purpur-2137 (MC: 1.20.4)

### ItemsAdder Version

[23:37:08 INFO]: ItemsAdder version 3.6.3-beta-12
[23:37:08 INFO]: Customized Minecraft without client mods!
[23:37:08 INFO]: Website: devs.beer
[23:37:08 INFO]: Author: LoneDev

### ProtocolLib Version

[23:37:23 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[23:37:23 INFO]: Provides read/write access to the Minecraft protocol.
[23:37:23 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:38:27 INFO]: LoneLibs version 1.0.45
[23:38:27 INFO]: Collection of libs used by my plugins
[23:38:27 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[23:40:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gui' in plugin Skript v2.8.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-418]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-418]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$13(ServerGamePacketListenerImpl.java:2194) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-418]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-418]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object dev.lone.itemsadder.api.FontImages.FontImageWrapper.getInternal()'
        at me.asleepp.SkriptItemsAdder.elements.sections.SecCreateCustomInventory.execute(SecCreateCustomInventory.java:61) ~[skript-itemsadder-1.4.1.jar:?]
        at me.asleepp.SkriptItemsAdder.elements.sections.SecCreateCustomInventory.walk(SecCreateCustomInventory.java:76) ~[skript-itemsadder-1.4.1.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[Skript.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

**Comment by LoneDev6** [comment]
You're not really supposed to use the getInternal method, it's for internal usage
