### ISSUE TITLE
It won't let me open an itemsadder category

### ISSUE THREAD

**Issue by DextralityNetwork** [PluginBugs/Issues-ItemsAdder#3557]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dextrality_earth

### What happened?

When I do the command /ia <category> it gives me an error in the chat: "there was an error executing this command".

### Steps to reproduce the issue

1. Enter the server
2. We load the plugin
3. We enter
4. We use /ia <category>
In this case /ia Clothing

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/71a408b5-f584-4c05-86f6-38311f777aef)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/c8c36729-0195-4890-9083-dfabefb5545d)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/a24aaf86-74fe-48ca-bcdc-16ac8e4dc82e)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/f21d2ddc-9719-4944-8070-c35740405ee8)

### FULL server log

https://paste.helpch.at/narepipovo.makefile

### Other files, you can drag and drop them here to upload. (optional)

https://paste.helpch.at/ohubigeqog.less

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/1112c176-ff6c-42f5-9cea-89ea3453ee08)

**Comment by LoneDev6** [comment]
Error:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'ia' in plugin ItemsAdder v3.6.3-beta-13
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2263) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2074) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2055) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1288) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: permission
	at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:172) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:212) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at ia.m.hO.onCommand(SourceFile:73) ~[ItemsAdder_3.6.3-beta-13.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Pufferfish-22]
	... 21 more
```

For some reason Luckperms fails to check for a permission.
You might have some misconfigured category permission with bad characters, empty string or something similar which triggered the issue.
Might also be something related to Luckperms itself which I can't control.

Anyway I added a null check in the upcoming update, this should be enough to fix the edge case.
