### ISSUE TITLE
EFFICIENCY hits the error

### ISSUE THREAD

**Issue by Taks1k** [PluginBugs/Issues-ItemsAdder#3582]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I'm trying to give a custom pickaxe the enchantment "efficiency" and it gives an error

### Steps to reproduce the issue

-

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-388 (MC: 1.18.2)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0

### LoneLibs Version

1.0.45

### Full server log

[00:20:02 ERROR]: AlaradaRP | Error loading the plugin, something is not configured right or an exception occured. More detail:
[00:20:02 WARN]: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: EFFICIENCY
[00:20:02 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
[00:20:02 WARN]:        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:86)
[00:20:02 WARN]:        at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:179)
[00:20:02 WARN]:        at ItemsAdder-3.6.3-beta-13.jar//ia.m.fr.bJ(SourceFile:804)
[00:20:02 WARN]:        at ItemsAdder-3.6.3-beta-13.jar//ia.m.G.b(SourceFile:785)
[00:20:02 WARN]:        at ItemsAdder-3.6.3-beta-13.jar//ia.m.G.c(SourceFile:641)
[00:20:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[00:20:02 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:20:02 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[00:20:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[00:20:02 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[00:20:02 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[00:20:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:20:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ctools
items:
  steel_pickaxe:
    enabled: true
    display_name: Стальная кирка
    resource:
      material: IRON_PICKAXE
      generate: true
      textures:
        - item/tools/steel_pickaxe.png
    durability:
      max_custom_durability: 375
    item_flags:
    enchants:
      - EFFICIENCY:1
    attribute_modifiers:
      mainhand:
        attackDamage: 4
        attackSpeed: 1.2
```

**Comment by Taks1k** [comment]
other effects work!

**Comment by Taks1k** [comment]
I just found out that it gives the following error when there is no “_” in the enchantment id

**Comment by Andre601** [comment]
Hello,

You seem to be one version behind with ItemsAdder. The latest version is `3.6.3-beta-14` while yours is `3.6.3-beta-13`.
Could you update ItemsAdder and see if that fixes the issue? If not, then please say so.
Also, it would help us a lot if you could provide the actual full log of your server and not just the error part, as it gives us crucial info.

**Comment by Taks1k** [comment]
[01:13:47] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:13:48] [ServerMain/INFO]: Loaded 7 recipes
[01:13:49] [Server thread/INFO]: Starting minecraft server version 1.19.4
[01:13:49] [Server thread/INFO]: Loading properties
[01:13:49] [Server thread/INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
[01:13:49] [Server thread/INFO]: Server Ping Player Sample Count: 0
[01:13:49] [Server thread/INFO]: Using 4 threads for Netty based IO
[01:13:50] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[01:13:50] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[01:13:50] [Server thread/INFO]: Default game type: SURVIVAL
[01:13:50] [Server thread/INFO]: Generating keypair
[01:13:50] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:21032
[01:13:50] [Server thread/INFO]: Using epoll channel type
[01:13:50] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:13:50] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[01:13:51] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[01:13:52] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar
[01:13:52] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[01:13:52] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[01:13:52] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[01:13:52] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/container/libraries/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[01:13:52] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_19_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[01:13:55] [Server thread/WARN]: Legacy plugin MVdWPlaceholderAPI v3.1.1 does not specify an api-version.
[01:13:55] [Server thread/WARN]: Legacy plugin Sudo v1 does not specify an api-version.
[01:13:56] [Server thread/WARN]: Legacy plugin MessageSounds v1.0 does not specify an api-version.
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loading 6 libraries... please wait
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/fasterxml/jackson/core/jackson-databind/2.12.7.1/jackson-databind-2.12.7.1.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/fasterxml/jackson/core/jackson-core/2.12.7/jackson-core-2.12.7.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/fasterxml/jackson/core/jackson-annotations/2.12.7/jackson-annotations-2.12.7.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/javacord/javacord/3.8.0/javacord-3.8.0.pom
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/javacord/javacord-api/3.8.0/javacord-api-3.8.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/javacord/javacord-core/3.8.0/javacord-core-3.8.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/squareup/okhttp3/okhttp/4.9.3/okhttp-4.9.3.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/squareup/okio/okio/2.8.0/okio-2.8.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.0/kotlin-stdlib-common-1.4.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/jetbrains/kotlin/kotlin-stdlib/1.4.10/kotlin-stdlib-1.4.10.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/jetbrains/annotations/13.0/annotations-13.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/squareup/okhttp3/logging-interceptor/4.9.3/logging-interceptor-4.9.3.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/kotlin-stdlib-jdk8-1.4.10.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/kotlin-stdlib-jdk7-1.4.10.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/neovisionaries/nv-websocket-client/2.14/nv-websocket-client-2.14.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/com/codahale/xsalsa20poly1305/0.11.0/xsalsa20poly1305-0.11.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/io/vavr/vavr/0.10.4/vavr-0.10.4.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/io/vavr/vavr-match/0.10.4/vavr-match-0.10.4.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
[01:13:56] [Server thread/INFO]: [SpigotLibraryLoader] [DiscordSynthesis] Loaded library /home/container/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
[01:13:56] [Server thread/WARN]: Legacy plugin Lores v1.4.1 does not specify an api-version.
[01:13:56] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.2
[01:13:56] [Server thread/INFO]: [ViaVersion] ViaVersion 4.9.2 is now loaded. Registering protocol transformers and injecting...
[01:13:56] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[01:13:56] [Server thread/INFO]: [ViaBackwards] Loading translations...
[01:13:56] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[01:13:56] [Server thread/INFO]: [ViaBackwards] Registering protocols...
[01:13:57] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.104
[01:13:57] [Server thread/INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[01:13:57] [Server thread/INFO]: [FastAsyncWorldEdit] Loading server plugin FastAsyncWorldEdit v2.9.1-SNAPSHOT-659;c93ec87
[01:13:59] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@208f65a8]
[01:13:59] [Server thread/INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.8+33cdb4a
[01:13:59] [Server thread/INFO]: [Multiverse-Core] Loading server plugin Multiverse-Core v4.3.1-b861
[01:13:59] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.5
[01:13:59] [Server thread/INFO]: [MythicMobs] Loading server plugin MythicMobs v5.5.1-9aedaa15
[01:13:59] [Server thread/INFO]: [LumineUtils] (io.lumine.mythic.bukkit.utils.) is bound to plugin MythicMobs - io.lumine.mythic.bukkit.MythicBukkit
[01:13:59] [Server thread/INFO]: [MythicMobs] §4M§6y§6t§6h§2i§2c§2 §3E§3n§1a§1b§1l§5e§5d§4![0m
[01:13:59] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[01:14:00] [Server thread/INFO]: [MythicLib] Loading server plugin MythicLib v1.6.1
[01:14:00] [Server thread/INFO]: [MythicLib] Plugin file is called 'MythicLib-1.6.1.jar'
[01:14:00] [Server thread/INFO]: [MythicLib] Detected Bukkit Version: v1_19_R3
[01:14:00] [Server thread/INFO]: [MythicLib] Hooked onto WorldGuard
[01:14:00] [Server thread/INFO]: [Citizens] Loading server plugin Citizens v2.0.33-SNAPSHOT (build 3362)
[01:14:00] [Server thread/INFO]: [DecentHolograms] Loading server plugin DecentHolograms v2.8.4
[01:14:00] [Server thread/INFO]: [NBTAPI] Loading server plugin NBTAPI v2.12.0
[01:14:00] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
[01:14:00] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R3' loaded!
[01:14:00] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'NBTAPI' to create a bStats instance!
[01:14:00] [Server thread/INFO]: [CoreProtect] Loading server plugin CoreProtect v21.2
[01:14:00] [Server thread/INFO]: [MMOCore] Loading server plugin MMOCore v1.12
[01:14:00] [Server thread/INFO]: [MMOCore] Plugin file is called 'MMOCore-1.12.jar'
[01:14:00] [Server thread/INFO]: [SCore] Loading server plugin SCore v4.24.3.10
[01:14:00] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.45
[01:14:00] [Server thread/INFO]: [ModelEngine] Loading server plugin ModelEngine vR3.1.9
[01:14:00] [Server thread/INFO]: [MMOItems] Loading server plugin MMOItems v6.9.4
[01:14:00] [Server thread/INFO]: [MMOItems] Plugin file is called 'MMOItems-6.9.4.jar'
[01:14:00] [Server thread/INFO]: [MMOItems] Hooked onto WorldEdit
[01:14:01] [Server thread/INFO]: [ExecutableItems] Loading server plugin ExecutableItems v6.24.3.10
[01:14:01] [Server thread/INFO]: [Towny] Loading server plugin Towny v0.100.2.0
[01:14:01] [Server thread/INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+76-71ca7ff
[01:14:01] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.3-beta-13
[01:14:01] [Server thread/WARN]: [38;2;0;25;154m[21mA[38;2;0;26;160m[21ml[38;2;0;27;166m[21ma[38;2;0;28;172m[21mr[38;2;0;29;178m[21ma[38;2;0;30;185m[21md[38;2;0;31;191m[21ma[38;2;0;32;197m[21mR[38;2;0;33;203m[21mP [0;30;1m[21m| [m[0;33;1m'allow_other_plugins_resourcepacks' enabled. Do not report resourcepack loading issues.[m
[01:14:01] [Server thread/INFO]: [MVdWPlaceholderAPI] Loading server plugin MVdWPlaceholderAPI v3.1.1
[01:14:01] [Server thread/INFO]: [EssentialsSpawn] Loading server plugin EssentialsSpawn v2.21.0-dev+76-71ca7ff
[01:14:01] [Server thread/INFO]: [WorldGuardEvents] Loading server plugin WorldGuardEvents v1.18.1
[01:14:01] [Server thread/INFO]: [Sentinel] Loading server plugin Sentinel v2.8.1-SNAPSHOT (build 513)
[01:14:01] [Server thread/INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.9.1
[01:14:01] [Server thread/INFO]: [CustomCrops] Loading server plugin CustomCrops v3.3.1.5
[01:14:01] [Server thread/INFO]: [AnimatedScoreboard] Loading server plugin AnimatedScoreboard v0.3.1
[01:14:01] [Server thread/INFO]: [ClearLag] Loading server plugin ClearLag v3.2.2
[01:14:01] [Server thread/INFO]: [UltimateAutoRestart] Loading server plugin UltimateAutoRestart vBuild 54a
[01:14:01] [Server thread/INFO]: [PluginManagerPlus] Loading server plugin PluginManagerPlus v2.7.6
[01:14:01] [Server thread/INFO]: [AuthMe] Loading server plugin AuthMe v5.6.0-beta2-b2453
[01:14:01] [Server thread/INFO]: [BetterRTP] Loading server plugin BetterRTP v3.6.12
[01:14:01] [Server thread/INFO]: [MyCommand] Loading server plugin MyCommand v5.7.4
[01:14:01] [Server thread/INFO]: [AdvancedPortals] Loading server plugin AdvancedPortals v0.9.3
[01:14:01] [Server thread/INFO]: [Chunky] Loading server plugin Chunky v1.3.92
[01:14:01] [Server thread/INFO]: [TobaccoPipes] Loading server plugin TobaccoPipes v1.0
[01:14:01] [Server thread/INFO]: [MCPets] Loading server plugin MCPets v4.0.3
[01:14:01] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: mcpets [1.0.0]
[01:14:01] [Server thread/INFO]: [MCPets] : mcpets-dismount flag registered successfully !
[01:14:01] [Server thread/INFO]: [MCPets] : mcpets-despawn flag registered successfully !
[01:14:01] [Server thread/INFO]: [MCPets] : mcpets-dismount-flying flag registered successfully !
[01:14:01] [Server thread/INFO]: [MythicMobsGUI] Loading server plugin MythicMobsGUI v1.7.7
[01:14:01] [Server thread/INFO]: [Sudo] Loading server plugin Sudo v1
[01:14:01] [Server thread/INFO]: [Volleyball] Loading server plugin Volleyball v1.4
[01:14:01] [Server thread/INFO]: [ConditionalEvents] Loading server plugin ConditionalEvents v4.49.1
[01:14:01] [Server thread/INFO]: [CrazyAuctions] Loading server plugin CrazyAuctions v1.2.19
[01:14:01] [Server thread/INFO]: [HeadDB] Loading server plugin HeadDB v5.0.0-rc.10
[01:14:01] [Server thread/INFO]: [Brewery] Loading server plugin Brewery v3.1.1
[01:14:01] [Server thread/INFO]: [DeluxeMenus] Loading server plugin DeluxeMenus v1.13.7-Release
[01:14:01] [Server thread/INFO]: [DeluxeMenus] NMS hook has been setup successfully!
[01:14:01] [Server thread/INFO]: [AdvancedAchievements] Loading server plugin AdvancedAchievements v8.0.2
[01:14:01] [Server thread/INFO]: [TownyLevel] Loading server plugin TownyLevel v1.0-SNAPSHOT
[01:14:01] [Server thread/INFO]: [DeathMessages] Loading server plugin DeathMessages v1.4.15
[01:14:01] [Thread-8/WARN]: [NBTAPI] [NBTAPI] The NBT-API in 'NBTAPI' seems to be outdated!
[01:14:01] [Thread-8/WARN]: [NBTAPI] [NBTAPI] Current Version: '2.12.0' Newest Version: 2.12.3'
[01:14:01] [Thread-8/WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!
[01:14:01] [Server thread/INFO]: [HappyHud] Loading server plugin HappyHUD v1.0.12-RELEASE
[01:14:01] [Server thread/INFO]: [CosmeticsCore] Loading server plugin CosmeticsCore v1.2.3d
[01:14:01] [Server thread/INFO]: [WorldGuard-Towny] Loading server plugin WorldGuard-Towny v${project.version}
[01:14:01] [Server thread/INFO]: [GSit] Loading server plugin GSit v1.5.0
[01:14:01] [Server thread/INFO]: [HyronicFriends] Loading server plugin HyronicFriends v1.3.6
[01:14:01] [Server thread/INFO]: [MessageSounds] Loading server plugin MessageSounds v1.0
[01:14:01] [Server thread/INFO]: [TownyChat] Loading server plugin TownyChat v0.115
[01:14:01] [Server thread/INFO]: [BarrelsPlus] Loading server plugin BarrelsPlus v1.15.2-3
[01:14:01] [Server thread/INFO]: [TAB] Loading server plugin TAB v4.0.6
[01:14:01] [Server thread/INFO]: [TownyCultures] Loading server plugin TownyCultures v2.0.1
[01:14:01] [Server thread/INFO]: [ArtMap] Loading server plugin ArtMap v3.9.14
[01:14:01] [Server thread/INFO]: [HamsterAPI] Loading server plugin HamsterAPI v0.2.3
[01:14:01] [Server thread/INFO]: [BeautyQuests] Loading server plugin BeautyQuests v1.0.2
[01:14:01] [Server thread/INFO]: [EventWar] Loading server plugin EventWar v0.0.105
[01:14:01] [Server thread/INFO]: [DiscordSynthesis] Loading server plugin DiscordSynthesis v9.2.8
[01:14:01] [Server thread/INFO]: [LootChest] Loading server plugin LootChest v2.4.0
[01:14:01] [Server thread/INFO]: [SkinsRestorer] Loading server plugin SkinsRestorer v15.0.11
[01:14:01] [Server thread/INFO]: [PL-Hide] Loading server plugin PL-Hide v1.5.21
[01:14:01] [Server thread/INFO]: [EssentialsProtect] Loading server plugin EssentialsProtect v2.21.0-dev+76-71ca7ff
[01:14:01] [Server thread/INFO]: [CustomFishing] Loading server plugin CustomFishing v2.1.3
[01:14:01] [Server thread/INFO]: [TownyIndustry] Loading server plugin TownyIndustry v1.0.0
[01:14:01] [Server thread/INFO]: [ConsoleSpamFix] Loading server plugin ConsoleSpamFix v1.10.0
[01:14:01] [Server thread/INFO]: [Interactions] Loading server plugin Interactions v2.2.6
[01:14:01] [Server thread/INFO]: [Lores] Loading server plugin Lores v1.4.1
[01:14:01] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:14:01] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.104
[01:14:03] [Server thread/INFO]:         __    
[01:14:03] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.104
[01:14:03] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[01:14:03] [Server thread/INFO]: 
[01:14:03] [Server thread/INFO]: [LuckPerms] Loading configuration...
[01:14:03] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[01:14:04] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[01:14:05] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[01:14:05] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 3899ms)
[01:14:05] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[01:14:05] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[01:14:05] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[01:14:05] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[01:14:05] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[01:14:05] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.9.1-SNAPSHOT-659;c93ec87
[01:14:06] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[01:14:06] [Server thread/INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully
[01:14:06] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[01:14:06] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[01:14:06] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightFaweAdapter as the Bukkit adapter
[01:14:07] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[01:14:07] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.45
[01:14:07] [Server thread/INFO]: [PluginManagerPlus] Enabling PluginManagerPlus v2.7.6
[01:14:08] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.0.11
[01:14:09] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1mRunning on Minecraft [33;1m1.19.4[32;1m.[0;39m
[01:14:09] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: skinsrestorer [15.0.11]
[01:14:09] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mPlaceholderAPI expansion registered![0;39m
[01:14:09] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mUsing paper join listener![0;39m
[01:14:09] [Server thread/INFO]: [ConsoleSpamFix] Enabling ConsoleSpamFix v1.10.0
[01:14:09] [Server thread/INFO]: [ConsoleSpamFix] Server version detected: 1.19.4
[01:14:09] [Server thread/INFO]: [ConsoleSpamFix] Loading the config file...
[01:14:09] [Server thread/INFO]: [ConsoleSpamFix] Config file loaded!
[01:14:09] [Server thread/INFO]: [ConsoleSpamFix] ConsoleSpamFix loaded successfully!
[01:14:09] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[01:14:09] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[01:14:09] [Server thread/WARN]: While this ma

**Comment by Taks1k** [comment]
[Uploading latest.log…]()

**Comment by Taks1k** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/15140192/latest.log)

**Comment by Andre601** [comment]
> [latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/15140192/latest.log)

Mind sharing this through a site such as <https://mclo.gs>?

**Comment by Taks1k** [comment]
https://mclo.gs/ofCdEFD

**Comment by Taks1k** [comment]
updating the plugin didn't help either

**Comment by Taks1k** [comment]
Thanks!
