### ISSUE TITLE
[URGENT] Itemsadder spams the entire console if a player is on the server

### ISSUE THREAD

**Issue by enesop** [PluginBugs/Issues-ItemsAdder#3592]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I updated all the plugins to the latest version, still on 1.20.4, whenever I join the server the console starts being spammed by itemsadder by the error below.

The issue happens as soon as I join, there is furniture, custom trees, and custom blocks placed in the world. I am not sure what else I can provide. This happened as soon as I updated everything and restarted the server.

The issue only happens when I join the sever, if I am not in a server or if anyone is not in the server the console will not be spammed by the error.

### Steps to reproduce the issue

1. Update everything to the latest
2. Maybe have some items on your world such as furniture, maybe some with large hitboxes? I am not very sure
3. Join server

### Server version

Leaves version git-Leaves-"e7c14b8" (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.2.1-SNAPSHOT-685

### LoneLibs Version

1.0.45 - it is on .46 I am unsure why it says .45 I seen someone else report this as well, so I assume it is 1.0.46

### Error (optional)

```shell
30.04 01:13:38 [Server] [WARN] [ItemsAdder] Task #117 for ItemsAdder v3.6.3-beta-14 generated an exception
30.04 01:13:38 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "ia.m.aS.getWidth()" because "this.a" is null
30.04 01:13:38 [Server] [INFO] at ia.m.aX.h(SourceFile:213) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at ia.m.bt.l(SourceFile:100) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at ia.m.bt.v(SourceFile:88) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at ia.m.bt.aJ(SourceFile:111) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at ia.m.bp.n(SourceFile:327) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at ia.m.bp.aH(SourceFile:175) ~[ItemsAdder_3.6.3-beta-14.jar:?]
30.04 01:13:38 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1519) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
30.04 01:13:38 [Server] [INFO] at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by Asleeepp** [comment]
You are using a custom paper fork that most likely breaks some of itemsadder code

**Comment by enesop** [comment]
I really doubt that, I never had an issue with it x itemsadder

**Comment by enesop** [comment]
As I suspected, a fresh install of Leaves with everything latest does not have this issue, this is still urgent please update on this.

**Comment by enesop** [comment]
Okay, I found the issue, it is no longer urgent.

The issue is if I have a HUD config, and the font image doesn't exist or it cannot find it, it will I assume try getting the `.getWidth()` of it and since it doesn't exist it throws the error.

Please fix this so that instead of spamming the console it won't load the HUD and give another error in the console about it. There are already errors about it not finding the image, but if this is the case then it should internally disable the HUD.

**Comment by LoneDev6** [comment]
Strange as I cannot reproduce the issue, a fix was introduced in beta 3.5.1, where if a font image is not found for a hud it will get skipped, and if none were found the hud will not load at all.
This is pretty strange, if this is still an issue please provide a sample pack I can load to test it.

Thanks!
