### ISSUE TITLE
Could not pass event PlayerJoinEvent to ItemsAdder v3.6.3-beta-14

### ISSUE THREAD

**Issue by chamo572** [PluginBugs/Issues-ItemsAdder#3594]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have this error, I don't know what it is, I checked my configs and all is good.... the consequences are players can't enchant custom items on anvils
And the error show everytime someone joins

### Steps to reproduce the issue

Since is a console error, I don't know how to reproduce

### Server version

paper 1.20.4

### ItemsAdder Version

v3.6.3-beta-14

### ProtocolLib Version

v 5.2.0-SNAPSHOT-679

### LoneLibs Version

v 1.0.45

### Error (optional)

```shell
https://pastebin.com/UtKarifk
```

**Comment by LoneDev6** [comment]
Try to update Paper 1.20.4 to the latest build.
For some reason vanilla recipes manager can't be found which is not normal.

**Comment by chamo572** [comment]
updated, but the problem stills

[15:45:49 ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v3.6.3-beta-14
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.RecipeHolder.a()" because "recipeholder" is null
        at net.minecraft.stats.ServerRecipeBook.addRecipes(ServerRecipeBook.java:39) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.awardRecipes(ServerPlayer.java:1833) ~[?:?]
        at ia.m.ox.a(SourceFile:232) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ia.m.nL.ap(SourceFile:83) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ia.m.fS.c(SourceFile:23) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor567.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:345) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:134) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by LoneDev6** [comment]
I think for some reason one of your recipes failed to register and caused the plugin to try to send to the server a `null` recipe.
Can you make sure all your recently added recipes are correct? And that you don't have any recipe initialization error in your console?

You can also try to remove some namespaces from your contents folder until the error disappears, so you can identify which file is causing the issue, if no further error contains more info.

**Comment by chamo572** [comment]
[smithing.zip](https://github.com/user-attachments/files/15744271/smithing.zip)

Ok, I made what you said, and I discovered is because this file, idk what it haves wrong, in-game it works, but gives that error on console
Another thing I discovered is that players with a version lower than of the server, (who are connected thanks to viabackwards plugin) when they try to put a custom item on the anvil, it kicks them

**Comment by LoneDev6** [comment]
Can you remove one recipe at a time from this file until you find the bugged recipe?
Thanks.

About the kick, do not allow users with lower clients to join your server. It's useless and just introduces unreliability to the gameplay. ViaBackwards is a cancer if used incorrectly.
