### ISSUE TITLE
Task for ItemsAdder generated an exception

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#3600]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

belzzebuh

### What happened?

messages appear in the console from time to time about the error log below.

### Steps to reproduce the issue

1. Only use the lastest version from itemsadder

### Server version

This server is running UniverseSpigot version git-UniverseSpigot-"3881c25" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3881c25 on ver/1.20.4-stable)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-14

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
[17:52:47 WARN]: [ItemsAdder] Task #31837037 for ItemsAdder v3.6.3-beta-14 generated an exception
java.lang.IndexOutOfBoundsException: Index 7 out of bounds for length 7
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
        at ia.m.pa.a(SourceFile:102) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ia.m.pa.a(SourceFile:47) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"3881c25"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[?:git-UniverseSpigot-"3881c25"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1651) ~[?:git-UniverseSpigot-"3881c25"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:465) ~[?:git-UniverseSpigot-"3881c25"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1534) ~[?:git-UniverseSpigot-"3881c25"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[?:git-UniverseSpigot-"3881c25"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[?:git-UniverseSpigot-"3881c25"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Andre601** [comment]
You seem to use some random fork of Spigot. Please make sure it actually also happens on a more common server such as Spigot itself, Paper or Purpur, as this error could be due to some changes in that particular fork.

**Comment by Belceebuh** [comment]
> You seem to use some random fork of Spigot. Please make sure it actually also happens on a more common server such as Spigot itself, Paper or Purpur, as this error could be due to some changes in that particular fork.

it is not a random fork of Spigot, in fact it is a Pufferfish fork with more than 200 clients. Happened to me when upgrading itemsadder to the latest version

**Comment by LoneDev6** [comment]
Might be an issue of UniverseSpigot, never received this report and I can't reproduce it.
