### ISSUE TITLE
Failed to calculate resourcepack hash form remote URL

### ISSUE THREAD

**Issue by heartlion1** [PluginBugs/Issues-ItemsAdder#3615]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

heartlion

### What happened?

IA can't load resourcepack by self host, 1 download resourcepack  with URL from log on browser will be successe,
2 url from command “iainfo" be http://generated.zip#a81da7f37e12857f0da0536a30020cd403288efa, it should be http://180.101.45.44:4301/generated.zip#a81da7f37e12857f0da0536a30020cd403288efa
3 in 3.6.3beta-8 this function will be working fine

### Steps to reproduce the issue

update ia to version 3.6.3-beta-14

### Server version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-454 (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

 5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Full server log

[10:41:17] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder]  
[10:41:17] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Generated resourcepack
[10:41:17] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[10:41:17] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Compressing resource_pack ... 
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_text.fsh
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_entity_translucent.fsh
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_text.vsh
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_entity_translucent.vsh
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/textures/gui/widgets.png
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:18] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/optifine/emissive.properties
[10:41:19] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_text.json
[10:41:19] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder]  
[10:41:19] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder]  
[10:41:19] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Saved into /测试服/plugins/ItemsAdder/output/generated.zip
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/ERROR]: [ItemsAdder] Failed to calculate resourcepack hash form remote URL http://180.101.45.44:4301/generated.zip#a81da7f37e12857f0da0536a30020cd403288efa.
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: java.net.SocketTimeoutException: Connect timed out
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.t(SourceFile:484)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.bA(SourceFile:310)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.cU(SourceFile:290)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.G.a(SourceFile:1219)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qe.a(SourceFile:471)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Compressed in 16869ms
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Applying to every player... 
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-14 generated an exception while executing task 19196
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
	at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.<init>(ClientboundResourcePackPushPacket.java:14) ~[paper-1.20.4.jar:git-Paper-496]
	at ia.m.mr.a(SourceFile:26) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.ax(SourceFile:186) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qP.av(SourceFile:67) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.aa(SourceFile:136) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iu.b(SourceFile:182) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iu.b(SourceFile:104) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.G.a(SourceFile:1222) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qe.a(SourceFile:471) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:43:12] [Server thread/INFO]: HeartLion lost connection: Disconnected
[10:43:12] [Server thread/INFO]: HeartLion left the game
[10:43:14] [User Authenticator #1/INFO]: UUID of player HeartLion is e2dea87a-909a-3299-8348-121317a18b69
[10:43:14] [Server thread/INFO]: [StateManager] 错误,不存在的状态重生保护
[10:43:14] [Server thread/INFO]: HeartLion joined the game
[10:43:14] [Server thread/INFO]: HeartLion[/220.179.249.224:64424] logged in with entity id 142 at ([xjcb]-198.27714038936156, 83.0, 33.74334133862465)
[10:43:14] [Craft Scheduler Thread - 70 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-14 generated an exception while executing task 35057
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
	at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.<init>(ClientboundResourcePackPushPacket.java:14) ~[paper-1.20.4.jar:git-Paper-496]
	at ia.m.mr.a(SourceFile:26) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.ax(SourceFile:186) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qP.av(SourceFile:67) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.ay(SourceFile:125) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Error (optional)

```shell
[ItemsAdder] Failed to calculate resourcepack hash form remote URL http://180.101.45.44:4301/generated.zip#a81da7f37e12857f0da0536a30020cd403288efa.
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: java.net.SocketTimeoutException: Connect timed out
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.t(SourceFile:484)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.bA(SourceFile:310)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qG.cU(SourceFile:290)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.G.a(SourceFile:1219)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.3-beta-14.jar//ia.m.qe.a(SourceFile:471)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Compressed in 16869ms
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Applying to every player... 
[10:41:34] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-14 generated an exception while executing task 19196

[ItemsAdder] Plugin ItemsAdder v3.6.3-beta-14 generated an exception while executing task 19196
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
	at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.<init>(ClientboundResourcePackPushPacket.java:14) ~[paper-1.20.4.jar:git-Paper-496]
	at ia.m.mr.a(SourceFile:26) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.mj.a(SourceFile:40) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.ax(SourceFile:186) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qP.av(SourceFile:67) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qG.aa(SourceFile:136) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iu.b(SourceFile:182) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iu.b(SourceFile:104) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.G.a(SourceFile:1222) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.qe.a(SourceFile:471) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Andre601** [comment]
This error happens usually when ItemsAdder can't connect to the URL to setup everything.

Double-check that the connection is actuslly valid and downloads the resource pack for you.

**Comment by Andre601** [comment]
This is also most likely the same as #3574, so I'll close this.
