### ISSUE TITLE
Could not load ItemsAdder because of invalid plugin.yml

### ISSUE THREAD

**Issue by yNathanNha** [PluginBugs/Issues-ItemsAdder#3629]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nathannha

### What happened?

I recently bought ItemsAdder and i keep getting this error i tried using older versions but nothing changes

### Steps to reproduce the issue

download the plugin
put in the plugins folder
run the server

### Server version

paper-1.18.1-216

### ItemsAdder Version

v3.6.3-beta-14

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Full server log

Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.10+7-Ubuntu-120.04.1) Host: Linux 6.5.11-8-pve (amd64)
Loading libraries, please wait...
[17:52:39 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:52:40 INFO]: Reloading ResourceManager: Default, bukkit
[17:52:41 INFO]: Loaded 7 recipes
[17:52:42 INFO]: Starting minecraft server version 1.18.1
[17:52:42 INFO]: Loading properties
[17:52:42 INFO]: This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
[17:52:42 INFO]: Server Ping Player Sample Count: 12
[17:52:42 INFO]: Using 4 threads for Netty based IO
[17:52:42 INFO]: Default game type: SURVIVAL
[17:52:42 INFO]: Generating keypair
[17:52:43 INFO]: Starting Minecraft server on 192.168.1.200:25565
[17:52:43 INFO]: Using epoll channel type
[17:52:43 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[17:52:43 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[17:52:43 ERROR]: Could not load 'plugins/ItemsAdder_3.6.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:420) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1762) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1546) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 6 more
[17:52:43 INFO]: [WorldEdit] Loading WorldEdit v7.2.20+6667-f0f1e66
[17:52:44 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@78466ce8]
[17:52:44 INFO]: [ViaVersion] Loading ViaVersion v4.10.2
[17:52:44 INFO]: [ViaVersion] ViaVersion 4.10.2 is now loaded. Registering protocol transformers and injecting...
[17:52:45 INFO]: [ViaVersion] Loading block connection mappings ...
[17:52:45 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[17:52:45 INFO]: [ModelEngine] Loading ModelEngine vR3.1.11
[17:52:45 INFO]: [LoneLibs] Loading LoneLibs v1.0.45
[17:52:45 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.5
[17:52:45 INFO]: [ProtocolLib] Loading ProtocolLib v5.2.0-SNAPSHOT-679
[17:52:46 INFO]: [WorldGuard] Loading WorldGuard v7.0.7+216b061
[17:52:46 INFO]: [SkinsRestorer] Loading SkinsRestorer v15.0.13
[17:52:46 INFO]: [ClothesPlus] Loading ClothesPlus vDEMO
[17:52:46 INFO]: [CommandPanels] Loading CommandPanels v3.21.2.2
[17:52:46 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:52:46 INFO]: [WorldEdit] Enabling WorldEdit v7.2.20+6667-f0f1e66
[17:52:46 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[17:52:46 INFO]: WEPIF: Using the Bukkit Permissions API.
[17:52:47 WARN]:
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

[17:52:47 INFO]: [LoneLibs] Enabling LoneLibs v1.0.45
[17:52:47 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[17:52:47 INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.0.13
[17:52:48 INFO]: [SkinsRestorer] Running on Minecraft 1.18.1.
[17:52:48 INFO]: [PlaceholderAPI] Successfully registered internal expansion: skinsrestorer [15.0.13]
[17:52:48 INFO]: [SkinsRestorer] PlaceholderAPI expansion registered!
[17:52:48 INFO]: [SkinsRestorer] Using paper join listener!
[17:52:48 INFO]: Preparing level "world"
[17:52:49 INFO]: Preparing start region for dimension minecraft:overworld
[17:52:50 INFO]: Time elapsed: 430 ms
[17:52:50 INFO]: Preparing start region for dimension minecraft:the_nether
[17:52:50 INFO]: Time elapsed: 250 ms
[17:52:50 INFO]: Preparing start region for dimension minecraft:the_end
[17:52:50 INFO]: Time elapsed: 338 ms
[17:52:50 INFO]: [ViaVersion] Enabling ViaVersion v4.10.2
[17:52:50 INFO]: [ViaVersion] ViaVersion detected server version: 1.18-1.18.1 (757)
[17:52:50 INFO]: [ModelEngine] Enabling ModelEngine vR3.1.11
[17:52:50 INFO]: [ModelEngine] [S] Compatibility applied: ViaVersion
[17:52:50 INFO]: [ModelEngine] [S] bStats enabled
[17:52:50 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.5
[17:52:51 INFO]: [PlaceholderAPI] Fetching available expansion information...
[17:52:51 INFO]: [WorldGuard] Enabling WorldGuard v7.0.7+216b061
[17:52:51 ERROR]: No TreeType mapping for TreeGenerator.TreeType.MANGROVE
[17:52:51 ERROR]: No TreeType mapping for TreeGenerator.TreeType.TALL_MANGROVE
[17:52:51 ERROR]: No TreeType mapping for TreeGenerator.TreeType.CHERRY
[17:52:51 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[17:52:51 INFO]: [WorldGuard] Loaded configuration for world 'world'
[17:52:51 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[17:52:51 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[17:52:51 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[17:52:51 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[17:52:51 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[17:52:51 INFO]: [WorldGuard] Loading region data...
[17:52:51 INFO]: [ClothesPlus] Enabling ClothesPlus vDEMO
[17:52:52 INFO]: [ClothesPlus] SkinManager reloaded successfully.
[17:52:53 INFO]: [CommandPanels] Enabling CommandPanels v3.21.2.2
[17:52:53 INFO]: [CommandPanels] RockyHawk's CommandPanels v3.21.2.2 Plugin Loading...
[17:52:53 INFO]: [PlaceholderAPI] Successfully registered internal expansion: commandpanels [1.0.0]
[17:52:53 INFO]: [CommandPanels] RockyHawk's CommandPanels v3.21.2.2 Plugin Loaded!
[17:52:53 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[17:52:53 INFO]: 0 placeholder hook(s) registered!
[17:52:53 INFO]: Running delayed init tasks
[17:52:53 INFO]: Done (11.225s)! For help, type "help"
[17:52:53 INFO]: Timings Reset
[17:52:53 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[17:52:53 INFO]: [ModelEngine] [A]
[17:52:53 INFO]: [ModelEngine] [A] [Importing models]
[17:52:53 INFO]: [ModelEngine] [A]
[17:52:53 INFO]: [ModelEngine] [A] [Generating assets]
[17:52:53 INFO]: [ModelEngine] [A]
[17:52:53 INFO]: [ModelEngine] [A] Resource pack zipped.
[17:52:54 INFO]: [SkinsRestorer] ----------------------------------------------
[17:52:54 INFO]: [SkinsRestorer]     +==================+
[17:52:54 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[17:52:54 INFO]: [SkinsRestorer]     |------------------|
[17:52:54 INFO]: [SkinsRestorer]     |  Standalone Mode |
[17:52:54 INFO]: [SkinsRestorer]     +==================+
[17:52:54 INFO]: [SkinsRestorer] ----------------------------------------------
[17:52:54 INFO]: [SkinsRestorer]     Version: 15.0.13
[17:52:54 INFO]: [SkinsRestorer]     Commit: 8e4c6e2
[17:52:54 INFO]: [SkinsRestorer]     This is the latest version!
[17:52:54 INFO]: [SkinsRestorer] ----------------------------------------------

### Error (optional)

```shell
[17:47:02 ERROR]: Could not load 'plugins/ItemsAdder_3.6.3-beta-14.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:420) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1762) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1546) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 6 more
```

**Comment by Andre601** [comment]
The jar file you downloaded was empty somehow, which either means the download got corrupted, or what is more likely, that you use a leaked a version.
Please purchase and download the plugin from its official sources.

**Comment by yNathanNha** [comment]
> The jar file you downloaded was empty somehow, which either means the download got corrupted, or what is more likely, that you use a leaked a version. Please purchase and download the plugin from its official sources.

I did buy it from builtbybit if you want i can prove it

**Comment by Andre601** [comment]
It's something LoneDev may request. I do believe you here, so the fact you got an empty jar (referenced as empty zip) from builtbybit means that eithert they messed up or LoneDev accidentally uploaded an empty jar.

**Comment by yNathanNha** [comment]
> It's something LoneDev may request. I do believe you here, so the fact you got an empty jar (referenced as empty zip) from builtbybit means that eithert they messed up or LoneDev accidentally uploaded an empty jar.

i believe it could be builtbybit who messed it up since with another plugin i also had some problems downloading
