### ISSUE TITLE
world-populator on itemsadder doesn't support to replace block with blockstate

### ISSUE THREAD

**Issue by MaledKhaoSan** [PluginBugs/Issues-ItemsAdder#3643]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

khxoismynickname

### What happened?

sorry , 
1. is there world-populator on itemsadder doesn't support to replace block with blockstate?

i try to replace my customblock to specific noteblock state, cause i have custom biomes and itemsadder support only
vanilla biomes right? so i use this method but its can't,

```ml
worlds_populators:
  maple_log:
    block: blocks:maple_log
    worlds:
    - test_18
    replaceable_blocks:
    - NOTE_BLOCK[instrument=chime,note=12,powered=off]
    biomes:
    - BIRCH_FOREST
    - PLAINS
    chunk_chance: 1000.0
    max_height: 100
    min_height: 1
    vein_blocks: 1000
    chunk_veins: 1000
```
2. if i need to replace a someblock with my customblock in everyworld?
i should try to remove a worlds article right? (same as biomes to replace every biomes)
like this ? (not have worlds: article) but its still not work
```ml
worlds_populators:
  maple_log:
    block: blocks:maple_log
    replaceable_blocks:
    - GRASS_BLOCK
    biomes:
    - BIRCH_FOREST
    - PLAINS
    chunk_chance: 1000.0
    max_height: 100
    min_height: 1
    vein_blocks: 1000
    chunk_veins: 1000
```

### Steps to reproduce the issue

Use a custom biomes (Terra plugin) and world populator on itemsadder to replace block

### Server version

Paper 1.20.4

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.2.1-SNAPSHOT-686

### LoneLibs Version

1.0.45

### Error (optional)

```shell
[03:13:54 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.3-beta-14 generated an exception while executing task 934334
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at ia.m.gK.f(SourceFile:166) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ia.m.fu.d(SourceFile:21) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ia.m.G.a(SourceFile:835) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```

**Comment by LoneDev6** [comment]
Exactly why do you need to replace blocks by their blockstate?
Are you trying to replace custom blocks already generated by Terra plugin?

**Comment by MaledKhaoSan** [comment]
yes, but now, i find a solution that, i use your itemsadderInjectionBlock to inject into Terra Generate , and its work fine
