### ISSUE TITLE
Not working on 1.20.5 +

### ISSUE THREAD

**Issue by HWFunnyMan** [PluginBugs/Issues-ItemsAdder#3648]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

-----#2364

### What happened?

Simple.

It's not working on first step.

### Steps to reproduce the issue

1. Same of first install process.
2. stop the server

put ProtocolLib and LonLibs in plugins folder

then put ItemsAdder.jar file in plugins folder

start

not working.

i even tried over 7 hours maybe.(try in clear, changing versions, try with spigot, changing spigot versions, downgrading java.)

i checked IA has work on paper 1.20.4 and spigot 1.20.1. but i cannot enter the server with my 1.20.6 client

searching on IA wiki, google, store page, and finally here.

sorry for bad english. have a good day.

### Server version

paper-1.20.6-82

### ItemsAdder Version

ItemsAdder_3.6.3-beta-14

### ProtocolLib Version

ProtocolLib v5.2.1-SNAPSHOT-689

### LoneLibs Version

LoneLibs v1.0.45

### Full server log

[07:47:42 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-14.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.get(Version.java:77) ~[LoneLibs.jar:?]
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isOlderThan(Version.java:67) ~[LoneLibs.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/ia.m.R.m(SourceFile:454) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/dev.lone.itemsadder.Main.bP(SourceFile:591) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

[07:47:47 ERROR]: Error occurred while enabling ItemsAdder v3.6.3-beta-14 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at LoneLibs.jar/dev.lone.LoneLibs.nbt.nbtapi.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[LoneLibs.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/ia.m.iW.a(SourceFile:393) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/ia.m.iZ.b(SourceFile:143) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:216) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[07:47:47 INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.3-beta-14
[07:47:47 ERROR]: Error occurred while disabling ItemsAdder v3.6.3-beta-14
java.lang.ExceptionInInitializerError: null
        at ItemsAdder_3.6.3-beta-14.jar/dev.lone.itemsadder.Main.onDisable(SourceFile:688) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.get(Version.java:77) ~[LoneLibs.jar:?]
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isAtLeast(Version.java:45) ~[LoneLibs.jar:?]
        at ItemsAdder_3.6.3-beta-14.jar/ia.m.mt.<clinit>(SourceFile:114) ~[ItemsAdder_3.6.3-beta-14.jar:?]
        ... 16 more

**Comment by Andre601** [comment]
ItemsAdder is not yet supporting the latest 1.20.x version, but will eventually.
