### ISSUE TITLE
[ItemsAdder] Failed to find nms implementation for: interface ia.m.ms

### ISSUE THREAD

**Issue by WhiteProject1** [PluginBugs/Issues-ItemsAdder#3650]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

batuhan____

### What happened?

not working 

### Steps to reproduce the issue

just error on start

### ItemsAdder Version

itemsadder_3.6.3-beta-14.jar

### ProtocolLib Version

protocollib 5.2.0

### LoneLibs Version

1.0.46

### Full server log

dont need

### Error (optional)

```shell
[09:33:14] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-14
[09:33:14] [Server thread/ERROR]: [ItemsAdder] Failed to find nms implementation for: interface ia.m.ms
[09:33:14] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.3-beta-14 (Is it up to date?)
java.lang.RuntimeException: null
	at ia.m.iS.a(SourceFile:137) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iS.a(SourceFile:45) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.iS.b(SourceFile:36) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.mt.<init>(SourceFile:35) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at ia.m.mt.init(SourceFile:51) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:219) ~[ItemsAdder_3.6.3-beta-14.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:33:14] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.3-beta-14
```

**Comment by Andre601** [comment]
1. LoneDev made a new release of ItemsAdder, so maybe this fixes your issue
2. Please provide the requested stuff, especially the server logs and proper steps to reproduce things.
