### ISSUE TITLE
1.20 - Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()"

### ISSUE THREAD

**Issue by uParis** [PluginBugs/Issues-ItemsAdder#3667]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When using the latest version of ItemsAdder, LoneLibs, and ProtocolLib, the server shuts itself.

### Steps to reproduce the issue

Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()"

### Server version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
You are running the latest version

### ItemsAdder Version

3.6.4

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### LoneLibs Version

1.0.54

### Full server log

[17:35:43] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:35:43] [ServerMain/INFO]: Loaded 7 recipes
[17:35:44] [Server thread/INFO]: Starting minecraft server version 1.20
[17:35:44] [Server thread/INFO]: Loading properties
[17:35:44] [Server thread/INFO]: This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
[17:35:44] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:35:44] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:35:44] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[17:35:44] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 5 worker threads, and gen parallelism of 5 threads
[17:35:44] [Server thread/INFO]: Default game type: SURVIVAL
[17:35:44] [Server thread/INFO]: Generating keypair
[17:35:44] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:35:44] [Server thread/INFO]: Using default channel type
[17:35:44] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[17:35:44] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\iParis\Desktop\Hyperia\libraries\org\apache\httpcomponents\httpmime\4.5.14\httpmime-4.5.14.jar
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\iParis\Desktop\Hyperia\libraries\org\apache\httpcomponents\httpclient\4.5.14\httpclient-4.5.14.jar
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\iParis\Desktop\Hyperia\libraries\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\iParis\Desktop\Hyperia\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar
[17:35:45] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\iParis\Desktop\Hyperia\libraries\commons-codec\commons-codec\1.11\commons-codec-1.11.jar
[17:35:45] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.1-SNAPSHOT-689
[17:35:46] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.54
[17:35:46] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.4
[17:35:46] [Server thread/ERROR]: [ItemsAdder] Error getting server minor version: For input string: "20-R0"
[17:35:46] [Server thread/WARN]: [ItemsAdder] Custom player emotes require Minecraft 1.17+. Feature disabled.
[17:35:46] [Server thread/ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.4.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
	at lonelibs.dev.lone.fastnbt.nms.Version.isOlderThan(Version.java:86) ~[LoneLibs.jar:?]
	at ia.m.R.m(SourceFile:454) ~[ItemsAdder_3.6.4.jar:?]
	at dev.lone.itemsadder.Main.bP(SourceFile:591) ~[ItemsAdder_3.6.4.jar:?]
	at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.4.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:430) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:35:46] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:35:46] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.1-SNAPSHOT-689
[17:35:46] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.54
[17:35:46] [Server thread/INFO]: Preparing level "world"
[17:35:46] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:35:46] [Server thread/INFO]: Time elapsed: 143 ms
[17:35:46] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[17:35:46] [Server thread/INFO]: Time elapsed: 23 ms
[17:35:46] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[17:35:46] [Server thread/INFO]: Time elapsed: 19 ms
[17:35:46] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.4
[17:35:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Minecraft: v1_20_R1! Trying to find NMS support
[17:35:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R1' loaded!
[17:35:46] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'LoneLibs' to create a bStats instance!
[17:35:46] [Server thread/ERROR]: [ItemsAdder] ════════════════════════════════════════════════════════════════════
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder] This server version is not supported: 1.20.0
[17:35:46] [Server thread/WARN]: [ItemsAdder] You're running an outdated version of Spigot. Please update it to 1.20.1.
[17:35:46] [Server thread/WARN]: [ItemsAdder] Open config.yml and set 'ignore-server-compatibility-check: true' 
to load the plugin anyway and to report them on Github:
> http://a.devs.beer/ia-not-compat-git <
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder]  
[17:35:46] [Server thread/ERROR]: [ItemsAdder] ════════════════════════════════════════════════════════════════════
[17:35:46] [Server thread/INFO]: Running delayed init tasks
[17:35:46] [Server thread/INFO]: Done (2.440s)! For help, type "help"
[17:35:46] [Server thread/INFO]: Stopping server
[17:35:46] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.4
[17:35:47] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v3.6.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at dev.lone.itemsadder.Main.onDisable(SourceFile:688) ~[ItemsAdder_3.6.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:493) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
	at lonelibs.dev.lone.fastnbt.nms.Version.isAtLeast(Version.java:64) ~[LoneLibs.jar:?]
	at ia.m.ms.<clinit>(SourceFile:114) ~[ItemsAdder_3.6.4.jar:?]
	... 12 more
[17:35:47] [Server thread/INFO]: [LoneLibs] Disabling LoneLibs v1.0.54
[17:35:47] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.1-SNAPSHOT-689
[17:35:47] [Server thread/INFO]: Saving players
[17:35:47] [Server thread/INFO]: Saving worlds
[17:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world' in 0,00s
[17:35:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_nether' in 0,00s
[17:35:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[17:35:47] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_the_end' in 0,00s
[17:35:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:35:47] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:35:47] [Server thread/INFO]: Flushing Chunk IO
[17:35:47] [Server thread/INFO]: Closing Thread Pool
[17:35:47] [Server thread/INFO]: Closing Server

**Comment by Andre601** [comment]
> [17:35:46] [Server thread/ERROR]: [ItemsAdder] This server version is not supported: 1.20.0
[17:35:46] [Server thread/WARN]: [ItemsAdder] You're running an outdated version of Spigot. Please update it to 1.20.1.

**Comment by uParis** [comment]
Okay, but then which version is needed?

**Comment by Andre601** [comment]
As the message mentions, use at least 1.20.1, tho you should preferably use 1.20.4 as that is the latest supported version by ItemsAdder right now.
There is no real reason to stay on 1.20, especially given later versions fix bugs and issues.

**Comment by uParis** [comment]
Okay, but what is the version for 1.20, I don't want to and I can't change the version

**Comment by uParis** [comment]
On your spigot page it is clearly written "Minecraft versions tested: 1.15 1.16 1.17 1.18 1.19 1.20" or "✅ Compatible with Spigot 1.15.2 to 1.20.4 and Java 8 to 17"

**Comment by Andre601** [comment]
If you mean this
![SmartSelect_20240527-182242_Firefox.jpg](https://github.com/PluginBugs/Issues-ItemsAdder/assets/11576465/b22b5efa-1ba1-4654-b045-c04d13ba8cec)

That is just what spigot gives the dev to show.
The other part is not automatically saying, that all versions are supported.

Again, there is no justifiable reason to stay on 1.20 itself.

**Comment by uParis** [comment]
If my server is 1.20

**Comment by uParis** [comment]
I'm not going to have fun changing the entire server for a plugin, or it exists in 1.20

**Comment by Andre601** [comment]
1.20.1 is a bugfix release, meaning players with 1.20 can also join.
And updating is literally just swapping the server jar.

**Comment by uParis** [comment]
But I have to change version to have it

**Comment by uParis** [comment]
I don't want to change version

**Comment by uParis** [comment]
I just want a version for 1.20

**Comment by Andre601** [comment]
I really can't see your issue here.
Updating to 1.20.1 is just swapping the server jar. Players with 1.20 can still join, plugins will still work, worlds will still be the same.
This is not a breaking update at all for your server.

But your choice.
If you really want an older plugin version check the plugin page's version history for one that works on 1.20.
But don't expect any support from our end.
