### ISSUE TITLE
Itemsadder, BetterHud

### ISSUE THREAD

**Issue by dafsdfasde** [PluginBugs/Issues-ItemsAdder#3670]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

An error will be displayed if you use the Itemsadder and BetterHud plugins together.

### Steps to reproduce the issue

If you add "- BetterHud/build" to Itemsadder "merge_other_plugins_resourcepacks_folders" and use the /iaz command, an error will be output.

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-2062 (MC: 1.20.1)

### ItemsAdder Version

[07:03:11 INFO]: ItemsAdder version 3.6.4-release-2
[07:03:11 INFO]: Customized Minecraft without client mods!
[07:03:11 INFO]: Website: devs.beer
[07:03:11 INFO]: Author: LoneDev

### ProtocolLib Version

[07:03:19 INFO]: ProtocolLib version 5.2.1-SNAPSHOT-689
[07:03:19 INFO]: Provides read/write access to the Minecraft protocol.
[07:03:19 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[07:03:25 INFO]: LoneLibs version 1.0.54
[07:03:25 INFO]: Collection of libs used by my plugins
[07:03:25 INFO]: Authors: LoneDev and others

### Full server log

[06:58:22 ERROR]: [ItemsAdder] Failed to protect zip file.
[06:58:22 WARN]: java.lang.IndexOutOfBoundsException
[06:58:22 WARN]:        at java.base/java.io.RandomAccessFile.writeBytes0(Native Method)
[06:58:22 WARN]:        at java.base/java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:562)
[06:58:22 WARN]:        at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:592)
[06:58:22 WARN]:        at ItemsAdder_3.6.4-release-2.jar//ia.m.qk.e(SourceFile:116)
[06:58:22 WARN]:        at ItemsAdder_3.6.4-release-2.jar//ia.m.pZ.a(SourceFile:229)
[06:58:22 WARN]:        at ItemsAdder_3.6.4-release-2.jar//ia.m.qd.a(SourceFile:454)
[06:58:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:58:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:58:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:58:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[06:58:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[06:58:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by dafsdfasde** [comment]
It seems that this problem occurs because the images are obfuscated in the BetterHud plugin.
But if I use ItemsAdder_3.6.2c version, that error does not occur.

**Comment by Andre601** [comment]
Could you please provide your full latest.log through <https://mclo.gs>?

**Comment by dafsdfasde** [comment]
https://mclo.gs/ZOjqMDF

**Comment by dafsdfasde** [comment]
> Could you please provide your full latest.log through https://mclo.gs?

**Comment by dafsdfasde** [comment]
> Could you please provide your full latest.log through https://mclo.gs?

test

**Comment by dafsdfasde** [comment]
@Andre601 https://mclo.gs/RDGOcxD

**Comment by Andre601** [comment]
Thanks, LoneDev will look into this once he finds some spare time. Your patience is apreciated.

**Comment by dafsdfasde** [comment]
@Andre601 Thank you, this is a resource security problem, so I hope you will solve it.

**Comment by LoneDev6** [comment]
> It seems that this problem occurs because the images are obfuscated in the BetterHud plugin.

Disable obfuscation in the BetterHud plugin.
