### ISSUE TITLE
ExcellentCrates with ItemsAdder

### ISSUE THREAD

**Issue by O3O-XiZhou** [PluginBugs/Issues-ItemsAdder#3674]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Console error when player right clicks on raffle box

### Steps to reproduce the issue

1.Get the raffle box key
2.Right click draw box
3.The console reports an error

### Server version

This server is running Paper version git-Paper-493 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) 

### ItemsAdder Version

ItemsAdder version 3.6.4

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.54

### Problematic items yml configuration file (optional)

```shell
[ExcellentCrates] Task #639257 for ExcellentCrates v5.2.2.3 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'iagive' in plugin ItemsAdder v3.6.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-493]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1100) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at su.nightexpress.nightcore.util.Players.dispatchCommand(Players.java:186) ~[nightcore-2.6.1.jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Reward.lambda$giveContent$3(Reward.java:321) ~[ExcellentCrates-5.2.2.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at su.nightexpress.excellentcrates.crate.impl.Reward.giveContent(Reward.java:320) ~[ExcellentCrates-5.2.2.3.jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Reward.give(Reward.java:326) ~[ExcellentCrates-5.2.2.3.jar:?]
        at su.nightexpress.excellentcrates.opening.impl.BasicOpening.roll(BasicOpening.java:71) ~[ExcellentCrates-5.2.2.3.jar:?]
        at su.nightexpress.excellentcrates.opening.impl.BasicOpening.onTick(BasicOpening.java:62) ~[ExcellentCrates-5.2.2.3.jar:?]
        at su.nightexpress.excellentcrates.opening.Runnable.tick(Runnable.java:47) ~[ExcellentCrates-5.2.2.3.jar:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at su.nightexpress.excellentcrates.opening.OpeningManager.tickOpenings(OpeningManager.java:82) ~[ExcellentCrates-5.2.2.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-493]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-493]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-493]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-493]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-493]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-493]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-493]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/Indyuce/mmoitems/MMOItems
        at dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:28) ~[ItemsAdder_3.6.4.jar:?]
        at ia.m.G.a(SourceFile:1637) ~[ItemsAdder_3.6.4.jar:?]
        at ia.m.hZ.onCommand(SourceFile:48) ~[ItemsAdder_3.6.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.ClassNotFoundException: net.Indyuce.mmoitems.MMOItems
        at dev.lone.itemsadder.Core.OtherPlugins.mmoitems.MmoItemsHook.injectMmoItem(SourceFile:28) ~[ItemsAdder_3.6.4.jar:?]
        at ia.m.G.a(SourceFile:1637) ~[ItemsAdder_3.6.4.jar:?]
        at ia.m.hZ.onCommand(SourceFile:48) ~[ItemsAdder_3.6.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

**Comment by Andre601** [comment]
Please provide the latest.log of your server through a Paste service such as https://mclo.gs

**Comment by DexterSK** [comment]
looks like you have mmoitems plugin here but its not loaded?
