### ISSUE TITLE
EntitiesLoadEvent and Unhandled exception occurred in onPacketSending(PacketEvent) (ERROR IN CONSOLE)

### ISSUE THREAD

**Issue by Micky117** [PluginBugs/Issues-ItemsAdder#3677]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The error appears after having updated the version of ItemsAdder to the most recent, previously I had it at 3.6.4-beta14 and the errors that appear in the log did not appear

### Steps to reproduce the issue

Just by having the "ItemsAdder" plugin in Arclight the error appears.

### Server version

This server is running Arclight version arclight-1.20.1-1.0.2-730181a4 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.4-release-2

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.54

### Full server log

https://mclo.gs/pFvDwC7

### Error (optional)

```shell
Error 1: [04:51:01 ERROR] [Minecraft]: Could not pass event EntitiesLoadEvent to ItemsAdder v3.6.4-release-2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactoryMixin.java:1806) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.handler$bgg000$arclight$fireLoad(PersistentEntitySectionManagerMixin.java:581) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManagerMixin.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManagerMixin.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftChunk.lambda$3(CraftChunk.java:151) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getEntities(CraftChunk.java:158) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at ia.m.aF.a(SourceFile:461) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunkMixin.java:973) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.level.chunk.LevelChunk.bridge$unloadCallback(LevelChunkMixin.java:930) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ChunkHolder.md2e1950$lambda$arclight$onChunkUnload$0$4(ChunkHolderMixin.java:586) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at io.izzel.arclight.common.mod.util.ArclightCallbackExecutor.run(ArclightCallbackExecutor.java:21) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at net.minecraft.server.level.ChunkHolder.handler$zdf000$arclight$onChunkUnload(ChunkHolderMixin.java:596) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ChunkHolder.m_143003_(ChunkHolderMixin.java:356) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.DistanceManager.m_183906_(DistanceManagerMixin.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.DistanceManager.redirect$zdi000$arclight$safeIter(DistanceManagerMixin.java:556) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManagerMixin.java:119) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCacheMixin.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ServerChunkCache.bridge$tickDistanceManager(ServerChunkCacheMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache_MainThreadExecutorMixin.java:631) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCacheMixin.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:758) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Chunk not there when requested: UNLOADED
        at net.minecraft.server.level.ServerChunkCache.m_8421_(ServerChunkCacheMixin.java:136) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%23111!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCacheMixin.java:132) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.level.Level.m_6522_(LevelMixin.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getChunkAt(CraftWorldMixin.java:213) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getEntities(CraftChunk.java:122) ~[arclight-1.20.1-1.0.2-730181a4.jar%23184!/:arclight-1.20.1-1.0.2-730181a4]
        at ia.m.aF.a(SourceFile:71) ~[?:?]
        at ia.m.aG.a(SourceFile:14) ~[?:?]
        ... 33 more


Error 2:

[04:55:47 ERROR] [Minecraft]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([374...76])
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
        at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
        at ia.m.hG.onPacketSending(SourceFile:186) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.network.Connection.m_129520_(ConnectionMixin.java:212) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.Connection.m_243124_(ConnectionMixin.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(ServerPlayNetHandlerMixin.java:1159) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9829_(ServerPlayNetHandlerMixin.java:1154) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.level.ServerPlayer.m_5893_(ServerPlayerMixin.java:971) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.item.trading.Merchant.m_45301_(MerchantMixin.java:40) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.entity.npc.Villager.m_35536_(VillagerMixin.java:298) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.entity.npc.Villager.m_6071_(VillagerMixin.java:276) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.entity.Mob.m_6096_(MobMixin.java:1122) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.world.entity.player.Player.m_36157_(PlayerMixin.java:979) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1Handler$3bb50c83565f40cd847e6e2759477445.performInteraction(ServerPlayNetHandlerMixin.java:1316) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1Handler$3bb50c83565f40cd847e6e2759477445.m_142299_(ServerPlayNetHandlerMixin.java:1335) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(ServerboundInteractPacket.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerPlayNetHandlerMixin.java:3150) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.protocol.PacketUtils.md2e1950$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([374...76])
        at net.minecraft.util.GsonHelper.m_13805_(GsonHelper.java:119) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.HoverEvent$EntityTooltipInfo.m_130880_(HoverEvent.java:133) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.HoverEvent$Action.m_130848_(HoverEvent.java:344) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.HoverEvent.m_130821_(HoverEvent.java:93) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.Style$Serializer.m_131212_(Style.java:431) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:405) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:387) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%23106!/:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:255) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:152) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23106!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%23106!/:?]
        at net.minecraft.network.chat.Component$Serializer.m_130691_(Component.java:406) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
        ... 44 more
[04:55:47 ERROR] [Minecraft]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundOpenScreenPacket@7c2244bd[
    f_132611_=3
    f_132612_=net.minecraft.world.inventory.MenuType@4c05993e
    f_132613_=translation{key='entity.minecraft.villager.farmer', args=[]}[style={hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.HoverEvent$EntityTooltipInfo@32eeb634'},insertion=1658c749-23cc-4ebd-8d67-d2e8d911ff9c}]
  ]
```

**Comment by Andre601** [comment]
ItemsAdder is not designed for plugin-mod hybrid servers.
