### ISSUE TITLE
Unable to run /iazip when I've done it once. To be able to do /iazip again I have to restart the server

### ISSUE THREAD

**Issue by Javimoa95** [PluginBugs/Issues-ItemsAdder#3679]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

raptorcroissant

### What happened?

I run /iazip and when it's done, I can't run it again anytime soon but if I restart the server. 

### Steps to reproduce the issue

1. Run /iazip
2. Run /iareload
3. Try and do it again and *poof*, doesn't work

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/d00a0443-310a-4c65-92c8-eecd2c8b6701)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/4003b7c0-e6e3-4355-9ee0-dffe642af763)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/af81dcb9-93ab-4de8-b4d1-313633373d87)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/e141b0cc-c75e-4e53-b7f2-309708ebce48)

### Full server log

https://mclo.gs/X6UFyi6 

### Error (optional)

```shell
[20:43:05] [Craft Scheduler Thread - 17 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.4-release-2 generated an exception while executing task 18664
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
    at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.url(ClientboundResourcePackPushPacket.java:13) ~[paper-1.20.4.jar:git-Paper-450]
    at ia.m.mq.a(SourceFile:26) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.mi.a(SourceFile:40) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.qF.ax(SourceFile:186) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.qO.av(SourceFile:67) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.qF.aa(SourceFile:136) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.it.b(SourceFile:182) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.it.b(SourceFile:104) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.G.a(SourceFile:1211) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at ia.m.qd.a(SourceFile:471) ~[ItemsAdder_3.6.4-release-2.jar:?]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-450]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-450]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Closed due to using leaked plugins.

**Comment by Javimoa95** [comment]
What's this... I literally bought the plugin, what's this reasoning to close a bug report...

**Comment by Asleeepp** [comment]
@Andre601 The user has provided proof on discord that they bought the plugin, this issue should be opened.

**Comment by LoneDev6** [comment]
Did you try to download release 3?

**Comment by Javimoa95** [comment]
I have 1.20.4, lastest version won't let me use it because it says "outdated server".

**Comment by Andre601** [comment]
You would use v4 of ItemsAdder for 1.20.6

**Comment by Javimoa95** [comment]
I downloaded lastest 1.20.4 version and it let me*

When downloading 1.20.6 update, it wouldn't. That's what I meant

**Comment by Andre601** [comment]
Your comment makes no sense. Please take some time to actually explain what you're talking about.

**Comment by Javimoa95** [comment]
When downloading any of the v4 beta updates the plugin won't load because it says "outdated server"
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/724791ed-5d80-48db-ac3a-d69cfdafd044)

I currently have this version:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/572b125b-1812-420d-a5fd-1687fbd31c1e)

**Comment by Andre601** [comment]
I just told you:
> You would use v4 of ItemsAdder for 1.20.6

**Comment by Javimoa95** [comment]
Alright, I just downloaded the lastest version for 1.20.4 and it still appears not to work. I have this version:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72030264/dee96b65-ffcc-4a6e-91f9-49f8cf833ae2)

**Comment by LoneDev6** [comment]
> Failed to calculate resourcepack hash form remote URL http://**.**.**.**:25569/generated.zip#2b055887aa431660df25ebddbfc2cfb4034fb6f2.

You have some issues with the port or the hosting in general.
Contact your hosting provider.

**Comment by Javimoa95** [comment]
@LoneDev6 I'm on a dedicated server and the txtp works perfectly. It applies uppon joining and when reloading or doing /iapack doesn't give issues. The only problem is when doing /iazip once and then trying again
