### ISSUE TITLE
 Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder

### ISSUE THREAD

**Issue by mat37dev** [PluginBugs/Issues-ItemsAdder#3685]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mat_37

### What happened?

When player click on vanilla pnj, i have an error in my console.

### Steps to reproduce the issue

Join Server
Spawn an pnj
click on the pnj

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-139 (MC: 1.20.1)

### ItemsAdder Version

3.6.4-release-2

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/DC5ymds

### Error (optional)

```shell
[22:54:37 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([513...30])
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[LoneLibs.jar:?]
        at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[LoneLibs.jar:?]
        at ia.m.hG.onPacketSending(SourceFile:186) ~[ItemsAdder_3.6.4-release-2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2217) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2203) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1594) ~[?:?]
        at net.minecraft.world.item.trading.Merchant.openTradingScreen(Merchant.java:41) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.startTrading(Villager.java:351) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobInteract(Villager.java:329) ~[?:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1331) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1129) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2876) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2896) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2837) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([513...30])
        at net.minecraft.util.GsonHelper.convertToString(GsonHelper.java:94) ~[?:?]
        at net.minecraft.util.GsonHelper.getAsString(GsonHelper.java:100) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$EntityTooltipInfo.create(HoverEvent.java:177) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$Action.deserialize(HoverEvent.java:136) ~[?:?]
        at net.minecraft.network.chat.HoverEvent.deserialize(HoverEvent.java:80) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.getHoverEvent(Style.java:405) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:377) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:364) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:361) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:222) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:536) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[LoneLibs.jar:?]
        ... 44 more
[22:54:37 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutOpenWindow@2860b4db[
    a=15
    b=net.minecraft.world.inventory.Containers@f3a833c
    c=empty[style={hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@572d0b7c'},insertion=1e962e27-77d7-498d-bfbe-ad9720153306}, siblings=[literal{x4 }[style={color=gold,bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Villager}[style={color=white,!bold,!italic}]]]
  ]
```

**Comment by LoneDev6** [comment]
Update to 1.20.2, no reason to stay on 1.20.1.
