### ISSUE TITLE
java.lang.IllegalArgumentException: Max damage should be positive

### ISSUE THREAD

**Issue by DexterSK** [PluginBugs/Issues-ItemsAdder#3690]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Checked all values of "attackDamage", "arrow_damage", "damage" also replaced damages with 0 to 0.1 but still can't load the plugin, what is max damage? maybe you can add file name to the error message?

### Steps to reproduce the issue

start the server

### Server version

1.20.6-2223-224e7c7 (MC: 1.20.6)*

### ItemsAdder Version

ItemsAdder_4.0.1-alpha-test-2

### ProtocolLib Version

5.3.0-SNAPSHOT-698

### LoneLibs Version

 1.0.54

### Error (optional)

```shell
[00:45:55] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[00:45:55] [Server thread/WARN]: java.lang.IllegalArgumentException: Max damage should be positive
[00:45:55] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[00:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setMaxDamage(CraftMetaItem.java:1529)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.ml.c(SourceFile:385)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.eL.setMaxDurability(SourceFile:48)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.eL.<init>(SourceFile:35)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.fi.hG(SourceFile:190)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.b(SourceFile:769)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.c(SourceFile:625)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.mz.d(SourceFile:110)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.a(SourceFile:619)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.<init>(SourceFile:274)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.a(SourceFile:294)
[00:45:55] [Server thread/WARN]: 	at ItemsAdder_4.0.1-alpha-test-2.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:397)
[00:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[00:45:55] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[00:45:55] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[00:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[00:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618)
[00:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567)
[00:45:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678)
[00:45:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[00:45:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357)
[00:45:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150)
[00:45:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[00:45:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Andre601** [comment]
Please share your full server log through https://mclo.gs

**Comment by DexterSK** [comment]
https://mclo.gs/hGG5fWi

**Comment by DexterSK** [comment]
The issue is in iaalchemy and iawearables addons

**Comment by DexterSK** [comment]
also there is no GRASS material in 1.20.6, its instead SHORT_GRASS i think, you should add it

`[14:46:49 ERROR]: [ItemsAdder] Error reading vanilla model for material SHORT_GRASS, skip: java.io.IOException: OriginalAsset: No vanilla model file: 'templates/vanilla_items/short_grass.json'
[14:46:49 ERROR]: [ItemsAdder] Choose another material, SHORT_GRASS is not supported for these items: blockus:dirt_path1, blockus:dirt_path2, blockus:dirt_path3, blockus:dirt_path4, blockus:dirt_path5, blockus:dirt_path6...and more

[14:47:53 ERROR]: [ItemsAdder] Failed to process item file: short_grass
[14:47:53 WARN]: java.lang.NullPointerException: Cannot invoke "lonelibs.com.alibaba.fastjson2.JSONObject.getJSONArray(String)" because "<parameter1>" is null
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.lz.c(SourceFile:313)
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.lz.d(SourceFile:341)
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.li.nh(SourceFile:996)
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.a(SourceFile:1191)
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.ii.a(SourceFile:84)
[14:47:53 WARN]:        at ItemsAdder_4.0.1-alpha-test-2.jar//ia.m.G.a(SourceFile:957)
[14:47:53 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[14:47:53 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:47:53 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:47:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[14:47:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:47:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
`

**Comment by Andre601** [comment]
> The issue is in iaalchemy and iawearables addons

If that is actually caused by the addons, then this isn't really an IA issue?

**Comment by DexterSK** [comment]
Also can't load font images

```
[19:19:00 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'minecraft:guis/pixel.png' doesn't exists. File: contents/minecraft/assets/minecraft/font/default.json
[19:19:00 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'minecraft:guis/space_split.png' doesn't exists. File: contents/minecraft/assets/minecraft/font/default.json
[19:19:00 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'minecraft:guis/space_split.png' doesn't exists. File: contents/minecraft/assets/minecraft/font/default.json
[19:19:00 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'minecraft:guis/space_split.png' doesn't exists. File: contents/minecraft/assets/minecraft/font/default.json
```

and can't laod resourcepack
```
[19:19:30 INFO]: [Cardinal] DexterSK URL: http://localhost:41050/generated.zip Hash: 6f477bfa6f6d461ea21aff4c70ec55b885500c24
[19:19:30 INFO]: [Cardinal] Player DexterSK has accepted resourcepack. Status: 'ACCEPTED'
[19:19:30 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableList.set(ImmutableCollections.java:262) ~[?:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jl.a(SourceFile:299) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.iM.onPacketSending(SourceFile:66) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:489) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.network.Connection.send(Connection.java:449) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:345) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:326) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcastAndSend(ChunkMap.java:1394) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jI.a(SourceFile:149) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jI.b(SourceFile:39) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jl.c(SourceFile:312) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.iL.aP(SourceFile:105) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.lo.nl(SourceFile:54) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.ln.bx(SourceFile:91) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.lf.a(SourceFile:252) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1012.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2223-224e7c7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:251) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[19:19:30 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket@79926a9[
    id=782
    packedItems=[DataValue[id=0, serializer=net.minecraft.network.syncher.EntityDataSerializer$$Lambda/0x0000015d947ed1f0@20bec64b, value=32]]
  ]

[19:19:30 INFO]: [Cardinal] Player DexterSK (contains) -> replacing resourcepack status to: 'DOWNLOADED'
[19:19:44 INFO]: [Cardinal] Player DexterSK (contains) -> replacing resourcepack status to: 'FAILED_RELOAD'
```

**Comment by DexterSK** [comment]
Also found that mobs.enabled always turns to false when reloading plugin/restarting server even if its set to true its overwriten

**Comment by LoneDev6** [comment]
Do not report multiple issues on the same issue page.
Duplicate of #3694

> Also can't load font images

I separated this issue into another page. #3701
Further invalid issue reports will be closed.


> also there is no GRASS material in 1.20.6, its instead SHORT_GRASS i think, you should add it

I separated this issue into another page. #3702
Further invalid issue reports will be closed.

> Also found that mobs.enabled always turns to false when reloading plugin/restarting server even if its set to true its overwriten

I separated this issue into another page. #3702
Further invalid issue reports will be closed.

**Comment by DexterSK** [comment]
> Do not report multiple issues on the same issue page.

thanks, but its annoying to write plugins versions X times
