### ISSUE TITLE
Plugin is still loading... Please wait before using /iatexture

### ISSUE THREAD

**Issue by DextralityNetwork** [PluginBugs/Issues-ItemsAdder#3698]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I can't use comanod /iatexture because it says that the plugin is reloading and it stays like this.

### Steps to reproduce the issue

Put the latest version of the plugin (not 4.0.0) the previous one.
start the server
see the error

### Server version

https://prnt.sc/mJa9GPX2mC3N

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/8229d69c-3e56-4aad-bc44-c4f25a47b150)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/63fea9b4-bcef-415c-b945-0769e6fb1188)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/479dd757-6115-42ba-8c54-9aa10773cf39)

### Full server log

https://paste.helpch.at/igipeduvuv.makefile

**Comment by DextralityNetwork** [comment]
the first problem its about online mode: false so its not the problem

**Comment by DextralityNetwork** [comment]
Itemsadder has not been working since I updated it, just today.

**Comment by Andre601** [comment]
> the first problem its about online mode: false so its not the problem

I highly doubt that. I have seen countless servers running in offline mode and non ever displayed the error your logs show at the very start, so this cannot be related to it at all.

**Comment by DextralityNetwork** [comment]
U can see in this github: https://github.com/AlexProgrammerDE/balena-minecraft-server/issues/32

**Comment by DextralityNetwork** [comment]
my problem was with itemsadder :( new version

**Comment by LoneDev6** [comment]
This is the error I see in your log

```
[18:59:22] [Craft Scheduler Thread - 12 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.4-release-3 generated an exception while executing task 253
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.isBlock()" because "<parameter1>" is null
	at ia.m.rm.g(SourceFile:996) ~[ItemsAdder_3.6.4-release-3.jar:?]
	at ia.m.iO.cb(SourceFile:238) ~[ItemsAdder_3.6.4-release-3.jar:?]
	at ia.m.iO.<init>(SourceFile:64) ~[ItemsAdder_3.6.4-release-3.jar:?]
	at ia.m.iK.<init>(SourceFile:95) ~[ItemsAdder_3.6.4-release-3.jar:?]
	at ia.m.G.a(SourceFile:914) ~[ItemsAdder_3.6.4-release-3.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```


You probably have a misconfigured ItemsAdder loot for a vanilla block that doesn't exists.
Check the loots that you recently added.

The error about the port is something that is probably related to your hosting, to your java installation or some other stuff.
Try to reinstall the server on a different machine or ask the hosting service about that.
