### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Mathildeuh** [PluginBugs/Issues-ItemsAdder#3699]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Mathildeuh

### What happened?

After /iazip

[21:19:32 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.set(ImmutableCollections.java:262) ~[?:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jl.a(SourceFile:299) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.iM.onPacketSending(SourceFile:66) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:489) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.network.Connection.send(Connection.java:449) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:345) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:326) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcastAndSend(ChunkMap.java:1394) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jI.a(SourceFile:149) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jI.b(SourceFile:39) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.jl.c(SourceFile:312) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.iL.aP(SourceFile:105) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.lo.nl(SourceFile:54) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.ln.bx(SourceFile:91) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at ItemsAdder_4.0.1-alpha-test-2.jar/ia.m.lf.a(SourceFile:252) ~[ItemsAdder_4.0.1-alpha-test-2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor403.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2226-86ad0b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:251) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:19:32 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket@32fe5c68[
    id=265
    packedItems=[DataValue[id=0, serializer=net.minecraft.network.syncher.EntityDataSerializer$$Lambda/0x00007feff88081f8@7ddc05a3, value=32]]
  ]

### Steps to reproduce the issue

/iazip

### Server version

Purpur build 2226

### ItemsAdder Version

4.0.1

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.54

**Comment by Andre601** [comment]
Duplicate of #3694 

Please check the issues next time, thank you.
