### ISSUE TITLE
Can't load RP on 1.20.6

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#3706]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

supersintiendo64

### What happened?

The resourcepack failed loading

### Steps to reproduce the issue

just load the server on 1.20.6 with 1.20.6 itemsadder builds

### Server version

This server is running Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-497 (MC: 1.20.4)

### ItemsAdder Version

4.0.1-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-709

### LoneLibs Version

1.0.54

### Error (optional)

```shell
<html>
<body>
<!--StartFragment-->
[13:01:17] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
--
73 | java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
74 | at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
75 | at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
76 | at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
77 | at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
78 | at auv.a(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
79 | at bpm.d(SourceFile:162) ~[minecraft-1.20.6-client.jar:?]
80 | at bpq.d(SourceFile:23) ~[minecraft-1.20.6-client.jar:?]
81 | at bpm.A(SourceFile:136) ~[minecraft-1.20.6-client.jar:?]
82 | at bpm.bA(SourceFile:121) ~[minecraft-1.20.6-client.jar:?]
83 | at ffh.c(SourceFile:1275) [minecraft-1.20.6-client.jar:?]
84 | at ffh.f(SourceFile:888) [minecraft-1.20.6-client.jar:?]
85 | at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.20.6-client.jar:?]
86 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
87 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
88 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
89 | Caused by: java.lang.RuntimeException: could not reload shaders
90 | at gdj.c(SourceFile:543) [minecraft-1.20.6-client.jar:?]
91 | at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
92 | at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
93 | at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
94 | at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
95 | ... 12 more
96 | Caused by: ali: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (server/00000000/d69238f2-b7ce-30b0-8262-17cd9490f29d, rendertype_text) : 0(36) : error C1102: incompatible type for parameter #1 ("pos.12")
97 | 0(36) : error C7623: implicit narrowing of type from "vec3" to "int"
98 | 0(36) : error C1104: too many parameters in function call
99 | at ali.a(SourceFile:48) ~[minecraft-1.20.6-client.jar:?]
100 | at gee.<init>(SourceFile:176) ~[minecraft-1.20.6-client.jar:?]
101 | at gdj.c(SourceFile:522) ~[minecraft-1.20.6-client.jar:?]
102 | at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
103 | at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
104 | at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
105 | at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
106 | ... 12 more
107 | Caused by: java.io.IOException: Couldn't compile vertex program (server/00000000/d69238f2-b7ce-30b0-8262-17cd9490f29d, rendertype_text) : 0(36) : error C1102: incompatible type for parameter #1 ("pos.12")
108 | 0(36) : error C7623: implicit narrowing of type from "vec3" to "int"
109 | 0(36) : error C1104: too many parameters in function call
110 | at ezo.b(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
111 | at ezo.a(SourceFile:51) ~[minecraft-1.20.6-client.jar:?]
112 | at gee.a(SourceFile:214) ~[minecraft-1.20.6-client.jar:?]
113 | at gee.<init>(SourceFile:161) ~[minecraft-1.20.6-client.jar:?]
114 | at gdj.c(SourceFile:522) ~[minecraft-1.20.6-client.jar:?]
115 | at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
116 | at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
117 | at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
118 | at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
119 | ... 12 more

<!--EndFragment-->
</body>
</html>[13:01:17] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at auv.a(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
	at bpm.d(SourceFile:162) ~[minecraft-1.20.6-client.jar:?]
	at bpq.d(SourceFile:23) ~[minecraft-1.20.6-client.jar:?]
	at bpm.A(SourceFile:136) ~[minecraft-1.20.6-client.jar:?]
	at bpm.bA(SourceFile:121) ~[minecraft-1.20.6-client.jar:?]
	at ffh.c(SourceFile:12[75](https://mclo.gs/FV9u4vc#L75)) [minecraft-1.20.6-client.jar:?]
	at ffh.f(SourceFile:888) [minecraft-1.20.6-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.20.6-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at gdj.c(SourceFile:543) [minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: ali: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (server/00000000/d69238f2-b7ce-30b0-8262-17cd9490f29d, rendertype_text) : 0(36) : error C1102: incompatible type for parameter #1 ("pos.12")
0(36) : error C[76](https://mclo.gs/FV9u4vc#L76)23: implicit narrowing of type from "vec3" to "int"
0(36) : error C1104: too many parameters in function call
	at ali.a(SourceFile:48) ~[minecraft-1.20.6-client.jar:?]
	at gee.<init>(SourceFile:176) ~[minecraft-1.20.6-client.jar:?]
	at gdj.c(SourceFile:522) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Couldn't compile vertex program (server/00000000/d69238f2-b7ce-30b0-[82](https://mclo.gs/FV9u4vc#L82)62-17cd9490f29d, rendertype_text) : 0(36) : error C1102: incompatible type for parameter #1 ("pos.12")
0(36) : error C7623: implicit narrowing of type from "vec3" to "int"
0(36) : error C1104: too many parameters in function call
	at ezo.b(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
	at ezo.a(SourceFile:51) ~[minecraft-1.20.6-client.jar:?]
	at gee.a(SourceFile:214) ~[minecraft-1.20.6-client.jar:?]
	at gee.<init>(SourceFile:161) ~[minecraft-1.20.6-client.jar:?]
	at gdj.c(SourceFile:522) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
```

**Comment by Andre601** [comment]
The error you sent is not an error from the server, but your client.

Please provide your **Server Logs** and **Server Error** (if any). Client-side logs and errors tell us nothing about any possible issue here.

**Comment by matipoirierg** [comment]
https://mclo.gs/OqHIFrv

**Comment by Andre601** [comment]
You seem to have some invalid file and folder names in your content...

To quote from LoneDev in #3700:
> Anyway the "invalid namespace" errors can be ignored as they don't make your pack fail to generate or download. **They seem to be related to the fact that you have some MacOS files in your resourcepack.**

For further help, please share your complete server log and not just a part of it, as it gives us important info to work with.

**Comment by matipoirierg** [comment]
fixed the issue I had a folder called minecraft inside my contents, deleted that and rp is loading fine now.
