### ISSUE TITLE
API Error.

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#3707]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

asleepp

### What happened?

I own a plugin named skript-itemsadder, where I add more compatiability with Skript and ItemsAdder, someone recently dmed me on discord about a stack trace they see when they try to use my plugin's `replace custom furniture` effect.

This is their code.
```
on place success of custom furniture "crafting_stations:forge_station":
    wait 2 seconds
    replace custom furniture "crafting_stations:jewelcrafting_station" at event-location
```

Once this executes, the script completely freezes, like nothing after the effect gets executed (could be my fault), and the stack trace in the Error part gets sent to the console. To me, this looks like a weird bug with the teleport method with CustomFurniture.

If you would like to get a look at the code for this effect, go [here](https://github.com/Asleeepp/skript-itemsadder/blob/master/src/main/java/me/asleepp/SkriptItemsAdder/elements/effects/EffReplaceCustomFurniture.java), as im still not 100% sure that this is my fault.

Note that all the version stuff is the person who reported it to me's server, not my own. So take this stuff with a grain of salt as I haven't had the time to test it personally yet.

### Steps to reproduce the issue

1) install Skript, ItemsAdder, Dependencies, and skript-itemsadder
2) use the `replace custom furniture` effect
3) stack trace

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119438940/6935d039-f08e-4894-bb96-719edd336362)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119438940/ea6b00f3-4437-4e0b-bb6f-4e8a534f3155)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119438940/cbbea7e4-9509-4928-94c7-8a66c8cc9df6)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119438940/106d4a26-bec9-49c9-b866-ec3f71fd6f7b)

### Error (optional)

```shell
[15:41:28 ERROR]: #!#! [Skript] Severe Error:
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[15:41:28 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[15:41:28 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Stack trace:
[15:41:28 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ia.m.bu.Y()" because "this.behaviour" is null
[15:41:28 ERROR]: #!#!     at ItemsAdder_3.6.3-beta-7.jar//dev.lone.itemsadder.api.CustomFurniture.teleport(SourceFile:155)
[15:41:28 ERROR]: #!#!     at skript-itemsadder-1.5.jar//me.asleepp.SkriptItemsAdder.elements.effects.EffReplaceCustomFurniture.execute(EffReplaceCustomFurniture.java:42)
[15:41:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[15:41:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:41:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:41:28 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[15:41:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:41:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:41:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[15:41:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[15:41:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[15:41:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[15:41:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[15:41:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Version Information:
[15:41:28 ERROR]: #!#!   Skript: 2.8.4 (OUTDATED)
[15:41:28 ERROR]: #!#!     Flavor: skriptlang-github
[15:41:28 ERROR]: #!#!     Date: 11:03:52.948789700
[15:41:28 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[15:41:28 ERROR]: #!#!   Minecraft: 1.19.4
[15:41:28 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[15:41:28 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Server platform: Paper
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Current node: null
[15:41:28 ERROR]: #!#! Current item: replace (custom|ia|itemsadder) furniture "crafting_stations:jewelcrafting_station" at the location
[15:41:28 ERROR]: #!#! Current trigger: place success of custom furniture "crafting_stations:forge_station" (FurniturePlaceSuccess event with id [[string:"crafting_stations:forge_station"]]) (test\test.sk, line 1)
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Thread: Server thread
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! Language: english
[15:41:28 ERROR]: #!#! Link parse mode: DISABLED
[15:41:28 ERROR]: #!#!
[15:41:28 ERROR]: #!#! End of Error.
[15:41:28 ERROR]: #!#!
```

**Comment by Andre601** [comment]
Your user is using a VERY outdated version of ItemsAdder. The latest version that still should support 1.19.4 is 3.6.4-release-3, so please tell them to update IA and any required dependencies.

Also, regarding your skript implementation, I can only assume things here, but maybe it would be good to check for null in the retrieved armor stand entity to make sure it really is there.
