### ISSUE TITLE
PlayerInteractEvent Error

### ISSUE THREAD

**Issue by TechGe3ks** [PluginBugs/Issues-ItemsAdder#3737]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When a player clicks there is an error that is thrown on the console.

It is from the PlayerInteractEvent being unable to be passed to ItemsAdder. Further on, this only happens if you are using the newer versions of protocollib

### Steps to reproduce the issue

On the most recent version release version(not alpha Test), on 1.20.4 server version, and use the latest Protocollib version

### Server version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-493 (MC: 1.20.4)

### ItemsAdder Version

[23:13:11 INFO]: ItemsAdder version 3.6.4-release-3
[23:13:11 INFO]: Customized Minecraft without client mods!
[23:13:11 INFO]: Website: devs.beer
[23:13:11 INFO]: Author: LoneDev

### ProtocolLib Version

[23:13:26 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-720
[23:13:26 INFO]: Provides read/write access to the Minecraft protocol.
[23:13:26 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:13:43 INFO]: LoneLibs version 1.0.54
[23:13:43 INFO]: Collection of libs used by my plugins
[23:13:43 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[23:08:56 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.6.4-release-3
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
        at ia.m.mW.a(SourceFile:267) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.cI.w(SourceFile:293) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.cK.a(SourceFile:195) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.cK.a(SourceFile:333) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:541) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2509) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
```

**Comment by LoneDev6** [comment]
> Further on, this only happens if you are using the newer versions of protocollib

If you're on 1.20.4 just use ProtocoLib 5.2.0, as said in the official repository, you're using an incompatible version.
https://ci.dmulloy2.net/job/ProtocolLib/

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/ba722d6c-91b2-4010-9038-e7f319222136)
