### ISSUE TITLE
The issuance of items in the self-written plugin does not work

### ISSUE THREAD

**Issue by Taks1k** [PluginBugs/Issues-ItemsAdder#3746]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The issuance of items in the self-written plugin does not work
I specify ctools:steel_ingot, but the item is not issued
writes that itemstack is null

### Steps to reproduce the issue

-

### Server version

1.19.4

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-14

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Full server log

[18:14:45] [Server thread/INFO]: [TownyIndustry] Enabling TownyIndustry v1.0.0
[18:14:45] [Server thread/INFO]: ctools:steel_ingot
[18:14:45] [Server thread/ERROR]: Error occurred while enabling TownyIndustry v1.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.api.CustomStack.getItemStack()" because "stack" is null
at me.axorom.townyindustry.structure.Level.<init>(Level.java:131) ~[TownyIndustry-1.0.0 (2).jar:?]
at me.axorom.townyindustry.structure.Building.<init>(Building.java:24) ~[TownyIndustry-1.0.0 (2).jar:?]
at me.axorom.townyindustry.structure.Category.<init>(Category.java:54) ~[TownyIndustry-1.0.0 (2).jar:?]
at me.axorom.townyindustry.utils.Config.<init>(Config.java:30) ~[TownyIndustry-1.0.0 (2).jar:?]
at me.axorom.townyindustry.TownyIndustry.onEnable(TownyIndustry.java:61) ~[TownyIndustry-1.0.0 (2).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[18:14:45] [Server thread/INFO]: [TownyIndustry] Disabling TownyIndustry v1.0.0
[18:14:45] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling TownyIndustry v1.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.axorom.townyindustry.utils.FileDatabase.save()" because "this.townData" is null
at me.axorom.townyindustry.TownyIndustry.onDisable(TownyIndustry.java:154) ~[TownyIndustry-1.0.0 (2).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### Error (optional)

```shell
Cannot invoke "dev.lone.itemsadder.api.CustomStack.getItemStack()" because "stack" is null
```

### Other files, you can drag and drop them here to upload. (optional)

        ConfigurationSection priceItems = levelSection.getConfigurationSection("item-price");
        if (priceItems != null) {
            for (String key : priceItems.getKeys(false)) {
                boolean mmo = priceItems.getBoolean(key + ".mmoitems", false);
                boolean adder = priceItems.getBoolean(key + ".itemsadder", false);
                ItemStack item;
                if (mmo) {
                    item = Objects.requireNonNull(MMOItems.plugin.getItem(priceItems.getString(key + ".FOOD"), priceItems.getString(key + ".id"))).clone();
                } else if (adder) {
                    Bukkit.getLogger().info(priceItems.getString(key + ".id"));
                    CustomStack stack = CustomStack.getInstance(priceItems.getString(key + ".id"));
                    item = stack.getItemStack();
                } else {
                    Material mat = Material.matchMaterial(priceItems.getString(key + ".id", "stone"));
                    if (mat == null)
                        throw new NullPointerException("Invalid material: " + priceItems.getString(key + ".id", "stone"));
                    if (priceItems.getInt(key + ".count") < 0) {
                        negativeItems.add(true);
                    } else {
                        negativeItems.add(false);
                    }
                    item = new ItemStack(mat, Math.abs(priceItems.getInt(key + ".count")));
                }
                ItemMeta meta = item.getItemMeta();
                if (meta == null) continue;

**Comment by Andre601** [comment]
Please provide the **full** server log throgh https://mclo.gs

**Comment by Taks1k** [comment]
https://mclo.gs/nLouSs3

**Comment by Andre601** [comment]
You use an outdated version of IA. Please update to the latest 3.6.4 version.

**Comment by Taks1k** [comment]
updated

**Comment by LoneDev6** [comment]
"Cannot invoke "dev.lone.itemsadder.api.CustomStack.getItemStack()" because "stack" is null"

Means that the plugin can't find the stack for that id.
This happens if you call this code when the items are not loaded yet or if the item doesn't exists.
Listen to ItemsAdderLoadDataEvent.

**Comment by Taks1k** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/156545563/77200a04-21df-4264-86d6-11558d4e2ca2)

**Comment by Taks1k** [comment]
I wrote it that way, same error

**Comment by Taks1k** [comment]
Items are not loading, there is no message that I registered

**Comment by Andre601** [comment]
Is the code of your plugin available on GitHub to look into?
Also, just sharing a screenshot does not give us any clues on wether you actually make sure your stuff is only loaded when IA is loaded, or not...

**Comment by Taks1k** [comment]
the event is called if this item is removed from the config

**Comment by Taks1k** [comment]
and my plugin is loading before the items are loaded
