### ISSUE TITLE
Invalid generated pack description

### ISSUE THREAD

**Issue by vortexthedev** [PluginBugs/Issues-ItemsAdder#3749]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

vortex2252

### What happened?

When I download the pack I'm getting kicked out of the server. The server logs doesn't contain any errors.
Client log error:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/72511773/926c6099-8046-4ef4-ba4b-0c41b4fc44ad)

### Steps to reproduce the issue

1. Generate resourcepack using /ia zip
2. Upload the generated.zip to Dropbox
3. Change the url in the host section
4. Join server and Accept resourcepack download
5. Get kicked out from the server

### Server version

Current: git-Purpur-"79a65ee" (MC: 1.20.2)*
Previous: 1.20.6-DEV-67512c4 (MC: 1.20.6)
* Error obtaining version information

### ItemsAdder Version

ItemsAdder_3.6.3-beta-14

### ProtocolLib Version

5.1.2

### LoneLibs Version

1.0.54

### Full server log

[16:01:36] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.9.2
[16:01:36] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.2 (764)
[16:01:36] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.6
[16:01:36] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[16:01:36] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.33-SNAPSHOT (build 3219)
[16:01:36] [Server thread/INFO]: [Citizens] Loading external libraries
[16:01:44] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-9
[16:01:44] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Minecraft: v1_20_R2! Trying to find NMS support
[16:01:44] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[16:01:44] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'LoneLibs' to create a bStats instance!
[16:01:45] [Server thread/INFO]: [MC] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-9
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.54
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-"79a65ee" (MC: 1.20.2)
                                               
[16:01:45] [Server thread/INFO]: [MC] Registered Citizens NPC Trait: customentity
[16:01:47] [Server thread/INFO]: [MC] [Pack] Extracting internal contents from .jar
[16:01:47] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [MC]  
[16:01:47] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [MC] UPDATE available: https://www.spigotmc.org/resources/73355/
[16:01:47] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [MC] Current version: 3.6.3-beta-9 | Online version: 4.0.1-alpha-test-4
[16:01:47] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [MC]  
[16:01:47] [Craft Scheduler Thread - 4 - ItemsAdder/INFO]: [MC] [License] Spigot product licensed to: zVortexGG (819056)
[16:01:47] [Server thread/INFO]: [MC] [Pack] DONE extracting internal contents from .jar
[16:01:49] [Server thread/INFO]: [Citizens] Loaded 6 NPCs.
[16:01:49] [Server thread/WARN]: [ViaVersion] There is a newer plugin version available: 5.0.0, you're on: 4.9.2
[16:01:49] [Server thread/INFO]: Done (32.304s)! For help, type "help"
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Loaded 711 items
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 0/188 REAL block IDs
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 0/750 REAL_NOTE block IDs
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 0/63 REAL_TRANSPARENT block IDs
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 0/127 REAL_WIRE block IDs
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 0/14 FIRE block IDs
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] Used 780/6608 font_images
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] [Init] Loaded 1 categories
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] [Init] Loaded successfully.
[16:01:50] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] [Pack] Checking resourcepack url... 
[16:01:50] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[16:01:50] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[16:01:50] [Server thread/INFO]: [MC] Reloading ItemsAdder Custom Entities Citizens NPCs...
[16:01:50] [Server thread/INFO]: [MC] Reloaded 0 ItemsAdder Custom Entities Citizens NPCs.
[16:01:52] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [MC] [Pack] Resourcepack URL is valid (external-host). Url: https://www.dropbox.com/scl/fi/2f72h6s9mr655g12dvtid/generated.zip?rlkey=itw3edujd4uy0jc9n3uxsenx7&st=gooz2vlhaw=1

### Error (optional)

```shell
[17:10:57] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at arn.a(SourceFile:529) ~[1.20.2.jar:?]
	at arn.b(SourceFile:534) ~[1.20.2.jar:?]
	at arn.a(SourceFile:596) ~[1.20.2.jar:?]
	at arn.a(SourceFile:604) ~[1.20.2.jar:?]
	at amb.a(SourceFile:43) ~[1.20.2.jar:?]
	at amb.a(SourceFile:35) ~[1.20.2.jar:?]
	at anb.a(SourceFile:69) ~[1.20.2.jar:?]
	at anb.a(SourceFile:47) ~[1.20.2.jar:?]
	at ana.a(SourceFile:55) ~[1.20.2.jar:?]
	at ana.a(SourceFile:76) ~[1.20.2.jar:?]
	at ana.a(SourceFile:50) ~[1.20.2.jar:?]
	at ane.h(SourceFile:39) ~[1.20.2.jar:?]
	at ane.a(SourceFile:32) ~[1.20.2.jar:?]
	at eqv.a(SourceFile:998) ~[1.20.2.jar:?]
	at eqv.k(SourceFile:982) ~[1.20.2.jar:?]
	at eqv.d(SourceFile:1219) ~[1.20.2.jar:?]
	at eqv.f(SourceFile:856) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:253) ~[1.20.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136) ~[tl_skin_cape_1.20.2-1.33.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:31) ~[tl_skin_cape_1.20.2-1.33.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1650) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1027) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.1.jar:?]
	at arn.a(SourceFile:527) ~[1.20.2.jar:?]
	... 23 more
```

**Comment by Andre601** [comment]
Also, be honest with your information and don't try to mislead us. You report using 3.6.3-beta-14, but the logs you share show you using 3.6.3-beta-9.

**Comment by vortexthedev** [comment]
It doesn't change anything, I tried all last versions that supports 1.20.2 and nothing changed

**Comment by Andre601** [comment]
Then update to 1.20.4. There isn't any real reason to stick with 1.20.2.

**Comment by vortexthedev** [comment]
This issue is literally not even related to the version

**Comment by vortexthedev** [comment]
I tried to join all 1.20+ client versions on that 1.20.2 Purpur, the error is still the same.
ItemsAdder is generating malformed pack.mcmeta

**Comment by LoneDev6** [comment]
Make sure you don't have a pack.mcmeta file inside your various folders which might overwrite the ItemsAdder generated one.
I don't see how ItemsAdder can generate an invalid resourcepack pack.mcmeta file as it generates is using the JSON library.
