### ISSUE TITLE
getLoot() function not work

### ISSUE THREAD

**Issue by NewZAZ** [PluginBugs/Issues-ItemsAdder#3752]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

newz_az

### What happened?

getLoot cause error : 

code : 
```
        CustomBlock customBlock = CustomBlock.byAlreadyPlaced(block);
        if (customBlock != null) {
            customBlock.getLoot().forEach(item -> {
                RItemDropEvent rItemDropEvent = new RItemDropEvent(player, block.getLocation());
                rItemDropEvent.addDrop(item);
                Utils.callEvent(rItemDropEvent);
            });
            customBlock.remove();
        }
```

### Steps to reproduce the issue

.

### Server version

Current: git-Purpur-2172 (MC: 1.20.4)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Error (optional)

```shell
[19:39:27 ERROR]: Could not pass event BlockBreakEvent to RemainsItems v1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<parameter1>" is null
        at ia.m.eJ.d(SourceFile:440) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getLoot(SourceFile:286) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getLoot(SourceFile:266) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getLoot(SourceFile:261) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at fr.remainsky.items.engine.items.farming.HammerItem.checkBlock(HammerItem.java:230) ~[RemainsItems-1.0.jar:?]
        at fr.remainsky.items.engine.items.farming.HammerItem.onBreak(HammerItem.java:167) ~[RemainsItems-1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor701.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2172]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1917) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2172]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Please share your full server logs, as requested, through https://mclo.gs

**Comment by NewZAZ** [comment]
Don't need full server logs

**Comment by Andre601** [comment]
That's what you're saying. We do need them.

**Comment by LoneDev6** [comment]
The block probably was removed from the itemsadder configurations but is still in the world, so you can't get loot for a block that was removed from configurations.
