### ISSUE TITLE
Please add compatibility with Itemsadder v3.6.4 to latest 5.3.0 Protocollib versions

### ISSUE THREAD

**Issue by SimonMage** [PluginBugs/Issues-ItemsAdder#3754]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

simonmage

### What happened?

I know that you dropped support, but before dropping definitely this version, please consider to update the compatibility with latest 5.3.0 protocollib versions.

Perfavore puoi aggiornare alle ultime versioni di protocollib, sto usando la 1.20.2 e sono scostretto a rimanerci perché ho un server Pixelmon in 1.20.2 e non posso aggiornare volendo perché non ci sono versioni pixelmon per quella versione.

### Steps to reproduce the issue

Startup the server, plugin disabled

### Server version

1.20.2

### ItemsAdder Version

v3.6.4 - release 3

### ProtocolLib Version

5.3.0 build 716

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/E8SFHfG

### Error (optional)

```shell
[13:43:39] [Server thread/INFO] [dev.lone.itemsadder.Main]: [ItemsAdder] Enabling ItemsAdder v3.6.4-release-3
[13:43:47] [Server thread/INFO] [Minecraft]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.4-release-3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.54
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Mohist 1.20.2-159 (MC: 1.20.2)
                                               
[13:43:47] [Server thread/INFO] [Minecraft]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[13:43:47] [Server thread/INFO] [Minecraft]: [ItemsAdder] [Host] Starting self-host webserver on port: 8046
[13:43:47] [Server thread/WARN] [com.comphenix.protocol.ProtocolLib]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Plugin %s tried to register listener for unknown packet %s [direction: from %s]
[13:43:47] [Server thread/WARN] [Minecraft]: [ProtocolLib] [OutboundPacketListenerSet] Plugin ItemsAdder tried to register listener for unknown packet ADD_RESOURCE_PACK[CONFIGURATION, SERVER, 9, classNames: [net.minecraft.network.protocol.configuration.PacketConfigurationOutResourcePackPush, net.minecraft.network.protocol.configuration.ClientboundResourcePackPushPacket, PacketConfigurationOutResourcePackPush, ClientboundResourcePackPushPacket, ResourcePackPush] (unregistered)] [direction: from SERVER]
[13:43:47] [Server thread/ERROR] [Minecraft]: Error occurred while enabling ItemsAdder v3.6.4-release-3 (Is it up to date?)
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.addListener(PacketListenerSet.java:48) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:327) ~[?:?]
	at ia.m.ms.a(SourceFile:220) ~[?:?]
	at ia.m.qa.register(SourceFile:164) ~[?:?]
	at ia.m.qf.<init>(SourceFile:83) ~[?:?]
	at ia.m.G.a(SourceFile:515) ~[?:?]
	at ia.m.G.<init>(SourceFile:276) ~[?:?]
	at ia.m.G.a(SourceFile:295) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:418) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:346) ~[forge-1.20.2-48.1.0-universal.jar%23173!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.20.2-48.1.0-universal.jar%23173!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481) ~[forge-1.20.2-48.1.0-universal.jar%23173!/:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.2-48.1.0-universal.jar%23173!/:ef888c07-758046319-b60a8662-48.1.0]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.2-48.1.0-universal.jar%23173!/:ef888c07-758046319-b60a8662-48.1.0]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:434) ~[server-1.20.2-20230921.100330-srg.jar%23168!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:336) ~[server-1.20.2-20230921.100330-srg.jar%23168!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.2-20230921.100330-srg.jar%23168!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:849) ~[server-1.20.2-20230921.100330-srg.jar%23168!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23168!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:43:47] [Server thread/INFO] [dev.lone.itemsadder.Main]: [ItemsAdder] Disabling ItemsAdder v3.6.4-release-3
```

**Comment by Andre601** [comment]
Your issue is, that you are using a hybrid server. Please don't do that, as they break plugins left, right and center.

**Comment by SimonMage00** [comment]
I have the same issue in paper server, please don't read the first 3 lines and think before speaking please.

In fact with a old version of protocollib I have no issues

**Comment by Andre601** [comment]
> I have the same issue in paper server, please don't read the first 3 lines and think before speaking please.
> 
> In fact with a old version of protocollib I have no issues

I went with the info you gave, which was the fact that you used Mohist, as shown by this screenthot:
![grafik](https://github.com/PluginBugs/Issues-ItemsAdder/assets/11576465/5f70159f-cd01-4e7c-b350-4d9a4e56ac62)

Please do some proper reports.

**Comment by LoneDev6** [comment]
Protocollib 5.3.0 is not compatible with Minecraft 1.20.4 and lower.
https://ci.dmulloy2.net/job/ProtocolLib/
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/13e94515-4cc5-443b-bed1-8412dac64cd4)

**Comment by LoneDev6** [comment]
I don't see why you're not using ProtocolLib 5.2.0

**Comment by SimonMage** [comment]
> I don't see why you're not using ProtocolLib 5.2.0

Because some new plugin versions doesn't work with old versions of protocollib

**Comment by LoneDev6** [comment]
Report this issue to ProtocoLib devs.
I don't see why it should throw the `java.util.ConcurrentModificationException` exception.
This is my code:
```java
ProtocolLibrary.getProtocolManager().addPacketListener(listener);
```

I think it's an issue with some recent ProtocolLib changes.
