### ISSUE TITLE
Player death error

### ISSUE THREAD

**Issue by mcabacd** [PluginBugs/Issues-ItemsAdder#3756]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The console sends an error after the player dies

### Steps to reproduce the issue

The player dies
An error is reported in the console

### Server version

 This server is running Mohist version 1.16.5-1240 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.42)

### ItemsAdder Version

ItemsAdder_3.6.4

### ProtocolLib Version

ProtocolLib_5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs_1.0.54

### Full server log

[latest.log](https://github.com/user-attachments/files/15954283/latest.log)

### Error (optional)

```shell
[19:03:57 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([153...02])
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
        at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
        at ia.m.hH.a(SourceFile:26) ~[?:?]
        at ia.m.hF.h(SourceFile:141) ~[?:?]
        at ia.m.hA.d(SourceFile:234) ~[?:?]
        at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:208) ~[?:?]
        at net.minecraft.network.NetworkManager.func_201058_a(NetworkManager.java:180) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_211148_a(ServerPlayNetHandler.java:1574) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147359_a(ServerPlayNetHandler.java:1548) ~[?:?]
        at net.minecraft.server.management.PlayerList.func_148540_a(PlayerList.java:738) ~[?:?]
        at net.minecraft.server.management.PlayerList.func_232641_a_(PlayerList.java:1004) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:686) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:124) ~[forge:?]
        at com.Zrips.CMI.commands.list.kill.perform(kill.java:102) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:782) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1826) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1663) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:971) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:954) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:948) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:934) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:851) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([153...02])
        at net.minecraft.util.JSONUtils.func_151206_a(SourceFile:103) ~[?:?]
        at net.minecraft.util.JSONUtils.func_151200_h(SourceFile:109) ~[?:?]
        at net.minecraft.util.text.event.HoverEvent$EntityHover.func_240682_a_(HoverEvent.java:187) ~[?:?]
        at net.minecraft.util.text.event.HoverEvent$Action.func_240668_a_(HoverEvent.java:146) ~[?:?]
        at net.minecraft.util.text.event.HoverEvent.func_240661_a_(HoverEvent.java:84) ~[?:?]
        at net.minecraft.util.text.Style$Serializer.func_240734_b_(Style.java:331) ~[?:?]
        at net.minecraft.util.text.Style$Serializer.deserialize(Style.java:303) ~[?:?]
        at net.minecraft.util.text.Style$Serializer.deserialize(Style.java:287) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at net.minecraft.util.text.ITextComponent$Serializer.deserialize(ITextComponent.java:246) ~[?:?]
        at net.minecraft.util.text.ITextComponent$Serializer.deserialize(ITextComponent.java:191) ~[?:?]
        at net.minecraft.util.text.ITextComponent$Serializer.deserialize(ITextComponent.java:128) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at net.minecraft.util.text.ITextComponent$Serializer.func_240641_a_(ITextComponent.java:352) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
        ... 47 more
[19:03:57 ERROR]: Parameters:
  net.minecraft.network.play.server.SChatPacket@b68e181[
    field_148919_a=TranslatableComponent{key='death.attack.generic', args=[TextComponent{text='', siblings=[TextComponent{text='', siblings=[TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='ab_FreePalestine', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell ab_FreePalestine '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.util.text.event.HoverEvent$EntityHover@d86198be'}, insertion=ab_FreePalestine, font=minecraft:default}}], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    field_179842_b=SYSTEM
    field_240809_c_=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by Andre601** [comment]
Please use mclo.gs next time to share your latest.log, nobody likes to download a random file, just to check its content.
Your log file: https://mclo.gs/RGb2tTf

Towards your issue: You're running a hybrid server, which you shouldn't.
They constantly break compatability with plugins, such as ItemsAdder, which is why we also don't support such servers.
If you want to use ItemsAdder, use Spigot, Paper or Purpur and not a hybrid server.
