### ISSUE TITLE
[16:48:15 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-2

### ISSUE THREAD

**Issue by SadB000Y** [PluginBugs/Issues-ItemsAdder#3786]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sadb000y

### What happened?

I started adding texture packs according to the guide (Step 2 - Resourcepack first installation), namely uploaded to dropbox, added a link to the config. The server itself restarted and tried to go to it, then I have an inscription on the screen that the resourcepack is installed, I can not move, nothing happens.

Perhaps not correctly installed or did not understand what exactly is needed to install the package

Translated with DeepL.com (free version)

### Steps to reproduce the issue

1. Installed the plugin
2. Threw resourcepack custom on dropbox(https://samusdev.com/product/rpg-class-series-necromancer/).
3. Restarted the server
4. Go to the server

### Server version

[16:50:24 INFO]: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### ItemsAdder Version

[16:51:02 INFO]: ItemsAdder version 3.6.4-release-2 (As I understand it, this is the version needed for 1.20.4)

### ProtocolLib Version

[16:51:36 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-723

### LoneLibs Version

[16:51:55 INFO]: LoneLibs version 1.0.55

### Full server log

https://logs.hosting-minecraft.pro/jonesopota

### Error (optional)

```shell
[16:47:15 INFO]: [ItemsAdder] [Pack] ETag: 1720444967449323d
[16:47:16 INFO]: [ItemsAdder] [Pack] URL is valid (external). URL: https://www.dropbox.com/scl/fi/e075973qxt89wr9guem32/assets.zip?rlkey=sma2cabe1vupxpc8h5y60wlx7&st=9834tjgxaw=1
[16:47:23 INFO]: [Konquest] Konquest Database passed startup check.
Hosting-Minecraft: Правила firewall успешно добавлены на сервер.
[16:48:13 INFO]: UUID of player For4anY is 7c658242-d4e4-3436-9d4c-c3a432ddade0
[16:48:14 INFO]: For4anY[/178.215.72.6:28882] logged in with entity id 74 at ([world]-202.7802027865997, 70.0, 38.97528464801803)
[16:48:15 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-2
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
        at ia.m.mW.a(SourceFile:267) ~[ItemsAdder_3.6.4-release-2.jar:?]
        at ia.m.qi.at(SourceFile:189) ~[ItemsAdder_3.6.4-release-2.jar:?]
        at ia.m.qa.a(SourceFile:209) ~[ItemsAdder_3.6.4-release-2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor340.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:200) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Your ItemsAdder version is outdated. Latest for 1.20.4 is 3.6.4-release-3, which you can ger from here: https://www.spigotmc.org/resources/73355/update?update=546971

**Comment by SadB000Y** [comment]
After updating to the latest version, the error remains.

Also changed the way of texturepack storage to self (ports opened)

**Comment by DemarcoFC** [comment]
I am having the same issue. https://pastebin.com/FW9k43e1

**Comment by stanleyvandenbos** [comment]
I'm encountering the same error with release 3. Here is my error log, in case it provides some insights:
https://pastebin.com/Rsi1ACzG

**Comment by leoms1408** [comment]
I have the same error with 1.20. and ItemsAdder v3.6.4-release-3

```
[16:24:49 INFO]: UUID of player leoms1408 is 5b75900b-d18d-42f0-8438-69c38fbef440
[16:24:50 INFO]: leoms1408[/XX.XXX.XXX.XXX:55968] logged in with entity id 169 at ([world]605.6236751012127, 63.0, -265.19050831845703)
[16:24:50 INFO]: [+] leoms1408
[16:24:51 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-3
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
at ia.m.mW.a(SourceFile:267) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qi.at(SourceFile:189) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qa.a(SourceFile:209) ~[ItemsAdder_3.6.4-release-3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor388.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:219) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1549) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:24:51 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-3
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
at ia.m.mW.a(SourceFile:267) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qi.at(SourceFile:189) ~[ItemsAdder_3.6.4-release-3.jar:?]
at ia.m.qa.a(SourceFile:209) ~[ItemsAdder_3.6.4-release-3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor388.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:219) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by LoneDev6** [comment]
Disable player black screen in config.yml
```yml
  protect-player:
    black-screen: false
```

**Comment by SadB000Y** [comment]
This helps to prevent the player from standing forever with the loading waiting screen, but the error remains in the console

**Comment by LoneDev6** [comment]
Can you restart? The error shouldn't appear due to the fact that the option was disabled and that code won't execute anymore.

**Comment by SadB000Y** [comment]
If there have been no changes in the plugin and there are no new versions, then there are no changes. 

The server restarts every night and when the error crashes again, but by disabling the Black screen, the player, at least, can walk without a long wait.

I disabled this feature a long time ago and, accordingly, wrote to Git after I saw that the error did not leave the console
