### ISSUE TITLE
[18:35:56 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-3

### ISSUE THREAD

**Issue by SadB000Y** [PluginBugs/Issues-ItemsAdder#3787]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sadb000y

### What happened?

Installed the new version and started using self storage method (ports opened)

The error remained the same as in previous times

### Steps to reproduce the issue

1. Installed the plugin
2. Installed the default texturepack from the guide
3. Restarted the server
4. Go to the server

### Server version

[18:34:54 INFO]: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### ItemsAdder Version

[18:35:07 INFO]: ItemsAdder version 3.6.4-release-3
[18:35:07 INFO]: Customized Minecraft without client mods!
[18:35:07 INFO]: Website: devs.beer
[18:35:07 INFO]: Author: LoneDev

### ProtocolLib Version

[18:35:22 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-723
[18:35:22 INFO]: Provides read/write access to the Minecraft protocol.
[18:35:22 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[18:35:25 INFO]: LoneLibs version 1.0.55
[18:35:25 INFO]: Collection of libs used by my plugins
[18:35:25 INFO]: Authors: LoneDev and others

### Full server log

https://logs.hosting-minecraft.pro/sasomixizo

### Error (optional)

```shell
[18:35:55 INFO]: UUID of player For4anY is 7c658242-d4e4-3436-9d4c-c3a432ddade0
[18:35:56 INFO]: For4anY[/178.215.72.6:28022] logged in with entity id 73 at ([world]-151.22470320524224, 75.0, 37.10691974242481)
[18:35:56 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-3
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
        at ia.m.mW.a(SourceFile:267) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.qi.at(SourceFile:189) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.qa.a(SourceFile:209) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor340.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:200) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:20) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(ServerboundResourcePackPacket.java:9) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
# Download it here: https://black-minecraft.com/resources/27/
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: 65.108.21.198
      pack-port: 25649
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
  handle-wear-held-actions-on-unexpected-inventory-changes: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      fast_packets_creation: true
      bundle_packets: false
      delay_packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
```

**Comment by Andre601** [comment]
Please don't open a new issue for the same thing.

I was busy, so I couldn't react to your reply on the other issue.
I'll close this one and reopen the other.
