### ISSUE TITLE
Hash validation timeout problem

### ISSUE THREAD

**Issue by jiuwu02** [PluginBugs/Issues-ItemsAdder#3800]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jw_jiuwu

### What happened?

In the configuration file for my server ItemsAdder, with the self-host option enabled and the IP value filled in, the issue of Connect timed out occurs when `/iazip` is used

### Steps to reproduce the issue

1. Configure the self-host option
2. Run the `/iazip` command

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2175 (MC: 1.20.4)

### ItemsAdder Version

ItemsAdder version 3.6.4-release-3

### ProtocolLib Version

ProtocolLib version 5.2.0

### LoneLibs Version

LoneLibs version 1.0.54

### Full server log

https://[api.mclo.gs/1/raw/GefLacI](https://api.mclo.gs/1/raw/GefLacI)

### Error (optional)

```shell
[ItemsAdder] Failed to calculate resourcepack hash form remote URL http://mc.jiuwu02.top:30002/generated.zip#d2bc1f7e217d24a596c362ab0231efbf4c58267a.
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.Socket.connect(Socket.java:757)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1307)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1240)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1126)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1055)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1678)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602)
	at [I][资源包]ItemsAdder_3.6.4-release-3.jar//ia.m.qF.t(SourceFile:484)
	at [I][资源包]ItemsAdder_3.6.4-release-3.jar//ia.m.qF.bA(SourceFile:310)
	at [I][资源包]ItemsAdder_3.6.4-release-3.jar//ia.m.qF.cU(SourceFile:290)
	at [I][资源包]ItemsAdder_3.6.4-release-3.jar//ia.m.G.a(SourceFile:912)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Problematic items yml configuration file (optional)

```shell
resource-pack:
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: mc.jiuwu02.top
      pack-port: 30002
```

### Screenshots/Videos (you can drag and drop files or paste links)

![QQ_1720810715972](https://github.com/user-attachments/assets/31870b25-ad38-42c5-82bf-c54eeff1f738)

**Comment by jiuwu02** [comment]
### Additional content
This error occurs when the player enters the `/iazip` command in the background while in the server

Submit additional error logs
[ItemsAdder] Plugin ItemsAdder v3.6.4-release-3 generated an exception while executing task 36169
java.lang.NullPointerException: Cannot invoke "String.length()" because "string2" is null
        at net.minecraft.network.protocol.common.ClientboundResourcePackPushPacket.<init>(ClientboundResourcePackPushPacket.java:14) ~[purpur-1.20.4.jar
:git-Purpur-2176]
        at ia.m.mq.a(SourceFile:26) ~[[I][资源包]ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.mi.a(SourceFile:40) ~[[I][资源包]ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.qF.ax(SourceFile:186) ~[[I][资源包]ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.qO.av(SourceFile:67) ~[[I][资源包]ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.qF.ay(SourceFile:125) ~[[I][资源包]ItemsAdder_3.6.4-release-3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by LoneDev6** [comment]
`mc.jiuwu02.top:30002` for some reason is unreachable from inside the server.
Is the address correct?
Are you using the same port as the server port? You must use two different ports.
Consider using another hosting method.
