### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder

### ISSUE THREAD

**Issue by ejdzeys** [PluginBugs/Issues-ItemsAdder#3803]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.ejdzey

### What happened?

When a player join the game, the console sends the error I gave below.

### Steps to reproduce the issue

When a player join the game, the console sends the error I gave below.

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

ItemsAdder 3.6.4 release-3

### ProtocolLib Version

ProtocolLib version 5.3.0 SNAPSHOT-723

### LoneLibs Version

LoneLibs Version 1.0.55

### Full server log

https://mclo.gs/bbuL7ED

### Error (optional)

```shell
[00:05:33] [User Authenticator #1/INFO]: UUID of player Ejdzey is 3b56c811-7d9e-346e-b040-1cc3f9f5e4e1
[00:05:33] [Server thread/INFO]: Ejdzey joined the game
[00:05:33] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([995...99])
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
	at ia.m.hH.a(SourceFile:26) ~[?:?]
	at ia.m.hF.h(SourceFile:141) ~[?:?]
	at ia.m.hA.d(SourceFile:234) ~[?:?]
	at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[?:?]
	at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[?:?]
	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1903) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1876) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerList.sendAll(PlayerList.java:1049) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerList.sendMessage(PlayerList.java:1418) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerList.sendMessage(PlayerList.java:1423) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:367) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([995...99])
	at net.minecraft.server.v1_16_R3.ChatDeserializer.a(SourceFile:103) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatDeserializer.h(SourceFile:109) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatHoverable$b.a(SourceFile:134) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatHoverable$EnumHoverAction.a(SourceFile:337) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatHoverable.a(SourceFile:94) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.b(ChatModifier.java:292) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:243) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:246) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:186) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:109) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.5.jar:git-Paper-794]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:376) ~[patched_1.16.5.jar:git-Paper-794]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
	... 35 more
[00:05:33] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@4ee4e2c1[
    a=io.papermc.paper.adventure.AdventureComponent@18aca925
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

[00:05:33] [Server thread/INFO]: Ejdzey[/88.243.39.33:50371] logged in with entity id 2 at ([world]0.9128934755230051, 1.0, 0.7968492159631662)
```

**Comment by Andre601** [comment]
Try downgrading lonelibs to an older version, to see if that fixes it. If that doesn't help check #3715 for any info that might help.

**Comment by ejdzeys** [comment]
> Lonelibs'i daha eski bir sürüye düşürmeyi deneyin, bunun nedenini çözüp çözmeye bakın. Bu işe yaramazsa yardımcı olabilecek herhangi bir bilgi [#3715'i kontrol edin.](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3715)

unfortunately the problem still persists

**Comment by Gecenin0fkesi** [comment]
Also I just discovered this error shows up when opening a Villager menu too.

**Comment by ejdzeys** [comment]
Where can I download the old version of LoneLibs? When the old version is downloaded from Spigot, it downloads the new version.

**Comment by Andre601** [comment]
> Where can I download the old version of LoneLibs? When the old version is downloaded from Spigot, it downloads the new version.

On the Resource page, click the "Version History" tab and then click the "Download" text next to the version you want to download.

**Comment by ejdzeys** [comment]
> > Where can I download the old version of LoneLibs? When the old version is downloaded from Spigot, it downloads the new version.
> 
> On the Resource page, click the "Version History" tab and then click the "Download" text next to the version you want to download.

I downloaded version 1.0.46 but this version is not valid downloading the latest version

**Comment by ejdzeys** [comment]
@LoneDev6

**Comment by Andre601** [comment]
Tagging LoneDev brings you nothing and may even result in punishments for halfhazardly tagging staff.
Stay patient.

**Comment by ejdzeys** [comment]
> Tagging LoneDev brings you nothing and may even result in punishments for halfhazardly tagging staff. Stay patient.

Is there a problem with your Discord verify system? "Error verifying user: AxiosError: Request failed with status code 403"

**Comment by Andre601** [comment]
In all honesty: The Discord system would not provide you anything beneficial there.
Tho, this is not something for the issue tracker here.

**Comment by Andre601** [comment]
> [LoneLibs.zip](https://github.com/user-attachments/files/16562077/LoneLibs.zip) 1.0.27 ItemsAdder_3.5.0b ProtocolLib 5.2.0
> 
> I am using these versions for 1.16.5. I have not encountered any problems. 1.16.5 to 1.21 works.

I suggest updating. You're using stoneage versions of LoneDev's plugins. Latest v3 should work fine on 1.16.5.
Also, it's recommended to not using plugins like ViaVersion to allow newer clients to join and play on the server. That's not what the plugin was made for.
