### ISSUE TITLE
a packet error

### ISSUE THREAD

**Issue by ZzhangaAo1z** [PluginBugs/Issues-ItemsAdder#3812]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When player dead, console will send this error
I also try to use old version ItemsAdder(3.5.0) and LoneLibs version(1.0.45/1.0.24)
this error still exist

### Steps to reproduce the issue

1.join game
2.kill myself
3.error

### Server version

This server is running CraftBukkit version 3498-Spigot-b081915-10ba1be (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder Version: 3.6.4-release-3

### ProtocolLib Version

ProtocolLib v5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.55

### Error (optional)

```shell
[04:09:21] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([585...02])
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
	at ia.m.hH.a(SourceFile:26) ~[?:?]
	at ia.m.hF.h(SourceFile:141) ~[?:?]
	at ia.m.hA.d(SourceFile:234) ~[?:?]
	at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.network.NetworkManager.b(NetworkManager.java:215) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:195) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1721) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1715) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:1147) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:819) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:905) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:934) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.world.entity.EntityLiving.ag(EntityLiving.java:317) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.commands.CommandKill.a(SourceFile:32) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.commands.CommandKill.a(SourceFile:25) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:284) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:826) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:811) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:454) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:430) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([585...02])
	at net.minecraft.util.ChatDeserializer.a(SourceFile:104) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.util.ChatDeserializer.h(SourceFile:110) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable$b.a(SourceFile:133) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable$EnumHoverAction.a(SourceFile:344) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable.a(SourceFile:93) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.b(SourceFile:374) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.a(SourceFile:348) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.deserialize(SourceFile:330) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:298) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:235) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:435) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
	... 41 more
[04:09:21] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutChat@31a68971[
    a=TranslatableComponent{key='death.attack.outOfWorld', args=[TextComponent{text='ZzhangaAo1z', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell ZzhangaAo1z '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@71ae4253'}, insertion=ZzhangaAo1z, font=minecraft:default}}], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

[04:09:21] [Server thread/INFO]: Killed ZzhangaAo1z
[04:09:21] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([585...02])
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
	at ia.m.hH.a(SourceFile:26) ~[?:?]
	at ia.m.hF.h(SourceFile:141) ~[?:?]
	at ia.m.hA.d(SourceFile:234) ~[?:?]
	at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.network.NetworkManager.b(NetworkManager.java:215) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:195) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1721) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1715) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1710) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.commands.CommandListenerWrapper.b(CommandListenerWrapper.java:240) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.commands.CommandListenerWrapper.a(CommandListenerWrapper.java:225) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.commands.CommandKill.a(SourceFile:36) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.commands.CommandKill.a(SourceFile:25) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:284) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:826) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:811) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:454) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:430) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([585...02])
	at net.minecraft.util.ChatDeserializer.a(SourceFile:104) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.util.ChatDeserializer.h(SourceFile:110) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable$b.a(SourceFile:133) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable$EnumHoverAction.a(SourceFile:344) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatHoverable.a(SourceFile:93) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.b(SourceFile:374) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.a(SourceFile:348) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.ChatModifier$ChatModifierSerializer.deserialize(SourceFile:330) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:298) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:235) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:235) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:435) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
	... 38 more
[04:09:21] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutChat@7831c802[
    a=TranslatableComponent{key='chat.type.admin', args=[TextComponent{text='Server', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TranslatableComponent{key='commands.kill.success.single', args=[TextComponent{text='ZzhangaAo1z', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell ZzhangaAo1z '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@71ae4253'}, insertion=ZzhangaAo1z, font=minecraft:default}}], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], siblings=[], style=Style{ color=gray, bold=null, italic=true, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by Andre601** [comment]
Did you try to only downgrade LoneLibs or did you downgrade everything at once?

Also, please provide your latest.log, thanks.

Finally, #3682 may have some additional info that may help you out here.
