### ISSUE TITLE
Plugin doesn't finish initializing

### ISSUE THREAD

**Issue by cubicPsycho** [PluginBugs/Issues-ItemsAdder#3813]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cubicpsycho

### What happened?

Whenever I launch my server with the plugin, it creates an error in the log and never finishes initializing

### Steps to reproduce the issue

Run server
???

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.55

### Error (optional)

```shell
[ItemsAdder] Plugin ItemsAdder v4.0.1-alpha-test-5 generated an exception while executing task 17
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String, boolean)" because "this.LY" is null
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.mm.k(SourceFile:153) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.fn.a(SourceFile:64) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.G.a(SourceFile:814) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by LoneDev6** [comment]
you have a misconfigured crafting_table recipe, please remove all yml configurations until you find the broken one, then post it here so that I can tell you the exact reason.
