### ISSUE TITLE
Error initializing plugin 'ItemsAdder_4.0.1-alpha-test-5.jar'

### ISSUE THREAD

**Issue by SeCrEaT999** [PluginBugs/Issues-ItemsAdder#3816]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have used all legitimate versions of the plugin, but the plugin outputs an error to the console.

### Steps to reproduce the issue

1. Put the latest version of ItemsAdder, ProtocoliLib, and LoneLibs into the plugins folder.

2. Click the start.bat file to start the server.

3. The server outputs the above error while starting.

The contents of start.bat are as follows: (@echo off

java - G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTen uringThreshold= 1 -XX:SurvivorRatio=32 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper-1.21-107.jar

pause)

### Server version

This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.55

### Full server log

Starting org.bukkit.craftbukkit.Main
[00:13:15 INFO]: [bootstrap] Running Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.4+8-LTS-274; Oracle Corporation null) on Windows 11 10.0 (amd64)
[00:13:15 INFO]: [bootstrap] Loading Paper 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) for Minecraft 1.21
[00:13:16 INFO]: [PluginInitializerManager] Initializing plugins...
[00:13:16 INFO]: [PluginRemapper] Remapping plugin 'plugins\LoneLibs.jar'...
[00:13:17 INFO]: [PluginRemapper] Done remapping plugin 'plugins\LoneLibs.jar' in 933ms.
[00:13:17 INFO]: [PluginInitializerManager] Initialized 7 plugins
[00:13:17 INFO]: [PluginInitializerManager] Bukkit plugins (7):
 - ItemsAdder (4.0.1-alpha-test-5), LoneLibs (1.0.55), Multiverse-Core (4.3.12), Multiverse-Portals (4.2.3), ProtocolLib (5.3.0-SNAPSHOT-723), WorldEdit (7.3.4+6823-6263244), WorldGuard (7.0.10+d9424b1)
[00:13:20 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[00:13:21 INFO]: Loaded 1290 recipes
[00:13:21 INFO]: Loaded 1399 advancements
[00:13:21 INFO]: Starting minecraft server version 1.21
[00:13:21 INFO]: Loading properties
[00:13:21 INFO]: This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[00:13:22 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[00:13:22 INFO]: Using 4 threads for Netty based IO
[00:13:22 INFO]: Server Ping Player Sample Count: 12
[00:13:22 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 6 worker threads, and population gen parallelism of 6 threads
[00:13:23 INFO]: Default game type: SURVIVAL
[00:13:23 INFO]: Generating keypair
[00:13:23 INFO]: Starting Minecraft server on *:25565
[00:13:23 INFO]: Using default channel type
[00:13:23 INFO]: Paper: Using Java compression from Velocity.
[00:13:23 INFO]: Paper: Using Java cipher from Velocity.
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 3 libraries... please wait
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\org\apache\httpcomponents\httpmime\4.5.14\httpmime-4.5.14.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\org\apache\httpcomponents\httpclient\4.5.14\httpclient-4.5.14.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\commons-codec\commons-codec\1.11\commons-codec-1.11.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar
[00:13:23 INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library C:\Users\hajun\OneDrive\바탕 화면\1.21\libraries\net\sourceforge\streamsupport\speedy-math\1.0.0\speedy-math-1.0.0.jar
[00:13:23 INFO]: [WorldEdit] Loading server plugin WorldEdit v7.3.4+6823-6263244
[00:13:24 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@741da19d]
[00:13:24 INFO]: [Multiverse-Core] Loading server plugin Multiverse-Core v4.3.12
[00:13:24 INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.10+d9424b1
[00:13:24 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.3.0-SNAPSHOT-723
[00:13:24 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[00:13:24 INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.55
[00:13:24 INFO]: [Multiverse-Portals] Loading server plugin Multiverse-Portals v4.2.3
[00:13:24 INFO]: [ItemsAdder] Loading server plugin ItemsAdder v4.0.1-alpha-test-5
[00:13:24 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_4.0.1-alpha-test-5.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isOlderThan(Version.java:86) ~[LoneLibs.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.Q.Q(SourceFile:450) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.iT(SourceFile:564) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onLoad(SourceFile:176) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:13:24 INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:13:24 INFO]: [WorldEdit] Enabling WorldEdit v7.3.4+6823-6263244
[00:13:24 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[00:13:25 INFO]: WEPIF: Using the Bukkit Permissions API.
[00:13:25 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_21.PaperweightAdapter as the Bukkit adapter
[00:13:26 INFO]: [ProtocolLib] Enabling ProtocolLib v5.3.0-SNAPSHOT-723
[00:13:26 INFO]: [LoneLibs] Enabling LoneLibs v1.0.55
[00:13:26 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[00:13:26 WARN]: The server will make no attempt to authenticate usernames. Beware.
[00:13:26 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[00:13:26 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[00:13:26 INFO]: Preparing level "PLAYGROUND"
[00:13:26 INFO]: Preparing start region for dimension minecraft:overworld
[00:13:27 INFO]: Time elapsed: 320 ms
[00:13:27 INFO]: Preparing start region for dimension minecraft:the_end
[00:13:27 INFO]: Time elapsed: 203 ms
[00:13:27 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.12
[00:13:27 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.12" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[00:13:27 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[00:13:27 INFO]: Preparing start region for dimension minecraft:the_nether
[00:13:27 INFO]: Time elapsed: 100 ms
[00:13:27 INFO]: Preparing start region for dimension minecraft:wild
[00:13:27 INFO]: Time elapsed: 77 ms
[00:13:27 INFO]: [Multiverse-Core] 4 - World(s) loaded.
[00:13:27 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
[00:13:27 INFO]: [Multiverse-Core] Version 4.3.12 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[00:13:27 INFO]: [WorldGuard] Enabling WorldGuard v7.0.10+d9424b1
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND) TNT ignition is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND) Lighters are PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND) Lava fire is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND) Fire spread is UNRESTRICTED.
[00:13:27 INFO]: [WorldGuard] Loaded configuration for world 'PLAYGROUND'
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_the_end) TNT ignition is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_the_end) Lighters are PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_the_end) Lava fire is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_the_end) Fire spread is UNRESTRICTED.
[00:13:27 INFO]: [WorldGuard] Loaded configuration for world 'PLAYGROUND_the_end'
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_nether) TNT ignition is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_nether) Lighters are PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_nether) Lava fire is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (PLAYGROUND_nether) Fire spread is UNRESTRICTED.
[00:13:27 INFO]: [WorldGuard] Loaded configuration for world 'PLAYGROUND_nether'
[00:13:27 INFO]: [WorldGuard] (wild) TNT ignition is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (wild) Lighters are PERMITTED.
[00:13:27 INFO]: [WorldGuard] (wild) Lava fire is PERMITTED.
[00:13:27 INFO]: [WorldGuard] (wild) Fire spread is UNRESTRICTED.
[00:13:27 INFO]: [WorldGuard] Loaded configuration for world 'wild'
[00:13:27 INFO]: [WorldGuard] Loading region data...
[00:13:28 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v4.2.3
[00:13:28 INFO]: [Multiverse-Portals] 1 - Portals(s) loaded
[00:13:28 INFO]: [Multiverse-Portals] Found WorldEdit. Using it for selections.
[00:13:28 INFO]: [Multiverse-Portals 4.2.3]  Enabled - By Rigby and fernferret
[00:13:28 INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.1-alpha-test-5
[00:13:28 ERROR]: Error occurred while enabling ItemsAdder v4.0.1-alpha-test-5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.Version.ordinal()" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.iO.jF(SourceFile:143) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.iO.jE(SourceFile:88) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:186) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:13:28 INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.1-alpha-test-5
[00:13:28 ERROR]: Error occurred while disabling ItemsAdder v4.0.1-alpha-test-5
java.lang.ExceptionInInitializerError: null
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onDisable(SourceFile:661) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isAtLeast(Version.java:64) ~[LoneLibs.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.jO.<clinit>(SourceFile:96) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        ... 16 more
[00:13:28 INFO]: [spark] Starting background profiler...
[00:13:28 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[00:13:28 INFO]: Done preparing level "PLAYGROUND" (2.508s)
[00:13:28 INFO]: Running delayed init tasks
[00:13:28 INFO]: Done (13.197s)! For help, type "help"
[00:13:28 INFO]: Timings Reset

### Error (optional)

```shell
[00:13:24 ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_4.0.1-alpha-test-5.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isOlderThan(Version.java:86) ~[LoneLibs.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.Q.Q(SourceFile:450) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.iT(SourceFile:564) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onLoad(SourceFile:176) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:13:28 ERROR]: Error occurred while enabling ItemsAdder v4.0.1-alpha-test-5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.Version.ordinal()" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.iO.jF(SourceFile:143) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.iO.jE(SourceFile:88) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:186) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:13:28 INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.1-alpha-test-5
[00:13:28 ERROR]: Error occurred while disabling ItemsAdder v4.0.1-alpha-test-5
java.lang.ExceptionInInitializerError: null
        at ItemsAdder_4.0.1-alpha-test-5.jar/dev.lone.itemsadder.Main.onDisable(SourceFile:661) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
        at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isAtLeast(Version.java:64) ~[LoneLibs.jar:?]
        at ItemsAdder_4.0.1-alpha-test-5.jar/ia.m.jO.<clinit>(SourceFile:96) ~[ItemsAdder_4.0.1-alpha-test-5.jar:?]
        ... 16 more
```

**Comment by Andre601** [comment]
v4 of ItemsAdder is ONLY for 1.20.6, no other version. Please read the changelogs next time before just downloading the plugin.

**Comment by SeCrEaT999** [comment]
> v4 of ItemsAdder is ONLY for 1.20.6, no other version. Please read the changelogs next time before just downloading the plugin.

I didn't see it because I was adjusting other plugins to 1.21. Thank you for pointing this out and letting me know.
