### ISSUE TITLE
 API Problem getting ItemStack from CustomStack

### ISSUE THREAD

**Issue by matiw219** [PluginBugs/Issues-ItemsAdder#3825]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have code that gettting ItemStack via item namespace but unfortunately it doesn't work with the latest version of itemsadder.

Code:
`
package me.masterkaiser.test;

import dev.lone.itemsadder.api.CustomStack;
import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;

public class TestPlugin extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    void onJoin(PlayerJoinEvent event) {
        event.getPlayer().getInventory().addItem(getStack("other:azure_shard"));
    }

    @EventHandler
    void onInteract(PlayerInteractEvent event) {
        event.getPlayer().getInventory().addItem(getStack("other:azure_shard"));
    }

    public static ItemStack getStack(String namespace) {
        if (namespace == null) {
            return null;
        }

        try {
            CustomStack customStack = CustomStack.getInstance(namespace);
            if (customStack != null) {
                return customStack.getItemStack();
            }

            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
`

### Steps to reproduce the issue

1. I wrote a plugin that gives a player an item from ItemsAdder upon joining the server and when they click.
2. Upon joining the server, the plugin throws an error related to CraftItemStack.
3. The end.

### Server version

[16:56:21 INFO]: Checking version, please wait...
[16:56:22 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-108-73a863b (MC: 1.21)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-723

### LoneLibs Version

LoneLibs version 1.0.56

### Error (optional)

```shell
[16:51:44 ERROR]: Could not pass event PlayerInteractEvent to TestPlugin v1.0
java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack
        at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:73) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.inventory.CraftInventory.addItem(CraftInventory.java:327) ~[paper-1.21.jar:1.21-109-5a5035b]
        at test-itemsadder-1.0-SNAPSHOT.jar/me.masterkaiser.test.TestPlugin.onInteract(TestPlugin.java:27) ~[test-itemsadder-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.jar:1.21-109-5a5035b]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2513) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:34) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:16) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-109-5a5035b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by ThePitereq** [comment]
Same problem here.
Issue seems to be related to ItemStack creation somehow, as IA items works in my custom villager generation through Merchant class, but they doesn't in direct ItemStack creation into inventory.
I am not highly experienced with minecraft plugins so take my answer with a grain of salt ^^

**Comment by TeamSussy** [comment]
Having the same issue as well, I'm able to get an item via namespace and use it in a crafting recipe however any other usage results in the exact same error

**Comment by Gypopo** [comment]
Same issue here, people started reporting this issue from the v4 alpha builds and breaks the hook in our plugin,, it seems like the NMS object of the item isn't working correctly. Using bukkit API to modify the item works fine and such but as soon as the item is either added to a inventory or casted to a NMS stack, the error pops up.

Altough I have found a simple temp fix by adding .clone(), so anyone with the same issue, use the following `CustomStack.getInstance(id).getItemStack().clone()` which seems to prevent the issue from happening.

However, when the item is cloned again using `new ItemStack(clone)` the issue will happen again when adding the item to inventory's.

**Comment by matiw219** [comment]
> Altough I have found a simple temp fix by adding .clone(), so anyone with the same issue, use the following `CustomStack.getInstance(id).getItemStack().clone()` which seems to prevent the issue from happening.

Unfortunately, I would have to make too many changes; I have one large plugin that handles the entire server. 
We can only wait for an update that will fix it. It's interesting how long we'll have to wait to get our servers started.

@LoneDev6 when we can expect the patch?

**Comment by Andre601** [comment]
> Unfortunately, I would have to make too many changes; I have one large plugin that handles the entire server.
> We can only wait for an update that will fix it. It's interesting how long we'll have to wait to get our servers started.

Not really related to the issue itself, but a personal suggestion of mine is to not have one big plugin do all the work for the server. Splitting it up into multiple smaller plugins that interact with each other is a much better and more managable aproach, as you could update one small plugin while everything else is still running.

Regarding LoneDev: He's currently taking a break, so updates and replies to issues may get delayed. Patience is apreciated.

**Comment by Ordwen** [comment]
I had the same problem with my ODailyQuests plugin. 

As mentioned by Gypopo, adding a `.clone()` after the call to `CustomStack.getInstance(id).getItemStack()` fixes the problem. But it's strange because the same type of object is returned by both methods...

For those who use this method in many places, you can still create an `ItemProvider` that you can reuse at each key location: this kind of problem can then be corrected in a single modification, and it will be cleaner overall, in addition to the advice given by Andre601.

Or you can simply do a "Replace All" in your IDE...

**Comment by LoneDev6** [comment]
Duplicate of #3857
Will be fixed, it's a 1.21 change, as usual shit caused by internal changes.
