### ISSUE TITLE
Task #124 for ItemsAdder v3.6.4-release-3 generated an exception

### ISSUE THREAD

**Issue by OrsoSgravato34** [PluginBugs/Issues-ItemsAdder#3840]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

orso_34

### What happened?

So.. i tried uploading the 3.6.4 version 3 of itemsadder since i'm with 1.17.1 and java17 but i got the error Task #124 for ItemsAdder v3.6.4-release-3 generated an exception right after the plugin loaded

### Steps to reproduce the issue

Install the plugin itemsadder 3.6.4 version 3,2,1 (i tried them all, still the same error)
Start the server
Wait for the plugin to load

### Server version

[04:17:29] [Server thread/INFO]: This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[04:17:29] [Server thread/INFO]: Checking version, please wait...
[04:17:30] [Thread-31/INFO]: You are 52 version(s) behind

### ItemsAdder Version

[04:17:49] [Server thread/INFO]: ItemsAdder version 3.6.4-release-3
[04:17:49] [Server thread/INFO]: Customized Minecraft without client mods!
[04:17:49] [Server thread/INFO]: Website: devs.beer
[04:17:49] [Server thread/INFO]: Author: LoneDev

### ProtocolLib Version

[04:18:00] [Server thread/INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[04:18:00] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[04:18:00] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[04:18:10] [Server thread/INFO]: LoneLibs version 1.0.56
[04:18:10] [Server thread/INFO]: Collection of libs used by my plugins
[04:18:10] [Server thread/INFO]: Authors: LoneDev and others

### Full server log

https://mclo.gs/cEzsluk

### Error (optional)

```shell
[04:15:39] [Server thread/WARN]: [ItemsAdder] Task #124 for ItemsAdder v3.6.4-release-3 generated an exception
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap
        at ia.m.nU.cs(SourceFile:246) ~[?:?]
        at ia.m.fM.bL(SourceFile:22) ~[?:?]
        at ia.m.fs.a(SourceFile:476) ~[?:?]
        at ia.m.G.a(SourceFile:919) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 12 more
```

**Comment by OrsoSgravato34** [comment]
Fixed it.

**Comment by OrsoSgravato34** [comment]
Fixed it
