### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by Ondraeucz** [PluginBugs/Issues-ItemsAdder#3841]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nyxcz

### What happened?

At startup, adding it throws an error and thus the plugin does not start.

### Steps to reproduce the issue

f

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

https://mclo.gs/FbalwSd

### Error (optional)

```shell
[13:02:44] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v4.0.2-alpha-test-3 (Is it up to date?)
java.lang.NoClassDefFoundError: me/wolfyscript/customcrafting/listeners/AnvilListener
	at ItemsAdder_4.0.2-alpha-test-3.jar/dev.lone.itemsadder.Core.OtherPlugins.CustomCrafting.CustomCraftingAPIWrapper.<clinit>(SourceFile:29) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:289) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.wolfyscript.customcrafting.listeners.AnvilListener
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 14 more
```

**Comment by Andre601** [comment]
```
java.lang.NoClassDefFoundError: me/wolfyscript/customcrafting/listeners/AnvilListener
```
This error points to ItemsAdder trying to use a class from a plugin (CustomCrafting) which seems to not be yet loaded/enabled.
My best guess here is, that this is a missing plugin dependency setting in ItemsAdder, or that the plugin CustomCrafting changed its name causing a previously working softdependency to no longer work.
