### ISSUE TITLE
 Could not pass event PlayerItemHeldEvent to ItemsAdder

### ISSUE THREAD

**Issue by Nunchakin** [PluginBugs/Issues-ItemsAdder#3843]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nunchakin

### What happened?

Some error, I have no idea when is this happening tbh

### Steps to reproduce the issue

Have ItemsAdder on 1.21 Paper, I joined my server for the first time (deleted CMI database)

### Server version

Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

https://mclo.gs/65WXeUC

### Error (optional)

```shell
[12:59:12 ERROR]: Could not pass event PlayerItemHeldEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.setString(String, String)" because the return value of "lonelibs.dev.lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:69) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:205) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) :[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-119-100d75a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) :[paper-1.21.jar:1.21-119-100d75a]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) :[paper-1.21.jar:1.21-119-100d75a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2061) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.TickTask.run(TickTask.java:18) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) :[paper-1.21.jar:1.21-119-100d75a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) :[paper-1.21.jar:1.21-119-100d75a]
at java.base/java.lang.Thread.run(Thread.java:1583) :[?:?]
```

**Comment by bobhenl** [comment]
Hello I can confirm this:
```yml
[16:12:27] [Server thread/ERROR]: Could not pass event PlayerItemHeldEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.setString(String, String)" because the return value of "lonelibs.dev.lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:69) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:205) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2140) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by svaningelgem** [comment]
I know you're on it, but also noticed this error on alpha-7:
```
[11:51:51 ERROR]: Could not pass event PlayerItemHeldEvent to ItemsAdder v4.0.2-alpha-test-7
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.setString(String, String)" because the return value of "lonelibs.dev.lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
        at ItemsAdder_4.0.2-alpha-test-7.jar/ia.m.mh.a(SourceFile:69) ~[ItemsAdder_4.0.2-alpha-test-7.jar:?]
        at ItemsAdder_4.0.2-alpha-test-7.jar/ia.m.mh.a(SourceFile:205) ~[ItemsAdder_4.0.2-alpha-test-7.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-106-3a47518]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2061) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by svaningelgem** [comment]
Thanks! 👍 Looking forward to alpha-8!
