### ISSUE TITLE
Blockbench Animation Particles (Unknown particle 'minecraft:block stone')

### ISSUE THREAD

**Issue by iCrashMix0** [PluginBugs/Issues-ItemsAdder#3850]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://discord.com/channels/533407895010803753/533413171403292712/1268273413248778423

### Steps to reproduce the issue

-

### Server version

-

### ItemsAdder Version

-

### ProtocolLib Version

-

### LoneLibs Version

-

### Error (optional)

```shell
[21:51:58 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R2.block.data.CraftBlockData.getState()" because "data" is null
[21:51:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:139)
[21:51:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftParticle$CraftParticleRegistry$4.createParticleParam(CraftParticle.java:136)
[21:51:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftParticle.createParticleParam(CraftParticle.java:68)
[21:51:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2755)
[21:51:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.spawnParticle(CraftPlayer.java:2740)
[21:51:58 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.av.a(SourceFile:68)
[21:51:58 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.ay.Z(SourceFile:159)
[21:51:58 WARN]:        at ItemsAdder_3.6.4-release-3.jar//ia.m.ad.B(SourceFile:1042)
[21:51:58 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:51:58 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:51:58 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:51:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:51:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:51:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by Andre601** [comment]
Please provide the info as requested and don't leave them blank. We ask for them for a reason and linking to a Discord Channel is not sufficient info.
