### ISSUE TITLE
ItemsAdder v4 /emote command not working!

### ISSUE THREAD

**Issue by iCrashMix0** [PluginBugs/Issues-ItemsAdder#3855]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

/emote command does not work properly.

### Steps to reproduce the issue

1. fresh Minecraft Server 1.21 PaperMC
2. install the following plugins: ItemsAdder, LoneLibs and ProtocolLib (The latest version installed on 02.08.2024)
3. in ItemsAdder folder under config.yml file, I have switched on "self-host".
4. join the server with 2 accounts and run /emote (something)
5. emote plays, does not stop afterwards and error 1 appears. Emote stops when you leave the server and rejoin the server, but you can't use /emote command anymore, error 2 appears.

Error 3 has appeared by leaving

### Server version

Paper version 1.21-123-master@0a1be9a

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full server log

[latest.log](https://github.com/user-attachments/files/16462928/latest.log)

### Error (optional)

```shell
Error 1:
[01:31:11 WARN]: [ItemsAdder] Task #1699 for ItemsAdder v4.0.2-alpha-test-3 generated an exception
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ab.W(SourceFile:32) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.a(SourceFile:1401) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.a(SourceFile:1814) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.c(SourceFile:1619) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Error 2:
[01:31:35 ERROR]: Command exception: /emote death_2
org.bukkit.command.CommandException: Unhandled exception executing command 'emote' in plugin ItemsAdder v4.0.2-alpha-test-3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ab.W(SourceFile:32) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.a(SourceFile:1414) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.z(SourceFile:1801) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.f(SourceFile:1602) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.hO.onCommand(SourceFile:79) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more

Error 3:
[01:40:40 INFO]: JulixDev lost connection: Disconnected
[01:40:40 ERROR]: Could not pass event PlayerQuitEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ab.W(SourceFile:32) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.a(SourceFile:1414) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ac.z(SourceFile:1801) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.aE.a(SourceFile:224) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:605) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:590) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2036) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2016) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2003) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:902) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1823) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/tyo0gYuczQU

**Comment by Andre601** [comment]
The error reported is the same as in #3854, as such will I close this issue as duplicate.
