### ISSUE TITLE
Error Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Nunchakin** [PluginBugs/Issues-ItemsAdder#3856]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nunchakin

### What happened?

Spamming errors in console
https://pastebin.com/jb6SJtkd

### Steps to reproduce the issue

I have no idea when this happens but it spams my console a lot

### Server version

Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Error (optional)

```shell
[12:10:49 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.setString(String, String)" because the return value of "lonelibs.dev.lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:69) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:222) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) :[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) :[paper-1.21.jar:1.21-123-0a1be9a]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.TickTask.run(TickTask.java:18) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) :[paper-1.21.jar:1.21-123-0a1be9a]
at java.base/java.lang.Thread.run(Thread.java:1583) :[?:?]
>....
[12:10:50 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.NCompound.setString(String, String)" because the return value of "lonelibs.dev.lone.fastnbt.nms.nbt.NItem.getCompound(String)" is null
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:69) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lC.a(SourceFile:222) :[ItemsAdder_4.0.2-alpha-test-3.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) :[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-123-0a1be9a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) :[paper-1.21.jar:1.21-123-0a1be9a]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) :[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) :[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.TickTask.run(TickTask.java:18) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) :[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) :[paper-1.21.jar:1.21-123-0a1be9a]
at java.base/java.lang.Thread.run(Thread.java:1583) :[?:?]
```

**Comment by TheModdersDen** [comment]
I am having a similar issue as well, but on PurpurMC with additional errors, which I thought might be of use in debugging this:
[link to logs](https://pastebin.com/kfF7hm6j).

Specifically, you can see the errors in question around lines 900 and below. The rest are just my server starting up and loading the laundry list of plugins I have.

I have also attached a picture of a list of plugins I am currently running, again for debugging purposes. As far as I know, none of them should be causing any incompatibilities. Then again, I haven't ever successfully made a plugin as good as LoneDev has. 😄 😉 
![plugin list](https://github.com/user-attachments/assets/a7d54f2a-0fc4-41b9-893a-32c16656bcc6)

Hope this helps!
//TheModdersDen

**Comment by WhiteProject1** [comment]
I have same problem to
