### ISSUE TITLE
rectangle char after emoji

### ISSUE THREAD

**Issue by SepSepHD** [PluginBugs/Issues-ItemsAdder#3861]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Rudlmeyer

### What happened?

All emojis render themselfes and an rectangle char.
![Bild_2024-08-04_222727321](https://github.com/user-attachments/assets/51fa312a-595e-4788-80fe-434b909b5072)
`[20:55:01] [Server thread/ERROR]: [ItemsAdder] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for ItemsAdder
[04.08 20:55:02.158] INFO: [City-1] java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
[04.08 20:55:02.158] INFO: [City-1]     at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:241) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at ia.m.hH.a(SourceFile:24) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at ia.m.hF.i(SourceFile:135) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at ia.m.hy.onPacketSending(SourceFile:99) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.network.NetworkManager.b(NetworkManager.java:212) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.network.NetworkManager.a(NetworkManager.java:192) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1836) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1822) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:288) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:559) ~[?:?]
[04.08 20:55:02.158] INFO: [City-1]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
[04.08 20:55:02.158] INFO: [City-1]     at java.lang.Thread.run(Thread.java:1589) [?:?]
[04.08 20:55:03.156] INFO: [City-1] Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
[04.08 20:55:03.156] INFO: [City-1]     at java.lang.Class.cast(Class.java:3946) ~[?:?]
[04.08 20:55:03.156] INFO: [City-1]     at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:233) ~[?:?]
[04.08 20:55:03.156] INFO: [City-1]     ... 30 more`

### Steps to reproduce the issue

1.Use emoji 
2. See that it has a box besides it

### Server version

This server is running CraftBukkit version 3610-Spigot-6198b5a-19df23a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### ItemsAdder Version

3.6.4

### ProtocolLib Version

5.1
5.2
5.0
tried all of them

### LoneLibs Version

1.0.56

### Full server log

[2024-08-04-15.log](https://github.com/user-attachments/files/16488847/2024-08-04-15.log)

### Error (optional)

```shell
[ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:241) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[?:?]
	at ia.m.hH.a(SourceFile:24) ~[?:?]
	at ia.m.hF.i(SourceFile:135) ~[?:?]
	at ia.m.hy.onPacketSending(SourceFile:99) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:565) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:468) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.network.NetworkManager.b(NetworkManager.java:212) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:192) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1836) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1822) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:288) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:559) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.IChatBaseComponent
	at java.lang.Class.cast(Class.java:3946) ~[?:?]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.deserialize(MinecraftComponentSerializer.java:233) ~[?:?]
	... 30 more
[21:46:41] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@27753597[
    a={"extra":[{"text":"Rudlmeyer: "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"tt"}],"text":""}
    b=false
  ]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: "ranks"
font_images:
  owner:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:owner"
    scale_ratio: 9
    y_position: 8
  admin:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:admin"
    scale_ratio: 9
    y_position: 8
  developer:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:developer"
    scale_ratio: 9
    y_position: 8
  mod:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:mod"
    scale_ratio: 9
    y_position: 8
  builder:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:builder"
    scale_ratio: 9
    y_position: 8
  helper:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:helper"
    scale_ratio: 9
    y_position: 8
  youtube:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:youtube"
    scale_ratio: 9
    y_position: 8
  twitch:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:twitch"
    scale_ratio: 9
    y_position: 8
  ultravip:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:ultravip"
    scale_ratio: 9
    y_position: 8
  megavip:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:megavip"
    scale_ratio: 9
    y_position: 8
  vipplus:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:vipplus"
    scale_ratio: 9
    y_position: 8
  vip:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:vip"
    scale_ratio: 9
    y_position: 8
  legend:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:legend"
    scale_ratio: 9
    y_position: 8
  hero:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:hero"
    scale_ratio: 9
    y_position: 8
  elite:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:elite"
    scale_ratio: 9
    y_position: 8
  player:
    permission: "highlanderranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "ranks:player"
    scale_ratio: 9
    y_position: 8
```

**Comment by Andre601** [comment]
1. You're using 1.19.2, and CraftBukkit on top of that. Please update your server to 1.19.4 and preferably Paper
2. You are running an outdated IA version. Please get the latest available version for your server version (NOT the latest v4 release, but the latest v3!)
3. You have a few errors about IA being unable to find images for specific font images... Did you modify the `_iainternal` folder?
