### ISSUE TITLE
Vanilla commands in execute_commands event in 4.0.2 alpha 3

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#3869]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@gust1337

### What happened?

Vanilla commands cause warns in console with execute_commands event

### Steps to reproduce the issue

1. Create item with execute_commands event
2. Use item
3. Look at console

### Server version

PaperSpigot version 1.21-46 (API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2 alpha 3

### ProtocolLib Version

5.3.0-726

### LoneLibs Version

 1.0.56

### Error (optional)

```shell
[15:06:15] [Server thread/INFO]: Gu57 issued server command: /iaget zl_items:recall_potion
[15:06:18] [Server thread/WARN]: [ItemsAdder] Task #26928 for ItemsAdder v4.0.2-alpha-test-3 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'minecraft:tp Gu57 78.5 65.0 -220.5' in org.bukkit.craftbukkit.command.VanillaCommandWrapper(minecraft:tp)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1103) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jw.g(SourceFile:130) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dy.a(SourceFile:152) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dx.a(SourceFile:52) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dZ.b(SourceFile:91) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.er.b(SourceFile:58) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dd.a(SourceFile:894) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1717) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1601) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1308) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.AbstractMethodError: Receiver class ia.m.jx does not define or inherit an implementation of the resolved method 'abstract boolean acceptsSuccess()' of interface net.minecraft.commands.CommandSource.
	at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:314) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.commands.TeleportCommand.teleportToPos(TeleportCommand.java:139) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.server.commands.TeleportCommand.lambda$register$3(TeleportCommand.java:56) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:327) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at org.bukkit.craftbukkit.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:55) ~[paper-1.21.jar:1.21-46-2fa5e0e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 16 more
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: zl_items
items:
  recall_potion:
    enabled: true
    display_name: Зелье возврата
    permission: zl.user
    lore:
      - §7Выпейте для возврата к кровати.
    resource:
      material: POTION
      generate: true
      textures:
        - potions/recall_potion
    item_flags:
      - HIDE_POTION_EFFECTS
    events:
      drink:
        execute_commands:
            cmd1:
              command: 'minecraft:tp {player} %player_bed_x% %player_bed_y% %player_bed_z%' #<--PAPI placeholders
              as_console: true
              delay: 20
```

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by PSYCHEER** [comment]
For better investigation please use latest build of your current version of Paper jar
Paper 1.21-130 at the moment
