### ISSUE TITLE
Could not pass event BlockBreakEvent to ItemsAdder v4.0.2-alpha-test-3 java.lang.ClassCastException: class ia.m.eH cannot be cast to class ia.m.eO (ia.m.eH and ia.m.eO are in unnamed module of loader 'ItemsAdder_4.0.2-alpha-test-3.jar' @ab27ad1)

### ISSUE THREAD

**Issue by Technofied** [PluginBugs/Issues-ItemsAdder#3875]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

technofied

### What happened?

A lot of spam in console appears when I have an item that can break multiple blocks.

### Steps to reproduce the issue

Have an item with the following options (on a pickaxe)
`multiple_break:
  keep_ores: true
  drop_all_blocks:
    enabled: true
    need_silk_touch: true
  size: 3
  depth: 3`

Try mining with it, observe the many errors.

### Server version

[14:27:40 INFO]: This server is running Paper version 1.21-127-master@4e6a2a1 (2024-08-07T12:50:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[14:27:51 INFO]: ItemsAdder version 4.0.2-alpha-test-3
[14:27:51 INFO]: Customized Minecraft without client mods!
[14:27:51 INFO]: Website: devs.beer
[14:27:51 INFO]: Author: LoneDev

### ProtocolLib Version

[14:27:58 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[14:27:58 INFO]: Provides read/write access to the Minecraft protocol.
[14:27:58 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:28:04 INFO]: LoneLibs version 1.0.56
[14:28:04 INFO]: Collection of libs used by my plugins
[14:28:04 INFO]: Authors: LoneDev and others

### Full server log

I don't think this is necessary, but let me know if it is.

### Error (optional)

```shell
[14:24:47 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.ClassCastException: class ia.m.eH cannot be cast to class ia.m.eO (ia.m.eH and ia.m.eO are in unnamed module of loader 'ItemsAdder_4.0.2-alpha-test-3.jar' @5ea64ebd)
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.eO.a(SourceFile:271) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.eO.a(SourceFile:237) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dG.a(SourceFile:174) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.es.b(SourceFile:288) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.dd.a(SourceFile:900) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.eH.b(SourceFile:584) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.nr.d(SourceFile:110) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.eH.a(SourceFile:583) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.es.b(SourceFile:287) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.di.a(SourceFile:174) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.di.f(SourceFile:523) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-127-4e6a2a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by Technofied** [comment]
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

I'm not comfortable sharing the full log file publicly, but I can provide exerpts from ItemsAdder loading to any error(s) you'd like

**Comment by Andre601** [comment]
There is no issues sharing the full log, especially when using mclo.gs as it censores sensitive data by default, such as IPs and full folder paths.

**Comment by Andre601** [comment]
We wouldn't ask for the full logs if they aren't of importance to us.

**Comment by Technofied** [comment]
> We wouldn't ask for the full logs if they aren't of importance to us.

https://mclo.gs/1XaWGpu
Reproduced on a fresh server with only an example item made in itemsadder.
