### ISSUE TITLE
Custom Item Drop Integration with MythicMobs Not Working

### ISSUE THREAD

**Issue by KeithR77** [PluginBugs/Issues-ItemsAdder#3879]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

It seems that the functionality of having custom Mythic Mobs drop ItemsAdder items upon death is not working with the most recent ItemsAdder_4.0.2-alpha-test-3.jar release. My console gives the following warnings/errors when I kill a mythic mob that has itemsadder items added onto it's drops within the mob configuration yml file:

```
[11:07:37 ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityDeathEvent
[11:07:37 WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[11:07:37 WARN]:        at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.core.drops.DropExecutor.handleEntityLootDrops(DropExecutor.java:297)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:423)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[11:07:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[11:07:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:07:37 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:07:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[11:07:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:07:37 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:992)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1878)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1781)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586)
[11:07:37 WARN]:        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:322)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.entity.EntityHandlerImpl.hurt(EntityHandlerImpl.java:307)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.api.entity.BukkitEntity.hurt(BukkitEntity.java:143)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.entity.hitbox.HitboxEntityImpl.hurt(HitboxEntityImpl.java:177)
[11:07:37 WARN]:        at net.minecraft.world.entity.player.Player.attack(Player.java:1344)
[11:07:37 WARN]:        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2417)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener$4.onAttack(PatchedServerGamePacketListener.java:266)
[11:07:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[11:07:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.dispatch(ServerboundInteractPacketWrapper.java:63)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener.handleInteract(PatchedServerGamePacketListener.java:173)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:45)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:15)
[11:07:37 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[11:07:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[11:07:37 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[11:07:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

The code for the custom mob appears as follows (and I ensured it matches exactly how it would be written based on the wiki page detailing how to add IA items to MythicMob drops):

```
iceboar:
  Type: husk
  Display: '&6Ice_Boar'
  Health: 30
  Damage: 1 
  Drops:
    - elitecreatures:20th_century_furniture_v1_bed 3 100%
    - elitecreatures:rpg_bundle_v19_item8 1 50%
  AIGoalSelectors:
  - 0 clear
  - 1 meleeattack
  - 2 randomstroll
  AITargetSelectors:
  - 0 clear
  - 1 players
  Modules:
    ThreatTable: true
  Options:
    AlwaysShowName: false
    PreventOtherDrops: true
    Silent: true
    FollowRange: 40
    PreventItemPickup: true
    PreventRandomEquipment: true
    MovementSpeed: 0.21
    KnockbackResistance: 1
    PreventJockeyMounts: true
  Skills:
  - model{mid=ice_boar} @self ~onSpawn
  - bodyclamp{m=ice_boar;c=20} @self ~onSpawn
  - CancelEvent{sync=true} @self ~onAttack
  - skill{s=Ice_boar_charge} @target ~onTimer:20
  - effect:sound{s=entity.ravager.hurt;v=1.3;p=0.8} @self ~onDamaged 0.7
  - effect:sound{s=entity.ravager.death;v=1.6;p=0.9} @self ~onDeath
  - effect:sound{s=block.fire.extinguish;v=0.6;p=0;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath ~onDeath
  - effect:particles{particle=reddust;color=#3cc7bb;amount=20;hs=0.4;vs=0.6;y=0.7;size=1;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath
  - effect:particles{particle=Snowflake;amount=15;hs=0.6;vs=0.4;y=0.6;size=1;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath
  - effect:sound{s=item.armor.equip_leather;v=2;p=1} @self ~onDamaged
```

### Steps to reproduce the issue

To reproduce the issue

1. Have a Mythic Mob setup, with the same IA drop mechanic as detailed in the [Wiki Page](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/mythicmobs).
2. Once this is setup, spawn the mob and then kill it
3. No IA items will drop, and the console will display the same warning/error messages as shown above

### Server version

This server is running Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

[Latest Log](https://mclo.gs/LNDdZ5H)

### Error (optional)

```shell
[11:07:37 ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityDeathEvent
[11:07:37 WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[11:07:37 WARN]:        at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.core.drops.DropExecutor.handleEntityLootDrops(DropExecutor.java:297)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:423)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[11:07:37 WARN]:        at MythicMobs-5.7.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[11:07:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84)
[11:07:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:07:37 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:07:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[11:07:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:07:37 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:992)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1878)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1781)
[11:07:37 WARN]:        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586)
[11:07:37 WARN]:        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:322)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.entity.EntityHandlerImpl.hurt(EntityHandlerImpl.java:307)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.api.entity.BukkitEntity.hurt(BukkitEntity.java:143)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.entity.hitbox.HitboxEntityImpl.hurt(HitboxEntityImpl.java:177)
[11:07:37 WARN]:        at net.minecraft.world.entity.player.Player.attack(Player.java:1344)
[11:07:37 WARN]:        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2417)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener$4.onAttack(PatchedServerGamePacketListener.java:266)
[11:07:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[11:07:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.dispatch(ServerboundInteractPacketWrapper.java:63)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener.handleInteract(PatchedServerGamePacketListener.java:173)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:45)
[11:07:37 WARN]:        at ModelEngine-4.0.7.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:15)
[11:07:37 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[11:07:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[11:07:37 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[11:07:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[11:07:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[11:07:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Problematic items yml configuration file (optional)

```shell
iceboar:
  Type: husk
  Display: '&6Ice_Boar'
  Health: 30
  Damage: 1 
  Drops:
    - elitecreatures:20th_century_furniture_v1_bed 3 100%
    - elitecreatures:rpg_bundle_v19_item8 1 50%
  AIGoalSelectors:
  - 0 clear
  - 1 meleeattack
  - 2 randomstroll
  AITargetSelectors:
  - 0 clear
  - 1 players
  Modules:
    ThreatTable: true
  Options:
    AlwaysShowName: false
    PreventOtherDrops: true
    Silent: true
    FollowRange: 40
    PreventItemPickup: true
    PreventRandomEquipment: true
    MovementSpeed: 0.21
    KnockbackResistance: 1
    PreventJockeyMounts: true
  Skills:
  - model{mid=ice_boar} @self ~onSpawn
  - bodyclamp{m=ice_boar;c=20} @self ~onSpawn
  - CancelEvent{sync=true} @self ~onAttack
  - skill{s=Ice_boar_charge} @target ~onTimer:20
  - effect:sound{s=entity.ravager.hurt;v=1.3;p=0.8} @self ~onDamaged 0.7
  - effect:sound{s=entity.ravager.death;v=1.6;p=0.9} @self ~onDeath
  - effect:sound{s=block.fire.extinguish;v=0.6;p=0;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath ~onDeath
  - effect:particles{particle=reddust;color=#3cc7bb;amount=20;hs=0.4;vs=0.6;y=0.7;size=1;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath
  - effect:particles{particle=Snowflake;amount=15;hs=0.6;vs=0.4;y=0.6;size=1;delay=113} @ModelPart{m=ice_boar;p=locator} ~onDeath
  - effect:sound{s=item.armor.equip_leather;v=2;p=1} @self ~onDamaged
```

**Comment by KeithR77** [comment]
Seems that a lot of other users have also reported issues with MythicMobs compatibility no longer working on the newest versions of IA. **(Referring to other currently open incidents: #4002 and #3915)**. It's been roughly 3 weeks now since the #3915 issue incident has been sitting in the 'future-updates' milestone, and over 6 weeks that my ticket has just been sitting here still open. I'm starting to get concerned that this issue is looking like it will be potentially unresolved for months at this rate. There's been 4 new IA releases since then, but none of them have provided a fix for this issue...really hoping you can take a look into this and that it can get resolved in the next update/release @LoneDev6

**Comment by Florenthz** [comment]
Hi Keith

**Comment by Florenthz** [comment]
@LoneDev6 Hi Lone, I have the same problem with MythicMobs, is there a date aprox for fix?
Greetings friend

**Comment by Andre601** [comment]
> [@]LoneDev6 Hi Lone, I have the same problem with MythicMobs, is there a date aprox for fix? Greetings friend

Please don't tag LoneDev for such stuff. Join the discord and try the latest Beta if you want to see if the issue is fixed.
And usually, there aren't and set dates for releases. It highly depends on how many other bugs there are that need fixing and how many people tested it, which is why we apreciate customers to try out the Betas.

**Comment by LoneDev6** [comment]
Did a quick search, can't find much examples, they are pretty outdated: https://github.com/xikage/MythicMobs-API-Examples
I should have fixed compatibility in the current update though.

**Comment by LoneDev6** [comment]
You can download the new beta on Discord, remember to verify your purchase and react on the beta channel to request access.

**Comment by Florenthz** [comment]
In which channel can I download betas? I only see stable releases

**Comment by Florenthz** [comment]
> You can download the new beta on Discord, remember to verify your purchase and react on the beta channel to request access.

In which channel can I download betas? I only see stable releases

**Comment by Andre601** [comment]
Like LoneDev mentioned would you first verify your account and that you're a customer. You do this in `#verify-account`
You then go to `#beta-access` and join the ItemsAdder Beta.

**Comment by Florenthz** [comment]
> Like LoneDev mentioned would you first verify your account and that you're a customer. You do this in `#verify-account` You then go to `#beta-access` and join the ItemsAdder Beta.

OH thanks a lot friend :D
Greetings
