### ISSUE TITLE
Plugin doesnt Load

### ISSUE THREAD

**Issue by suchtiboy** [PluginBugs/Issues-ItemsAdder#3880]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

suchhtiboyreal

### What happened?

The ItemsAdder plugin doesn't load on my Paper 1.20.2 server. I first used version 3.6.4_5, which didn't work either, then I used version 4.0.1, which didn't work either. I only have ModelEngine, ItemsAdder, ProtocolLib and LoneLib on the server. If I select No Host, the plugin loads fine, but if I use something else, it doesn't work. I can't use a self-host because I can't create a port. I tried Google Drive and LobFile, but that didn't work either. I followed all the steps in the wiki and even watched tutorials. But nothing works. I hope someone can help me.

### Steps to reproduce the issue

The problem arises when I select a host other than No Host.

### Server version

This server is running Paper version git-Paper-245 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 90fe0d5)
You are 73 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

ItemsAdder Version 3.6.4

### ProtocolLib Version

Protocol Lib Version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLib Version 1.0.56

### Full server log

[18:01:10] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.4 (Is it up to date?)
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.addListener(PacketListenerSet.java:48) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:313) ~[ProtocolLib.jar:?]
	at ia.m.ms.a(SourceFile:220) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.qa.register(SourceFile:164) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.qf.<init>(SourceFile:83) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.a(SourceFile:515) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.<init>(SourceFile:276) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.a(SourceFile:295) ~[ItemsAdder_3.6.4_5.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:418) ~[ItemsAdder_3.6.4_5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-245]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-245]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-245]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-245]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:01:10] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.4

### Error (optional)

```shell
[18:01:10] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.6.4 (Is it up to date?)
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.addListener(PacketListenerSet.java:48) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:313) ~[ProtocolLib.jar:?]
	at ia.m.ms.a(SourceFile:220) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.qa.register(SourceFile:164) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.qf.<init>(SourceFile:83) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.a(SourceFile:515) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.<init>(SourceFile:276) ~[ItemsAdder_3.6.4_5.jar:?]
	at ia.m.G.a(SourceFile:295) ~[ItemsAdder_3.6.4_5.jar:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:418) ~[ItemsAdder_3.6.4_5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-245]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-245]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-245]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-245]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-245]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:01:10] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.4
```

### Problematic items yml configuration file (optional)

```shell
I dont add Items
```

### Screenshots/Videos (you can drag and drop files or paste links)

<img width="1076" alt="Bildschirmfoto 2024-08-09 um 20 04 22" src="https://github.com/user-attachments/assets/655de85c-c900-4d87-bb3b-0e076c5bbe07">
<img width="1076" alt="Bildschirmfoto 2024-08-09 um 20 04 01" src="https://github.com/user-attachments/assets/fb2219b9-ba9c-4193-a6c8-2d12311d6359">

**Comment by Andre601** [comment]
1. Please provide your complete latest.log through https://mclo.gs
2. Actually use the **latest v3 Release** of ItemsAdder (3.6.4-release-3)
3. Update your server to 1.20.4. There is no reason to be on 1.20.2 at all.
4. Use the ProtocolLib version recommended for pre 1.20.5, which should be latest stable 5.2.0 Build from their jenkins or GitHub.
