### ISSUE TITLE
ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack

### ISSUE THREAD

**Issue by ri1ongithub** [PluginBugs/Issues-ItemsAdder#3883]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ri1_

### What happened?

When I try to convert a CustomStack to a normal ItemStack I get this error.

(This was working fine in 1.20.6)

### Steps to reproduce the issue

1. Create a plugin in 1.21 using Purpur and itemsadder's api
2. Try to convert a custom stack to a normal item stack (CustomStack.getInstance("mynamespace:myitem").getItemStack()

### Server version

Purpur Version: 1.21-2281-7950960 (MC: 1.21)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-720

### LoneLibs Version

1.0.56

### Full server log

```
[WARN]: [MyPlugin] Task #96 for MyPlugin v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack
	at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:73) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventory.addItem(CraftInventory.java:327) ~[purpur-1.21.jar:1.21-2281-7950960]
	at MyPlugin-1.0-SNAPSHOT-all.jar/my.package.MyClass$1.run(MyClass.java:160) ~[MyPlugin-1.0-SNAPSHOT-all.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2281-7950960]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Error (optional)

```shell
[WARN]: [MyPlugin] Task #96 for MyPlugin v1.0-SNAPSHOT generated an exception
java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack
	at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:73) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.inventory.CraftInventory.addItem(CraftInventory.java:327) ~[purpur-1.21.jar:1.21-2281-7950960]
	at MyPlugin-1.0-SNAPSHOT-all.jar/my.package.MyClass$1.run(MyClass.java:160) ~[MyPlugin-1.0-SNAPSHOT-all.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2281-7950960]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2281-7950960]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2281-7950960]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: mynamespace
items:
  myitem:
    display_name: "My Display Name"
    lore:
      - ""
      - "§r§fMy Lore"
      - ""
    resource:
      generate: true
      material: PAPER
      textures:
        - "mytexture"
```

**Comment by Andre601** [comment]
How exactly are you trying to convert the custom stack to an item stack?
Please provide actual code examples should you use the API.

**Comment by ri1ongithub** [comment]
```CustomStack.getInstance("mynamespace:myitem").getItemStack()```, like in the documentation.

**Comment by ri1ongithub** [comment]
```java
CustomStack stack = CustomStack.getInstance("your_item")
if(stack != null)
{
    ItemStack itemStack = stack.getItemStack();
}
else
{
    //no custom item found with that id
}
```
https://itemsadder.devs.beer/developers/java-api/examples

**Comment by Andre601** [comment]
May be related to https://github.com/PluginBugs/Issues-ItemsAdder/issues/3857, tho I cannot say for sure.
We have to wait for LoneDev to come back from his vacation to check this.

**Comment by Andre601** [comment]
Actually, your issue is similar to #3825 so I'll close this issue. Make sure to follow the other one to get notified about any updates.

**Comment by MathiasDPX** [comment]
Hello, We (me and ri1) are working on the same plugin and have the same error,
Here is my code: https://github.com/MathiasDPX/PluginOpenMC/blob/main/src/main/java/fr/communaywen/core/dreamdim/fishing/loot_table/fish/MoonFish.java#L10, I hope it can help you

PS: It's have the same problem everywhere I use CustomStack.getInstance

**Comment by LoneDev6** [comment]
Very strange, if you have Discord please send her eyour tag, join my Discord server to join the beta testing team so that I can send you a JAR with a fix.

**Comment by ri1ongithub** [comment]
I'm already on your discord, my tag is "ri1_"
