### ISSUE TITLE
Error on iazip and iatexture

### ISSUE THREAD

**Issue by gamehub224** [PluginBugs/Issues-ItemsAdder#3886]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Using IAZip and IATexture commands throws an error. The pack still gets applied, but the player does not get locked in place.

### Steps to reproduce the issue

1. Have IA 4.0.2 alpha 3 and all its dependencies.
2. After logging in, do iazip and/or iatexture

### Server version

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
* You are running the latest version
Previous: git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full server log

https://mclo.gs/Xj7puHA

### Error (optional)

```shell
[17:54:28 ERROR]: [ItemsAdder] Failed to lock player movements.
[17:54:28 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mg.nz(SourceFile:67) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mf.by(SourceFile:118) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lX.a(SourceFile:255) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:252) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1624) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Duplicate of #3854

**Check the issue tracker for existing issues before submitting one!**
