### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#3903]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Plugin don't start on 1.21.1

### Steps to reproduce the issue

not necessary

### Server version

[13:28:41 INFO]: This server is running Paper version 1.21.1-38-master@e4b38b4 (2024-08-19T10:54:40Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-34-b4bc512 (MC: 1.21.1)

### ItemsAdder Version

[13:29:10 INFO]: ItemsAdder version 4.0.2-alpha-test-3
[13:29:10 INFO]: Customized Minecraft without client mods!
[13:29:10 INFO]: Website: devs.beer
[13:29:10 INFO]: Author: LoneDev

### ProtocolLib Version

[13:29:01 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[13:29:01 INFO]: Provides read/write access to the Minecraft protocol.
[13:29:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[13:29:19 INFO]: LoneLibs version 1.0.56
[13:29:19 INFO]: Collection of libs used by my plugins
[13:29:19 INFO]: Authors: LoneDev and others

### Full Server Log

//

### Error (optional)

```shell
[13:26:28] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v4.0.2-alpha-test-3
[13:26:28] [Server thread/ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_4.0.2-alpha-test-3.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.NullPointerException: Cannot read field "protocol" because the return value of "lonelibs.dev.lone.fastnbt.nms.Version.get()" is null
	at LoneLibs.jar/lonelibs.dev.lone.fastnbt.nms.Version.isOlderThan(Version.java:87) ~[LoneLibs.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.Q.Q(SourceFile:450) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/dev.lone.itemsadder.Main.iU(SourceFile:542) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/dev.lone.itemsadder.Main.onLoad(SourceFile:176) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-38-e4b38b4]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Andre601** [comment]
Filing a bug report for this is not required. LoneDev will make an update once he's back working at IA and finds the time for it.
