### ISSUE TITLE
Damage cannot be negative

### ISSUE THREAD

**Issue by astridcloud** [PluginBugs/Issues-ItemsAdder#3904]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

hanasensei

### What happened?

Before, I used the stable version of ItemAdders, but now I switched to the alpha test version for Minecraft 1.21, and it shows an error: 'Damage cannot be negative.' The stable version didn't have this issue but doesn't support 1.21.

### Steps to reproduce the issue

Update to Alpha Test Version
And add durability unbreakable for any item

### Server version

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full Server Log

https://mclo.gs/j6mYJVS

### Error (optional)

```
[22:06:18] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[22:06:18] [Server thread/WARN]: java.lang.IllegalArgumentException: Damage cannot be negative
[22:06:18] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1634)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.nd.d(SourceFile:366)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.eO.setDurability(SourceFile:55)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.eO.<init>(SourceFile:36)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.fl.hL(SourceFile:203)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.b(SourceFile:769)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.c(SourceFile:625)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.nr.d(SourceFile:110)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.a(SourceFile:619)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.<init>(SourceFile:274)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.a(SourceFile:294)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:374)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[22:06:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[22:06:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[22:06:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: noraset
armors_rendering:
  noraarmor:
    color: '#ab2eff'
    layer_1: armor/nora_armor_layer_1
    layer_2: armor/nora_armor_layer_2
    use_color: false
items:
  norachestplate:
    display_name: Nora Chestplate
    permission: simple
    executableitem:
      id: itemadder_set     
    durability:
      unbreakable: true
    attribute_modifiers:
      chest: 
        armor: 6
        armorToughness: 3
        attackKnockback: 1.1
    resource:
      generate: true
      model_id: 50520
      textures:
      - armor/nora_chestplate_icon.png
    specific_properties:
      armor:
        slot: chest
        custom_armor: noraarmor
  noraleggings:
    display_name: Nora Leggings
    permission: simple
    executableitem:
      id: itemadder_set     
    durability:
      unbreakable: true    
    attribute_modifiers:
      legs: 
        armor: 6
        armorToughness: 3
        attackKnockback: 1.1
    resource:
      generate: true
      model_id: 50521
      textures:
      - armor/nora_leggings_icon.png
    specific_properties:
      armor:
        slot: legs
        custom_armor: noraarmor
  noraboots:
    display_name: Nora Boots
    permission: simple
    executableitem:
      id: itemadder_set     
    durability:
      unbreakable: true    
    attribute_modifiers:
      feet: 
        armor: 6
        armorToughness: 3
        attackKnockback: 1.1
    resource:
      generate: true
      model_id: 50522
      textures:
      - armor/nora_boots_icon.png
    specific_properties:
      armor:
        slot: feet
        custom_armor: noraarmor
```

### Screenshots/Videos (you can drag and drop files or paste links)

_No response_[22:06:18] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[22:06:18] [Server thread/WARN]: java.lang.IllegalArgumentException: Damage cannot be negative
[22:06:18] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1634)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.nd.d(SourceFile:366)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.eO.setDurability(SourceFile:55)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.eO.<init>(SourceFile:36)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.fl.hL(SourceFile:203)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.b(SourceFile:769)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.c(SourceFile:625)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.nr.d(SourceFile:110)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.a(SourceFile:619)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.<init>(SourceFile:274)
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//ia.m.G.a(SourceFile:2[94](https://mclo.gs/j6mYJVS#L94))
[22:06:18] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-3.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:374)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[22:06:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[22:06:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[22:06:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[22:06:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[22:06:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LoneDev6** [comment]
Can't reproduce the issue using your config on 1.21.1 and ItemsAdder 4.0.2-alpha-test-4 (upcoming version).
So it probably was fixed during development.
