### ISSUE TITLE
Invalid Server Response; Pack loading

### ISSUE THREAD

**Issue by debugtarget** [PluginBugs/Issues-ItemsAdder#3912]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

.debugtarget

### What happened?

After a server restart Itemsadder is suddenly no longer able to load the texture pack, the download fails.

The configuration was changed prior to a restart, but that configuration was functional up until the time of the restart. Reverting the change has not solved the issue.

**Server Version**
Paper 1.20.4

**Plugin Version**
ItemsAdder_3.6.4-release-3

**Details**
The console returns the error `Failed to upload resourcepack, invalid server response.` when running `/iazip`.
In console the pack URL is show as `[ItemsAdder] Pack URL is null.`
When running `/iainfo` the correct pack URL is shown, that being `https://lobfile.com/file/FmNnSLzg.zip`.
A zip file is created in `ItemsAdder/output` when `/iazip` is run, the file name is "generated.zip".
We are using lobfile as the pack host.
We have already tried to remove ALL configuration files and textures and starting entirely from new with an empty namespace.
The discord server's support was not able to solve the issue and instructed us to open a Github Issue.
I have attached the hosting configuration.
![image](https://github.com/user-attachments/assets/2b51c27a-b069-4c64-9c72-6ed9c6685794)

### Steps to reproduce the issue

I have not been able to recreate the issue in small scale testing.

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version
Previous version: git-Pufferfish-49 (MC: 1.20.4)

### ItemsAdder Version

[16:01:00 INFO]: ItemsAdder version 3.6.4-release-3
[16:01:00 INFO]: Customized Minecraft without client mods!
[16:01:00 INFO]: Website: devs.beer
[16:01:00 INFO]: Author: LoneDev

### ProtocolLib Version

[16:01:19 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[16:01:19 INFO]: Provides read/write access to the Minecraft protocol.
[16:01:19 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:02:01 INFO]: LoneLibs version 1.0.56
[16:02:01 INFO]: Collection of libs used by my plugins
[16:02:01 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/FPJ1KY2

### Error (optional)

```shell
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Failed to upload resourcepack, invalid server response.
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.qS.a(SourceFile:125)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.qS.a(SourceFile:67)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.qH.az(SourceFile:288)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.qH.au(SourceFile:139)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.G.a(SourceFile:1207)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at ItemsAdder_3.6.4-release-3.jar//ia.m.qd.a(SourceFile:471)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/INFO]: [ItemsAdder] Pack URL is null.
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Compressed in 2099ms
[14:47:15] [Craft Scheduler Thread - 16 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (lobfile). URL: https://lobfile.com/file/FmNnSLzg.zip
```

### Other files, you can drag and drop them here to upload. (optional)

[Client-log-error.txt](https://github.com/user-attachments/files/16714655/Client-log-error.txt)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/eb0c0c5f-5652-446d-b24b-56a3ed74089f)

**Comment by debugtarget** [comment]
### Solution found, cause unknown
The issue was fixed by reinstalling all of Itemsadder.

First the .jar file and the plugins directory were deleted entirely (a full backup was made prior to this).
The plugin was reinstalled in default state and the lobfile setup was followed, here a entirely new lobfile account was used and the old resourcepack (downloaded as a .zip) was uploaded to this account prior to plugin configuration. Note that prior attempts of reinstalls did not work until the new account was setup and the pack was uploaded.
The lobfile setup was then completed as described, after this the namespaces could imported one by one and the config was changed BY HAND.

**Comment by debugtarget** [comment]
> ### Solution found, cause unknown
> The issue was fixed by reinstalling all of Itemsadder.
> 
> First the .jar file and the plugins directory were deleted entirely (a full backup was made prior to this). The plugin was reinstalled in default state and the lobfile setup was followed, here a entirely new lobfile account was used and the old resourcepack (downloaded as a .zip) was uploaded to this account prior to plugin configuration. Note that prior attempts of reinstalls did not work until the new account was setup and the pack was uploaded. The lobfile setup was then completed as described, after this the namespaces could imported one by one and the config was changed BY HAND.

Reference this for closing reason

**Comment by Andre601** [comment]
The issue was a malformed JSON file, maybe partially caused by using invalid name formats (uppercase letters, literal zip files inside the RP), as was reported by ItemsAdder itself:
> [14:47:12] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Malformed JSON resource pack/assets/minecraft/models/item/shield.json
> [14:47:12] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Index 0 out of bounds for length 0
> ...
> [14:47:13] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Invalid character in folders/name of file: resourcepack/assets/minecraft/textures/entity/fox/archive-2024-07-13T173935Z.tar.gz
> [14:47:13] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Invalid character in folders/name of file: resourcepack/assets/minecraft/lang/en_usOLD.json

**Comment by debugtarget** [comment]
> The issue was a malformed JSON file, maybe partially caused by using invalid name formats (uppercase letters, literal zip files inside the RP), as was reported by ItemsAdder itself:
> 
> > [14:47:12] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Malformed JSON resource pack/assets/minecraft/models/item/shield.json
> > [14:47:12] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Index 0 out of bounds for length 0
> > ...
> > [14:47:13] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Invalid character in folders/name of file: resourcepack/assets/minecraft/textures/entity/fox/archive-2024-07-13T173935Z.tar.gz
> > [14:47:13] [Craft Scheduler Thread - 16 - ItemsAdder/ERROR]: [ItemsAdder] Invalid character in folders/name of file: resourcepack/assets/minecraft/lang/en_usOLD.json
> 
> And for the next time, test it on an isolated environment with just IA itself.

Thank you for your reply. While these JSONs being the source of the issue had crossed my mind, removing them never ended up solving my issues. These are archived files that were no longer in use and had been in this malformed state quite some time before the pack stopped loading, they are also still around in the currently functional pack, though I may remove them as we have no more use for those.

Unfortunately fully isolated testing wasn't possible this time as I only have so many test environments available to me, resetting the dev environment was not in question and my private test server was running a different server configuration at the time.
