### ISSUE TITLE
Problems with textures and models with MMOCore / MMOItems in version 1.21

### ISSUE THREAD

**Issue by Karuho** [PluginBugs/Issues-ItemsAdder#3914]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

karuho.

### What happened?

The textures of the MMOCore skill icons are not seen, only the material appears (example: coal), some skills or mobs are not seen either and they disappear when changing worlds, or when using a skill, and reappear with a death or never again, is very relative. It worked correctly in the stable version, but not with the alpha version.

### Steps to reproduce the issue

1. Upload all the texture files and configurations of the skill and class in the corresponding folders (MMOCore, MMOItems, MythicLibs, MythicMobs, ModelEngine, ItemsAdder)
2. Reload all plugins, and finally reload ItemsAdder with the /iareload command
3. Use the /iazip command
4. Loads the resource packs but with an error in the console and does not show some textures in the skills list or when executing them

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-148-20f5165 (MC: 1.20.6)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full Server Log

https://mclo.gs/rzZIKKj

### Error (optional)

```shell
[02:03:37 INFO]: [ItemsAdder]  
[02:03:37 INFO]: [ItemsAdder]  
[02:03:37 INFO]: [ItemsAdder] [Pack] Saved into /container/plugins/ItemsAdder/output/generated.zip
[02:03:37 INFO]: [ItemsAdder] [Pack] Compressed in 1788ms
[02:03:37 INFO]: [ItemsAdder] [Pack] Resourcepack URL (self-host): http://104.224.55.138:8123/generated.zip
[02:03:37 INFO]: [ItemsAdder] [Pack] Applying to every player... 
[02:03:37 INFO]: [ItemsAdder] [Pack] Applied to 2 players
[02:03:37 ERROR]: [ItemsAdder] Failed to lock player movements.
[02:03:37 ERROR]: [ItemsAdder] Failed to lock player movements.
[02:03:38 WARN]: [ItemsAdder] Task #753543 for ItemsAdder v4.0.2-alpha-test-3 generated an exception
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.kB.a(SourceFile:158) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.kH.a(SourceFile:101) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ky.a(SourceFile:279) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.a(SourceFile:175) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aS(SourceFile:169) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aT(SourceFile:162) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:03:40 WARN]: [ItemsAdder] Task #753568 for ItemsAdder v4.0.2-alpha-test-3 generated an exception
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.kB.a(SourceFile:158) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.kH.a(SourceFile:101) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.ky.a(SourceFile:279) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.a(SourceFile:175) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aS(SourceFile:169) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aT(SourceFile:162) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:03:42 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mg.nz(SourceFile:67) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mf.by(SourceFile:118) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lX.a(SourceFile:255) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor763.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:233) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:03:48 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.NoSuchFieldError: Class net.minecraft.world.entity.Entity does not have member field 'net.minecraft.server.level.ChunkMap$TrackedEntity tracker'
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.a(SourceFile:147) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.km.b(SourceFile:39) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.jG.c(SourceFile:334) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.iR.aQ(SourceFile:112) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mg.nz(SourceFile:67) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.mf.by(SourceFile:118) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.lX.a(SourceFile:255) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor763.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleResourcePackResponse(ServerCommonPacketListenerImpl.java:233) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:15) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![coal](https://github.com/user-attachments/assets/dbd98081-d081-43ed-956e-2e3bff8d8432)
![guardian-defense skill](https://github.com/user-attachments/assets/1c82245b-90e1-4c09-a40a-62e9ae5b765f)
![with guardian](https://github.com/user-attachments/assets/637e8760-cd13-486e-833a-e21d365de8d4)
![without guardian](https://github.com/user-attachments/assets/83fbcb08-3293-49f7-8728-472a7b8dd775)

**Comment by dinobossytnew** [comment]
I confirm the error <3let's wait for it to be repaired by our lonedev

**Comment by SMHenrry** [comment]
This is more related to a MMOCore/items/lib bug that was resolved in the latest builds, I have tested it in the most recent version and it works perfectly with ItemsAdder

![image](https://github.com/user-attachments/assets/189d1b30-e867-4a76-940e-d696f9ba71d3)
