### ISSUE TITLE
Advanced enchant not compat with latest beta IA

### ISSUE THREAD

**Issue by spookymgmt** [PluginBugs/Issues-ItemsAdder#3921]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

dr.lunar

### What happened?

[03:57:52 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.advancedplugins.ae.enchanthandler.enchantments.AEnchants
[03:57:52 WARN]:        at AdvancedEnchantments-9.10.7.jar//net.advancedplugins.ae.api.AEAPI.isAnEnchantment(AEAPI.java:422)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//dev.lone.itemsadder.Core.OtherPlugins.enchants.AeWrapper.isCustomEnchant(SourceFile:53)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.fl.hL(SourceFile:905)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.b(SourceFile:769)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.c(SourceFile:625)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.nY.d(SourceFile:129)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.a(SourceFile:619)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.ic.b(SourceFile:80)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.ic.onCommand(SourceFile:55)
[03:57:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[03:57:52 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[03:57:52 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[03:57:52 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[03:57:52 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[03:57:52 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[03:57:52 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[03:57:52 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[03:57:52 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[03:57:52 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[03:57:52 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[03:57:52 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[03:57:52 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2219)
[03:57:52 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2193)
[03:57:52 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[03:57:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[03:57:52 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1559)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:203)
[03:57:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1536)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1529)
[03:57:52 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1488)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1495)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1340)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[03:57:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[03:57:52 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
[03:57:52 WARN]:        at AdvancedEnchantments-9.10.7.jar//net.advancedplugins.ae.enchanthandler.enchantments.AEnchants.<clinit>(AEnchants.java:30)
[03:57:52 WARN]:        at AdvancedEnchantments-9.10.7.jar//net.advancedplugins.ae.api.AEAPI.isAnEnchantment(AEAPI.java:422)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//dev.lone.itemsadder.Core.OtherPlugins.enchants.AeWrapper.isCustomEnchant(SourceFile:53)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.fl.hL(SourceFile:905)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.b(SourceFile:769)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.c(SourceFile:625)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.nY.d(SourceFile:129)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.a(SourceFile:619)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.<init>(SourceFile:274)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//ia.m.G.a(SourceFile:294)
[03:57:52 WARN]:        at ItemsAdder_4.0.2-alpha-test-4-pre-release-2.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:376)
[03:57:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[03:57:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[03:57:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[03:57:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[03:57:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:662)
[03:57:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:611)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520)
[03:57:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338)
[03:57:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1223)
[03:57:52 WARN]:        ... 2 more
>

### Steps to reproduce the issue

Use latest IA + AE on 1.21.1

### Server version

1.21.1 version

### ItemsAdder Version

4.0.2 alpha 4 pre 2

### ProtocolLib Version

726 version

### LoneLibs Version

1.0.57 version

### Full Server Log

aaa

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

Also, you are clearly not using latest IA version available. Please make sure of that before opening an issue, as you agree to have checked this.

**Comment by Andre601** [comment]
On another note, there is no 1.0.57 of LoneLibs, so please stop lyeing to us here.

**Comment by spookymgmt** [comment]
> On another note, there is no 1.0.57 of LoneLibs, so please stop lyeing to us here.
Could you just like, refrain from posting on my issues.

![UoVgXhLBhr](https://github.com/user-attachments/assets/ea132070-37b4-4cce-b735-7b05c6992620)

**Comment by spookymgmt** [comment]
@Andre601 Stop commenting on my issues

**Comment by spookymgmt** [comment]
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.
> 
> Also, you are clearly not using latest IA version available. Please make sure of that before opening an issue, as you agree to have checked this.

It's a beta version, I'm not sharing my log, error is in main post.

**Comment by Andre601** [comment]
> It's a beta version, I'm not sharing my log, error is in main post.

Then you won't receive any support, as logs are necessary to get important context that otherwise is missing.
Also, you had [no issues sharing logs last time](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3893#issuecomment-2293691491).

> @Andre601 Stop commenting on my issues

Well, it's sorta my job here, as I'm a support member for LoneDev, so I have to reply to issues here.
If you dislike this, block me. I certainly don't care. But don't tell me how I have to do my job here.

**Comment by spookymgmt** [comment]
> > It's a beta version, I'm not sharing my log, error is in main post.
> 
> Then you won't receive any support, as logs are necessary to get important context that otherwise is missing. Also, you had [no issues sharing logs last time](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3893#issuecomment-2293691491).
> 
> > @Andre601 Stop commenting on my issues
> 
> Well, it's sorta my job here, as I'm a support member for LoneDev, so I have to reply to issues here. If you dislike this, block me. I certainly don't care. But don't tell me how I have to do my job here.

That's fine, lone told me to make an issue so I'm just doing my job.

**Comment by LoneDev6** [comment]
Will be worked on today, thanks for the report!

**Comment by LoneDev6** [comment]
This is caused by AdvancedEnchantments-9.10.8 which has ItemsAdder in its softdepend list.
I'm working on a workaround.
