### ISSUE TITLE
Shader 1.21.1 issue

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#3930]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Rickylachow

### What happened?

Texture can't load, and after reviewing the client logs i have found an error, i'm using MythicHud plugin version: 1.1.0

### Steps to reproduce the issue

i don't know how to reproduce this issue

### Server version

[20:05:01 INFO]: Checking version, please wait...
[20:05:02 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-51-789a267 (MC: 1.21.1)

### ItemsAdder Version

[20:04:54 INFO]: ItemsAdder version 4.0.2-alpha-test-7
[20:04:54 INFO]: Customized Minecraft without client mods!
[20:04:54 INFO]: Website: devs.beer
[20:04:54 INFO]: Author: LoneDev

### ProtocolLib Version

[20:04:45 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[20:04:45 INFO]: Provides read/write access to the Minecraft protocol.
[20:04:45 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:04:35 INFO]: LoneLibs version 1.0.57
[20:04:35 INFO]: Collection of libs used by my plugins
[20:04:35 INFO]: Authors: LoneDev and others

### Full Server Log

no server logs only client logs

### Error (optional)

```shell
22:02:52.096
gfn
Render thread
Shader rendertype_entity_translucent could not find uniform named FogShape in the specified shader program.
22:02:52.098
gfn
Render thread
Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
22:02:52.143
fgo
Render thread
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at auk.a(SourceFile:69)
	at bph.d(SourceFile:162)
	at bpl.d(SourceFile:23)
	at bph.B(SourceFile:136)
	at bph.bB(SourceFile:121)
	at fgo.c(SourceFile:1240)
	at fgo.f(SourceFile:882)
	at net.minecraft.client.main.Main.main(SourceFile:256)
Caused by: java.lang.RuntimeException: could not reload shaders
	at ges.c(SourceFile:537)
	at ges$1.a(SourceFile:419)
	at ges$1.a(SourceFile:396)
	at auj.a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 9 more
Caused by: aku: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (server/0000000B/d69238f2-b7ce-30b0-8262-17cd9490f29d, rendertype_text) : ERROR: 0:36: No matching function for call to fog_distance(mat4, vec3, int)
	at aku.a(SourceFile:48)
	at gfn.<init>(SourceFile:172)
	at ges.c(SourceFile:516)
	... 13 more
Caused by: java.io.IOException: Couldn't compile vertex program (server/0000000B/d69238f2-b7ce-30b0-8262-17cd9490f29d, rendertype_text) : ERROR: 0:36: No matching function for call to fog_distance(mat4, vec3, int)
	at faw.b(SourceFile:69)
	at faw.a(SourceFile:51)
	at gfn.a(SourceFile:210)
	at gfn.<init>(SourceFile:157)
	... 14 more
```

**Comment by RickyLaChow** [comment]
Seems MythicHud issue
