### ISSUE TITLE
1.21 loading error with ae

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3944]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

trying to update my server i getting errors and can make IA works, i see an error with AvancedEnchantments.

### Steps to reproduce the issue

trying to update my server

### Server version

Pufferfish 1.21.1 #13

### ItemsAdder Version

4.0.2-alpha-test-7

### ProtocolLib Version

[12:19:21 INFO]: ProtocolLib v5.3.0-SNAPSHOT-726
[12:19:21 INFO]: Authors: dmulloy2 and Comphenix
[12:19:21 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues

### LoneLibs Version

1.0.57

### Full Server Log

i cant upload to this site im blocked

### Error (optional)

```shell
[12:03:51] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.2-alpha-test-7
[12:03:53] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 4.0.2-alpha-test-7
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.57
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Pufferfish 1.21.1-13-c789f72 (MC: 1.21.1)
                                               
[12:03:53] [Server thread/WARN]: [ItemsAdder]  
[12:03:53] [Server thread/WARN]: [ItemsAdder] This is a test version of ItemsAdder v4 for Minecraft 1.20.6 and 1.21.
[12:03:53] [Server thread/WARN]: [ItemsAdder] Please make backups before using this version.
[12:03:53] [Server thread/WARN]: [ItemsAdder] Use this only on a test server.
[12:03:53] [Server thread/WARN]: [ItemsAdder] I am not responsible for any damage done to your server.
[12:03:53] [Server thread/WARN]: [ItemsAdder]  
[12:03:53] [Server thread/INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[12:03:55] [Server thread/INFO]: [ItemsAdder] [Pack] Done extracting internal contents from .jar
[12:03:55] [Server thread/WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'assets/minecraft/textures/item/scute.png' doesn't exists. File: /contents/mcemojis/configs/emoji_images.yml
[12:03:57] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[12:03:57] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[12:03:57] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.8.jar//net.advancedplugins.ae.api.AEAPI.isAnEnchantment(AEAPI.java:422)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//dev.lone.itemsadder.Core.OtherPlugins.enchants.AeWrapper.isCustomEnchant(SourceFile:53)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.fl.hL(SourceFile:900)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.G.b(SourceFile:773)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.G.c(SourceFile:628)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.nW.d(SourceFile:129)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.G.a(SourceFile:622)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.G.<init>(SourceFile:277)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//ia.m.G.a(SourceFile:297)
[12:03:57] [Server thread/WARN]: 	at ItemsAdder_4.0.2-alpha-test-7.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:387)
[12:03:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[12:03:57] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[12:03:57] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[12:03:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[12:03:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[12:03:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[12:03:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755)
[12:03:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517)
[12:03:57] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331)
[12:03:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
[12:03:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[12:03:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:03:57] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.TriggerHandler.getTriggers()" because the return value of "net.advancedplugins.ae.impl.effects.effects.EffectsHandler.getTriggerHandler()" is null
[12:03:57] [Server thread/WARN]: 	at AdvancedEnchantments-9.10.8.jar//net.advancedplugins.ae.enchanthandler.enchantments.AEnchants.<clinit>(AEnchants.java:30)
[12:03:57] [Server thread/WARN]: 	... 22 more
```

### Other files, you can drag and drop them here to upload. (optional)

[latest.log](https://github.com/user-attachments/files/16798984/latest.log)

**Comment by SliderKP** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3921
