### ISSUE TITLE
Console spam "Could not pass event EntityDamageByBlockEvent to ItemsAdder v4.0.2-alpha-test-7"

### ISSUE THREAD

**Issue by SlyGuy89** [PluginBugs/Issues-ItemsAdder#3945]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

nanashi0498

### What happened?

Console getting spammed with the following error:

```
Could not pass event EntityDamageEvent to ItemsAdder v4.0.2-alpha-test-7
29.08 13:40:25 [Server] INFO java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
29.08 13:40:25 [Server] INFO at ItemsAdder_4.0.2-alpha-test-7.jar/ia.m.bX.a(SourceFile:136) ~[ItemsAdder_4.0.2-alpha-test-7.jar:?]
29.08 13:40:25 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
29.08 13:40:25 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
29.08 13:40:25 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1189) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.callNonLivingEntityDamageEvent(CraftEventFactory.java:1266) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at org.bukkit.craftbukkit.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1270) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.entity.decoration.ArmorStand.hurt(ArmorStand.java:503) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:453) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:848) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3132) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.entity.decoration.ArmorStand.tick(ArmorStand.java:702) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-35-be1078f]
29.08 13:40:25 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
29.08 13:40:25 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
29.08 13:40:25 [Server] INFO ... 29 more
```

Also should be noted my Resource pack isn't loading, although I don't know if this error is related. I've seen similar errors reported but not sure if I'm overlapping with a previously reported issue or not...

### Steps to reproduce the issue

Happens at all times while server is running, no other known conditions to reproduce.

### Server version

This server is running Paper version 1.21.1-35-master@be1078f (2024-08-18T22:41:36Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 17 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-129-4d7cef3 (MC: 1.21)

### ItemsAdder Version

4.0.2-alpha-test-7

### ProtocolLib Version

Protocollib v5.3.0-SNAPSHOT-726

### LoneLibs Version

Lonelibs 1.0.57

### Full Server Log

https://mclo.gs/LHm83fW

**Comment by Andre601** [comment]
The error reports a class ItemsAdder tries to access, which seems to not be there. Given the provided path, this seems to be a compat issue with another plugin (A disguise plugin by the looks of it).

**Comment by SlyGuy89** [comment]
As it turns out LibsDisguises did indeed have a Dev version update available that has resolved this error.

Thank you! I'll keep working on learning how to interpret stacktraces to hopefully save some time in the future!
