### ISSUE TITLE
Can't break blocks in survival + corrupted datas

### ISSUE THREAD

**Issue by CarraGrive** [PluginBugs/Issues-ItemsAdder#3970]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

carragrive

### What happened?

after the recent update (4.0.2-beta-release-9) it is impossible to break any blocks in survival
itemsadder will spam error in the console such as corrupted data and missing events

### Steps to reproduce the issue

install itemsadder
get yourself in survival
try to break a block

### Server version

This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

4.0.2-beta-release-9

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/Lybukqq

### Error (optional)

```shell
[02:35:10] [Server thread/ERROR]: [ItemsAdder] Corrupted region data! Copying it into '_corrupted' folder. 
[02:35:10] [Server thread/WARN]: java.lang.NoClassDefFoundError: io/protostuff/Message
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023)
[02:35:10] [Server thread/WARN]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cY.fO(SourceFile:78)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.da.<init>(SourceFile:87)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:123)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:117)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.G.b(SourceFile:1755)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.G.a(SourceFile:1422)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cq.a(SourceFile:247)
[02:35:10] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[02:35:10] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:35:10] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:35:10] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.gameevent.GameEventDispatcher.post(GameEventDispatcher.java:34)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.gameEvent(ServerLevel.java:1682)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.vibrationAndSoundEffectsFromBlock(Entity.java:1320)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.move(Entity.java:1249)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3065)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2999)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3525)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Mob.aiStep(Mob.java:678)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:273)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Mob.tick(Mob.java:445)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:241)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[02:35:10] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: io.protostuff.Message
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[02:35:10] [Server thread/WARN]: 	... 46 more
[02:35:10] [Server thread/ERROR]: [ItemsAdder] Error moving corrupted region to 'corrupted_data' folder
[02:35:10] [Server thread/WARN]: java.io.FileNotFoundException: File system element for parameter 'source' does not exist: './world/itemsadder/region/r.0.0.pregion'
[02:35:10] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2802)
[02:35:10] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2833)
[02:35:10] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:799)
[02:35:10] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:834)
[02:35:10] [Server thread/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:742)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:134)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:117)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.G.b(SourceFile:1755)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.G.a(SourceFile:1422)
[02:35:10] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cq.a(SourceFile:247)
[02:35:10] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[02:35:10] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:35:10] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:35:10] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:35:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.gameevent.GameEventDispatcher.post(GameEventDispatcher.java:34)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.gameEvent(ServerLevel.java:1682)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.vibrationAndSoundEffectsFromBlock(Entity.java:1320)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.move(Entity.java:1249)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3065)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2999)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3525)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Mob.aiStep(Mob.java:678)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:273)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.Mob.tick(Mob.java:445)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:241)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[02:35:10] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:35:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[02:35:10] [Server thread/ERROR]: Could not pass event GenericGameEvent to ItemsAdder v4.0.2-beta-release-9
java.lang.NullPointerException: Cannot invoke "ia.m.da.isCustomBlock(org.bukkit.block.Block)" because "<local3>" is null
	at ItemsAdder_4.0.2-beta-release-9.jar/ia.m.G.a(SourceFile:1423) ~[ItemsAdder_4.0.2-beta-release-9.jar:?]
	at ItemsAdder_4.0.2-beta-release-9.jar/ia.m.cq.a(SourceFile:247) ~[ItemsAdder_4.0.2-beta-release-9.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-57-b483da4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.gameevent.GameEventDispatcher.post(GameEventDispatcher.java:34) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.level.ServerLevel.gameEvent(ServerLevel.java:1682) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.Entity.vibrationAndSoundEffectsFromBlock(Entity.java:1320) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.Entity.move(Entity.java:1249) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3065) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2999) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3525) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:678) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:273) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.Mob.tick(Mob.java:445) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:241) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by pessiuff** [comment]
I've got the same problem.

**Comment by Bendashhh** [comment]
i confirm this i rollback to the .7 ver

**Comment by MrMaleficus** [comment]
confirmed here too
