### ISSUE TITLE
All my worlds corrupted?

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3976]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

i getting an error trying to upgrade my server.

### Steps to reproduce the issue

trying to update my server

### Server version

pufferfish 1.21.1 build 15

### ItemsAdder Version

4.0.2-beta-release-9

### ProtocolLib Version

build #726

### LoneLibs Version

1.0.58

### Full Server Log

i cant upload to this site im blocked

### Error (optional)

```shell
this error spam all my console.
[17:00:50 ERROR]: [ItemsAdder] Error moving corrupted region to 'corrupted_data' folder
[17:00:50 WARN]: java.io.FileNotFoundException: File system element for parameter 'source' does not exist: './Factions/itemsadder/region/r.-13.-3.pregion'
[17:00:50 WARN]:        at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2802)
[17:00:50 WARN]:        at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2833)
[17:00:50 WARN]:        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:799)
[17:00:50 WARN]:        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:834)
[17:00:50 WARN]:        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:742)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cP.a(SourceFile:134)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:71)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cQ.b(SourceFile:117)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.G.b(SourceFile:1755)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cJ.b(SourceFile:398)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cJ.b(SourceFile:389)
[17:00:50 WARN]:        at ItemsAdder_4.0.2-beta-release-9.jar//ia.m.cJ.d(SourceFile:527)
[17:00:50 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[17:00:50 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:00:50 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:00:50 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:00:50 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:00:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[17:00:50 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[17:00:50 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:129)
[17:00:50 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:80)
[17:00:50 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:65)
[17:00:50 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:47)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1757)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2330)
[17:00:50 WARN]:        at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:1126)
[17:00:50 WARN]:        at net.minecraft.world.level.Level.setBlock(Level.java:1098)
[17:00:50 WARN]:        at net.minecraft.world.level.Level.setBlock(Level.java:1012)
[17:00:50 WARN]:        at net.minecraft.world.level.Level.removeBlock(Level.java:1167)
[17:00:50 WARN]:        at net.minecraft.world.level.block.LeavesBlock.randomTick(LeavesBlock.java:70)
[17:00:50 WARN]:        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1226)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:858)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:921)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:523)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:411)
[17:00:50 WARN]:        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689)
[17:00:50 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813)
[17:00:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476)
[17:00:50 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605)
[17:00:50 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[17:00:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[17:00:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by iFranticman** [comment]
Same issue here i get the moved to corrupted folder and the plugin won't work but loads oddly. No items or anything loads.

**Comment by Andre601** [comment]
Duplicate of #3966
