### ISSUE TITLE
itemsadder prevents another plugin from working.

### ISSUE THREAD

**Issue by uouiiu** [PluginBugs/Issues-ItemsAdder#3983]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

[15:53:06 ERROR]: Boss 4.13.7 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.21.1-R0.1-SNAPSHOT and Java 21.0.2.0.2
[15:53:06 WARN]: org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: Unable to find method replaceFontImages with params interface org.bukkit.entity.Player, class java.lang.String in class class dev.lone.itemsadder.api.FontImages.FontImageWrapper and her subclasses
[15:53:06 WARN]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:413)
[15:53:06 WARN]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.model.ItemsAdderHook.<init>(HookManager.java:3915)
[15:53:06 WARN]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:224)
[15:53:06 WARN]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:367)
[15:53:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[15:53:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:53:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[15:53:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[15:53:06 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[15:53:06 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[15:53:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758)
[15:53:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520)
[15:53:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[15:53:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[15:53:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[15:53:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:53:06 ERROR]: Error occurred while enabling Boss v4.13.7 (Is it up to date?)
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: Unable to find method replaceFontImages with params interface org.bukkit.entity.Player, class java.lang.String in class class dev.lone.itemsadder.api.FontImages.FontImageWrapper and her subclasses
        at Boss-4.13.7.jar/org.mineacademy.boss.lib.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:413) ~[Boss-4.13.7.jar:?]
        at Boss-4.13.7.jar/org.mineacademy.boss.lib.model.ItemsAdderHook.<init>(HookManager.java:3915) ~[Boss-4.13.7.jar:?]
        at Boss-4.13.7.jar/org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:224) ~[Boss-4.13.7.jar:?]
        at Boss-4.13.7.jar/org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:367) ~[Boss-4.13.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:53:06 INFO]: [Boss] Disabling Boss v4.13.7
[15:53:06 ERROR]: Error occurred while disabling Boss v4.13.7
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "org.mineacademy.boss.settings.Settings.REGISTER_REGIONS" is null
        at Boss-4.13.7.jar/org.mineacademy.boss.BossPlugin.areRegionsEnabled(BossPlugin.java:218) ~[Boss-4.13.7.jar:?]
        at Boss-4.13.7.jar/org.mineacademy.boss.lib.plugin.SimplePlugin.onDisable(SimplePlugin.java:670) ~[Boss-4.13.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce the issue

1

### Server version

purpur-1.21.1-2301

### ItemsAdder Version

ItemsAdder_4.0.2-beta-release-9

### ProtocolLib Version

Protocollib #726

### LoneLibs Version

1.0.58

### Full Server Log

1

**Comment by LoneDev6** [comment]
Contact them, they are using reflection to access my API while they are not supposed to.
This is not a bug of ItemsAdder.
