### ISSUE TITLE
Error when setting vanilla item as block loot instead of custom item

### ISSUE THREAD

**Issue by czychuuu** [PluginBugs/Issues-ItemsAdder#3989]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

custom drops dont work

### Steps to reproduce the issue

1. mine a block with loots defined
2. see error

### Server version

Current Purpur Version: 1.21.1-2301-a43711d (MC: 1.21.1)*
* You are running the latest version

### ItemsAdder Version

4.0.2-beta-release-10

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

not needed

### Error (optional)

```shell
[15:25:43 ERROR]: Could not pass event cn to ItemsAdder v4.0.2-beta-release-10
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
        at ItemsAdder.jar/ia.m.fg.b(SourceFile:116) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.fw.c(SourceFile:77) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.fp.a(SourceFile:138) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ItemsAdder.jar/ia.m.ou.a(SourceFile:74) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.j(SourceFile:191) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.nQ.d(SourceFile:130) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.fj(SourceFile:173) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.fg(SourceFile:105) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cD.b(SourceFile:224) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2675) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:34) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:16) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Problematic items yml configuration file (optional)

```yaml
items:
  end_coal:
    display_name: "end coal"
    resource:
      generate: true
      material: END_STONE
      textures:
        - block/end/coal
    specific_properties:
      block:
        cancel_drop: true
        hardness: 2
        placed_model:
          type: REAL
          break_particles: ITEM
        break_tools_whitelist:
        - WOODEN_PICKAXE
        - STONE_PICKAXE
        - IRON_PICKAXE
        - DIAMOND_PICKAXE
        - NETHERITE_PICKAXE

loots:
  blocks:
    end_coal:
      type: end_coal
      items:
        coal:
          item: coal
          min_amount: 1
          chance: 100
```

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by czychuuu** [comment]
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

https://mclo.gs/b1jWyGk

**Comment by Andre601** [comment]
I can see you are using Iris and IABlocksInjector. Does the issue persist while these plugins aren't present?

**Comment by LoneDev6** [comment]
Will be tested, strange.

**Comment by czychuuu** [comment]
> I can see you are using Iris and IABlocksInjector. Does the issue persist while these plugins aren't present?

yes
`
[16:42:26 ERROR]: Could not pass event cn to ItemsAdder v4.0.2-beta-release-10
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "this.itemStack" is null
        at ItemsAdder.jar/ia.m.fg.b(SourceFile:116) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.fw.c(SourceFile:77) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.fp.a(SourceFile:138) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ItemsAdder.jar/ia.m.ou.a(SourceFile:74) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.j(SourceFile:191) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.nQ.d(SourceFile:130) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.fj(SourceFile:173) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cB.fg(SourceFile:105) ~[ItemsAdder.jar:?]
        at ItemsAdder.jar/ia.m.cD.b(SourceFile:224) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2675) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:34) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:16) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
> pl
[16:42:43 INFO]: Paper Plugins: (0):
[16:42:43 INFO]: Bukkit Plugins: (4):
[16:42:43 INFO]:  - ItemsAdder, LoneLibs, ProtocolLib, Terra
`
