### ISSUE TITLE
Java Class Conflict with ChatControlRed plugin

### ISSUE THREAD

**Issue by Nunchakin** [PluginBugs/Issues-ItemsAdder#3991]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

nunchakin

### What happened?

I use ItemsAdder as well as ChatControlRed plugin and after updating to the latest ItemsAdder dev build 10, ChatControlRed plugin won't start due to conflict with ItemsAdder function or something and people from their server told me to also report it to ItemsAdder dev.

### Steps to reproduce the issue

1. Use ItemsAdder 10 dev build
2. Use latest ChatControlRed plugin version for managing chat etc
3. Start the server

### Server version

This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

[12:55:36 INFO]: ItemsAdder version 4.0.2-beta-release-10
>....
[12:55:36 INFO]: Customized Minecraft without client mods!

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### Full Server Log

https://mclo.gs/bX75fuX

### Error (optional)

```shell
Error while loading ChatControlRed dependencies!
ReflectionException Unable to find method replaceFontImages with params interface org.bukkit.entity.Player, class java.lang.String in class class dev.lone.itemsadder.api.FontImages.FontImageWrapper and her subclasses
	 at ChatControl-Red-10.27.9.jar//org.mineacademy.chatcontrol.lib.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:413)
	 at ChatControl-Red-10.27.9.jar//org.mineacademy.chatcontrol.lib.model.ItemsAdderHook.<init>(HookManager.java:3915)
	 at ChatControl-Red-10.27.9.jar//org.mineacademy.chatcontrol.lib.model.HookManager.loadDependencies(HookManager.java:224)
	 at ChatControl-Red-10.27.9.jar//org.mineacademy.chatcontrol.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:367)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
----------------------------------------------------------------------------------------------
```

**Comment by Pattanawaris** [comment]
having same issues please help ;-; I know it not seems to be your responsibilities LoneDev but we just have nowhere to get helped.

**Comment by Andre601** [comment]
This isn't an ItemsAdder issue unless it for some reason does not have the current API included, which is very unlikely.

I personally find it questionable that ChatControl Red is using reflection rather than using the API directly... There is no benefit of doing that and I would argue that it even has a negative performance impact. My only guess is that this is Kangarko's way of stripping away dependencies.

Either way, the method is available and hasn't changed in that regards for years at this point:
https://github.com/LoneDev6/API-ItemsAdder/blob/3a4421726fb6ed0e781eda65dfe245aebdf9b042/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java#L56-L59

**Comment by kangarko** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/3801, addressed there.
