### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#4000]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

im getting some erors

### Steps to reproduce the issue

just start and play server.

### Server version

pufferfish-1.21.1.jar:1.21.1 build 15

### ItemsAdder Version

hotfix 10

### ProtocolLib Version

build 726

### LoneLibs Version

LoneLibs 1.0.58

### Full Server Log

https://paste.helpch.at/wuronepele.makefile

### Error (optional)

```shell
[01:36:02 WARN]: [ItemsAdder] Task #2074815 for ItemsAdder v4.0.2-beta-release-10 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil
        at LoneLibs_1.0.58.jar/dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.setString(NBTCompound.java:176) ~[LoneLibs_1.0.58.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.hB.a(SourceFile:160) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
        at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at LoneLibs_1.0.58.jar/dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[LoneLibs_1.0.58.jar:?]
        at LoneLibs_1.0.58.jar/dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[LoneLibs_1.0.58.jar:?]
        at LoneLibs_1.0.58.jar/dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.hasKey(NBTCompound.java:707) ~[LoneLibs_1.0.58.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.fA.M(SourceFile:79) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.fp.d(SourceFile:53) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-3554f78]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:998) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1890) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1793) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.npc.AbstractVillager.die(AbstractVillager.java:242) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.npc.Villager.die(Villager.java:699) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1598) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2420) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2872) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2783) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1544) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1521) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1514) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1473) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1480) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325) ~[pufferfish-1.21.1.jar:1.21.1-15-3554f78]
        ... 2 more
```

**Comment by LoneDev6** [comment]
Try to update LoneLibs and ItemsAdder to the latest available version.
