### ISSUE TITLE
lang.yml doesn't allow string with spaces

### ISSUE THREAD

**Issue by szarkans** [PluginBugs/Issues-ItemsAdder#4025]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

When entry added by `lang.yml` has spaces in it, it will not be added to lang file in generated resourcepack.
Adding same entry directly in `assets/minecraft/lang/<lang_code>.json` will work just fine.

Example:
"This is some text with spaces": "This is translated version of text"

This type of translations are needed for translatable item name/lore with new lines, because Minecraft doesn't allow using `\n` in item's lore

### Steps to reproduce the issue

1. Create itemsadder's language file
2. Add any entry to any language with key having spaces
3. Notice that it doesn't work that way

### Server version

 Current Purpur Version: 1.21.1-2309-be61a07 (MC: 1.21.1)*

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### Full Server Log

https://mclo.gs/wN8qk2t

### Error (optional)

```shell
[01:04:42 ERROR]: Cannot load file: /contents/catcraft/configs/lang.yml
[01:04:42 WARN]: java.lang.IllegalArgumentException: Cannot set to an empty path
[01:04:42 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[01:04:42 WARN]:        at org.bukkit.configuration.MemorySection.set(MemorySection.java:191)
[01:04:42 WARN]:        at org.bukkit.configuration.MemorySection.set(MemorySection.java:230)
[01:04:42 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163)
[01:04:42 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
[01:04:42 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
[01:04:42 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
[01:04:42 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120)
[01:04:42 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[01:04:42 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.lD.a(SourceFile:201)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.lD.<init>(SourceFile:141)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.lD.<init>(SourceFile:102)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.a(SourceFile:1967)
[01:04:42 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[01:04:42 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
[01:04:42 WARN]:        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[01:04:42 WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
[01:04:42 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
[01:04:42 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
[01:04:42 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[01:04:42 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[01:04:42 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[01:04:42 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.c(SourceFile:1937)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.b(SourceFile:1914)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.b(SourceFile:668)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.c(SourceFile:626)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.ma.d(SourceFile:130)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.a(SourceFile:620)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//ia.m.G.u(SourceFile:278)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//dev.lone.itemsadder.Main.jf(SourceFile:514)
[01:04:42 WARN]:        at ItemsAdder-4.0.2-beta-release-11.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:426)
[01:04:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[01:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[01:04:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[01:04:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[01:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
[01:04:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
[01:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[01:04:42 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[01:04:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[01:04:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[01:04:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[01:04:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Problematic items yml configuration file (optional)

```yaml
info:
    namespace: server_name
minecraft_lang_overwrite:
    en:
        entries:
            "Небольшой электронно-магический модуль": "    &7Small electrical-magical module,"
        languages:
            - en_us
```

**Comment by Andre601** [comment]
You completely misunderstand the purpose of the `minecraft_lang_override` option.
It's there to override text of specific messages based on the message-key, not the effective text that is usually displayed.

The wiki is giving a clear example here:
https://itemsadder.devs.beer/plugin-usage/adding-content/minecraft-language-files#example-of-usage-custom-esc-menu

Also, next time share the **FULL** console log and not just the error. We ask for it for a reason.
