### ISSUE TITLE
PlayerEditBookEvent Error for Locked Bookshelf

### ISSUE THREAD

**Issue by zikehalil3535** [PluginBugs/Issues-ItemsAdder#4027]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

So, I have a plugin for lock bookshelf, chest etc. If another player tried to use bookshelf I get error like this:
![image](https://github.com/user-attachments/assets/31d1f552-ce76-4623-bbde-5a76dcf08977)

### Steps to reproduce the issue

Lock the Bookshelf
Try to get Book with another account.
I will get this error.

### Server version

Current Purpur Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)*

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.59

### Full Server Log

Not needed

### Error (optional)

```shell
[06:17:56 ERROR]: Could not pass event PlayerEditBookEvent to ItemsAdder v4.0.2-beta-release-11
java.lang.UnsupportedOperationException: null
        at java.base/java.util.AbstractList.set(AbstractList.java:138) ~[?:?]
        at ItemsAdder-4.0.2-beta-release-11.jar/ia.m.hC.b(SourceFile:189) ~[ItemsAdder-4.0.2-beta-release-11.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2299-5c0d2f7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEditBookEvent(CraftEventFactory.java:1662) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.signBook(ServerGamePacketListenerImpl.java:1296) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleEditBook$6(ServerGamePacketListenerImpl.java:1251) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/3112fc92-07f0-468f-8e00-80a2c944eb9a)

**Comment by Andre601** [comment]
Share the logs. We wouldn't ask for them if they aren't needed.
