### ISSUE TITLE
Itemsadder 4.0.2-beta-release-11 and 4.0.2-beta-release-10 spam console

### ISSUE THREAD

**Issue by PixelsTurtle** [PluginBugs/Issues-ItemsAdder#4029]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

PixelsTurtle

### What happened?

Itemsadder sends messages in the console really really quickly

### Steps to reproduce the issue

Start the server
Wait and look at console
Console gets filled
Server crashes

### Server version

Pufferfish 1.21.1 RO.1-SNAPSHOT

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

5.3.0 SNAPSHOT 726

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/3OIjQGj

### Error (optional)

```shell
[19:13:12 ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v4.0.2-beta-release-10
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
        at ItemsAdder_4.0.2-beta-release-10 (1)-1727205101126.jar/ia.m.bX.b(SourceFile:154) ~[ItemsAdder_4.0.2-beta-release-10 (1)-1727205101126.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-16-a9e9d99]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2353) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1500) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:301) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:266) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:245) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1262) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:740) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
        ... 34 more
[19:13:12 ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v4.0.2-beta-release-10
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
        at ItemsAdder_4.0.2-beta-release-10 (1)-1727205101126.jar/ia.m.bX.b(SourceFile:154) ~[ItemsAdder_4.0.2-beta-release-10 (1)-1727205101126.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-16-a9e9d99]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2353) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1500) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:301) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:266) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:245) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1262) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:740) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-16-a9e9d99]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
        ... 34 more
```

**Comment by Andre601** [comment]
There are two possible cases here:

1. ItemsAdder uses an outdated version of LibsDisguise's API
2. You use an outdated version of LibsDisguise

I personally feel like 2 is the more likely option here, as the logs show you using a version that isn't compatible with your server version. I suggest checking if there is a dev build you can use for your server.
Otherwise temporarely remove LibsDisguise until a fix is availble.

**Comment by PixelsTurtle** [comment]
> There are two possible cases here:
> 
> 1. ItemsAdder uses an outdated version of LibsDisguise's API
> 2. You use an outdated version of LibsDisguise
> 
> I personally feel like 2 is the more likely option here, as the logs show you using a version that isn't compatible with your server version. I suggest checking if there is a dev build you can use for your server. Otherwise temporarely remove LibsDisguise until a fix is availble.

You're a life saver. TYSM
