### ISSUE TITLE
Console log massive spam

### ISSUE THREAD

**Issue by LionelSp** [PluginBugs/Issues-ItemsAdder#4038]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

monbry

### What happened?

An error produces a massive spam on the console, its extremely annoying and it makes the console log unreadable.

### Steps to reproduce the issue

We think its due to armor stands, when we summon an armor stand or use a cosmetic like a balloon on cosmetics core the error spams everywhere.

### Server version

1.20.6 Paper-149-ver

### ItemsAdder Version

[4.0.2-beta-release-12

### ProtocolLib Version

procollib 5.3.0-SNAPSHOT-726

### LoneLibs Version

lone libs1.0.59 

### Full Server Log

e

### Error (optional)

```shell
[23:00:09 ERROR]: Could not pass event EntityDamageEvent to ItemsAdder v4.0.2-beta-release-12
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
        at ItemsAdder_4.0.2-beta-release-12.jar/itemsadder.m.ex.a(SourceFile:136) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-149-6e71f41]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1187) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1177) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1082) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1231) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2280) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1499) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:209) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:913) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:420) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:375) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.Entity.tick(Entity.java:866) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3074) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.Mob.tick(Mob.java:452) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:122) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1415) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1301) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:922) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:902) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
```

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot 2024-09-28 234649](https://github.com/user-attachments/assets/ca81cd4e-2274-428e-94ef-d99e8cf9f6f5)

**Comment by Andre601** [comment]
You seem to uae an outdated libsdisguise version. Either that or IA uses an outdated api.

Try using the latest dev build of LD and see if that fixes things.

**Comment by LionelSp** [comment]
It really worked! Thanks! We just noticed that is the only plugin we forgot to update.
