### ISSUE TITLE
Denizen issue

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4060]
![image](https://github.com/user-attachments/assets/3da53085-3933-443f-9c62-e870af59363e)

```
[23:00:36] [Server thread/ERROR]: [ItemsAdder] Error while hooking into Denizen
[23:00:36] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/denizenscript/denizen/objects/ItemTag
[23:00:36] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.Core.OtherPlugins.Denizen.DenizenHook.hook(SourceFile:22)
[23:00:36] [Server thread/WARN]: 	at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:361)
[23:00:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[23:00:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[23:00:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[23:00:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[23:00:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[23:00:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[23:00:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[23:00:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[23:00:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[23:00:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[23:00:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[23:00:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[23:00:36] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizen.objects.ItemTag
[23:00:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[23:00:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[23:00:36] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[23:00:36] [Server thread/WARN]: 	... 14 more
```

**Comment by PSYCHEER** [comment]
Can I get more information about this? I'm using Denizen dev version and latest IA and it works for me in the way it should.

**Comment by LoneDev6** [comment]
Same, will close as can't reproduce
