### ISSUE TITLE
Plugin not working with authlib-injector.jar

### ISSUE THREAD

**Issue by StelStelox** [PluginBugs/Issues-ItemsAdder#4064]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

stel_stelox

### What happened?

I use custom authlib for game accounts https://github.com/yushijinhun/authlib-injector/blob/develop/README.en.md . I encountered java.lang.BootstrapMethodError: bootstrap method initialization exception when running via authlib-injector.

### Steps to reproduce the issue

Run the server once (with vulnerable elua). Download authlib-injector. Run the kernel with arguments -javaagent:authlib-injector-1.2.5.jar=http://127.0.0.1:1370

### Server version

Current Purpur Version: 1.21.1-2326-4f2fe31 (MC: 1.21.1)*  

### ItemsAdder Version

ItemsAdder version 4.0.2-beta-release-12  

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-732  

### LoneLibs Version

LoneLibs version 1.0.59 

### Full Server Log

https://mclo.gs/4aJaKiA

### Error (optional)

```shell
[15:29:56 ERROR]: Error occurred while disabling ItemsAdder v4.0.2-beta-release-12                                                                                                                                                           java.lang.BootstrapMethodError: bootstrap method initialization exception                                                                                                                                                                            at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?]                                                                                                                                          at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]                                                                                                                                                                    at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?]                                                                                                                                      at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?]                                                                                                                                          at ItemsAdder_4.0.2-beta-release-12.jar/dev.lone.itemsadder.Main.onDisable(SourceFile:678) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]                                                                                                         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]                                                                                                                           at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                            at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]                                                                                                           at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                             at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]                                                                                                            at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                            at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                           at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                              at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]                                                                                                                     at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]                                                                                                                                                                           Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "veMcDurecttDYMseaksufM8s3uq6dyVAV.TbMgimWI5U9oJat8qV" is null                                                                                               at ItemsAdder_4.0.2-beta-release-12.jar/veMcDurecttDYMseaksufM8s3uq6dyVAV.m0Mr8arkV2B(veMcDurecttDYMseaksufM8s3uq6dyVAV.java) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]                                                                      at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:170) ~[?:?]                                                                                                                                          ... 19 more
```

### Problematic items yml configuration file (optional)

```yaml
I didn't set it up
```

**Comment by LoneDev6** [comment]
Seems you're using an unofficial version of the ItemsAdder JAR.
If it's a mistake, please join the Discord and confirm your license.
Thanks!

> Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "veMcDurecttDYMseaksufM8s3uq6dyVAV.TbMgimWI5U9oJat8qV" is null                                                                                               at ItemsAdder_4.0.2-beta-release-12.jar/veMcDurecttDYMseaksufM8s3uq6dyVAV.m0Mr8arkV2B(veMcDurecttDYMseaksufM8s3uq6dyVAV.java) ~[ItemsAdder_4.0.2-beta-release-12.jar:?]    

My plugin doesn't include such file names, so it's most likely to be an unofficial version.

**Comment by StelStelox** [comment]
Thanks for explaining the problem. The project person told me he had a purchased version. But thanks anyway.

**Comment by StelStelox** [comment]
Thanks for explaining the problem. The project person told me he had a purchased version. But thanks anyway.
