### ISSUE TITLE
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-93...12])

### ISSUE THREAD

**Issue by xBeratE** [PluginBugs/Issues-ItemsAdder#4078]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

xberat

### What happened?

I'm getting an error on the 1.16.5 server

### Steps to reproduce the issue

This error appears on the console every time the player logs into the server.

### Server version

1.16.5

### ItemsAdder Version

3.6.5-legacy

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/USo0mQV

### Error (optional)

```shell
[21:43:47] [Server thread/INFO]: xBerat joined the game
[21:43:47] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-93...12])
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:257) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
	at ia.m.hH.a(SourceFile:26) ~[?:?]
	at ia.m.hF.h(SourceFile:141) ~[?:?]
	at ia.m.hA.d(SourceFile:234) ~[?:?]
	at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[?:?]
	at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[?:?]
	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[?:?]
	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2033) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.sendAll(PlayerList.java:1055) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.sendMessage(PlayerList.java:1425) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.sendMessage(PlayerList.java:1430) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:368) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:317) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1597) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-93...12])
	at net.minecraft.server.v1_16_R3.ChatDeserializer.a(SourceFile:103) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatDeserializer.h(SourceFile:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatHoverable$b.a(SourceFile:134) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatHoverable$EnumHoverAction.a(SourceFile:337) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatHoverable.a(SourceFile:94) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.b(ChatModifier.java:292) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChatModifier$ChatModifierSerializer.deserialize(ChatModifier.java:243) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:246) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:186) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:376) ~[patched_1.16.5.jar:git-Purpur-1171]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:253) ~[?:?]
	... 34 more
[21:43:47] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@24d6da0c[
    a=io.papermc.paper.adventure.AdventureComponent@17f1921
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by Andre601** [comment]
Try using [5.2.0 of ProtocolLib](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.2.0), as it is stated to be the recommended version for 1.20.4 and older [on their CI](https://ci.dmulloy2.net/job/ProtocolLib/).

**Comment by PSYCHEER** [comment]
> Try using [5.2.0 of ProtocolLib](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.2.0), as it is stated to be the recommended version for 1.20.4 and older [on their CI](https://ci.dmulloy2.net/job/ProtocolLib/).

Need to mention the LoneLibs version as in log is stated 1.0.56 which is already really old, please use newest instead, as it can be issue

**Comment by MemencioPerez** [comment]
This should be fixed if https://github.com/KyoriPowered/adventure-platform/pull/197 is merged, in my case the error occurred when a player unlocked an achievement.

```
[02Dec2024 15:20:43.317] [Server thread/INFO] [Console/]: [+] Memencio
[02Dec2024 15:21:00.300] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]:  Memencio has made the advancement [Getting an Upgrade]
[02Dec2024 15:21:00.360] [Server thread/ERROR] [Minecraft/]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-16...52])
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:267) ~[?:?]
	at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[?:?]
	at ia.m.hH.a(SourceFile:26) ~[?:?]
	at ia.m.hF.h(SourceFile:141) ~[?:?]
	at ia.m.hA.d(SourceFile:234) ~[?:?]
	at ia.m.hA.onPacketSending(SourceFile:174) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:266) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223) ~[?:?]
	at net.minecraft.network.NetworkManager.handler$zze000$sendImmediately$rewrite(NetworkManagerMixin.java:1569) ~[?:?]
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManagerMixin.java:173) ~[?:?]
	at net.minecraft.network.NetworkManager.func_201058_a(NetworkManagerMixin.java:163) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_211148_a(ServerPlayNetHandlerMixin.java:1052) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147359_a(ServerPlayNetHandlerMixin.java:1035) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_148540_a(PlayerListMixin.java:505) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_232641_a_(PlayerListMixin.java:749) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancementsMixin.java:211) ~[?:?]
	at net.minecraft.command.impl.AdvancementCommand$Action$1.func_198179_a(SourceFile:235) ~[?:?]
	at net.minecraft.command.impl.AdvancementCommand$Action.func_198180_a(SourceFile:274) ~[?:?]
	at net.minecraft.command.impl.AdvancementCommand.func_198214_a(SourceFile:137) ~[?:?]
	at net.minecraft.command.impl.AdvancementCommand.func_198215_j(SourceFile:59) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?]
	at net.minecraft.command.Commands.func_197059_a(CommandsMixin.java:217) ~[?:?]
	at net.minecraft.command.Commands.a(CommandsMixin.java:546) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServerMixin.java:746) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at net.minecraft.server.dedicated.DedicatedServer.redirect$bcd000$arclight$serverCommandEvent(DedicatedServerMixin.java:655) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServerMixin.java:312) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:292) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-16...52])
	at net.minecraft.util.JSONUtils.func_151206_a(SourceFile:103) ~[?:?]
	at net.minecraft.util.JSONUtils.func_151200_h(SourceFile:109) ~[?:?]
	at net.minecraft.util.text.event.HoverEvent$EntityHover.func_240682_a_(SourceFile:134) ~[?:?]
	at net.minecraft.util.text.event.HoverEvent$Action.func_240668_a_(SourceFile:337) ~[?:?]
	at net.minecraft.util.text.event.HoverEvent.func_240661_a_(SourceFile:94) ~[?:?]
	at net.minecraft.util.text.Style$Serializer.func_240734_b_(Style.java:331) ~[?:?]
	at net.minecraft.util.text.Style$Serializer.deserialize(Style.java:303) ~[?:?]
	at net.minecraft.util.text.Style$Serializer.deserialize(Style.java:287) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at net.minecraft.util.text.ITextComponent$Serializer.deserialize(SourceFile:234) ~[?:?]
	at net.minecraft.util.text.ITextComponent$Serializer.deserialize(SourceFile:181) ~[?:?]
	at net.minecraft.util.text.ITextComponent$Serializer.deserialize(SourceFile:130) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[arclight-forge-1.16.5-1.0.26-SNAPSHOT-custom.jar:arclight-1.16.5-1.0.26-SNAPSHOT-5c6b7953]
	at net.minecraft.util.text.ITextComponent$Serializer.func_240641_a_(SourceFile:355) ~[?:?]
	at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:263) ~[?:?]
	... 41 more
[02Dec2024 15:21:00.375] [Server thread/ERROR] [Minecraft/]: Parameters: 
  net.minecraft.network.play.server.SChatPacket@63b65a18[
    field_148919_a=TranslatableComponent{key='chat.type.advancement.task', args=[TextComponent{text='', siblings=[TextComponent{text='', siblings=[TextComponent{text='', siblings=[TextComponent{text='', siblings=[], style=Style{ color=white, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text=' ', siblings=[], style=Style{ color=null, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='Memencio', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell Memencio '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.util.text.event.HoverEvent$EntityHover@82d4806b'}, insertion=Memencio, font=minecraft:default}}, TranslatableComponent{key='chat.square_brackets', args=[TranslatableComponent{key='advancements.story.upgrade_tools.title', args=[], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=HoverEvent{action=<action show_text>, value='TranslatableComponent{key='advancements.story.upgrade_tools.title', args=[], siblings=[TextComponent{text='
  ', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TranslatableComponent{key='advancements.story.upgrade_tools.description', args=[], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=green, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}'}, insertion=null, font=minecraft:default}}], siblings=[], style=Style{ color=green, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    field_179842_b=SYSTEM
    field_240809_c_=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by MemencioPerez** [comment]
@xBeratE can you try this version of LoneLibs to see if it works for you?

https://lobfile.com/file/P364Vm2G.zip

**Comment by xBeratE** [comment]
It's working no problem now

MemencioPerez ***@***.***>, 2 Ara 2024 Pzt, 22:14 tarihinde
şunu yazdı:

**Comment by LoneDev6** [comment]
Try to update LoneLibs

**Comment by LoneDev6** [comment]
@MemencioPerez
exactly what did you change in this "custom" jar?

**Comment by LoneDev6** [comment]
Thanks, I might implement that in the next LoneLibs
