### ISSUE TITLE
It seems like there’s an issue with the API

### ISSUE THREAD

**Issue by CCjun6** [PluginBugs/Issues-ItemsAdder#4090]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

After the server runs for a while, this error suddenly appears, and then ItemsAdder completely stops working. A restart is required to restore it. Additionally, many other server owners have encountered the same problem, all happening today.

### Steps to reproduce the issue

Any server with ItemsAdder installed will encounter this issue after running for a while.

### Server version

Current Purpur Version: 1.21.1-2324-e12a4de (MC: 1.21.1)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)

### ItemsAdder Version

4.0.3

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/xPG4g7f

### Error (optional)

```shell
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: java.lang.ClassCircularityError
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kd.a(class:5574)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.nt.a(class:5199)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ll.a(class:4619)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.tv.a(class:5373)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.lr.a(class:4850)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.Input.a(class:1767)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.mr.a(class:2010)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ael.a(class:870)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.x.a(class:4468)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.cr.a(class:1854)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.CustomBlock$Advanced.a(class:2708)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.abz.a(class:3968)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.uj.a(class:858)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.cu.a(class:1762)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.os.a(class:3272)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kw.a(class:3948)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ul.a(class:1088)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.agc.a(class:3680)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.act.a(class:408)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.agx.a(class:2482)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.aau.a(class:1284)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.hf.a(class:3529)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Denizen.SetCustomBlock.a(class:88)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.Message.a(class:2436)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.acv.a(class:5181)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.qa.a(class:4261)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.rj.a(class:3800)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.xc.a(class:5530)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.Mimic.ItemsAdderItemsRegistryCreator.a(class:5164)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.fk.a(class:1571)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.aei.a(class:344)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ahd.a(class:3580)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kk.a(class:1230)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.afs.a(class:3010)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.dw.a(class:4577)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.cu.a(class:730)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.adv.a(class:4490)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.ByteString.a(class:4001)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kv.a(class:870)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kp.a(class:4351)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ud.a(class:4956)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.be.a(class:4690)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.fo.a(class:2780)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kj.a(class:5222)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.fs.a(class:178)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.pd.a(class:5282)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at ia.sh.io.protostuff.B64Code.a(class:5114)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.qe.a(class:740)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.adz.a(class:768)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.tg.a(class:1003)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.acz.a(class:1013)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.la.a(class:3098)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.so.a(class:4260)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.wd.a(class:5477)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.ProtectionPlugins.ProtectionPlugins.a(class:1290)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.ael.a(class:2021)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.fr.a(class:5970)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.be.a(class:3522)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.aao.a(class:1726)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.bt.a(class:5644)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.enchants.AeWrapper.a(class:869)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.hr.a(class:822)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.va.a(class:6201)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kt.a(class:6118)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.PAPI.PAPI_FontImages.a(class:4742)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.uz.a(class:2600)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.xg.a(class:1561)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.kc.a(class:2584)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.rl.a(class:2592)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.yd.a(class:2932)
[21:05:38] [Craft Scheduler Thread - 737 - ItemsAdder/WARN]: 	at itemsadder.m.eo.a(class:4474)
[21:05:38] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.3
[21:05:38] [pool-96-thread-1/INFO]: [ia] [Host] Stopped self-host webserver on port: 8002
[21:06:21] [Server thread/INFO]: CC issued server command: /ia
[21:06:21] [Server thread/ERROR]: Command exception: /ia
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v4.0.3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/137fae6c-64cc-4404-b7ec-332bb25bd3fd)

**Comment by Taks1k** [comment]
We have a similar problem, only itemsadder version 3.6.5 and minecraft version 1.19.4

**Comment by Taks1k** [comment]
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: java.lang.InstantiationException
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.ea.a(class:5207)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.mj.a(class:2867)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.rk.a(class:4188)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.ea.a(class:2076)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.util.CombinatoricsUtils.a(class:5121)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.NoDataException.a(class:1586)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.TooManyEvaluationsException.a(class:2209)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.gp.a(class:3446)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.CustomEntity$Bone.a(class:3662)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.MaxCountExceededException.a(class:114)
[17:03:50] [Server thread/INFO]: [MythicMobs] Loading Packs...[0m
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.FontImages.FontImageWrapper.a(class:6058)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cB.a(class:2258)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.ce.a(class:3405)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cb.a(class:1549)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.hL.a(class:6456)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.iH.a(class:872)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.hY.a(class:122)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.of.a(class:6306)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.he.a(class:2164)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.rS.a(class:3715)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.bD.a(class:6625)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.jS.a(class:3542)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.qy.a(class:3249)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.jw.a(class:4619)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.hm.a(class:5209)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.util.IntegerSequence$Incrementor.a(class:1294)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.hg.a(class:4093)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.jK.a(class:5340)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.hv.a(class:628)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.od.a(class:2083)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cb.a(class:1669)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.pz.a(class:3182)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.mJ.a(class:3722)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.jZ.a(class:5602)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.aO.a(class:1751)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.ly.a(class:5234)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.qn.a(class:6418)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.jx.a(class:5148)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.oP.a(class:5648)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.dC.a(class:332)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.MathInternalError.a(class:3789)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cH.a(class:5081)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.bB.a(class:1450)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.kE.a(class:4320)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cB.a(class:724)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.pL.a(class:763)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.iY.a(class:787)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.pa.a(class:1247)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.aU.a(class:3738)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.eU.a(class:4276)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.is.a(class:2138)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.dK.a(class:2527)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.iH.a(class:5703)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.NumberIsTooLargeException.a(class:2189)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.exception.MathIllegalStateException.a(class:6257)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.dZ.a(class:3032)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.lV.a(class:3682)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.bR.a(class:3987)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.me.a(class:681)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.distribution.AbstractRealDistribution$1.a(class:3589)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.je.a(class:2584)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.geometry.euclidean.threed.Euclidean3D$LazyHolder.a(class:777)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.bw.a(class:6093)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.eg.a(class:2867)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.sh.org.apache.commons.math3.util.IntegerSequence.a(class:1610)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.CustomFurniture.a(class:5158)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.nK.a(class:3908)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.qI.a(class:1892)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.bp.a(class:1913)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.lu.a(class:3726)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.ji.a(class:4354)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at dev.lone.itemsadder.api.CustomMob.a(class:5649)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.mz.a(class:5150)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.cn.a(class:2558)
[17:03:50] [Craft Scheduler Thread - 430 - ItemsAdder/WARN]: 	at ia.m.aZ.a(class:4282)
[17:03:51] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.6.5

**Comment by Taks1k** [comment]
After about 1.5 hours of server operation

**Comment by TheStepashich** [comment]
Same problem... 

Version 1.21, Purpur

```
[17:24:53 WARN]: java.lang.SecurityException
[17:24:53 WARN]:        at itemsadder.m.mr.a(class:3564)
[17:24:53 WARN]:        at itemsadder.m.lr.a(class:2006)
[17:24:53 WARN]:        at ia.sh.io.protostuff.WriteSink$1.a(class:5088)
[17:24:53 WARN]:        at itemsadder.m.aet.a(class:4891)
[17:24:53 WARN]:        at itemsadder.m.ab.a(class:6045)
[17:24:53 WARN]:        at itemsadder.m.gv.a(class:3334)
[17:24:53 WARN]:        at itemsadder.m.nl.a(class:1156)
[17:24:53 WARN]:        at itemsadder.m.ago.a(class:6172)
[17:24:53 WARN]:        at itemsadder.m.adr.a(class:328)
[17:24:53 WARN]:        at itemsadder.m.ov.a(class:4192)
[17:24:53 WARN]:        at itemsadder.m.acc.a(class:1554)
[17:24:53 WARN]:        at itemsadder.m.xu.a(class:3484)
[17:24:53 WARN]:        at itemsadder.m.wz.a(class:5705)
[17:24:53 WARN]:        at itemsadder.m.ch.a(class:3026)
[17:24:53 WARN]:        at itemsadder.m.adv.a(class:6200)
[17:24:53 WARN]:        at itemsadder.m.ta.a(class:6503)
[17:24:53 WARN]:        at itemsadder.m.iu.a(class:2605)
[17:24:53 WARN]:        at itemsadder.m.bn.a(class:474)
[17:24:53 WARN]:        at itemsadder.m.vt.a(class:6000)
[17:24:53 WARN]:        at itemsadder.m.aj.a(class:1577)
[17:24:53 WARN]:        at itemsadder.m.agi.a(class:4579)
[17:24:53 WARN]:        at itemsadder.m.nz.a(class:5097)
[17:24:53 WARN]:        at itemsadder.m.np.a(class:1910)
[17:24:53 WARN]:        at itemsadder.m.dg.a(class:5748)
[17:24:53 WARN]:        at itemsadder.m.adg.a(class:6302)
[17:24:53 WARN]:        at itemsadder.m.ada.a(class:4709)
[17:24:53 WARN]:        at dev.lone.itemsadder.api.Events.campfire.CampfireUnlitEvent.a(class:1271)
[17:24:53 WARN]:        at dev.lone.itemsadder.api.Examples.a(class:6467)
[17:24:53 WARN]:        at itemsadder.m.qz.a(class:5728)
[17:24:53 WARN]:        at itemsadder.m.l.a(class:4330)
[17:24:53 WARN]:        at itemsadder.m.vd.a(class:5444)
[17:24:53 WARN]:        at itemsadder.m.ix.a(class:2966)
[17:24:53 WARN]:        at itemsadder.m.po.a(class:2905)
[17:24:53 WARN]:        at itemsadder.m.aw.a(class:17)
[17:24:53 WARN]:        at itemsadder.m.yn.a(class:772)
[17:24:53 WARN]:        at itemsadder.m.ie.a(class:5039)
[17:24:53 WARN]:        at itemsadder.m.abs.a(class:6615)
[17:24:53 WARN]:        at itemsadder.m.vq.a(class:5709)
[17:24:53 WARN]:        at itemsadder.m.add.a(class:5003)
[17:24:53 WARN]:        at itemsadder.m.rp.a(class:1140)
[17:24:53 WARN]:        at itemsadder.m.ya.a(class:3367)
[17:24:53 WARN]:        at itemsadder.m.qf.a(class:1647)
[17:24:53 WARN]:        at itemsadder.m.yn.a(class:2857)
[17:24:53 WARN]:        at itemsadder.m.aed.a(class:940)
[17:24:53 INFO]: [ItemsAdder] Disabling ItemsAdder v4.0.3
```

**Comment by Andre601** [comment]
Please don't share errors directly in your posts. Use paste sites to keep the issue from being filled with too much stuff.

@CCjun6 Please provide the **Full** server logs, not just the error itself. Thanks.

**Comment by szarkans** [comment]
Same  
https://mclo.gs/jhyaJ3b  
`This server is running Leaf version 1.21.1-DEV-ver/1.21.1@9514f2b (2024-10-28T10:22:26Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)`

**Comment by Shurelia** [comment]
happening on beta-13 aswell, updated it earlier to the latest 4.0.3 and still happening

**Comment by CCjun6** [comment]
> Please don't share errors directly in your posts. Use paste sites to keep the issue from being filled with too much stuff.
> 
> @CCjun6 Please provide the **Full** server logs, not just the error itself. Thanks.

https://mclo.gs/RlZbjPQ

**Comment by CCjun6** [comment]
> Please don't share errors directly in your posts. Use paste sites to keep the issue from being filled with too much stuff.
> 
> @CCjun6 Please provide the **Full** server logs, not just the error itself. Thanks.

I hope the priority of this issue can be raised. It occurs every hour or so, and the server needs to be restarted constantly to recover, which is very troublesome

**Comment by CirrusPreeminent** [comment]
same problem +1

**Comment by nesinamore** [comment]
same https://mclo.gs/u5Ph7Ce

**Comment by nesinamore** [comment]
how i can this fixed?

**Comment by Taks1k** [comment]
Will there be an answer?

**Comment by dimpetrop** [comment]
+1 this is an issue for us aswell!

**Comment by Taks1k** [comment]
@LoneDev6 @Andre601 This is a very serious problem, the server cannot work more than 1.5 hours, every time you need to restart
