### ISSUE TITLE
Cannot invoke "net.minecraft.world.item.crafting.RecipeHolder.id()" because "recipeholder" is null

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4101]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.RecipeHolder.id()" because "recipeholder" is null
        at net.minecraft.stats.ServerRecipeBook.addRecipes(ServerRecipeBook.java:39) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.level.ServerPlayer.awardRecipes(ServerPlayer.java:1953) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at ItemsAdder-1730840641714.jar/dev.lone.itemsadder.nms.recipebook.impl.RecipePacketHandler_v1_21_1.discoverRecipes(RecipePacketHandler_v1_21_1.java:225) ~[ItemsAdder-1730840641714.jar:?]
```

**Comment by nhanledev** [comment]
I still have this issue on 4.0.5 beta version. Seems like it happens randomly event if I get the item brand-new from /iaget commend and move it around the inventory
```
[13:16:26] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ItemsAdder v4.0.5-beta-3
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.RecipeHolder.id()" because "recipeholder" is null
	at net.minecraft.stats.ServerRecipeBook.addRecipes(ServerRecipeBook.java:39) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.level.ServerPlayer.awardRecipes(ServerPlayer.java:1957) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.yu.b(SourceFile:203) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.ym.c(SourceFile:87) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.ym.a(SourceFile:48) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.mm.f(SourceFile:88) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.hn.a(SourceFile:174) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at ItemsAdder_4.0.5-beta-3.jar/itemsadder.m.hn.d(SourceFile:607) ~[ItemsAdder_4.0.5-beta-3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-131-84281ce]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
	```

**Comment by LoneDev6** [comment]
I think it was related to smithing recipes not having any NMS recipe initialized. Related to: #2815
