### ISSUE TITLE
Java API for ItemsAdder not working (FontImageWrapper)

### ISSUE THREAD

**Issue by toohard2explain** [PluginBugs/Issues-ItemsAdder#4103]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

I simply started up my server and executed the command that uses the method given from the documentation to get the font images.

### Steps to reproduce the issue

1. Use the Java API with` new FontImageWrapper("twitteremojis:confirm").getString()`
2. Executing the command that uses that function
3. Read the logs

### Server version

1.21.1-131-ver/1.21.1@84281ce

### ItemsAdder Version

4.0.3

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/HOuMmpu

### Error (optional)

```shell
[22:42:31] [Server thread/WARN]: Caused by: java.lang.ExceptionInInitializerError
[22:42:31] [Server thread/WARN]: 	at neo.jar//dev.lone.itemsadder.api.FontImages.FontImageWrapper.<init>(SourceFile:21)
[22:42:31] [Server thread/WARN]: 	at neo.jar//com.aventox.neo.commands.DebugCommand.icons(DebugCommand.java:16)
[22:42:31] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[22:42:31] [Server thread/WARN]: 	... 30 more
[22:42:31] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.iP()" is null
[22:42:31] [Server thread/WARN]: 	at neo.jar//itemsadder.m.ag.<clinit>(SourceFile:114)
[22:42:31] [Server thread/WARN]: 	... 33 more
```

**Comment by Andre601** [comment]
Please share the actual code used when executing the command, so that we can check for any errors.

Also, share your current setup for including the API of itemsadder in your plugin (Current pom.xml/build.gradle setup and plugin.yml/paper-plugin.yml configuration)

**Comment by toohard2explain** [comment]
Fixed! I compiled the api inside the plugin inself via shadow and it used them instead of the plugins instances.
