### ISSUE TITLE
 ItemsAdder Custom MythicMobs 5.7.2 drop

### ISSUE THREAD

**Issue by uouiiu** [PluginBugs/Issues-ItemsAdder#4106]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

[03:45:37 ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityDeathEvent[03:45:37 WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[03:45:37 WARN]:        at ItemsAdder_4.0.3.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[03:45:37 WARN]:        at MythicMobs-5.7.2 (1).jar//io.lumine.mythic.core.drops.DropExecutor.handleEntityLootDrops(DropExecutor.java:315)
[03:45:37 WARN]:        at MythicMobs-5.7.2 (1).jar//io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:423)
[03:45:37 WARN]:        at MythicMobs-5.7.2 (1).jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[03:45:37 WARN]:        at MythicMobs-5.7.2 (1).jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[03:45:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[03:45:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:45:37 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[03:45:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[03:45:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[03:45:37 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:1007)
[03:45:37 WARN]:        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1957)
[03:45:37 WARN]:        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1858)
[03:45:37 WARN]:        at net.minecraft.world.entity.TamableAnimal.die(TamableAnimal.java:258)
[03:45:37 WARN]:        at net.minecraft.world.entity.animal.Wolf.die(Wolf.java:455)
[03:45:37 WARN]:        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1651)
[03:45:37 WARN]:        at net.minecraft.world.entity.animal.Wolf.hurt(Wolf.java:493)
[03:45:37 WARN]:        at net.minecraft.world.entity.player.Player.attack(Player.java:1383)
[03:45:37 WARN]:        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2544)
[03:45:37 WARN]:        at ModelEngine-4.0.8.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener$4.onAttack(PatchedServerGamePacketListener.java:264)
[03:45:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[03:45:37 WARN]:        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[03:45:37 WARN]:        at ModelEngine-4.0.8.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.dispatch(ServerboundInteractPacketWrapper.java:63)
[03:45:37 WARN]:        at ModelEngine-4.0.8.jar//com.ticxo.modelengine.v1_21_R1.network.patch.PatchedServerGamePacketListener.handleInteract(PatchedServerGamePacketListener.java:173)
[03:45:37 WARN]:        at ModelEngine-4.0.8.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:45)
[03:45:37 WARN]:        at ModelEngine-4.0.8.jar//com.ticxo.modelengine.v1_21_R1.network.patch.ServerboundInteractPacketWrapper.handle(ServerboundInteractPacketWrapper.java:15)
[03:45:37 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[03:45:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[03:45:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[03:45:37 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[03:45:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[03:45:37 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
[03:45:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[03:45:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583) 

### Steps to reproduce the issue

I have searched for
the author of MythicMobs.
The author of MythicMobs said that the error comes from itemsadder.
There is no way for creatures to set drops with itemsadder

### Server version

1.21.1

### ItemsAdder Version

4.0.3

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

1

### Error (optional)

```shell
1
```

### Problematic items yml configuration file (optional)

```yaml
1
```

**Comment by Andre601** [comment]
Please provide your latest.log as requested and don't fill parts of the issue template with junk info.
