### ISSUE TITLE
1.21.3 - Could not find shader: minecraft:rendertype_text (VERTEX)

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4107]
```
[12:15:55] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_text (VertexFormat[Position, Color, UV0, UV2]): Could not find shader: minecraft:rendertype_text (VERTEX)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at awb.a(SourceFile:68) ~[minecraft-1.21.3-client.jar:?]
	at bry.d(SourceFile:164) ~[minecraft-1.21.3-client.jar:?]
	at bsc.d(SourceFile:23) ~[minecraft-1.21.3-client.jar:?]
	at bry.B(SourceFile:138) ~[minecraft-1.21.3-client.jar:?]
	at bry.bA(SourceFile:123) ~[minecraft-1.21.3-client.jar:?]
	at fmg.c(SourceFile:1307) [minecraft-1.21.3-client.jar:?]
	at fmg.f(SourceFile:933) [minecraft-1.21.3-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.21.3-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_text (VertexFormat[Position, Color, UV0, UV2]): Could not find shader: minecraft:rendertype_text (VERTEX)
	at gmc.a(SourceFile:174) ~[minecraft-1.21.3-client.jar:?]
	at gmc.a(SourceFile:37) ~[minecraft-1.21.3-client.jar:?]
	at awa.a(SourceFile:14) ~[minecraft-1.21.3-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more

**Comment by LoneDev6** [comment]
Was caused by some changes in vanilla `rendertype_text.json`.
