### ISSUE TITLE
LibsDisguises\MythicMobs problem

### ISSUE THREAD

**Issue by DonPedroTV** [PluginBugs/Issues-ItemsAdder#4168]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

DonPedroTV

### What happened?

Since turning on the server, there is constant error spam. 

This happened after the plugin was updated.

When I remove LibsDisguises there is no error. But this plguin is needed for custom mobs in MythicMobs

### Steps to reproduce the issue

install mythicmobs, LibsDisguises, itemsadder and LoneLibs

### Server version

purpur-1.21.1-2329

### ItemsAdder Version

ItemsAdder version:  ItemsAdder_4.0.4

### ProtocolLib Version

ProtocolLib v5.3.0

### LoneLibs Version

LoneLibs version LoneLibs_1.0.61.jar

### Full Server Log

https://mclo.gs/iHJq7Jf#L2220

### Error (optional)

```shell
[07:15:16] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to ItemsAdder v4.0.4
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
	at ItemsAdder_4.0.4.jar/itemsadder.m.fa.a(SourceFile:136) ~[ItemsAdder_4.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1214) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1142) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callNonLivingEntityDamageEvent(CraftEventFactory.java:1276) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1280) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1266) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1262) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.item.ItemEntity.hurt(ItemEntity.java:399) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:1020) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:940) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.tick(Entity.java:880) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.item.ItemEntity.tick(ItemEntity.java:161) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1330) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1851) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
	... 30 more
```

**Comment by Andre601** [comment]
`[05:02:21] [Server thread/ERROR]:  Failed to hook into LibsDisguises. Make sure you have the latest version installed.`

Double-check you use the latest dev build of LibsDisguise

**Comment by Andre601** [comment]
Further proof you don't use an up-to-date version:
```
[05:01:13] [Server thread/ERROR]: [LibsDisguises] You're using the wrong version of Lib's Disguises for your server! This is intended for 1.12, 1.12.1, 1.12.2, 1.13, 1.13.1, 1.13.2, 1.14, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.15, 1.15.1, 1.15.2, 1.16, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.17, 1.17.1, 1.18, 1.18.1, 1.18.2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2, 1.20.3, 1.20.4!
```

**Comment by DonPedroTV** [comment]
I tested on the version Libs Disguises 10.0.44 and tested on the latest build - 1488

I posted the logs that weighed less. Because the ones with another version of Libs Disgusises weighed 15 GB

**Comment by Andre601** [comment]
> ```
> [05:01:13] [Server thread/ERROR]: [LibsDisguises] You're using the wrong version of Lib's Disguises for your server! This is intended for 1.12, 1.12.1, 1.12.2, 1.13, 1.13.1, 1.13.2, 1.14, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.15, 1.15.1, 1.15.2, 1.16, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.17, 1.17.1, 1.18, 1.18.1, 1.18.2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1, 1.20.2, 1.20.3, 1.20.4!
> ```

Well, as shown here is this most likely an issue with LD simply not supporting 1.21.1, so I will close this issue.
If you can find that a version of LD supports 1.21.1 while IA still won't work with it, let me know and we can re-open this issue.
