### ISSUE TITLE
Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4-release-3

### ISSUE THREAD

**Issue by CrayzyEyez** [PluginBugs/Issues-ItemsAdder#4171]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

came back to my server after about a month and found it wasnt working with v3.6.4 so i was gonna update to latest but v4 is only for 1.20.6 or higher so i used v3.6.4 release 3 and updated dependencies to latest and now i get stuck at spawn i know i can set black-screen to false but i have alot of stuff in design for the server with item adder and would hate for it not to show up anything

### Steps to reproduce the issue

join my server from any of the via versions possible and bam issue 

### Server version

1.20.2 for server version joinable from 1.20.2-1.21.3

### ItemsAdder Version

3.6.4 release 3

### ProtocolLib Version

#736 (Nov 8, 2024, 5:04:32 PM)

### LoneLibs Version

1.0.61

### Full Server Log

https://mclo.gs/9wO4azE

### Error (optional)

```shell
Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v3.6.4
Console22:45:04
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java:159) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(SourceFile:24) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.a(SourceFile:6) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:32) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1089) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3950-Spigot-2888990-d485cde]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[?:?]
	at ia.m.mW.a(SourceFile:267) ~[?:?]
	at ia.m.qi.at(SourceFile:189) ~[?:?]
	at ia.m.qa.a(SourceFile:209) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	... 20 more
```

### Problematic items yml configuration file (optional)

```yaml
metrics: true
update-checker: true
resource-pack:
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    lock-player: true
    hide-hud: true
    black-screen: true
    cancel-movement: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
      vanilla: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    compress-shader-files: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
  atlas_support: false
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  apply-during-chunk-load-phase: true
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
    delay_ticks: 1
  allow_other_plugins_resourcepacks: true
  notify_other_plugins_resourcepacks: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
  custom:
    mushroom: true
    chorus: true
    note: true
    wire: false
    fire: true
  convert-legacy-ia-region-files: true
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world'
  - '!example_disabled_blocks_world_*'
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
  handle-wear-held-actions-on-unexpected-inventory-changes: true
  update-legacy-items:
    enabled: true
    update_durability: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  enabled: true
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: true
    expert_users:
      delay_packets: false
      fast_packets_creation: true
      bundle_packets: false
      extract_emotes_shaders: true
  furniture:
    auto_convert_to_item_display: false
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
      automatically: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
  resourcepacks:
    log_player_install: false
    compression:
      files: true
      overlays: true
  blocks-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
effects:
  hide-scoreboard-numbers-old-clients: true
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    legacy_colors_compatibility: true
show_plugin_logo_on_enable: true
ignore-server-compatibility-check: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/f46ca763-fe1c-4dad-922b-fe835d1c7d51)

**Comment by Andre601** [comment]
ProtocolLib v5.4.0 is only for 1.21+

Please read the dev build page before just downloading stuff.

**Comment by CrayzyEyez** [comment]
Sorry  meant to give update I did read that and downgraded but I'm back with the original issue of none of the textures are loading but people can join in but it won't freeze them

**Comment by ShengXiaLio** [comment]
You can upgrade ItemsAdder to 3.6.5 and use ProtocolLib 5.3.0.

If you continue using 3.6.4-3, ProtocolLib should be 5.2.0.

In addition, it is recommended not to use Spigot anymore; Paper and Purpur might be better choices.

**Comment by CrayzyEyez** [comment]
just tried IA v3.6.5 and PLib 5.3.0 with LoneLib 1.0.58 - 1.0.61. all of which having the same problem so my guess is its prob something out dated or something in the config because I haven't added anything new on the server. I'm gonna completely delete the addons and configs and retry it to see if it works ill post back here when done to say if it did or didn't

**Comment by CrayzyEyez** [comment]
![image](https://github.com/user-attachments/assets/ae356bec-8d01-44cb-b6ab-6846142981ba)
a good 99% sure this shouldn't happen lol. I'm using lobfile and apparently all my shit is corrupted. idk how or what happened if yall know how to fix or be able to get my textures back on my pc because I my backup was lost that would be great

**Comment by CrayzyEyez** [comment]
![image](https://github.com/user-attachments/assets/3060990f-509e-48e2-92c7-d7f8917e3525)
idk what this is about

**Comment by CrayzyEyez** [comment]
nvm that because the protection from ItemAdder. ive reset all files retaining to the addon and dependencies and i still get the error with nothing more setup than a fresh install of itemadder

**Comment by CrayzyEyez** [comment]
decided to just update my server to 1.21 no error now but if someone knows how i can roll back the zip for lob file that would be great because my addon file is empty now
