### ISSUE TITLE
execution/function commands do not work when using Execute_Commands event. 

### ISSUE THREAD

**Issue by LilPhyziX** [PluginBugs/Issues-ItemsAdder#4174]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

lil_phyzix

### What happened?

I am unable to execute /function commands (exception generated in console) using the Execute_Commands item interact event. /Execute commands work, but also generate an exception in console.

*I have verified the function by running it in console and in game, both work flawlessly. I can confirm it is IA*

### Steps to reproduce the issue

1. Set up interact events for an item (right click for easier reproduction).
2. Set it so when you interact it executes a command. 
3. Set the command to execute a /execute or /function command. (Function commands do not work at all and produce an exception in console saying acceptsSuccess abstract error, while execute commands still generate the exception but work (limited))
4. Watch as the exceptions show in console when you interact. 

### Server version

Checking version, please wait...
[17:04:02] [Thread-5558/INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-131-84281ce (MC: 1.21.1)

### ItemsAdder Version

[17:05:54] [Server thread/INFO]: ItemsAdder version 4.0.4
[17:05:54] [Server thread/INFO]: Customized Minecraft without client mods!
[17:05:54] [Server thread/INFO]: Website: devs.beer
[17:05:54] [Server thread/INFO]: Author: LoneDev

### ProtocolLib Version

[17:07:04] [Server thread/INFO]: ProtocolLib version 5.3.0
[17:07:04] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[17:07:04] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:07:39] [Server thread/INFO]: LoneLibs version 1.0.60
[17:07:39] [Server thread/INFO]: Collection of libs used by my plugins
[17:07:39] [Server thread/INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/vCgDyvz

### Error (optional)

```shell
[21:24:23 WARN]: [ItemsAdder] Task #27484 for ItemsAdder v4.0.4 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'execute at Lil_PhyziX run function cratexsmp_main:example_function' in org.bukkit.craftbukkit.command.VanillaCommandWrapper(execute)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.un.g(SourceFile:130) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.id.a(SourceFile:152) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.ic.i(SourceFile:83) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.km.a(SourceFile:686) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.hi.a(SourceFile:901) ~[ItemsAdder_4.0.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.AbstractMethodError: Method itemsadder/m/uo.acceptsSuccess()Z is abstract
        at ItemsAdder_4.0.4.jar/itemsadder.m.uo.acceptsSuccess(SourceFile) ~[ItemsAdder_4.0.4.jar:?]
        at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:314) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.commands.FunctionCommand$FunctionCustomExecutor.runGuarded(FunctionCommand.java:268) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.commands.FunctionCommand$FunctionCustomExecutor.runGuarded(FunctionCommand.java:258) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.CustomCommandExecutor$WithErrorHandling.run(CustomCommandExecutor.java:23) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.CustomCommandExecutor$WithErrorHandling.run(CustomCommandExecutor.java:23) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.tasks.BuildContexts.execute(BuildContexts.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.tasks.BuildContexts$TopLevel.execute(BuildContexts.java:161) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:327) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:55) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: cratexsmp_main
items:
  diamond_battle_axe:
    display_name: Diamond Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3325
    attribute_modifiers:
      mainhand:
        attackDamage: 18.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/diamond_battle_axe.png
    events:
      interact:
        right:
          potion_effect_1:
            type: JUMP_BOOST
            amplifier: 2
            duration: 20
          potion_effect_2:
            type: SPEED
            amplifier: 1
            duration: 30
  emerald_battle_axe:
    display_name: Emerald Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3325
    attribute_modifiers:
      mainhand:
        attackDamage: 18.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/emerald_battle_axe.png
    events:
      interact:
        right:
          potion_effect_1:
            type: HERO_OF_THE_VILLAGE
            amplifier: 0
            duration: 30
          potion_effect_2:
            type: ABSORPTION
            amplifier: 1
            duration: 30
  enderite_battle_axe:
    display_name: Enderite Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3632
    attribute_modifiers:
      mainhand:
        attackDamage: 23.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/enderite_battle_axe.png
  blaze_battle_axe:
    display_name: Blaze Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3489
    attribute_modifiers:
      mainhand:
        attackDamage: 22.5
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/blaze_battle_axe.png
  frozen_battle_axe:
    display_name: Frozen Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3489
    attribute_modifiers:
      mainhand:
        attackDamage: 22.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/frozen_battle_axe.png
  iron_battle_axe:
    display_name: Iron Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 1520
    attribute_modifiers:
      mainhand:
        attackDamage: 15.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/iron_battle_axe.png
    events:
      interact:
        right:
          potion_effect_1:
            type: RESISTANCE
            amplifier: 2
            duration: 30
          potion_effect_2:
            type: STRENGTH
            amplifier: 1
            duration: 30
  lightning_battle_axe:
    display_name: Lightning Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 3976
    attribute_modifiers:
      mainhand:
        attackDamage: 22.5
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/lightning_battle_axe.png
    events:
      interact:
        right:
        right_shift:
          execute_commands_lightning:
            cmd0:
              command: 'execute as Lil_PhyziX run execute at @s run function cratexsmp_main:lightning_battle_axe_1'
              as_console: true
              delay: 1
  netherite_battle_axe:
    display_name: Netherite Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 4289
    attribute_modifiers:
      mainhand:
        attackDamage: 20.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/netherite_battle_axe.png
    events:
      interact:
        right:
          potion_effect_1:
            type: FIRE_RESISTANCE
            amplifier: 0
            duration: 60
          potion_effect_2:
            type: SLOW_FALLING
            amplifier: 4
            duration: 60
          potion_effect_3:
            type: ABSORPTION
            amplifier: 2
            duration: 20
          potion_effect_4:
            type: STRENGTH
            amplifier: 1
            duration: 20
          potion_effect_5:
            type: RESISTANCE
            amplifier: 1
            duration: 60
  echo_battle_axe:
    display_name: Echo Battle Axe
    permission: cratexsmp.battleaxes
    nbt: "{PublicBukkitValues:{\"auraskills:ignore_interact\":1b}}"
    durability:
      max_custom_durability: 4565
    attribute_modifiers:
      mainhand:
        attackDamage: 25.0
        attackSpeed: 0.9
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - items/battle_axes/echo_battle_axe.png
    events:
      interact:
        right:
          shoot_particle:
            name: SONIC_BOOM
            distance: 20
```

### Other files, you can drag and drop them here to upload. (optional)

[cratexsmp-2024-11-24T171544Z.tar.gz](https://github.com/user-attachments/files/17894164/cratexsmp-2024-11-24T171544Z.tar.gz)

**Comment by LilPhyziX** [comment]
The tar.gz file is the data pack containing the function files if needed.

**Comment by LilPhyziX** [comment]
The tar.gz file I listed is the data pack file containing thee function files if needed.

**Comment by LilPhyziX** [comment]
Sorry if there a duplicate comments. (I don't use GitHub often).

**Comment by Andre601** [comment]
You are using outdated dependencies.
Please update them.

**Comment by LilPhyziX** [comment]
@Andre601 testing. Will release an update message if issue persists after updates.

**Comment by LilPhyziX** [comment]
@PortableGames this is referring to ViaVersion. I do not use ViaVersion, and the latest Minecraft version is 1.21.3. I'm only 2 subversions behind. Give me a break.

**Comment by Andre601** [comment]
@PortableGames please leave such comments away from here.
They have nothing to do with the issue at hand and I won't tollerate any off-topic here to complain about how Lone decides to support mc versions.

**Comment by LilPhyziX** [comment]
@Andre601, after updates, the issues still persists. I still get the exception. Here is an updated error/exception. 

```[17:40:27] [Server thread/WARN]: [ItemsAdder] Task #6096 for ItemsAdder v4.0.4 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'execute as Lil_PhyziX run execute at @s run function cratexsmp_main:lightning_battle_axe_1' in org.bukkit.craftbukkit.command.VanillaCommandWrapper(execute)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.un.g(SourceFile:130) ~[ItemsAdder_4.0.4.jar:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.id.a(SourceFile:152) ~[ItemsAdder_4.0.4.jar:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.ic.i(SourceFile:83) ~[ItemsAdder_4.0.4.jar:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.km.a(SourceFile:686) ~[ItemsAdder_4.0.4.jar:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.hi.a(SourceFile:901) ~[ItemsAdder_4.0.4.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.AbstractMethodError: Receiver class itemsadder.m.uo does not define or inherit an implementation of the resolved method 'abstract boolean acceptsSuccess()' of interface net.minecraft.commands.CommandSource.
	at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:314) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.commands.FunctionCommand$FunctionCustomExecutor.runGuarded(FunctionCommand.java:268) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.commands.FunctionCommand$FunctionCustomExecutor.runGuarded(FunctionCommand.java:258) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.CustomCommandExecutor$WithErrorHandling.run(CustomCommandExecutor.java:23) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.CustomCommandExecutor$WithErrorHandling.run(CustomCommandExecutor.java:23) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.tasks.BuildContexts.execute(BuildContexts.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.tasks.BuildContexts$TopLevel.execute(BuildContexts.java:161) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:327) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:55) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 15 more

**Comment by LilPhyziX** [comment]
Seems to be an issue with ItemsAdder trying to call an undefined class or something. 
I decided to ask chat GPT just for the heck of it. Here's it's response. 

# Chat GPT's response:

***The error occurs because ItemsAdder is calling the method acceptsSuccess() in its internal class itemsadder.m.uo, but this method is abstract and has not been implemented. This results in an AbstractMethodError when the plugin tries to handle feedback from the execution of a Minecraft function. The issue is likely due to an incompatibility between ItemsAdder v4.0.4 and the Minecraft 1.21.1 or Paper API, specifically related to how command success states are processed.***

**Comment by Andre601** [comment]
Rule of thumb: Don't trust ChatGPT responses.
They are unreliable.

**Comment by LilPhyziX** [comment]
@PortableGames true. I just did it because why not lol. But I mean, it does seem to be correct. To a certain degree.

**Comment by LilPhyziX** [comment]
This issue does seem to be persistent. I hope this can be fixed soon, this is preventing me from adding functionality to my items.

**Comment by LoneDev6** [comment]
#3869 thought I had fixed it before, but seems not.
This might be caused by some bad implementation of `net.minecraft.commands.CommandSource` by `Execute_Commands`.
I will investigate more.
