### ISSUE TITLE
ItemsAdder still trying to access files in an unloaded/deleted world

### ISSUE THREAD

**Issue by Collinvh** [PluginBugs/Issues-ItemsAdder#4180]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Collinvht

### What happened?

When i delete my world, in certant cases itemsadder still tries to access it to load a chunk for a pregion
This sometimes even crashes the server

### Steps to reproduce the issue

(Note: It happens like a coinflip sometimes it does sometimes it doesn't)
1. Clone a world with itemsadder content in it (using code)
2. Unload the world (using code)
3. Delete that world (using code)
4. See results

### Server version

This server is running Paper version git-Paper-499 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9de3f75 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.5

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.59

### Full Server Log

https://mclo.gs/pyLkWMG

### Error (optional)

```shell
[16:19:04] [Server thread/ERROR]: [ItemsAdder] Empty chunk will be used to avoid problems for chunk 0.-1 | dede965a-1090-4970-9ab1-a1114d24f47dlevel0 -> /itemsadder/region/r.0.-1.pregion
[16:19:04] [Server thread/ERROR]: [ItemsAdder] Failed to load chunk '0, -1' | dede965a-1090-4970-9ab1-a1114d24f47dlevel0 -> /itemsadder/region/r.0.-1.pregion
[16:19:04] [Server thread/WARN]: java.io.FileNotFoundException: worlds/dede965a-1090-4970-9ab1-a1114d24f47dlevel0/itemsadder/region/r.0.-1.pregion (No such file or directory)
[16:19:04] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.open0(Native Method)
[16:19:04] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
[16:19:04] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
[16:19:04] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.rV.pJ(SourceFile:113)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.rV.eq(SourceFile:226)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.a(SourceFile:141)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.b(SourceFile:177)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.f(SourceFile:183)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.a(SourceFile:212)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.n(SourceFile:225)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.di.b(SourceFile:367)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.cQ.a(SourceFile:521)
[16:19:04] [Server thread/WARN]: 	at ItemsAdder_3.6.5.jar//ia.m.cY.b(SourceFile:194)
[16:19:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:19:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:19:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
[16:19:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[16:19:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
[16:19:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[16:19:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:19:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LoneDev6** [comment]
Update the plugin to the latest legacy version.
You are running an outdated version of the plugin.
