### ISSUE TITLE
Could not pass event PlayerEditBookEvent to ItemsAdder v4.0.4

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#4195]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

DOGE#1690

### What happened?

When i format book's text using ampersand like that "&a111", it shows an error in console, all config lines with a word "book" are disabled, but disabling didn't help.

### Steps to reproduce the issue

1. Open a writable book
2. Write a text with a color code using "&"
3. Close a book with saved changes and get an error

### Server version

Purpur 1.21.1-2329-803bf62 (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.4

### ProtocolLib Version

ProtocolLib v5.3.0

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/0uIFzUr

### Error (optional)

```shell
[01:20:48] [Server thread/ERROR]: Could not pass event PlayerEditBookEvent to ItemsAdder v4.0.4
java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.set(AbstractList.java:138) ~[?:?]
	at ItemsAdder_4.0.4.jar/itemsadder.m.qh.b(SourceFile:192) ~[ItemsAdder_4.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEditBookEvent(CraftEventFactory.java:1662) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.updateBookContents(ServerGamePacketListenerImpl.java:1275) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleEditBook$7(ServerGamePacketListenerImpl.java:1253) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

```yaml
metrics: true
update-checker: true
resource-pack:
  uuid: d69238f2-b7ce-30b0-8262-17cd9490f29d
  apply-during-chunk-load-phase: true
  apply-on-join: false
  hosting:
    no-host:
      enabled: false
    lobfile:
      enabled: false
    self-host:
      enabled: true
      server-ip: 185.9.145.145
      pack-port: 25616
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  atlas_support: true
  fix_force_unicode_font_images: true
  expert_users:
    allow_other_plugins_resourcepacks: false
  protect-player:
    lock-player: true
    hide-hud: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    compress-shader-files: true
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
    delay_ticks: 1
  allow_other_plugins_resourcepacks: true
  notify_other_plugins_resourcepacks: true
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  custom:
    note: true
    mushroom: true
    chorus: true
    wire: false
    fire: false
  worlds:
  - '*'
  - example_world_*
  - '*_example_nether'
  - '!example_disabled_blocks_world_*'
  - '!example_disabled_blocks_world_*'
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  hide-custom-durability-lore: true
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: true
  optimizations:
    kick_on_quickbar_spam:
      enabled: true
      ms: 200
      clicks: 6
  update-legacy-items:
    enabled: true
    update_durability: true
  show_item_durability:
    in_ia_menu: true
    in_inventory: false
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  enabled: true
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
  advanced_enchantments:
    enable_custom_enchants_in_items_configs: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: false
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  hide-scoreboard-numbers-old-clients: false
  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: false
    anvil:
      enabled: true
    legacy_colors_compatibility: true
entities:
  max-furniture-vehicles-per-chunk: 30
  custom-entitites:
    enabled: true
    emotes: false
    expert_users:
      delay_packets: false
      extract_emotes_shaders: false
  furniture:
    auto_convert_to_item_display: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      automatically: true
      all-on-join: false
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
show_plugin_logo_on_enable: true
debug:
  benchmark: false
  resourcepacks:
    log_player_install: false
    compression:
      files: true
      overlays: true
  items:
    log-files-loading: false
    log-files-reloading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  blocks-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true
```

**Comment by Andre601** [comment]
Please test if this issue persists on a Bare-bones setup with just ItemsAdder, ProtocolLib and LoneLibs, to eliminate the possability of another plugin messing with IA.

**Comment by WataLaker37821** [comment]
https://mclo.gs/DFuyC4T 

here

**Comment by LoneDev6** [comment]
This should have already been fixed during some code changes of previous updates, let me know.
