### ISSUE TITLE
Error when write in anvilgui -  java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by rageyh** [PluginBugs/Issues-ItemsAdder#4201]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

zrageyh

### What happened?

Hi lone, I have a problem: when I try to write any word on an anvilgui (using AnvilGUI API), it spams me with this error in the console for every character:

"[11:40:18 WARN]: [ItemsAdder] Task #29389 for ItemsAdder v3.6.6-legacy generated an exception
java.lang.ArithmeticException: / by zero
        at ia.m.eT.N(SourceFile:289) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at ia.m.eT.c(SourceFile:281) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at ia.m.fU.a(SourceFile:184) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:40:30 WARN]: [LightOptimizer] Loaded class net.citiz"  

### Steps to reproduce the issue

1. open an anvilgui (using (https://github.com/WesJD/AnvilGUI) api in my plugin)
2. write
3. error in console

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-387 (MC: 1.18.2)

### ItemsAdder Version

[11:44:14 INFO]: ItemsAdder version 3.6.6-legacy

### ProtocolLib Version

[11:44:35 INFO]: ProtocolLib version 5.3.0

### LoneLibs Version

[11:44:48 INFO]: LoneLibs version 1.0.61

### Full Server Log

https://api.mclo.gs/1/raw/KC4YotS

### Error (optional)

```shell
[11:46:27 WARN]: [ItemsAdder] Task #46255 for ItemsAdder v3.6.6-legacy generated an exception
java.lang.ArithmeticException: / by zero
        at ia.m.eT.N(SourceFile:289) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at ia.m.eT.c(SourceFile:281) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at ia.m.fU.a(SourceFile:184) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/fdaa277d-65fc-4df8-b923-c89037db141a

**Comment by Andre601** [comment]
Please write your issue in english so that everyone can understand it.

**Comment by rageyh** [comment]
> Please write your issue in english so that everyone can understand it.

done

**Comment by Andre601** [comment]
> Please write your issue in english so that everyone can understand it.

I have to repeat this.

**Comment by rageyh** [comment]
@LoneDev6 do you have news?
