### ISSUE TITLE
villagers parameters issues 1.19.4 - 3.6.6 legacy

### ISSUE THREAD

**Issue by Angelosso1** [PluginBugs/Issues-ItemsAdder#4218]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Hello, I have a problem with villagers. As seen in the picture, when you right click on the villager, it seems like you have traded with the villager. It takes a long time to get a profession and exit. I left the error below.

### Steps to reproduce the issue

Place a blacksmith table in front of the villager and wait for him to choose his profession. After the villager chooses his profession, right click on him and the broken villager menu will open. Also the error I showed in the console appears.

### Server version

purpur  1.19.4- 1985

### ItemsAdder Version

3.6.6 legacy 

### ProtocolLib Version

protocolib 5.3.0

### LoneLibs Version

lonelibs 1.0.61

### Full Server Log

https://mclo.gs/Syib5Vu

### Error (optional)

```shell
[20:11:51 ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-34...82])
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:267) ~[LoneLibs_1.0.61.jar:?]
        at dev.lone.LoneLibs.chat.Comp.componentToNms(Comp.java:180) ~[LoneLibs_1.0.61.jar:?]
        at ia.m.hG.onPacketSending(SourceFile:186) ~[ItemsAdder_3.6.6-legacy.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:442) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:385) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2252) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2238) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1589) ~[?:?]
        at net.minecraft.world.item.trading.Merchant.openTradingScreen(Merchant.java:41) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.startTrading(Villager.java:455) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobInteract(Villager.java:433) ~[?:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1363) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1168) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.performInteraction(ServerGamePacketListenerImpl.java:2932) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2952) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2891) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-34...82])
        at net.minecraft.util.GsonHelper.convertToString(GsonHelper.java:85) ~[?:?]
        at net.minecraft.util.GsonHelper.getAsString(GsonHelper.java:91) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$EntityTooltipInfo.create(HoverEvent.java:177) ~[?:?]
        at net.minecraft.network.chat.HoverEvent$Action.deserialize(HoverEvent.java:136) ~[?:?]
        at net.minecraft.network.chat.HoverEvent.deserialize(HoverEvent.java:80) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.getHoverEvent(Style.java:405) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:377) ~[?:?]
        at net.minecraft.network.chat.Style$Serializer.deserialize(Style.java:364) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:361) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:222) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:536) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializer.serialize(MinecraftComponentSerializer.java:263) ~[LoneLibs_1.0.61.jar:?]
        ... 44 more
[20:11:51 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutOpenWindow@7eb95a10[
    a=9
    b=net.minecraft.world.inventory.Containers@39ddbe3a
    c=translation{key='entity.minecraft.villager.librarian', args=[]}[style={hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.network.chat.ChatHoverable$b@6ce0bc0e'},insertion=ebafca5c-cdad-4dab-8497-ab8d02cb7172}]
  ]
```

### Screenshots/Videos (you can drag and drop files or paste links)

![sdsd](https://github.com/user-attachments/assets/677b5755-edda-4fcd-97b8-f8f938636e42)

**Comment by LoneDev6** [comment]
Try to downgrade LoneLibs to 1.0.58 or some older version.
https://github.com/LoneDev6/SpigotUtilities/releases/tag/LoneLibs_1.0.58
https://github.com/LoneDev6/SpigotUtilities/releases/tag/old-versions
