### ISSUE TITLE
Cleaning recipes brokes mod

### ISSUE THREAD

**Issue by ElgerElg** [PluginBugs/Issues-ItemsAdder#4219]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

After palyer joins in game, log shows that cleaned 988 recipes and other. But after some time plugin broke mod and guns not shooting. Ammo type is air.
![image](https://github.com/user-attachments/assets/2caef0c5-b856-41cc-a088-8909df5a6945)

### Steps to reproduce the issue

1. Join the server
2. Give gun from mod Timeless and classic guns
3. Try to shoot and it's not shooting

### Server version

![image](https://github.com/user-attachments/assets/45368cf2-efa1-43d9-9854-57bdfb68d915)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/ed7554ca-bcbb-4a20-b962-3857268969e0)
( I tryed to use newer version but they didn't work so)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/5c9ac878-997f-4547-8221-8745605009d9)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/02127dad-0988-42ef-be0d-6d3b1f4e8374)

### Full Server Log

no sorry

### Error (optional)

```shell
[16:15:40] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
[16:15:40] [Server thread/WARN] [/]: java.lang.ClassCastException: class net.minecraft.item.AirItem cannot be cast to class com.tac.guns.item.GunItem (net.minecraft.item.AirItem and com.tac.guns.item.GunItem are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @254449bb)
[16:15:40] [Server thread/WARN] [/]: 	at com.tac.guns.network.message.MessageReload.lambda$handle$1(MessageReload.java:67)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:203)
[16:15:40] [Server thread/WARN] [/]: 	at com.tac.guns.network.message.MessageReload.handle(MessageReload.java:50)
[16:15:40] [Server thread/WARN] [/]: 	at com.tac.guns.network.PacketHandler.lambda$registerPlayMessage$7(PacketHandler.java:99)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114)
[16:15:40] [Server thread/WARN] [/]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:248)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:240)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80)
[16:15:40] [Server thread/WARN] [/]: 	at java.base/java.util.Optional.map(Optional.java:260)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2646)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:971)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:954)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:948)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:934)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:851)
[16:15:40] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267)
[16:15:40] [Server thread/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

how to off cleaning recipes?

**Comment by ElgerElg** [comment]
I know that my version of server core is mohist it's unstable and so on but 1 month ago this problem doesn't exist. Also yeah Im using 1.16.5

**Comment by ElgerElg** [comment]
Also I reload a mod from command /datapack and get this... 
![image](https://github.com/user-attachments/assets/53d5351c-cc0a-413f-8b3f-404f70dafd00)

**Comment by ElgerElg** [comment]
Mod is load 933 recipes and plugin just cleaned them...

**Comment by ElgerElg** [comment]
I get this error and disabling itemsadder after reloading mod Guns by command /datapack

[17:30:23 WARN]: java.lang.IllegalThreadStateException
[17:30:23 WARN]:        at ia.m.gO.a(class:4699)
[17:30:23 WARN]:        at ia.nms.aa.impl.e.a(class:5178)
[17:30:23 WARN]:        at ia.nms.aW.bW.a(class:1296)
[17:30:23 WARN]:        at ia.m.O.a(class:3998)
[17:30:23 WARN]:        at ia.m.jR.a(class:6018)
[17:30:23 WARN]:        at ia.m.jS.a(class:6303)
[17:30:23 WARN]:        at ia.sh.com.jayway.jsonpath.ReadContext.a(class:1669)
[17:30:23 WARN]:        at ia.m.u.a(class:3194)
[17:30:24 WARN]:        at ia.sh.org.apache.commons.math3.geometry.euclidean.threed.Euclidean3D.a(class:6320)
[17:30:24 WARN]:        at ia.m.gY.a(class:424)
[17:30:24 WARN]:        at ia.m.q.a(class:6620)
[17:30:24 WARN]:        at ia.sh.com.jayway.jsonpath.internal.filter.ExpressionNode.a(class:3007)
[17:30:24 WARN]:        at ia.m.p.a(class:264)
[17:30:24 WARN]:        at ia.nms.nbt.nms.impl.NBTTagList_v1_19_R1_2.a(class:568)
[17:30:24 WARN]:        at ia.m.gY.a(class:6037)
[17:30:24 WARN]:        at ia.m.kA.a(class:2003)
[17:30:24 WARN]:        at ia.nms.aQ.impl.a.a(class:3124)
[17:30:24 WARN]:        at dev.lone.itemsadder.Core.OtherPlugins.Vault.GenericVault.a(class:978)
[17:30:24 WARN]:        at ia.sh.net.minidev.json.writer.CompessorMapper.a(class:1560)
[17:30:24 WARN]:        at ia.m.gT.a(class:1649)
[17:30:24 WARN]:        at ia.sh.org.apache.commons.math3.distribution.BetaDistribution.a(class:2873)
[17:30:24 WARN]:        at ia.m.cO.a(class:6541)
[17:30:24 WARN]:        at ia.m.fp.a(class:4318)
[17:30:24 WARN]:        at ia.m.jQ.a(class:2843)
[17:30:24 WARN]:        at ia.nms.aX.impl.f.a(class:6312)
[17:30:24 WARN]:        at ia.m.kc.a(class:4941)
[17:30:24 WARN]:        at ia.sh.net.minidev.json.writer.ArraysMapper$2.a(class:2260)
[17:30:24 WARN]:        at ia.nms.B.impl.v1_18_R2.a(class:1584)
[17:30:24 WARN]:        at ia.m.ct.a(class:5175)
[17:30:24 WARN]:        at ia.sh.net.minidev.json.reader.JsonWriter$9.a(class:1670)
[17:30:24 WARN]:        at dev.lone.itemsadder.Core.OtherPlugins.Glow.a(class:3856)
[17:30:24 WARN]:        at ia.sh.com.jayway.jsonpath.internal.PathRef$1.a(class:5864)
[17:30:24 WARN]:        at ia.m.fz.a(class:547)
[17:30:24 WARN]:        at ia.m.ds.a(class:4413)
[17:30:24 WARN]:        at ia.m.lh.a(class:4003)
[17:30:24 WARN]:        at ia.m.fy.a(class:5351)
[17:30:24 WARN]:        at ia.sh.org.apache.commons.math3.exception.NotANumberException.a(class:592)
[17:30:24 WARN]:        at ia.m.cc.a(class:1647)
[17:30:24 WARN]:        at ia.sh.com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider$BooleanReader.a(class:6634)
[17:30:24 WARN]:        at ia.nms.aD.impl.v1_15_R1.a(class:2164)
[17:30:24 INFO]: [ItemsAdder] Disabling ItemsAdder v3.5.0c
[17:30:24 INFO]: [ItemsAdder] [Host] Stopped self-host webserver on port: 25564

**Comment by Andre601** [comment]
You are running a Hybrid server. ItemsAdder is **only** designed for Spigot and Paper servers, not for hybrids.

In general should you avoid using Hybrid servers, as they mess up a lot more than what they add, especially internals which ItemsAdder relies on.

For the future, only report bugs that happen on a Spigot/Paper server and not on hybrids.

**Comment by ElgerElg** [comment]
> You are running a Hybrid server. ItemsAdder is **only** designed for Spigot and Paper servers, not for hybrids.
> 
> In general should you avoid using Hybrid servers, as they mess up a lot more than what they add, especially internals which ItemsAdder relies on.
> 
> For the future, only report bugs that happen on a Spigot/Paper server and not on hybrids.

Okay, I know that it's a hybrid, but there is no way to off cleaning recipes?

**Comment by Andre601** [comment]
Look, we won't provide support for Hybrid Servers. These kinds of servers mess a lot of stuff up which makes ItemsAdder incompatible. Just stop using them. There is 0 value in trying to merge mods and plugins together as issues like you encounter will be received.
