### ISSUE TITLE
EcoItems - Crafting Recipes Bug | Not pass event PrepareItemCraftEvent

### ISSUE THREAD

**Issue by Futodama** [PluginBugs/Issues-ItemsAdder#4220]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When trying to use "ItemsAdder" items in the creation recipe from another "EcoItems" plugin, an error appeared in the console.

As far as I noticed at the end of the check, what the error is, I found out the following: The error occurs when trying to reproduce a recipe from "EcoItems" where items from "ItemsAdder" were used. The result of the error is that the crafting item does not appear in the creation window.

I consider "ItemsAdder" to be the source of this error, since all the items that are used in crafting, the result of which is an axe from "EcoItems", belong to the original game and "ItemsAdder". Also, the error only comes out of the ItemsAdder. If you translate the result item to a recipe based on the same items, with the same models, but recorded in "EcoItems" - the recipe works correctly.

### Steps to reproduce the issue

1. Install ItemsAdder 
2. Install EcoItems
3. Create items in ItemsAdder
4. Create Item in EcoItems
5. Use ItemsAdder items in EcoItems craft recipe, and empty result of craft
6. See error in console.

### Server version

[19:17:33 INFO]: Checking version, please wait...
[19:17:34 INFO]: Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2328-d49ca07 (MC: 1.21.1)

### ItemsAdder Version

[19:17:19 INFO]: ItemsAdder version 4.0.4

### ProtocolLib Version

[19:17:04 INFO]: ProtocolLib version 5.3.0

### LoneLibs Version

[19:16:45 INFO]: LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/YonmHoo

### Error (optional)

```shell
[19:10:14 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v4.0.4
java.util.NoSuchElementException: null
        at java.base/java.util.ArrayList.getFirst(ArrayList.java:440) ~[?:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.ne.a(SourceFile:415) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.ne.a(SourceFile:340) ~[ItemsAdder_4.0.4.jar:?]
        at ItemsAdder_4.0.4.jar/itemsadder.m.ne.a(SourceFile:245) ~[ItemsAdder_4.0.4.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1464) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:98) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at PublicCrafters-4.13.14.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R1.CustomContainerWorkbench.slotsChanged(CustomContainerWorkbench.java:113) ~[PublicCrafters-4.13.14.jar:?]
        at PublicCrafters-4.13.14.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R1.CustomContainerWorkbench.<init>(CustomContainerWorkbench.java:88) ~[PublicCrafters-4.13.14.jar:?]
        at PublicCrafters-4.13.14.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R1.CustomTileEntityContainerWorkbench.createMenu(CustomTileEntityContainerWorkbench.java:43) ~[PublicCrafters-4.13.14.jar:?]
        at net.minecraft.world.SimpleMenuProvider.createMenu(SimpleMenuProvider.java:25) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1737) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at PublicCrafters-4.13.14.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R1.ContainerManager_v1_21_R1.openWorkbench(ContainerManager_v1_21_R1.java:160) ~[PublicCrafters-4.13.14.jar:?]
        at PublicCrafters-4.13.14.jar/io.github.bananapuncher714.crafters.listeners.InventoryOpenListener.onPlayerInteractEvent(InventoryOpenListener.java:64) ~[PublicCrafters-4.13.14.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### Problematic items yml configuration file (optional)

```yaml
reinforced_copper:
    display_name: "&fУсиленная медь"
    permission: rebuild
    lore:
     - '&eМедь, усиленная особым видом'
     - '&eперекалки и остуженная для'
     - '&eзакрепления эффекта.'
     - '&e'
     - '&eТеперь её хавтит для'
     - '&eсоздания инструментов.'
    drop:
      show_name: false
    blocked_enchants:
      - ALL
    item_flags:
      - HIDE_ATTRIBUTES
      - HIDE_DESTROYS
      - HIDE_ENCHANTS
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      - HIDE_UNBREAKABLE
    resource:
      material: arrow
      generate: true
      textures:
      - item/reinforced_copper.png
```

### Other files, you can drag and drop them here to upload. (optional)

This is the item file from "EcoItems". I attach it for re-creation if you have "EcoItems".

```yaml
item:
  item: "itemsadder:rebuild__cop_axe"
  display-name: "&fМедный топор"
  lore:
    - '&eГромоздкий и неповороливый.'
    - '&eНо это и есть его плюсы.'
  craftable: true
  recipe:
    - air
    - itemsadder:rebuild__reinforced_copper
    - itemsadder:rebuild__reinforced_copper
    - air
    - stick
    - itemsadder:rebuild__reinforced_copper
    - air
    - stick
    - itemsadder:rebuild__reinforced_copper
  recipe-give-amount: 1
base-damage: 9
base-attack-speed: 1

effects: []
conditions: []
fuels: []
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/b5124b89-54aa-468d-9ac6-26bf01de4333

**Comment by Andre601** [comment]
Hey,

If you haven't already, join the LoneDev Discord, verify yourself and join the Beta. There is currently an active Beta testing of ItemsAdder and perhaps your issue is already fixed in this version.
Would apreciate if you could test it.

Also, the attached video seems broken?

**Comment by Futodama** [comment]
https://drive.google.com/file/d/1gTAExGbTdIySWqZD8rrXLvgQpCPhDrjH/view?usp=sharing

**Comment by Futodama** [comment]
> Hey,
> 
> If you haven't already, join the LoneDev Discord, verify yourself and join the Beta. There is currently an active Beta testing of ItemsAdder and perhaps your issue is already fixed in this version. Would apreciate if you could test it.
> 
> Also, the attached video seems broken?

I am attached to your Discord, I cannot be sure that I can be useful in the beta branch. But I'll try it.

**Comment by LoneDev6** [comment]
Will share a new JAR shortly on the beta channel on my Discord server.
Make sure to join, verify your purchase and react to the beta channel so that you can access the latest 4.0.7 beta.

**Comment by Futodama** [comment]
@futodama_no_mikoto in your discord. I'm using your beta versions. However, the problems with them are only growing. And this one doesn't get fixed at all.

**Comment by LoneDev6** [comment]
Be more specific, are you still getting an error? Share it.
Explain more, thanks.

**Comment by Futodama** [comment]
Yes, already on version 1.21.3 I keep getting errors. The adjacent crafting is still not working. I can describe it in more detail in the evening.

**Comment by Futodama** [comment]
[21:24:25 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v4.0.6
java.util.NoSuchElementException: null
        at java.base/java.util.ArrayList.getFirst(ArrayList.java:440) ~[?:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.nd.a(SourceFile:415) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.nd.a(SourceFile:340) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.nd.a(SourceFile:245) ~[ItemsAdder_4.0.6.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1468) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:75) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at PublicCrafters-4.13.15.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R2.CustomContainerWorkbench.slotsChanged(CustomContainerWorkbench.java:133) ~[PublicCrafters-4.13.15.jar:?]
        at PublicCrafters-4.13.15.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R2.CustomContainerWorkbench.<init>(CustomContainerWorkbench.java:75) ~[PublicCrafters-4.13.15.jar:?]
        at PublicCrafters-4.13.15.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R2.CustomTileEntityContainerWorkbench.createMenu(CustomTileEntityContainerWorkbench.java:43) ~[PublicCrafters-4.13.15.jar:?]
        at net.minecraft.world.SimpleMenuProvider.createMenu(SimpleMenuProvider.java:25) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:2006) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at PublicCrafters-4.13.15.jar/io.github.bananapuncher714.crafters.implementation.v1_21_R2.ContainerManager_v1_21_R2.openWorkbench(ContainerManager_v1_21_R2.java:160) ~[PublicCrafters-4.13.15.jar:?]
        at PublicCrafters-4.13.15.jar/io.github.bananapuncher714.crafters.listeners.InventoryOpenListener.onPlayerInteractEvent(InventoryOpenListener.java:64) ~[PublicCrafters-4.13.15.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:544) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2035) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1624) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1601) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1594) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1545) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1555) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1391) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]

**Comment by Futodama** [comment]
[21:21:43 INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.6
[21:21:44 INFO]: [ItemsAdder]
                                                   ItemsAdder 4.0.6
  ___  ___        __        __   __   ___  __      LoneLibs 1.0.63
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     ProtocolLib 5.4.0-SNAPSHOT-739
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur 1.21.3-2358-16ce24a (MC: 1.21.3)
                                                   Build Date: 2024-12-19_14.54.20
                                                   Java Version: 23.0.1
                                                   OS: Windows 11 10.0
[21:21:45 INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 8163

**Comment by Futodama** [comment]
![image](https://github.com/user-attachments/assets/4c5a1f44-0e84-4760-a1f8-98a5bb350d24)
![image](https://github.com/user-attachments/assets/85168791-19ab-47cc-904f-d03717fc8cac)

**Comment by Futodama** [comment]
Hi. There is still a problem with using IA items in another plugin. EcoItems plugin support has assured that the issue is not on their side.

**Comment by Futodama** [comment]
If you have the time and opportunity, I would like to help you solve this problem in some way. However, I don't understand how. Please give me some kind of plugin or IA version with which I could provide you with all the information about the server, and the processes that are going on at the time of operation and where the problem is.

**Comment by Futodama** [comment]
[22:05:46] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v4.0.7
[22:05:47] [Server thread/INFO]: [ItemsAdder] 
                                                   ItemsAdder 4.0.7
  ___  ___        __        __   __   ___  __      LoneLibs 1.0.63
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     ProtocolLib 5.4.0-SNAPSHOT-739
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur 1.21.3-2358-16ce24a (MC: 1.21.3)
                                                   Build Date: 2025-01-23_16.53.39
                                                   Java Version: 23.0.1
                                                   OS: Windows 11 10.0
[22:05:49] [Server thread/INFO]: [ItemsAdder] [Host] Starting self-host webserver on port: 8163

**Comment by Futodama** [comment]
I still can't create items using ItemsAdder ingots.

**Comment by Futodama** [comment]
The problem has not gone away
