### ISSUE TITLE
java.io.FileNotFoundException When generating pack with clean installation

### ISSUE THREAD

**Issue by Foxxite** [PluginBugs/Issues-ItemsAdder#4268]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

articca

### What happened?

When starting the Server with Items Adder and Cosmetics Core the following error shows up:

### Steps to reproduce the issue

1. Install Items Adder
2. Install Cosmetics Core
3. Start the server

### Server version

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

[22:30:37 INFO]: ItemsAdder version 4.0.6
[22:30:37 INFO]: Customized Minecraft without client mods!
[22:30:37 INFO]: Website: devs.beer
[22:30:37 INFO]: Author: LoneDev

### ProtocolLib Version

[22:30:54 INFO]: ProtocolLib version 5.3.0
[22:30:54 INFO]: Provides read/write access to the Minecraft protocol.
[22:30:54 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[22:31:07 INFO]: LoneLibs version 1.0.63
[22:31:07 INFO]: Collection of libs used by my plugins
[22:31:07 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/ZTRw4Uo

### Error (optional)

```shell
[22:27:48 WARN]: [ItemsAdder] Plugin ItemsAdder v4.0.6 generated an exception while executing task 2291
java.lang.RuntimeException: java.io.FileNotFoundException: /home/container/plugins/ItemsAdder/output/generated.zip (No such file or directory)
        at ItemsAdder_4.0.6.jar/itemsadder.m.aci.ny(SourceFile:263) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.adt.a(SourceFile:75) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.rg.g(SourceFile:66) ~[ItemsAdder_4.0.6.jar:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.ag.a(SourceFile:989) ~[ItemsAdder_4.0.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.FileNotFoundException: /home/container/plugins/ItemsAdder/output/generated.zip (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213) ~[?:?]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152) ~[?:?]
        at ItemsAdder_4.0.6.jar/itemsadder.m.aci.ny(SourceFile:251) ~[ItemsAdder_4.0.6.jar:?]
        ... 9 more
```

**Comment by Andre601** [comment]
On a first look, it seems ItemsAdder wasn't able to create the Zip file. Possibly due to lack of permissions on the operating system.
This is further supported by the fact, that Bluemap also reports missing files, which I assume also should've been extracted/created automatically, but haven't.

So please double check that the server and plugins actually have necessary permissions to write files.

Also, please test on a setup with just ItemsAdder and its dependencies to confirm it isn't caused by other plugins.
Finally, disable the `allow_other_plugins_resourcepacks` option reported by ItemsAdder to also confirm it isn't caused by other plugins resource packs.

**Comment by Foxxite** [comment]
Running the server with only these 3 plugins:
```
[09:51:22 INFO]: Server Plugins (3):
[09:51:22 INFO]: Bukkit Plugins:
[09:51:22 INFO]:  - ItemsAdder, LoneLibs, ProtocolLib
```

With the ItemsAdder folder completely cleared on start. Saw nothing. 
Restarting the server, the error shows up.
I did this both on the Pterodactyl hosted server as well as running the server on my windows system. So it's unlikely to be a file system permission error, especially since all other plugins files do get created correctly.

Unrelated, Blue Maps was configured incorrectly causing those errors.

-----

Did a bit more playing around and it might be an order of operations error. After running /iazip the error went away and the zipfile was created.

**Comment by LoneDev6** [comment]
- Disable all hosting methods in `config.yml`
- Start the server
- Run `/iazip` to generate the pack
- enable an hosting method in `config.yml`
- reload using `/iareload`

Let me know if the issue is fixed.

**Comment by LoneDev6** [comment]
This was already fixed in 4.0.12
