### ISSUE TITLE
[BUG] Concurrent modification on login after restart

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#495]
```
>.... [11:38:42 WARN]: [ItemsAdder] Plugin ItemsAdder v2.1.19 generated an exception while executing task 6667
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_252]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_252]
at dev.lone.itemsadder.Core.Recipes.Cooking.CustomCookingRecipesManager.getRecipesForItem(CustomCookingRecipesManager.java:92) ~[?:?]
at dev.lone.itemsadder.Core.Recipes.Cooking.CustomCookingRecipesManager.getRecipesForItemAndUsingItem(CustomCookingRecipesManager.java:113) ~[?:?]
at dev.lone.itemsadder.GUI.CustomItemGUI.lambda$new$0(CustomItemGUI.java:74) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-246]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-246]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by LoneDev6** [comment]
Never got another report from that, may reopen it only if happens again
