### ISSUE TITLE
Not loading correctly items with custom models

### ISSUE THREAD

**Issue by RicardormDev** [PluginBugs/Issues-ItemsAdder#538]
**Describe the bug**
Not loading the items correctly and displaying this on console.

Basically this happens when you add multiple items to the sections 'items:'
[Configration](https://hastebin.com/obuxojamom.yaml)
[Console Error](https://hastebin.com/fiduhadalu.shell)

**To Reproduce**
1. Create a new workspace
2. Add multiple items to it.
3. Do /iareload 

**Expected behavior**
Loading correctly each item.

**Info (please complete the following information):**
![image](https://user-images.githubusercontent.com/8129679/100977730-06334a80-3507-11eb-8d0a-71d446f3b96a.png)

**Comment by LoneDev6** [comment]
I'm sorry but hastebin website is down so I cannot read the logs.

Anyway please make sure to use this tool to validate your files and identify errors: https://ide.plugin.ga/itemsadder/

**Comment by RicardormDev** [comment]
It seems to be good,

```.... [07:24:07 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
>.... [07:24:07 WARN]: java.lang.ClassCastException: org.bukkit.configuration.MemorySection incompatible with java.lang.Comparable
>.... [07:24:07 WARN]: at java.util.Collections$ReverseComparator.compare(Unknown Source)
>.... [07:24:07 WARN]: at java.util.Map$Entry.lambda$comparingByValue$827a17d5$1(Unknown Source)
>.... [07:24:07 WARN]: at java.util.Map$Entry$$Lambda$5924.000000004DB09B30.compare(Unknown Source)
>.... [07:24:07 WARN]: at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
>.... [07:24:07 WARN]: at java.util.TimSort.sort(Unknown Source)
>.... [07:24:07 WARN]: at java.util.Arrays.sort(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
>.... [07:24:07 WARN]: at java.util.stream.ReferencePipeline.collect(Unknown Source)
>.... [07:24:07 WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:1652)
>.... [07:24:07 WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:644)
>.... [07:24:07 WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:348)
>.... [07:24:07 WARN]: at dev.lone.itemsadder.f.b$$Lambda$5843.000000004E847FD0.accept(Unknown Source)
>.... [07:24:07 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:101)
>.... [07:24:07 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [07:24:07 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3055.00000000FDEF96C0.run(Unknown Source)
>.... [07:24:07 WARN]: at java.lang.Thread.run(Unknown Source)```

**Comment by LoneDev6** [comment]
> Anyway please make sure to use this tool to validate your files and identify errors: https://ide.plugin.ga/itemsadder/
