### ISSUE TITLE
[BUG] ProjectileLaunchEvent NoSuchMethodError getItemStack (1.14.4)

### ISSUE THREAD

**Issue by KinderCrowd602** [PluginBugs/Issues-ItemsAdder#595]
Hello LoneDev i discovered a weird bug with event! When some player charge and shoot crossbow its write an error with ProjectileLaunchEvent so everytime when player shoot with crossbow it spams my console alot of!

This Is The Error:

[12:36:34] [Server thread/ERROR]: Could not pass event ProjectileLaunchEvent to ItemsAdder v2.1.27
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1130) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:531) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:969) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:894) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.ItemCrossbow.a(ItemCrossbow.java:235) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.ItemCrossbow.a(ItemCrossbow.java:276) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.ItemCrossbow.a(ItemCrossbow.java:48) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:301) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:384) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1293) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Arrow.getItemStack()Lorg/bukkit/inventory/ItemStack;
	at dev.lone.itemsadder.k.k.a(SourceFile:915) ~[ItemsAdder.jar:?]
	at dev.lone.itemsadder.Core.f.c.c.b(SourceFile:348) ~[ItemsAdder.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
	... 26 more
[12:36:48]

Thats it the problem!

 - Server version: 1.14.4
 - Client version: Badlion Client 1.14.4
 - Plugin version:  2.1.27

**Comment by LoneDev6** [comment]
Thanks! I will fix it this week, I think it's due to 1.14.4 missing a method I use to detect item used in the projectile event.
I hope to find a way to fix that since it may not be possible.

I suggest you to consider updating to 1.15.2 as 1.14.4 is not that great in terms of performance and stability.

have a nice day!

**Comment by LoneDev6** [comment]
Thanks this will be fixed in next update
