### ISSUE TITLE
[BUG] throw potion error

### ISSUE THREAD

**Issue by kamyu1537** [PluginBugs/Issues-ItemsAdder#600]
**Describe the bug**
error is printed to the console
```
[00:38:46 ERROR]: Could not pass event ProjectileLaunchEvent to ItemsAdder v2.1.27
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftThrownPotion cannot be cast to class org.bukkit.entity.SplashPotion (org.bukkit.craftbukkit.v1_16_R3.entity.CraftThrownPotion and org.bukkit.entity.SplashPotion are in unnamed module of loader 'app')
        at dev.lone.itemsadder.k.k.a(SourceFile:923) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.c.b(SourceFile:348) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1294) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:606) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1763) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1659) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.ItemPotionThrowable.a(ItemPotionThrowable.java:20) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.ItemLingeringPotion.a(ItemLingeringPotion.java:12) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:379) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:447) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1625) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1321) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-"1d169e7"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. throw potion (splash, lingering potion)

**Expected behavior**
no error

**Screenshots**
none

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5
 - Client version: fabric 1.16.5
 - Plugin version: 2.1.27

**Additional context**

**Comment by LoneDev6** [comment]
Thanks! This should be fixed in the upcoming release of the plugin
