### ISSUE TITLE
[BUG] Nor sure what is it, PacketEvent.

### ISSUE THREAD

**Issue by waylun1990** [PluginBugs/Issues-ItemsAdder#608]
[11:13:48 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemsAdder
java.lang.IllegalStateException: The packet event is read-only.
at com.comphenix.protocol.events.PacketEvent.setCancelled(PacketEvent.java:315) ~[?:?]
at dev.lone.itemsadder.Core.f.a.b.a.a(SourceFile:105) ~[?:?]
at dev.lone.itemsadder.Core.f.a.b.b.onPacketReceiving(SourceFile:67) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) ~[?:?]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.16.4.jar:git-Paper-416]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.4.jar:git-Paper-416]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
>.... [11:13:48 ERROR]: Parameters:
net.minecraft.server.v1_16_R3.PacketPlayInUseEntity@40ea98bb[
a=983
action=ATTACK
c=<null>
d=<null>
e=false

**Comment by LoneDev6** [comment]
Does this happens only when a user removes furnitures I suppose?

**Comment by waylun1990** [comment]
well, not really a player removes furniture, I'm not so sure about that, but basicly nothing change, all feature are good as well
just console showing this every ~15 ~20 mins. and thanks for reply. thank you, looking forward the fix version show.

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming update, thanks a lot
