### ISSUE TITLE
RPGMoney - Could not pass event InventoryClickEvent to RPGMoney v1.1.26

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ItemsAdder#617]
```

[09:59:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RPGMoney v1.1.26
--
3751 | java.lang.NullPointerException: null
3752 | at com.evill4mer.RealMoney.RealMoney.d(SourceFile:607) ~[?:?]
3753 | at com.evill4mer.RealMoney.RealMoney.c(SourceFile:598) ~[?:?]
3754 | at com.evill4mer.RealMoney.c.b.a(SourceFile:403) ~[?:?]
3755 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1538.execute(Unknown Source) ~[?:?]
3756 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-253]
3757 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
3758 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
3759 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
3760 | at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2437) ~[patched_1.16.3.jar:git-Paper-253]
3761 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-253]
3762 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-253]
3763 | at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-253]
3764 | at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
3765 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
3766 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
3767 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
3768 | at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
3769 | at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
3770 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
3771 | at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
3772 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
3773 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
3774 | at java.lang.Thread.run(Thread.java:834) [?:?]



```

**Comment by LoneDev6** [comment]
Thanks, i will fix it today

**Comment by LoneDev6** [comment]
Done
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-rpgmoney-money-with-custom-texture-no-mods.25392/
