### ISSUE TITLE
[BUG] i have this error

### ISSUE THREAD

**Issue by waylun1990** [PluginBugs/Issues-ItemsAdder#703]
hi Lone.

i meet this issues and my mob egine, does not fit in. 
[https://gyazo.com/59bf0d95bfb915c191340aaa535dc1f3]

thank you very much.

.. [05:36:13 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemsAdder
java.lang.NullPointerException: null
at dev.lone.itemsadder.Core.f.a.b.b.b.a.g(SourceFile:252) ~[?:?]
at dev.lone.itemsadder.Core.f.a.b.b.b.a.L(SourceFile:66) ~[?:?]
at dev.lone.itemsadder.Core.f.a.b.b.b.d.onPacketReceiving(SourceFile:155) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) ~[?:?]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Airplane-"4b9dd63"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by LoneDev6** [comment]
As always, please include the plugin version or I can't identify the issue
