### ISSUE TITLE
[BUG] ia menu texture not showing

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#715]
**Describe the bug**
The texture for the /ia menu will not show, and neither will custom categories, all the other textures still work, and the menu still functions, so it's not that big of a problem

**To Reproduce**
i have no idea, but I have an error log

[15:56:04 ERROR]: Cannot load plugins/ItemsAdder/ia_gui.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 1, column 1:
    settings:
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 125, column 3:
      staffs:
      ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.5.jar:git-Paper-491]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.5.jar:git-Paper-491]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.5.jar:git-Paper-491]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.16.5.jar:git-Paper-491]
	at dev.lone.itemsadder.j.e.<init>(SourceFile:71) ~[?:?]
	at dev.lone.itemsadder.j.e.<init>(SourceFile:45) ~[?:?]
	at dev.lone.itemsadder.j.e.<init>(SourceFile:77) ~[?:?]
	at dev.lone.itemsadder.h.d.<init>(SourceFile:38) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:1508) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-491]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-491]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-491]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 1, column 1:
    settings:
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 125, column 3:
      staffs:
      ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-491]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-491]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-491]
	... 14 more
[15:56:05 INFO]: brendaWCKD250[/73.247.9.227:51962] logged in with entity id 317 at ([world]-3265.589330991517, 73.0, -1961.0726676235834)
[15:56:05 INFO]: [PlaceholderAPI] Successfully registered expansion: img
[15:56:05 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.categories_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[15:56:05 INFO]: [ItemsAdder] Loaded 47 categories
[15:56:05 INFO]: [ItemsAdder] Loaded items and stuff in 4177ms
[15:56:05 ERROR]: Could not pass event ItemsAdderFirstLoadEvent to ChestCommands v4.0.0-SNAPSHOT
**Expected behavior**
the texture to work

**Screenshots**
![image](https://user-images.githubusercontent.com/79489385/109433472-722a2f80-79de-11eb-834e-10e6e08768db.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: vanilla 1.16.5
 - Plugin version: 2.1.42

**Additional context**
I might of messed up the config, but I couldn't find anything wrong when I went through it, and couldn't find anything wrong, but I'm not sure

**Comment by LoneDev6** [comment]
Use the official tool to write your configs to avoid this type of errors.
Surely something has too many spaces and it's not aligned correctly

https://ide.plugin.ga/itemsadder/
