### ISSUE TITLE
[BUG] Failed to download default resourcepack.

### ISSUE THREAD

**Issue by ryanrox333** [PluginBugs/Issues-ItemsAdder#717]
**Describe the bug**
When I load ItemsAdder, I cannot do the First Setup because it does not connect to matteodev.it

**Expected behavior**
The plugin downloads the pack with no issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/44746268/109520528-55dbd080-7a7a-11eb-9698-a59f7eee8195.png)

**Info:**
 - Server version: Spigot 1.16.4
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.42

**Additional context**
Here is the text version of the error above.
```
[09:47:20] [Craft Scheduler Thread - 2/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:20] [Craft Scheduler Thread - 2/ERROR]: [ItemsAdder]     Failed to download default resourcepack, retrying... ( java.net.UnknownHostException: matteodev.it )
[09:47:21] [Server thread/INFO]: -------< LightAPI-fork 3.4.6 >-------
[09:47:21] [Server thread/INFO]: You are running the latest version!
[09:47:22] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[09:47:23] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:23] [Craft Scheduler Thread - 3/ERROR]: [ItemsAdder]     Failed to download default resourcepack, retrying... ( java.net.UnknownHostException: matteodev.it )
[09:47:25] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[09:47:26] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:26] [Craft Scheduler Thread - 3/ERROR]: [ItemsAdder]     Failed to download default resourcepack, retrying... ( java.net.UnknownHostException: matteodev.it )
[09:47:28] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[09:47:28] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:28] [Craft Scheduler Thread - 3/ERROR]: [ItemsAdder]     Failed to download default resourcepack, retrying... ( java.net.UnknownHostException: matteodev.it )
[09:47:31] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[09:47:31] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:31] [Craft Scheduler Thread - 4/ERROR]: [ItemsAdder]     Failed to download default resourcepack, retrying... ( java.net.UnknownHostException: matteodev.it )
[09:47:34] [Craft Scheduler Thread - 0/INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[09:47:34] [Craft Scheduler Thread - 0/INFO]: [ItemsAdder]     Downloading default resourcepack...
[09:47:34] [Craft Scheduler Thread - 0/ERROR]: [ItemsAdder]    Failed to download default resourcepack, check your internet connection. Seems the server cannot download it from my website. Ask your host service if it blocks internet access.
[09:47:34] [Craft Scheduler Thread - 0/ERROR]: [ItemsAdder] It's important to let the plugin download the default resourcepack at its first installation or it won't work! After first download you can disable the website again.
[09:47:34] [Craft Scheduler Thread - 0/ERROR]: [ItemsAdder] matteodev.it
[09:47:34] [Craft Scheduler Thread - 0/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.42
[09:47:34] [Craft Scheduler Thread - 0/ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v2.1.42 (Is it up to date?)
java.lang.IllegalStateException: PluginDisableEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:370) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at dev.lone.itemsadder.Resourcepack.b.aK(SourceFile:476) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-37d799b-3eb7236]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```

**Comment by ryanrox333** [comment]
Is it possible to do this directly?

**Comment by LoneDev6** [comment]
sure, open a ticket on my discord server and I will send you the required files.
Seems your hosting is blocking access to my website to download the needed resourcepack files.

https://support.plugin.ga

**Comment by ryanrox333** [comment]
My spigot didn't link over the discord.
