### ISSUE TITLE
[BUG] Custom block cannot be loaded correctly

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#725]
**Describe the bug**
Very strange question, I don't even know how to describe it.

**Info (please complete the following information):**
 - Server version: paper1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.1.42

**Additional context**
[08:36:02 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.1.42
java.lang.NullPointerException: null
        at dev.lone.itemsadder.Core.b.a(SourceFile:1896) ~[?:?]
        at dev.lone.itemsadder.Core.b.a(SourceFile:1918) ~[?:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b.b.d(SourceFile:458) ~[?:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b.b.b(SourceFile:383) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-508]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-508]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-508]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.a(World.java:612) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:570) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:2208) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:482) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.a(World.java:449) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.World.a(World.java:553) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.IWorldWriter.a(IWorldWriter.java:20) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.IWorldWriter.b(IWorldWriter.java:16) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.BlockChorusFruit.tickAlways(SourceFile:61) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:565) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:808) ~[patched_1.16.5.jar:git-Paper-508]
        at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:47) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:466) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1362) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-508]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-508]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by LoneDev6** [comment]
Can you try without optifine?
let me know, thanks

**Comment by killertuling** [comment]
I didn't delete the block either...
I used opfine, but I don't know how to reproduce it

**Comment by LoneDev6** [comment]
Can you please try without optifine?
Thanks

**Comment by killertuling** [comment]
There is no problem when optifine is not installed.

**Comment by LoneDev6** [comment]
It's a optifine bug, please report the bug on optifine github and include your video.
Don't include the itemsadder error as it has nothing to do with the clientside fps drop you see
