### ISSUE TITLE
[BUG] ProjectileLaunchEvent error

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#733]
**Describe the bug**
When im shooting arrow ill get this on console:

[19:00:43 ERROR]: Could not pass event ProjectileLaunchEvent to ItemsAdder v2.1.42
java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.entity.Arrow.getItemStack()'
        at dev.lone.itemsadder.j.l.a(SourceFile:925) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.c.b(SourceFile:348) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-208]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-208]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-208]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-208]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1248) ~[patched_1.15.2.jar:git-Paper-208]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:557) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1251) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1153) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.ItemBow.a(ItemBow.java:82) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.ItemStack.a(ItemStack.java:563) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.EntityLiving.clearActiveItem(EntityLiving.java:3061) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1315) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-208]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-208]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Screenshots**
![image](https://user-images.githubusercontent.com/21358664/110491316-9a1a4100-810a-11eb-9777-895fd4a2f2e4.png)

 - Server version: paper 1.15.2
 - Client version: vanilla 1.15.2
 - Plugin version: 2.1.42

**Additional context**
im also tested this on clear server and this error dont disappear.
i have latest lonelibs installed.

**Comment by LoneDev6** [comment]
Will be fixed
