### ISSUE TITLE
BetterHud with ItemAdder occured bug on paper[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#736]
**Describe the bug**
When I try to change from spigot to paper, ItemAdder and BetterHUd encounter errors, the HUD constantly shifts to the left and there are errors in the console.

**To Reproduce**
1. Install ItemAdder
2. Install BetterHud
3. Run Paper 1.16.4

**Error log**
`[18:21:39 WARN]: [ItemsAdder] Plugin ItemsAdder v2.1.42 generated an exception while executing task 4031
>java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
at dev.lone.itemsadder.Core.d.a.a.j(SourceFile:45) ~[?:?]
at dev.lone.itemsadder.Core.d.b.a.l(SourceFile:101) ~[?:?]
at dev.lone.itemsadder.Core.d.b.a.p(SourceFile:88) ~[?:?]
at dev.lone.itemsadder.Core.d.b.a.o(SourceFile:108) ~[?:?]
at dev.lone.itemsadder.Core.d.b.b.d(SourceFile:272) ~[?:?]
at dev.lone.itemsadder.Core.d.b.b.v(SourceFile:164) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-416]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-416]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-416]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Expected behavior**
The Hud should not shift, and no errors in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/39553613/110772755-d33cd900-8210-11eb-8e82-f6ee6902e98f.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.4
 - Client version: 1.16.4
 - Plugin version: 2.1.42 (ItemAdder) 
 - 2.0.1.1(BetterHUd)

**Additional context**
Betterhud config
https://paste.ubuntu.com/p/TKbHGp6Y3s/
ItemAdder config
https://paste.ubuntu.com/p/v62rnk79jk/

**Comment by LoneDev6** [comment]
please update to latest version and send the new error log, thanks

**Comment by Caishangqi** [comment]
> please update to latest version of itemsadder and send the new error log, thanks

The new error log

`[20:15:54 WARN]: [ItemsAdder] Plugin ItemsAdder v2.2.1 generated an exception while executing task 1498
>java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
at dev.lone.itemsadder.Core.d.a.a.l(SourceFile:56) ~[?:?]
at dev.lone.itemsadder.Core.d.b.a.p(SourceFile:85) ~[?:?]
at dev.lone.itemsadder.Core.d.b.a.o(SourceFile:108) ~[?:?]
at dev.lone.itemsadder.Core.d.b.b.d(SourceFile:272) ~[?:?]
at dev.lone.itemsadder.Core.d.b.b.v(SourceFile:164) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-416]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-416]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-416]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Caishangqi** [comment]
> please update to latest version of itemsadder and send the new error log, thanks

The entire log:
https://paste.ubuntu.com/p/3knHg54C22/

**Comment by LoneDev6** [comment]
are you sure this happens only in the new versions of paper but worked fine in old versions?

**Comment by Caishangqi** [comment]
> are you sure this happens only in the new versions of paper but worked fine in old versions?

The plugin add-ons only work for 1.16.4, so I can not use 1.16.5 Paper. The add-ons work properly on 1.16.4 spigot but occurred bug on 1.16.4 paper.

**Comment by LoneDev6** [comment]
Last update of BetterHuds should have fixed these issues, anyway the dev is working on another hotfix to fix some little problems with the addon, so please wait some days and check the upcoming version of BetterHuds.
If the issue is still there please comment here again.

Thanks

**Comment by Caishangqi** [comment]
> Last update of BetterHuds should have fixed these issues, anyway the dev is working on another hotfix to fix some little problems with the addon, so please wait some days and check the upcoming version of BetterHuds.
> If the issue is still there please comment here again.
> 
> Thanks

Thanks, I had tried the latest version of BetterHUd, it have some problem with loading fonts, I will waited for the updated 👍
