### ISSUE TITLE
[BUG] Portable bags do not support custom nbt texture heads

### ISSUE THREAD

**Issue by GeistFighter** [PluginBugs/Issues-ItemsAdder#746]
**Describe the bug**
Portable bags do not support custom nbt texture heads

**To Reproduce**
1. Go to your Portable bags
2. Open it
3. Place a head with nbt custom texture
4. Close and open

**Expected behavior**
To be able to make it possible to put this kind of object in the bags.

**Screenshots**
![image](https://user-images.githubusercontent.com/42804270/111082003-58243d00-8506-11eb-9d7c-62b93d09a563.png)

**Info (please complete the following information):**
 - Server version: paper 1.8.8
 - Client version: Optifine 1.8.8
 - Plugin version: 1.3.1

** If we put a head with nbt custom in the /ebp it stays there unlike the handbag but an error in the console happens **
[20:48:39 ERROR]: Could not pass event InventoryCloseEvent to EpicBackpacks v1.3.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:852) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1411) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:173) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at dev.lone.EpicBackpacks.d.b(Unknown Source) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor520.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 16 more

**Comment by GeistFighter** [comment]
not goob plugins
