### ISSUE TITLE
[BUG] Spawning mobs with egg on the new REAL_NOTE blocks

### ISSUE THREAD

**Issue by shmezi** [PluginBugs/Issues-ItemsAdder#754]
It creates the following error:
[08:40:15 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.2.2 java.lang.IllegalArgumentException: Cannot get data for not block SHEEP_SPAWN_EGG at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:495) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2200) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2175) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.Bukkit.createBlockData(Bukkit.java:1693) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.Material.createBlockData(Material.java:3647) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.setType(CraftBlock.java:173) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.setType(CraftBlock.java:167) ~[patched_1.16.5.jar:git-Paper-496] at dev.lone.itemsadder.Core.f.a.b.b.b.f.a(SourceFile:176) ~[?:?] at dev.lone.itemsadder.Core.f.a.b.b.b.f.i(SourceFile:128) ~[?:?] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-496] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.5.jar:git-Paper-496] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-496]

**Comment by LoneDev6** [comment]
will be fixed
