### ISSUE TITLE
Bug with Chest Commands and AdvancedEnchantments and itemadder 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#766]
**Describe the bug**
When you set | 
```
ACTIONS:
    - 'enchanter'
```
![image](https://user-images.githubusercontent.com/68678154/111561811-be76bd00-879d-11eb-82c3-e05c56645949.png)
ite's working | with spawn any another command but with enchanter the problem comes 
-
```
[02:51:59 WARN]: [ItemsAdder] Task #9145 for ItemsAdder v2.2.4 generated an exception
java.lang.UnsupportedOperationException: Unable to construct this menu by type
at net.minecraft.server.v1_16_R3.Container.getType(Container.java:75) ~[patched_1.16.5.jar:git-Paper-520]
at dev.lone.itemsadder.k.b.j.h.e(SourceFile:18) ~[?:?]
at dev.lone.itemsadder.g.e.a(SourceFile:523) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-520]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-520]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Paper-520]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-520]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-520]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-520]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-520]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**To Reproduce**
1. Downlode the chestcommands , AdvancedEnchantments , | **notice** | I tried the chestcommands original version and the 
chest command | and Chest Commands FORK (+ ItemsAdder compatibility) 4.0.0 all the same problem .
2. Change the ACTIONS: enchanter

**Info (please complete the following information):**
 - Server version: ( paper 1.16.5)
 - Client version: ( Vanilla 1.16.5)
 - Plugin version: ( 2.2.4 )

**Additional context**
i Really Don't know Where the Problem come from but I think it's Coding problem xD

**Comment by LoneDev6** [comment]
I don't understand where you set this setting nor what are you trying to do
```yml
ACTIONS:
    - 'enchanter'
```

**Comment by SNokerYT** [comment]
This is a Chest Commands | Config.yml
![image](https://user-images.githubusercontent.com/68678154/111627429-b6e40200-87f7-11eb-8b50-424150da34a6.png)
When the ACTIONS is enchanter the error comes on console and not working

**Comment by LoneDev6** [comment]
it's because of "keep-open", set it to false
