### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by dingods** [PluginBugs/Issues-ItemsAdder#776]
[11:37:32 INFO]: [ItemsAdder] Enabling ItemsAdder v2.1.3
[11:37:32 INFO]: [ItemsAdder] ------ ItemsAdder ------
[11:37:32 INFO]: [ItemsAdder]   _____ _                                 _     _
[11:37:32 INFO]: [ItemsAdder]  |_   _| |                       /\      | |   | |
[11:37:32 INFO]: [ItemsAdder]    | | | |_ ___ _ __ ___  ___   /  \   __| | __| | ___ _ __
[11:37:32 INFO]: [ItemsAdder]    | | | __/ _ \ '_ ` _ \/ __| / /\ \ / _` |/ _` |/ _ \ '__|
[11:37:32 INFO]: [ItemsAdder]   _| |_| ||  __/ | | | | \__ \/ ____ \ (_| | (_| |  __/ |
[11:37:32 INFO]: [ItemsAdder]  |_____|\__\___|_| |_| |_|___/_/    \_\__,_|\__,_|\___|_|
[11:37:32 INFO]: [ItemsAdder]
[11:37:32 INFO]: [ItemsAdder]
[11:37:32 INFO]: [ItemsAdder] Loading data...
[11:37:32 ERROR]: Error occurred while enabling ItemsAdder v2.1.3 (Is it up to date?)
java.lang.IllegalStateException: FastInv is already registered
        at fr.mrmicky.fastinv.FastInvManager.register(FastInvManager.java:37) ~[?:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:949) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1022]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[11:37:32 INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.3
[11:37:32 ERROR]: Error occurred while disabling ItemsAdder v2.1.3 (Is it up to date?)
java.lang.IllegalArgumentException: listener cannot be NULL
        at com.comphenix.protocol.injector.PacketFilterManager.removePacketListener(PacketFilterManager.java:462) ~[?:?]        at dev.lone.itemsadder.f.f.a.b.m.F(SourceFile:471) ~[?:?]
        at dev.lone.itemsadder.Main.onDisable(SourceFile:270) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1022]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:949) ~[patched_1.16.5.jar:git-Purpur-1022]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1022]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by LoneDev6** [comment]
update itemsadder and lonelibs

**Comment by dingods** [comment]
> update itemsadder and lonelibs

K

**Comment by LoneDev6** [comment]
K.
You're using an ancient version of ItemsAdder from Oct 9, 2020...
