### ISSUE TITLE
[BUG] ChunkLoadEvent

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#796]
**Describe the bug**
Spam in console
[12:10:38 ERROR]: Could not pass event ChunkLoadEvent to ItemsAdder v2.2.7
java.lang.NullPointerException: null
Suppongo succeda al caricamento di nuovi chunk

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Plugin version: 2.2.7

**Comment by RickyLaChow** [comment]
[16:01:19 ERROR]: Could not pass event ChunkLoadEvent to ItemsAdder v2.2.7
java.lang.NullPointerException: null
        at dev.lone.itemsadder.Core.f.a.b.b.b.c.b(SourceFile:495) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[server.jar:git-Paper-545]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:821) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:749) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:150) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1053) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1030) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1109) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$9(MinecraftServer.java:1208) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:118) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1207) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[server.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by RickyLaChow** [comment]
Forse risolto, ho pulito la cache

**Comment by LoneDev6** [comment]
> 
> 
> Forse risolto, ho pulito la cache

Please be careful cleaning the cache, it may create problems.

Per favore stai attento a pulire la cache, può creare dei problemi.

**Comment by LoneDev6** [comment]
Ti consiglio di ripristinare la cache da un backup.. e di cancellare solo il file `plugins\ItemsAdder\storage\cache\various\fixed_glitched_blocks.nbt`, come sicuramente c'è scritto nella parte alta del log.
Leggi sempre tutto il log
