### ISSUE TITLE
[BUG] Plugin crash after 30 minutes

### ISSUE THREAD

**Issue by GalaxyCrafted** [PluginBugs/Issues-ItemsAdder#802]
**Describe the bug**
After ca 30 minutes the plugin will crash competly with :  
[19:58:33] [Craft Scheduler Thread - 362/WARN]: java.lang.IllegalThreadStateException: InitializationException
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.Core.j.d.e.class.a(a:515)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.Core.h.a.a.class.a(a:253)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.k.b.a.a.b.class.a(a:963)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.Core.f.a.b.d.class.a(a:511)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.Core.f.a.b.d.class.a(a:880)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.k.b.g.e.class.a(a:818)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at dev.lone.itemsadder.Core.h.a.g.class.a(a:797)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:58:33] [Craft Scheduler Thread - 362/WARN]: 	at java.lang.Thread.run(Thread.java:748)

and if i do an command :  

[20:00:16] [Server thread/INFO]: Leo_Parden issued server command: /ia
[20:00:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v2.2.7 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1381) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-575]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Info (please complete the following information):**
 - Server version: 1.16.5.jar     Paper-575
 - Client version: 1.16.5
 - Plugin version: 2.2.7

**Comment by LoneDev6** [comment]
Please open a support ticket https://support.plugin.ga/
