### ISSUE TITLE
TNTPrimeEvent ItemsAdder v2.2.8 

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-ItemsAdder#803]
Error occurred while enabling ItemsAdder v2.2.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/destroystokyo/paper/event/block/TNTPrimeEvent
	at dev.lone.itemsadder.Core.f.a.b.b.b.c.<init>(SourceFile:125) ~[?:?]
	at dev.lone.itemsadder.Core.b.b(SourceFile:349) ~[?:?]
	at dev.lone.itemsadder.Core.b.<init>(SourceFile:218) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:258) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:544) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:918) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: com.destroystokyo.paper.event.block.TNTPrimeEvent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:3026-Spigot-79d53c2-d54b500]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 14 more

**Comment by LoneDev6** [comment]
send full server log

**Comment by LoneDev6** [comment]
will be fixed, thanks
