### ISSUE TITLE
[BUG] PlayerInteractEvent Error Printed upon Snowball Thrown

### ISSUE THREAD

**Issue by james-samios** [PluginBugs/Issues-ItemsAdder#824]
**Describe the bug**
A PlayerInteractEvent event error prints in Console after throwing a modified snowball itemstack (name and lore changed). It says something about a campfire. No in-game issues or anything broken. 

**To Reproduce**
This error occurred when I tried to throw a custom snowball (custom as in a modified ItemStack - not an ItemsAdder item).

**Expected behavior**
Snowball throws as expected but throws a PlayerInteractEvent error in console. 

**Info (please complete the following information):**
 - Server version: paper 1.16.5 (latest)
 - Client version: optifine 1.16.5
 - Plugin version: 2.2.12

**Additional context**
Error Message:
`java.lang.NullPointerException: null
        at dev.lone.itemsadder.Campfire.a.b(SourceFile:196) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-590]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:494) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489) ~[patched_1.16.5.jar:git-Paper-590]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:485) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2206) ~[?:git-Paper-590]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:31) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:9) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-590]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

**Comment by LoneDev6** [comment]
> I tried to throw a custom snowball (custom as in a modified ItemStack

I need to know what is this custom item.
run the /iatag command while holding the item in your hand and copy the text in console, then send it here

**Comment by james-samios** [comment]
Sure, here you go:

` {display:{Name:'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Paintball"}],"text":""}',Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"light_purple","text":"Throw this at the ground to change colour!"}],"text":""}']}}`

**Comment by LoneDev6** [comment]
thanks, this will be fixed
