### ISSUE TITLE
[BUG] Could not pass event EntityDeathEvent to ItemsAdder 2.3.0

### ISSUE THREAD

**Issue by antibitcoin** [PluginBugs/Issues-ItemsAdder#831]
**Describe the bug**
Error showing on console after updating to itemsadder 2.3.0

**To Reproduce**
[16:28:59 ERROR]: Could not pass event EntityDeathEvent to ItemsAdder v2.3.0
java.lang.NullPointerException: null
        at dev.lone.itemsadder.Core.h.a.b(SourceFile:47) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-591]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:829) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1598) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1520) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:317) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1184) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1989) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2396) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1381) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-591]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[16:29:00 ERROR]: Could not pass event EntityDeathEvent to ItemsAdder v2.3.0
java.lang.NullPointerException: null
        at dev.lone.itemsadder.Core.h.a.b(SourceFile:47) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-591]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-591]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:829) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1598) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1520) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:317) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1184) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1989) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2396) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1381) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-591]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-591]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Expected behavior**
No errors on console

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.3.0

**Additional context**
Help?

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/840
