### ISSUE TITLE
ItemAdder does not work at all. [BUG] 

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#834]
** Describe the bug **
Nothing works at all. No commands, Resource pack, NOTHING AT ALL! The console says that ItemAdder is installed, but none of it works. And it tells me that I don't have LightAPI installed, even though I have it in the plugins folder. I will copy the error in the console to ** Additional context **

** To Reproduce **
(I'm sorry I can't fill it out because I have nothing.)

** Expected behavior **
I thought it would work normally, but it doesn't work. I tried it first on version 1.16.5 and then on 1.16.1 and it didn't work on any of it.

** Screenshots **
![2021-04-16](https://user-images.githubusercontent.com/62265168/114982652-03bb0700-9e90-11eb-9ee1-f3e039ab0e4a.png)

** Information (please fill in the following information): **
  - Server version: CraftBukkit 1.16.5
  - Client version: Vanilla 1.16.5
  - Plugin version: ItemAdder: 2.3.0 LoneLibs: 1.0.9

** Additional context **
Here is a console all about ItemAdder and I note that I have LightAPI in the plugins folder!

[08:20:57] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.3.0
[08:20:58] [Server thread/INFO]: [ItemsAdder]
[08:20:58] [Server thread/INFO]:   ___  ___        __        __   __   ___  __      ItemsAdder 2.3.0
[08:20:58] [Server thread/INFO]: |  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.9
[08:20:58] [Server thread/INFO]: |  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     CraftBukkit 2991-Bukkit-f3f3094 (MC: 1.16.5)
[08:20:58] [Server thread/INFO]:
[08:20:58] [Server thread/INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: www.spigotmc.org/resources/48247/
[08:20:58] [Server thread/INFO]: [ItemsAdder] LibsDisguises not installed, please install it to make custom mobs working: ci.md-5.net/job/LibsDisguises/
[08:20:58] [Server thread/INFO]: [ItemsAdder] [Pack] Resourcepack folder: C:\Users\uzivatel\Desktop\testing\plugins\ItemsAdder\data\resource_pack
[08:20:58] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at dev.lone.itemsadder.Core.b.a(SourceFile:334) ~[?:?]
        at dev.lone.itemsadder.Core.b.<init>(SourceFile:220) ~[?:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:293) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:480) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:426) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:205) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:787) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[craftbukkit.jar:2991-Bukkit-f3f3094]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        ... 13 more
[08:20:58] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:20:58] [Server thread/INFO]: Done (19.633s)! For help, type "help"
[08:20:58] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder] [Pack] Checking for online default resourcepack updates...
[08:20:58] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] You can ignore this message: Can't connect to SpigotMC.org, probably internet connection is blocked.
[08:20:58] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] (Server returned HTTP response code: 503 for URL: https://www.spigotmc.org/members/781333/) - 781333
[08:20:58] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder] [Pack] Downloading default resourcepack...
[08:21:01] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder] [Pack] Downloaded default resourcepack
[08:21:01] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder] [Pack] Extracting default resources from default resourcepack
[08:21:04] [Craft Scheduler Thread - 3/INFO]: [ItemsAdder] [Pack]         DONE extracting resources from default resourcepack
[08:22:05] [User Authenticator #1/INFO]: UUID of player Vojtax_XX is 91718b94-230b-41f8-b55d-302b44441784
[08:22:05] [Server thread/INFO]: Vojtax_XX[/127.0.0.1:52774] logged in with entity id 446 at ([world]-180.5, 64.0, -234.5)
>op Vojtax_XX
[08:22:34] [Server thread/INFO]: Nothing changed. The player already is an operator
[08:22:46] [Server thread/INFO]: Vojtax_XX issued server command: /gamemode creative
[08:22:46] [Server thread/INFO]: [Vojtax_XX: Set own game mode to Creative Mode]
[08:22:59] [Server thread/INFO]: Vojtax_XX issued server command: /ia
[08:37:18] [Server thread/INFO]: Vojtax_XX issued server command: /iazip
[08:37:23] [Server thread/INFO]: Vojtax_XX issued server command: /ia help

**Comment by 100petr** [comment]
Try Spigot, Paper or others forks.

**Comment by TeiBri** [comment]
> Vyzkoušejte vidlice Spigot, Paper nebo jiné.
> Vyzkoušej Spigot, Paper nebo jiný fork
> (vidím tam českou zprávu, tak mi možná bude rozumět: D)

Ano rozumím ti moc dobře :DDDD Prosím ty děláš něco s tímhle pluginem? Umíš s ním aspoň trošku? Jestli jo nemáš discord?? :DDDDDD No nic. Úplně poprvé, co jsem si stáhnul tenhle plugin (1 den zpět), jsem ho dal na server SPIGOT a nefungovalo to :(.  Tobě to funguje? A jestli ano, jakou verzi a jaký fork používáš prosím? :D

**Comment by 100petr** [comment]
Pokud ti nefunguje tak prostě pošli log. Plugin používám už přes rok. DC: pitilon#6950 Na svém serveru využívám Purpur, ale měl by fungovat i na tom spigotuI'm sorry lonedev that he doesn't understand us 😂

**Comment by 100petr** [comment]
We connected on the discord and found out that it has a problem with version 2.3.20. https://pastebin.com/E1jYBEfc
Version 2.2.12 works for him

**Comment by LoneDev6** [comment]
> java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent

this is a very bad thing and surely means that they're running an old Spigot build.
Download it using BuildTools: https://www.youtube.com/watch?v=QdV-3OtXcPY
