### ISSUE TITLE
[BUG] Repeat this message

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-ItemsAdder#846]
- Server version: spigot 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.3.0
 [18:29:12] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [0;36;1m[Pack] Checking for online default resourcepack updates...[m
[18:29:12] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] [0;33;1mYou can ignore this message: Can't connect to SpigotMC.org, probably internet connection is blocked.[m
[18:29:12] [Craft Scheduler Thread - 1/INFO]: [ItemsAdder] (Server returned HTTP response code: 503 for URL: https://www.spigotmc.org/members/514374/) - 514374[m
[18:29:13] [Craft Scheduler Thread - 4/INFO]: [ItemsAdder] [0;32;1m[Pack] No need to download default resourcepack. Cached file is up to date[m
[18:29:13] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading YML files...[m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;33;1mUsed [0;36;1m568[0;33;1m/[0;36;1m6608[0;33;1m available max font_images. [m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading items_packs...[m
[18:29:14] [Server thread/WARN]: [ItemsAdder] Task #16 for ItemsAdder v2.3.0 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.server.v1_16_R3.ItemStack org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.getHandle()'
	at dev.lone.itemsadder.k.l.a.b.d.b(SourceFile:262) ~[?:?]
	at dev.lone.itemsadder.k.l.a.b.d.a(SourceFile:14) ~[?:?]
	at dev.lone.itemsadder.k.l.c.b(SourceFile:192) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.a(SourceFile:449) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.c(SourceFile:581) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.<init>(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:737) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:394) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:83) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1169) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading YML files...[m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;33;1mUsed [0;36;1m568[0;33;1m/[0;36;1m6608[0;33;1m available max font_images. [m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading items_packs...[m
[18:29:14] [Server thread/WARN]: [ItemsAdder] Task #16 for ItemsAdder v2.3.0 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.server.v1_16_R3.ItemStack org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.getHandle()'
	at dev.lone.itemsadder.k.l.a.b.d.b(SourceFile:262) ~[?:?]
	at dev.lone.itemsadder.k.l.a.b.d.a(SourceFile:14) ~[?:?]
	at dev.lone.itemsadder.k.l.c.b(SourceFile:192) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.a(SourceFile:449) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.c(SourceFile:581) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.<init>(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:737) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:394) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:83) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1169) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading YML files...[m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;33;1mUsed [0;36;1m568[0;33;1m/[0;36;1m6608[0;33;1m available max font_images. [m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading items_packs...[m
[18:29:14] [Server thread/WARN]: [ItemsAdder] Task #16 for ItemsAdder v2.3.0 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.server.v1_16_R3.ItemStack org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.getHandle()'
	at dev.lone.itemsadder.k.l.a.b.d.b(SourceFile:262) ~[?:?]
	at dev.lone.itemsadder.k.l.a.b.d.a(SourceFile:14) ~[?:?]
	at dev.lone.itemsadder.k.l.c.b(SourceFile:192) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.a(SourceFile:449) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.c(SourceFile:581) ~[?:?]
	at dev.lone.itemsadder.Core.e.h.<init>(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:737) ~[?:?]
	at dev.lone.itemsadder.Core.b.a(SourceFile:394) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:83) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1169) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3029-Spigot-79d53c2-e9ad7cb]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading YML files...[m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;33;1mUsed [0;36;1m568[0;33;1m/[0;36;1m6608[0;33;1m available max font_images. [m
[18:29:14] [Server thread/INFO]: [ItemsAdder] [0;36;1m[Init] Loading items_packs...[m

**Comment by LoneDev6** [comment]
will be fixed, thanks.
in the meantime use paper instead of spigot
