### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-ItemsAdder#860]
Server version: paper-1.16.5-621
Client version: 1.16.5
Plugin version: 2.3.4
Could not pass event InventoryClickEvent to ItemsAdder v2.3.4
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at dev.lone.itemsadder.Core.j.c.b.a(SourceFile:101) ~[?:?]
        at dev.lone.itemsadder.Core.j.c.c.a(SourceFile:166) ~[?:?]
        at dev.lone.itemsadder.Core.j.c.c.a(SourceFile:189) ~[?:?]
        at dev.lone.itemsadder.Core.j.c.c.j(SourceFile:279) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-621]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-621]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-621]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2701) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-621]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-621]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LoneDev6** [comment]
1. Do you have any idea of when this happens?
2. Can you send me the full log?

**Comment by HoneyBearc** [comment]
Oops, I found that it's because some other plugins... my fault, sorry to bother you.

**Comment by LoneDev6** [comment]
It's okay, no worries at all, which plugin?

**Comment by HoneyBearc** [comment]
ItemSoulBind
# Prevents anvil use with soul bound items
preventAnvil: true
