### ISSUE TITLE
[BUG] Could not pass event BlockBreakEvent to ItemsAdder v2.3.5 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by DesiVb** [PluginBugs/Issues-ItemsAdder#868]
ava.lang.NullPointerException: null
	at dev.lone.itemsadder.Core.h.a.g(SourceFile:89) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:106) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityPlayer.tick(EntityPlayer.java:452) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1425) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.World.a(World.java:1019) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1090) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1434) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1281) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[15:17:05] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.3.5
java.lang.NullPointerException: null
	at dev.lone.itemsadder.Core.h.a.g(SourceFile:89) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:106) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityPlayer.tick(EntityPlayer.java:452) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1425) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.World.a(World.java:1019) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1090) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1434) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1281) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[15:17:05] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ItemsAdder v2.3.5
java.lang.NullPointerException: null
	at dev.lone.itemsadder.Core.h.a.b(SourceFile:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:808) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1501) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1430) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1272) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.damageEntity(EntityInsentient.java:278) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1129) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1837) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2274) ~[?:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1197) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1272) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[15:17:06] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.3.5
java.lang.NullPointerException: null
	at dev.lone.itemsadder.Core.h.a.g(SourceFile:89) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:310) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:270) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1504) ~[?:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1197) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1272) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by LoneDev6** [comment]
Please check your logs on the top, a loot failed to load.
