### ISSUE TITLE
[BUG] 632/ERROR

### ISSUE THREAD

**Issue by GlobusOk** [PluginBugs/Issues-ItemsAdder#869]
[22:55:35] [Craft Scheduler Thread - 632/ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.IllegalStateException: ResourcePackSendEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at dev.lone.itemsadder.n.i.a(SourceFile:29) ~[?:?]
        at dev.lone.itemsadder.l.e.onPacketSending(SourceFile:64) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:194) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:164) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:191) ~[?:?]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1680) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1653) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:71) ~[?:?]
        at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:84) ~[?:?]
        at net.minecraft.server.v1_16_R3.EntityPlayer.setResourcePack(EntityPlayer.java:1705) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.setResourcePack(CraftPlayer.java:1275) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at dev.lone.itemsadder.l.b.G(SourceFile:722) ~[?:?]
        at dev.lone.itemsadder.l.a.F(SourceFile:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:3037-Spigot-a25e8ed-c85efa8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by LoneDev6** [comment]
Will be fixed, thanks

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/871
