### ISSUE TITLE
[BUG] Cannot pass PlayerInteractEvent to ItemsAdder

### ISSUE THREAD

**Issue by Zangerine** [PluginBugs/Issues-ItemsAdder#878]
**Describe the bug**
Cannot pass PlayerInteractEvent to ItemsAdder

**Plugin Version**
2.3.6

`[20:31:58] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.3.6
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryAllValues(FlagValueCalculator.java:268) ~[?:?]
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryValue(FlagValueCalculator.java:223) ~[?:?]
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryState(FlagValueCalculator.java:170) ~[?:?]
	at com.sk89q.worldguard.protection.RegionResultSet.queryState(RegionResultSet.java:97) ~[?:?]
	at com.sk89q.worldguard.protection.regions.RegionQuery.queryState(RegionQuery.java:239) ~[?:?]
	at com.sk89q.worldguard.protection.regions.RegionQuery.testState(RegionQuery.java:194) ~[?:?]
	at dev.lone.itemsadder.Core.OtherPlugins.c.b.a(SourceFile:121) ~[?:?]
	at dev.lone.itemsadder.Core.OtherPlugins.c.a.a(SourceFile:267) ~[?:?]
	at dev.lone.itemsadder.Core.OtherPlugins.c.a.d(SourceFile:240) ~[?:?]
	at dev.lone.itemsadder.Core.f.a.b.n.m(SourceFile:144) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:531) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1768) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:31) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1441) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by LoneDev6** [comment]
Will be fixed in the next update
