### ISSUE TITLE
[BUG] ClassCastException in Physics event

### ISSUE THREAD

**Issue by PhanaticD** [PluginBugs/Issues-ItemsAdder#890]
**Describe the bug**
```
[11:38:14 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.3.7
java.lang.ClassCastException: class dev.lone.itemsadder.Core.e.d cannot be cast to class dev.lone.itemsadder.Core.e.l (dev.lone.itemsadder.Core.e.d and dev.lone.itemsadder.Core.e.l are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5f376e1f)
        at dev.lone.itemsadder.Core.f.a.b.b.b.b.a(SourceFile:117) ~[?:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b.b.a(SourceFile:53) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1090]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1090]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1090]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.a(World.java:878) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:837) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.WorldServer.update(WorldServer.java:3037) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.notifyAndUpdatePhysics(World.java:748) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.a(World.java:714) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:622) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.World.a(World.java:785) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.BlockFire.trySpread(BlockFire.java:296) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.BlockFire.tickAlways(BlockFire.java:206) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:676) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:1477) ~[patched_1.16.5.jar:git-Purpur-1090]
        at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:309) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:59) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1064) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1563) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1090]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1090]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```
**To Reproduce**
not sure, I was just flying around the world

**Expected behavior**
no error

**Screenshots**
no screenshot

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2) purpur 1.16.5
 - Client version: (example: fabric 1.15.2) 1.16.5
 - Plugin version: (example: 2.0.9 do not write "latest") 2.3.7

**Additional context**

**Comment by LoneDev6** [comment]
hello, please check if any of the itemsadder items/blocks failed to load, it may be the cause
