### ISSUE TITLE
Occurred in Dungeons XL. Spam error due to world regeneration

### ISSUE THREAD

**Issue by mA0w0** [PluginBugs/Issues-ItemsAdder#907]
Occurred in Dungeon XL.
When played with a plugin that can create dungeons, DXL will generate a clone world and the world will be deleted when the play is over.
ItemsAdder is trying to read a file in that world and the file has been deleted, which can result in an unresolved spam error.

ItemsAdder - 2.3.8
DungeonsXL - #1100
paper - 1.16.5-714

> [13:40:09 ERROR]: [ItemsAdder] Error saving region file: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_liquids\r.-1.0.nbt
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:40:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:40:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:40:09 WARN]: java.io.FileNotFoundException: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_liquids\r.-1.0.nbt (The specified path can not be found.)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
[13:40:09 WARN]:        at dev.lone.itemsadder.k.n.d.an(SourceFile:45)
[13:40:09 WARN]:        at dev.lone.itemsadder.Core.f.a.c.b.b.an(SourceFile:238)
[13:40:09 WARN]:        at dev.lone.itemsadder.Core.f.a.c.c.f(SourceFile:60)
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:40:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:40:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:40:09 ERROR]: [ItemsAdder] Error saving region file: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_blocks\r.-1.0.nbt
[13:40:09 WARN]: java.io.FileNotFoundException: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_blocks\r.-1.0.nbt (The specified path can not be found.)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[13:40:09 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
[13:40:09 WARN]:        at dev.lone.itemsadder.k.n.d.an(SourceFile:45)
[13:40:09 WARN]:        at dev.lone.itemsadder.Core.f.a.c.b.b.an(SourceFile:238)
[13:40:09 WARN]:        at dev.lone.itemsadder.Core.f.a.c.c.f(SourceFile:60)
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:40:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:40:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:40:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:40:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:40:19 ERROR]: [ItemsAdder] Error saving region file: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_liquids\r.0.0.nbt
[13:40:19 ERROR]: [ItemsAdder] Error saving region file: D:\Minecraft\1.16.5\.\DXL_Game_0\region_custom_blocks\r.-1.0.nbt
[13:40:19 WARN]: java.io.FileNotFoundException: D:\Minecraft\1.16.5\.\DXL_Game_1\region_custom_liquids\r.0.0.nbt (The specified path can not be found.)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
[13:40:19 WARN]:        at dev.lone.itemsadder.k.n.d.an(SourceFile:45)
[13:40:19 WARN]:        at dev.lone.itemsadder.Core.f.a.c.b.b.an(SourceFile:238)
[13:40:19 WARN]:        at dev.lone.itemsadder.Core.f.a.c.c.f(SourceFile:60)
[13:40:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:40:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:40:19 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:40:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:40:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:40:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:40:19 WARN]: java.io.FileNotFoundException: D:\Minecraft\1.16.5\.\DXL_Game_0\region_custom_blocks\r.-1.0.nbt (The specified path can not be found.)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[13:40:19 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
[13:40:19 WARN]:        at dev.lone.itemsadder.k.n.d.an(SourceFile:45)
[13:40:19 WARN]:        at dev.lone.itemsadder.Core.f.a.c.b.b.an(SourceFile:238)
[13:40:19 WARN]:        at dev.lone.itemsadder.Core.f.a.c.c.f(SourceFile:60)
[13:40:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:40:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:40:19 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:40:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:40:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:40:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mA0w0** [comment]
It was already created in #904
