### ISSUE TITLE
Jukebox error

### ISSUE THREAD

**Issue by Tenitrex** [PluginBugs/Issues-ItemsAdder#932]
When I insert a custom music disc to the jukebox everything works fine, the music plays, but when I try to take the disk out that's where the fun begins .. Jukebox gets muted but still plays music and the console throws an error every time i click on it.

`[01.06 21:41:50] [Server] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.3.9
[01.06 21:41:50] [Server] org.bukkit.event.EventExceptionnull
[01.06 21:41:50] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:494) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:479) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1504) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1037) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[01.06 21:41:50] [Server] Caused byjava.lang.NoSuchMethodError: net.minecraft.server.v1_16_R3.ItemStack.fromCompound(Lnet/minecraft/server/v1_16_R3/NBTTagCompound;)Lnet/minecraft/server/v1_16_R3/ItemStack;
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.k.n.a.b.d.a(SourceFile:349) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.k.n.a.b.d.b(SourceFile:16) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.k.n.e.a(SourceFile:92) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.Core.f.a.c.b.a.a(SourceFile:61) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.Core.f.a.b.j.a(SourceFile:152) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.Core.f.a.b.j.a(SourceFile:144) ~[?:?]
[01.06 21:41:50] [Server] 	at dev.lone.itemsadder.Core.f.a.b.j.j(SourceFile:117) ~[?:?]
[01.06 21:41:50] [Server] 	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source) ~[?:?]
[01.06 21:41:50] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
[01.06 21:41:50] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
[01.06 21:41:50] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3090-Spigot-9fb885e-90a4d64]
[01.06 21:41:50] [Server] 	... more
[01.06 21:42:10] [Multicraft] Auto-saving world...
[01.06 21:42:10] [Server] [Server thread/INFO]: Saving is already turned on
[01.06 21:42:10] [Server] [Server thread/INFO]: Saving the game (this may take a moment!)
[01.06 21:42:10] [Server] [Server thread/INFO]: Saved the game
[01.06 21:48:20] [Server] [Server thread/INFO]: Antidotas issued server command: /fly
[01.06 21:48:23] [Server] [Server thread/INFO]: Antidotas issued server command: /heal
[01.06 21:48:46] [Disconnect] Antidotas has disconnected, reasonDisconnected
[01.06 21:48:46] [Server] [Server thread/INFO]: Antidotas left the game`

**Comment by LoneDev6** [comment]
post the complete server log as file or using pastebin.

also you erased the whole issue template for no reason, i need all the info asked to identify the issue
