### ISSUE TITLE
[BUG] ERROR]: Could not pass event ChunkUnloadEvent to ItemsAdder v2.3.10

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#945]
Good evening, I have installed the latest version and I have again the errors in the server console.
I don't know how to give a procedure to get them, they happen even if I don't do anything special. I just used a warp and I saw the errors afterwards, so I made another warp nothing I came back to the same nothing so I don't know how to reproduce.
I see that it is noted "Chunk" but also that it is related to LibsDisguise as with 2.3.9, so I used LibsDisguise 937 then when it came out the 938 but it's the same.

**ItemsAdder v2.3.10 + LibsDisguises v10.0.25-SNAPSHOT 937 :**

>.... [08:22:23 INFO]: vdl19 lost connection: Disconnected
>.... [08:22:23 INFO]: vdl19 left the game
>.... [08:22:33 ERROR]: Could not pass event ChunkUnloadEvent to ItemsAdder v2.3.10
java.lang.NoSuchMethodError: 'java.util.LinkedHashMap me.libraryaddict.disguise.disguisetypes.Disguise.getCustomData()'
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:170) ~[?:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:373) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1055.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-769]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:906) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$7(PlayerChunk.java:609) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:619) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1072) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:762) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.Thread.run(Thread.java:834) [?:?]
>.... [08:22:33 ERROR]: Could not pass event ChunkUnloadEvent to ItemsAdder v2.3.10
java.lang.NoSuchMethodError: 'java.util.LinkedHashMap me.libraryaddict.disguise.disguisetypes.Disguise.getCustomData()'
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:170) ~[?:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:373) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1055.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-769]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:906) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$7(PlayerChunk.java:609) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:619) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1072) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:762) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.Thread.run(Thread.java:834) [?:?]

**ItemsAdder v2.3.10 + LibsDisguises v10.0.25-SNAPSHOT 938 :**

>.... [21:20:37 ERROR]: Could not pass event ChunkUnloadEvent to ItemsAdder v2.3.10
java.lang.NoSuchMethodError: 'java.util.LinkedHashMap me.libraryaddict.disguise.disguisetypes.Disguise.getCustomData()'
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:170) ~[?:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:373) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1094.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-769]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:906) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$7(PlayerChunk.java:609) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:619) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:763) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.Thread.run(Thread.java:834) [?:?]
>.... [21:20:37 ERROR]: Could not pass event ChunkUnloadEvent to ItemsAdder v2.3.10
java.lang.NoSuchMethodError: 'java.util.LinkedHashMap me.libraryaddict.disguise.disguisetypes.Disguise.getCustomData()'
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:170) ~[?:?]
at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:373) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1094.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-769]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-769]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:906) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$7(PlayerChunk.java:609) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:619) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:763) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-769]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-769]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Info (please complete the following information):**
 - Server version:  Paper 1.16.5 #769
 - Plugin version: 2.3.10 + LibsDisguise #937 & #938

**Comment by LoneDev6** [comment]
update libsdisguises
