### ISSUE TITLE
[BUG] Doesn't work - 1.17 beta

### ISSUE THREAD

**Issue by myk3sr** [PluginBugs/Issues-ItemsAdder#979]
**Describe the bug**
Doesn't load, I'm assuming it's beta and a paper 1.17 compatibility issue from reading the output, but also some error?

**To Reproduce**
1. Copy jar to plugins folder
2. Fails to run
3. Output from console says unloaded

**Expected behavior**
Normal operation

**Server Output**
04:42:42 INFO]: [ItemsAdder] Enabling ItemsAdder v2.4.0
04:42:42 ERROR]: Error occurred while enabling ItemsAdder v2.4.0 (Is it up to date?)
ava.lang.NoSuchFieldError: MC1_17_R1
at dev.lone.itemsadder.k.a.ah(SourceFile:11) ~[?:?]
at dev.lone.itemsadder.Main.onEnable(SourceFile:153) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-46]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-
6]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper
46]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-4
]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-
6]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Pa
er-46]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]
at java.lang.Thread.run(Thread.java:831) [?:?]
04:42:42 INFO]: [ItemsAdder] Disabling ItemsAdder v2.4.0.

**Info (please complete the following information):**
 - Server version:  paper 1.17
 - Client version: n/a
 - Plugin version: 2.4.0

**Additional context**
I understand 1.17 is relatively new, a lot has changed, java 16 is new format also, hopefully it can be worked out?

**Comment by 100petr** [comment]
what version of lonelibs do you have?

**Comment by myk3sr** [comment]
Should be the latest.. been keeping up with them since 1.17 using latest dev builds until stable branch posted

**Comment by 100petr** [comment]
and protocollib version? I'm just updating the server to 1.17 and it works for me in purpur.

**Comment by myk3sr** [comment]
i re-installed everything now here....

[23:13:32 INFO]: Myk3sr issued server command: /iazip
[23:13:32 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'iazip' in plugin ItemsAdder v2.4.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.jar:git-Paper-46]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-46]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Pape
r-46]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:218
5) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1996)
~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1977)
~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper
-46]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Pape
r-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]

        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by 100petr** [comment]
can you send full log?

**Comment by myk3sr** [comment]
i used all versions of depemds linked in the install guide

**Comment by myk3sr** [comment]
[23:07:20 INFO]: [ItemsAdder] Enabling ItemsAdder v2.4.0
[23:07:20 ERROR]: Error occurred while enabling ItemsAdder v2.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/FieldUtils
        at dev.lone.itemsadder.k.o.a.a.j.<clinit>(SourceFile:19) ~[?:?]
        at dev.lone.itemsadder.k.o.a.b(SourceFile:31) ~[?:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:173) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-46]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-
46]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper
-46]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-4
6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-
46]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Pa
per-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]

        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.FieldUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-
46]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-4
6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more
[23:07:20 INFO]: [ItemsAdder] Disabling ItemsAdder v2.4.0

**Comment by LoneDev6** [comment]
Update LoneLibs, install ProtocolLib, update Spigot
