### ISSUE TITLE
Unknown Bucket Window Error

### ISSUE THREAD

**Issue by ninesik** [PluginBugs/Issues-ItemsAdder#985]
[22:14:21 ERROR]: Could not pass event NotePlayEvent to ItemsAdder v2.4.0
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "<local3>" is null
        at dev.lone.itemsadder.k.b.a.f.a(SourceFile:42) ~[?:?]
        at dev.lone.itemsadder.k.b.a.a(SourceFile:79) ~[?:?]
        at dev.lone.itemsadder.Core.e.a.c.a(SourceFile:362) ~[?:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b.f.a(SourceFile:278) ~[?:?]
        at dev.lone.itemsadder.Core.f.a.b.b.b.f.a(SourceFile:87) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.jar:git-Purpur-1206]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callNotePlayEvent(CraftEventFactory.java:1384) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.world.level.block.NoteBlock.play(NoteBlock.java:66) ~[?:?]
        at net.minecraft.world.level.block.NoteBlock.neighborChanged(NoteBlock.java:54) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.neighborChanged(BlockBehaviour.java:876) ~[?:?]
        at net.minecraft.world.level.Level.neighborChanged(Level.java:863) ~[?:?]
        at net.minecraft.world.level.Level.updateNeighborsAtExceptFromFacing(Level.java:842) ~[?:?]
        at net.minecraft.world.level.block.ObserverBlock.updateNeighborsInFront(ObserverBlock.java:85) ~[?:?]
        at net.minecraft.world.level.block.ObserverBlock.tick(ObserverBlock.java:61) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:919) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1159) ~[?:?]
        at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:807) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.jar:git-Purpur-1206]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1206]
        at java.lang.Thread.run(Thread.java:831) [?:?]

https://drive.google.com/file/d/1EjrUm6ioH29lwGVWxxWFvkrgveKI-0nT/view?usp=sharing

my data pack

**Comment by LoneDev6** [comment]
Don't erase the issue template, provide all the asked info and also make sure to update spigot to the latest version.
