### ISSUE TITLE
[BUG] Error code after player gets kicked

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#988]
**Describe the bug**

**To Reproduce**
1. Let players kick that aren't allowing the download of the rp
2. Watch the error in console

**Expected behavior**
No error message

**Screenshots**

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: ---
 - Plugin version: 2.3.12

**Additional context**
[28.06 21:53:07.900] INFO: [Earth-1] [21:52:15 ERROR]: Could not pass event PlayerResourcePackStatusEvent to ItemsAdder v2.3.12
[28.06 21:53:07.900] INFO: [Earth-1] org.bukkit.event.EventException: null
[28.06 21:53:07.900] INFO: [Earth-1]    at org.mcnative.runtime.bukkit.plugin.McNativePluginWrapperLoader.lambda$registerMethods$1(McNativePluginWrapperLoader.java:116) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1808) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.PacketPlayInResourcePackStatus.a(SourceFile:30) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.PacketPlayInResourcePackStatus.a(SourceFile:8) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at java.lang.Thread.run(Thread.java:829) [?:?]
[28.06 21:53:07.900] INFO: [Earth-1] Caused by: java.lang.IllegalArgumentException: cannot send packets to a closed channel
[28.06 21:53:07.900] INFO: [Earth-1]    at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[paper.jar:git-Paper-629]
[28.06 21:53:07.900] INFO: [Earth-1]    at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:739) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:731) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:399) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:733) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:687) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at dev.lone.itemsadder.k.j.a.a(SourceFile:110) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at dev.lone.itemsadder.k.j.a.d.b(SourceFile:18) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at dev.lone.itemsadder.k.j.a.G(SourceFile:62) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at dev.lone.itemsadder.l.h.M(SourceFile:120) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at dev.lone.itemsadder.l.d.a(SourceFile:228) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at jdk.internal.reflect.GeneratedMethodAccessor415.invoke(Unknown Source) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    at org.mcnative.runtime.bukkit.plugin.McNativePluginWrapperLoader.lambda$registerMethods$1(McNativePluginWrapperLoader.java:114) ~[?:?]
[28.06 21:53:07.900] INFO: [Earth-1]    ... 18 more

**Comment by LoneDev6** [comment]
This is very rare, also you're using McNative which is not official.
Anyway a future update may fix this issue
